### ISSUE TITLE
GM_XHR in fetch mode doesn't support timeout

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#1002]
GM_XHR in fetch mode already supports `abort()`, and combining it with `setTimeout` should allow implementing the timeout.

## Expected Behavior
The script prints message about a timeout in the console.

## Actual Behavior
The script prints Response object with a successfully finished request.

## Specifications

Chromium: Version 83.0.4103.97 (Official Build) Arch Linux (64-bit)
TM: beta, 4.11.6116
OS: KDE Manjaro (64-bit)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Test GM_XHR-fetch timeout
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*
// @grant        GM_xmlhttpRequest
// @connect      httpbin.org
// ==/UserScript==

(() => {
    GM_xmlhttpRequest({
        fetch: true,
        url: "https://httpbin.org/delay/2",
        timout: 1000,
        ontimout: (err) => console.log("timeout:", err),
        onload: (resp) => console.log("resp:", resp),
        onerror: (err) => console.error("error:", err),
    });
})();
```

**Comment by derjanb** [comment]
Should be fixed at 4.11.6117
