### ISSUE TITLE
[Bug] Script website list not showing on screen

### ISSUE THREAD

**Issue by wuniversales** [Tampermonkey/tampermonkey#1004]
## Expected Behavior
It should display the icons of the three websites that the script supports.

## Actual Behavior
It only shows the icon of a website " https://golden-tea.me/* "
![imagen](https://user-images.githubusercontent.com/48658161/87855696-31cbe480-c91a-11ea-8003-cb94f3152060.png)

## Specifications

- Firefox: (V 78.0.2, 64 bits)
- TM: 4.11.6114
- OS: (Manjaro linux, latest version)

## Script

```js
// ==UserScript==
// @name         Golden Tea (Bot)
// @icon         https://golden-tea.me/assert/images/favicon.ico
// @version      0.1
// @description  Script automatizado para Golden Tea, configuralo segun tus gustos.
// @author       test
// @namespace    https://greasyfork.org/
// @include      https://golden-tea.me/*
// @include      https://golden-tea.com/*
// @include      https://golden-tea.cc/*
// @require      https://cdn.jsdelivr.net/npm/jquery@1.9.1/jquery.min.js
// @require      https://greasyfork.org/scripts/37236-monkeyconfig/code/MonkeyConfig.js
// @grant        GM_Config
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_addStyle
// @grant        GM_registerMenuCommand
// ==/UserScript==
```

**Comment by derjanb** [comment]
Should be fixed at 4.19.6180 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
