### ISSUE TITLE
Blocking PDFs from loading as preview in Canvas

### ISSUE THREAD

**Issue by cjhays1** [Tampermonkey/tampermonkey#1009]
(Please fill out the issue template with your details)

## Specifications

- Google Chrome 84.0.4147.105 (Official Build) (64-bit)
- OS: macOS Catalina 10.15.6

Without Tampermonkey:
![image](https://user-images.githubusercontent.com/69335602/89607771-4debe300-d841-11ea-8299-09727c157781.png)
(Contact info removed)

With Tampermonkey:
![image](https://user-images.githubusercontent.com/69335602/89607807-652ad080-d841-11ea-80be-89ef5a57b544.png)

**Comment by derjanb** [comment]
Should be fixed now.
