### ISSUE TITLE
Suggest Tampermonkey to become Recommended extensions

### ISSUE THREAD

**Issue by yingziwu** [Tampermonkey/tampermonkey#1011]
I noticed that Tampermonkey  is not the [recommended extension](https://support.mozilla.org/en-US/kb/recommended-extensions-program) of Firefox. 
So if you install [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) on firefox, you will see the warning: `This is not monitored for security through Mozilla's Recommended Extensions program. Make sure you trust it before installing.` 
I don't know if you tried to email amo-featured@mozilla.org to suggest Tampermonkey to become recommended. I think becoming the recommended extension is very necessary. After becoming recommended, Tampermonkey will not only be recommended to Firefox users, but also remove the unsafe warning.

**Comment by derjanb** [comment]
In the end it is up to the Mozilla folks, but they done a first step by making Tampermonkey available at Firefox Android Nightly.
