### ISSUE TITLE
can‘t match https://forum.xda-developers.com

### ISSUE THREAD

**Issue by bAdOoWindy** [Tampermonkey/tampermonkey#1012]
(Please fill out the issue template with your details)

## Specifications

Firefox 79.0 (20200720193547)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         XDA width fix
// @namespace    https://space.bilibili.com/6727237
// @version      0.1
// @author       尺子上的彩虹
// @match        https://forum.xda-developers.com
// @grant        none
// @description:zh-cn XDA header width fix
// ==/UserScript==

document.getElementsByTagName('header')[0].style.width='zpx';

```
code is simple , but can't match ? is nothing.

**Comment by yingziwu** [comment]
"zpx" is a ivalid property value.
You should use  `console.log` to test whether the script is running.

Tampermonkey work well and you can try following script.

```javascript
// ==UserScript==
// @name         XDA width fix
// @namespace    https://space.bilibili.com/6727237
// @version      0.1
// @author       尺子上的彩虹
// @match        https://forum.xda-developers.com
// @grant        none
// @description:zh-cn XDA header width fix
// ==/UserScript==

(()=>{
    document.getElementsByTagName('header')[0].style.width='50%';
    console.log("Tampermonky");
})();
```

**Attention:**
``// @match        https://forum.xda-developers.com`` mean the script only work on the page https://forum.xda-developers.com . 
If you need the script work on entire site, you need to use ``// @match        https://forum.xda-developers.com/*``
