### ISSUE TITLE
Tampermonkey loses all scripts.

### ISSUE THREAD

**Issue by Dra9o** [Tampermonkey/tampermonkey#1013]
After using cleaning utilities which delete file
`\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\000003.log`
Is it truth that scripts are stored in 000003.log?

**Comment by derjanb** [comment]
No, this is just a log file. However, you might be able to recover them by manually copying values from this file.
