### ISSUE TITLE
很抱歉

### ISSUE THREAD

**Issue by zendeyaozheyangzima** [Tampermonkey/tampermonkey#1015]
很抱歉打扰到您 ，我很想捐赠与你  但是没有渠道   你知道国内只用支付宝 或者微信   我没有那么好的电脑   苹果手机我也买不起   我们很多人都用安卓手机   我很想你们出一款支持安卓的扩展    您的产品真的很棒！ 再次感谢你！25604499
```

**Comment by shakeelmajeed-work** [comment]
怎么了？

**Comment by derjanb** [comment]
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-670414131 😔
