### ISSUE TITLE
Scripts can't run on specific websites after Firefox restarts

### ISSUE THREAD

**Issue by li-zyang** [Tampermonkey/tampermonkey#1016]
## Expected Behavior
Scripts runs in all of the non-reserved sites

## Actual Behavior
Scripts didn't run in some sites (e.g. [Shimo doc](https://shimo.im/)).   
I can't see console output given by my scripts and the global variables set by the scripts. The control panel shows they had run, however. The same problem didn't happen on websites who sets CSP (e.g. Github) after I set `Security -> Modify existing content security policy (CSP) headers` to `Remove entirely`, so it seems not the fault of CSP.
It seems only happen on v4.11.6118 BETA version. When I switched back to the official version v4.11.6117 (keeping the setting) everything seems OK.

## Specifications

- Firefox 79.0 (64-bit) (latest)
- TM: 4.11.6118 (BETA)
- OS: Windows 10 1803

## Script

```js
// ==UserScript==
// @name         an-example-script
// @namespace    https://github.com/li-zyang
// @version      0.1.0
// @description  An example script
// @include      https://shimo.im/*
// @exclude      none
// @require      https://cdn.staticfile.org/jquery/3.4.1/jquery.min.js
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_deleteValue
// @grant        GM_addValueChangeListener
// @connect      *
// @noframes
// @run-at       document-end
// @note         v1.0.0      1970-01-01  Add your release notes here.
// ==/UserScript==

(function(window, $) {
  'use strict';

  window.anExampleScriptJS = {};
  var s = anExampleScriptJS;

  console.log("I'm here!");

})(window.unsafeWindow, $);

// and <anExampleScriptJS> variable is not available in the console, nor the "I'm here!" was seen
```

## My Tampermonkey setting
```json
{"created_by":"Tampermonkey","version":"1","settings":{"script_blacklist_server":[{"severity":"2","rules":["/https?:\\/\\/userscripts\\.org\\/scripts\\/(source|version)/(102614).*\\.user\\.js/"]},{"name":"SaveFrom.net helper","severity":"3","rules":["/https?:\\/\\/sf-addon\\.com\\/.*\\/.*\\.user\\.js/","/https?:\\/\\/.*\\.sf-helper\\.com\\/.*\\.user\\.js/"],"reason":"Shows advertisements"},{"severity":"8","reasons":{"en":"Used for a phishing compain to compromise users of baon-nutrition.com"},"rules":["/https?:\\/\\/files\\.ulysse\\.travel\\/.*\\.user\\.js/"]}],"configMode":100,"layout":"default#dark","layout_user_css":"::selection {\n  background: rgba(127, 127, 127, 0.3);\n  color: currentColor;\n}\nhtml, body {\n  background: #202020\n}\nhtml {\n  overflow: hidden;\n}\n.script_tab_head {\n  /* display: none; */\n}\n.head_container a :first-child img {\n  width: 15px;\n  height: 15px;\n}\n.head_container a :nth-child(2) {\n  display: flex;\n  flex-direction: row;\n}\n.header_title {\n  font-size: 15px;\n  bottom: 4px;\n  position: relative;\n}\n.version {\n  position: relative;\n  left: 15px;\n}\n.tv_container_fit {\n  top: 30px;\n}\n.nameNicon64 {\n  width: 100px;\n}\n.tv_contents {\n  position: relative;\n  top: -1px;\n}\n.tv_tab {\n  font-size: 1em;\n  padding: .3em 1em .3em 1em;\n  height: 30px;\n}\n.tv_tabs_table {\n  padding: 0 0px 0 0px;\n}\n.tv_tabs_table_alt {\n  left: 40px;\n}\ntextarea {\n  height: 300px;\n  padding: 5px 5px 5px 5px;\n}\n.settingsth, \nth.script_sel {\n  position: sticky;\n  top: 0px;\n  background: #202020;\n  z-index: 10000\n}\n* {\n  scrollbar-color: #4d4d4d #2e2e2e;\n}\n.cm-s-monokai .CodeMirror-gutters {\n  background: #30312a !important;\n  border-right: 0 !important;\n}\n.CodeMirror-linenumber {\n  min-width: 2.5em;\n}\n.CodeMirror-lint-marker-warning,\n.CodeMirror-lint-marker-error {\n  left: calc(-3.2em - 8px);\n}\n.CodeMirror-lint-markers {\n  width: 0px;\n}\n.CodeMirror-gutter-background.CodeMirror-activeline-gutter {\n  background: #3e3d32;\n}\n.CodeMirror-activeline .CodeMirror-gutter-wrapper .CodeMirror-linenumber {\n  background-color: transparent;\n  color: #d0d0d0;\n}\n.CodeMirror-scrollbar-filler, .CodeMirror-gutter-filler {\n  background-color: transparent;\n}\n.dark .editormenu {\n  background-color: #222222;\n  color: #c0c0c0;\n}\n.editor_border {\n  border: none;\n  padding: 0;\n}\n.dark .tr_content {\n  background-color: transparent;\n}\n.dark textarea, .dark input, .dark button, .dark select, .dark option {\n  filter: none;\n  background: #1c1c1c;\n  border: 2px solid transparent;\n  color: #c0c0c0;\n}\n.dark button[disabled],\ninput[type=\"button\"][disabled] {\n  color: #888888;\n}\nbutton,\ninput[type=\"button\"],\ncheckbox,\ninput[type=\"checkbox\"],\nradio,\ninput[type=\"radio\"],\nselect,\ninput[type=\"select\"],\noption {\n  cursor: pointer;\n}\nbutton[disabled],\ninput[type=\"button\"][disabled],\ncheckbox[disabled],\ninput[type=\"checkbox\"][disabled],\nradio[disabled],\ninput[type=\"radio\"][disabled],\nselect[disabled],\ninput[type=\"select\"][disabled],\noption[disabled] {\n  cursor: not-allowed;\n}\ncheckbox,\ninput[type=\"checkbox\"],\nradio,\ninput[type=\"radio\"] {\n  filter: invert(100%) contrast(70%);\n}\n.dark .tv_content {\n  background-color: transparent;\n}\n.dark .tr_tabs_alt {\n  background-color: transparent !important;\n}\n.dark .script_tab_head {\n  background: #2a2a2a;\n}\n.CodeMirror-foldmarker {\n  color: darkkhaki;\n  text-shadow: none;\n  border-bottom: 1px dashed currentColor;\n}\n.global_hint_information > span {\n  background-color: rgba(122, 149, 188, 0.86);\n}\n","notification_showUpdate":"changelog","favicon_service":"google","webrequest_fixCSP":"remove","webrequest_modHeaders":"yes","script_file_access":"off","external_connect":"all","require_sri_mode":"supported","connect_mode":"ask","page_filter_mode":"black","page_whitelist":["/https?:\\/\\/greasyfork\\.org\\/.*/","http://xkcd.com/970/"],"forbiddenPages":["*example.org/*","*paypal.tld/*","*stripe.com/*","https://*deutsche-bank-24.tld/*","https://*bankofamerica.tld/*","/^.*:\\/\\/apis\\.google\\.com\\/((?!render)([^\\/]+)\\/)+([^\\/]+)?$/","*://www.facebook.com/plugins/*","*://platform.twitter.com/widgets/*"],"editor_enabled":true,"editor_theme":"monokai","editor_fontSize":"100","editor_keyMap":"sublime","editor_indentUnit":"2","editor_indentWithTabs":"spaces","editor_tabMode":"classic","editor_lineWrapping":false,"editor_electricChars":true,"editor_autoSave":false,"editor_easySave":true,"editor_highlightTrailingWhitespace":false,"editor_trimTrailingSpacesFromModifiedLines":false,"editor_autoLint":false,"editor_autoLintMaxLen":"300000","editor_linter_config":{"globals":{"$":"writable","uneval":"writeable","unsafeWindow":"writeable","TM_info":"writeable","GM_info":"writeable","GM":"writeable","GM_addStyle":"writeable","GM_deleteValue":"writeable","GM_listValues":"writeable","GM_getValue":"writeable","GM_download":"writeable","GM_log":"writeable","GM_registerMenuCommand":"writeable","GM_unregisterMenuCommand":"writeable","GM_openInTab":"writeable","GM_setValue":"writeable","GM_addValueChangeListener":"writeable","GM_removeValueChangeListener":"writeable","GM_xmlhttpRequest":"writeable","GM_getTab":"writeable","GM_setTab":"writeable","GM_saveTab":"writeable","GM_getTabs":"writeable","GM_setClipboard":"writeable","GM_notification":"writeable","GM_getResourceText":"writeable","GM_getResourceURL":"writeable"}},"action_menu_scripts_hide_disabled":false,"action_menu_columns":"2","action_menu_scripts_sort":"auto","appearance_badges":"running","appearance_badge_color":"#ee3131","appearance_badge_text_color":"#ffffff","downloads_mode":"default","downloads_extension_whitelist":["/^[^\\.]*$/","/\\.mp[34]$/",".wav","/\\.(avi|mkv|flv|divx|mpe?g|webm)$/","/\\.(ico|gif|png|jpe?g)/","/\\.(srt|sub|idx)$/",".txt",".iso",".zip","/\\.r(ar|[0-9]{2,2})$/","/\\.x?html?/"]}}
```

**Comment by li-zyang** [comment]
## Update

It seems this problem do not happens only with beta version. Each time Firefox crashes & was restarted, it comes up again on the same sites. When I disabled the official version and switched to BETA version the scripts runs again.

Though it can sounds weird, I found that the site I ran into this problem is the only site uses web workers among the sites I opened, I think maybe it have something to do with web workers.

**Comment by li-zyang** [comment]
## Update

I found that not only a browser crash can cause this problem, but also a common restart of Firefox (well I seldom close the browser). Re-enabling the extension after the restart seems to (temporary) solve the problem.

**Comment by derkalle4** [comment]
Hi,

I literally have the same problem. This includes Firefox Firefox 78.3.1esr (64Bit) as well as the latest release 64bit version of Firefox. It seems that this problem is somehow more large scaled: https://github.com/Tampermonkey/tampermonkey/issues/477

I would definitely looking forward to get a solution because it seem to be frequently just "not loading" scripts at all. Disabling and enabling Tampermonkey does work though but Tampermonkey refuses to load any scripts after the next reboot of Windows / restart of Firefox. Sometimes it does work though. Somehow I also get a lot of errors in the debug window for Tampermonkey "about:debugging". But I bet they are not directly related to this issue.

This error seems to come with all scripts I have enabled:
```
...
scriptman: @include "/(^https:\/\/foo\.bar\.com\/.*)/i" matched (f08a4f49-6c05-4a0f-a87d-0bca6683750f)
...
scriptman: inconsistent script entry 0190f32f-4a57-4fe1-9097-a37d4de6aafb Object { script: undefined, cond: "" }
...
badge: set icon background.js:262:172
badge: set 1 background.js:263:274
badge: set icon background.js:262:172
badge: set 1 background.js:263:274
badge: set icon background.js:262:172
badge: set 1 background.js:263:274
...
```

Despite this spamming the debugging console I cannot see any other errors. 

Within that log output above I can clearly see that it matched my Tampermonkey script ID - this ID does not have another entry in the debug log like "scriptman: inconsistent script entry".

Is it possible to fix the problem?

**Comment by dogancelik** [comment]
I can't run scripts on Twitter.

I have Tampermonkey v4.11.6120 (not Beta)

I get this error:

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). common.js:2:319
Content Security Policy: The page’s settings blocked the loading of a resource at data:i (“object-src”).
```

My security settings:
* Modify existing content security policy (CSP) headers: `Remove entirely (possibly unsecure)`
* Allow HTTP headers to be modified by scripts: `Yes`
* Allow scripts to access local files: `Disabled`
* Allow communication with cooperate pages: `Tampermonkey + script version`
* Subresource Integrity: `Validate if possible`
* Check @connect: `Ask if unknown`
* Page Filter Mode: `Blacklist`
  * ```
    /^.*:\/\/apis\.google\.com\/((?!render)([^\/]+)\/)+([^\/]+)?$/
    *://www.facebook.com/plugins/*
    *://platform.twitter.com/widgets/*
    ```

**Comment by li-zyang** [comment]
## Update
Hi all. It seems this problem has been solved with the latest firefox (82.0.3) and tampermonkey BETA (4.12.6121) without doing any extra configuration. Try updating them both to see whether it works on your computer. I'm going to close this issue.

**Comment by li-zyang** [comment]
The scripts does not run on Firefox 83.0 again ... or maybe I'm wrong with the last comment.

but what I found is that if I switch Tampermonkey on an off too quickly, it gives the following complaint:

```
content: Stop here, cause a second Tampermonkey instance was detected!
This can be caused by using "document.write" at Userscripts.
See https://code.google.com/p/chromium/issues/detail?id=253388 for more information
[content.js:1:72]
```

**Comment by dogancelik** [comment]
Don't run Tampermonkey and Tampermonkey Beta at the same time, disable Stable version ![logo](https://user-images.githubusercontent.com/486818/99513001-31605a80-299b-11eb-9957-7d01f7982ac3.png) of Tampermonkey.

1. Go to Tampermonkey Settings
  ![settings](https://user-images.githubusercontent.com/486818/99512550-a54e3300-299a-11eb-8e6e-b2e552370be0.png)
2. Select General > Config mode: `Advanced`
  ![advanced](https://user-images.githubusercontent.com/486818/99512287-54d6d580-299a-11eb-9171-ba7dc1639f83.png)
3. Go bottom of the page, click "Restart Tampermonkey"
  ![restart](https://user-images.githubusercontent.com/486818/99512281-53a5a880-299a-11eb-9a77-890f9bed527d.png)

Beta works but I had to "restart" within Settings to make it work on Github on Twitter again, so still buggy.

**Comment by wvffle** [comment]
For me the issue occurs when I restore the firefox session. The workaround @dogancelik proposed seems to work fine.
