### ISSUE TITLE
Update ESLint to adapt ECMAScript 2020

### ISSUE THREAD

**Issue by gekkedev** [Tampermonkey/tampermonkey#1017]
I was trying to make use of a fairly simple to implement syntactical addition from ECMAScript 2020. [Most browsers have already adapted this specification](https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining) which is why I think it's not a big deal to raise our standards.

## Expected Behavior
no syntax errors when writing ECMAScript 2020

## Actual Behavior
![image](https://user-images.githubusercontent.com/17025257/90343320-b429f000-e00f-11ea-9294-0d2f2e62e492.png)

## Specifications

- Chromium: v84.0.4147.125
- TM: v4.10
- OS: Windows 10

## Script
```js
let testVar = unreliable.reference?.subreference
```

**Comment by derjanb** [comment]
Fixed at 4.11.6119

**Comment by gekkedev** [comment]
An chance to get a reply?
