### ISSUE TITLE
Cannot Export More Than 670 Scripts At A Time

### ISSUE THREAD

**Issue by charliediep0** [Tampermonkey/tampermonkey#1020]
## Expected Behavior
When clicking the Cloud, ZIP, or File export options in the Utilities pane, I would expect it to create an export file containing all the userscripts I installed. 

## Actual Behavior
The process loads forever. Further testing shows that when I manually export (by ticking the checkboxes of each script in the Installed Scripts pane, and selecting the "Export" option) around 670 scripts in total, the export happens normally. Any additional scripts above that number does not allow the export process to complete, and it ends up loading forever. 

## Specifications

- Vanilla Chrome 84.0.4147.135
- TM: (i.e. 4.5.5648)
- Windows 10 Home Edition

**Comment by dineshrathee12** [comment]
+1
- Affected as well, I am not even using less than **100** scripts

**Google Chrome Version:**
Version **84.0.4147.135** (Official Build) (64-bit)

**TM - Version:**
**4.10**
