### ISSUE TITLE
Local File is not loading 

### ISSUE THREAD

**Issue by Vegeta780** [Tampermonkey/tampermonkey#1025]
local file is not loading script with latest tampermonkey beta alert is not working too 
`      HTML ode  <a className="input" href="http://210.56.com"  target="_blank" download/>
`
// ==UserScript==
// @name         New Userscript Local
// @match        file:///E:/H/Physics.html
// @grant        GM_openInTab
// ==/UserScript==
/* global $ */
(function() {
alert("assa");
var x = document.getElementsByClassName("input").length;
    var i ;
    for (i = 0; i < x; i++) {
  var fields = document.getElementsByClassName("input")[i].getAttribute('href');
GM_openInTab(fields);
  }
})();

**Comment by 7nik** [comment]
TM v4.11.6119
For me (`// @match        file:///mnt/all/Documents/sources/unified-GM-shim/test/test%20page.html`) it works.
After fixing `className="input"` to `class="input"`, it even opens the link.

**Comment by Vegeta780** [comment]
here is the video its not working for me 
https://streamable.com/a24s37

**Comment by Vegeta780** [comment]
well after Enable "Allow access to file urls " its working fine thanks 
reference 
https://github.com/Tampermonkey/tampermonkey/issues/977#issuecomment-657268478
