### ISSUE TITLE
new version of Microsoft Edge

### ISSUE THREAD

**Issue by PapillonYu** [Tampermonkey/tampermonkey#1026]
The menu bar cannot pop up in the new version of Microsoft Edge

**Comment by derjanb** [comment]
Hi. this is working fine here. What is you Windows and MS Edge version?

**Comment by PapilionY** [comment]
Windows10, Edge 85.0.564.51....It's weird. The broken&nbsp;tampermonkey&nbsp;is directly transplanted from google, but I re-downloaded it from the edge expansion platform and there is no problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jan Biniok"<notifications@github.com&gt;; 
发送时间: 2020年9月12日(星期六) 凌晨1:53
收件人: "Tampermonkey/tampermonkey"<tampermonkey@noreply.github.com&gt;; 
抄送: "酾酒临江，醉身烟雨"<447361145@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tampermonkey/tampermonkey] new version of Microsoft Edge (#1026)





 
Hi. this is working fine here. What is you Windows and MS Edge version?
