### ISSUE TITLE
WEBREQUETS_WEBSOCKET

### ISSUE THREAD

**Issue by filbo** [Tampermonkey/tampermonkey#1027]
TM 4.11.6117 and 4.11.6119: rea/common.js sets `WEBREQUETS_WEBSOCKET:!1`; code elsewhere looks for the more likely `WEBREQUEST_WEBSOCKET`.

I didn't try to chase what effect this might have, it's just an obvious code-level bug.

**Comment by derjanb** [comment]
Nice find!
