### ISSUE TITLE
CSP prevents scripts from running

### ISSUE THREAD

**Issue by ArsenicX** [Tampermonkey/tampermonkey#1028]
## Expected Behavior
Some script work right on Safari like on Chrome.

## Actual Behavior
Some scripts, work right on Chrome, but not on Safari

## Specifications
- Safari: Version 13.1 (15609.1.20.111.8)
- TM: 4.11.6117 on AppStore
- OS: MacOS 10.15.4

## Script
https://github.com/Revadike/SteamWebIntegration/releases
https://greasyfork.org/en/scripts/14178
and some more. 

Sorry for my poor English.

**Comment by m-thomson** [comment]
Hi @derjanb,

The most recent version available from the App Store is 4.17 so Safari users don't have access to this fix.

That is, unless it's possible to install TM from outside the App Store but last I checked it wasn't.

Thanks

**Comment by derjanb** [comment]
Should be fixed at 4.20.6184 which is currently rolled out. There is nothing more I can do until I migrated Tampermonkey to [Safari web extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions).
