### ISSUE TITLE
Extension content scripts not injected if hostname starts with number

### ISSUE THREAD

**Issue by vermgit** [Tampermonkey/tampermonkey#1032]
Because I rarely see hostnames starting with a number I guess that it might be the root of the problem here. The host I want to write a script for is "2ddl.ms". So if you go to https://2ddl.ms/ the snippet below should show an alert.

## Expected Behavior
the script loads and does the usual

## Actual Behavior
does not get loaded

## Specifications

- Vivaldi: 3.3.2022.45
- TM: 4.10
- OS: Manjaro

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         2ddl
// @namespace    http://namespace/
// @match        *://2ddl.ms/*
// @grant        none
// ==/UserScript==

(function() {
  'use strict';

  alert("woohoo");

})();
```
Other lines tried:
```
// @match        *://%32ddl.ms/*
// @match        *://\u0032ddl.ms/*
// @match        *://\\u0032ddl.ms/*
```

**Comment by derjanb** [comment]
Tampermonkey's content scripts aren't injected. Not sure why. I've reported this to Vivaldi -> issue reference VB-72004

**Comment by derjanb** [comment]
Note: it's at least not only about the number because http://2sub.test.tampermonkey.de/empty.html is working fine.

**Comment by vermgit** [comment]
Guess what, today it's working... Weird.

The things that fix themselves are the bad ones...
