### ISSUE TITLE
I suggest adding a function to register the right-click menu

### ISSUE THREAD

**Issue by wish5115** [Tampermonkey/tampermonkey#1033]
I suggest adding a function to register the right-click menu.

**Comment by wish5115** [comment]
I found a way.
see: https://stackoverflow.com/questions/42800590/tampermonkey-right-click-menu

**Comment by eight04** [comment]
If you use Firefox, you can also try this:
https://github.com/eight04/GM_context

**Comment by derjanb** [comment]
GM_addMenuCommand entries are now shown at the context menu as well. (latest TM BETA)
