### ISSUE TITLE
userscript not executed in iframe

### ISSUE THREAD

**Issue by Loceka** [Tampermonkey/tampermonkey#1034]
I am trying to execute a userscript on https://www.youtube.com which contains an iframe pointing to https://consent.google.com :

```
// ==UserScript==
// @name          youtube.com
// @namespace     youtube.com
// @include       https://www.youtube.com*
// @include       https://consent.youtube.com*
// @include       https://consent.google.com*
// @grant         none
// @run-at        document-start
// ==/UserScript==

(function() {
    console.log(location.hostname);
})();
```

On youtube, it only displays the youtube URL, not the one of the iframe.
On consent.google.com, it displays the consent.google.com URL, which discards an @include problem.

Other iframes on other pages work fine, but not this particular one.

**Comment by Loceka** [comment]
My total bad.
The iframe src points to https://consent.google.com but the location is changed server-side to https://consent.youtube.com which explains why it didn't work.

Solved now

**Comment by Loceka** [comment]
I reopen this bug report because although the userscript works in chrome based browsers (at least Chrome and Opera), it doesn't in Firefox.

These are the step to reproduce : 
- install this script
- open a private navigation window in Firefox (or wipe all the browser cookies)
- go on any youtube video
- say "no thanks" to the login popup
- a policy iframe (also a popup) will appear linked to https://consent.google.com/ in the source code but redirected to https://consent.youtube.com/ server side
- the "consent.youtube.com" line from the userscript does not appear in the browser console

It does in Chrome/Opera and probably any derivated browser.

Possibly it is due to the fact that Firefox doesn't handle it well when the source iframe URL is different than the load content URL?

**Comment by Procyon-b** [comment]
@derjanb 
I bumped into this bug today trying to fix an issue a user has with one of my userscripts.
Tried the script in TM, TMbeta, GM and VM. Only violentmonkey works correctly.

after loading the following script in the 4 "monkeys", (choosing a label and a different color), here is what I get

![TM-frame bug](https://user-images.githubusercontent.com/40043075/97612655-fca25880-1a17-11eb-9957-7610a97cab4a.PNG)

Youtube only loads an iframe if there are no cookies. (or use a private window)

FF: 82.0.2
TM: 4.11.6117
TM beta: 4.11.6120
GM: 4.10.0
VM: 2.12.7


```
// ==UserScript==
// @name         Test frames
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  frame bug in TM ?
// @author       You
// @match        https://*.youtube.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(function() {
"use strict";
var color,label;
//label='TM'; color='background:red;';
//label='TM beta'; color='background:blue;color:white;';
//label='GreaseMonkey'; color='background:green;color:white;';
//label='ViolentMonkey'; color='background:lightblue;';
console.info('%c '+label+' ', color, location.href);
})();
```

**Comment by derjanb** [comment]
Hmm, sorry for the delay. Can not reproduce at YouTube (because the iframe is not there). There also were a lot architectural changes, which might have fixed this issue. 

Can someone please try TM BETA 4.18.6163 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

You can install it [here](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 
Please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

If the issue persists, then please try the fix mentioned here: https://github.com/Tampermonkey/tampermonkey/issues/1186#issuecomment-1151485354

Thanks.

**Comment by derjanb** [comment]
> To be sure I'll have to download an old TM (4.11.6117) to verify if the problem still appears with it in the newer FF.

You can get TM BETA for FF 4.11.6117 from [here](https://firefox.tampermonkey.net/firefox-6117-beta-signed.xpi).

**Comment by freemedom** [comment]
@Loceka thank you very much, i finally solved my problem by your tip. the src attribute of iframe is different from the true url(it can be find by devtool-network-doc.
