### ISSUE TITLE
molehole

### ISSUE THREAD

**Issue by kmclark16** [Tampermonkey/tampermonkey#1039]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact the script developer.

**Comment by kmclark16** [comment]
tell me who it is and i will I don't know how to contact him

**Comment by kmclark16** [comment]
nondscript is not working too i don't know who to talk to about these
scripts  for grepolis
