### ISSUE TITLE
Edge install & download fail

### ISSUE THREAD

**Issue by eggplantisme** [Tampermonkey/tampermonkey#1041]
Try install in Edge, and a bug:
Download was not a valid extension or user script

Edge version: version 85.0.564.63 (64 位)

**Comment by derjanb** [comment]
This is working fine here using https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd.

From where are you trying to install Tampermonkey?
