### ISSUE TITLE
When clicking user.js file it begins download too

### ISSUE THREAD

**Issue by SmartManoj** [Tampermonkey/tampermonkey#1048]
(Please fill out the issue template with your details)

## Expected Behavior
It should not download

## Actual Behavior
It shouldn't

## Specifications

- Chromium: (i.e. 64.0.3282.140) 85.0.4183.121
- TM: (i.e. 4.5.5648) 4.11.6120
 
- OS: (i.e. MacOS 10.13.4) Win 10

**Comment by derjanb** [comment]
Can not reproduce using the Install button at https://openuserjs.org/scripts/anka-213/Webcomic_Reader.
What is your script's URL?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/97074787-c2dbe700-15fe-11eb-95d0-ca68660ed43b.png)
Opens new tab in left side?

**Comment by derjanb** [comment]
> Opens new tab in left side?

Yes, a relic from old times. 🦖 Will be fixed soon.

**Comment by derjanb** [comment]
Do you still see downloads of user.js files? If so, then can you maybe add a screencast?
