### ISSUE TITLE
Updating Tampermonkey removes scripts?

### ISSUE THREAD

**Issue by NicoHaase** [Tampermonkey/tampermonkey#1051]
## Expected Behavior
On upgrading Tampermonkey, I would assume that **only** Tampermonkey is updated and all my scripts are contained.

## Actual Behavior
After having upgraded Tampermonkey and restarted Firefox, all scripts are gone

## Specifications

- Browser: Firefox 81.0.1
- TM: v4.11.6117
- OS: Ubuntu 20.04

**Comment by derjanb** [comment]
I'm sorry that you lost your scripts, but unfortunately there is nothing I can do here. Tampermonkey simply uses the extension storage API offered by Firefox and relies on it to work correctly.

Do you have a profile folder backup? If so, then this comment may help: https://github.com/Tampermonkey/tampermonkey/issues/668#issuecomment-475064123

**Comment by NicoHaase** [comment]
Thanks for your answer - this is pretty strange. As far as I understand, could it be possible that the UUID used to store the data is changed on updates?
