### ISSUE TITLE
exclude/include in the other way

### ISSUE THREAD

**Issue by gabri25ele** [Tampermonkey/tampermonkey#1053]
Hello, 
is possible, for one script, to exclude all the sites (in general) and specify the only site to enable that script?

A script disabled for all, but enabled for one specific url?
How can?

**Comment by derjanb** [comment]
Yes, simply disable "Original includes" and add your own ones at "User includes".

![image](https://user-images.githubusercontent.com/767504/96653122-a3ac3380-1338-11eb-8d10-b889cbf8e7b8.png)
