### ISSUE TITLE
Question: Is Tampermonkey open source? Is there any obfuscated code?

### ISSUE THREAD

**Issue by lilcsz** [Tampermonkey/tampermonkey#1055]

**Comment by derjanb** [comment]
> Is Tampermonkey open source?
Up to version 2.9: yes, see https://github.com/Tampermonkey/tampermonkey/blob/master/README.md

> Is there any obfuscated code?
No, there is minified code only.

**Comment by elvey** [comment]
I'm wondering if the (current non-minified) code is still available to read, even if it isn't (technically/officially) open source.  So one can be reassured, security-wise. I'm trying to decide between installing this and Greasemonkey in Firefox...   I notice that both are flagged, "This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing." but only Greasemonkey is open source.

**Comment by jesus2099** [comment]
@elvey,
There is also multi-platform open source Violentmonkey.
