### ISSUE TITLE
net::ERR_FAILED google chrome

### ISSUE THREAD

**Issue by FARHANE** [Tampermonkey/tampermonkey#1056]
Hello,
I have a problem with the tampermonkey for some websites.
There are some http request blocked and the console prints the error 
net::ERR_FAILED

## Expected Behavior
Request blocked and console shows the error:
net::ERR_FAILED

## Specifications

- Chromium: (i.e.  86.0.4240.111 (Build officiel) (64 bits))
- TM: (4.11)
- OS: (windows 10)

**Comment by Go4RaiT** [comment]
Same problem.
So annoying, I have to use Violentmonkey for alternative.

**Comment by raszpl** [comment]
>for some websites

name one?

**Comment by Go4RaiT** [comment]
> > for some websites
> 
> name one?

I find some websites listed in a related issue, FYI: https://github.com/Tampermonkey/tampermonkey/issues/883#issuecomment-690836513
