### ISSUE TITLE
Cannot install user script

### ISSUE THREAD

**Issue by tehmang** [Tampermonkey/tampermonkey#1057]
(Please fill out the issue template with your details)

## Expected Behavior
Clicking install button on openuserjs.org should install the script, but it only uploads it in the browsee

## Script
https://openuserjs.org/scripts/tehmang/covid_form_id_auto_fill

```

**Comment by derjanb** [comment]
Working fine here at FF 81.0.2 (64-bit) and  Chromium Version 86.0.4240.75.

Please add more steps on how to reproduce this.

**Comment by tehmang** [comment]
I saw this issue on tampermonkey android app.

**Comment by derjanb** [comment]
There is no support for this app anymore. Please check other ways how to use Tampermonkey on Android: https://www.userscript.zone/howto?env=android
