### ISSUE TITLE
document.currentScript is Null in User Script

### ISSUE THREAD

**Issue by devtomschi** [Tampermonkey/tampermonkey#1058]
I have a user script that augments my Trello boards, which worked fine up to the last FireFox update.
The user script includes the Trello JS client API from https://trello.com/1/client.js

After the last FireFox update (to version 82.0.2 64bit on Windows 10) i get the following error in the console:
ERROR: Execution of script 'New Userscript' failed! document.currentScript is null

Some investigation shows that the expression "document.currentScript" now evaluates to null, which leads to an exception in the Trello JS client. Since it worked flawlessly before the update, I would assume "document.currentScript" was not null before.
I'm not sure what the expected behavior is, but I decided to report this since behavior IMHO has changed and I'm not sure this happended intentionally.

## Specifications

- Firefox 82.0.2 64bit
- TM: 4.11.6117
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @require      https://trello.com/1/client.js
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    console.log("everything OK")  // does not get logged due to error
})();```

**Comment by 7nik** [comment]
Are you sure that it caused by the FF update but not the script update?
The client.js extracts key and token params from `document.currentScript.scr` and I have no idea how it supposed to get them in a userscript.

**Comment by fabiosirchia** [comment]
Hi,

we have the same problem here in chrome  86.0.4240.183 
seems that the trello's client.js cant access to document.currentScript after the last Chrome update.

i really don't know if it depends on tampermonkey but, if i will not user @require and i paste the code of client.js inside the userscript it seems work..

Fabio

**Comment by fabiosirchia** [comment]
Hi,
i think that trello made an upgrade of the file client.js
https://web.archive.org/web/20201025121726/https://api.trello.com/1/client.js

seems that the document.currentScript was introduced the last week

**Comment by 7nik** [comment]
This is what I meant.
Also, it requires jQuery.
You can try this workaround:
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @match */*
// @author       You
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
// @require      data:javascript,let document = {currentScript: {src: location.href}};
// @require      https://trello.com/1/client.js
// @grant        none
// ==/UserScript==
document = window.document; // eslint-disable-line

(function() {
    'use strict';
    console.log("everything OK");
})();
```

**Comment by devtomschi** [comment]
Thanks for your investigation, @7nik and @fabiosirchia 

@7nik : I will try your magic :-) since I'm using jQuery anyway
However, I wonder if this kind of "forwarding" shouldn't be rather done by Tampermonkey itself. As @fabiosirchia said it works if you paste the referenced script into the userscript, so I would naively expect it should also work the other way.

**Comment by fabiosirchia** [comment]
uh ok, 
i tested it, but i think that here there is a problem,
// @require      data:javascript,let document = {currentScript: {src: location.href}};
will set current script to the main website, the new client.js instead seems that espect 
// @require      data:javascript,let document = {currentScript: {src: 'https://trello.com/1/client.js'}};

i think that this need to be figured out by tampermonkey

**Comment by 7nik** [comment]
I very doubt that TM should do it because usercripts aren't executed inside <script>. Also, it's unclear what `document.currentScript.src` should be. 
E.g., here the client.js extracts `key` and `token` from `document.currentScript.src` and I don't know whether it'll work without them.
I just proposed an idea of how to run the script because it's tricky.

**Comment by devtomschi** [comment]
Thanks for your ideas guys, I have the following workaround in place which is now entirely included in the userscript header:

`// @require      data:javascript,let document = {currentScript: {src: 'https://trello.com/1/client.js'}};`
`// @require      https://trello.com/1/client.js`
`// @require      data:javascript,document = window.document;`

This helps my to get rid of my local copy of client.js :-)

@7nik I thought that `document.currentScript` is not null in a user script and that therefore the information should be propagated to the **require**d scripts as well. However, I was mistaken and `document.currentScript` is null in the user script.

@fabiosirchia When you pasted client.js into the userscript, did you use a hard-coded value of  'https://trello.com/1/client.js' for the  `document.currentScript.src` or how did you make it work?

**Comment by derjanb** [comment]
I'm glad to see you helping out each other. 😊

> You can try this workaround

@7nik Great solution. I don't know why, but when I encountered a similar problem, I never thought about simply using a  JavaScript data URI. 🤦‍♂️

> I very doubt that TM should do it because usercripts aren't executed inside <script>. Also, it's unclear what document.currentScript.src should be.

👍

**Comment by vanowm** [comment]
Can we reopen this issue, please? The work around only good for this specific use-case, it doesn't work when needed access to the source of the script.

**Comment by 7nik** [comment]
> get proper version number

Just use [GM_info](https://www.tampermonkey.net/documentation.php#api:GM_info): `GM_info.script.version`

**Comment by vanowm** [comment]
`GM_info.script.version` does not return version number of the file when edited in external editor.

**Comment by 7nik** [comment]
Why do you even need it? What is your [XY problem](https://xyproblem.info/)?

**Comment by XyuBAM** [comment]
> Why do you even need it? What is your [XY problem](https://xyproblem.info/)?
1. display proper version
2. ability update database or w/o when version changed

My external editor automatically updates version number in the userscript file when I save the file. So currently I have to manually edit my script in the browser.

**Comment by vanowm** [comment]
> Why do you even need it? What is your [XY problem](https://xyproblem.info/)?
1. display proper version in script's UI
2. ability update database or w/o when version changed

My external editor automatically updates version number in the userscript file when I save the file. So currently I have to manually edit my script in the browser.
