### ISSUE TITLE
After the latest update (Fedora 33) Firefox now deletes all tampermonkey scripts on restart

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [Tampermonkey/tampermonkey#1062]
(Please fill out the issue template with your details)

## Expected Behavior
Browser restarted; userscripts loaded.
## Actual Behavior
Browser restarted; userscripts gone. Whole database nuked.

## Specifications

- Firefox: (82.0.2 64bit; fedora -1.0 - Yesterday's update)
- OS: (Fedora 33)

## Script
All and any.

**Comment by hjyssg** [comment]
This bug also happened to me, not sure if this comes from firefox or temper monkey.

**Comment by derjanb** [comment]
Info: This is a Firefox bug, because after reverting to an older version the scripts re-appear and other extensions are affected as well.
