### ISSUE TITLE
Tampermonkey hangs (100% CPU) on Google video search

### ISSUE THREAD

**Issue by Wuerfel21** [Tampermonkey/tampermonkey#1065]
## Steps to reproduce
1. search for something on google
2. change to video search
3. edit the search box
4. press enter

## Expected Behavior
Results should load.

## Actual Behavior
Tampermonkey process hangs with 100% CPU usage, page doesn't load. This happens regardless of wehter any scripts are actually enabled, but doesn't happen when Tampermonkey is disabled entirely (through it's own setting, but of course disabling the extension works, too)

## Specifications

- Vivaldi: 3.4.2066.94
- TM: 4.11
- OS: Windows 7

**Comment by raszpl** [comment]
cant reproduce, Vivaldi | 3.5.2110.3 (Official Build) (64-bit)

**Comment by Wuerfel21** [comment]
Oh indeed, doesn't happen in a fresh profile with just Tampermonkey installed, but does happen in my actual profile with all other extensions disabled.
So it may have to do with a setting... I'll see if I can reproduce on a fresh profile

**Comment by Wuerfel21** [comment]
Nope, can not get it to happen in a fresh profile, all settings the same

**Comment by raszpl** [comment]
delete \AppData\Local\Vivaldi\User Data\Default\Service Worker

**Comment by Wuerfel21** [comment]
That didn't do the trick, either.

**Comment by raszpl** [comment]
update to latest vivaldi build? Its hard to tell with vivaldi, its very buggy and slow on its own. I still use it due to flexibility and less google spying.

**Comment by derjanb** [comment]
Is this still an issue?

**Comment by Wuerfel21** [comment]
Yep, still is. I've just been avoiding google video search. Only site this happens on.

**Comment by raszpl** [comment]
make a backup copy of your profile (AppData\Local\Vivaldi\User Data), then start deleting stuff from AppData\Local\Vivaldi\User Data\Default. cache, code cache, etc until it starts working again

or go the other way around, create fresh profile and just copy what you need from the old one - bookmarks, cookies, history, local storage etc
