### ISSUE TITLE
When get WebDAV Backup list, plsease use decodeURI() to decode the file name.

### ISSUE THREAD

**Issue by Antecer** [Tampermonkey/tampermonkey#1066]
When get WebDAV Backup list, plsease use decodeURI() to decode the file name.
If not, the string encoded by encodeURI() will be displayed, which is very unfriendly to users.

version=4.11.6120

**Comment by Antecer** [comment]
Now, the version is 4.12.6122, but the issue didn't fixed.

**Comment by derjanb** [comment]
Sorry for the delay. Fixed at 4.14.6141
