### ISSUE TITLE
Diff view on script update doesn't work

### ISSUE THREAD

**Issue by RX-3200** [Tampermonkey/tampermonkey#1070]
## Expected Behavior
after script editing (only 1 string changed) and after press in menu "save" it show changes

## Actual Behavior
after script editing (only 1 string changed) and after press in menu "save" it print: too many changes. can't show
https://i.imgur.com/VnCh83J.jpg
(in 4.11.6120 it worked)

## Specifications
- Chromium: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Safari/537.36
- TM: 4.12.6121
- OS: Win7x64

## Script
any

**Comment by derjanb** [comment]
Can you please explain a litte bit more in detail and/or attach a screencast or screenshot? Thanks.

**Comment by RX-3200** [comment]
https://i.imgur.com/VnCh83J.jpg

**Comment by derjanb** [comment]
Ah OK, understood. Thanks for reporting.
