### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by neoOpus** [Tampermonkey/tampermonkey#1071]
## Expected Behavior
It should just show the icon or grayed number of scripts

## Actual Behavior
Icons keep showing runing instances in red even when it is disabled and it shows often more than what are supposed to be runing which is confusing

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
The number shows the current state and scripts are still running until the page is reloaded.
Too high instance numbers are usually caused by iframes.
