### ISSUE TITLE
Is there a way to speed up how fast the code is ran?

### ISSUE THREAD

**Issue by KennyKr7** [Tampermonkey/tampermonkey#1072]
(Please fill out the issue template with your details)

## Expected Behavior
Increase speed of action

## Actual Behavior
too slow

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595

**Comment by KennyKr7** [comment]
How do I enable Instant Mode?

**Comment by derjanb** [comment]
1) Open Tampermonkey Options
2) Set "Config Mode" to "Advanced"
3) search for "Inject Mode"
