### ISSUE TITLE
Are @require blocks run synchronously?

### ISSUE THREAD

**Issue by xdhmoore** [Tampermonkey/tampermonkey#1073]
The following files:

**a.js**
```
console.log('a');
```

**b.js**
```
console.log('b');
```

**main.js**
```
// ==UserScript==
//
// insert other metadata here 
//
// @require http://server.com/a.js
// @require http://server.com/b.js
//
// ==/UserScript==

console.log('c');

```
    
These seem to load synchronously with the result:
```
a
b
c
```
Are these guaranteed to run synchronously? I couldn't find the answer in the greasemonkey or the tampermonkey docs.

**Comment by tophf** [comment]
Yes, they always run synchronously. In Tampermonkey/Violentmokey the code is simply concatenated as you can see in devtools.
