### ISSUE TITLE
Instant inject failure

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#1074]
Cent Version 4.3.9.182 (Official Build) (64-bit) (Portable) (Chromium 86.0.4240.183)

`Failed to execute 'send' on 'XMLHttpRequest'`

[Example](https://hw-videos.worldstarhiphop.com/u/vid/2020/11/zgo7IE2ptxyc.mp4)

**Comment by raszpl** [comment]
nice a er example :-)

full error is

    content.js:26 GET blob:chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/1baaf851-b4d7-4346-8bf8-3a18f87e14ac net::ERR_FILE_NOT_FOUND
    Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'blob:chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/1baaf851-b4d7-4346-8bf8-3a18f87e14ac'.

but this isnt an ordinary page, this is a media file so no idea if we are even supposed to be able to inject js into Chrome default media player thingy

**Comment by narcolepticinsomniac** [comment]
> this is a media file so no idea if we are even supposed to be able to inject js

Yes, we're supposed to be able to. It's a relatively new bug, since they've worked fine previously. @derjanb any word on this? Seems like it's all top-level mp4s - at least all the ones I've checked. Oddly enough, iframes seem fine.

Obviously, ideally this bug should be fixed, but instant inject should also have a fallback to default injection when it fails, as opposed to not injecting scripts at all.

**Comment by narcolepticinsomniac** [comment]
LGTM now.
