### ISSUE TITLE
icon looks awry in Safari 14

### ISSUE THREAD

**Issue by daviehh** [Tampermonkey/tampermonkey#1075]
After updated to macos big sur, the icon in Safari 14 looks a bit awry: not rounded-corner square, no button shape, etc.

<img width="124" alt="Screen Shot 2020-11-14 at 6 36 32 PM" src="https://user-images.githubusercontent.com/25255906/99159229-b0f2de80-26a8-11eb-9c2c-8636f6dcb666.png">

## Expected Behavior
Correct icon?

## Specifications

- Safari: 14.0.1
- TM: 4.11.6117
- OS: MacOS 11.0.1 (20B29)

## Script

N/A

**Comment by derjanb** [comment]
Should be fixed at 4.13.6140
