### ISSUE TITLE
The FetchEvent for "chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html" resulted in a network error response: an object that was not a Response was passed to respondWith().

### ISSUE THREAD

**Issue by raszpl** [Tampermonkey/tampermonkey#1079]
Happened randomly. Worked yesterday when shutting down, today this error.

## Expected Behavior
opened dashboard

## Actual Behavior
> This site can’t be reached
> The webpage at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html might be temporarily down or it may have moved permanently to a new web address.
> ERR_FAILED

opening devtools shows 
>The FetchEvent for "chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html" resulted in a network error response: an object that was not a Response was passed to respondWith().

restarting extension - no change
restarting browser - no change

vivaldi://serviceworker-internals/?devtools
> Registrations in: ...
> Scope: chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html
> Registration ID: 16
> Navigation preload enabled: false
> Navigation preload header length: 4
> Active worker:
> Installation Status: ACTIVATED
> Running Status: RUNNING
> Fetch handler existence: EXISTS
> Script: chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/cache.js
> Version ID: 24
> Renderer process ID: 2700
> Renderer thread ID: 1
> DevTools agent route ID: 1
> Log:

manualy deleting service worker fixes loading up dashboard, now with this in console

> An unknown error occurred when fetching the script.
> extension.js:532 SQ: registration for /options.html failed -> TypeError: Failed to register a ServiceWorker for scope ('chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html') with script ('chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/cache.js'): An unknown error occurred when fetching the script.

restarting extension/browser doesnt fix this, manually nuking 'Service Worker' directory from the hard drive clears it up, now getting this
> pp: Warn: got pseudo response!
> options.html#url=aHR0cHM6Ly9naXRodWIuY29tL1RhbXBlcm1vbmtleS90YW1wZXJtb25rZXkvaXNzdWVzL25ldw==&nav=dashboard:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
> cache.js:3 SW: started

refreshing Dashboard  (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html#nav=dashboard) and we are back in business, everything works as expected again. Might of been a freak Chrome Service Worker glitch, posting just in case its an actual bug, or someone has same problem.

## Specifications

- Chromium: 86.0.4240.112
- TM: 4.12.6121
- OS: win10

**Comment by derjanb** [comment]
Thanks for reporting. Looks like there are more service worker issues than expected. 😒 Investigating...

**Comment by raszpl** [comment]
#1148 might be related, just happened again today with 4.12.6132
