### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by bonfiresh** [Tampermonkey/tampermonkey#1081]
With the safari in my case, there is high cpu usage issue for all scripts, unless don't use TM

- Safari: 14.0.1 (15610.2.11.51.10, 15610)
- TM: 4.11.6117
- OS: macOS Catalina 10.15.7 (19H15)

**Comment by derjanb** [comment]
Tampermonkey got updated to 4.20.6184 and I didn't notice any high CPU usage.
