### ISSUE TITLE
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by raszpl** [Tampermonkey/tampermonkey#1083]
Seems one of Google efforts to speed up first page load results in extensions having hard time to load on time. Is this Chrome bug, or can something as trivial as this suggestion https://stackoverflow.com/questions/54619817/how-to-fix-unchecked-runtime-lasterror-could-not-establish-connection-receivi/61530117#61530117 fix it? uBo and couple other extensions seem to experience similar problem.

## Expected Behavior
Extension works on the first page loaded from last session after browser restart.

## Actual Behavior
Browser starts, active page from last session loads with 3x:

     Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

in console log, devtools doesnt show script injection. Reloading fixes it.

## Specifications

- Chromium: 87.0.4280.66 and 81.0.4044.83 (Official Build) beta
- TM: v4.12.6121
- OS: W10

**Comment by derjanb** [comment]
This is working fine here using Ubuntu. 🤔 Will check this at Windows next week.

**Comment by raszpl** [comment]
Steps to reproduce:

- download https://chromeenterprise.google/browser/download/ currently its at Version 87.0.4280.66 (Official Build) (64-bit) 

- settings/on startup/Continue where you left off

- install TM: v4.12.6121, injection mode: instant

- load random website, restart browser

- ctrl-shift-i to open inspector, look at console:

    _missing_ 'Synchronous XMLHttpRequest on the main thread is deprecated' warning
    Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

extensions seem to have worked and got injected, but injection mode: instant failed and website was loaded before any scripts had a change to start running. This seems to affect all extensions? as I have one modifying some headers thru chrome.webRequest.onBeforeSendHeaders and that also fails to  fire up fast enough _on the very first website loaded from previous session_ (Continue where you left off) in Chrome. Im starting to suspect it might be Googles misguided fight against synchronous code paths (manifest V3 killing blocking webRequest, now delayed "run_at": "document_start") in chase for faster page loads - they recently boasted about "optimizations" reducing first page load times.

- reload website

    'Synchronous XMLHttpRequest on the main thread is deprecated' warning _present_
    _missing_ Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by derjanb** [comment]
Hmm, my simple test script:

```JS
// ==UserScript==
// @name         Log HREF
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*/*
// @grant        none
// ==/UserScript==

console.log('SSSS', window.location.href);
```

This is working fine here. I always see the console log. However, this is a very simple script, which has no problem with missing "real" `document-start`. Unfortunately hitting document-start is not possible on browser start, because Chrome is not willing to wait for extensions being initialized. 🤷

So if your userscript needs real document-start (which might be the case since you're using instant injection mode), then I can not fix issues at browser start.

**Comment by raszpl** [comment]
> Unfortunately hitting document-start is not possible on browser start, because Chrome is not willing to wait for extensions being initialized.

Thats what I was afraid of :( I havent seen this documented/mentioned anywhere on the web.
