### ISSUE TITLE
Display all tags along with branch names for a given JIRA committed

### ISSUE THREAD

**Issue by smajeti22** [Tampermonkey/tampermonkey#1085]
(Please fill out the issue template with your details)

## Expected Behavior
Should show up all tags along with branches that a specific JIRA is committed in

## Actual Behavior

Shows only branches a JIRA is committed in. Snapshot shows only HDP-3.1-maint but not HDP-3.1.5 tag .
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```
<img width="491" alt="Screenshot 2020-11-27 at 11 44 05 AM" src="https://user-images.githubusercontent.com/20850313/100417022-e4206f00-30a5-11eb-9e7c-696ed8c175cd.png">

**Comment by derjanb** [comment]
Please contact the userscript developer. Tampermonkey is the extension which allows such userscript to run.
