### ISSUE TITLE
GM_webRequest some times works, some times not

### ISSUE THREAD

**Issue by jc3213** [Tampermonkey/tampermonkey#1086]
I've trying the sample from https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-299949037 and want to record and block all web traffics from - for example `*.youtube.com/*`

## Expected Behavior
All web traffic from youtube.com will be blocked, and will be recorded through `GM_webRequest( [ruleArray], callback )`

## Actual Behavior
`@webRequest` won't block requests, `GM_webRequest( [ruleArray], callback )` won't work.
Another script, `@webRequest` will block requests, but `GM_webRequest( [ruleArray], callback )` still won't work.

## Specifications

- Chromium: 86.0.4240.198
- TM: 4.11
- OS: Windows 10

## Not Working Script

```js
// ==UserScript==
// @name         GM_webRequest testing
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// @include      *://*.youtube.com/*
// @grant        GM_webRequest
// @webRequest   [{"selector":"*youtube.com/*","action":"cancel"}]
// ==/UserScript==

var rule = JSON.stringify(GM_info.script.webRequest); // == @webRequst header from above

GM_webRequest(rule, function(info, message, details) {
    console.log(info, message, details);
});

/*
  Notes:
    Action:
      The final redirect: URL needs to be included into the scripts @match or @include header
    Selector:
      If just a string is given, it is interpreted as include: property.
      include:, exclude: and match: properties are supported and can have an array or a string value - the syntax equals @include, @match and @exclude
    @webRequest may have a human readable format in the future, but for now it's the stringified first argument of GM_webRequest and allow request 
      manipulation even if the script didn't run yet. The only downside atm is that you need to re-register the rules (which overrides all previous ones)
      in order to get manipulation events. GM_webRequest(currently_active_webrequest_rule, function...)
*/
```
## Half Working Script
```js
// ==UserScript==
// @name         GM_webRequest testing
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://wupfile.com/*
// @grant           GM_webRequest
// @webRequest   {"selector": "*.adreactor.com/*", "action": "cancel"}
// @webRequest   {"selector": "*pagead2.googlesyndication.com/*", "action": "cancel"}

var rule = JSON.stringify(GM_info.script.webRequest); // == @webRequst header from above

GM_webRequest(rule, function(info, message, details) {
    console.log(info, message, details);
});
```

**Comment by 7nik** [comment]
1. You pass the rule as a string but it should array: `var rule = GM_info.script.webRequest;`
2. There is no reason to call `GM_webRequest`, unless you really need logging.`@webRequest` already will block network requests. So, if you want just block those requests - just remove the code and leave meta-block.

**Comment by jc3213** [comment]
Thanks for your advice, it works but not perfectly. I wonder how should I code if I only want to logging the web request. I know I should not `cancel` or `redirect` them. and the code still some time works, some time not.

https://www.bilibili.com/audio/au1966098?type=7
there are no loggings in the console, and even `@webRequest` meta won't block anything

https://www.bilibili.com/video/BV1HK4y1771i
there are loggings, videos from `*.bilivideo.com` also will be blocked. I wonder how I can only log the request not cancelling it

```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.bilibili.com/audio/*
// @match        https://www.bilibili.com/BV*
// @match        https://www.bilibili.com/av*
// @grant        GM_webRequest
// @webRequest   { "selector": "*.bilivideo.com/*", "action": "cancel" },
// ==/UserScript==

'use strict';
GM_webRequest([
     { selector: '*.bilivideo.com/*', action: 'cancel' },
], function(info, message, details) {
    console.log(info, message, details);
});```

**Comment by 7nik** [comment]
This one was really tricky - the song is loaded via Audio element and hence network request has the type 'media'. But webRequest proceeds only requests with [types 'sub_frame', 'script', 'xmlhttprequest' and 'websocket'.](https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-300132157)

>  only log the request not cancelling it

you can redirect a request to itself
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.bilibili.com/audio/*
// @match        https://www.bilibili.com/video/*
// @match        https://*.bilivideo.com/*
// @grant        GM_webRequest
// ==/UserScript==

'use strict';
GM_webRequest([
     { selector: '*.bilivideo.com/*', action: { redirect: { from: "(.*)", to: "$1" } } },
], function(info, message, details) {
    console.log(info, message, details);
});
```
But note, in this case, you need to add redirecting sites to `@match` or `@include`

**Comment by jc3213** [comment]
Any chance for supporting `media` contents and `logging` action? It will be useful for downloading videos and audios from website if GM_webReqeust will support them.

PS: ``` { selector: '*.bilivideo.com/*', action: 'redirect' }, ``` works for me too

PS2: Calling GM_webRequest in script editor will show notification about `GM_webRequest is not defined`, will it be fixed?
![GM_webRequest is not defined](https://user-images.githubusercontent.com/8744936/102756434-e0cd8a00-43aa-11eb-9e61-300f75be54d1.png)

**Comment by 7nik** [comment]
> action: 'redirect'

It complains that it cannot redirect due to the incorrect rule.

You can use GM.webRequest - there is no big difference.

**Comment by MikeDabrowski** [comment]
@7nik Can I get to the response body when redirecting the request?

**Comment by derjanb** [comment]
`GM_webRequest` needs to be re-implemented for Manifest v3. Please watch #397 for future progress.
