### ISSUE TITLE
SHA-256 checksum is calculated incorrectly

### ISSUE THREAD

**Issue by xx55tt** [Tampermonkey/tampermonkey#1087]
I'm trying to use [this script](https://cdn.jsdelivr.net/npm/js-base64@3.6.0/base64.js) with a SHA-256 checksum, but it seems like the checksum is calculated incorrectly so I get a SRI error. I have tried the other checksums as well, everything worked except SHA-256.
I looked into the code, it looks to me that the SHA-256 is calculated with Forge even though the [documentation](https://www.tampermonkey.net/documentation.php#Subresource_Integrity) states that it uses `window.crypto`.
If this is the case then this might be relevant: [SHA256 hash of binary data using Forge](https://stackoverflow.com/a/58301910)

Here are checksums that I used:
- MD5: `bc1b222c876bd47820664d5c419e87c5`
- SHA-1: `c0a37e41d94061c614fc7d2cb15acdb382c2cd1f`
- SHA-256: `f2d5e3a482ce23c801ec6babdc5879156b78e6b643d441717b50e7702824db7b`
- SHA-384: `94fbfb123f8afd1f8a3f7df87c6733dd8b45d51b8be3ac3c9f3aa4208d00c8ce264f9c33e2ca418e0e288a2c9a2fa5a5`
- SHA-512: `436ded37e332f3f12ff392eaabf140d0250672322a31d7285974784c8cea92075d80d8a1601aa7ab9216918026ea79346a7a1391a7b5c8d3f69d4e4f1bb6dc7a`

## Expected Behavior
The script is successfully validated with the SHA-256 checksum.

## Actual Behavior
`Tampermonkey: couldn't load @require from URL https://cdn.jsdelivr.net/npm/js-base64@3.6.0/base64.js#sha25…e3a482ce23c801ec6babdc5879156b78e6b643d441717b50e7702824db7b due to a SRI error`

## Specifications

- Chrome: 87.0.4280.66
- Firefox: 83.0
- TM: 4.11 (Chrome), 4.11.6120 (Firefox)
- OS: Linux

## Script

```js
// ==UserScript==
// @name         SRI Error
// @match        https://*
// @require      https://cdn.jsdelivr.net/npm/js-base64@3.6.0/base64.js#sha256=f2d5e3a482ce23c801ec6babdc5879156b78e6b643d441717b50e7702824db7b
// @grant        none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Thanks for reporting. Simply passing the right encoding to the hash function instead of relying on its auto-detect magic also helps. 🤦‍♂️😁
