### ISSUE TITLE
WARNING: Microsoft Edge - TM Beta - Bogus Version

### ISSUE THREAD

**Issue by slopra** [Tampermonkey/tampermonkey#1089]
I assume this single result for TM Beta on the Microsoft Edge Add-ons store is inappropriate at best, nefarious at worst.

- Only on version 4.11
- Developer Dexterous?

[Microsoft Edge - TM Beta \[Bogus\]](https://microsoftedge.microsoft.com/addons/detail/tampermonkey-beta/nboeolaojkicnnbcieehfkbghifapigj)

[Microsoft Edge - TM Stable \[Official\]](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd)

I haven't reported it yet on the off chance that I'm missing something.

**Comment by derjanb** [comment]
Please report it! I've also reported it twice, because it was modified to load code from `https://1658209995.rsc.cdn77.org/app.js`.

I've also commented on [reddit](https://www.reddit.com/r/techsupport/comments/jvdc6u/google_search_links_sometimes_redirect_to/gdf8vy4/?context=3), but all I got was:

> Thank you for your comment in r/techsupport but your account does not have enough credibility in the reddit community and your comment has been suppressed.

🤷‍♂️

**Comment by slopra** [comment]
Eeek I hadn't looked at its code yet. Reporting it now and letting a few others know to do the same.

Legacy Edge support would be cool. Just my 2 cents: I'm not privy to the relevant demographic data, but I wonder if it's worth the effort and maintenance for an already unpopular browser that hits EOS 03/2021? 🤔 

Do you have any plans to officially bring TM Beta to the Edge Chromium store alongside Stable? I know extensions can be installed from the Chrome Web Store but it'd be nice to have it on the native store. De-Googlefying my browser was one of the reasons I "changed" browsers 😁

**Comment by slopra** [comment]
Extension has been removed from the store
