### ISSUE TITLE
Firefox: can't remove a script permanently, keeps coming back after FF restart

### ISSUE THREAD

**Issue by Marooned-MB** [Tampermonkey/tampermonkey#1090]
## Expected Behavior
When I remove a script, it should be removed permanently.

## Actual Behavior
When I remove a script, it's being restored after FF restart and as this is quite old script, it's breaking the whole page (YouTube in this case).

## Specifications

- Firefox: 83.0 (64 bit)
- TM: v4.11.6120
- OS: Windows 7

**Comment by derjanb** [comment]
Please disable sync and try with a new profile.
