### ISSUE TITLE
Page CSP prevents script execution

### ISSUE THREAD

**Issue by karottenreibe** [Tampermonkey/tampermonkey#1092]
## Expected Behavior

This userscript should show an alert when navigating to a Slack channel in Firefox:

```js
// ==UserScript==
// @name         Slack DND
// @version      0.1
// @description  bla
// @author       You
// @match        https://app.slack.com/*
// @grant        none
// ==/UserScript==

alert(1):
```

## Actual Behavior

No alert shown, error console shows:

```
Uncaught TypeError: A is undefined
    sa eval:2
    T eval:3
    exec_script eval:1
    exec_csp eval:1
    <anonymous> eval:12
    Aa eval:11
```

Disabling Tampermonkey makes this error vanish, so I'm assuming it's related to why the userscript is not executed.

## Specifications

- Firefox: 83.0
- TM: 4.11.6120
- OS: Ubuntu 20.04

## Script

```js
// ==UserScript==
// @name         Slack DND
// @version      0.1
// @description  bla
// @author       You
// @match        https://app.slack.com/*
// @grant        none
// ==/UserScript==

alert(1):
```

**Comment by SNDST00M** [comment]
@derjanb the CSP error also catastrophically breaks all JS on the page on Chrome. Could a tag be added to prevent running on pages with a content security policy?

**Comment by derjanb** [comment]
@SNDST00M Page CSP should not affect script execution at Chrome. If you encounter such a problem, then please create a new issue with steps to reproduce. Thanks.

**Comment by graingert** [comment]
Should that be `alert(1);`?

**Comment by derjanb** [comment]
> Should that be alert(1);?

Don't get the question.

> Uncaught TypeError: A is undefined

The error was fixed in the meantime, but this issue wasn't closed. So closing it now.

**Comment by graingert** [comment]
The demo user script says `alert(1):` I think it should be a semicolon not a colon

**Comment by derjanb** [comment]
> The demo user script says `alert(1):` I think it should be a semicolon not a colon

I see. Yes, you're right.
