### ISSUE TITLE
Documentation: broken link for match patterns in @match section

### ISSUE THREAD

**Issue by Archangel1C** [Tampermonkey/tampermonkey#1093]
The link to match patterns points to https://code.google.com/chrome/extensions/match_patterns.html and is dead.
The new link is probably https://developer.chrome.com/docs/extensions/mv2/match_patterns/

BTW: in the @include section is a link to http://forum.tampermonkey.net/viewtopic.php?p=3094#p3094 and the _forum is temporarily offline due to GDPR_.

**Comment by derjanb** [comment]
Fixed. Thanks for reporting.
