### ISSUE TITLE
 Layout of the settings panel (options) on mobile

### ISSUE THREAD

**Issue by Eccenux** [Tampermonkey/tampermonkey#1095]
## Expected Behavior

Should be able to access main functions:

- Tabs (like the utils tab).
- Search/filter.
- Checkboxes in settings.

## Actual Behavior

Tap areas are too small (buttons, checkboxes).
Tabs do not scroll nor wrap.

I think most of the above can be fixed with styles. It might be worth adding labels to the checkboxes, but it's not necessary.
I can work on styles if you are willing to accept pull requests 🙂

## Specifications

- FF Nightly.
- TM: 4.11.6120
- OS: Android

**Comment by derjanb** [comment]
Mobile view should work now
