### ISSUE TITLE
Multiple context menu entries support

### ISSUE THREAD

**Issue by taoyuancun123** [Tampermonkey/tampermonkey#1097]
I write a script to add a search button in contextMenu,like below image,
![image](https://user-images.githubusercontent.com/31681398/102032677-6c1bae00-3df4-11eb-9e38-4c8ca5948ae5.png)

but in now,One search item ,must create a single one script.
some user ask me ,Can in combine them into one script.

## Expected Behavior
add multi context menu item,and auto get into one parent item.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
https://greasyfork.org/zh-CN/scripts/402717-%E5%9C%A8google%E4%B8%AD%E6%90%9C%E7%B4%A2
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
TM BETA 4.12.6121 and above will show menu commands at the context menu as well.

https://www.tampermonkey.net/documentation.php#GM_registerMenuCommand

**Comment by taoyuancun123** [comment]
tks for your reply
