### ISSUE TITLE
What are the criteria for receiving userscript update notification?

### ISSUE THREAD

**Issue by jeiea** [Tampermonkey/tampermonkey#1098]
I'm not sure what userscript modification can cause an alert to an user during userscript auto update. I tried finding manual userscript update, but only method I could find was the installation from URL.

I skimmed faq and other docs, but had no luck. If the criteria is complex (by config.. etc) it may be documented.

The following is the modification I'm currently care about.

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/[2.1.3]/jquery.min.js  [...] <--- this may vary
// @resource some https://some.in?v=[234234] <--- this may vary
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by jeiea** [comment]
I got answer to my question. Manual update can be invoked by dashboard update check column. @resource change doesn't alert when auto update.
Close.

**Comment by derjanb** [comment]
Ok, nonetheless these are the reasons for an update tab:

* Modification from different tabs
* Errors: e.g. no include information
* Changed update URL
* Changed include/match/exclude
* Changed connect
* Automatically added includes (userstyles.org script)
* Antifeature present (installation) or changed (update)
