### ISSUE TITLE
4.12.6123 broke some of my scripts

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#1102]
Some of my scripts stopped working after TM beta updated.
How do I roll back to 4.12.6121?

## Expected Behavior
Scripts works as described below

## Actual Behavior
Scripts does not work
Script does work on 4.12.6120 (could not find a way to install 4.12.6121)

## Specifications
- FF 85b3
- TM: 4.12.6123
- OS: Win 10

## Script
Install https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new
Run a google search
Scroll down to the bottom of the page
Script should display a tiny icon at upper right corner and enable settings in its menu

**Comment by derjanb** [comment]
> How do I roll back to 4.12.6121?

You can download it from here https://firefox.tampermonkey.net/firefox-6121-beta-signed.xpi

**Comment by alexolog** [comment]
Thank you.  I installed it and disabled automatic updates until the issue is resolved.

It would be nice if the "changes" page had links to older versions since betas sometimes break things.

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.12.6124. 😅
