### ISSUE TITLE
Storage is broken issue

### ISSUE THREAD

**Issue by Gil3X** [Tampermonkey/tampermonkey#1103]
Somehow got warning that storage is broken, according to FAQ: Set - localStorage.setItem('#brokenprofile', 'nowarning'); in the Console and got responce "undefined". ROFL

## Expected Behavior
Fix broken storage

## Actual Behavior
Still getting notifications/errors

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)
Chrom 87.0.4280.88 (latest official - 22.12.2020)
## Script

(Please give an example of the script if applicable.)

```js
General error
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
This message means that somehow the extension storage is broken, most probably due to a corrupt browser profile.

> according to FAQ: Set - localStorage.setItem('#brokenprofile', 'nowarning'); in the Console and got responce "undefined". ROFL

This command is not intended to return anything.
