### ISSUE TITLE
[Safari]Tampermonkey scripts are automatically deleted

### ISSUE THREAD

**Issue by ivanfei-1** [Tampermonkey/tampermonkey#1108]
## Actual Behavior
On OS Catalina the scripts will suddenly disappear. But I doubt if this is tempermonkey's problem, because other plug-in such as user script deletes its scripts simultaneously. 

- OS: (safari 14.0.2 (15610.3.7.1.10, 15610))

**Comment by derjanb** [comment]
Looks like something is clearing app data. Not sure how this can happen. It is however unrelated to Tampermonkey.
