### ISSUE TITLE
Tampermonkey detected that the extension storage is unreliable

### ISSUE THREAD

**Issue by NaturalHarmonia** [Tampermonkey/tampermonkey#1110]
I'm using Tampermonkey on Chrome and it just deleted all my userscripts. I'm getting an error that says "Tampermonkey detected that the extension storage is unreliable!"

**Comment by NaturalHarmonia** [comment]
Okay so everything is back to normal now after chrome crashed and I started it up again.

**Comment by derjanb** [comment]
OK, sounds like this can be closed. There is not much more that Tampermonkey can do than to warn when the extension storage is unreliable.
