### ISSUE TITLE
Tampermonkey Opera uses ESLint in ES5 mode

### ISSUE THREAD

**Issue by Swangie-Errangie** [Tampermonkey/tampermonkey#1112]
(Please fill out the issue template with your details)

## Expected Behavior
Tampermonkey should not give an eslint syntax error when using 'const' in the latest version of Opera.

## Actual Behavior
In the current version of Opera, Tampermonkey is giving an error saying: "eslint: null - Parsing error: The keyword 'const' is reserved". However, userscripts using 'const' execute as intended. The only issue is that the script editor is giving an error.

## Specifications

- Opera 73.0.3856.284
- TM: 4.11.6120
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Const Error
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  For some reason, const isn't working
// @author       You
// @include      *
// @grant        none
// ==/UserScript==

const x = 2;
alert(x);
```
![image](https://user-images.githubusercontent.com/76885647/103483104-07c88a80-4db3-11eb-956b-61c24a896581.png)
![image](https://user-images.githubusercontent.com/76885647/103483153-60982300-4db3-11eb-866a-c7569ffadfeb.png)

**Comment by derjanb** [comment]
This issue should be fixed at TM BETA 4.12.6126. 😅

I'm not sure how long it'll take for the Chrome Webstore team to review the new version, but in the meantime, you can download it from [here](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6126.crx).
