### ISSUE TITLE
Problem in Tampermonkey Beta 4.12.6124 with settings backup.

### ISSUE THREAD

**Issue by JohnD78** [Tampermonkey/tampermonkey#1114]
A way to reproduce the problem.
1. Perform a clean install of Tampermonkey Beta or use Factory Reset in Advanced Mode in Settings.
2. Change something in the settings: for example, select Advanced Mode and set Experimental
Inject Mode to Instant.
3. Export a backup in the utilities as a .zip or as a file by specifying Include Tampermonkey settings.
4. Repeat the first point.
5. Import a backup copy of the settings.
6. The settings from the backup were not applied.
Everything worked correctly in Tampermonkey Beta 4.12.6123.

## Expected Behavior
The settings from the backup should be applied.

## Actual Behavior

The settings from the backup were not applied.

## Specifications

- Chromium:  87.0.4280.88
- TM: Beta 4.12.6124 
- OS: Win7 x64

**Comment by derjanb** [comment]
This issue should be fixed at TM BETA 4.12.6126. 😅

I'm not sure how long it'll take for the Chrome Webstore team to review the new version, but in the meantime, you can download it from [here](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6126.crx).

**Comment by JohnD78** [comment]
Yes, as far as I tested, in TM BETA 4.12.6126 this bug is fixed. Thank you!
