### ISSUE TITLE
Tampermonkey BETA 4.12.6125 stopped working with SteamTradeMatcher script

### ISSUE THREAD

**Issue by KRyouCK** [Tampermonkey/tampermonkey#1116]
SteamTradeMatcher script has ceased to function completely with Tampermonkey BETA.

## Expected Behavior
No issues until updated Tampermonkey BETA 4.12.6125 (2021.01.04)

## Actual Behavior
SteamTradeMatcher script becomes fully worthless with Tampermonkey BETA 4.12.6125 (2021.01.04) Update.

## Specifications
Doesn't matter

## Script
https://www.steamtradematcher.com/userscript
https://www.steamtradematcher.com/res/userscript/stm.user.js

**Comment by derjanb** [comment]
This seems to work fine here. Do you see error messages at the page or Tampermonkey's background page console?

![image](https://user-images.githubusercontent.com/767504/103894192-d6232c80-50ee-11eb-8a6f-978cb0e93732.png)

**Comment by KRyouCK** [comment]
It works a way different :D
SteamTradeMatches script is for these pages *://steamcommunity.com/tradeoffer/new/*source=stm*

For example, when you click on this button https://ibb.co/D5ZgTmx
you will get new window where SteamTradeMatcher script automatically fills in the required cards for trade https://ibb.co/bbtTC4H

But with new Tempermonkey BETA nothing happened https://ibb.co/d7pXfbp

**Comment by derjanb** [comment]
Well you said completely and I showed you that it is running at the given example page `https://www.steamtradematcher.com/userscript` ;-)

Looks like I need to reactivate my Steam account... 

Do you see errors at the page console?

**Comment by KRyouCK** [comment]
Yes
1. With older Tampermonkey, if SteamTradeMatcher script work propertly i got only these errors in console https://ibb.co/j5kXCJf https://pastebin.com/tGDtX4ue
2. With new Tampermonkey BETA 4.12.6125 I got these errors https://ibb.co/d5kqPgC https://pastebin.com/yvgL5Uyb

**Comment by derjanb** [comment]
I've found the issue. Thanks.

**Comment by derjanb** [comment]
This issue should be fixed at TM BETA 4.12.6126. 😅

I'm not sure how long it'll take for the Chrome Webstore team to review the new version, but in the meantime, you can download it from [here](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6126.crx).
