### ISSUE TITLE
Regex fallback favicons bugged with ddgo service

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#1117]
Beta 4.12.6126

Regex includes, resulting in fallback generic favicons being shown, are bugged when ddgo's service is used. The actual regex string flashes in place of the favicon for a split second as the manager page loads, causing the layout to shift jarringly.

**Comment by derjanb** [comment]
Hmm, I saw ddgo answering with status 500 on some requests. Now it's sending 404 again. However, I don't see the regex string flashing, while initially loading the icons was somehow delayed.

Can you please check your console? Does it work now for you? Thanks.

**Comment by narcolepticinsomniac** [comment]
I'm getting 500's. Not sure how any response would relate to what I'm seeing though.


https://user-images.githubusercontent.com/14100003/104058319-895c5600-51c1-11eb-8113-3cbf97eab3bf.mp4

**Comment by narcolepticinsomniac** [comment]
Here's the includes for the real obvious one:

```
// @include      /https?://streamhoe\.online.*/
// @include      /https?://(.*\.)?fe(mbed|url)\.com.*/
// @include      /https?://.*\.mp4.*/
```

**Comment by derjanb** [comment]
Wahhh... I'll check this. Thanks for reporting.
