### ISSUE TITLE
Recursively invoke setTimeout(..., 0) hang browsers; Add minimal setTimeout delay for invokes with deep nesting level 

### ISSUE THREAD

**Issue by tiansh** [Tampermonkey/tampermonkey#1121]
* With https://greasyfork.org/en/scripts/3249-yet-another-weibo-filter installed
* Visit https://www.weibo.com/ and login the website.
* Visit https://www.weibo.com/

## Expected Behavior
It should work, some how.
It works with old versions. I'm not sure which version introduce this problem. But maybe recent week ~ month.

## Actual Behavior
Sometimes the page crash due to OOM.
Sometimes it just make the webpage hang and have a high CPU load.

## Specifications

- Chromium: 87.0.4280.88 (Official Build) (64-bit)
- TM: Tampermonkey BETA 4.12.6126
- OS: Windows 10.0.19042.746 (64 bit)

## Script

https://greasyfork.org/en/scripts/3249-yet-another-weibo-filter?version=873004

![Chrome CPU Usage High](https://user-images.githubusercontent.com/6500326/104808008-254a1b00-57db-11eb-8343-89a7da2e2532.png)

**Comment by derjanb** [comment]
Sorry for the delay. I once had a Weibo account, but it was deleted/archived and it was somehow difficult to create a new account using the same number. 🤷

This is a script bug that was not visible earlier due to a [a Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=402694).

Latest Tampermonkey BETA version now implements `setTimeout(() => ..., 0)` the right way, that's why the code results in an endless loop. So what you basically want is `setTimeout(() => ..., 1)` or even better a `MutationObserver` to wait for `document.body`, don't you?


```JS
        setTimeout(function addStyle() {
          if (!document.body) setTimeout(addStyle, 0);
          else document.body.appendChild(style);
        }, 0);
```

**Comment by tiansh** [comment]
It does work by commenting out these codes. But I'm confused why `setTimeout` is provided by Monkey (otherwise, there is no reason this code works with non-beta version). Also, if I understand correctly to [the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Timeouts_throttled_to_%E2%89%A5_4ms), writing `setTimeout(f, 0)` should be as same as `setTimeout(f, 4)`. So I didn't quite understand why this modification would fix it. Anyway, will this behavior be changed in following beta version? Or should I schedule a fix by changing `0` to `4`?

**Comment by tiansh** [comment]
`MutationObserver` won't work. There is no guarantee the `document.documentElement` is ready when this code executed. And I had to ensure the `style` placed at bottom of `<head>` or in `<body>` so it cascade correctly.

**Comment by derjanb** [comment]
> But I'm confused why setTimeout is provided by Monkey

Pages can monitor timer IDs an cancel timeouts, which now does not affect userscript timers anymore.

```JS
const t = setTimeout(() => null, 0)
for (let i=0; i<t; i++) clearTimeout(i)
```

> setTimeout(f, 0) should be as same as setTimeout(f, 4)

Yes, browsers may round timer values.

> Anyway, will this behavior be changed in following beta version?

The plan is to keep the "correct" implementation as it is now in TM BETA.

> Or should I schedule a fix by changing 0 to 4?

You can also use `unsafeWindow.setTimeout` to keep the current behavior, which however will fail if Chrome bug 402694 is fixed sometime in the future.

**Comment by tiansh** [comment]
I believe the behavior is not a bug of Chrome. As the spec page linked from MDN, it does say:

> If _nesting level_ is greater than 5, and _timeout_ is less than 4, then set _timeout_ to 4.

**Comment by derjanb** [comment]
Good point. I'll try to add this to my implementation.

**Comment by tiansh** [comment]
I had updated my script by replace setTimeout(..., 0) to setTimeout(..., 16). And it seems works on TM beta now.
