### ISSUE TITLE
DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by james-work-account** [Tampermonkey/tampermonkey#1125]
## Summary
Brave's JavaScript console gives out "DevTools failed to load SourceMap" warnings when Tampermonkey BETA is enabled. The warnings go away when it is disabled. I'm not sure if this is an issue with normal Tampermonkey too or not.

## Expected Behavior
This warning does not appear in my JavaScript console.

## Actual Behavior
When Tampermonkey BETA is enabled, I get warnings in my console that look like the following:

<img width="762" alt="Screenshot 2021-01-20 at 22 30 34" src="https://user-images.githubusercontent.com/31282758/105248904-1fec2800-5b6f-11eb-888d-cb476b0df92b.png">

When the extension is disabled, the warnings go away. These warnings appear both on localhost and on live websites (e.g. https://www.google.com/).

## Specifications

- Chromium: 87.0.4280.141 (Official Build) (x86_64)
- TM: v4.12.6126
- OS: macOS 10.15.7

## Script

(Please give an example of the script if applicable.)

N/A

**Comment by maltoze** [comment]
> DevTools failed to load SourceMap: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Same issue here.
