### ISSUE TITLE
Zip/text file export not working

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#1126]
1.change to dark mode according to browser's theme change to dark theme
2.fix export scripts to zip and txt

**Comment by derjanb** [comment]
Using 86.0a1 (2021-01-21) (64-bit) automatic dark mode detection and zip export are working fine.

What is your FF and OS version?

**Comment by Rosabis** [comment]
> Using 86.0a1 (2021-01-21) (64-bit) automatic dark mode detection and zip export are working fine.
> 
> What is your FF and OS version?

Firefox nightly 86
Android 9

**Comment by derjanb** [comment]
Dark mode detection seems to work with FF Nightly 210331. So it seems like they fixed it. 

Regarding the download issue, FF's downloads API doesn't seem to support objectURLs at the moment or has more general issues and using the native way to download the zip simply crashes FF. 
This means unfortunately there is nothing I can do to fix this at the moment.

**Comment by Rosabis** [comment]
> Dark mode detection seems to work with FF Nightly 210331. So it seems like they fixed it.
> 
> Regarding the download issue, FF's downloads API doesn't seem to support objectURLs at the moment or has more general issues and using the native way to download the zip simply crashes FF.
> This means unfortunately there is nothing I can do to fix this at the moment.

But Violentmonkey have fixed that issue

**Comment by Rosabis** [comment]
This happened again in firefox nightly 106.0a1

**Comment by derjanb** [comment]
Should be fixed at 4.19.6179 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons`
