### ISSUE TITLE
Hi I am a coder,i hope tempermonkey can add require script run time

### ISSUE THREAD

**Issue by TangJin9487** [Tampermonkey/tampermonkey#1131]
example:

i have a script must run on document-start

but my 2nd script is run default

i need let 2 script to 1 script

but if i set to document-start

script 2 will error

if i set to default

1st script will error

please help me

i hope require can set what time run

**Comment by erosman** [comment]
Here is an example ...

```js
// ==UserScript==
// @name         New Userscript 
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*.example.com/*
// @run-at       document-start
// ==/UserScript==


// the code for script 1

window.addEventListener('DOMContentLoaded', (event) => {
 
 // the code for script 2
 // 'DOMContentLoaded' is like document-end
});
```

or ....

```js
// ==UserScript==
// @name         New Userscript 
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*.example.com/*
// @run-at       document-start
// ==/UserScript==


// the code for script 1

window.addEventListener('load', (event) => {
 
 // the code for script 2
 // 'load' is like document-idle
});
```

**Comment by TangJin9487** [comment]
umm it  no work
it will say something var and require is undefined

**Comment by TangJin9487** [comment]
and 2 th script no any work

**Comment by erosman** [comment]
> it will say something var and require is undefined

If the scripts have different `@require`, then it needs more adjustment. Previous answer was just an **example**.

Full code must be seen for a detailed answer.

**Comment by derjanb** [comment]
Thanks @erosman for giving support here.
