### ISSUE TITLE
DOMContentLoaded doesn't work 

### ISSUE THREAD

**Issue by Purfview** [Tampermonkey/tampermonkey#1142]
Heyo @derjanb,

I got report that my userscript stopped working on TM, found that problem is (no errors in console):
`window.addEventListener('DOMContentLoaded', addDarkmodeWidget);`

This works:
`window.addEventListener('load', addDarkmodeWidget);`

Script is there:
https://github.com/Purfview/Darkmode-User

**Comment by derjanb** [comment]
Please add ```// @run-at document-start` to the script's header.

**Comment by Purfview** [comment]
That works. Thank you.
