### ISSUE TITLE
Where is the latest version?

### ISSUE THREAD

**Issue by jb222** [Tampermonkey/tampermonkey#1143]
According to the website, version 4.12.6127 is available since February 5th but it's still not in the Chrome store?

**Comment by derjanb** [comment]
Status: "Pending review" 🤷

However, you can download it from [here](https://www.tampermonkey.net/crx/tampermonkey_beta_4_12_6127.crx) and drag and drop it to chrome://extensions.

**Comment by jb222** [comment]
Wow! Quick reply! Thanks.
