### ISSUE TITLE
 Enhanced UI-interaction: The toolbar icon should change instantly/real-time 

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1146]
<img align=right width=40% src=https://user-images.githubusercontent.com/10995302/107455345-a4880000-6b89-11eb-8f59-7731ab17fd4f.png>

Toggle enable state: 

1. Or clicking  `✔️/❌` button in the Popup of Tampermonkey.
2. `chrome://extensions/shortcuts#:~:text=Toggle enable state`

Currently, you need `F5 Reload` the page to make the icon change.

Especially using hotkeys to `Toggle enable state` ,  very need to be able to change icon in real time. Otherwise, it is difficult for you to perceive the state instantly.

**Comment by derjanb** [comment]
This is kind of "functions as intended". Icon and bagde show show the current state, which in this case means Tampermonkey and scripts **were** executed at the tab. 

Debatable is whether enabling and disabling Tampermonkey should trigger a reload if "Auto reload pages" is enabled.
