### ISSUE TITLE
The scripts I use have stopped working since yesterday (18feb21) on firefox

### ISSUE THREAD

**Issue by julioalonsoa** [Tampermonkey/tampermonkey#1150]
(Please fill out the issue template with your details)

## Expected Behavior
Planets Nu related scripts load on planets.nu pages when loaded.

## Actual Behavior
Scripts do not load, game GUI is unchanged. Tampermonkey shows fine and shows the scripts as active

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)
![Screenshot 2021-02-18 at 12 29 35](https://user-images.githubusercontent.com/79258011/108350838-fe6d7300-71e4-11eb-8e05-431c4051e3ea.png)

**Comment by NicoleRauch** [comment]
Can confirm! Did a Firefox update today and now my scripts don't run any more 😱

**Comment by derjanb** [comment]
An initial test showed, that one of the scripts is injected and started. So can you please add more details? Do you see errors at the Javascript console? Is this a general problem with all scripts running at this domain? Has a change at the websize made the scripts incompatible?

![image](https://user-images.githubusercontent.com/767504/108609876-4b15a180-73d1-11eb-9d21-f12861667faa.png)

**Comment by NicoleRauch** [comment]
In my case, it seems that my computer had some weird networking issues, which I was able to resolve this morning. At the same time, the scripts started working again...
Sorry that I could not contribute more to this issue.

**Comment by julioalonsoa** [comment]
@derjanb thank you for your help. It must have been something with the site. The scripts were shown by tampermonkey as running but did not actually show up on the game's screen. I have found a work around using a more modern version on the game (planets.nu instead of play.planets.nu). Scripts work properly on that url.

Thanks again for taking the time.

**Comment by derjanb** [comment]
OK, closing this then..

**Comment by NicoleRauch** [comment]
I'm sorry, but I need to get back to this again...

I restarted Firefox and again the Tampermonkey scripts are not running.

The site in question is https://www.wanikani.com/dashboard (you need an account if you want to access the page).

This is my console:

![image](https://user-images.githubusercontent.com/436499/109144223-30d91c00-7761-11eb-8679-b7de755ae321.png)

That does not look very suspicious to me tbh...

This is Tampermonkey:

![image](https://user-images.githubusercontent.com/436499/109144302-4a7a6380-7761-11eb-8389-431ef4b77b41.png)

It tells me that 14 scripts are running but I don't see the expected changes on the page.

The version numbers are:
Firefox: 85.0.2
OS: MacOS 10.15.7
TM: 4.11.6120

Other MacOS users with the same Firefox version tell me that they don't encounter any issues. So it seems to be something specific to my machine, but how can I figure this out? Why does Tampermonkey silently stop executing all of the scripts without giving any hints? Thanks for any insights :-)
