### ISSUE TITLE
Add real-time Highlighting to the CodeMirror-editor !

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1151]
## Actual Behavior
- No real-time/temporary highlighting at all, 
(only one situation at present, i.e. Manual `Ctrl+F`+`Enter` can be highlighted.)

## Expected Behavior
- Can real-time/temporary highlighting.
- Highlighting when selecting ! (It would be best if it can be highlighted under the cursor like [ Stylus ](https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne) CodeMirror-editor ) 

- The scroll-bar will also display the highlight indicator in real time !

> I personally think that real-time highlighting should be the basic function of the code-editor, because it has very practical and obvious effects!

　
![Highlighting](https://user-images.githubusercontent.com/10995302/108360236-e836d580-722b-11eb-88fc-a25c3db2b008.gif)

　
Stylus extension, Also use CodeMirror as editor, highlight is perfect, we can refer to !
He should have attached a CodeMirror plugin to achieve this function, but I don't know what plugin it is ... ^_^

https://chrome.google.com/webstore/detail/clngdbkpkpeebahjckkjfobafhncgmne
https://github.com/openstyles/stylus

**Comment by darkred** [comment]
@derjanb Maybe you'd like to consider my suggestions in #587 as a follow-up to this?
i.e. in Editor|"Search for" (Ctrl+F) to display: 
- the currently highlighted position and 
- the total found occurrences count ?

Just like Chrome browser's `Find`:
![12345](https://user-images.githubusercontent.com/723651/108706106-cd5bae00-7516-11eb-9124-810927f234f0.gif)

I find both features equally useful.

_For reference, the mentioned Stylus extensions offers the latter: [screenshot](https://user-images.githubusercontent.com/723651/108705457-0ba49d80-7516-11eb-8db1-bf031683d75d.gif)_

**Comment by dnknn** [comment]
@darkred 

> * the currently highlighted position and

This is not necessary, I have already responded to you in [your issue](https://github.com/Tampermonkey/tampermonkey/issues/587#issuecomment-783348198)


> * the total found occurrences count ?

This is a must!

**Comment by dnknn** [comment]
@darkred 

> Maybe you'd like to consider my suggestions in #587 as a follow-up to this?

In fact, the issue I raised is not very related to the issue you raised. What I am talking about here is instant matching search, which can easily highlight a certain function/keyword, etc. in the context, which is obviously more useful!

And the search counter you proposed, it only works in the case of manual search, 
i.e. `Ctrl+F` or `Ctrl+F3` or `Shift+F3`



> * the currently highlighted position and

This is not necessary, I have already responded to you in [your issue](https://github.com/Tampermonkey/tampermonkey/issues/587#issuecomment-783348198)


> * the total found occurrences count ?

This is a must!

**Comment by darkred** [comment]
Your issue has been approved by derjanb, hence the addition of the milestone label.

I mentioned my issue hoping to be considered as a *follow-up*, not as part of your issue. 
And, I never asked for your opinion. Don't try to downplay my suggestion with the "performance analysis" that you did in my issue. You are not the TM developer.

**Comment by derjanb** [comment]
4.12.6128 has a new setting to control automatic highlighting -> "Highlight selection matches"
