### ISSUE TITLE
toampermonkay mi nie działa 

### ISSUE THREAD

**Issue by pepedddh** [Tampermonkey/tampermonkey#1152]
jak klikam w ikonke to pokazuje si ekulko ladowania https://prnt.sc/101s8s5
a jak sie zaladuje to wyskakuje mi komunikat https://prnt.sc/101slc4
co mam zrobić ?

**Comment by derjanb** [comment]
Are there any errors at the background page console? -> https://www.tampermonkey.net/faq#Q600
