### ISSUE TITLE
Randomly getting "Error handling response: TypeError: Cannot read property 'userscript_search_url' of undefined" errors in backgroung.html console

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1157]
I randomly get this error in the console:

```
Error handling response: TypeError: Cannot read property 'userscript_search_url' of undefined
    at p (.../background.js:261:379)
    at .../background.js:264:37
```

and then none of the userscripts appears to run. Restarting Tampermonkey fixes the problem. What does the error mean?

## Specifications

- Chromium: 88.0.705.74
- TM: 4.12.6128 (beta)
- OS: Windows 10 update 1909

**Comment by derjanb** [comment]
I found a code path that could run before the internal configuration is loaded. Fortunately it's not a critical problem.

Thanks for reporting. :-)
