### ISSUE TITLE
[HELP]/[PROPOSAL] @user-vars

### ISSUE THREAD

**Issue by Lcfvs** [Tampermonkey/tampermonkey#1158]
Hi,

Sorry if it's already discussed but is there a way to provide some user variables, only known by that userscript, please?

The goal is to provide a way, to the users, to customize a userscript behavior but without altering it and to indicate that requirements.

I think to something like this

```js
// @user-vars varName
```

Thanks in advance.

**Comment by Lcfvs** [comment]
I tried using the `GM_info.script.options.comment` but the `@grant` of `GM_info` kills the JS `Symbol.for()`

**Comment by derjanb** [comment]
`GM_info` is available even in `@grant none` mode. 

> @grant of GM_info kills the JS Symbol.for()

Do you have some example code?

**Comment by Lcfvs** [comment]
> `GM_info` is available even in `@grant none` mode.

Hum, nice, it works, without the `@grant`!

> Do you have some example code?

Sure, the working script
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Lcf.vs
// @match        *://*/*
// @grant        none
// @run-at       document-idle
// @noframes
// ==/UserScript==

(function() {
  'use strict';
  const comments = GM_info.script.options.comment.split('\n')
  const vars = new Map(comments.map(comment => comment.split('=')))
  const key = vars.get('key')

  if (!vars.has('key') || !vars.has('pass')) {
     throw new ReferenceError('Missing userscript comment')
  }

  if (key in window) {
     throw new ReferenceError('Conflictual userscript comment key')
  }

  Object.defineProperty(window, Symbol.for(key), {
    value: pass => {
      if (pass !== vars.get('pass')) {
        throw new ReferenceError('Invalid userscript pass')
      }

      console.log('Do something with this userscript')
    }
  })
})();
```

The comment to trigger
```
key=userscript-key
pass=userscript-pass
```

Then, into the console
```js
window[Symbol.for('userscript-key')]('userscript-pass') // 'Do something with this userscript'
```

**Comment by Lcfvs** [comment]
That a few tricky, to use the comment for that... that's why this proposal. ;)

**Comment by derjanb** [comment]
> @grant of GM_info kills the JS Symbol.for()

The script works with ```@grant unsafeWindow``` or ```@grant GM_info``` as well (see below). 

So you could use GM_setValue which is designed to handle user-specific configuration data. You could also use a "lib" like GM_config to avoid writing your own config UI: https://sizzlemctwizzle.github.io/GM_config/

Is that an option?

```JS
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Lcf.vs
// @match        *://*/*
// @grant        unsafeWindow
// @run-at       document-idle
// @noframes
// ==/UserScript==

(function() {
  'use strict';
  const comments = GM_info.script.options.comment.split('\n')
  const vars = new Map(comments.map(comment => comment.split('=')))
  const key = vars.get('key')

  if (!vars.has('key') || !vars.has('pass')) {
     throw new ReferenceError('Missing userscript comment')
  }

  if (key in unsafeWindow) {
     throw new ReferenceError('Conflictual userscript comment key')
  }

  Object.defineProperty(unsafeWindow, Symbol.for(key), {
    value: pass => {
      if (pass !== vars.get('pass')) {
        throw new ReferenceError('Invalid userscript pass')
      }

      console.log('Do something with this userscript')
    }
  })
})();
```

**Comment by Lcfvs** [comment]
Thanks, your solution, using `unsafeWindow` is working but, in that case, I don't understand why it works with mine too (using `@grant none` + in-script `window`).

The GM_config doesn't seems to be a secure solution because the local storage which can be read by websites scripts and/or other userscripts.

But about the `GM_setValue()`, it seems fine, once initialized.

**Comment by Lcfvs** [comment]
Combining our solutions, this one is ok
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Lcf.vs
// @match        *://*/*
// @grant        unsafeWindow
// @grant        GM_setValue
// @grant        GM_getValue
// @run-at       document-idle
// @noframes
// ==/UserScript==

(function() {
  'use strict';

  if (GM_getValue('key') === undefined && GM_getValue('pass') === undefined) {
    GM_setValue('key', '')
    GM_setValue('pass', '')

    throw new ReferenceError('Missing userscript storage key/pass')
  }

  if (GM_getValue('key') in unsafeWindow) {
     throw new ReferenceError('Conflictual userscript storage key')
  }

  Object.defineProperty(unsafeWindow, Symbol.for(GM_getValue('key')), {
    value: pass => {
      if (pass !== GM_getValue('pass')) {
        throw new ReferenceError('Invalid userscript pass')
      }

      console.log('Do something with this userscript')
    }
  })
})();
```

**Comment by derjanb** [comment]
> The GM_config doesn't seems to be a secure solution because the local storage

According to the wiki it uses GM_get/setValue if available. https://github.com/sizzlemctwizzle/GM_config/wiki

**Comment by Lcfvs** [comment]
Yeah, sorry, I misread it... but what about why [this code](https://github.com/Tampermonkey/tampermonkey/issues/1158#issuecomment-786661178) is working without `unsafeWindow`?

**Comment by Lcfvs** [comment]
Oh, ok, thanks
