### ISSUE TITLE
@downloadURL behavior have no sense

### ISSUE THREAD

**Issue by jeisonfriedman** [Tampermonkey/tampermonkey#1159]
Hello team. I'm not an English speaker, so apologizes...

I've changed the version format for my scripts (ie: before 21.0226.120528, now 21.058.12548), and I want that my installed scripts (many locations and devices) take that new format when TM update them. The problem?

First, I could notice TM @updateURL ignore right zero in @version tag, and just evaluate the next numbers (226, 58). Because of this, 21.058 is evaluated as minor that 21.0226. I think this is an error, but I thought maybe I was wrong. So I say to myself: "That's why the genious behind TM gave us the @downloadURL tag! I will solve this issue using it!" But then I faced the second problem.

My script has this tags order:

@updateURL ...
@downloadURL ...

So, I programmed my server to response with two different versions of the script: the first one, containing an increased @version number of my first version format (ie: 21.0325.120528), and the second with the new @version number and format (21.058.12548).

My server do this: in the first request (ie: @updateURL), it checks if a certain file exists; if not, creates it and responses the first version of script. At the nexts requests (ie: @downloadURL), the server responses the last and new version of my script, including the new version format.

When I tested in the web browser (from URL bar), it worked perfect! I was exited for get the solution to my problem! But, sadly, I noticed that TM didn't update the script when I check for updates. Why? Well, after many tests, I can say that TM is evaluating twice the @version number in the script: with @updateURL and also with @downloadURL! That destroyed my simple and "elegant" solution! I was so sad... :-(

I don't know you, but I think this is a big mistake! What's the propose of having those diferents tags, if both do the same? I mean, @downloadURL shouldn't care the @version number, cause this is the @updateURL job, right?

Please, fix this behavior, or tell me what must I do. I will apreciate it!

- Chromium: 88.0.4324.190
- TM: 4.11
- OS: Windows 10

**Comment by derjanb** [comment]
Version comparison follows Mozilla's toolkit version format -> https://developer.mozilla.org/en-US/docs/Toolkit_version_format

> Please, fix this behavior,

Not sure, what to fix.The first request tries to get meta information and second one loads the complete script. And of course both check that the version number is increased for sanity reasons.

**Comment by jeisonfriedman** [comment]
Thanks for answering!

Could you explain what are those "sanity reasons"? And, if @downloadURL also checks the version number, why having two meta tags? Is it possible to add another tag (ie: @disableDownloadCheck) to avoid that second check?

I think that my case shows you a good reason for enable that capability! Don't you?

**Comment by derjanb** [comment]
`@updateURL` is used for an initial update check. Servers can send only meta data instead of a potentially some MB large script.

> Is it possible to add another tag (ie: @disableDownloadCheck) to avoid that second check?

Unfortunately not, because automatic version downgrades are something nobody expects.

> I've changed the version format for my scripts (ie: before 21.0226.120528, now 21.058.12548),

Why not just update to 21.**1**58.12548?

**Comment by fish-404** [comment]
> Version comparison follows Mozilla's toolkit version format -> [developer.mozilla.org/en-US/docs/Toolkit_version_format](https://developer.mozilla.org/en-US/docs/Toolkit_version_format)
> 
> > Please, fix this behavior,
> 
> Not sure, what to fix.The first request tries to get meta information and second one loads the complete script. And of course both check that the version number is increased for sanity reasons.

Mozilla's document link broken, may reference this one[Manifest Version Format-Mozilla|MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version/formatl)
