### ISSUE TITLE
GM_addElement cannot select the appropriate body

### ISSUE THREAD

**Issue by chuggafan** [Tampermonkey/tampermonkey#1161]
## Expected Behavior
GM_addElement will append to the document body when I specify I want the element in the document body, as specified by the GM_addElement(parent_node, tag_name, attributes) documentation
If I'm doing something wrong, as shown below (my whole code), please inform me, I'm not really a JS guy, just a guy trying to write an improvement script for his day-to-day life.
## Actual Behavior
If I leave out document.body, the input I add via GM_addElement is added to the head, if I leave it in, it does not get input and I get:

"content.js:20 content: error adding script DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name."

I know there's a way to do what I'm doing without having issues but that was lost from me and CSP is now hitting me when I try to redo my machinations.

## Specifications

- Chromium: 86.0.4240.198
- TM: 4.11
- OS: 10.0.19042 N/A Build 19042

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        mail.google.com/mail/u/*
// @grant        GM_addElement
// ==/UserScript==

GM_addElement('script',
              {
    textContent: 'function selectAllFunc() {document.querySelectorAll("input").forEach(function(element) { element.checked = true});}'
});
GM_addElement(document.body, 'input', {
    type: "button",
    value: "Select All",
    name: "select",
    onclick: "selectAllFunc()"

});
```
Please note: this appears to be a thing in addElement, 

```js
(document.head || document.body || document.documentElement || document).appendChild(a);
```

is used, however there should be an option for selecting from whatever is passed in, so maybe a version with d in front so that if the user actually passes in this option it works.

**Comment by derjanb** [comment]
This will be supported by 4.12 which will be released soon. Please use the BETA version in the meanwhile.
