### ISSUE TITLE
Interacting with the textarea in storage when the data is too big crashes Tampermonkey

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1162]
A userscript I use has to cache some API responses (to enhance performance) which expire after some time. Because I use it a lot, it has stored ~8MB of data.

If I go to storage and try to somehow interact with the textarea, the tab freezes. The script also prevents others from running (only when running on the same page as them) occasionally (extension's console doesn't say anything about it), so I have to restart Tampermonkey each time. Clearing the cache resolves this issue.

**Comment by jb222** [comment]
Isn't local storage limited to 5MB per domain? 
A recent [article](https://web.dev/storage-for-the-web/#:~:text=LocalStorage%20should%20be%20avoided%20because,not%20be%20used%20for%20storage.) on this.

**Comment by double-beep** [comment]
@jb222 it's Tampermonkey's storage, not `localStorage`.

**Comment by jb222** [comment]
You're right, sorry for that.
