### ISSUE TITLE
Add on/off setting for menu commands appearing in the context menu

### ISSUE THREAD

**Issue by BravoBravissimo** [Tampermonkey/tampermonkey#1164]
Please add an on/off setting for controlling whether menu commands should appear in the context menu: TM-wide, per-script, or both.

**Comment by belnet** [comment]
I join the request of the topicstarter.
otherwise, you will have to delete the addon, this item in the menu disturbs me so much.
thank!

**Comment by derjanb** [comment]
Will be fixed soon.

In the meanwhile you can also revert to the old Firefox version here: https://addons.mozilla.org/firefox/addon/tampermonkey/versions/

**Comment by belnet** [comment]
thanks, but rollback is difficult. For now, I just turned off your addon so that it does not interfere with surfing and every day I check AMO for updates with a fix.

**Comment by derjanb** [comment]
FYI: Latest Tampermonkey BETA (4.12.6131) includes a fix for this.

**Comment by derjanb** [comment]
> when to wait for a stable version?

@belnet A new version was released.
