### ISSUE TITLE
New dashboard topbar announcements are hidden by already existing announcements

### ISSUE THREAD

**Issue by makyen** [Tampermonkey/tampermonkey#1165]
## Expected Behavior
I expect to see any and all announcements, even multiple announcements which are raised at the same time (e.g. announcement of a new Tampermonkey version and the announcement that the currently edited script has been saved, passes/fails eslint, etc.).

## Actual Behavior
Only one announcement is seen at a time. If any other announcements are added to the page at the same time, they are hidden.

An example is when there's an announcement of the availability of a new Tampermonkey version, then *every other announcement* is hidden until the browser is restarted and a Tampermonkey update performed (if the user has set such updates to be automatic). It is the user's choice when to restart their browser and/or update Tampermonkey. Tampermonkey operation shouldn't be degraded in order to encourage the user to restart/upgrade Tampermonkey (degrading functionality probably isn't the intent, but it's the effect).

## Specifications

- Firefox 86.0 (64-bit)
- TM: 4.11.6120
- Windows 10

## Script
not applicable

## Resolution
There are, of course, multiple ways which seeing all announcements could be implemented, including having the announcements be dismiss-able, show up sequentially, etc., if the desire is to only show one announcement at a time.

From an implementation point of view, probably the easiest thing to implement is just to have all announcements which are added to the DOM be displayed at the same time, with new ones just pushing older ones down the page. Doing this side-steps any additional need to manage these announcements in JavaScript beyond what already exists. In fact, it can be achieved with just changes to the CSS.

Currently, the announcements end up stacked on top of each other at exactly the same place in the page, which results in only the last one in the DOM being displayed. The issue is that the `position: fixed; top:0; left:0; z-index:1000;`  is placed on the `<span class="global_hint">` for each announcement, instead of on the `<div class="status">` wrapper which contains all of the announcements.

One solution to this is to change the CSS from:
```
.global_hint {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  text-align: center;
  z-index: 1000;
}
```
to:
```
.status {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 1000;
} 
.global_hint {
  width: 100vw;
  text-align: center;
} 
```
I have not looked through the full source to determine that the above classes are used only for these elements, so the possibility that they are used elsewhere should be double-checked.

**Comment by derjanb** [comment]
FYI: Latest Tampermonkey BETA (4.12.6131) contains a fix for this. 
Thanks for reporting and the detailed bug report.
