### ISSUE TITLE
Restore from zip never completes with latest TM beta in both Chrome and Firefox

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#1166]
Using latest Tampermonkey beta 4.12.6129 (and 4.12.6131) in Chrome 89/Firefox 86 with windows 10.

The issue is with latest TM beta (both Chrome and Firefox), the restore from zip never completes.
<sup>*(but with TM stable 4.11 the procedure completed immediately, within seconds, in both Chrome/Firefox).*</sup>

I made with TM beta a zip backup file *(Utilities>Zip>Export, having all 3 checkboxes in 'General' group checked)*.
Then in a fresh Chrome/Firefox profile, I re-installed TM beta and tried to import the zip:
the procedure never completed, it remained at "Please wait" indefinitely, without ever displaying the "Import" window to confirm importing : 
![2021-03-03_002452](https://user-images.githubusercontent.com/723651/109723563-e9b2b700-7bb6-11eb-8d7b-cab970327516.jpg)
I waited a lot, and even repeated the procedure multiple times, without success.
There was no error in Console at that time, the last TM message was: `porter: read from zip Tampermonkey.global.json` :

<details>
<summary>Console screenshot</summary>

![](https://user-images.githubusercontent.com/723651/110207320-59f95b00-7e8b-11eb-85aa-5395759e0868.jpg)
</details>

@derjanb If you'd like to test, I could email you my TM zip backup.

**Comment by derjanb** [comment]
> If you'd like to test, I could email you my TM zip backup.

@darkred Yes, please send it to support@tampermonkey.net. Thanks.

**Comment by darkred** [comment]
I've just emailed it to you. Thank you.

**Comment by derjanb** [comment]
I'm able to reproduce the issue. Thank you very much for your help!

**Comment by darkred** [comment]
Thank you fixing this in the new beta.
