### ISSUE TITLE
Highlight selection matches option will not save

### ISSUE THREAD

**Issue by Vantageright** [Tampermonkey/tampermonkey#1169]
## Expected Behavior
Settings > Editor > Highlight selection matches dropdown saves my selection.

## Actual Behavior
Settings > Editor > Highlight selection matches dropdown does not save my selection.

## Specifications
Firefox 84.0
- TM: 4.12.6130
- OS: W10

**Comment by derjanb** [comment]
Please use the save button at the bottom of the section.

**Comment by Vantageright** [comment]
I did, that didnt do anything.

**Comment by derjanb** [comment]
🙈

**Comment by derjanb** [comment]
Note: the setting itself is working only visual representation is broken.

Thanks for reporting.
