### ISSUE TITLE
JS file not detected when served from localhost on Chromium 89.0.4389.72/Brave 1.21.73

### ISSUE THREAD

**Issue by gmcheems** [Tampermonkey/tampermonkey#1170]
## Expected Behavior
Expected tampermonkey to prompt me to install the script.

## Actual Behavior
Chromium/Brave downloads the file and saves it to disk.

## Specifications

- Chromium 89.0.4389.72/Brave 1.21.73
- Windows 10

Script is served from http://localhost:8080/dist/myscript.user.js

**Comment by gmcheems** [comment]
Funny enough, if i visit http://localhost:8080/dist/myscript.meta.js , Brave displays it in the browser, doesn't prompt me to download/save it.

**Comment by gmcheems** [comment]
Also if I go to Utilities > Install from URL and enter `http://localhost:8080/dist/myscript.user.js` and click Install, it errors with
```
Unable to load user script from URL: http://localhost:8080/dist/myscript.user.js
```

**Comment by gmcheems** [comment]
Ok, found an important detail. If I instead of visiting localhost:8080, I visit my machine's IP address, `http://192.168.1.11:8080/dist/myscript.user.js` , everything works. Tampermonkey prompts me to install it.

**Comment by derjanb** [comment]
A quick test using a node based server at localhost:8080 showed now issue [1].

Does the background page devtools network show an error? [2]

[1]
![image](https://user-images.githubusercontent.com/767504/110288627-9d1d1080-7fe8-11eb-9599-07ccf30851a7.png)

[2]
![image](https://user-images.githubusercontent.com/767504/110289032-259bb100-7fe9-11eb-8df0-f0570e41b4be.png)

**Comment by gmcheems** [comment]
I created a new Brave profile with only Tampermonkey installed. I can see the request in the network tab, but it's blocked.

![image](https://user-images.githubusercontent.com/50040855/110424643-1c562700-8071-11eb-9a97-b8bf66ac6746.png)

![image](https://user-images.githubusercontent.com/50040855/110424674-25df8f00-8071-11eb-8635-2f26e1e8d801.png)

I can see the request in the server

![image](https://user-images.githubusercontent.com/50040855/110424706-35f76e80-8071-11eb-8b9f-0e723a46533d.png)

But tampermonkey doesn't show the install screen. Instead Brave just asks me where to save the file.

**Comment by gmcheems** [comment]
Ok, good news. Just upgraded to Brave 1.21.74 Chromium: 89.0.4389.72 and it works now.

Seems like 1.21.73 broke some stuff

https://github.com/brave/brave-browser/issues/14473
https://github.com/brave/brave-core/pull/8168

In your screenshot, you're using 1.21.74.

**Comment by derjanb** [comment]
> In your screenshot, you're using 1.21.74.

Yes, this was the version I got when updating... 

> Ok, good news. Just upgraded to Brave 1.21.74 Chromium: 89.0.4389.72 and it works now.

😅
