### ISSUE TITLE
Tampermonkey unable to stop ads on https://www.watchmovies5.com.pk/

### ISSUE THREAD

**Issue by usama115** [Tampermonkey/tampermonkey#1174]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Tampermonkey is a userscript manager. Please contact the script developer if a script does not work. If there is a general problem with Tampermonkey then he will come back to me.
