### ISSUE TITLE
Calling another GM extension from registered menu command callback doesn't work

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1175]
(Please fill out the issue template with your details)

## Expected Behavior
GM_... function call

## Actual Behavior
No action

## Specifications

- Firefox 54.0.1
- TM: 4.11.6120
- OS: Win 8.1/x64

## Script

```
GM_registerMenuCommand('Command', function() {
  GM_setClipboard('TEST', 'text');
});

```
fails. If it's not a bug but known limitation, is there a trick or makeshift to run the callback outside of the GM_registerMenuCommand context?

**Comment by derjanb** [comment]
This is working fine here using FF 52 and 56. Can you please retry with a new clean profile? Thanks.

```JS
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*/*
// @grant        GM_registerMenuCommand
// @grant        GM_setClipboard
// ==/UserScript==

(function() {
    'use strict';

    GM_registerMenuCommand('Command', function() {
        GM_setClipboard('TEST', 'text');
    });
})();
```

**Comment by trumpeta** [comment]
I can confirm tha nested GM_setClipboard call works in FF Legacy with clean profile.
Any idea why it fails on the established profile? Any hints how to track it down, detailed logging?
