### ISSUE TITLE
option for manual Google Drive update

### ISSUE THREAD

**Issue by BloodyRain2k** [Tampermonkey/tampermonkey#1177]
## Expected Behavior
While having GDrive as sync active, updating a script in one browser should reflect the changes in another.

## Actual Behavior
Script won't be updated at all and I can't seem to find a way to force an update that involves GDrive.
And this is across all browsers for all scripts the same.
The only time the sync download seems to work is when I first activate it, after that it stops working.

I'm also wondering if this is because it also asks me everytime I start a browser to pick a google account to use, because I somehow accidentally logged in with two and now I don't know how to undo that...
And I do remember that this used to work before, but the last time I actively paid attention to sync was like a year ago, and there's been a dozen updates to all parts involved, so yeah...

## Specifications
- Win 7 x64 (7601)
- Firefox 68.12.0esr (64-bit) / TM: 4.12.6130
- Chromium Portable 61.0.3153.0 (Official Build) (64-bit) / TM: 4.11
- Google Chrome 89.0.4389.82 (Official Build) (64-bit) / TM: 4.11

## Proposal
There's the list of actions when one or more scripts are selected in the Dashboard.
Could a "Cloud Update" action be added there so TM checks if there's a newer version in the cloud and if not upload it?
Just in case.

**Comment by derjanb** [comment]
Closed in favor of #1282
