### ISSUE TITLE
TM popup disapeared since 4.12.6132 in firefox nightly android

### ISSUE THREAD

**Issue by Rosabis** [Tampermonkey/tampermonkey#1188]
Use addons collenction to install TM
1.Click Menu key when you open a tab
2.Click add-ons
3.Shows nothing since 4.12.6132
![Screenshot_2021-03-22-15-43-41-052_org mozilla fenix](https://user-images.githubusercontent.com/32984303/111957519-10fe0380-8b27-11eb-9e8f-f66c10cfe09d.png)

**Comment by Rosabis** [comment]
Same solution as firegox pc

**Comment by derjanb** [comment]
You mean issue #1181, right?

**Comment by Rosabis** [comment]
> You mean issue #1181, right?

Yes,the same solution as #1181

**Comment by Rosabis** [comment]
> You mean issue #1181, right?

By the way, when do you plan to fix the export script to local? This problem exists in firefox nightly for a long time
