### ISSUE TITLE
Feature: add expiration date option to GM_setValue()

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1189]
Currently, if userscripts store some data which after some time should be removed (e.g. an access token that expires or some API response that's cached) they have to handle it on their own. Instead, can we have an `expirationDate` option (e.g. `GM_setValue('cache_key', 'cache_value', { expirationDate: new Date('...').getTime() })`)?

**Comment by jonnytest1** [comment]
i dont think this feature should be within the scope of tampermonkey 🤔 writing a small wrapper for GM_get/setValue is also not really a big deal

**Comment by derjanb** [comment]
Hmm, it's really so special and easy to implement that it wouldn't be of much use to other userscripts. Sorry.

**Comment by jonnytest1** [comment]
`
 class StorageImplementationClass {

            /**
             *
             * @param {import('./storage').StorageBase} base
             */
            constructor(base) {
                this.base = base;
                for(let i in base) {
                    if(i !== 'get' && i !== 'set') {
                        let val = base[i];
                        if(typeof val === 'function') {
                            val.bind(this);
                        }
                        this[i] = val;
                    }
                }
            }
            g(identifier, standard) {
                return this.base.get(identifier, standard);
            }

            s(identifier, element) {
                return this.base.set(identifier, element);
            }

            p(identifier, value, options = {}) {
                options.default = options.default || [];
                if(options.mapKey) {
                    options.default = {};
                }
                let storageObj = this.base.get(identifier, options.default);
                let ar = storageObj;
                if(options.mapKey) {
                    if(ar[options.mapKey] === undefined) {
                        ar[options.mapKey] = [];
                    }
                    ar = ar[options.mapKey];

                }
                ar.push(value);
                this.base.set(identifier, storageObj);
            }

            /**
            * @param { String } identifier ""
            * @param { String } key ""
            * @param { any } value ""
            * @param { any } standard ""
            * @returns {any}
            */
            setValue(identifier, key, value, standard = {}) {
                let obj = this.base.get(identifier, standard);
                obj[key] = value;
                this.base.set(identifier, obj);
            }

            removeWhere(identifier, filterFunction) {
                let elements = this.base.get(identifier, []);
                elements = elements.filter(el => !filterFunction(el));
                this.base.set(identifier, elements);
                return elements;
            }
            /**
             *
             * @param {string} identifier
             * @param {*} filterFunction
             * @param {{mapKey?:string}} [options]
             */
            filter(identifier, filterFunction, options = {}) {
                let elements = this.base.get(identifier, []);
                let array = elements;
                if(options.mapKey) {
                    if(!elements[options.mapKey]) {
                        elements[options.mapKey] = [];
                    }
                    array = elements[options.mapKey].filter(filterFunction);
                    elements[options.mapKey] = array;
                } else {
                    array = elements.filter(filterFunction);
                    elements = array;
                }

                this.base.set(identifier, elements);
                return array;
            }

            /**
             * @type {import("./storage").filterFunction}
             */
            static filterDaysFunction(days, options = {}) {
                return (el, index, array) => {
                    if(options.keepLatest) {
                        const sorted = [...array].sort((a, b) => b.timestamp - a.timestamp);
                        return sorted[0].timestamp === el.timestamp || el.timestamp > Date.now() - (1000 * 60 * 60 * 24 * days);
                    }
                    return el.timestamp > Date.now() - (1000 * 60 * 60 * 24 * days);
                };
            }

        }
        
        const tempermonkeyStorageWrapper=new StorageImplementation(
         {
            set: (identifier, element) => {
                if(window['GM_setValue']) {
                    window['GM_setValue'](identifier, element);
                } else {
                    localStorage[identifier] = JSON.stringify(element);
                }
                return element;
            },
            /**
            * @param { String } identifier ""
            * @param { any } standard ""
            * @returns {any}
            */
            get: (identifier, standard = new Array(0)) => {
                let element;
                if(window['GM_getValue']) {
                    element = window['GM_getValue'](identifier);
                } else {
                    element = localStorage[identifier];
                    if(!element) {
                        grease.set(identifier, standard);
                        return standard;
                    } else {
                        return JSON.parse(element);
                    }
                }
                if(element === null || element === undefined) {
                    grease.set(identifier, standard);
                    return standard;
                }
                return element;
            }
        });
`

something approximately like this 

this use case removes everything that is older than §{days} days when filter is called but always keeps the latest entry:
`
const days=1;
tampermonkeyStorageWrapper.p('key', { timestamp: Date.now(), value: newObject });
tampermonkeyStorageWrapper.filter('key', StorageImplementation.filterDaysFunction(days, { keepLatest: true }))
`

(ignore the types the typedef file is probably not of help to you ^^)
