### ISSUE TITLE
In Kiwi, version 4.12 breaks action.html and options.html extension pages.

### ISSUE THREAD

**Issue by phineas12** [Tampermonkey/tampermonkey#1197]
In Kiwi (Android Chromium), TM version 4.12 breaks action.html and options.html extension pages.

## Expected Behavior
TM button in Chrome menu opening .../actions.html showing what scripts are running, etc.
TM options button in Extensions showing list of installed scripts.

## Actual Behavior
Action shows nothing but the loading animation, then a blank screen.
Options shows empty list of installed scripts.  Attempting to export scripts displays endless loading animation with "Please wait...".
Previously installed scripts run fine.

## Specifications

- Kiwi: Git210216Gen570536402 (Latest)
- Chromium: 77
- TM: 4.12
- OS: Android 9
- Javascript: V8 6.8.275.15

## Error messages in console were similar in Stable and Beta
(action.html)
Error in event handler for (unknown): TypeError: Cannot read property 'options' of undefined
    at e (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/extension.js:829:481)
    at r (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/extension.js:833:18)
    at rea.extension.sendMessage.e (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/extension.js:833:118)

(Installed userscripts)
Error in event handler for (unknown): TypeError: Cannot read property 'items' of undefined
    at e (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/extension.js:566:3)
    at rea.extension.sendMessage.e (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/extension.js:834:337)

I realize Kiwi is using an old version of Chromium, but they do have 5 million installs mainly because they support Chrome extensions.  He also backports security fixes.  Hope you can find a way to keep it working.

I tried debugging the issue myself for several hours in Stable and Beta and didn't get very far.  Was able to recover settings, but unable to restore a working version 4.11 without a crx.

**Comment by derjanb** [comment]
Will be fixed soon. In the meanwhile you can get v4.11 from here https://www.tampermonkey.net/crx/tampermonkey_4_11.crx

**Comment by phineas12** [comment]
`Object.fromElements` isn't available in Chromium 77 apparently.  Replacing this with a javascript only implementation in background.js and extension.js

Here is my poorly designed fix, places at the top
`Object.fromEntries = function(a){ return JSON.parse(JSON.stringify(a).replace(/,\{\}/g,":{}").replace(/,null/g,":null").replace(/\[\[/g,"{").replace(/\]\]/g,"}").replace(/\[/g,"").replace(/\]/g,"").replace(/,\}/g,":[]")); };
`

**Comment by derjanb** [comment]
> Object.fromElements isn't available in Chromium 77

Well it should. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries
I've also tested 4.12 with Chromium 73 and above and everything worked. So it looks like this is something Kiwi-specific...

![image](https://user-images.githubusercontent.com/767504/113152925-e3a40a80-9236-11eb-819f-b1a048b3bdf2.png)

**Comment by derjanb** [comment]
Fixed at the latest [BETA version](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6133.crx) which will be published at the Chrome Web Store after review.

**Comment by phineas12** [comment]
It looks like Kiwi uses Javascript: V8 6.8.275.15 which (I just found out) means it's the javascript engine from Chrome 68 (July 2018).  Just an FYI for anyone looking here later.
