### ISSUE TITLE
CSS UI bug when openning tampermonkey from hidden add-ons list in Firefox 87 on Windows 10.

### ISSUE THREAD

**Issue by Pawloland** [Tampermonkey/tampermonkey#1198]
(Please fill out the issue template with your details)

## Expected Behavior
It should look something like this, when opening tampermonkey from hidden add-ons list in Firefox (the image shows how it looks when tampermonkey isn't hidden).

![img_expected](https://user-images.githubusercontent.com/59684145/113318582-e2471080-9310-11eb-9c53-27386aff4fa7.png)

## Actual Behavior
When opening tampermonkey from hidden add-ons list there is a problem with css, that pushes the content to the bottom and event causes overflow, so that the scrollbars appear. It is really annoying, having to scroll to the bottom every time, just to enter the settings.

![.](https://user-images.githubusercontent.com/59684145/113318836-263a1580-9311-11eb-9ff7-a243f431b9a8.png)
![.](https://user-images.githubusercontent.com/59684145/113319923-40282800-9312-11eb-80a2-a823a5b1076b.png)
![.](https://user-images.githubusercontent.com/59684145/113318778-18849000-9311-11eb-954f-8824742ab138.png)

## Specifications
- Firefox: 87.0 (64 bit)
- TM: 4.12.6132
- OS: win10

**Comment by phineas12** [comment]
Try this fix until the next release?
https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889

**Comment by Pawloland** [comment]
Thank you, I didn't found that before posting issue. It fixed my problem, so I am closing this bug report.
