### ISSUE TITLE
Feature Request: Add @require destinations to content-security-policy

### ISSUE THREAD

**Issue by jasonmclose** [Tampermonkey/tampermonkey#1199]
I apologize if this isn't the proper way to register a feature request.  I couldn't figure out any other way of doing it.

I have gone down the rabbit hole of how to get some of my code to work with a site that has a rigid CSP.  I need to use a javascript API to send some stuff to a database, and it's getting blocked by the CSP.  The blocking of XMLHttpRequest hurts.  For example, github essentially has their CSP locked down as tight as it goes.

The new feature of using the "Modify existing content security policy (CSP) headers:" helps, but I have to select the "Remove entirely" option.  This is, obviously, a bit unsecure, as it removes all of the CSP controls for that site.  Fortunately, you (at Tampermonkey) thought of this ahead of time, and the CSP is only removed on pages in which Tampermonkey has an active script running.

Since you already have the code to access and manipulate the CSP, what if TM injected any domains used in @require tags into the relevant CSP, so that we don't have to disable the CSP entirely?  Or, this could even be a new tag (@csp) or set of tags (@csp-src, @csp-img...), where we could set the domains required for injection into these various CSP fields.  If we can't do it in the script level, a whitelist textarea in the Settings could work.

To me, this makes sense with the default "Yes" selection of the CSP modification. With more and more major sites using the CSP, I see this as a growing problem.

Thanks for your work.

**Comment by derjanb** [comment]
Can you please attach an example script that shows what you're trying to achieve? All code of ```@require``` tags is part of the userscript and should be executed along with the userscript. For ```@require``` scripts that are using XMLHttpRequests you could use something like this that makes use of GM_xmlhttpRequest to make in this case JQuery Ajax requests work:

https://gist.github.com/derjanb/10961253

**Comment by jasonmclose** [comment]
So after using that, you are correct.  I apologize for not understanding it correctly.

But I have a new challenge for you.

Try running that code on Facebook.  Facebook's graph javascript specifically looks for the GM_xmlhttpRequest and blocks it.  They attach an event listener to xhr and look for that specific call, and then they return a blacklist error.

Any clue how to get around that?

**Comment by 7nik** [comment]
Can you provide an example so we can look for a solution?

**Comment by derjanb** [comment]
> They attach an event listener to xhr and look for that specific call, and then they return a blacklist error.

The mentioned gist uses [GM_xmlhttpRequest](https://www.tampermonkey.net/documentation.php#GM_xmlhttpRequest) which does not use the page's XHR.

**Comment by asheroto** [comment]
Hi there, possibly could reopen this?

I use QuickBooks online and found this issue to be of relevance when searching for a solution.

I thought that XHR requests used the TamperMonkey plugin, but whenever I have that setting set to "Yes", I get a console error saying the request was blocked due to a CSP violation. If I turn on the setting "Remove entirely" then it works.

I don't see anything "TamperMonkey" in the CSP, as if it wasn't modified.

Any ideas? Thanks!
