### ISSUE TITLE
GM_xmlhttpRequest.responseText might not be present or not of type "text" if responseType is set

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1200]
>  I saw https://github.com/Tampermonkey/tampermonkey/issues/1172#issuecomment-792986175  before,   @derjanb "Will be fixed soon..."

I thought it could be fixed, but the problem still exists...

> I don't understand the code, but I provide sample scripts and sample pages, which should enable you to reproduce the problem.

## Simple steps to reproduce: 
TM: (⩾V4.13+ [including store stable version](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo)) 　　 Chromium: 86-89 　OS: Win10

<details><summary>Details</summary>

- 1) Install UserJS: 
https://greasyfork.org/scripts/408466

- 2) Then open any page with `magnet`, for example:
https://magnet.dog/package/97fb54e32521f6926d48b8e2000dae3c74138e78.html

- 3) Bug coming: 
![image](https://user-images.githubusercontent.com/10995302/113364133-4c999880-9385-11eb-8dfb-78f94f2006b6.png)

>  👆 If it works normally, click the icon button, it will popup `confirm()` .
>   Tampermonkey now , click the icon button, nothing happens (completely unable to communicate with the other page) .</details>  

---------------------------------------------------------------------

## Why is it considered a bug?

⚔ Because there is no problem with Tampermonkey＜4.13 version (i.e. V4.12 or V4.11) .
⚔ Because there is no problem with Violentmonkey.

You can reproduce the problem and analyze the cause through comparative testing.

**Comment by derjanb** [comment]
Nice finding, this bug however happens in 4.12 as well and is present since at least 4.12.6125.

**Comment by dnknn** [comment]
> however happens in 4.12 as well and is present since at least BETA 4.12.6125.


🙈 Haha, sorry, I did not express the specific situation. I also knew that BETA 4.12 had this problem. I am referring to the Google Store version 🙈
