### ISSUE TITLE
GM.notification not working: "GM.notification(details): received no details"

### ISSUE THREAD

**Issue by Purfview** [Tampermonkey/tampermonkey#1203]
GM.notification is not working. Warning from console:
"GM.notification(details): received no details"

## Expected Behavior

The notification is displayed.

## Actual Behavior

The notification is not displayed.

## Specifications

- Opera: 73.0
- Firefox 87.0 (64-bit)
- TM: 4.11.6120
- TM: 4.12.6132
- TM beta: 4.13.6133
- OS: (Win7 x64)

## Script

```js
// ==UserScript==
// @name         Test notification
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @match        *://*/*
// @grant        GM.notification
// ==/UserScript==

GM.notification("Hello!", "Test notification");
```

**Comment by 7nik** [comment]
GM.notification doesn't support (text, title, image, onclick) arguments format.
Use either GM_notification or pass `details` object instead.

It can still be considered a bug because there is nothing about this nuance in the documentation.

**Comment by Purfview** [comment]
GM_notification is not supported by Greasemonkey and "object" solution would require to rewrite existing scripts.

**Comment by Purfview** [comment]
Quick tested new beta, and it works. Thanks derjanb.

Small cosmetic stuff: If "image" is not defined it could show by default TM's icon like other monkeys do.
