### ISSUE TITLE
Cannot install a userscript from url

### ISSUE THREAD

**Issue by petitchamp** [Tampermonkey/tampermonkey#1208]
## Expected Behavior

should be able to install an exported userscript file from http url

## Actual Behavior
I server a exported tampermonkey userscript file via a http server. 
When I enter the url in "Install from URL"  on utilities tab, I get a "Invalid Userscript sry" error
If I save the content of http response in a local text file, I can import it as file

## Specifications

- Chromium: 89.0.4389.114 (
- TM: 4.12
- OS: Win10 19042.906

## Script
N/A

**Comment by derjanb** [comment]
Working fine here using this several test URLs: 

http://test.tampermonkey.net/test.user.js
https://github.com/anka-213/webcomic_reader/raw/master/webcomic_reader.user.js
https://gist.github.com/derjanb/5592ff3b7cdc4feabba5/raw/763856b43eb38d66fa959225474d4567faec2d16/tampermonkey_translation_support.user.js

Can you please attach more details?

**Comment by petitchamp** [comment]
I see.
I used Utilities -> File -> Export tool to export all my user scripts. Which is the export format of tampermonkey. 
So Install from URL does not support this format. 
I can only install a single user script with this function.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141. You can now point to zip, JSON format and plain userscript files.

**Comment by brohithkr** [comment]
Is there any issue in this script that results in tamper monkey not prompting from install and just raw file appearing on page ? Unlike above links..

https://gist.githubusercontent.com/brohithkr/7c8c0163d0a773a9c12a9b02522feb32/raw/EnableCopyPasteScript.js
