### ISSUE TITLE
TM Editor changes  EoL encoding

### ISSUE THREAD

**Issue by MysticJay** [Tampermonkey/tampermonkey#1209]
1) import a script with EoL encoding = "x0D0A" (CR/LF)
2) do an edit and save the script using TM built-in editor
3) request to update the script from the external source
Result: all lines are marked as changed.
Same can be confirmed when exporting the same script. All line terminate with "x0A" (LF only)

## Expected Behavior
Keep EoL encoding 

## Actual Behavior
Editor and export always change EoL encoding to "x0A", ignoring original encoding.

## Specifications

- FF: 87.0
- TM: 4.12.6132
- OS: Win10-20H2

**Comment by derjanb** [comment]
Do you know if this has worked before?

Note: Probably related issue codemirror/CodeMirror#3395

**Comment by MysticJay** [comment]
Yes I can confirm it worked before. I was able to do local changes (to do quick testing), then duplicate them to the source files and finally provide a new build of the script. That was compared to my local changes.

Now after each local change the new build will replace the whole code i.e. a DIFF fails due to too many changes.

building process has not changed and I get the same effect when using builds that have been created long ago.

I can test against some older TM release to see if that changes things. But what version?

**Comment by derjanb** [comment]
4.11.6120 vs 4.12.6121 would be interesting, because CodeMirror editor was updated back then. Thanks a lot.

**Comment by MysticJay** [comment]
confirming problem introduced after 4.11.6120.
I could not find 4.11.6121, but 4.12.6130 has the issue.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141
