### ISSUE TITLE
Script not loading correctly on page load

### ISSUE THREAD

**Issue by nita0318** [Tampermonkey/tampermonkey#1213]
## Expected Behavior
Scripts are loaded correctly when the page loads.

## Actual Behavior
The script did not load.

I did not encounter this problem until I upgraded from version 4.11 to 4.12.
The script loads correctly when the page loads after a manual restart of TM.

## Specifications

- Chromium: 89.0.4389.114
- TM: 4.12
- OS: win10 19042.867

## Script
N/A

**Comment by 7nik** [comment]
Is it similar to https://github.com/Tampermonkey/tampermonkey/issues/1190#issuecomment-808411189 ?

**Comment by nita0318** [comment]
> Is it similar to [#1190 (comment)](https://github.com/Tampermonkey/tampermonkey/issues/1190#issuecomment-808411189) ?

Yes.The script's switch is on(show as green).But none of them are working.
Restart TM in the extension settings page then scripts can load correctly.

**Comment by moontai0724** [comment]
same issue here

**Comment by derjanb** [comment]
Closing in favor of #1215

**Comment by piszczello** [comment]
hello everyone, I invite you all

**Comment by piszczello** [comment]
King of Avalon piszczello
