### ISSUE TITLE
Report: script resources and require not load && fix method

### ISSUE THREAD

**Issue by langren1353** [Tampermonkey/tampermonkey#1215]
(Please fill out the issue template with your details)
My script user report my script doesn't work sometimes, and I trace the code, then I found the script did not exec at all.
Then tried to follow the running code of TM. Then I found something
## Occurrence at：
1. chrome set the openning page as https://www.youtube.com or https://www.baidu.com (res = every time when you open chrome, it open youtube.com)
2. tampermonkey with a script who has `@resource` and `@require` and some exec code which will exec at youtube
3. close chrome and reopen it. (it happens sometimes but not always)

## Occurrence Reason：
1. chrome open the default page very fast, TM load resources at same time，but sometimes it will happen an error at console:
>Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

2. TM resouce promise handler didn't receive the message back.Then the script stucked
![image](https://user-images.githubusercontent.com/14857127/114696661-7ec8d400-9d4f-11eb-8971-4c6f17358c53.png)
![image](https://user-images.githubusercontent.com/14857127/114703862-77f28f00-9d58-11eb-956b-c5259eb37f4a.png)

## Fix Method
resource fetch promise with a timestamp
after timeout clear the promise

## Expected Behavior
Script loading and exec well

## Actual Behavior
Script loaded
But it didn't exec!!!!!

## Specifications

- Chromium: 86.0.4240.198
- TM: 4.12 & 4.13Beta
- OS: Win

## Script
```
// ==UserScript==
// @name         !!!!!!!!!May not run!!!!!!!!
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      https://www.youtube.com/*
// @include      https://www.baidu.com/*
// @icon         https://www.google.com/s2/favicons?domain=baidu.com
// @resource     AnimateSSS https://cdn.staticfile.org/animate.css/2.0/animate.min.css
// @require      https://cdn.staticfile.org/jquery/1.10.0/jquery.min.js
// @grant        none
// ==/UserScript==

console.error("logLOGOGOGOGOGOGOOG！！！！")
console.error("logLOGOGOGOGOGOGOOG！！！！")
console.error("logLOGOGOGOGOGOGOOG！！！！")
console.error("logLOGOGOGOGOGOGOOG！！！！")
console.error("logLOGOGOGOGOGOGOOG！！！！")
console.error("logLOGOGOGOGOGOGOOG！！！！")
```

**Comment by derjanb** [comment]
Nice finding! This happens to scripts that have at least two externals (`@require` and `@resource`) and want to run at the initially visible tab on browser start.

**Comment by derjanb** [comment]
Should be fixed at Tampmonkey BETA 4.13.6135 which is review now. In urgent cases please download the [crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6135.crx) and drag and drop it to Chrome's extensions page (chrome://extensions).

**Comment by langren1353** [comment]
Nice, I double checked that, it works fine on Beta version now.
Thank you for your prompt reply and fix, TmaperMonkey is the best GM extension I have ever known.

**Comment by lvzhenbo** [comment]
It is hoped that this change will be released to the stable version as soon as possible.This bug has caused a very serious problem with the script not working

**Comment by filbo** [comment]
@derjanb the underlying cause of this was some sort of over-eager loading / execution of the first-seen page by Chrome, right?  Can you possibly characterize this better?  An extension I work on has been suffering for years from occasional mis-startup in the first-visible tab of a restored session.  (As seen in https://github.com/violentmonkey/violentmonkey/issues/73; and perhaps traced back to https://bugs.chromium.org/p/chromium/issues/detail?id=314686, which is still sitting there ignored...)
