### ISSUE TITLE
Cannot store a RegExp by GM_setValue

### ISSUE THREAD

**Issue by andywang425** [Tampermonkey/tampermonkey#1216]
## Expected Behavior
Store a RegExp(`"reg": /reg/`).

## Actual Behavior
It turns into an empty object(`"reg": {}`).

## Specifications

- Chromium: 88.0.4324.190
- TM: 4.12
- OS: Windows 10 Enterprise

## Code

```js
GM_setValue('reg', /reg/)
```

**Comment by 7nik** [comment]
RegExp cannot be serialized to JSON (as well as function, bigint, Symbol, HTMLElement, and other special types and classes).

In general, it's possible to convert them to some plain object, but during deserialization, it'll be tough to differ serialized object and an object with the same properties.

You can explicitly convert RegExp to string and store it. 
```js
function saveRegExp (name, { source, flags }) {
  GM_setValue(name, { source, flags });
}  

function restoreRegExp (name, defRegExp) {
  const { source, flags } = GM_getValue(name, {});
  if (source == null) return defRegExp;
  return new RegExp(source, flags);
}
```

**Comment by andywang425** [comment]
> RegExp cannot be serialized to JSON (as well as function, bigint, Symbol, HTMLElement, and other special types and classes).
> 
> In general, it's possible to convert them to some plain object, but during deserialization, it'll be tough to differ serialized object and an object with the same properties.
> 
> You can explicitly convert RegExp to string and store it.
> 
> ```js
> function saveRegExp (name, { source, flags }) {
>   GM_setValue(name, { source, flags });
> }  
> 
> function restoreRegExp (name, defRegExp) {
>   const { source, flags } = GM_getValue(name, {});
>   if (source == null) return defRegExp;
>   return new RegExp(source, flags);
> }
> ```

Thanks! It solved my problem.
