### ISSUE TITLE
Feature Request: show GM_xmlhttpRequest in network tab 

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1217]
## Expected Behavior
if a request is done via GM_xmlhttpRequest it should then be viewable in the chrome developer tools network tab

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @grant GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({url:"www.google.de",onload:e=>{debugger;}})
```

**Comment by 7nik** [comment]
It is but in devtools of TM's background page.
In menu -> More tools -> Extensions -> Enable deleloper mode -> Find Tampermonkey and click Inspect views
background.html

**Comment by jonnytest1** [comment]
oh thanks good to know 
(im very much wondering how im not rate limited on some domains right now 😅)
