### ISSUE TITLE
Different behavior on Chrome & Firefox

### ISSUE THREAD

**Issue by SukkaW** [Tampermonkey/tampermonkey#1218]
(Please fill out the issue template with your details)

## Expected Behavior

The behavior should be the same.

## Actual Behavior

Chrome:

![image](https://user-images.githubusercontent.com/40715044/114790376-3d6c0f00-9db7-11eb-9c87-9d16e913ba0e.png)

Firefox:

![image](https://user-images.githubusercontent.com/40715044/114790416-4fe64880-9db7-11eb-88c9-ae24358498a2.png)

## Specifications

- Chromium: 89.0.4389.128 / Firefox: 87.0
- TM: 4.12.6132
- OS: macOS 11.2.3

## Script

```js
// ==UserScript==
// @name        DOMContentLoaded
// @namespace   https://example.com
// @run-at      document-end
// @version     0.0.0
// @author      Me
// @grant       unsafeWindow
// @match       https://example.com
// ==/UserScript==
(() => {
  console.log(document.readyState);

  window.addEventListener('load', () => {
    console.log('window load event');

    document.addEventListener('DOMContentLoaded', () => { console.log('DOMContentLoaded is now triggered'); });
  });
})();
```

**Comment by SukkaW** [comment]
Note, it is also different from the browser's own behavior. See https://lab.skk.moe/domcontentloaded/ for an example:

Chrome:

![image](https://user-images.githubusercontent.com/40715044/114794200-87a4be80-9dbe-11eb-9c7e-d779eb9a1aca.png)

Firefox:

![image](https://user-images.githubusercontent.com/40715044/114794214-8f646300-9dbe-11eb-904f-5351b2885a85.png)

They are identical.

**Comment by derjanb** [comment]
Should be fixed at Tampermonkey BETA 4.13.6135.

**Comment by SukkaW** [comment]
Can confirm it works at my side: DOMContentLoaded event will not be fired after the window load event has already fired.

**Comment by SukkaW** [comment]
@derjanb OK. Now I found even more unintended behaviors:

Given a userscript:

```js
// ==UserScript==
// @name        DOMContentLoaded
// @namespace   https://example.com
// @run-at      document-end
// @version     0.0.0
// @author      Me
// @grant       unsafeWindow
// @match       https://example.com
// ==/UserScript==
(() => {
  console.log(new Date().getTime(), document.readyState);
  document.addEventListener('readystatechange', event => {
    console.log(new Date().getTime(), 'readystatechange:', event.target.readyState);
  });
  document.addEventListener('DOMContentLoaded', () => {
    console.log(new Date().getTime(), 'DOMContentLoaded is now triggered');
  });
  window.addEventListener('load', () => {
    console.log(new Date().getTime(), 'window load is now triggered');
  });
})();
```

With TamperMonkey 4.12 on Firefox, it will prints:

```
complete
DOMContentLoaded is now triggered
window load is now triggered
```

With TamperMonkey 4.13 beta on Firefox, it will prints:

```
interactive
readystatechange: complete
window load is now triggered
DOMContentLoaded is now triggered
```

With TamperMonkey 4.12 and 4.13 beta on Chrome, after the script is saved, first time the page load it will prints:

```
interactive
DOMContentLoaded is now triggered
readystatechange: complete
window load is now triggered
```

Refresh the page it will prints:

```
complete
DOMContentLoaded is now triggered
window load is now triggered
```

So:

- TamperMonkey 4.13 on Firefox will cause the DOMContentLoaded event to be fired even after the window load event.
- TamperMonkey (both 4.12 and 4.13) on Chrome have different behavior between right after script is saved and the page has been loaded once.
