### ISSUE TITLE
Skewed action panel for a large number of scripts

### ISSUE THREAD

**Issue by wvxwxvw** [Tampermonkey/tampermonkey#1222]
Firefox 78 ESR, dark theme TM.
Skewed action panel for a large number of scripts.
It helps `html.desktop.dark body div#status.action.status {display: none}` in the custom style section TM.

**Comment by CennoxX** [comment]
For me (Firefox 87.0) the problem exists with every theme. So I'm using `html.desktop body div#status.action.status {display: none}`.

**Comment by derjanb** [comment]
Duplicate of #1181 and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround. It is also fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Comment by wvxwxvw** [comment]
Yes, everything is fine in beta.
