### ISSUE TITLE
GM_xmlhttpRequest: Cannot download blobs on Firefox

### ISSUE THREAD

**Issue by juliano-lopes** [Tampermonkey/tampermonkey#1223]
(Please fill out the issue template with your details)

## Expected Behavior
The request with GM_xmlhttpRequest should return the blob response on Mozilla Firefox as occurs on Google Chrome and Microsoft Edge.

## Actual Behavior
The response on Mozilla Firefox is null:

Object { readyState: 4, responseHeaders: "", finalUrl: "blob:https://xxx.com/xxx", status: 0, statusText: "", responseXML: null, responseText: "", response: null }
WhatsappWithMoreAccessibility.user.js:701:29

## Specifications

Firefox version: 88.0 (64-bits)
Tampermonkey version: v4.12.6132

## Script

(Please give an example of the script if applicable.)

Request:

    GM_xmlhttpRequest({
        method: "GET",
        url: "blob:https://xxx.com/xxx",
        responseType: "blob",
        onabort: function (res) {
            console.log("It was aborted", res);
        },
        onerror: function (res) {
            console.log("There is an error: ", res);
        },
        onload: function (res) {
            console.log("It is ok", res);
        }
    });

**Comment by llyama** [comment]
This started happening with Firefox version 88. The cookies in the request header get double url encoded causing them to be incorrect.

**Comment by derjanb** [comment]
Should be fixed at 4.19.6180 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
