### ISSUE TITLE
Run script immediately when script is enabled

### ISSUE THREAD

**Issue by joeytwiddle** [Tampermonkey/tampermonkey#1225]
Currently if Tampermonkey is disabled and we enable it, all the scripts run immediately, without the need to reload the page. This is good.

Why not do this same behaviour when a disabled script is enabled from Tampermonkey's dropdown?

## Expected Behavior

When I use TamperMonkey's extension dropdown menu to enable a script, the script should run immediately on the current page. (I don't mind if it also runs in other tabs, or if a reload is required for other tabs.)

**Comment by drhouse** [comment]
doesn't Tampermonkey already act this way with this option checked?
Settings > General > ☑ Auto reload pages (tooltip: Reload affected pages if a script was turned on or off)

It does for me

**Comment by joeytwiddle** [comment]
Thanks @drhouse, I wasn't aware of that option.

Although my request was to run the userscript _without_ a page reload, that solution is pretty close.

**Comment by derjanb** [comment]
> Although my request was to run the userscript without a page reload, that solution is pretty close.

The current approach has the advantage that all scripts including the ones running at `document-start` are injected into a "well-defined" environment due to the page reload.
