### ISSUE TITLE
userscripts dont run on chrome webstore

### ISSUE THREAD

**Issue by retronbv** [Tampermonkey/tampermonkey#1226]
(Please fill out the issue template with your details)

## Expected Behavior

Userscripts can run on chrome webstore

## Actual Behavior

Userscript doesnt even show in popup:
![image](https://user-images.githubusercontent.com/49005044/115591219-e0cd9000-a29f-11eb-9ded-81aa84b88131.png)
![image](https://user-images.githubusercontent.com/49005044/115591315-f6db5080-a29f-11eb-87b0-169ee8d2d70d.png)

## Specifications

- Vivaldi: 3.7.2218.55 
- TM: 4.12
- OS: Linux

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Vivaldi Web Store
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  changes chrome webstore to vivaldi webtore
// @author       retronbv
// @match        https://chrome.google.com/webstore/category/extensions
// @icon         https://img.icons8.com/fluent/344/vivaldi-web-browser.png
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    var x = document.getElementsByClassName("uKSMob")[0];
    x.removeChild(x.firstElementChild);
    var y = document.createElement("img");
    y.src = "https://img.icons8.com/fluent/344/vivaldi-web-browser.png";
    y.width="32";
    x.appendChild(y);
    document.querySelectorAll(".PNF6le")[0].innerText="vivaldi web store";
    document.querySelectorAll(".SUBrWc")[0].innerText="About Vivaldi Web Store";
})();
```

**Comment by 7nik** [comment]
TM just cannot. Changing the chrome web store pages is prohibited for all extensions for security reasons, and for chrome://* pages as well.

**Comment by retronbv** [comment]
welp, thanks for your help @7nik

**Comment by asheroto** [comment]
@7nik do you happen to know if this applies to "chrome-extension://" as well?  I have an extension that I want to use a TM script on in Brave browser.  Thanks!

**Comment by 7nik** [comment]
As you can see in [MDN's Browser compatibility of schemes](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#browser_compatibility), chrome (and likely all chomium-based browsers) supports only `http`, `https`, `ftp` and `file` schemes (same list as on [Chrome Develeopers](https://developer.chrome.com/docs/extensions/mv3/match_patterns/)) and there is even no `chrome-extension` scheme though it's listed in the [possible values](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#scheme).
In Chromium, attempt to load an unpacked extension with access to extension's pages, even own ones, gives the error `Invalid value for 'content_scripts[0].matches[0]': Invalid scheme.`

**Comment by asheroto** [comment]
Thanks!
