### ISSUE TITLE
Factory Reset feature does not work in Chrome in the TM Beta.

### ISSUE THREAD

**Issue by JohnD78** [Tampermonkey/tampermonkey#1227]
Hi, now the "Reset Factory" function completely breaks the extension in Chrome.  
The only way to get the extension working again is to completely reinstall the extension. 
There is no such problem in the Firefox version.

## Expected Behavior
The function should work as before.

## Actual Behavior
Now the "Reset Factory" function completely breaks the extension in Chrome.

## Specifications

- Chromium: 90.0.4430.85
- TM: Beta 4.13.6135
- OS: Win 7x64

**Comment by derjanb** [comment]
Should be fixed at latest BETA version 4.13.6136
