### ISSUE TITLE
`@run-at context-menu` click not working in macos chrome

### ISSUE THREAD

**Issue by zaaack** [Tampermonkey/tampermonkey#1228]
(Please fill out the issue template with your details)

## Expected Behavior

click on context-menu should open new tab

## Actual Behavior

click on context-menu has no effects

## Specifications

- Chrome: (i.e. 64.0.3282.140) 89.0.4389.90
- TM: (i.e. 4.5.5648) beta 4.13.6135
- OS: (i.e. MacOS 10.13.4) 10.14.6 

## Script

https://greasyfork.org/scripts/402736-%E4%BD%BF%E7%94%A8%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91/code/%E4%BD%BF%E7%94%A8%E7%99%BE%E5%BA%A6%E7%BF%BB%E8%AF%91.user.js

**Comment by derjanb** [comment]
Working fine at MacOS 11.2.9 and Chrome 89.0.4389.90. 

Do youan error at the page's JavaScript console?

**Comment by zaaack** [comment]
@derjanb no errors, no logs for my test scripts, just not execute any thing, I know somebody's windows chrome also has this problem, but my windows laptop is fine.

**Comment by derjanb** [comment]
Have you configured Chrome to restore your tabs on restart? If so this issue might be related to #1215.

**Comment by zaaack** [comment]
@derjanb Yes, but it's not working in all tabs, including new started, my tampermonkey is beta version.

**Comment by derjanb** [comment]
I see. 

Can you please set "Logging Level" to "Debug" and check the JS console again. Do you see TM related messages? Can you also please check [TM's background console](https://www.tampermonkey.net/faq.php?#Q600)?

**Comment by zaaack** [comment]
![image](https://user-images.githubusercontent.com/5233940/116513449-2faca280-a8fc-11eb-97c7-ce46418d10d9.png)
