### ISSUE TITLE
@resource with file:// not working in Firefox 88 and Chrome 90 (as of 24April2021)

### ISSUE THREAD

**Issue by macdevign** [Tampermonkey/tampermonkey#1229]
@resource does not seem to work with file://  on both Firefox 88 and Chrome 90.

Add this line for example does not work to access the testme.js
// @require file:///projects/kms_tampermonkey/src/experiment/testme.js

The following is the setting of Tampermonkey security 

Firefox:    ( Allow scripts to access local files set to @resource   or "Allow local files" option does not solve the problem)
<img width="811" alt="image" src="https://user-images.githubusercontent.com/6662383/115952387-27c5ba80-a518-11eb-82a1-e18d4de0da43.png">

Chrome: (oddly this does not have "Allow scripts to access local files" option as available in Firefox version of Tampermonkey
<img width="839" alt="image" src="https://user-images.githubusercontent.com/6662383/115952397-32804f80-a518-11eb-9e77-80b56cb3504c.png">

## Expected Behavior ============
The window title should be changed to "Testing title: " text

## Actual Behavior ===============
The window title didn't change at all as though the javascript is not loaded through @resource

## Specifications ==================
- Chromium Version 90.0.4430.85
- Firefox 88
- OS: (i.e. MacOS Catalina 10.15.7)

## UserScript ======================

```js
// ==UserScript==
// @name            TEST: Mem
// @namespace       http://tampermonkey.net/
// @description    Testing @require
// @version         1.0
// @author          macdevign
// @include         *
// @run-at document-end
// @require file:///projects/kms_tampermonkey/src/experiment/testme.js
// ====================================
// ==/UserScript==]
"use strict;";
```

Content of testme.js  : Change the document title every 1 second
================================
setInterval(() => {
    document.title = "Testing title: " + new Date();
}, 1000);

**Comment by 7nik** [comment]
Have you allowed access to files in chrome?
![image](https://user-images.githubusercontent.com/29704098/115952726-5e87da80-a4f0-11eb-8c90-aa53e9d052a2.png)

**Comment by macdevign** [comment]
Hi 7nik,
thank for the info. 
setting that in Chrome works. Wonder if Tampermonkey developer could add a notice in Tampermonkey Setting screen to indicate that "Allow scripts to access local files: " can only be set through Chrome only.

As for the firefox, the problem still remains though.

**Comment by 7nik** [comment]
It seems there is even a method to check the state of this checkbox https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedFileSchemeAccess

From what I got about FF, it has no way to read local files by a path anymore.

**Comment by macdevign** [comment]
> It seems there is even a method to check the state of this checkbox https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedFileSchemeAccess
> 
> From what I got about FF, it has no way to read local files by a path anymore.

thank for the quick reply.
Probably you refer to this issue "[Firefox] How can I use a local file in Tampermonkey? #347 " 
[https://github.com/Tampermonkey/tampermonkey/issues/347]. 

I just have to duplicate the code across browsers then.

thank

**Comment by brasofilo** [comment]
> Have you allowed access to files in chrome?
> ![image](https://user-images.githubusercontent.com/29704098/115952726-5e87da80-a4f0-11eb-8c90-aa53e9d052a2.png)

<facepalm>... had to reinstall TM and forgot about this detail, thanks for the reminder!
