### ISSUE TITLE
Error: Promised response from onMessage listener went out of scope

### ISSUE THREAD

**Issue by h0rn3z0r** [Tampermonkey/tampermonkey#1231]
## Expected Behavior
No error.

## Actual Behavior
Getting this error after the latest Firefox update.

![image](https://user-images.githubusercontent.com/8987403/115994255-e3e9b880-a5de-11eb-84ea-1c223095dfe7.png)

It usually appears in a minute.

## Specifications

- Firefox: 88.0
- TM: 4.12.6132
- OS: Win 10

## Script
Any script. even the "New Userscript" template will work.

**Comment by MyBlueHorizon** [comment]
this bug don't appear in v4.11.6120.
maybe something go wrong in new version.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141

**Comment by SolidBlock-cn** [comment]
Reproduced in Firefox 96.0b4 and TM 4.13.6136.
```Error: Promised response from onMessage listener went out of scope 4 common.js:formatted:85```

**Comment by 7nik** [comment]
@SolidBlock-cn but it was fixed in the TM beta 4.14.6141 while your TM is 4.13.6136.

**Comment by RorinL** [comment]
> @SolidBlock-cn but it was fixed in the TM beta 4.14.6141 while your TM is 4.13.6136.

Indeed it is,thansk
