### ISSUE TITLE
New build of Tampermonkey on Mac App Store for Apple Silicon ?

### ISSUE THREAD

**Issue by fanvinga** [Tampermonkey/tampermonkey#1233]
Recently apple launched apple silicon m1, which is an arm cpu compare to the traditional intel cpu.Their architectures are not the same, so Apple provides Rosetta 2 as a compatibility implementation to allow apps developed for intel to run directly on apple silicon.
However, apps that running under Rosetta 2 will occur performance degradation and energy consumption increasing.So would you to compile a universal native version for Apple silicon and upload it to the App Store, as an update to the existing version ?
Anyway, thanks a lot to the developer for providing tampermonkey compatible with safari on macOS !

**Comment by derjanb** [comment]
Sorry for the delay -> fixed at 4.13.6140

**Comment by fanvinga** [comment]
> Sorry for the delay -> fixed at 4.13.6140

Thanks for your work !
