### ISSUE TITLE
Common.js warnings on console for all websites

### ISSUE THREAD

**Issue by FossPrime** [Tampermonkey/tampermonkey#1234]
Every website prints this to Console.log on firefox for Ubuntu 

> common.js:6:419
> resistFingerprinting detected! FF version is lower than 54, but URL.toJSON() seems to work. Overriding version to 54!!! https://developer.mozilla.org/en-US/Firefox/Releases/54#DOM_HTML_DOM

My user agent `Mozilla (Linux) Gecko Firefox` installed by default on Ubuntu's distribution of Firefox 88

## Expected Behavior
No errors or warnings.

## Actual Behavior
Warnings on every website in console.log

## Specifications

- Firefox 88 on Ubuntu
- TM: 4.13.6136
- OS: Ubuntu 20.04 LTS

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
