### ISSUE TITLE
Help with Userscript and Websocket protocol

### ISSUE THREAD

**Issue by ACH1980** [Tampermonkey/tampermonkey#1235]
I need again help with working on a userscript.

Especially I need to know how to interact with an existing websocket - or isn't it even possible? I'm actually working on a script to get the map coordinates from slither.io, based on the work in https://github.com/jfbarras/slimy-snake and the communication in https://github.com/jfbarras/slimy-snake/issues/37 I've made this little script, but it crashes my whole computer (not only the browser)...

```
// ==UserScript==
// @name         Slither.io Dev-Script
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://slither.io/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==


var h = window.h;

function coordinates() {
    if (window.snake) {
        h.xx = window.snake.xx + window.snake.fx;
        h.yy = window.snake.yy + window.snake.fy;

        console.log(h.xx);
        console.log(h.yy);
    }
}

while (true) {
    window.setTimeout(coordinates(h), 1000)
}
```

**Comment by 7nik** [comment]
> ```js
> while (true) {
>     window.setTimeout(coordinates(h), 1000)
> }
> ```

Completely wrong: you infinitely set timers without even waiting when previous ones finish, also you call the `coordinates` function instead of passing link to it.

If you need to call the function every second do just `setInterval(coordinates, 1000);`

If you need to pass the `h` parameter (which isn't used in your example): 
`setInterval(coordinates, 1000, h)` or `setInterval(() => coordinates(h), 1000)`

**Comment by ACH1980** [comment]
Thx, I'll try.

**Comment by ACH1980** [comment]
Now I've this code, but it has the same problem:

```
// ==UserScript==
// @name         Slither.io Dev-Script
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://slither.io/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==


var h = window.h;

function coordinates() {
    if (window.snake) {
        h.xx = window.snake.xx + window.snake.fx;
        h.yy = window.snake.yy + window.snake.fy;

        console.log(h.xx);
        console.log(h.yy);
    }
}

while (true) {
    setInterval(coordinates, 1000, h)
}
```

Also I still pass the h variable because I think I need to init it to use it in the function, right? Tbh I'm not an JS expert and nevertheless a tampermonkey expert (it's my second Userscript)...

**Comment by 7nik** [comment]
You don't need the while loop - setInterval already schedules execution every second.
The function already see the h variable.

```js 
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://slither.io/
// @icon         https://www.google.com/s2/favicons?domain=slither.io
// @grant        none
// ==/UserScript==

/* global snake */

(function() {
    'use strict';

    let data = {}; // init with empty object

    function printSnakePosition () {
        // if snake is not defined or is falsy, e.g. null
        if (!window.snake) return;

        // we already know that snake is defined and has data
        // so we can drop the window part
        data.x = snake.xx;
        data.y = snake.yy;

        console.log(data);
    }

    setInterval(printSnakePosition, 1000);
})();
```

**Comment by ACH1980** [comment]
It's working now! Thank you very much 🙏
