### ISSUE TITLE
Top-level await

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#1236]
It's about the experimental `top-level await` setting
that has been implemented in TM beta 4.12.6123 for Chrome+Firefox (released 2020-12-16)
with currently possible values: `Default`(=Enabled), `Enabled`, `Disabled`.

&nbsp;
According to the `top-level await` [specification](https://github.com/tc39/proposal-top-level-await) itself :

> Synopsis:
> Top-level `await` enables *modules* to act as big async functions: With top-level `await`, ECMAScript Modules (ESM) can `await` resources, causing other modules who `import` them to wait before they start evaluating their body.

Also, about Chrome:
here is a [Chrome Status page](https://www.chromestatus.com/feature/5767881411264512) regarding this feature, a [v8 feature page](https://v8.dev/features/top-level-await), and a [tweet](https://twitter.com/addyosmani/status/1360664535120506881).

And, about Firefox:
according to [this](https://spidermonkey.dev/blog/2021/04/05/top-level-await-ships.html) Spidermonkey announcement:

> Firefox will ship Top Level Await by default starting in Firefox 89 (currently in Beta). 
> This new feature introduces a capability to *modules* allowing programmers to do asynchronous work, such as fetching data, directly at the top level of any module.

All the above descriptions refer to modules. Also, ES modules will not be supported in userscripts.

&nbsp;
Yes, I see that the following 1-line example script is working ok in Tampermonkey (Chrome 90), 
*(not in Violentmonkey: `Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules` )*

```
// ==UserScript==
// @name         Test
// @match        *
// @grant        none
// ==/UserScript==

await fetch(location.href).then(res => console.log(res))
```

&nbsp;
But, @derjanb, given that, in userscripts, there are no ES modules, and we don't need to wait for imports.
could you please describe the possible *actual* use cases of the `top-level await` feature in userscripts ?  
How can a script author make good use of this feature? 
*I can't find any mention in the repo or in tampermonkey.net*.

Thank you

PS. Related discussion in Violentmonkey repo: https://github.com/violentmonkey/violentmonkey/issues/833

**Comment by derjanb** [comment]
The actual use case is something like your example script. It is no longer necessary to wrap the code in an asynchronous function.

I understand that Tampermonkey's top-level await support doesn't fit into any of the specs mentioned, but none of those specifies a userscript environment. Userscripts in Tampermonkey are always wrapped into a function (which now has the async attribute), and this is something that userscript authors need to be aware of in any case.

Therefore top-level await provides more flexibility while not breaking things. The option to disable it was only added to provide a workaround if problems become obvious.

**Comment by darkred** [comment]
Thanks a lot for the detailed reply!
