### ISSUE TITLE
Extension doesn't automatically switch between light / dark theme

### ISSUE THREAD

**Issue by twio142** [Tampermonkey/tampermonkey#1237]
## Expected Behavior
The extension tab and the dashboard should be switching automatically between light/ dark mode according to the （scheduled) system appearance setting.

## Actual Behavior
It remains the old appearance despite system theme has changed, and only refresh after manually reloading the extension.

## Specifications

- Chrome: 90.0.4430.85
- TM: 4.13.6137
- OS: MacOS 11.3

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141+

**Comment by twio142** [comment]
Yes it is. Thanks!

**Comment by Geeyun-JY3** [comment]
It seems that I need to reload the Tampermonkey page to make it switch to light/dark theme after the system theme is changed.

Chrome: 92.0.4515.131 
TM: 4.13.6142
OS: Windows 10 21H1 19043.1165
