### ISSUE TITLE
How to set the Tampermonkey extension option page title to a default name?

### ISSUE THREAD

**Issue by lyscop** [Tampermonkey/tampermonkey#1238]
The title of the Tampermonkey extension option page will change when the different script or the function tab is focused.

Could it be set to a default name like 'Tampermonkey'?

**Comment by derjanb** [comment]
This is not supported because the current way seems to be very common. 
For example here at GitHub, you can recognize the tab's content origin via the favicon. If you select the issues tab the title becomes "Issues". If you click at a issue then the title becomes the issue's title.
