### ISSUE TITLE
tampermonkey扩展更新脚本的问题

### ISSUE THREAD

**Issue by violenttamper** [Tampermonkey/tampermonkey#1243]
当脚本网站上已被删除的脚本提示更新了，更新后使得脚本失效，请问怎么解决？怎么设置禁止更新某些脚本？
当一些小的脚本更新能做到静默更新，而大脚本却会弹出更新的窗口，能否增改善一下大脚本更新不弹窗的问题，加入一个静默更新所有脚本的功能，然后可以右下角弹窗显示更新完成。

**Comment by derjanb** [comment]
I guess this is a duplicate of #1252
