### ISSUE TITLE
Option to set preferred language for names and more

### ISSUE THREAD

**Issue by Cyberavater** [Tampermonkey/tampermonkey#1244]
Eg script: https://greasyfork.org/en/scripts/28497-remove-web-limits-modified

If you inspect this code, you can see that this userscript has an English name too, but it shows the Chinese name on the Installed scripts page. So, if you can add a setting to select the preferred language then all the script that has English name written in source code will be displayed in the preferred language.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6141

**Comment by Geeyun-JY3** [comment]
Still can reproduce in 4.14.6141, Chrome 91.0.4472.124
![ZBO3`)`10_V@C(8Y56I)A30](https://user-images.githubusercontent.com/49396421/125061031-8514e500-e0df-11eb-9c6d-a4910159f9ca.png)

**Comment by derjanb** [comment]
I found some more places where the localized name and description wasn't shown. -> Should be fixed at 4.14.6142
