### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Buggedweirdo** [Tampermonkey/tampermonkey#1245]
Well, it used to work for a couple of months, but when I disabled a script and enabled another one, it just, broke. I enabled it again, but when I went to that website the script was meant for, it didn't have that red number next to the logo. I checked it again and it said no script is running. I reinstalled it and the issue still persists.

**Comment by 7nik** [comment]
What the site and what the script?

**Comment by Buggedweirdo** [comment]
Every site any of the scripts are intended for

**Comment by 7nik** [comment]
Then, what browser and OS you use?

**Comment by Buggedweirdo** [comment]
PC using the chrome version. My Edge addons is currently having a problem. So I used the chrome one

**Comment by 7nik** [comment]
TM is broken for Chrome, or Edge, or both?
Also, if you click "Create a new script...", save it and reload the page, the script doesn't run as well?

**Comment by Buggedweirdo** [comment]
Nope

**Comment by SekiBetu** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/1190#issuecomment-808411189
this is a workaround works for me

**Comment by derjanb** [comment]
Is this still an issue with TM 4.13?
