### ISSUE TITLE
could not create backup from incognito

### ISSUE THREAD

**Issue by shdeb** [Tampermonkey/tampermonkey#1247]
I was not able to reach the dashboard page, even after the latest update.
error : page unavailable (moved temporarily) ...
then i tried to backup my data through incognito (as dashboard opened there)
uninstalled it reinstalled it
dashboard works now
!! turns out it DID NOT create a backup from incognito !!
is this a expected?

## Expected Behavior
to create a backup !

## Actual Behavior
not create a backup

## Specifications

- Chromium: 90.0
- TM: 4.13
- OS: win 10

**Comment by derjanb** [comment]
> is this a expected?

No

I guess this is a Chrome issue. It is working fine here with 91.0.4472.77 and 92.0.4515.40. Do you still see this issue?
