### ISSUE TITLE
The problem of tampermonkeymonkey extension update script

### ISSUE THREAD

**Issue by violenttamper** [Tampermonkey/tampermonkey#1252]
When the deleted script on the script website is prompted to be updated, the updated script will be invalid. How can I solve this problem? How do I set the disable update of some scripts?

When some small scripts can be updated silently, but big scripts will pop up the update window. Can we improve the problem that big scripts don't pop up when updating? Add a function of silently updating all scripts, and then pop up the window in the lower right corner to show the completion of the update.

**Comment by derjanb** [comment]
You can disable "Check for updates" for this script.

![216_09232844](https://user-images.githubusercontent.com/10995302/121383962-715c4e80-c97a-11eb-8c7d-7cf764a1afe2.png) (taken from #1261)

**Comment by violenttamper** [comment]
thank you，i get√
