### ISSUE TITLE
Dark mode issue in trash UI

### ISSUE THREAD

**Issue by Geeyun-JY3** [Tampermonkey/tampermonkey#1253]
## Expected Behavior
Be totally dark

## Actual Behavior
![image](https://user-images.githubusercontent.com/49396421/120881320-c60e6b00-c602-11eb-8117-7cdaddcaee9a.png)

## Specifications

- Chromium: 91.0.4472.77
- TM: 4.13
- OS: Windows 10 21H1

**Comment by derjanb** [comment]
Fixed at 4.14.6141
