### ISSUE TITLE
TESLA

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1255]
(Please fill out the issue template with your details)

## Problem description
TESLA, when enabled and linked to Google Drive or OneDrive often freezes. It means the addon menu and control panel tab show lightblue ribbon with status of Sync started...but idles to timeout. If I invoke Synchronization by hand later, it shows system notification that it's waiting for finishing previous synchronization. The sync facility then can be restored only by disabling/enabling the addon in browser or restarting browser.
I didn't observe the issue with Dropbox yet and that's why I reverted to it.

I propose either to handle sync freezes by discarding stalled session in reasonable time to unblock further attempts, or remove the reason of freezing (which may be on the cloud provider side).

As a sidenote, when using GDrive as sync provider, browsers ask for re-login to Google (or at least confirming synced account if 2+) on new launch, which I find extra annoying. The background sync is great feature, but once set up, should work completely invisible to the user.

## Specifications

- Chromium: 91.0.4472.77, FF 54.0.1
- TM: 4.13 / 4.11
- OS: Win 8.1/x64

## Script

There's no script to demonstrate the issue on, it just happens on the addon self.

**Comment by derjanb** [comment]
Can you please check the [background console](https://www.tampermonkey.net/faq.php#Q600) for error messages?
