### ISSUE TITLE
script keeps getting removed

### ISSUE THREAD

**Issue by feiercrack** [Tampermonkey/tampermonkey#1256]
https://greasyfork.org/de/scripts/378976-corrected-coords

script with corrected geocaching coordinates

i used that a lot to verify my work.
now its completely vanished after my long disease.
after a long time period, i am healthy back again and want to use this script again.
but i cant find it anywhere...
what to do?
any help available?
many thanks

**Comment by Martii** [comment]
@feiercrack 
Your script hosting site has very little to do with TM here. Perhaps you should try logging into Greasyfork *(GF)* and ask. If your account is gone then you might, and I do emphasize might, make an issue at https://github.com/JasonBarnabe/greasyfork **after you check** why/if it was removed on GF at https://greasyfork.org/en/moderator_actions . You will need to find yourself if possible.

**Comment by feiercrack** [comment]
ok. thank you!
