### ISSUE TITLE
Issue with hyperbadge script - shows error after re- installing 

### ISSUE THREAD

**Issue by hmeera** [Tampermonkey/tampermonkey#1257]
(Please fill out the issue template with your details)

## Expected Behavior
Shows error for hyperbadge script on phonetool

## Specifications
Mozilla firefox browser 
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)
hyperbadge script
```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Tampermonkey is a userscript manager. Please contact the script developers if a script does not work. If there is a general problem with Tampermonkey then they will come back to me.
