### ISSUE TITLE
`Update.checked`  always auto change into `false`  , why?

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1261]
![216_09232844](https://user-images.githubusercontent.com/10995302/121383962-715c4e80-c97a-11eb-8c7d-7cf764a1afe2.png)

For example / Easy to reproduce : 

- current setting is : 
![216_09233131](https://user-images.githubusercontent.com/10995302/121384460-df087a80-c97a-11eb-91ef-cd2450095019.png)  `.checked === 1` 

- then , you **edit** UserJS code or **update** UserJS , after , it will auto change to 👇
![216_09233405](https://user-images.githubusercontent.com/10995302/121384815-2ee74180-c97b-11eb-8d99-6369e46a5bb0.png)	`.checked === 0` 

> I don't know why it will trigger itself to change settings ?
This brings up 1 big problem: If it is `.checked === 0` (automatically disable), the automatic update check will not be triggered.

**Comment by derjanb** [comment]
This is to prevent accidental loss of changes that might be difficult to restore as opposed to simply reactivating the setting.

**Comment by Invertex** [comment]
The fact that this is a hidden functionality that the user is not made aware of is bad UX. I had been wondering for ages why the auto-update keeps breaking every time I do development on a script and thus worrying that users wouldn't be getting my updates.

There should be some sort of warning asking if you'd like to disable auto-updates (if it's on) when you edit and save a script. This would also be important to let end-users know that once they've tweaked a script they won't be getting updates anymore, something I'm sure most would not be aware of.

A script meta flag to prevent this would be nice too, but that might be a bit of a stretch for a request...
