### ISSUE TITLE
the cachetur assistant 3.0.5.1

### ISSUE THREAD

**Issue by flat2let** [Tampermonkey/tampermonkey#1264]
(Please fill out the issue template with your details)

## Expected Behavior
after clicking on "activate cachetur assistant" it should provide a dropdown with all my routes

## Actual Behavior
the page just refreshes and nothing else happens

## Specifications

- Firefox 89
- Windows 10

**Comment by derjanb** [comment]
Tampermonkey is a userscript manager. Please contact the script developers if a script does not work. If there is a general problem with Tampermonkey then they will come back to me.

**Comment by flat2let** [comment]
Thanks for your response, I will do that. I am new in this subject so please excuse my error.
