### ISSUE TITLE
@require in libraries

### ISSUE THREAD

**Issue by BogudanPro** [Tampermonkey/tampermonkey#1266]
I'm trying to understand how exactly @require works. Current question is following.

Assume we have library A.js. Now we createlibrary B.js and add @require A.js. After this we create userscript C.user.js where we add @require B.js (only).

My question is: does not having A.js inside compiled C.user.js is intended behaviour or a bug? In other words: does @require should work recursively?

**Comment by derjanb** [comment]
`@require` only works on top level. Think of it as if the @require statement at the userscript was simply replaced with the contents of the URL.
