### ISSUE TITLE
GM_notification should implement actions

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1267]
(Please fill out the issue template with your details)

## Expected Behavior
GM_notification({title:"testa1",text:"test",actions:[{title:"test",action:"a1"}]}) displays a notificaiton with actions

## Actual Behavior

GM_notification({title:"testa1",text:"test",actions:[{title:"test",action:"a1"}]}) doesnt
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==

GM_notification({title:"testa1",text:"test",actions:[{title:"test",action:"a1"}]}) 
```

**Comment by 7nik** [comment]
To support the actions, TM should implement a way to register them or some alternative. Looks like a headache.

Note, you can already listen for clicking the notification:
```js
        GM.notification({
            text: "Click me",
            title: "Test 3",
            // user clicked the notification
            onclick: () => console.log("clicked"),
            // clicked/closed/timeout
            ondone: (clicked) => console.log(clicked ? "clicked" : "not clicked"),
        });
```

**Comment by jonnytest1** [comment]
> To support the actions, TM should implement a way to register them or some alternative. Looks like a headache.
> 
> Note, you can already listen for clicking the notification:
> 
> ```js
>         GM.notification({
>             text: "Click me",
>             title: "Test 3",
>             // user clicked the notification
>             onclick: () => console.log("clicked"),
>             // clicked/closed/timeout
>             ondone: (clicked) => console.log(clicked ? "clicked" : "not clicked"),
>         });
> ```

i was thinking to implement it using the service worker approach of a notification - which already has support for it 🤔

**Comment by derjanb** [comment]
This feature has only been requested once so far. Sorry.
