### ISSUE TITLE
Utilities > Install from URL results in "Unable to load script from url: ..." when URL that requires log in

### ISSUE THREAD

**Issue by clackwell** [Tampermonkey/tampermonkey#1269]
(Please fill out the issue template with your details)

## Expected Behavior

User script installation via Utilities > Install from URL works.

## Actual Behavior

- User script installation via Utilities > Install from URL works results in error ```Unable to load script from url: URL HERE``` when the URL requires logging in.

- After trying, the browser console shows a GET request that resulted in status 401:
```
HTTP/2 401 Unauthorized
server: nginx[...]
date: Mon, 21 Jun 2021 13:33:56 GMT
content-type: text/html
content-length: 195
www-authenticate: Basic realm="[...]"
X-Firefox-Spdy: h2
```

- When opening the URL directly, the URL is changed to end with "#bypass=true", the script contents is shown without the TM user interface (as if opening the URL in a browser that does not have TM installed).

## Specifications

- Firefox: 89.0.1
- TM: 4.13.6136
- OS: Ubuntu 20.04.2 LTS

## Script

Hopefully not relevant for the issue.

**Comment by 7nik** [comment]
Can you access the userscript in incognito mode / private window?
If no then I believe there is nothing that TM can do. There are just too many authentication methods, and TM can't know the exact method that the site uses.

**Comment by clackwell** [comment]
I can access the userscript in an incognito mode / private window, but it requires that I log in. If I do that, the URL gets "#bypass=true" appended to it, and the userscript file content is shown plain (not with the usual TM UI).

This used to work for years with exactly this web server. Can I perhaps try with older TM versions to check if it works with one of the version from the past few release?

**Comment by derjanb** [comment]
> Can I perhaps try with older TM versions to check if it works with one of the version from the past few release?

Sure, you can get previous FF version from here: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/

**Comment by JAGulin** [comment]
> I can access the userscript in an incognito mode / private window, but it requires that I log in. 

If you feel that it's safe, you could try the option to add the login credentials to the URL, 
https://stackoverflow.com/a/57080626/14315999

> the URL gets "#bypass=true" appended to it, and the userscript file content is shown plain (not with the usual TM UI).

I'm guessing the bypass is specifically there to bypass TM and my guess is that it's actually TM that does this. Would like author to comment on that and if so which scenario that causes it. 

Please test the script URL in a browser where you don't have TM installed, to see if URL is modified or not.
And if you have access to the server config you should check for any URL redirect there as well.

> There are just too many authentication methods, and TM can't know the exact method that the site uses.

The site would tell exactly that in the response headers. If you leave the loading to the browser, they should take care of the auth. I understand that auto-update isn't helped by a password prompt popup, but the manual "install from URL" action I think could use it. If not, you could still handle 401 errors different from other errors and write some guidance in log or UI.

**Comment by derjanb** [comment]
> If no then I believe there is nothing that TM can do. There are just too many authentication methods, and TM can't know the exact method that the site uses.

Thanks @7nik
