### ISSUE TITLE
Tampermonkey 4.13.6138 stops ublock origin from working

### ISSUE THREAD

**Issue by Lenmaer67** [Tampermonkey/tampermonkey#1271]
## Expected Behavior
ublock origin to block ads

## Actual Behavior
ublock origin doesn't block anything anymore when tampermonkey is activated.
Disabling tampermonkey and relaunching Opera fixes that problem.

## Specifications

- Chromium: Opera 77.0.4054.90
- TM: 4.13.6138
- OS: Windows 10

**Comment by Lenmaer67** [comment]
I have to launch Opera with Tampermonkey disabled, and then manually enable it to have ublock origin work.

**Comment by derjanb** [comment]
This is a Chrome/Opera issue. 

Please check [this comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1612#issuecomment-858893930) for a workaround.

The Chrome issue is already fixed so it will be fixed at Opera as well once they update the source to 91.0.4472.106.

**Comment by Lenmaer67** [comment]
That's weird, because that bug isn't happening when using tampermonkey v4.11.6120.

**Comment by Lenmaer67** [comment]
After Opera's today update everything works fine again.
Thanks.
