### ISSUE TITLE
Unable to @require a file from WSL

### ISSUE THREAD

**Issue by Jorgen1040** [Tampermonkey/tampermonkey#1273]
## Expected Behavior
Tampermonkey loads a file located on WSL using @require

## Actual Behavior
Tampermonkey fails to load the file and returns an error:
`Tampermonkey: couldn't load @require from URL file://wsl$/Ubuntu/home/some/path/to/userscript/script.user.js`
(Keep in mind, this URL works fine when accessed directly via Chrome)

I'm guessing this just isn't implemented, and if so I guess this is a feature request for adding WSL file support.

## Specifications

- Chromium: 91.0.4472.114
- TM: 4.13
- OS: Windows 10 21H1

## Script

Example userscript
```js
// ==UserScript==
// @name         Dev
// @require      file://wsl$/Ubuntu/home/some/path/to/userscript/script.user.js
// ==/UserScript==
```

**Comment by derjanb** [comment]
Are you sure file access is enabled? 

![image](https://user-images.githubusercontent.com/29704098/115952726-5e87da80-a4f0-11eb-8c90-aa53e9d052a2.png)

**Comment by Jorgen1040** [comment]
> Are you sure file access is enabled?

Can't believe I missed that. It works just fine now. Thanks!
