### ISSUE TITLE
No script is running issue

### ISSUE THREAD

**Issue by groovyd** [Tampermonkey/tampermonkey#1277]
## Expected Behavior

Icon badge indicates script instances running

## Actual Behavior

No icon badge and click menu says 'no script is running'

![Screen Shot 2021-07-01 at 5 21 50 PM](https://user-images.githubusercontent.com/33761369/124340860-38348a00-db86-11eb-8145-55c90502bcda.jpg)

## Specifications

- Safari 14.1.1
- TM: 4.13.6140
- OS: MacOS 11.4

## Script

SocialFixer

**Comment by groovyd** [comment]
Actual SocialFixer script is indeed running but about half the time TM shows no icon badge and no script running.  refreshing page sometimes fixes it and sometimes breaks it again.

**Comment by filbo** [comment]
That's with Social Fixer 27.2.0, currently at https://socialfixer.com/socialfixer.user.js but will be superseded.  The 27.2.1 beta script at https://socialfixer.com/test/27.2.1/greasemonkey/socialfixer.user.js is effectively identical and should not change.

This was after groovyd added to the script header, at my suggestion, `@noframes`.   Before that it showed 4 instances (perhaps not consistently).

**Comment by derjanb** [comment]
> but about half the time TM shows no icon badge and no script running

Sorry about that. Unfortunately there is nothing more I can do until I migrated Tampermonkey to [Safari web extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions).
