### ISSUE TITLE
Running a script only when a page is truly fully loaded?

### ISSUE THREAD

**Issue by Mrnofish** [Tampermonkey/tampermonkey#1279]
Strictly speaking, the following might not be a TamperMonkey bug:

### The problem

A script is running before the page has been loaded in full; `@run-at` is set to `document-idle`, however the only work around I've found so far, is to actively check `document.readyState` until it turns to `complete`.

(There is another, less desirable way, that is to trigger the script manually via the context menu.)

### Environment

TamperMonkey: 4.13.6136
Browser: Firefox 89.0.2
OS: Win10

### document-idle/DOMContentLoaded VS readyState complete
[From MDN, readyState:](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState)
```
interactive
    The document has finished loading and the document has been parsed but sub-resources such as scripts, images, stylesheets and frames are still loading.

complete
    The document and all sub-resources have finished loading. The state indicates that the load event is about to fire.
```
So the `load` event should be firing *shortly after* `readyState` turns from `interactive` to `complete`.

What I am seeing, instead, is that the script gets triggered about at the same time as `readyState` reaches `interactive`. Listening for the `load` event appears to work the same way.

My understanding is that TamperMonkey's `document-idle` listens to the event `DOMContentLoaded`, [which would explain why the script is injected long before the page is done loading](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event).

I'm not sure, though, why the `load` event would be triggered at `interactive` and not `complete`. Maybe a Firefox bug, or maybe I am missing something big here.

### What's your take?
There seems to be no way, currently, for TamperMonkey to only run a script after a page is done loading in full.

Would it be possible for TamperMonkey to provide a solution that doesn't require the script to do this job?

**Comment by Mrnofish** [comment]
Shucks, I had to restart my browser and now the workaround no longer works.

I had to add a fixed delay after the readyState change. If not even readyState works as expected, what will?

**Comment by joeytwiddle** [comment]
One concern is that scripts relying on this proposed TamperMonkey feature would then not work with other userscript extensions. (Although I'm not sure how popular the others are in 2021. I'm using TamperMonkey everywhere myself.)

Many websites these days load some bootstrap HTML and JS first, and then load the actual content purely through AJAX requests. (Not ideal, but they do!)

The solution I usually fall back on is a setTimeout loop which looks for the thing that I need to be present (often just checking that a selector matches something).

A convenience function to encapsulate that behaviour might be helpful. But I'd probably just copy that from script to script, rather than push it into a library or into Tampermonkey itself. "A little copying is better than a little dependency." - GoLang proverb

**Comment by Mrnofish** [comment]
Userscripts are meant to empower end-users, who I suspect may, in many instances, find the intricacies of async JavaScript hard to grok.

Javascript and web design started out very simple, and were meant to cater to a less technical audience than, say, folks who code in Go.

TamperMonkey and JavaScript make for a very gentle introduction and learning curve, suitable to anybody, no matter how little programming and JavaScript experience they have. 

But, as deftly noted, many sites these days throws the basics of web design to the wind and deliver JavaScript-only content.

Since the scenario is so commonplace now, many beginners will stumble on this problem early on, and be forced to reinvent the wheel. They may find themselves unable to come to a solution, because even asking the right questions to a search engine requires a certain level of knowledge and expertise.

I have no problem admitting, had I run into this problem myself when I was more green, I might have given up entirely.

Even then, implementing an inelegant solution (partially dynamic, but relying on a hard-coded timeout) actually was rather costly in term of time for me, having had to figure out a lot of stuff on my own, not just the hows but the whys in the first place.

For these reasons, I think there is value in this change; while not huge for someone who has wrapped their mind around it, and maybe keeps code snippets handy, it still does away with rote repetition.

Also, even though it isn't strictly speaking a bug, I'd argue that TamperMonkey isn't behaving intuitively in its current shape.

My 2 cents.

**Comment by derjanb** [comment]
Depending on the page add an event listener and wait for the `load` event or use a lib like [waitForKeyElements](https://gist.github.com/BrockA/2625891).

**Comment by Mrnofish** [comment]
@derjanb Nobody is saying that there aren't alternative solutions, the gist of the matter is that the user expects TM to fulfill a certain task, while in truth it isn't capable of accomplishing that task in satisfactory matter.

Those alternative solutions:
1. Require an understanding of the problem to begin with, which may not look like rocket science to you, and nevertheless provides a substantial barrier to entry to beginner script writers
2. Are not exactly straightforward to deploy, far removed from flipping a switch in the script's settings

So my own personal problem has been solved a long time ago, because I had the motivation and the resources to acquire the necessary skills, but others might simply give up on solving it and get soured on the extension which they may perceived as broken.

**Comment by dsm2005** [comment]
> One concern is that scripts relying on this proposed TamperMonkey feature would then not work with other userscript extensions. (Although I'm not sure how popular the others are in 2021. I'm using TamperMonkey everywhere myself.)
> 
> Many websites these days load some bootstrap HTML and JS first, and then load the actual content purely through AJAX requests. (Not ideal, but they do!)
> 
> The solution I usually fall back on is a setTimeout loop which looks for the thing that I need to be present (often just checking that a selector matches something).
> 
> A convenience function to encapsulate that behaviour might be helpful. But I'd probably just copy that from script to script, rather than push it into a library or into Tampermonkey itself. "A little copying is better than a little dependency." - GoLang proverb
> 

This is really nice, thanks! I've tweaked my implementation to use a timeout expressed in seconds, rather than in iterations, for clarity (at least to my mind). Also uses the performance package:

```
// Convenience function to execute your callback only after an element matching readySelector has been added to the page.
// Example: runWhenReady('.search-result', augmentSearchResults);
// Gives up after specified duration.
function runWhenReady(readySelector, callback) {
    const TIMEOUT_SEC = 10;

    performance.mark("startReadyCheck");
    var tryMeasure;
    var numAttempts = 0;
    var tryNow = function() {
        var elem = document.querySelector(readySelector);
        if (elem) {
            callback(elem);
        } else {
            numAttempts++;
            tryMeasure = performance.measure("startReadyCheck");
            if (tryMeasure.duration > (TIMEOUT_SEC * 1000) ) {
                console.log("Giving up after", tryMeasure.duration/1000, "seconds; could not find", readySelector);
            } else {
                setTimeout(tryNow, 250 * Math.pow(1.1, numAttempts));
            }
        }
    };
    tryNow();
}
```
