### ISSUE TITLE
Sending Raids Bug

### ISSUE THREAD

**Issue by worriedcitizen2015** [Tampermonkey/tampermonkey#1280]
## Expected Behavior
Queue/Program raids and attacks

## Actual Behavior
Failing getting an error "server page failed 1"
<img width="193" alt="2021-07-08 08_11_00" src="https://user-images.githubusercontent.com/87132686/124927314-1bec7f00-dfc4-11eb-8ef1-c31e3e8b0ac5.png">

## Specifications

- Chromium: Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by 7nik** [comment]
Tampermonkey is a userscript manager. Please contact the script developers if a script does not work. If there is a general problem with Tampermonkey then they will come back to me.
