### ISSUE TITLE
[Feature Request] Dark Mode support to scrollbars

### ISSUE THREAD

**Issue by Geeyun-JY3** [Tampermonkey/tampermonkey#1281]
## Expected Behavior
Dark scrollbar in Tampermonkey dashboard when the layout is set as Dark/Darker

## Actual Behavior
Bright/white scrollbar

## Specifications
- Chromium: 91.0.4472.77
- TM: 4.13
- OS: Windows 10 21H1

**Comment by derjanb** [comment]
Should be fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))
