### ISSUE TITLE
Add a button to force sync

### ISSUE THREAD

**Issue by SmartManoj** [Tampermonkey/tampermonkey#1282]
![image](https://user-images.githubusercontent.com/7231077/125168375-eb266880-e1c2-11eb-99a3-5dffe18a72a8.png)

**Comment by SmartManoj** [comment]
In beta too,
![image](https://user-images.githubusercontent.com/7231077/125168523-933c3180-e1c3-11eb-8776-441a37b128e8.png)

**Comment by derjanb** [comment]
Fixed at 4.14.6142
