### ISSUE TITLE
`GM_download` downloads file with wrong suffix

### ISSUE THREAD

**Issue by Compartany** [Tampermonkey/tampermonkey#1283]
It can be reproduced with the following code. The downloaded file should be `.jpg`, but instead it is downloaded as `.txt`. I suspect the reason is that the image size is too small (< 100KiB), because images of a slightly larger size are downloaded back correctly.

```js
// wrong suffix
GM_download({ name: 'test', url: 'https://i0.hdslb.com/bfs/bangumi/fb7e3e784c2ac32c6ecb4bad14043ef4e743a878.jpg' })
GM_download({ name: 'test', url: 'https://i0.hdslb.com/bfs/bangumi/72c46a24e266cb6040a6320de1395276cc6d38b3.jpg' })

// correct suffix
GM_download({ name: 'test', url: 'https://i0.hdslb.com/bfs/bangumi/10e90ed6acd3edcfb0d7f353b85f283e30c091a1.jpg' })
```

> Edge 91.0.864.67
> Tampermonkey 4.13.6138

**Comment by 7nik** [comment]
At manual saving these images, they get `.txt.` extension as well (Cromium 91, Archlinux). 
I think it's because the stupid server set `content-type: text/plain` header and the browser changes extension according to the header. 
The bigger image has correct header `content-type: image/jpeg`.

**Comment by derjanb** [comment]
@7nik Thanks for investigation.

Besides this defining a complete file name works fine as well. So there is nothing else Tampermonkey can do here.

```JS
// wrong suffix
GM_download({ name: 'test1.jpg', url: 'https://i0.hdslb.com/bfs/bangumi/fb7e3e784c2ac32c6ecb4bad14043ef4e743a878.jpg' })
GM_download({ name: 'test2.jpg', url: 'https://i0.hdslb.com/bfs/bangumi/72c46a24e266cb6040a6320de1395276cc6d38b3.jpg' })

// correct suffix
GM_download({ name: 'test3.jpg', url: 'https://i0.hdslb.com/bfs/bangumi/10e90ed6acd3edcfb0d7f353b85f283e30c091a1.jpg' })
```
