### ISSUE TITLE
[Feature Request] Make script trash optional

### ISSUE THREAD

**Issue by Geeyun-JY3** [Tampermonkey/tampermonkey#1284]
## Expected Behavior
Make script trash optional. I just want it delete the script directly.

## Specifications
- Chromium: 91.0.4472.77
- TM: 4.13
- OS: Windows 10 21H1

**Comment by derjanb** [comment]
Fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))
