### ISSUE TITLE
[Feature request] Warn users about disabled access to files

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#1286]
It seems quite many people think TM can open local files out of the box, so it would be useful to warn them that it isn't so when a userscript needs access to local files.

The [isAllowedFileSchemeAccess](https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedFileSchemeAccess) method allows checking whether the user provided access to local files. So, at saving or importing a userscript with `@request` or `@resource` with the `file:` schema, TM can check access to local files and ask the user to provide the access if needed. Another way can be printing the warning in the console after the message about failed attempt to load a file.

Also, it probably makes sense to warn users that Firefox currently doesn't support access to local files.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6142. A console message with some details is logged.

**Comment by 7nik** [comment]
Not sure how many people will check the background's console with at least the warning level of logging.

**Comment by derjanb** [comment]
It was a background console warning earlier. Now there also is a warning at the page's console.

**Comment by 7nik** [comment]
That's all I see at the page's console even with debug level. Nothing about disabled access to files.
![image](https://user-images.githubusercontent.com/29704098/126820756-d4c89491-e0dd-49c1-86ae-a89043b022e0.png)

**Comment by derjanb** [comment]
Next try! 😂 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))
