### ISSUE TITLE
Enhance the multi-select operation of the list on the dashboard page!

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1287]
```js
															this page 👇
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=dashboard
```
> Currently, it is very inconvenient when operating in batches! 

```css
		// When entering batch multiple selection mode: i.e.👇
		table.multiselectvisible.multiselect.scripttable
```

### Expected behavior at this time:
- Clicking on the entire row of each list is equivalent to clicking a small `input[type=checkbox]` element.
```js
	let TARGET = event.target,
		$li = TARGET.closest(`tr.scripttr`),
		$liCk = $li.querySelector(`input[type=checkbox]`);
		
	if(TARGET.matches(`tr.scripttr`))		$liCk.click();
```

- Can list hotkeys be supported ?
	* Holdind `Shift` : can interval selection !

**Comment by derjanb** [comment]
Once one script is selected you can use Ctrl+up/down to select more. Ctrl+a is also working.

**Comment by dnknn** [comment]
> Ctrl+a is also working.

I know this, it is equivalent to holding `Ctrl`

> Ctrl+up/down to select more. 

I tested it and it didn't work,  then even if it works, it is not convenient. 
Using Ctrl+up/down will make the operation more expensive.

So I personally think that when entering the batch selection mode, 
we better support the click of each `tr` entire line.

Then support holdind `Shift` to interval selection !

This will make the selection a lot easier!
