### ISSUE TITLE
Export to Zip or File doesn't open file save dialog

### ISSUE THREAD

**Issue by dmland** [Tampermonkey/tampermonkey#1288]
## Expected Behavior

After clicking the Export button in the Zip or File sections of the Utilities tab, and after the spinner indicates that the export is complete, I expect a file-save dialog so that I can save the export somewhere.

The same behavior occurs on the dashboard > Select all > Apply this to all selected Scripts > Export > Start: The spinner spins, a notification bar appears at the top "✓ Operation completed successfully," but no opportunity to save the resulting zip file.

## Actual Behavior

No file save dialog.

Also, the export takes a suspiciously short time: I have 167 scripts, and the spinner runs for maybe 2 seconds. It is possible that you're caching a previous export, which might make it less suspicious.

In the meanwhile, I performed an export to the textarea and saved that as a JSON file, but that's obviously not the ideal way to work. :-) I hope it's complete. It's 5.6mb, which seems about right for my script library.

# Specifications

- Chromium: Version 91.0.4472.114
- TM: v4.14.6141
- OS: 10.15.7

## Script

N/A

**Comment by derjanb** [comment]
Should be fixed at 4.14.6142

**Comment by dmland** [comment]
No save dialog, but the zip downloaded and automagically opened in my zip app. All is well.

Would prefer to be offered a chance to choose where to save the export, but then again, I'm a demanding preson.
