### ISSUE TITLE
Is there a way to listen `console.log` from other scripts?

### ISSUE THREAD

**Issue by liangjiancang** [Tampermonkey/tampermonkey#1289]
What I mean is that under normal circumstances we can listen to the logs in the following way.

```js
// from https://stackoverflow.com/a/6455726/7152981
console._log_old = console.log
console.log = function(msg) {
    alert(msg);
    console._log_old(msg);
}
```

Obviously this does not work for userscripts, because the `console` object in userscripts is fake and cannot be overridden externally. But that's exactly what I'm aiming for. Is there a way to achieve it?

**Comment by 7nik** [comment]
No, because it means that a userscript can get out of its sandbox and affect the work of other userscripts. And this is bad.

> that's exactly what I'm aiming for

No, it's absolutely not clear what you want to achieve with it and thus other people cannot suggest to you other solutions without being a telepath.

**Comment by liangjiancang** [comment]
This is bad in the usual sense, but greatly beneficial for debugging. My intention is to use one script to consolidate reporting of problems that occur with other scripts for subsequent optimization.

**Comment by 7nik** [comment]
As a workaround, you can create a wrapping userscript: copy only the meta block from the target script and insert one `@require` at the beginning with a link to your script that does what you need and another `@require` with the link to the target script at the end. Thus you'll get a copy of your target userscript prepended with your code. But you need to keep the meta block synced with the target script.

**Comment by liangjiancang** [comment]
> As a workaround, you can create a wrapping userscript: copy only the meta block from the target script and insert one `@require` at the beginning with a link to your script that does what you need and another `@require` with the link to the target script at the end. Thus you'll get a copy of your target userscript prepended with your code. But you need to keep the meta block synced with the target script.

It's not that convenient, but it's enough for local development. In fact, I've been developing with "wrapping userscripts" you mentioned, so this solution for me is just simply `@require` the error detection script for my existing "wrapping userscripts".
