### ISSUE TITLE
GM.notification({ highlight: true }) don't focus a window

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#1292]
The command `GM.notification({ highlight: true })` do not focus a window.

## Expected Behavior

If tabs are spread across multiple windows, the target tab will get focused and its window will get the focus as well. If applied to a popup window, the window should just get focus.

## Actual Behavior

The tab gets focused but the focused window remains the same.

## Specifications

- Chromium: (91.0.4472.114)
- TM: (4.13)
- OS: (KDE Manjaro Linux)

## Script

```js
// ==UserScript==
// @name         Test window highlighting
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       7nik
// @match        http://www.blanksite.com/*
// @icon         https://www.google.com/s2/favicons?domain=blanksite.com
// @grant        GM.setValue
// @grant        GM.addValueChangeListener
// @grant        GM.notification
// ==/UserScript==

(function() {
    'use strict';

    if (!window.location.hash) {
        window.open("http://www.blanksite.com/#child", "title", "width=300,height=300");
        window.addEventListener("click", () => GM.setValue("dothetrick", Math.random()));
    } else {
        GM.addValueChangeListener("dothetrick", (name, oldValue, newValue, remote) => {
            document.body.firstElementChild.textContent = newValue;
            GM.notification({ highlight: true });
        });
    }

})();
```
Go to http://www.blanksite.com/ , a popup window will appear, then clicking anywhere on the main tab should make the popup window focused but it doesn't. 

To open in a tab, drop the third argument of the `window.open`.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))
