### ISSUE TITLE
Wrong matching at localhost

### ISSUE THREAD

**Issue by ForkKILLET** [Tampermonkey/tampermonkey#1293]
## Expected Behavior

I wrote `@match http://localhost:1634/*`, so the script should run on only port 1634.

## Actual Behavior

When I opened anthor port 1633, to my surprise, the script ran as well.

## Specifications

- Chromium: 93.0.4549.3 dev
- TM: 4.13
- OS: Archlinux

**Comment by Mrnofish** [comment]
According to this StackOverflow question, `@match` is not supposed to work against port numbers.

https://stackoverflow.com/questions/20462544/greasemonkey-tampermonkey-match-for-a-page-with-parameters

**Comment by ForkKILLET** [comment]
thanks
