### ISSUE TITLE
GM_getResourceText returns nothing after external HTML is edited from TM Editor

### ISSUE THREAD

**Issue by jeisonfriedman** [Tampermonkey/tampermonkey#1297]
GM_getResourceText works well, but after I edit and save the HTML external using the TM Editor, it returns nothing (empty). And only happens with HTML externals, no with CSS.

**Edited:**
By the way, I forgot to say that I use to edit externals (HTML/CSS) directly in TM Editor, cause TM isn't reloading them from server, but from cache, although I set up _Always_ the _External > Update interval_ setting. That isn't working well either. And it is not a server cache setting, cause when I open the externals URLs directly in the browser, it always gets the updated file content.

## Expected Behavior

GM_getResourceText returns always the external content.

**Edited:**
GM_getResourceText loads from server when  _Externals > Update interval > Always_ is set up.

## Actual Behavior

GM_getResourceText returns nothing after the external HTML was edited/saved.

**Edited:**
GM_getResourceText loads from cache although _Externals > Update interval > Always_ is set up.

## Specifications

- Chromium: 91.0.864.71 x64 - MS Edge
- TM: 4.13
- OS: W10

## Script

// ==UserScript==
// @name         Name
// @description  Desc
// @author       Author
// @version      1.0
// @namespace    https://example.com/
// @match        https://example.com/*
// @updateURL    https://example.com/script.js
// @downloadURL https://example.com/script.js
// @require      https://example.com/otherscript.js
// @resource     scrCss https://example.com/script.css
// @resource     scrHtml https://example.com/script.html
// @connect      example.com
// @grant        GM_getResourceText
// @grant        GM_xmlhttpRequest
// @grant        GM_setValue
// @grant        GM_getValue
// @grant        GM_addValueChangeListener
// @run-at       document-end
// ==/UserScript==

**Comment by derjanb** [comment]
This is working fine here using a small example script. Can you please make it fail or attach yours?

```JS
// ==UserScript==
// @name         userscript.zone @ example.com
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://example.com
// @resource html https://www.userscript.zone
// @grant        GM_getResourceText
// ==/UserScript==

const html = GM_getResourceText('html');
document.body.innerHTML = html;
```

**Comment by dannysunday** [comment]
thank you for ur reply, i m still kind of not totally understand. anyway, i will follow ur instruction n do it again, 1, u suggest i download fire fox as my browser? 2, when u said userscript, snd the example, what should i put in it?

best regards

dan

Get Outlook for Android<https://aka.ms/AAb9ysg>

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
