### ISSUE TITLE
This script was modified by another tab

### ISSUE THREAD

**Issue by reaseno** [Tampermonkey/tampermonkey#1298]
I often get the message "Userscript modification  CONFLICT: This script was modified by another tab 843 second(s) ago!". But I have no other open tab with that script. Its also annoying as it opens a new tab for this.

Maybe reasons:
- "Save content when editor loses focus" activated
- WebDAV sync

## Expected Behavior
- no message

## Actual Behavior
- opening a new tab with message and needed action

## Specifications

- Chrome/92.0.4515.126
- TM: 4.1.3
- OS: Win10

**Comment by Mrnofish** [comment]
I had a bout of this, too, after switching sync to WebDAV (TamperDAV). As I could not get TamperDAV to work as expected (i.e. TamperMonkey promptly picking up changes made in the external editor), I started forgetting to start TamperDAV before the browser, and TamperMonkey began complaining seemingly at random.

After a while, TamperMonkey stopped complaining. Not sure why this has happened, but make sure your WebDAV sync is working as it should or, if possible, try switching to a different sync method for a while and see if that fixes it.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))

**Comment by Mrnofish** [comment]
Nice, thank you! Any chance this might cure the issue mentioned above with TM not picking up changes from the external editor, or was this unrelated?

**Comment by derjanb** [comment]
> TM not picking up changes from the external editor, or are the two unrelated?

They are unrelated. However, this is working fine here. Are you sure TamperDAV is started before TM/your browser is started and TamperDAV is started with the [`meta-touch`](https://github.com/Tampermonkey/tamperdav#all-options) option enabled?
