### ISSUE TITLE
Use `eslint-plugin-userscripts`

### ISSUE THREAD

**Issue by Yash-Singh1** [Tampermonkey/tampermonkey#1300]
I built a little `eslint` plugin called `eslint-plugin-userscripts` that helps validate userscripts. It would be useful to enable this in the CodeMirror editor. Here is a link for more info: https://github.com/Yash-Singh1/eslint-plugin-userscripts#readme.

**Comment by derjanb** [comment]
Included in 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))

However, I feel there is room for improvement... :-)

**Comment by Yash-Singh1** [comment]
> However, I feel there is room for improvement... :-)

You can always create a feature request for a new rule.
