### ISSUE TITLE
Tampermonkey page is opened on every start of Firefox

### ISSUE THREAD

**Issue by workflowsguy** [Tampermonkey/tampermonkey#1301]
## Expected Behavior
When opening Firefox, only the pages that where open on when FF was last closed should be reopened

## Actual Behavior
Every time Firefox starts, the page `https://www.tampermonkey.net/index.php?version=4.13.6136&ext=fire&updated=true`
opens in addition to the previously open pages

## Specifications

- Firefox 90.0.2
- TM: 4.13.6136
- OS: macOS 10.13.6

**Comment by derjanb** [comment]
This page should be shown only after installation. Maybe your browser profile is broken? Please try a new temporary profile.

**Comment by dannysunday** [comment]
thank you, but Chrome don't  with it?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by workflowsguy** [comment]
@derjanb, this issue is is not related to a broken browser profile.
It occurs only when the addon "CanvasBlocker" is also installed and active.
