### ISSUE TITLE
Script settings have some serious issues with them not saving/persisting

### ISSUE THREAD

**Issue by starkapandan** [Tampermonkey/tampermonkey#1302]
The settings in tampermonkey is really frustrating to work with. Settings do not persists...

## Expected Behavior
* Select any script and disable it.........script stays disabled -> GOOD
* Go into any script settings, select the checkbox to allow update of this script.........checkbox stays checked in-> GOOD

## Actual Behavior
* Select any script and disable it.........1-4 days passes .... script reenables itself (and vice versa if enabled then it disables) -> NOT OK
* Go into any script settings, select the checkbox to allow update of this script.........1-4 days passes..... update checkbox have been unticked-> NOT OK

I can't say exact but my guess is settings are not saved or are conflicting between chrome instances. Say i untick some setting in my desktop, then go to laptop and it sees it "reticked" so it saves back to that...??

## Specifications
chrome windows 10

**Comment by Mrnofish** [comment]
Are you sure this is not a sync issue?

**Comment by derjanb** [comment]
I suspect something is restoring the Chrome profile after some time. Tampermonkey itself does not sync script enabled states (and of course does not alter it without user interaction).

**Comment by starkapandan** [comment]
@derjanb why was this closed? the bug still persists in the current up to date extension in chrome webstore?
