### ISSUE TITLE
Problems with the export/import settings option in TM beta 4.14.6142

### ISSUE THREAD

**Issue by JohnD78** [Tampermonkey/tampermonkey#1306]
In TM beta 4.14.6142, the global Tampermonkey settings are not loaded when importing from a file or Zip file made with TM beta 4.14.6142 even if the "Include Tampermonkey settings" option is checked.
If the export file was created in a previous version of TM, there are no problems.

## Specifications

- Chromium: 92.0.4515.131
- TM: v4.14.6142 Beta
- OS: Win 7x64

**Comment by derjanb** [comment]
Should be fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))

Thanks for reporting!

**Comment by JohnD78** [comment]
Thank you! Everything seems to be in order.
