### ISSUE TITLE
Pass the clicked mouse button and modifier to callback of GM_registerMenuCommand

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#1307]
This is a feature request. If implemented here, I'll add it to Violentmonkey as well.

Internally, Tampermonkey would construct a `MouseEvent` using `button` and modifiers at the time of event in the popup. If TM currently uses `click` then it would need to switch to `mouseup` and check that its target is equal to the one in `mousedown`.
```js
fn(new MouseEvent('click', {button, shiftKey, altKey, ctrlKey, metaKey}))
```

The values of `button` are listed in https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

>0: Main button pressed, usually the left button or the un-initialized state
1: Auxiliary button pressed, usually the wheel button or the middle button (if present)
2: Secondary button pressed, usually the right button
3: Fourth button, typically the Browser Back button
4: Fifth button, typically the Browser Forward button

Usage example:
```json
GM_registerMenuCommand('foo', e => alert('Button ' + e?.button + ', shift: ' + e?.shiftKey));
```

**Comment by derjanb** [comment]
Should be fixed at 4.14.6143 (in review|[crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_14_6143.crx))
