### ISSUE TITLE
The enable/disable scripts setting is not imported in TM beta v4.14.6143.

### ISSUE THREAD

**Issue by JohnD78** [Tampermonkey/tampermonkey#1309]
The enable/disable scripts setting is not imported in TM beta v4.14.6143. 
When importing files, the enable/disable setting for each script is ignored. 
After importing a file, all scripts are enabled regardless of the settings in the file.

## Specifications

- Chromium: (92.0.4515.131)
- TM: (beta v4.14.6143)
- OS: (Win 7x64)

**Comment by derjanb** [comment]
Should be fixed at 4.14.6144 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6144.crx))

**Comment by JohnD78** [comment]
Checked, I confirm that the bug has been fixed. Thanks!
