### ISSUE TITLE
@resource doesn't check REMOTE_CSS url for possible changes

### ISSUE THREAD

**Issue by Kurdz2** [Tampermonkey/tampermonkey#1310]
## Expected Behavior
as the title says, it should recheck the REMOTE_CSS url for possible changes then load it, 
so in order for this to work, i open up TM editor, delete one letter of the REMOTE_CSS url, save it, CTRL + Z and save it 
i have to make tampermonkey think that the link was edited
## Actual Behavior
instead it just uses the previews cached version of it,

## Specifications

- Browser: Edge
- TM: (4.13...)
- OS: (windows 11)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         xxxx
// @namespace    xxxx
// @version      0.2
// @description  KA
// @author     Kalary
// @match      https://test.net/*
// @icon         https://www.google.com/s2/favicons?domain=test.net
// @run-at      document-end
// @require     https://code.jquery.com/jquery-3.6.0.slim.min.js
// @require     file:///C:/Users/{user}/Documents/xxx.js
// @grant        GM.xmlHttpRequest
// @resource   REMOTE_CSS https://drive.google.com/uc?export=view&id={FILEID}
// @grant        GM_getResourceText
// @grant        GM_addStyle
// ==/UserScript==

```

**Comment by 7nik** [comment]
Settings -> Externals -> Update Interval: -> Always / Every Day / Every Week (default) / Every Month / Never.
Also, in the script editor, you can go to the Externals tab and delete/edit external data.

**Comment by Kurdz2** [comment]
> Settings -> Externals -> Update Interval: -> Always / Every Day / Every Week (default) / Every Month / Never.
> Also, in the script editor, you can go to the Externals tab and delete/edit external data.

Thanks a bunch issue solved, 7nik <3
