### ISSUE TITLE
GM_download does not download to specified subfolder. Again.

### ISSUE THREAD

**Issue by afgit** [Tampermonkey/tampermonkey#1311]
The same issue as #1010. It has been fixed before but it's broken again.

## Expected Behavior
When GM_download is called with the "name" parameter set with a forward slash "/", the downloaded file should be created inside that folder.
Example:
`name: "sample/sample_image.jpg"`
should result in the file created with the path:
`Downloads\sample\sample_image.jpg`
## Actual Behavior
The forward slash is instead renamed as a dash ("-").
Example:
`name: "sample/sample_image.jpg"`
the file is instead created as
`Downloads\sample_sample_image.jpg`

## Specifications
It works in Firefox with Download mode set to "standard".
It does *not* work in Brave (or Chrome) with any download mode setting.

- Brave: Version 1.28.105 Chromium: 92.0.4515.131
- TM: both 4.13 (release) and 4.14.6143 (beta)
- OS: Ubuntu Linux 20.04.3 LTS, Windows 10

## Script
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://i.redd.it/xf13lv5n2qf51.jpg
// @grant        GM_download
// ==/UserScript==

    'use strict';
    let downloadArgs = {
        url: document.querySelector("img").currentSrc,
        name: "sample/sample_image.jpg"
    }
    GM_download(downloadArgs)
```

Maybe I'm missing something and there is a workaround!?

**Comment by disco0** [comment]
I had this issue for a few months with Chrome Canary and TM Beta build on multiple computers—it ended up being a problem with the global settings storage, and it actually causing multiple (mostly less obvious and seemingly unrelated) issues. 

Eventually I exported a full backup zip via TM's Utilities panel and checked `Tampermonkey.global.json`, it's contents were literally just `true`. After replacing the `true` with a pair of brackets (and restoring from this modified backup) I was able to apply the correct settings and everything was working fine. 

Before fixing, any time I tried to change the config mode from novice to advanced to allow setting the Download Mode it'd fail silently with a success message, and refreshing the page would then reveal nothing had actually changed.

All this is to say I'm getting a little deja-vu from a comment in the previous thread and your situation, figured I'd comment.

> It works in Firefox with Download mode set to "standard".
> It does not work in Brave (or Chrome) with any download mode setting.

Subfolder downloads should only work in Chrome when using the Browser API mode, btw

**Comment by afgit** [comment]
Thanks for the hint, I'll give it a try and report whether it solved the issue!

**Comment by derjanb** [comment]
> Eventually I exported a full backup zip via TM's Utilities panel and checked Tampermonkey.global.json, it's contents were literally just true. 

🙈 Fixed at 4.14.6143

> Subfolder downloads should only work in Chrome when using the Browser API mode, btw

[Exactly](https://github.com/Tampermonkey/tampermonkey/issues/1010#issuecomment-678817007) :+1:

**Comment by afgit** [comment]
So I took a deeper look into the settings: they were all ok.

But I was thinking naively that Brave and Chrome behave exactly the same - which is unfortunately not the case:
Trying again in Chrome, it works, but not in Brave 😒

So it's probably nothing Tampermonkey can do about, is it?

**Comment by derjanb** [comment]
> So it's probably nothing Tampermonkey can do about, is it?

Yes, looks like Brave simply prevents this.
