### ISSUE TITLE
Storage viewer updates too slowly, Reload button behavior is unintuitive

### ISSUE THREAD

**Issue by Mrnofish** [Tampermonkey/tampermonkey#1312]
## Expected Behavior
After saving a manual change in the Storage tab of a script, it should be possible to view further changes made subsequently by the script itself.

## Actual Behavior
- The changes made by the script immediately after the manual edit, do not become visible in a timely manner, the Storage textarea still shows the changes made manually
- Pressing Reload to force the Storage viewer to refresh, actually brings up a confirmation request to reset all changes. Pressing OK restores the Storage to its previous state.
- After a few minutes(?), the Reload button does what it says on the tin, and eventually updates the textarea with the current state of the storage

The delay between the changes and the Storage viewer updating makes it hard to keep tabs on what is happening.

If the viewer cannot update automatically quickly enough, then there should be two different buttons:
- One to force the viewer to update
- And another to undo changes

The slow update rate in combination with the same button performing two different functions, enforces a stalemate and a long wait, that can only be worked around by modifying the script to constantly log the Storage state.

## Specifications

- Firefox 91.1
- TM: 4.13.6136
- OS: Windows 10

**Comment by derjanb** [comment]
Fixed at 4.14.61445.

Note: All recent Firefox versions are stuck in review ([which seems to be a known problem](https://discourse.mozilla.org/t/add-on-review-questions/82754))
