### ISSUE TITLE
Tampermonkey "couldn't load @require from URL"

### ISSUE THREAD

**Issue by gasparschott** [Tampermonkey/tampermonkey#1319]
(Please fill out the issue template with your details)

## Expected Behavior
@require links pointing to https://cdn.jsdelivr.net/ (e.g.: https://cdn.jsdelivr.net/npm/markdown-it@12.0.4/dist/markdown-it.min.js) should be loaded into the script

## Actual Behavior
Such links are not loaded, with error "Tampermonkey couldn't load @require from URL ...." 
This behavior just began yesterday; previously all scripts were loading normally.
It it important to note that an @require link to jQuery (https://code.jquery.com/jquery-latest.min.js) continues to work normally.
Also, linking to another cdn (e.g.: https://cdnjs.cloudflare.com/ajax/libs/markdown-it/12.2.0/markdown-it.min.js) does not resolve the issue.

## Specifications

- Vivaldi: (4.1.2369.21)
- TM: (4.13)
- OS: (MacOS 11.5.2)

## Script

Script is located here: https://openuserjs.org/scripts/gaspar_schot/Supercharged_Local_Directory_File_Browser

**Comment by derjanb** [comment]
Working fine on Chrome 96.0.4651.0 + Ubuntu and Vivaldi 4.3.2431.3 + Windows 10. Can you still reproduce the issues?

**Comment by gasparschott** [comment]
Thank you, the external scripts started loading again a few days after my post. I never determined the cause the of the problem.
