### ISSUE TITLE
Adding more API features to `@run-at context-menu`?

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#1321]
I want to implement `@run-at context-menu` in https://github.com/violentmonkey/violentmonkey/issues/1364 but the feature seems incomplete to me if we can't specify sites where to show the menu. Here's my idea:

* `@match` (multiple) will be used for `documentUrlPatterns` so that scripts can control where they appear. Note that the API doesn't support other matchers such as `@exclude-match`, `@include`, `@exclude`.
* `@run-at-context` with `page` by default, possible values: `all frame selection link editable image video audio`
* `@run-at-target` (multiple) will be used for `targetUrlPatterns`

What do you think?

**Comment by 7nik** [comment]
Seems `@run-at context-menu` already supports `@match`, `@include`, and `@exclude` - likely since 4.12.6121 (2020-11-08).

I haven't used `@run-at context-menu` so can't say much but wouldn't it be useful for `@run-at-context` with `selection link image video audio` pass `linkUrl`/`srcUrl`/`selectionText` to the script via `GM.targetContext` or something?

**Comment by derjanb** [comment]
> Seems @run-at context-menu already supports @match, @include, and @exclude - likely since 4.12.6121 (2020-11-08).

That's right. `@run-at context-menu` now works like regular userscripts with the only difference that the execution time does not depend on the page's load progress but a user action which triggers the start.

**Comment by tophf** [comment]
So I guess you listen on keydown/mousedown and dynamically toggle the menu. While technically possible, I don't see it as a good approach as it's dependent on the internal timings of the click event sequence and the duration of the API call to update the menu. This is why I'd like to implement just `@match` which is directly translatable into `documentUrlPatterns`.

What about the other suggestions?

**Comment by 7nik** [comment]
> So I guess you listen on keydown/mousedown and dynamically toggle the menu.

I use such an approach in my extension but there is also a script on the page that decides whether to show the menu item and tells the background page to show or hide it. _Most time_ it works properly.

For `@run-at context-menu` I think it is easier to just rebuild the list of menu items when a user goes to another tab or page.

**Comment by derjanb** [comment]
> What about the other suggestions (@run-at-context and @run-at-target), @derjanb?

I'm sorry. I don't get why they should be necessary.

Tampermonkey as usual checks the page and its frame URLs for matching ` @include` and `@match`es. If the script is a `context-menu` script, then it is added to the context menu (of course for the entire page which is debatable but was good enough for some years) and executed if clicked by the user. So I see no need to specify a context or target.

**Comment by tophf** [comment]
Thanks. My idea was to implement some of the underlying capabilities so that userscripts could surface themselves with more precision e.g. only on links that lead to specified site patterns. Since you haven't seen the need I guess we won't be implementing these options either.
