### ISSUE TITLE
@match or @include not working on specific page for some reason

### ISSUE THREAD

**Issue by archon810** [Tampermonkey/tampermonkey#1323]
## Expected Behavior
I'm trying to create a script that would run on https://secure.tdameritrade.com/login as well as https://auth.tdameritrade.com/auth?blablaetc.

1. Go to https://secure.tdameritrade.com/login. The first time it may redirect to auth.tdameritrade.com/auth.
2. Click Cancel, and you should be back at https://secure.tdameritrade.com/login. This is where I'm trying to get GreaseMonkey to run and click the Login button.
![image](https://user-images.githubusercontent.com/469543/132598572-9bb22255-9dc3-4dda-9912-9fd7c5c46429.png)

## Actual Behavior
`// @match        https://auth.tdameritrade.com/auth*` - this works and fires correctly.
`// @match        https://secure.tdameritrade.com/login*` - this doesn't fire on https://secure.tdameritrade.com/login for some reason, and I don't understand why.
`// @match        https://secure.tdameritrade.com/*` - this does fire on https://secure.tdameritrade.com/login correctly, but is too broad. I'd like it to only fire on /login.

I also tried `@include` without any luck.

## Specifications

- Chrome: Version 93.0.4577.63 (Official Build) (64-bit)
- TM: 4.13
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         Test
// @namespace    tda
// @match        https://secure.tdameritrade.com/login*
// @match        https://auth.tdameritrade.com/auth*
// @version      1
// @grant        none
// ==/UserScript==

alert("on login page!");
```

**Comment by webrockers** [comment]
I've the same problem with sites which worked before.
I can't tell since when or what.

**Comment by 7nik** [comment]
The trick is that when you return from `/auth`, the real page address is `/authCafe`, and then it gets dynamically changed to `/login`.
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://secure.tdameritrade.com/authCafe*
// @icon         https://www.google.com/s2/favicons?domain=tdameritrade.com
// @grant        none
// ==/UserScript==

document.body.style.background = "lightgreen";
```

**Comment by webrockers** [comment]
Well, this is. my case, which worked before.

```
// ==UserScript==
// @name         peter2-hartleb: Scroll to bottom
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  body.scrollTop = body.scrollHeight;
// @author       ms@webrockers.net
// @match        http://*.peter2-hartleb.de/Kombiloesung/*
// @include		 http://*.peter2-hartleb.de/Kombiloesung/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    var body = document.body;
    body.scrollTop = body.scrollHeight;

})();
```

**Comment by 7nik** [comment]
@webrockers it works for me here http://www.peter2-hartleb.de/Kombiloesung/Kombi_2021.html
Though when I just refresh the page it immediately scrolls from the end to the position before refreshing.

**Comment by webrockers** [comment]
@7nik Thanks, for checking.

Must be a Safari Issue then. If I only knew how to debug this.

**Comment by webrockers** [comment]
@7nik 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3598387/132655960-7d44abad-4f69-43d2-a3d5-ea18501aa130.png">

In this and another site, which worked before, I get the following errors in console.
Both belonging to tampermonkey.

**Comment by derjanb** [comment]
> @7nik
> <img alt="image" width="870" src="https://user-images.githubusercontent.com/3598387/132655960-7d44abad-4f69-43d2-a3d5-ea18501aa130.png">
> 
> In this and another site, which worked before, I get the following errors in console.
> Both belonging to tampermonkey.

I've created a new issue for this.

**Comment by archon810** [comment]
> The trick is that when you return from `/auth`, the real page address is `/authCafe`, and then it gets dynamically changed to `/login`.

@7nik Thanks, nice spot. How would you recommend debugging this issue? I enabled debug in TM, and when it paused the debugger, the url shown in the browser bar was already https://secure.tdameritrade.com/login. Same when I tried printing it from the script. How does one see the exact url TM is using?

**Comment by 7nik** [comment]
Open the devtools, go to the Network tab, set Doc type filtering, and navigate to where you need.
The first request without redirection is what you need.
Maybe there are more convenient ways but I don't need it so often.
