### ISSUE TITLE
Safari console errors

### ISSUE THREAD

**Issue by derjanb** [Tampermonkey/tampermonkey#1324]
@7nik 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/3598387/132655960-7d44abad-4f69-43d2-a3d5-ea18501aa130.png">

In [this](http://www.peter2-hartleb.de/Kombiloesung/Kombi_2021.html) and another site, which worked before, I get the following errors in console.
Both belonging to tampermonkey.

_Originally posted by @webrockers in https://github.com/Tampermonkey/tampermonkey/issues/1323#issuecomment-915898017_

**Comment by okalachev** [comment]
Also this error prevents userscripts from working on http sites.

Seems that they only work on https sites.

**Comment by sunxpro** [comment]
Met the same problem:
> TypeError: undefined is not an object (evaluating 'crypto.subtle.generateKey')
> ReferenceError: Can't find variable: chrome
> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.FEATURES.RUNTIME')

Triggering condition:
1. safari 15.1 (17612.2.9.1.20)
2. MacBook Air (M1, 2020)
3. Mac OS 12.0.1 (21A559)

Which cause the problem that tampermonkey can't be loaded successfully, and all script won't be injected.

**Comment by hundredpercentdynamite** [comment]
Have the same errors with Safari 15.1 on http website

**Comment by derjanb** [comment]
You found the root cause of #1425 ;-)

Will be fixed at the next release. `crypto.subtle.generateKey` should not be availiable in "unsecure" contexts by the spec and that's why it was removed from `http` pages.
