### ISSUE TITLE
Use icons with higher resolution in template

### ISSUE THREAD

**Issue by CennoxX** [Tampermonkey/tampermonkey#1325]
## Actual Behavior
Currently the template generates from
```js
// @icon         <$ICON$>
```
something like
```js
// @icon         https://www.google.com/s2/favicons?domain=wikipedia.org
```
This generates icons with a small dimension of 16x16.
![grafik](https://user-images.githubusercontent.com/6975881/132750480-82767ca8-16e6-4bc4-8676-0f117c625a52.png)

## Expected Behavior
Use instead 
```js
// @icon         https://www.google.com/s2/favicons?sz=64&domain=wikipedia.org
```
![grafik](https://user-images.githubusercontent.com/6975881/132750643-1be4d278-b99b-4c14-a859-06d1f2ff5002.png)

**Comment by derjanb** [comment]
Should be fixed at 4.14.6144 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6144.crx))
