### ISSUE TITLE
Neither script status (enabled/disabled) nor execution order are maintained after script restore in latest TM beta

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#1327]
I've just made a script ZIP backup with latest TM beta in Chrome, and when I restored it in a new Chrome profile,
neither the script status (enabled/disabled) nor the execution order (1st, 2nd, etc) were maintained. In other words, after restore: 
- ALL restored scripts are enabled,  
- the script order is irrelevant to the initial one.

The same occurs in Firefox 92.

But, If I restore that ZIP backup in TM 4.13, then both script status and order are maintained.

@derjanb If you'd like, I could send you my ZIP backup via email.

Using latest TM beta 4.14.6143 with Chrome 93/Firefox 92 on Win10.

**Comment by darkred** [comment]
In addition to the above, it's not possible to manually change the execution order of the scripts in their Settings: changing them to any value, it gets back to the previous order after a few secs.

**Comment by derjanb** [comment]
Should be fixed at 4.14.6144 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6144.crx))

**Comment by darkred** [comment]
I confirm all issues are fixed in the new version, thank you.
