### ISSUE TITLE
[Feature Request] Add m4a file extension to Downloads - Whitelisted File Extensions

### ISSUE THREAD

**Issue by Napoli0n** [Tampermonkey/tampermonkey#1328]
## Expected Behavior

Please add the ".m4a" file extension to Whitelisted File Extensions in the Downloads section
In my opinion, m4a is just a normal audio format (mp4 without video) and shouldn't cause any additional security risks.

Currently Whitelisted File Extensions:

/^[^\.]*$/
/\.mp[34]$/
.wav
/\.(avi|mkv|flv|divx|mpe?g|webm)$/
/\.(ico|gif|png|jpe?g)/
/\.(srt|sub|idx)$/
.txt
.iso
.zip
/\.r(ar|[0-9]{2,2})$/

## Specifications

- Firefox: 91.0.2 (64-Bit)
- TM: 4.13.6136
- OS: Windows 10 Pro

**Comment by derjanb** [comment]
Should be fixed at 4.14.6144 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6144.crx))
