### ISSUE TITLE
[FireFox] localhost HTTPS static file server not being called from @require

### ISSUE THREAD

**Issue by robinlarondelle** [Tampermonkey/tampermonkey#1329]
## Expected Behavior
In order to ease development i want to serve the necessary TM `@require` files through a localhost HTTP(S) server. I expected these files to be reloaded on each page reload.

## Actual Behavior
The files are fetched from the localhost server when i update the UserScript in the TM editor, however, they are not fetched when a matched URL is loaded. I'm not sure if this is a caching thing by TM or if i'm doing something wrong here.

## Specifications
- FireFox 91.0.2
- TM: 4.13.6136
- OS: Windows 10
- Matched URL: all LinkedIn pages

## Script
To separate concerns in the JS files, the UserScript header is separated from other logic. The necessary files are imported using @required. This is the content of the UserScript file that is pasted in the TM editor:
```js
// ==UserScript==
// @name            myName
// @description     myDescription
// @author          robinlarondelle
// @version         0.1
// @namespace       myNameSpace
// @homepage        myHomePage
// @include         *linkedin.com/*
// @icon            https://www.google.com/s2/favicons?domain=linkedin.com
// @grant           window.onurlchange
// @require         https://localhost:3000/public/myScript.user.js
// ==/UserScript== 
```

The localhost HTTPS static file server is a Node.JS server with a self signed certificate to enable HTTPS. When using Postman and FireFox after providing my `.pem` file, the server works as expected. If necessary i can provide more details about the server, but i don't think the problem resides here

## Things to point out:
FireFox prohibits accessing local files from TM (see this [comment](https://github.com/Tampermonkey/tampermonkey/issues/347#issuecomment-269039234)). So one alternative to this problem would be to just use Chrome, as it does support accessing local files. However, i want to abstain from using local files because there are multiple developers working on this project. I also don't want to limit development to one specific browser.

The main question/problem is: Why does `@require` from the UserScript header only fetch the required files on Script Save in the TM editor, but not on Page Reload when the URL matches? Is this normal behavior and/or can we turn this off?

**Comment by 7nik** [comment]
You need to change the Update Interval: https://github.com/Tampermonkey/tampermonkey/issues/1310#issuecomment-899704702

Though yeah, maybe for localhost it would be better to set the update interval to always.

**Comment by robinlarondelle** [comment]
@7nik Setting the "Externals" update to "Always" indeed solved the issue for me, thanks for that. I did noticed however that this setting is poorly documented and is the source of problems for more developers (looking through the issue history). Should the setting be documented and/or explained better as well?

**Comment by 7nik** [comment]
I assume it's done because you never know how much time will take to request a resource, and at the same time, TM needs to be able to satisfy `@run-at document-start`. So it just cannot wait for script/resources/requires updates and have to use old values whilst updating.

**Comment by robinlarondelle** [comment]
I have played around with the settings and i can't find any setting that changes this behavior. I guess it's something i have to deal with. I'm closing this issue for now because my initial issue has been solved. Thanks

**Comment by marcorobiati** [comment]
I had the same problem, after googling i ended up here. Would it be possible to make a separate settings to ease development so that we can set to load external resources on each page load just for localhost/specific host, in which case it would fetch it before running the script (blocking page load) so it we don't have to reload twice to get updates?
