### ISSUE TITLE
Add alipay(zhifubao) donate

### ISSUE THREAD

**Issue by chenqiny** [Tampermonkey/tampermonkey#1330]
Hi,

As Chinese user, I would like to donate. But I am not confident to use paypal or stripe. If you provide zhifubao channel, some of us will not be affraid of donate.

https://global.alipay.com/platform/site/ihome

I think you just need to request a qrcode from alibaba, then I can scan your image to donate.

Or maybe you can just put your alipay qrcode image in your website or just put your alipay acount in the site. Then I can scan to donate. 

You don't need to write any new code.

## Expected Behavior

Provide a channel to donate from alipay

## Actual Behavior

stripe and paypal channel only

**Comment by derjanb** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-670414131
