### ISSUE TITLE
Notification/New message icon?

### ISSUE THREAD

**Issue by trueTrueman** [Tampermonkey/tampermonkey#1336]
### Discussed in https://github.com/Tampermonkey/tampermonkey/discussions/1335

<div type='discussions-op-text'>

<sup>Originally posted by **trueTrueman** September 25, 2021</sup>
Hi, I'm probably missing something obvious, but what does the number in a red circle mean that oftenly appears above the Tampermonkey extension icon, similar to those unread messages counters on the icons of messaging apps?
Like this: ![Screenshot_693](https://user-images.githubusercontent.com/53678740/134753093-d32c5724-5345-4875-84e2-680715c56431.png)
</div>

**Comment by derjanb** [comment]
The number shows the number of executed script instances. Please note that higher instance numbers are usually caused by iframes.

Please alos see #163 and/or #446 how to modify or even disabled it.
