### ISSUE TITLE
Execute the problem after the refresh

### ISSUE THREAD

**Issue by longczx** [Tampermonkey/tampermonkey#1337]
In some website (https://www.pinterest.com/), refresh the page can lead to a script does not perform, and executing scripts Tampermonkey quantity will increase.  

![image](https://user-images.githubusercontent.com/53259974/134802238-695b93d6-317d-4b00-ae4a-ae4aafd41c8f.png)

**Comment by derjanb** [comment]
Please contact the script developers. If there is a general problem with Tampermonkey they will contact me.
