### ISSUE TITLE
uBlock Origin is preventing Tampermonkey from injecting scripts

### ISSUE THREAD

**Issue by sapioit** [Tampermonkey/tampermonkey#1338]
(Please fill out the issue template with your details)

## Expected Behavior
Enable uBlock Origin, reload page, userscripts working. (Tested on `readm.org`.)

## Actual Behavior
Enable uBlock Origin, reload page, userscripts **not** working. (Tested on `readm.org`.)

## Specifications

- Chrome: 93.0.4577.82 x64
- TM: 4.9. No idea why it didn't update to the 4.13 from the Chrome Store,
- OS: Win7x64

## Script
Any script
(Please give an example of the script if applicable.)

> ### What is the problem?
> violentmonkey and ublock origin are in conflict in some sites, for example
> http://xxxwebdlxxx.org/img-5b392d724b75f.html (NSFW)
> 
> ### How to reproduce it?
> 1. install [ublock origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) ,update the filters and enable them
>    2.install a userscript inside violentmonkey,for example https://gist.github.com/gera2ld/1c14672b77ade31ad8f0984725de18fc
>    3.add this match to the userscript:
>    `// @match http://xxxwebdlxxx.org/*`
> 2. now head over to the url http://xxxwebdlxxx.org/img-5b392d724b75f.html
>    you'll see that ublock origin has blocked all the scripts on the page including the scripts injected by violentmonkey,so no userscript is running
> 
> ### What is the expected result?
> I'm not sure what to expect, shouldn't the injected script be running regradless of the ad blocking ? or is this an expected behavior ?how can I solve or workaround this ? should this be reported to the ublock origin guys instead ?
> 
> ### What is the actual result?
> userscripts not running
> 
> ### Environment
> * Browser: firefox
> * Browser version:62.0.3
> * Violentmonkey version:2.9.7
> * OS:manjaro linux

**Comment by 7nik** [comment]
Scripts work for me on both sites. The example script also works after removing `const globalThis = this;` line.
Chromium: 94.0.4606.61
TM: 4.13
OS: Manjaor KDE

Could you update TM to 4.13 and re-check?

**Comment by sapioit** [comment]
**_Alright, after the update, it works._** I exported the settings, uninstalled it, then reinstalled it from the chrome store. No idea why it didn't automatically update the extension.

Thank you! Really strange that Chrome didn't update the extension.

**Comment by derjanb** [comment]
@7nik Thanks for the answer.
