### ISSUE TITLE
How to detect that a file has been `@require` in other scripts?

### ISSUE THREAD

**Issue by liangjiancang** [Tampermonkey/tampermonkey#1339]
Suppose I want to write a library file for userscripts. Some of the code cannot be executed twice, so if two userscripts `@require` this file, there will be a problem. How do I detect in the library that it has been `@require` before?

Theoretically it makes the most sense to flag on `window`, but it doesn't work for userscripts. Flagging on `unsafeWindow`? Obviously very bad. What is the best practice?

**Comment by 7nik** [comment]
Every userscript is executed in the sandbox and thus it has its own `window` object.
So, unless your lib does something to `unsafeWindow`, it's safe to use the same lib in multiple userscripts.

**Comment by liangjiancang** [comment]
I have a question, the documentation mentions `@grant unsafeWindow`, the script that declares it will display "This item has full access to webpage" message in Tampermonkey.

However, I found that even without declaring it, `unsafeWindow` works fine (on Violentmonkey as well). I'm wondering if this is a bug, a compromise for compatibility, or a subtle design?

If this is a designed feature, does it mean that the designer believes that all scripts should have the ability to access the real `window`, even if they don't declare it.

**Comment by 7nik** [comment]
If your lib does something with `unsafeWindow` or does DOM manipulation that must be performed only once, or you need to synchronize lib instances for whatever reason, well, you need to define a property on `unsafeWindow` or on the target HTML element or add an attribute to it. Also, you can use symbols for properties:
```js
const key = Symbol.for("name of my symbol for my X lib");
unsafeWindow[key] = data;
// or
targetElement[key] = data;
```

A really clandestine way can be using events to find and communicate between instances but in this case, initialization became asynchronous.

---
>  the documentation mentions `@grant` unsafeWindow, the script that declares it will display "This item has full access to webpage" message in Tampermonkey.
>  However, I found that even without declaring it, unsafeWindow works fine (on Violentmonkey as well).

Likely it was so in the past. Now a sandboxed `window` always is inside the real `window`'s scope so you can read global variables unless you overrode it with your local one. `unsafeWindow` just "gives" you write access but even without it there are workarounds and maybe it's why it was changed. Changing this behavior back will break the script that uses `unsafeWindow` without declaring it.

**Comment by derjanb** [comment]
> However, I found that even without declaring it, unsafeWindow works fine[...]. I'm wondering if this is a bug, a compromise for compatibility, or a subtle design? 

You are right, this message is inconsistent. Will be removed.

**Comment by liangjiancang** [comment]
My confusion about `unsafeWindow` for a long time is cleared up. Since `unsafeWindow` is always accessible, I don't have any concerns about @7nik's solution.
