### ISSUE TITLE
window.fetch inside userscript is different from one within the page

### ISSUE THREAD

**Issue by xxzefgh** [Tampermonkey/tampermonkey#1343]
I am trying to intercept global `XMLHttpRequest` and `fetch` API-s, but setting `window.fetch` doesn't work.

## Intercepting XMLHttpRequest
```js
// ==UserScript==
// ...

const _originalXhrOpen = window.XMLHttpRequest.prototype.open;

window.XMLHttpRequest.prototype.open = function (
  method,
  url,
  async,
  user,
  password
) {
  console.log(method, url);
  return _originalXhrOpen.apply(this, arguments);
};
```
this works fine and it successfully logs requests made from page context.

## Intercepting Fetch API
```js
// ==UserScript==
// ...

window.fetch = function (url, options = {}) {
  const method = options.method || "GET";
  console.log(method, url);

  return _originalFetch.apply(this, arguments);
};
```
however, this doesn't work. Do I need special permissions or browsers don't allow it?

## Specifications

- Chrome: (i.e. 94.0.4606.61)
- OS: (Windows 10 19043.1110)

**Comment by double-beep** [comment]
If the sandbox mode is enabled, the `window` object won't be available. You can use `unsafeWindow` instead.

**Comment by xxzefgh** [comment]
That did the trick, thank you
