### ISSUE TITLE
GM_xmlhttpRequest overwrite cookie in headers parameter

### ISSUE THREAD

**Issue by alpgul** [Tampermonkey/tampermonkey#1346]
#### Request Header:
`cookie: data=1`

## Actual Behavior
When I define a cookie, cookies are sending along with the cookies belonging to the URL. How do I overwrite cookies?
[Similar issue in Greasemonkey](https://github.com/greasemonkey/greasemonkey/issues/2235)
#### Request Header:
`cookie: data=2;data=1`

## Specifications

- Chrome v94.0.4606.81
- TM: 4.13
- OS: windows 10

## Script

```js
// ==UserScript==
// @name         Tempail.com
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include        https://*
// @grant        GM_xmlhttpRequest
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
    'use strict';

    let options={};
    options.method="POST";
    options.url="url";
    //options.cookie="data=1"
    options.headers={
                    "cookie":"data=1"
                    "content-type":"application/x-www-form-urlencoded",
                    };
    options.anonymous=true;
    options.data="data=1";

 GM_xmlhttpRequest(options);
})();
```

**Comment by alpgul** [comment]
The problem still continues. I joined this site, defined a cookie(`document.cookie="data=2"`), then ran your code. The cookie appended with the site's cookie. The cookie in the code added the cookie belonging to the site and the request operation worked.
![tampermonkey](https://user-images.githubusercontent.com/5773704/136545232-7c4b178a-3ea1-489c-92e7-b2e2e2222386.jpg)

**Comment by derjanb** [comment]
> You may also specify `options.anonymous = true;`.

Have you tried to set the `anonymous` flag?

**Comment by derjanb** [comment]
Nevermind. I found the bug...
