### ISSUE TITLE
[Feature Request] Sync with data

### ISSUE THREAD

**Issue by Cyberavater** [Tampermonkey/tampermonkey#1350]
Currently, I can upload the userscripts to the cloud and import it, that good and all but it would be nice to have a Sync feature, i.e automatically update the changes to the cloud so the next time I'm on my different device It fetches the changes from the cloud to my new device.

Very useful for having the same configuration across all devices.
Also very useful for scripts like [Google Hit Hider](https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites) and scripts that have very editable settings [Mouseover Popup](https://greasyfork.org/en/scripts/394820-mouseover-popup-image-viewer)

Edit: I just found out that Sync is under advanced settings, but what is missing is sync with data (the one you get with regular export-import)

**Comment by Shi-553** [comment]
#825
Is it a duplicate?
