### ISSUE TITLE
[Feature Request] add domain blacklist

### ISSUE THREAD

**Issue by LittleJake** [Tampermonkey/tampermonkey#1359]
Hi, I use lots of scripts and feel tired to add many scripts which are out of scope to site exception.

All scripts should not run on any bank site, many payment sites, and some private sites.

I think a domain blacklist to block all the scripts running is needed.

Thank you.

**Comment by 7nik** [comment]
In settings, set Config mode to Beginner or Advanced, then go to the Security section.
