### ISSUE TITLE
Script not working with Tampermonkey but Does with MeddleMonkey

### ISSUE THREAD

**Issue by CodexJeff** [Tampermonkey/tampermonkey#1361]
(Please fill out the issue template with your details)

## Expected Behavior
Supposed to be able to track episode change on crunchyroll beta. Using meddlemonkey, it worked however

## Actual Behavior
Throws errors in console and does not track (image below)

## Specifications

- Safari 15.1
- TM: 4.13.6140
- OS: MacOS 11.6

## Script

https://github.com/MALSync/MALSync
(Please give an example of the script if applicable.)

![image](https://user-images.githubusercontent.com/42257491/139150097-fdaa93c6-047c-4977-95a4-3d6267f4ddbe.png)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact [the script developers](https://github.com/MALSync/MALSync/issues). If something is wrong with Tampermonkey, then they'll come back to me.
