### ISSUE TITLE
Tampermonkey donation tracking and forum

### ISSUE THREAD

**Issue by qzjake** [Tampermonkey/tampermonkey#1362]
## Expected Behavior

There should be a place to log in and see our donation history, maybe even a forum owned by Jan Biniok for us financial contributors to communicate with other people and discuss our thoughts and ideas with other contributors.

I think this forum should have a profile that may share how much has been donated, but at the very least lets Jan know how much has been contributed and by who.

This would also allow Jan to communicate directly with those of us ready, willing, and able to financially support this and other efforts.

## Actual Behavior

Donations are done privately and feel forgotten.  This discourages me from donating.

## Specifications

All

## Script

We love you Tampermonkey!  Thank you Jan!

**Comment by jb222** [comment]
"Donations are done privately and feel forgotten." 
Isn't this the nature of a donation? It's no subscription where you agree to pay regularly for some guaranteed service. What you're asking for looks like an investment with influence on TM's development, and makes Jan Biniok a shareholders' puppet... 

Well, did I donate this year? I forgot! 
;-)

**Comment by derjanb** [comment]
Feel free to discuss your thoughts and ideas here: https://github.com/Tampermonkey/tampermonkey/discussions
