### ISSUE TITLE
GM_download doesn't work stable on Chrome

### ISSUE THREAD

**Issue by wololowins** [Tampermonkey/tampermonkey#1363]
I have a script for downloading videos using tiktok api and it doesn't work most of the times on chromium browsers with different videos, throwing status 0 error. I tested the script on Firefox and it works perfectly fine though. To reproduce the issue, you need to download a video about 5 times until it breaks.

## Expected Behavior
File downloaded

## Actual Behavior
Download is not going, throwing onerror exception:
{
  finalUrl: "https://api.tiktokv.com/aweme/v1/play/?video_id=v10025g50000c5ubbb3c77u3gsu874ng&improve_bitrate=1&ratio=default"
  readyState: 4
  responseHeaders: ""
  responseText: ""
  status: 0
  statusText: ""
}

## Specifications

- Chrome: 95.0.4638.69
- TM: 4.13.6136
- OS: Windows 10 21H1

## Script

```js
// ==UserScript==
// @name         Tiktok-Downloader BUG
// @version      1.0
// @description  tiktok.com Video Downloader
// @match        https://www.tiktok.com/*
// @match        https://tiktok.com/*
// @grant        GM_download
// ==/UserScript==

(function() {
    GM_download({
        url: 'https://api.tiktokv.com/aweme/v1/play/?video_id=v10025g50000c5ubbb3c77u3gsu874ng&improve_bitrate=1&ratio=default',
        name: '1.mp4',
        headers:    {
            "User-Agent": "okhttp"
        },
        onerror: (e) => {console.log(e);}
    });
})();
```

**Comment by derjanb** [comment]
It's working fine here as long as the server sends the video. Looks like they limit the number of downloads within a time period or so. I don't see how Tampermonkey could be responsible for the server not sending data.
