### ISSUE TITLE
Tampermonkey BETA最新版导致打不开，所有数据丢失

### ISSUE THREAD

**Issue by oplle** [Tampermonkey/tampermonkey#1367]
Tampermonkey BETA 今天提示更新到最新版重启浏览器之后，我的所有脚本都无效了，设置页面也打不开，以前配置的脚本都看不到了，这样我也无法导出脚本备份，我的浏览器是chrome77，应该怎么回退版本？？还有怎么备份阿，我的脚本那么多，配置了那么多细节全丢失了。。。。

**Comment by derjanb** [comment]
Do you have a backup of the Chrome profile folder? If you can try to recover the scripts using this Python script: https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0

https://github.com/Tampermonkey/tampermonkey/issues/247#issuecomment-155727107

**Comment by oplle** [comment]
> Do you have a backup of the Chrome profile folder? If you can try to recover the scripts using this Python script: https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0
> 
> [#247 (comment)](https://github.com/Tampermonkey/tampermonkey/issues/247#issuecomment-155727107)

Will the mistake of Tampermonkey will be solved? My chrome77
