### ISSUE TITLE
[Feature request] OneDrive sync authentication in the background

### ISSUE THREAD

**Issue by Rheinmetallskorpion** [Tampermonkey/tampermonkey#1380]
Every time a browser with TM starts, it opens and focuses on a new tab for OneDrive authentication after 3-5 seconds. This is pretty annoying since it interrupts typing. 

Is there any way to make this authentication background or in a new tab or pop-up that's not focused by default?

Thanks for the hard work!

## Specifications

- Every browser on every system
- TM: (i.e. 4.13.6140)

**Comment by 2052645064** [comment]
这是来自QQ邮箱的自动回复邮件。
你好，非常抱歉我没能及时查看到你的消息，若2小时内我未回复请致电17629150335及时联系，谢谢！

**Comment by derjanb** [comment]
Should be fixed at 4.14.6149 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6149.crx))

If no user activity is needed, then the tab should open and close in background.

**Comment by Rheinmetallskorpion** [comment]
Thank you so much! Since I use Safari, I'll wait for the public release to give it a try.

**Comment by Rheinmetallskorpion** [comment]
> Should be fixed at 4.14.6149 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6149.crx))
> 
> If no user activity is needed, then the tab should open and close in background

Should I wait until the version number shows 4.14.6149 on stable release to see the feature? 
Upon checking the [changelogs](https://www.tampermonkey.net/changelog.php?ext=dhdg&show=dhdg) I can see chrome versions don't typically include the last part.

I have already updated to 4.14 of the stable release on macOS chrome. This feature seems not to be implemented yet.
