### ISSUE TITLE
block ads or block domains (proxy)

### ISSUE THREAD

**Issue by AhrimanSefid** [Tampermonkey/tampermonkey#1383]
hi all
me very try block ads or blocks domain but open proxy show ads.
can help me for blocks.
add hosts open vpn or proxy load ads.
thank you.

**Comment by 7nik** [comment]
I doubt that TM is related to or can solve your problem.
Try adblocker, e.g. [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), and ask there how to solve your problem if it will still be presented.

**Comment by AhrimanSefid** [comment]
try not work.
