### ISSUE TITLE
Tampermonkey not injecting from firefox until restarted 

### ISSUE THREAD

**Issue by DanaMW** [Tampermonkey/tampermonkey#1384]
Since a couple versions ago the beta version of TM on Firefox developers has required me to reload (click the restart button in TM settings) to get scripts to inject. Would anyone have some place to look for why this might have started happening? I changed nothing and they always worked fine till then. Obviously it might be a FF issue, i have been unable to suss out the issue causing it. The most noticeable site is Discord. Any ideas? Thanks.

**Comment by derjanb** [comment]
Can not reproduce using TM 4.14.6149 and FF Developer 96.0b3. 

Do you see a difference in the background console log when this happens?

**Comment by DanaMW** [comment]
On discord URL:
Not Working on browser start with pinned Discord.
![NotWorking](https://user-images.githubusercontent.com/12940577/145735260-5f8cdc90-9add-4d82-a0c9-e0f3e8de30c2.png)
Working After TM restart then refresh
![WorkingAfterRestartofTM](https://user-images.githubusercontent.com/12940577/145735275-7faec822-569b-47e0-ae50-1598e6bcf896.png)

Thank you for checking.

**Comment by DanaMW** [comment]
I have some stupid little Discord web scripts for my sons that is what is trying to load. Worked great like i said until 2 TM and 3 FF versions ago. About the time you did the latest sandbox work. NOT that it is your TM but about then the break for me happened.

**Comment by DanaMW** [comment]
It also works after you disable and enable TM i just found.  Seems to me like FF is not letting it act normal until firefox is completely loaded. The faster machine has a higher percentage of working right, as it sometimes does,

**Comment by DanaMW** [comment]
I changed the graphic above to what I hope shows the error? Sorry for my previous mistake.

**Comment by Crul** [comment]
This is happening to me on Firefox 96.0.1, only on Pinterest (any of their domains). I'm getting these errors:

    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

I was going crazy because sometimes it worked but I couldn't find why. I thought it was related to Experimental options "Inject mode" and/or "Add Tampermonkey to the HTML's CSP". But after finding this report, I tried the default values and restarted Tampermonkey and it works.

**Comment by DanaMW** [comment]
Everything is set to default for me on discord and it still does it 90+% of the time. I figure patients will allow it to be discovered at some point. I keep looking every day. I just toggle TM OFF/ON and reload. i am used to it now.

**Comment by Crul** [comment]
FYI: I got the update to version 4.15.6154 (Firefox 98.0 - Windows 10) and the issue still happens on all pinterest domains. Restarting Tampermonkey fixes it, but it needs to be restarted manually every time the browser is closed & open.

**Comment by DanaMW** [comment]
I am still having to restart Tampermonkey Beta on Firefox load to get it to work right on DIscord. (that I know of, could be more) I use the right-click, manage extension, stop, start, method.

**Comment by Fubuchi** [comment]
I had the same issue, I have some script for github with CSP bypass enable but it only work if I restart tampermonkey.

I am using FF 99.0b2 (64-bit)

**Comment by Crul** [comment]
FYI: I got the update to version 4.16.6160 (Firefox 99.0 - Windows 10) and the issue still happens on all pinterest domains. Restarting Tampermonkey fixes it, but it needs to be restarted manually every time the browser is closed & open.

**Comment by Crul** [comment]
FYI: I got the update to version 4.17.6161 (Firefox 100.0 - Windows 10) and the issue still happens on all pinterest domains. Same behavior as before.

**Comment by derjanb** [comment]
Please try the fix explained here: https://github.com/Tampermonkey/tampermonkey/issues/1186#issuecomment-1151485354

**Comment by Crul** [comment]
@derjanb I confirm the new version with `// @sandbox JavaScript` works for me (Windows 10 - Firefox 101.0).

Thanks!

**Comment by DanaMW** [comment]
Further testing has shown that beta 4.18.6163 with Sandbox mode: javascript+Dom fixes the problem. CLosing.

**Comment by derjanb** [comment]
Sounds great. JavaScript sandbox mode will become the default at FF after some testing. So please report back if you encounter issues.
