### ISSUE TITLE
Unable to control all request types via webRequest

### ISSUE THREAD

**Issue by QwertyChouskie-Asurion** [Tampermonkey/tampermonkey#1386]
(Please fill out the issue template with your details)

## Expected Behavior
I can redirect a request for a dynamically loaded image on a webapp

## Actual Behavior
I cannot redirect a request for a dynamically loaded image on a webapp

## Specifications

- Browser: Firefox Nightly 97.0a1
- TM: 4.13.6136
- OS: Ubuntu

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Portal Improved
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @icon         https://www.google.com/s2/favicons?domain=portal.ubif.net
// @match        https://portal.ubif.net/*
// @include      https://d1zmiyu61cpipt.cloudfront.net/*
// @grant        GM_webRequest
// @webRequest   {"selector":"https://portal.ubif.net/assets/img/ubiflogo-black-trademark.png","action":{"redirect":"https://d1zmiyu61cpipt.cloudfront.net/assets/images/ubif_asurion_logo_dark.svg"}}
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();

```

(And yes, I did try to find a way to listen for the img creation via `MutationObserver` and change the `src`, and after a couple hours I couldn't get it to work.)

**Comment by 7nik** [comment]
> I did try to find a way to listen for the img creation via MutationObserver and change the src, and after a couple hours I couldn't get it to work.

With `MutationObserver` it's easy to miss an element when it's a part of the added subtree.
It's more convenient to use [MutationSummary](https://github.com/rafaelw/mutation-summary). [Example](https://github.com/7nik/userscripts/blob/9b929e9edc30c0bf3ce2c974214420424b45747f/NM%20trade%20enhancement.user.js#L692-L705).

**Comment by derjanb** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-300132157
