### ISSUE TITLE
Calling a site's global functions from userscript fails in Beta `4.14.6150`

### ISSUE THREAD

**Issue by NatoBoram** [Tampermonkey/tampermonkey#1392]
## Expected Behavior

Executing a website's global function should work properly in Tampermonkey

![image](https://user-images.githubusercontent.com/10495562/146709149-3686a641-2747-4842-868f-6e4bc76bb0ba.png)

## Actual Behavior

It throws an error, but only in Tampermonkey Beta

![image](https://user-images.githubusercontent.com/10495562/146709097-b6591c31-ce26-4440-ab63-e7035f2e67cb.png)

I can work around it by adding `setTimeout(() => $.flavrNotif("Hello world!"), 0)` around each and every call to this global function when I don't want the result or `await new Promise(resolve => setTimeout(() => resolve($.flavrNotif("Hello world!")), 0))` when I do want the result, but I'd very much rather not :(

## Specifications

- Firefox: 95.0 (64-bit)
- TM: 4.14.6150
- OS: Pop!_OS 21.10 x86_64

## Script

This works properly in Tampermonkey `4.13.6136` but not in the Beta version, `4.14.6150`.

```js
// ==UserScript==
// @name            $.flavrNotif("Test")
// @version         1392
// @namespace       https://github.com/Tampermonkey/tampermonkey/issues/1392
//
// @match https://www.eldarya.com/*
// @match https://www.eldarya.fr/*
//
// @grant none
// ==/UserScript==

$.flavrNotif("Hello world!")
```

**Comment by derjanb** [comment]
Should be fixed at 4.14.6151. Thanks for reporting this.

**Comment by InoxydableWrite** [comment]
Thank you!!!

**Comment by NatoBoram** [comment]
Confirmed. Thank you!
