### ISSUE TITLE
TM not changing the theme at runtime

### ISSUE THREAD

**Issue by xmha97** [Tampermonkey/tampermonkey#1395]
Tampermonkey not changing the theme at runtime

## Expected Behavior

I want to change the Tampermonkey theme at runtime.

## Actual Behavior

Tampermonkey not changing the theme at runtime.
I have to restart the browser (Firefox).

## Specifications

- Chromium: Firefox 95.0.1
- TM: 4.13.6136
- OS: Windows 10 21H2

**Comment by derjanb** [comment]
Duplicate of #1237
