### ISSUE TITLE
Plain `fetchInit` for `responseType: "stream"`/`fetch: true`

### ISSUE THREAD

**Issue by AlttiRi** [Tampermonkey/tampermonkey#1398]
I have already wrote here about it: https://github.com/Tampermonkey/tampermonkey/issues/1278#issuecomment-899176903

Allow `fetch`'s property of `GM_xmlhttpRequest` to be 
```js
{
  referrer: "", // optionally, since the extension allow to set headers in more advanced way
  referrerPolicy: "no-referrer-when-downgrade",
  mode: "cors",
  credentials: "include",
  cache: "force-cache",
  redirect: "follow",
  integrity: "sha256-BpfBw7ivV8q2jLiT13fxDYAe2tJllusRSZ273h2nFSE=",
  keepalive: true,
}
```
object. All these properties are `string` (and `boolean` the last one).

It will be compatible with the existed code because any object is `true`. And **it's very simple to implement.** 
Just use this object as a base of `Object.assign` in the background script when you pass your fetch init object.

```js
fetch(url, props);
```
->
```js
if (typeof fetchInit === "object" && fetchInit !== null) {
  props = Object.assign(fetchInit, props); // fetchInit is passed by a user 
}
fetch(url, props);
```

This `fetchInit` should have the less priority in comparison with other props like `nocache`.

---

I want to use it with `responseType: "stream"` to pass some `fetchInit` settings to implement the most similar function to the native `fetch` function.

**Comment by derjanb** [comment]
And I have already answered this request [here](https://github.com/Tampermonkey/tampermonkey/issues/1278#issuecomment-899315740). Sorry.
