### ISSUE TITLE
Allow userscript installation via drag and drop even if local file access is disabled

### ISSUE THREAD

**Issue by pstein** [Tampermonkey/tampermonkey#1399]
I installed newest Tampermonkey AddOn in newest Chrome browser.

As far as I know Greasemonkey scripts from Firefox run under Tampermonkey on Chrome as well.

So I want to install such a *.user.js script in Tampermonkey.
Therefore I opened TM Dashboard and drag & dropped the corresponding *.user.js from File Explorer onto Dashboard.

But the script seems to be NOT added.
Instead the script source code is simply shown in Chrome browser tab window.

When I open Extension page chrome://extensions/
and drag & drop the script file it seems to be added successfully BUT it does NOT show up in TM Dashboard as installed Userscript.

So how else can I install a *.user.js script by drag &drop?

**Comment by derjanb** [comment]
For the moment please enable local file access first: https://github.com/Tampermonkey/tampermonkey/issues/977#issuecomment-657268478

**Comment by derjanb** [comment]
Should be fixed at 4.15.6153 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_15_6153.crx))
