### ISSUE TITLE
Can you add sorting of scripts by number after restarting the browser by default or an option?

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [Tampermonkey/tampermonkey#1400]
(Please fill out the issue template with your details)

## Expected Behavior

Sort scripts by number after browser restart.

## Actual Behavior

Scripts not sorted by number after browser restart.

## Specifications

- Chromium: (97.0.4692.71)

## Screenshots

![2022-01-12_02-20-19](https://user-images.githubusercontent.com/31162059/149007773-142706d5-3de8-4071-b7eb-6ba98211c7a4.png)

**Comment by derjanb** [comment]
Currently Tampermonkey remembers your last choice. What's wrong with this?

**Comment by SnIPeRSnIPeR** [comment]
> Currently Tampermonkey remembers your last choice. What's wrong with this?

After restarting Chrome I see this:
![2022-01-17_02-41-39](https://user-images.githubusercontent.com/31162059/150024637-76053326-6f5f-457d-aea7-a2c29b2e2cbb.png)

**Comment by SnIPeRSnIPeR** [comment]
Feedback added!

**Comment by derjanb** [comment]
Can not reproduce. The last sorting option always is stored and applied after Chrome restart again.

**Comment by SnIPeRSnIPeR** [comment]
This issue is not completed for me anyway. How can I help you with fix? Can I provide you logs or smh?
