### ISSUE TITLE
Broken login on PayPal due to attempt to inject code on paypalobjects.com

### ISSUE THREAD

**Issue by lainverse** [Tampermonkey/tampermonkey#1401]
## Expected Behavior
PayPal login works fine.

## Actual Behavior
Page with checkbox "I'm not a robot" which appears in some cases after login and password reloads indefinitely.

## Specifications

- Problem encountered in Firefox, I personally wasn't able to make that page to appear, so can't tell is Chrome affected
- TM: any latest (including Beta)
- OS: irrelevant

## Script

As I know not all scripts trigger this issue (most of them do, though, according to report I got), but mine definitely do.
https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

According to report I got this is due to TM attempting to inject code on paypalobjects.com frame on PayPal.
Considering PayPal itself already is in a Blacklist might be a good idea to add this domain there as well.

**Comment by dimisa-RUAdList** [comment]
Apparently, the problem occurs when using any script that works on all sites `// @include       *://*`, for example: [Absolute Enable Right Click & Copy](https://greasyfork.org/ru/scripts/23772-absolute-enable-right-click-copy). Adding paypalobjects.com to the Blacklist solves the problem in all cases.

**Comment by derjanb** [comment]
Hmm, I haven't been able to reproduce the issue by myself, but I fixed a problem that could potentially cause this issue.

Could you please check whether 4.16.6156 improves your issue? -> https://github.com/Tampermonkey/tampermonkey/issues/1442#issuecomment-1066798220

Thanks.
