### ISSUE TITLE
Tampermonkey has no access to this page

### ISSUE THREAD

**Issue by 12nickemen** [Tampermonkey/tampermonkey#1402]
Hello everyone,

I add tampermonkey to my chrome page. I load a script into tampermonkey and I enabled. But in the right screen there stay ‘Tampermonkey has no access to this page’ so I went to settings to allow access to file URL’s, but that was already active.

So who can help me?
![B44D81EB-1F8A-4D21-A7C8-59CE608E6705](https://user-images.githubusercontent.com/97918583/149841094-a77d95bf-8f49-450c-be3f-d013b9666323.jpeg)
![Uploading 1E07B0BE-BD47-4111-9A70-2276D1E883E5.jpeg…]()

![image](https://user-images.githubusercontent.com/97918583/149841022-e7958c8a-05a1-4ee2-9272-1601c71ecb40.jpg)
![image](https://user-images.githubusercontent.com/97918583/149841022-e7958c8a-05a1-4ee2-9272-1601c71ecb40.jpg)

**Comment by User-adult** [comment]
I also have the same problem

**Comment by 7nik** [comment]
For security reasons, Tampermonkey cannot apply userscripts to pages that are system's (various browser settings pages) or belongs to some extension (like on the screenshots above) or chrome web store.

Just go and find userscripts you want and install them.

**Comment by 12nickemen** [comment]
Remove ?/? after ?Lauch/? in your script On Mon, 21 Mar 2022 at 14:13, User-adult ***@***.***> wrote:
I also have the same problem

?Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
