### ISSUE TITLE
Add hotkey for Auto-Indent All

### ISSUE THREAD

**Issue by skygate2012** [Tampermonkey/tampermonkey#1404]
## Expected Behavior
Press a hotkey to trigger Auto-Indent All (for example <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> in VSCode)

## Actual Behavior
Currently no hotkey is assigned to the Auto-Indent All option, the user will have to open the Developer menu and select it with mouse.
Alternatively the user can use <kbd>Ctrl</kbd>+<kbd>A</kbd> and then <kbd>Tab</kbd> to indent the code. But the code needs to be selected and the selection would divert the current caret position.

**Comment by derjanb** [comment]
Should be fixed at 4.18.6165 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
