### ISSUE TITLE
Option to easily toggle no-multi-spaces linting

### ISSUE THREAD

**Issue by JohannesMP** [Tampermonkey/tampermonkey#1406]
## Overview

The default ESLint config used in Tampermonkey has `no-multi-spaces` enabled.

It's a fairly common practice to use additional spaces to align code for readability, which leads to fairly common warnings:
![image](https://user-images.githubusercontent.com/662874/150707262-7c8a2a44-3b3b-4905-b5f4-285841fd769a.png)

Heck, even the metadata blocks in Tampermonkey's default templates use spaces to align its values for readability:
![image](https://user-images.githubusercontent.com/662874/150707843-61ee1d8a-407b-4569-8dc9-a375bb887c5b.png)

## Suggestion

It would be useful if there was a simple exposed toggle for this specific linting option in Tampermonkey's Editor settings, without the user having to provide a whole custom linter config.

I understand that adding a toggle for every linting option would be unreasonable, but given how prevalent this kind of formatting is I think the case could be made that it would be worthwhile to include this as a dedicated exposed option in the Editor options so that it could be easily modified without the user having to use a complete custom linter config.

**Comment by derjanb** [comment]
Is adding an inline configuration for ESLint to allow this an acceptable solution?

```JS
/* eslint-disable no-multi-spaces */
const o =           1;
const b =           2;
const t = 1;
```
