### ISSUE TITLE
Deleted userscripts automatically download again

### ISSUE THREAD

**Issue by purevertigo** [Tampermonkey/tampermonkey#1410]
(Please fill out the issue template with your details)

## Expected Behavior
Deleted userscripts should stay deleted.

## Actual Behavior
Deleted userscripts automatically download again

## Specifications

- Chrome 98
- TM: 4.13
- OS: Mac Montery / Windows 11

## Script
All scripts

```

**Comment by derjanb** [comment]
Should be fixed at 4.14
