### ISSUE TITLE
userscripts search URL is wrong

### ISSUE THREAD

**Issue by MerrickZ** [Tampermonkey/tampermonkey#1411]
when browsering twitter.com ( for example ), it shows ```Found 259 available scripts``` in the context menu of the menu icon, but when clicked, it goes to 

https://www.userscript.zonehttps//www.userscript.zone/search?q=https%3A%2F%2Ftwitter.com%2Fhome&utm_campaign=iikm&utm_medium=api&utm_source=usz 

instead of 

https//www.userscript.zone/search?q=https%3A%2F%2Ftwitter.com%2Fhome&utm_campaign=iikm&utm_medium=api&utm_source=usz

## Expected Behavior

https//www.userscript.zone/search?q=https%3A%2F%2Ftwitter.com%2Fhome&utm_campaign=iikm&utm_medium=api&utm_source=usz

## Actual Behavior

https://www.userscript.zonehttps//www.userscript.zone/search?q=https%3A%2F%2Ftwitter.com%2Fhome&utm_campaign=iikm&utm_medium=api&utm_source=usz

**Duplicate https://www.userscript.zone**

## Specifications
- Tampermonkey 4.13.6138
- Edge  99.0.1150.2 x64
- OS: Windows 11

Thanks!

**Comment by derjanb** [comment]
Fixed. Thank you very much for reporting.
