### ISSUE TITLE
Tampermonkey beta and Tampermonkey issues

### ISSUE THREAD

**Issue by KL-07** [Tampermonkey/tampermonkey#1419]
(Please fill out the issue template with your details)

## Two aforementioned functions in tampermonkey and its beta version do not appear
<img width="1440" alt="Screen Shot 2022-02-17 at 8 26 38 AM" src="https://user-images.githubusercontent.com/99524563/154380433-27c5d3f2-383f-4518-a5c3-57bd8b2f84dc.png">
<img width="1440" alt="Screen Shot 2022-02-17 at 8 23 23 AM" src="https://user-images.githubusercontent.com/99524563/154380438-0b99bb67-8fd9-450a-b255-28b0da73e95b.png">
<img width="1440" alt="Screen Shot 2022-02-17 at 8 25 28 AM" src="https://user-images.githubusercontent.com/99524563/154380444-c1e8a4a3-07b7-42b1-afaf-2d2acb85dd65.png">
<img width="1440" alt="Screen Shot 2022-02-17 at 8 26 01 AM" src="https://user-images.githubusercontent.com/99524563/154380447-7061b391-6c8c-43c9-b87f-1f6f50f91e1f.png">

## Specifications

- Google Chrome: Version 98.0.4758.80
- OS: MacOS Monterey 12.2.1

## Script not available

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
You can now use "Choose file" from "Import from file". It will auto-detect the file type.

**Comment by KL-07** [comment]
> You can now use "Choose file" from "Import from file". It will auto-detect the file type.

It says "Invalid json" for select zip files...
