### ISSUE TITLE
Tampermonkey's icon disappears on Safari, macOS 12.3 beta3

### ISSUE THREAD

**Issue by micturkey** [Tampermonkey/tampermonkey#1420]
(Please fill out the issue template with your details)

## Expected Behavior
Icon to be shown

## Actual Behavior
Icon disappeared like https://www.reddit.com/r/MacOSBeta/comments/sf4uvq/safari_extension_icon_lost/

## Specifications

- Safari: 15.4 (17613.1.16.1.6)
- TM: 4.13.6140
- OS: macOS 12.3 beta3

## Script
It happens without or with scripts enabled
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by chensiyue98** [comment]
Same issue here

**Comment by ShadowLyin** [comment]
I have the same problem.

**Comment by chensiyue98** [comment]
The problem still exists on macOS 12.3 (Non-beta version)

**Comment by jetblackrx89** [comment]
Same here. The toolbar icon starts off abnormally small when the extension is first enabled and then quickly disappears. The problem exists in Safari build 17613.1.17.1.6 and Technology Preview build 17614.1.3.8.

**Comment by modyuan** [comment]
same problem.

**Comment by HaoshuaiXu** [comment]
Same here.

**Comment by kusazh** [comment]
same issue

**Comment by macbookproiceland** [comment]
same here.
macOS Version 12.3 (21E230)

**Comment by jetblackrx89** [comment]
Issue continues with the latest Safari Technology Preview Release 142.

**Comment by joaolisboa** [comment]
Happening here on latest stable version. macOS 12.3 and Safari 15.4.

**Comment by timkite** [comment]
Also still happening after updating to macOS 12.3.1 (Safari still at 15.4).
<img width="274" alt="Screen Shot 2022-04-01 at 09 55 05" src="https://user-images.githubusercontent.com/6933976/161277832-726f5342-d47e-4658-9284-e476829ff565.png">

**Comment by CharlieYu4994** [comment]
It's still here

**Comment by jylsec** [comment]
Same here.
<img width="197" alt="image" src="https://user-images.githubusercontent.com/43801137/163300882-abba8ece-8055-4b89-818f-0be13510ede2.png">

**Comment by jprokos** [comment]
Same issue. The Tampermonkey extension hasn't been updated since June of 2021. I am sure it's related to some change in Safari since it's been almost a year now, but really isn't a priority as it doesn't affect functionality.

Safari Version 15.4 (15613.1.17.1.13, 15613)
macOS Catalina Version 10.15.7 (19H1824)

**Comment by troyliu0105** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5518286/163905372-cf61a1d1-1d37-4d7a-8803-e4a1fa4b40af.png">
still exists in 12.3.1

**Comment by Eric-Guo** [comment]
I already quite happy living with the missing icon now, it's almost a feature for me. ☺️

**Comment by derjanb** [comment]
> I already quite happy living with the missing icon now, it's almost a feature for me. relaxed

Stealth Mode!!! 😂

I can reproduce the problem. I'm [adding mutliple resolutions to the toolbar image](https://developer.apple.com/documentation/appkit/nsimage/1519911-addrepresentation?language=swift) in order to allow every system to show it in a native resolution, but since some Safari versions the icon is missing then. The workaround is to always use the `@2x` image, even though this is not the best solution for all systems. 🤷

**Comment by timkite** [comment]
> Stealth Mode!!! 😂
> 
> I can reproduce the problem. I'm [adding mutliple resolutions to the toolbar image](https://developer.apple.com/documentation/appkit/nsimage/1519911-addrepresentation?language=swift) in order to allow every system to show it in a native resolution, but since some Safari versions the icon is missing then. The workaround is to always use the `@2x` image, even though this is not the best solution for all systems. 🤷

Safari 15.4 introduced other bugs (a very annoying form submission bug where multiple feed characters get inserted for every line in textarea fields, for example), so perhaps you're doing it correctly and it's just 15.4 doing something wonky? I wonder if anyone running the macOS 12.4/Safari 15.5 beta can test to see if they fixed it?

**Comment by jprokos** [comment]
> I can reproduce the problem. I'm [adding mutliple resolutions to the toolbar image](https://developer.apple.com/documentation/appkit/nsimage/1519911-addrepresentation?language=swift) in order to allow every system to show it in a native resolution, but since some Safari versions the icon is missing then. The workaround is to always use the `@2x` image, even though this is not the best solution for all systems. 🤷

How are other developers getting consistent results across all Safari versions? Any open source extensions that might have a clue?

**Comment by derjanb** [comment]
They let Xcode manage their icon sets, which would be possible for Tampermonkey as well, but that needs some more investigation and coding. The core of the Safari app is the Tampermonkey webextension like it is used in other browsers and it likes to set toolbar images by path.

**Comment by nomadism19** [comment]
Safe to say issue affects everybody

**Comment by nammminn2** [comment]
yep its so funny https://share.cleanshot.com/v8hmTY

**Comment by P0sce3fa** [comment]
> Should be fixed at 4.17.6162. Sorry for the delay.

I'd be happy to hear the good news. Thank you very much.

**Comment by timkite** [comment]
> Should be fixed at 4.17.6162. Sorry for the delay.

Confirmed fixed! Thanks!

**Comment by jprokos** [comment]
Thanks for this fix. Even the color is spot on!

**Comment by timkite** [comment]
> > Should be fixed at 4.17.6162. Sorry for the delay.
> 
> I don't see it how do I install the beta version for safari ?

You shouldn't need a beta. The version in the AppStore now works.

**Comment by nammminn2** [comment]
It still looks the same for me I'm on Monterey![image](https://user-images.githubusercontent.com/64177573/170584609-c1dc3308-b415-414e-8c7d-0776a25a2fcc.png)

**Comment by GarthSnyder** [comment]
Hmm, interesting... It's definitely fixed for me, Monterey 12.4.

**Comment by timkite** [comment]
> It still looks the same for me I'm on Monterey!

I'm on Monterey myself. Safari 15.5, macOS 12.4, Tampermonkey 4.17.6162 (AppStore). You might need to restart?

Light Mode, separate tabs:
<img width="739" alt="Screen Shot 2022-05-26 at 17 45 47" src="https://user-images.githubusercontent.com/6933976/170585726-dfdf88b8-4a15-47f6-8eab-f66d8b1685e9.png">

Combined tabs:
<img width="796" alt="Screen Shot 2022-05-26 at 17 46 47" src="https://user-images.githubusercontent.com/6933976/170585766-6fc4fae2-a6f4-44a4-9883-9cd1a9011e8f.png">

Dark Mode, separate tabs:
<img width="760" alt="Screen Shot 2022-05-26 at 17 47 50" src="https://user-images.githubusercontent.com/6933976/170585787-d69561fb-1911-4bdf-80de-2d2cd55a57a6.png">

**Comment by nammminn2** [comment]
> > It still looks the same for me I'm on Monterey!
> 
> I'm on Monterey myself. Safari 15.5, macOS 12.4, Tampermonkey 4.17.6162 (AppStore). You might need to restart?
> 
> Light Mode, separate tabs: <img alt="Screen Shot 2022-05-26 at 17 45 47" width="739" src="https://user-images.githubusercontent.com/6933976/170585726-dfdf88b8-4a15-47f6-8eab-f66d8b1685e9.png">
> 
> Combined tabs: <img alt="Screen Shot 2022-05-26 at 17 46 47" width="796" src="https://user-images.githubusercontent.com/6933976/170585766-6fc4fae2-a6f4-44a4-9883-9cd1a9011e8f.png">
> 
> Dark Mode, separate tabs: <img alt="Screen Shot 2022-05-26 at 17 47 50" width="760" src="https://user-images.githubusercontent.com/6933976/170585787-d69561fb-1911-4bdf-80de-2d2cd55a57a6.png">

just got the update it works now :D

**Comment by okalachev** [comment]
Can there be an icon, only when some extension is active? It's **actually** a useful feature!

**Comment by timkite** [comment]
> Can there be an icon, only when some extension is active? It's actually a **useful** feature!

Safari already highlights extensions that are active with the selected highlight color (blue by default). They’re “button color” (depends on light/dark mode) otherwise. Hiding them completely when inactive could be a suggestion for Safari (https://www.apple.com/feedback/safari.html). IMO, Safari could really use an overflow menu like Firefox and others have to get extension icons out of your toolbar without hiding them (and their controls) completely.
