### ISSUE TITLE
`@connect *` doesn't allow to connect to localhost or to IP address

### ISSUE THREAD

**Issue by vabushkevich** [Tampermonkey/tampermonkey#1421]
## Expected Behavior

`@connect *` should allow `GM_xmlhttpRequest` to connect to the localhost or to an IP address.

## Actual Behavior

The request ends with an error. No confirmation dialog appears.

> Refused to connect to "http://localhost": Request was blocked by the user

or

> Refused to connect to "http://127.0.0.1": Request was blocked by the user

## Specifications

- Chrome: 98.0.4758.102
- TM: 4.14
- OS: Microsoft Windows 10.0.19041.1415

## Script

```js
// ==UserScript==
// @name    Connect issue
// @include *
// @grant   GM_xmlhttpRequest
// @connect *
// ==/UserScript==

(function () {
    'use strict';

    GM_xmlhttpRequest({
        url: "http://localhost",
        // url: "http://127.0.0.1", // also doesn't work
        method: "GET",
        onload: () => {
            console.log("Success");
        },
        onerror: (err) => {
            console.log("Error:", err);
        },
    });
})();
```

**Comment by derjanb** [comment]
Should be fixed at 4.15.6153 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_15_6153.crx))
