### ISSUE TITLE
[Safari] TM doesn't work on http / port 80

### ISSUE THREAD

**Issue by FirePanther** [Tampermonkey/tampermonkey#1425]
It doesn't matter what kind of "`match`" or "`include`" I use, TM doesn't run on http URLs (no difference between wildcard or hardcoded `http://` protocol inside of `@match`).
It doesn't recognize the change from an https to an http tab, it still thinks, I am on the https URL.
<img width="639" alt="Screenshot 2022-02-22 um 19 58 23" src="https://user-images.githubusercontent.com/1711106/155200525-5d07cc97-b308-40bc-a811-bd3c6d79a862.png">

MacOS Monterey (12.2.1)
Safari 15.3 (17612.4.9.1.8)
Tried also with turning off additional extensions
I think it's not blocked by Safari directly, other extensions (like AdGuard) work also on http.

Thanks for any help

**Comment by micturkey** [comment]
+1
Same problem found by me today
