### ISSUE TITLE
[Chromium] No console.x messages

### ISSUE THREAD

**Issue by aberfan** [Tampermonkey/tampermonkey#1426]
## Expected Behavior
console.log('test') will display "test" in console.

## Actual Behavior
No output at all.

## Specifications
Chromium Version 91.0.4455.0 (Developer Build) (64-bit)
Tampermonkey 4.14
WIndows 7 x64

## Script
```
console.log('Test');
console.info(`${GM_info.script.name} ${GM_info.script.version}`);
```

There is a show stopping bug in Tampermonkey 4.14 where no console.log messages, or ANY console messages (console.info, console.trace) appear.  Exact same scripts worked in 4.13. 

However, I use multiple browsers, and it's not broken in current Chrome (mainline) ones. It IS broken in my production work browser, where I use scripts on crowd platforms and so use Chromium and a set version. 
This is through reloading browser, clearing cache and so on. I don't know what the malfunction is, but I depend heavily on console output in scripts.

I managed to find a shady site to get a version of v4.13 and install locally, which at least allows me to use scripts but this may be something to look into if anyone else in the world isn't just using Chrome main.

**Comment by derjanb** [comment]
Closing in favor of #1451
