### ISSUE TITLE
Scoping Issue with TM 4.14

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1427]
(Please fill out the issue template with your details)

## Expected Behavior
Backwards compatibility with TM 4.13-

## Actual Behavior
Inherited prototypes don't seem to be available

## Specifications

- Chrome:98.0.4758.102
- TM: 4.14
- OS: Win8.1 / x64

## Script

Compared to plain JS in global context, only one call to foo(...) is completed:

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match *
// ==/UserScript==

Blob.prototype.foo = function(x) { console.log(x) };
let f = new File(["foo"], "foo.txt", { type: "text/plain" });
Blob.prototype.foo.call(f, 'bar'); // call is made
f.foo('bar'); // throws TypeError: f.foo is not a function
```

Beyond this incompatibility also I got error messages trying to define new local variables in console during TM script debugging .

**Comment by derjanb** [comment]
Should be fixed at 4.15.6153 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_15_6153.crx))
