### ISSUE TITLE
Import from file returns "Invalid json" for zip files

### ISSUE THREAD

**Issue by KL-07** [Tampermonkey/tampermonkey#1432]
(Please fill out the issue template with your details)

## Expected Behavior
1. Import zip file and multiple missing icons missing under "Utilities" section
<img width="1440" alt="Screen Shot 2022-03-05 at 5 06 44 PM" src="https://user-images.githubusercontent.com/99524563/156876632-22b4713d-00e9-459c-a08c-04c5f1706f71.png">
<img width="1440" alt="Screen Shot 2022-03-05 at 5 06 37 PM" src="https://user-images.githubusercontent.com/99524563/156876637-0f2cb37a-8173-48fa-9548-0e464a920390.png">

2. Automatic syntax check size in Settings-editor should have a text box next to it

## Actual Behavior
1. Only export option is shown at Utilities-zip
2. No text box is shown besides automatic syntax check size in Settings-editor

## Specifications

- Chromium: 99.0.4844.51
- TM: idk what this means
- OS: MacOS Monterey 12.2.1
**Please note that I have uploaded a bug report already prior to this one. Fast response is expected**

## Script

(Please give an example of the script if applicable.); not applicable as it is a bug in tampermonkey itself

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by KL-07** [comment]
Please respond fast... I know that you are busy but a long time has passed since my last bug report...

**Comment by KL-07** [comment]
Sorry sorry sorry I am new to github and do now know how to look at previous bug reports. Choose file in Utilities-Import from file works for select zip files, but sometimes it says "Invalid json" for zip files...

**Comment by KL-07** [comment]
<img width="1440" alt="Screen Shot 2022-03-05 at 5 14 15 PM" src="https://user-images.githubusercontent.com/99524563/156876857-bd3b5096-2e08-4e96-b4f7-aa1c461bb761.png">
Like this

**Comment by derjanb** [comment]
Should be fixed at 4.16.6158 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by KL-07** [comment]
> crx

hmm chrome says this: 
<img width="526" alt="Screen Shot 2022-03-25 at 12 41 52 AM" src="https://user-images.githubusercontent.com/99524563/159966835-90c8f0cb-2578-42d8-9a07-a2101344d42f.png">

**Comment by KL-07** [comment]
can i basically reinstall tampermonkey beta?
