### ISSUE TITLE
How to access multiple forms across pages

### ISSUE THREAD

**Issue by its-ogawa** [Tampermonkey/tampermonkey#1433]
I have found that I can access forms within a page from a Tampermonkey script.
This is a great feature for me.

Now, I am challenged with the case where there are multiple such forms across pages of URLs. (ex. https://****/page1, https://****/page2, ...)

I would like to pre-set the form input values in page1, then transition from the href tag in page1 to page2 and input them one after the other into the form.

However, even though I have written the process for the form on page2 after the page transition process, the process for the form on page2 is not executed.
What does Tampermonkey recommend to write in such a case?

Any advice would be appreciated in advance.

```
// ==UserScript==
// @name         sample html
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://localhost/page*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=undefined.localhost
// @grant        none
// @require      https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.11.1/xlsx.full.min.js
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    var import_component = document.createElement ('div');
    import_component.style = "position: fixed; top: 0; width:30%; z-index: 10000;"
    import_component.innerHTML='<input id="xlsx" type="file">'
    document.body.appendChild (import_component);

    var fileInput = document.getElementById("xlsx"),
        readFile = function () {
            var reader = new FileReader();
            reader.onload = function (e) {
                var data = reader.result;
                var arr = fixdata(data);
                var wb = XLSX.read(btoa(arr), {
                    type: 'base64',
                    cellDates: true,
                });
                var output = to_dictionary(wb); // Read input values to form from xlsx
                console.log(output);

                set_page1(values); // Description for page1 form
                document.getElementById("next").click()
                set_page2(values); // Description for page2 form

            };
            reader.readAsArrayBuffer(fileInput.files[0]);
        };
    };
})();
```

**Comment by derjanb** [comment]
You can retain your state via [GM_setValue](https://www.tampermonkey.net/documentation.php#GM_setValue).

**Comment by its-ogawa** [comment]
@derjanb 
Thanks for the answer.
I wasn't sure how to use 'GM_setValue'.
I used localStorage instead and successfully got the value even after page transitions.
I'm sure it will be used in a similar way, but I'd like an example of how to use it well.
