### ISSUE TITLE
How to roll back old version

### ISSUE THREAD

**Issue by luotianyiismywife** [Tampermonkey/tampermonkey#1437]
How to roll back old version
In the latest 4.15.6154 version, some of my scripts don't work properly, so I want to rollback him.
By the way, I attach my browser information and script information.
win10, Firefox 98.0 (20220304153049), tamermonkey version 4.15.6154
The script in question is https://github.com/XIU2/UserScript of this project
The specific situation is that if the option of whether to allow tamermonkey to run in the privacy window is not changed once, the script cannot be used normally.

**Comment by luotianyiismywife** [comment]
https://github.com/XIU2/UserScript/issues/186  this is when i found the bug‘s time，the communicate of i with that script's developer

**Comment by derjanb** [comment]
For me the script is crashing at https://github.com/XIU2/UserScript/blob/master/Zhihu-Enhanced.user.js#L369 in both TM 4.13.6136 and  4.15.6154. Once this is fixed the script itself runs without error, but I don't know what behavior to expect.

Another issue might be cause by this line. Tampermonkey got faster so it might be necessary to wait 300ms now in TM as well? But I'm not sure though. https://github.com/XIU2/UserScript/blob/master/Zhihu-Enhanced.user.js#L1384

**Comment by luotianyiismywife** [comment]
> > How to roll back old version
> 
> Oh, and to answer your question: Mozilla disabled 4.13.6136 because they didn't like the used jQuery version. So it is unfortunately not possible to go back to the old version. Sorry.

oh，i know，so maby ishould use chrome or wait for next version。
thank you。
