### ISSUE TITLE
Tampermonkey doesn't save settings in sections that have a "Save" button

### ISSUE THREAD

**Issue by tomcss** [Tampermonkey/tampermonkey#1438]
## Expected Behavior
When I click on any 'Save' button in the settings page, I expect the settings to be saved and remembered. I tried almost all settings groups including changing the script templates which also didn't get stored.

## Actual Behavior
Most 'Save' buttons do nothing. Some tell me they require a refresh, and then it actually does refresh but will not show the new settings changes, but instead the original settings. The save buttons do become enabled (not greyed out) after changing settings or text inside textboxes.

## Specifications

This is on a very fresh install of Windows and Firefox

Firefox 98.0 (64-bit)
Windows 11 21H2 (22000.527)
TM v4.15.6154

**Comment by vanja-san** [comment]
This happened after last update of tempmonkey. Problem is most likely with extension itself. 😶

**Comment by derjanb** [comment]
This seems to work fine here. There also was no change at the storage code.

Please try a new temporary profile. Is it working then?

https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

**Comment by vanja-san** [comment]
@derjanb I can try and get logs
![изображение](https://user-images.githubusercontent.com/7201687/157544237-cb5fef02-9b4c-450b-bcfb-0b03f6ca70df.png)

**Comment by tomcss** [comment]
> This seems to work fine here. There also was no change at the storage code.
> 
> Please try a new temporary profile. Is it working then?
> 
> https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

I tried with a new temporary profile but experienced the same problem.

There are no errors or messages in the console.

After some more testing I found that the "General", "Context Menu" and "Userscript Search" settings *do* get saved. It seems anything with a 'Save' button does not get saved.

**Comment by wongzeon** [comment]
I experienced the same problem too, the 'Save' button can't save anythings. 

The problem came up after I installed Windows 11 (ver: 22000.556) and update the Edge browser to the lasted version(99.0.1150.39), installed Tampermonkey(ver: 4.15) via Edge Add-ons store.

I think the problem maybe with the version of system, because in Windows 10 it doesn't happen.

**Comment by derjanb** [comment]
Should be fixed at 4.16.6155 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_16_6155.crx))

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

Chrome users, please install the BETA version or download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the (BETA version)[https://www.tampermonkey.net/index.php?browser=firefox] or check for updates at `about:addons`

**Comment by vanja-san** [comment]
@derjanb It seems to work on Firefox. I understand that I have lost all my saves from browser storage?

**Comment by SunshineboyZj** [comment]
> I experienced the same problem too, the 'Save' button can't save anythings.

Windows 10 Home Edition 21H2(ver: 19044.1586) and update the Edge browser to the lasted version(99.0.1150.36), installed Tampermonkey(ver: 4.15) via Edge Add-ons store.

**Comment by SunshineboyZj** [comment]
I experienced the same problem too, the 'Save' button can't save anythings in Windows 10 Home Edition 21H2 (ver: 19044.1586) , Edge version(99.0.1150.36)(64 bit), Tampermonkey(ver: 4.15) via Edge Add-ons store.

**Comment by derjanb** [comment]
> I understand that I lost all my saves from the browser storage?

@vanja-san This issue should only have prevented you from changing some settings. Nothing else can be lost due to this issue.

> Tampermonkey(ver: 4.15) via Edge Add-ons store.

@SunshineboyZj MS Edge can install the crx file from my last post as well.

**Comment by dtrunk90** [comment]
@derjanb if i understand correctly firefox users already have the fix in place if there are no addon updates? because i still can't save the security section settings.

**Comment by vanja-san** [comment]
@dtrunk90 Only beta version with fixes so far, no stable release yet.

**Comment by dtrunk90** [comment]
@vanja-san Maybe this sentence should be changed then because it's confusing:
> Firefox users please install the BETA version or check for updates at about:addons

**Comment by Tatsh** [comment]
I am having this issue with cloud sync settings.
