### ISSUE TITLE
expect show translucent pictures icon, got black background image

### ISSUE THREAD

**Issue by lisonge** [Tampermonkey/tampermonkey#1439]
tampermonkey@v4.15

## Expected Behavior

Show translucent pictures icon

## Actual Behavior

Display black background image

![image](https://user-images.githubusercontent.com/38517192/157800090-98215934-dc1b-40ac-bd9e-10ce06068431.png)

## UserScript

```js
// ==UserScript==
// @name         原神Wiki辅助工具
// @namespace    https://dev.songe.li
// @version      1.1.0
// @author       lisonge
// @description  原神 Wiki 辅助工具, 1.显示/隐藏已完成成就
// @license      MIT
// @icon         https://dev.songe.li/favicon.svg
// @homepage     https://github.com/lisonge/op-wiki-plus#readme
// @homepageURL  https://github.com/lisonge/op-wiki-plus#readme
// @supportURL   https://github.com/lisonge/op-wiki-plus/issues
// @include      https://wiki.biligame.com/ys/*
// @require      https://cdn.jsdelivr.net/npm/vue@3.2.31/dist/vue.global.prod.js
// @require      https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js
// ==/UserScript==
```

**Comment by derjanb** [comment]
Should be fixed at 4.16.6157 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons`
