### ISSUE TITLE
Amazon subtitle downloader hangs amazon webpages after tampermonkey update

### ISSUE THREAD

**Issue by Frank-Steiner** [Tampermonkey/tampermonkey#1442]
In the recent version of tampermonkey the "amazon subtitle downloader" script has issues with tampermonkey. The same version of the script worked fine with the previous version of tampermonkey. 

There is no such problem when running the script in greasemonkey.

## Expected Behavior
The script should do nothing when not on a amazon prime video page and it should not cause high cpu usage or keep amazon webpages from loading.

## Actual Behavior
On any amazon product page (so, not on the the start page but on every page that show a product) the script causes the amazon webpage to stop loading somewhere in the middle of the load process, hanging forever and causing high cpu usage. Even after closing the webpage there is a "Web content" process is left over and the cpu load continues, the process must be killed manually.

## Specifications
Firefox 91.7.0esr and Firefox 98
- TM: 4.15.6154
- OS: SuSE Linux Enterprise 15sp3 and openSuSE 15.3.

## Script
https://greasyfork.org/de/scripts/34885-amazon-video-subtitle-downloader/code

**Comment by derjanb** [comment]
Should be fixed at 4.16.6156 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_16_6156.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Frank-Steiner** [comment]
Yes, it works fine in the beta for FF! Many thanks!
