### ISSUE TITLE
In tampermonkey menu with darker mode the icons are overlapping userscript switches

### ISSUE THREAD

**Issue by CennoxX** [Tampermonkey/tampermonkey#1444]
With the new version and "darker" theme the icons are shown at the beginning of the options and are overlapping with the switches.

## Expected Behavior
I expect something like this, just with darker mode.
![grafik](https://user-images.githubusercontent.com/6975881/158537837-88124d7e-87cd-4118-9392-2c9093faf0f3.png)

## Actual Behavior
What I get is this mess. See also the size difference of the window, the size is made bigger line by line, until it's this size.
![grafik](https://user-images.githubusercontent.com/6975881/158538176-bff88c3d-337b-413f-85c2-7d222fee5150.png)

## Specifications

- Firefox: 98.0.1
- TM: 4.15.6154
- OS: Windows 10 Pro (21H1, 19043.1586)

**Comment by derjanb** [comment]
Darker mode was the missing hint. :+1:  Closing in favor of #1414
