### ISSUE TITLE
console.clear() doesn't work

### ISSUE THREAD

**Issue by CennoxX** [Tampermonkey/tampermonkey#1445]
In the new version, console.clear() doesn't work.

## Expected Behavior
The console is cleared when calling console.clear().

## Actual Behavior
Nothing happens

## Specifications

- Firefox: 98.0.1
- TM: 4.15.6154
- OS: Windows 10 Pro (21H1, 19043.1586)

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @version 1.0
// @description try to take over the world!
// @author Me
// @include https://github.com/*
// @grant none
// ==/UserScript==

(function() {
    "use strict";
    console.log("what");
    alert("pause");
    console.clear();
})();
```

Log:
<details><pre>
08:40:21.908 content: normal start event processing for f852430c-8cf3-49aa-8344-9fde38017281 (1 to run) content.js:131:29
08:40:21.909 content: Start ENV normally f852430c-8cf3-49aa-8344-9fde38017281 content.js:132:216
08:40:21.912 env: initialized (content, id:f852430c-8..., https://github.com/Tampermonkey/tampermonkey/issues/1444) 1444 line 3 > eval:7:184
08:40:21.913 Tampermonkey started 1444 line 3 > eval:67:4
08:40:21.913 env: schedule "MyName" for document-idle 1444 line 3 > eval:7:43
08:40:21.931 env: execute script MyName @ the unsafe context now! 1444 line 3 > eval:61:191
08:40:21.934 what 1444:13:1037
08:40:21.934 Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. 1444 line 4 > eval:16:9
08:40:26.985 Referrer Policy: Weniger eingeschränkte Richtlinien, einschließlich "no-referrer-when-downgrade", "origin-when-cross-origin" und "unsafe-url", werden für Website-übergreifende Anfragen bald ignoriert: https://github.githubassets.com/assets/chunk-7178-491800522f12.js runtime-9bb11f732d6f.js line 16 > srcScript:1:4212
08:40:27.153 content: detected DOMContentLoaded f852430c-8cf3-49aa-8344-9fde38017281 content.js:109:381
08:40:27.174 content: detected load f852430c-8cf3-49aa-8344-9fde38017281 content.js:109:244
08:40:27.188 Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html für weitere Details und um an der Diskussion über damit verbundene Werkzeuge und Funktionen teilzunehmen. 1444
08:40:28.917 Error: Promised response from onMessage listener went out of scope background.js:88:27
</pre></details>

**Comment by derjanb** [comment]
Closing in favor of https://github.com/Tampermonkey/tampermonkey/issues/1451
