### ISSUE TITLE
jump to line from console does't jump into the userscript source anymore

### ISSUE THREAD

**Issue by CennoxX** [Tampermonkey/tampermonkey#1446]
When clicking on a line in the console with the earlier teampermonkey version, I would jump directly to the part in the userscript, for example "MyUser.user.js" where console.log was written, now I end in SOURCE.

When clicking here: 
![grafik](https://user-images.githubusercontent.com/6975881/158542525-661e3c0d-e62f-4709-9915-b1867e20666b.png)
## Expected Behavior
I expect to go here
![grafik](https://user-images.githubusercontent.com/6975881/158542779-8190a9ab-0942-4a1c-a225-be24d57154e1.png)

## Actual Behavior
Instead I go here, to "SOURCE"
![grafik](https://user-images.githubusercontent.com/6975881/158542886-8446c428-5de9-4e00-9d57-c16e1c7be755.png)

## Specifications

- Firefox: 98.0.1
- TM: 4.15.6154
- OS: Windows 10 Pro (21H1, 19043.1586)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @version 1.0
// @description try to take over the world!
// @author Me
// @include https://stackoverflow.com/*
// @grant none
// ==/UserScript==

(function() {
    "use strict";
    console.log("jump here");
})();
```

**Comment by derjanb** [comment]
Closing in favor of https://github.com/Tampermonkey/tampermonkey/issues/1451
