### ISSUE TITLE
TamperMonkey not updating in Rodeo

### ISSUE THREAD

**Issue by broocarr** [Tampermonkey/tampermonkey#1453]
(Please fill out the issue template with your details)

## Expected Behavior
expected behavior of tamper monkey is to show what picks are in scanner, whos scanner they are in, if the got refused or rejected, etc. 

## Actual Behavior
Tamper Monkey is completely not working at all for IND1. We are not able to see any updates in rodeo with Tamper Monkey and it took us back to the old way. we can no longer see what picks are in scanner, etc. Nothing at all 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
Version 20210915
not sure how to look at script? 

(Please give an example of the script if applicable.)
// ==UserScript==
// @name        NewRodeo
// @namespace   ORY1
// @version 20210915
// @updateURL   https://drive.corp.amazon.com/view/lorfeuvr@/ORY1scripts/NewRodeo.user.js
// @downloadURL https://drive.corp.amazon.com/view/lorfeuvr@/ORY1scripts/NewRodeo.user.js
// @include     https://rodeo-*.amazon.com/*/ItemList?*
// @include     https://rodeo-*.amazon.com/*/Search?*
// @include     https://rodeo-*.amazon.com/*/ExSD?*
// @require     https://drive.corp.amazon.com/view/lorfeuvr@/libs/jquery/3.2.1/jquery.min.js
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_xmlhttpRequest
// ==/UserScript==
// ORY1 - lorfeuvr@amazon.com
// _______________________________________

**Comment by mandel99** [comment]
Tampermonkey is only tool for scripts created by someone else, you need to contact script creator i think it is login "lorfeuvr" try  send pm on chime
