### ISSUE TITLE
Export to file fails when "Include Tampermonkey settings" is enabled

### ISSUE THREAD

**Issue by joeytwiddle** [Tampermonkey/tampermonkey#1455]
## Expected Behavior

On Utilities page, "Export to File" should cause a file to download. And it does, when "Include Tampermonkey settings" is disabled.

## Actual Behavior

When "Include Tampermonkey settings" is enabled, "Export to File" does not produce a file for download.

Also there is a popup at the top of the page, which says: "Action Failed"

## Specifications

- Google Chrome 99.0.4844.51
- TamperMonkey 4.14_0

## Data

Since "Export to zip" does work, I will share that with you. It might be possible to reproduce the bug.

https://mega.nz/file/ut80AAjL#mbXahkNyI3lVKbmIeUdqC9z_FS9CdRiZIaC32xXVyrs

## Additional

This isn't a big issue for me, since the zip worked fine for me.

I didn't know where to find a logfile that might help you.

**Comment by derjanb** [comment]
Working fine here. But what happened to me was a download dialog in the background, which prevented new ones from coming up? Can you please re-test? If you still see this issue: what is "Download Mode" is configured?
