### ISSUE TITLE
wont open and let me userscripts

### ISSUE THREAD

**Issue by LETMESAYMYISSUE1128726821** [Tampermonkey/tampermonkey#1457]
(Please fill out the issue template with your details)

## Expected Behavior
open and let me userscripts

## Actual Behavior
doesnt open and let me userscripts

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Scratch Ext2to3
// @namespace    https://github.com/NitroCipher/ext2to3
// @version      0.8b
// @description  try to take over the world!
// @author       NitroCipher and Jamesbmadden
// @match        https://scratch.mit.edu/convert/*
// @grant        none
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
// @require      https://cdn.rawgit.com/beautify-web/js-beautify/v1.8.9/js/lib/beautify.js
// ==/UserScript==
```

**Comment by LETMESAYMYISSUE1128726821** [comment]
heres the file of what i was trying to use (i had to compress it because js is not supported file type here
[ext2to3.user.js.zip](https://github.com/Tampermonkey/tampermonkey/files/8344069/ext2to3.user.js.zip)
)

**Comment by derjanb** [comment]
What is your Tampermonkey version?

**Comment by LETMESAYMYISSUE1128726821** [comment]
Sorry! The issue is fixed, it's working now.
