### ISSUE TITLE
the web page of Town Star refreshing forever when using TS Auto-Sell Script 

### ISSUE THREAD

**Issue by katthsieh** [Tampermonkey/tampermonkey#1459]
(Please fill out the issue template with your details)

## Expected Behavior

the web page below opens normally and play Town star normally when using Town Star Auto-Sell Script.

## Actual Behavior

1) the web page below keeps refreshing forever when using Town Star Auto-Sell Script and launch town star around 60%
https://app.gala.games/games/town-star/play

2) Works well serveral day ago (play Town star as normal when using Town Star Auto-Sell Script). 
3) Also tried using 4.16.6156 version of Tampermonkey, but doesn't help.

## Specifications

- Chromium:  **Chrome 99.0.4844.82 (Official build) 64-bit**
- TM: **4.14 (stable version)**
- OS:  **windows 11**

## Script

**Town Star Auto-Sell Script**

// ==UserScript==
// @name         Town Star Auto-Sell
// @namespace    http://tampermonkey.net/
// @version      2.3
// @description  Automatically sell crafted items.
// @author       Groove
// @match        *://*.sandbox-games.com/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

**Comment by 7nik** [comment]
Tampermonkey is a userscript manager. Please contact the script developers if a script does not work. If there is a general problem with Tampermonkey, they will come back here.

[Here](https://gist.github.com/MrCelticFox/cf416fddbc25c456de5bbe5d1aac857f) I found a discussion about this script so you can ask there for the fix.

**Comment by troytabor** [comment]
Noticed this too. So, disable tampermonkey, then go click the Open Townstar for it to start loading. After it's past the 60% mark, click Enable for Tampermonkey and it should finish loading and work!

**Comment by katthsieh** [comment]
@troytabor @7nik  thanks. 
I found that town star just updated with the function of auto-sell several days ago. it means no need for the auto-sell script from tampermonkey
