### ISSUE TITLE
GM_notification silent doesn't work

### ISSUE THREAD

**Issue by KorayUlusan** [Tampermonkey/tampermonkey#1462]
This should be added in #727

## Expected Behavior

Notification should be silent.

## Actual Behavior

Notification is displayed with sound.

## Specifications

- Firefox 96
- TM: 4.15.6154
- OS: MacOS Catalina

## Script

```js
// ==UserScript==
// @....
// @grant        GM_notification
// ==/UserScript==

(function () {
    'use strict';

    GM_notification({
        title: 'aaaa',
        text: 'bbbb',
        silent: true,
    })
})();
```

**Comment by derjanb** [comment]
`silent` is not supported by Firefox. Feel free to star the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1335659
