### ISSUE TITLE
Script Issue

### ISSUE THREAD

**Issue by Tanookirby** [Tampermonkey/tampermonkey#1463]
## Expected Behavior
Script is supposed to remove the rel attribute from certain elements under a certain condition.

## Actual Behavior
No changes to the HTML layout

## Specifications

Name 	Firefox
Version 	98.0.2
Build ID 	20220322144853

## Script

// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http*://*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    var anotherElement = document.querySelector('*[class~=h-entry],*[class~=hentry]')
    var shouldDelete = anotherElement && anotherElement.className.match(/(^|\s)h-?entry(\s|$)/)

    if (shouldDelete) {
      var links = document.querySelectorAll('link[rel*="next"], link[rel*="Next"], link[rel*="NEXT"]')
      for(var link of links){
          link.removeAttribute('rel')
      }
    }

    var anotherElement2 = document.querySelector('*[class~=h-entry],*[class~=hentry]')
    var shouldDelete2 = anotherElement2 && anotherElement2.className.match(/(^|\s)post-.*h-?entry(\s|$)/)

    if (shouldDelete2) {
      var links2 = document.querySelectorAll('a[rel*="next"], a[rel*="Next"], a[rel*="NEXT"]')
      for(var a of links2){
          a.removeAttribute('rel')
      }
    }

})();

## Example link:

https://tvline.com/lists/cancelled-tv-shows-what-happened-next-spoilers/

**Comment by 7nik** [comment]
Your `@match` is invalid. Use `http*://*/*`
