### ISSUE TITLE
"Website will not allow Firefox to display the page if another site has embedded it" error with any script enabled

### ISSUE THREAD

**Issue by byzod** [Tampermonkey/tampermonkey#1467]
Example site: https://www.reddit.com/r/place/

(Please locate the problem ASAP before the event ends, I haven't find any other example site yet)

Problem: If any script is enabled, embedded r/place page can't be loaded

## Expected Behavior
Display embedded site normally

## Actual Behavior
"Website will not allow Firefox to display the page if another site has embedded it" Error 

## Specifications

- Firefox: 99.0b8 (20220324185704)
- TM: 4.15.6154
- OS:  Windows_NT 10.0 19044

## Script

```js
// ==UserScript==
// @name         Dummy Userscript
// @namespace    test@test.user.js
// @version      0.1
// @description  try to take over the world!
// @include      http://*
// @include      https://*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=reddit.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    // Your code here...
    // Do nothing
})();
```

## Reproduce steps
1. Install firefox 99b8 and create a new profile, install TM
2. Create a dummy script that does nothing as provided above
3. Open https://www.reddit.com/r/place/

## More info
Embedded site display correctly when no script is enabled
![0](https://user-images.githubusercontent.com/848607/161410581-bb855713-3057-4767-8f77-750ee215ca3d.jpg)

Error when any script enabled
![1](https://user-images.githubusercontent.com/848607/161410597-bffbf312-1d54-439a-a497-0bda55e9a072.jpg)

This issue can be reproduced on a fresh new profile that has only TM installed and only one script enabled
![2](https://user-images.githubusercontent.com/848607/161410637-975fbac0-bdc2-4bb2-9d75-ce24b6428bb2.jpg)
![3](https://user-images.githubusercontent.com/848607/161410638-365da3dd-d3ab-4c0b-9330-caa17f4994b7.jpg)

**Comment by derjanb** [comment]
Potential dupliate of #1447
Does the [BETA version](https://www.tampermonkey.net/?browser=firefox) work fo you?

**Comment by byzod** [comment]
I use violentmonkey instead now :D
