### ISSUE TITLE
Tamper doesnt load scripts or options

### ISSUE THREAD

**Issue by noponydeepweb** [Tampermonkey/tampermonkey#1469]
since i installed tampermonkey, the extension is not opening after 3 days of installation, it only freezes all scripts and itself
i didnt even changed anything on browser (Firefox 98.0.2 32-bit) or browser (i only installed new scripts, like oneechan, 4chanx or changed a css script)

**Comment by ronpage55** [comment]
taper did update on my laptop which runs firefox now i cant get my scripts back

**Comment by Tatsh** [comment]
On Chrome I am not able to load options at all or the widget from the icon. Just shows the spinner. This happens for both regular 3.15 and beta version.

**Comment by V2Blast** [comment]
TamperMonkey was working fine for me for a while... but scripts haven't been running for me for the last few weeks, and I haven't been able to load the options either. Even the menu won't open from Firefox's toolbar; it just displays the loading icon forever.

Not sure if a Firefox update caused the issue, or something else. Restarting my browser hasn't helped, either. I'm currently using Firefox 101.0 (64-bit) in Windows 10.

> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0

**Comment by derjanb** [comment]
Please check the latest Tampermonkey version 4.18.0
