### ISSUE TITLE
受限的运行时主机权限可能损坏脚本升级、 GM_xmlhttpRequest 以及其他 Tampermonkey 功能！

### ISSUE THREAD

**Issue by guocuixia** [Tampermonkey/tampermonkey#1475]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by guocuixia** [comment]
受限的运行时主机权限可能损坏脚本升级、 GM_xmlhttpRequest 以及其他 Tampermonkey 功能！

**Comment by derjanb** [comment]
Duplicate of #640

**Comment by 1545118122** [comment]
在权限受限的执行环境中可能会影响脚本升级、GM_xmlhttpRequest 以及其他 Tampermonkey 功能！
请问出现这个问题怎么办呢？我的脚本加入之后就会被自动删除，反反复复，无法解决。谢谢。
PS：Sigma OS

**Comment by derjanb** [comment]
Looks like your browser profile is broken? Please try a new temporary profile.

**Comment by 1545118122** [comment]
你好，我重新下载了该脚本管理器，但仍显示该提示，事情并未能解决，希望您帮忙解决下谢谢。用的Mac浏览器cigma os。
Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others
