### ISSUE TITLE
Get all storage data

### ISSUE THREAD

**Issue by sdfdger** [Tampermonkey/tampermonkey#1476]
I would like to be able to get all storage data for my script. 
```
> GM_getAllData()
{"foo":"bar"}
> GM_setValue("key","value")
> GM_getAllData()
{"foo":"bar","key":"value"}

```

## Specifications

- Chromium: 99.0.4844.84
- TM: v4.14
- OS: Windows 10

**Comment by jb222** [comment]
Try this:
`GM_listValues().forEach(function(v){console.log(v + ": " + GM_getValue(v));});`
