### ISSUE TITLE
Vue Devtools stops working after page refresh when open Tampermonkey

### ISSUE THREAD

**Issue by N1body** [Tampermonkey/tampermonkey#1477]
(Please fill out the issue template with your details)

## Expected Behavior
Vue Devtools can will refresh after page refresh when open Tampermonkey

## Actual Behavior
Vue Devtools stops working after page refresh when open Tampermonkey

## Specifications

- Chrome 100.0.4896.75
- Windows 10
- TamperMonkey 4.16

## Script
no script

**Comment by derjanb** [comment]
Can you please add the exact steps how to reproduce the issue? Thanks.

**Comment by N1body** [comment]
> Can you please add the exact steps how to reproduce the issue? Thanks.

### Steps to reproduce
Run the vue project----F12----open the Tampermonkey extension----open vuejs-devtools page----F5(refresh page)------Bug(vuejs-devtools page is empty)---<> (Chrome Version 100.0.4896.127)

when I close the Tampermonkey extension, I refresh page the vuejs-devtools also can run normally. So I think that is the conflict of two extensions

**Comment by derjanb** [comment]
Tested at 

https://sfc.vuejs.org/

[Vue.js devtools 6.1.4](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

with TM 4.16.1 and TM 4.18.6163 + Chrome 104.0.5098.0 @ Ubuntu
and TM 4.16.1 + Chrome 99.0.4844.51 and  102.0.5005.63 @ Windows 10

and all is working fine here. Can your reproduce the issue this way?
