### ISSUE TITLE
A base64 image slows down the loading of webpages.

### ISSUE THREAD

**Issue by nomomo** [Tampermonkey/tampermonkey#1478]
## Expected Behavior
Until TM v4.15, the string of base64 image included in the script had little effect on the performance of the webpage.

## Actual Behavior
Depending on the length of the base64 image string included in the script, it slows down the loading of webpages.

## Specifications
- Chrome: 100.0.4896.75 (Latest version as of April 9, 22)
- TM: 4.16 (Latest version as of April 9, 22)
- OS: Windows 10

## Script
The userscript I actually developed is too complex([link](https://github.com/nomomo/Addostream/blob/master/Addostream.user.js)). So I created a userscript for this bug report.

[220409TMdebug.user.zip](https://github.com/Tampermonkey/tampermonkey/files/8453946/220409TMdebug.user.zip)

After installing the userscript above, go to [https://www.youtube.com/](https://www.youtube.com/) and you will notice that webpage takes a long time to fully load. It takes about 10 seconds to fully load the Youtube webpage on my PC. In this script, the text corresponding to the base64 image is even commented out, but the webpage loads very slowly.

**Comment by derjanb** [comment]
Closing in favor of #1486

Thank you very much for your debug information!
