### ISSUE TITLE
[Enhancement] Option to make data storage shared with incognito mode

### ISSUE THREAD

**Issue by sdfdger** [Tampermonkey/tampermonkey#1479]
"Store data in incognito mode" should have an option to make non/incognito mode use the same data storage.

## Script
```
Non-incognito > GM_getValue("name")
"foo"
Incognito > GM_setValue("name","bar")
Non-incognito > GM_getValue("name")
"bar"
```

## Specifications

- Chromium: 99.0.4844.84
- TM: 4.14
- OS: Windows 10

**Comment by derjanb** [comment]
Set "Settings > Security > Store data in incognito mode" to "Permanent" to achieve this behavior. Make sure to set "Config Mode" to "Advanced" first.
