### ISSUE TITLE
Google Charts Visualization via Tampermonkey Not working.

### ISSUE THREAD

**Issue by zwebmedia** [Tampermonkey/tampermonkey#1482]
Thanks to this community for all the great help. I have been successful adding new JS functionality to some webpages with Tampermonkey. Now I am trying to show a Google Chart injected on a webpage. Chrome browser. I have been trying on and off for several months, and no joy. To simplify debugging, I have stripped everything down to the simplest TM script to show a pie chart, URL matching on Google home page. The TM script activates on google home page and overlays a chart div. The DIV is visible but no chart is rendered. No related errors in JS console.

The chart renders fine if NOT using Tampermonkey.

[https://jsfiddle.net/_pirateX/ue88hus0](url)

I have tried window.onload in various positions, and moved the Google chart loader in various places. I have tried to set the load callback just using the function name drawChart. I tried different methods of detecting page load, but no change.

`// @name         Chart Example1
// @namespace    http://tampermonkey.net/
// @version      1.0.0
// @description  try to take over the world!
// @author       You
// @require      https://www.gstatic.com/charts/loader.js
// @match        https://www.google.com
// ==/UserScript==
/* global google */

'use strict';

google.charts.load("current", {packages:["corechart"]});

window.onload = function() {

   var myWrapper = document.createElement('div');
   myWrapper.style.position = 'fixed';
   myWrapper.id = "myChart";
   myWrapper.style.width = '600px';
   myWrapper.style.height = '300px';;
   myWrapper.style.right = '1em';
   myWrapper.style.top= '10em';
   myWrapper.style.background = 'rgba(255, 255, 255, 1)';
   myWrapper.style.border = '2px solid grey';
   document.body.append(myWrapper);

    //put here code
    google.charts.setOnLoadCallback(function() { drawChart()});

    function drawChart() {

       var data = new google.visualization.DataTable();
       data.addColumn('string', 'Group');
       data.addColumn('number', 'Gender');
       data.addRows([
          ['Males', 10],
          ['Females', 5]
       ]);

       var options = {'title':'Gender distribution',
                       'width':300,
                       'height':300};
       var chart = new google.visualization.PieChart(document.getElementById('myChart'));
       chart.draw(data, options);
    }
}`

**Comment by derjanb** [comment]
The loader injects a script into the page, but the`@require`'d script "lives" inside the sandbox. Please use
`@unwrap` to make it work.

```// ==UserScript==
// @name Chart Example1
// @namespace http://tampermonkey.net/
// @Version 1.0.0
// @description try to take over the world!
// @author You
// @require https://www.gstatic.com/charts/loader.js
// @match https://www.google.com/
// @unwrap
// ==/UserScript==
[...]
```

**Comment by zwebmedia** [comment]
Thank you sir for quick reply, much appreciated. When I do exactly as your suggestion, I get yellow triangle eslint error "'@unwrap' is not a valid userscript header." Please can you recommend how to fix this thank you again.

![image](https://user-images.githubusercontent.com/4979226/163303566-c942b72d-ac27-4c6c-83f4-095d7d03da87.png)

**Comment by derjanb** [comment]
Please update to Tampermonkey 4.16

**Comment by zwebmedia** [comment]
Thank you sir. Yes I am running V4.16
![image](https://user-images.githubusercontent.com/4979226/163349044-4abc19b3-59d0-4241-8f19-1e4e4bbe77d2.png)
