### ISSUE TITLE
Userscript not loaded when Firefox JSON Viewer enabled

### ISSUE THREAD

**Issue by michele-grifa** [Tampermonkey/tampermonkey#1484]
When the Firefox integrated JSON Viewer render a JSON response from an url, any userscript is loaded.
Disabling `devtools.jsonview.enabled` config, resolve the problem.

## Expected Behavior
When loading a JSON response, the userscript should load and trigger.

## Actual Behavior
The userscript is not loaded.

## Specifications

- Firefox: 99.0
- TM: 4.16.6160
- OS: Windows 10 21H2 19044.1586

## Script

```js
// ==UserScript==
// @name         Test Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Test script to report issue
// @author       Test
// @match        http://headers.jsontest.com/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=jsontest.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    const json = JSON.parse(document.querySelector('pre').innerText);

    console.log(json.Accept);
})();
```

**Comment by derjanb** [comment]
Needs to be fixed by Mozilla. Sorry. -> https://bugzilla.mozilla.org/show_bug.cgi?id=1416888
