### ISSUE TITLE
Remove "Both" Page Filter Mode

### ISSUE THREAD

**Issue by Anonymous87549236** [Tampermonkey/tampermonkey#1487]
## Expected Behavior
Settings -> Security -> Page Filter Mode -> Both unique behaviour.

## Actual Behavior
Synonym for whitelist.

## Specifications
- Chromium: 100.0.4896.88
- TM: 4.16
- OS: Windows 11 x64
Console: 10.0.22000.613
Version: 21H2
Build: 22000.613
Windows Feature Experience Pack: 1000.22000.613.0

**Comment by derjanb** [comment]
`Both` means both lists are taken into account.
