### ISSUE TITLE
Where is the source code and api document of tempermonkey beta?

### ISSUE THREAD

**Issue by aweiu** [Tampermonkey/tampermonkey#1488]
First of all, thank you very much for providing such an excellent plug-in!

I'm sorry to ask you a question that may seem very simple to you. I really didn't find it

I can't find the source code related to **GM_cookie** under this repo, and I can't find the relevant instructions in the [document](https://www.tampermonkey.net/documentation.php)

**Comment by 7nik** [comment]
TM is a closed-source software since a long time ago.
[Here](https://github.com/Tampermonkey/tampermonkey/issues/465#issuecomment-429058294) is the info about GM_cookie.

**Comment by derjanb** [comment]
`GM_cookie` is an experimental API and "documented" here -> https://github.com/Tampermonkey/tampermonkey/issues/465#issuecomment-429058294
