### ISSUE TITLE
Tampermonkey should not modify CSP on websites where it is disabled

### ISSUE THREAD

**Issue by nyuszika7h** [Tampermonkey/tampermonkey#1489]
## Expected Behavior

Tampermonkey should not modify CSP on a website if it is disabled there.

## Actual Behavior

If the global option to modify CSP is enabled, it messes with CSP settings regardless, which breaks some sites, for example https://cryptpad.fr/drive/:

![Screenshot of error](https://user-images.githubusercontent.com/482367/164007830-a4b2d365-3355-4744-b235-82505dfb22fb.png)

The only solution is disabling Tampermonkey globally while using this site.

## Specifications

- Chromium: 99.0.4844.82
- TM: 4.16
- OS: Ubuntu 21.10

## Script

N/A

**Comment by derjanb** [comment]
Disabling all scripts deactivates the warning fine here. Does a force-reload (ctrl+f5 or shift+f5) help?

BTW: you can disable CSP modification at "Settings > Security > Modify existing content security policy (CSP) headers". Be sure to enable "Advanced" "Config Mode" first.

**Comment by nyuszika7h** [comment]
> Disabling all scripts deactivates the warning here. Does a force-reload (ctrl+f5 or shift+f5) help?
Nope, that didn't help.

> BTW: you can disable CSP modification at "Settings > Security > Modify existing content security policy (CSP) headers". Be sure to enable "Advanced" "Config Mode" first.
I know I can do that, but I *don't* want to disable CSP modification globally, only for this website.
