### ISSUE TITLE
The icon does not display properly in Safari 15.4（MacOS 12.3.1）

### ISSUE THREAD

**Issue by Aurope** [Tampermonkey/tampermonkey#1490]
(Please fill out the issue template with your details)

## Expected Behavior

![image](https://user-images.githubusercontent.com/51815566/164146708-ee055400-63af-4b52-9c1e-c1a36ed8695f.png)

## Specifications

- Safari: (15.4 (17613.1.17.1.13))
- OS: (i.e. MacOS 12.3.1)

**Comment by derjanb** [comment]
Duplicate of #1420

**Comment by Aurope** [comment]
GOT IT, Plz delete the issue, THX!!!!

**Comment by Aurope** [comment]
Could you please delete this issue(https://github.com/Tampermonkey/tampermonkey/issues/1490 <https://github.com/Tampermonkey/tampermonkey/issues/1490>).
Thanks a lot!

Regards,
Aurope
