### ISSUE TITLE
为什么我的Tampermonkey下载了无法打开？

### ISSUE THREAD

**Issue by asjdnbajskdn** [Tampermonkey/tampermonkey#1492]
一直在转圈圈无法打开，还显示内部出现了错误

**Comment by derjanb** [comment]
Can you please attach a screensot?

**Comment by dotabillie** [comment]
![屏幕截图 2022-05-30 224004](https://user-images.githubusercontent.com/86512760/171015714-f1be7fc6-84b7-4b96-aa4a-aefbdb3c0628.png)
same question, keep loading when click the extention icon, here's the image

**Comment by derjanb** [comment]
What is your browser and Tampermonkey version?

**Comment by derjanb** [comment]
Duplicate of #1469
