### ISSUE TITLE
Can't enable/disable scripts from popout

### ISSUE THREAD

**Issue by aubymori** [Tampermonkey/tampermonkey#1493]
## Expected Behavior
I should be able to enable/disable scripts from the extension popout.

## Actual Behavior
The enable/disable button does nothing on the popout.

## Specifications

- Firefox: 78.15.0 (ESR)
- TM: 4.16.6160
- OS: Windows 10 LTSC 2019 (1809, build 17763)

**Comment by derjanb** [comment]
Working fine here with FF 63 and FF79 and newer. 
Does the button state toggle? If so, just to be sure, are you reloading the page?

**Comment by aubymori** [comment]
The button state does not toggle. I'll see if any errors get logged in the console when I try to click it.

**Comment by aubymori** [comment]
Yep.
![image](https://user-images.githubusercontent.com/44238627/165871253-74abf41d-9ce7-4c28-8c03-11207d350f32.png)

**Comment by Benur21** [comment]
> Yep. ![image](https://user-images.githubusercontent.com/44238627/165871253-74abf41d-9ce7-4c28-8c03-11207d350f32.png)

You have to reload the page for the toggle to make effect. Until you reload the page nothing is supposed to happen.
Are you sure this error log comes from the extension?

**Comment by aubymori** [comment]
Yes, I'm sure. That error is from the inspector on the extension from about:debugging.

**Comment by Mishasama** [comment]
Same here on Chrome 101.0.4951.67

**Comment by derjanb** [comment]
Closing in favor of #1544
