### ISSUE TITLE
Increasing number of installed scripts on local file with every refresh

### ISSUE THREAD

**Issue by mandel99** [Tampermonkey/tampermonkey#1494]
## Expected Behavior
TM display correct number of installed scripts

## Actual Behavior
TM increasing number of installed scripts on every refresh when script running on local file.
![increase](https://user-images.githubusercontent.com/4213037/165168235-005447db-d3aa-4e25-9a50-5f35d98c2410.png)

## Specifications

- Firefox: (99.0.1 (64 bit))
- TM: (4.16.6160, 4.17.6161)
- OS: (Windows 10 19043.1645)

## Script

```
// ==UserScript==
// @name         Script count on local file
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  TM script count test on local file after every refresh!
// @author       Me
// @match        file:///C:/hello.html
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';
    document.getElementById("hello").innerText += " INCREASING after every refresh";
    setTimeout(function() { location.reload(); },3000);
})();
```
[hello.zip](https://github.com/Tampermonkey/tampermonkey/files/8557656/hello.zip)

**Comment by derjanb** [comment]
Should be fixed at 4.18.6163 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
