### ISSUE TITLE
Can't insert modified javascript and inconsistent behavior between browsers

### ISSUE THREAD

**Issue by ifuchs** [Tampermonkey/tampermonkey#1499]
I have the following script which is meant to test changing a script from a webpage:

```
// ==UserScript==
// @name        Test
// @match       http://192.168.3.21/
// @description TEST
// @version     1
// @grant       GM_xmlhttpRequest
// @run-at      document-start
// ==/UserScript==

function addScript(text) {
    text = text.replace(/Normal/g, "Abnormal");
    var newScript = document.createElement('script');
    newScript.type = "text/javascript";
    newScript.textContent = text;
    var head = document.getElementsByTagName('head')[0];
    head.appendChild(newScript);
}

window.addEventListener('beforescriptexecute', function(e) {
    var src = e.target.src;
    if (src.search(/system_data\.js/) != -1) {
        e.preventDefault();
        e.stopPropagation();
        GM_xmlhttpRequest({
            method: "GET",
            url: e.target.src,
            onload: function(response) {
                addScript(response.responseText);
            }

        });
    }
});
```
This test userscript is intended to change the word Normal to Abnormal in system_data.js. If I add an alert I can see that the script is triggered ; however, only on Firefox is the function called (not on Chrome or iOS). Also, even on FF, a modifed system_data.js does not appear to be inserted and the page stops rendering halfway through.
Is there a way to do this on any browser? Is it to be expected that the window.addEventListener works on FF and not elsewhere?

**Comment by derjanb** [comment]
`beforescriptexecute` is a non-standard event only implemented by Firefox[1].

Please check https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595 for instant script injection.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Element/beforescriptexecute_event

**Comment by ifuchs** [comment]
OK thank. That explains why the function is not called in other than FF. After looking at #211 I remain unclear whether this can be made to work and why, even in FF, the modified .js is not working. Perhaps there is a more appropriate forum for these sorts of noob problems.
