### ISSUE TITLE
Use Emojis as icons

### ISSUE THREAD

**Issue by sjehuda** [Tampermonkey/tampermonkey#1500]
[This](https://www.flaticon.com/free-icon/robe_2520932) is the `@icon` I've selected for [BlackBelt](https://openuserjs.org/scripts/sjehuda/Black_Belt). Though, originally, I wanted to have 🥋 (Martial Arts Uniform) as icon.

1. As all unicode chars, these icons are scalable.
2. Script authors wouldn't need to think about copyright concerns.
3. The emoji chars index is easily accessible in a matter of seconds.
4. This is easier than converting an image to base64 or making a one-line svg string `data:image/svg+xml;charset=UTF-8,<svg>...</svg>`

One might ask, why doing so when you can simply place an icon inside `@name`.
I'd answer, because it'll harden the sorting (by name) mechanism.

Also posted at https://github.com/greasemonkey/greasemonkey/issues/3140

**Comment by sjehuda** [comment]
Solved with `data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>` Source https://css-tricks.com/emoji-as-a-favicon/

**Comment by ppo** [comment]
Easy copy of solution in https://github.com/Tampermonkey/tampermonkey/issues/1500#issuecomment-1124408329

```
data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>
```
