### ISSUE TITLE
GM_addElement cannot set ID

### ISSUE THREAD

**Issue by ChristopherTheBoss** [Tampermonkey/tampermonkey#1505]
## Script

```
let sidebar = document.getElementById('sidebar');
let avatar = 'avatar.jpg';
GM_addElement(sidebar, 'img', {
	src : avatar,
	id : 'avatar'
});
```

## Expected Behavior

The new element should have the specified ID

```
<div id="sidebar">
	<img src="avatar.jpg" id="avatar">
</div>
```

## Actual Behavior

The new element has a random string as its ID

```
<div id="sidebar">
	<img src="avatar.jpg" id="1.f3riqmunf3">
</div>
```

## Specifications

- Edge: 101.0.1210.39
- TM: 4.17.6161
- OS: Windows 10

**Comment by Skeeve** [comment]
FYI: It's working for me now, but a browser restart wasn't sufficient on my Mac. I had to log off as well.

Thanks for the fast help @derjanb
