### ISSUE TITLE
What is TamperMonkey useful to? Should I uninstall TM?

### ISSUE THREAD

**Issue by MichelMerlin** [Tampermonkey/tampermonkey#1510]
(Please fill out the issue template with your details)

## Expected Behavior
Just remembering installing TM was part of components necessary for another app install. So what I expect is TM remaining silent and never coming in the way

## Actual Behavior
At each of the Chrome Relaunch, TM displays a large page, and now asks for money, while NOT telling who is requesting what, in order to improve what, etc.
In the past years I asked a coulpe questions, never got a bit of a beginning of an answer.
So my best choice maybe to uninstall TM and, if TM is useful or required, sure an app will ask me to install it
Note: I have written a lot of large sci-eng programs over decades with always aim at high perfs, HIGH RELIABILITY hence high friendliness to all users incl the less-instructed, large domain of validity. So I now usually don't spend too much time in programming or setting up programs, I expect them to work at least partially as well as the programs I wrote.
Versailles, Mon 16 May 2022 16:07:45 +0200

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
> Should I uninstall TM?

If you don't know what Tampermonkey is then you should uninstall it. This is valid for all extension that you don't use (anymore).

> Just remembering installing TM was part of components necessary for another app install. o what I expect is TM remaining silent and never coming in the way.

I don't work with anyone. So the app distributor should have told you what Tampermonkey is and why they installed it in your browser.

**Comment by MichelMerlin** [comment]
"the app distributor" probably told me, but this was long ago.
My apologies if my wording (or my poor English) hurt or disturbed you, what I am looking for is solution, not disturbing, so I will, as said, uninstall TM next time it comes in the way, not excluding reinstalling it if requested again by an app.
Thanks anyway.
Versailles, Mon 23 May 2022 22:47:20 +0200
