### ISSUE TITLE
Add `.webp` to the default download whitelist

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#1511]
In TM [3.12.4868](https://www.tampermonkey.net/changelog.php?ext=dhdg&show=gcal&more=true#:~:text=3.12.4868,default%20download%20whitelist) `.webm` (audio/video format) was added to the default download whitelist.
For reference, here is the current default download whitelist:
![2022-05-17_161529](https://user-images.githubusercontent.com/723651/168821909-b1187834-1a9d-4464-be20-c05c997ec391.jpg)

My suggestion is to also include `.webp` (image format) in the default download whitelist.
It would go in the `/\.(ico|gif|png|jpe?g)/` row, together with the other image file extensions.

[WebP](https://en.wikipedia.org/wiki/WebP), as a derivative of the [VP8](https://en.wikipedia.org/wiki/VP8) video format, is a sister project to the [WebM](https://en.wikipedia.org/wiki/WebM). 
It's a format used by many sites, e.g. Instagram and Facebook.

Thank you.

PS. Using latest Tampermonkey beta 4.17.6161 in Chrome 101, Firefox 100, with win 11 x64.

**Comment by derjanb** [comment]
Fixed at 4.18.6164 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by darkred** [comment]
Thank you for adding this.
