### ISSUE TITLE
cant run userscript (Android-Dolphin)

### ISSUE THREAD

**Issue by feiercrack** [Tampermonkey/tampermonkey#1512]
## Expected Behavior
working scripts on android mobile

## Actual Behavior
doesnt work

## Specifications

- Dolphin V12.2.9
- OS: Android 11
- Smartfon: Samsung A21s

## Script
https://greasyfork.org/en/scripts/425414-violent-coords/code

i am currently use this script on my Win11 Pro x64 PC with several Chrome Browsers, like Chrome, Brave and Egde.
That works fine.
Now i like to have this also on my mobile, but i cant get it to work. Neither Brave nor Google Chrome Browser works with the Tampermonkey script!
So i installed the recommended Dolphin Browser with current tampermonkey extension.
that works a bit better for now, but i get always an error, that tampermonkey could not be runned...

Also, i cant import my with Win11 Browser exported scripts in the Android mobile tampermonkey extension. 
it also give me an error: file // wrong syntax

my scripts file is downloadable here --> https://pixeldrain.com/u/aUTRHadp
its an collection of geocaching tools, which i like to use on my mobile also.

i am very thankful for every help on how to get this to run finally.
many thanks,
cheers^^

**Comment by derjanb** [comment]
Please check [this page](https://www.userscript.zone/howto?env=android) how to run scripts on Android these days.
