### ISSUE TITLE
TamperMonkey set strange cookies

### ISSUE THREAD

**Issue by VarunAgw** [Tampermonkey/tampermonkey#1517]
Please see the attached screenshot.

I see these strange cookies when using TamperMonkey. It's conflicting with one of the website I use.

They starts with TM_ and have extension UUID in the content so I am assuming TM is creating them

## Specifications

- Chrome Dev x64 Latest
- TM:  Beta Latest
- OS: Windows 11 x64 Latest

 
![2022-06-01_194303](https://user-images.githubusercontent.com/4201835/171425777-574059b8-8014-487a-9e38-3bdf2f8c2e0f.png)

**Comment by AlttiRi** [comment]
I thought Chrome does not display `Set-Cookie` header in DevTools.

It does not display `Set-Cookie` header even in Dev version for me.

**Comment by derjanb** [comment]
This happens in instant injection mode only. The cookie is deleted once the scripts are executed.

**Comment by VarunAgw** [comment]
@derjanb Is it possible to disable this? It cause issue with a website I use
