### ISSUE TITLE
Favicons in the "Sites" column are not displayed correctly in dashboard page on Safari

### ISSUE THREAD

**Issue by oscar-c** [Tampermonkey/tampermonkey#1518]
## Expected Behavior
On the dashboard page, favicons show up for the websites that a script will run on in the "Sites" section.

## Actual Behavior
![Favicons missing](https://d.pr/i/y2JvLp+)
The square question mark icon has image url like `blob:https://ui.tampermonkey.net/0c677c7b-8e49-481f-b573-06842d4b59eb`

## Specifications

- Safari 15.5
- TM: v4.17.6162
- OS: macOS Big Sur 11.6.6

## Script

N/A

**Comment by wyq977** [comment]
Not just in site column, same missing in the name column 

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/27303600/213382609-4acc5f64-9241-41be-bb50-36037d1b9947.png">

**Comment by m-thomson** [comment]
I'm seeing the same thing as well. Like the other user said the `src` for the icon is in the form `blob:https://ui.tampermonkey.net/9a0e1e88-4df0-418e-86e4-2a075ccddfed` which appears to download a PNG when pasted into the URL but Safari shows a "The resource was requested insecurely." message when referenced from the "installed userscripts" tab in TM.

<img width="1029" alt="CleanShot 2023-02-08 at 14 06 55@2x" src="https://user-images.githubusercontent.com/5273016/217662122-f13e6232-1af2-4a12-af6c-86931dfd1600.png">

**Comment by derjanb** [comment]
Fixed 4.20.6184 which is currently rolled out. Thanks for reporting.
