### ISSUE TITLE
Erratic scrolling in the Editor on Chrome 102

### ISSUE THREAD

**Issue by jimdonohue** [Tampermonkey/tampermonkey#1519]
## Expected Behavior
Scrolling with a mouse wheel, touchpad, or similar, should be smooth while traversing code in the built-in editor

## Actual Behavior
Continuous scrolling is impossible. The scrolling does not resume unless the physical process of scrolling stops momentarily before starting again. This massively interrupts scrolling operations. Similar behavior with the web browser's middle-click scrolling method (enabled by clicking the middle-button and moving the cursor above or below the clicked anchor location). Grabbing the scrollbar and dragging is not affected (works as expected). Other areas of the TM interface (Settings, Help) are not affected.

## Specifications
TM from Chrome Webstore 4.16.1
Chrome Version 102.0.5005.63 (Official Build) (32-bit)
Windows Version 10.0.17134.706 (64-bit)

## Script
Any script longer than one full screen, regardless of content.

**Comment by derjanb** [comment]
Seems to be an Chrome issue. Have to update CM at the beta version...

https://github.com/codemirror/CodeMirror/issues/6923

**Comment by raszpl** [comment]
This even happens in Devtools/source tab (Vivaldi, probably all chromiums)

**Comment by krystian3w** [comment]
May fixed in Chromium 103 maybe no back in 104+ (e.g. automated tests with any method to scroll by mouse, touch screen/pad and keyboard).
