### ISSUE TITLE
GM_getResourceText() not reading file changes, unless page is reloaded

### ISSUE THREAD

**Issue by sdfdger** [Tampermonkey/tampermonkey#1521]
## Expected Behavior
```
GM_getResourceText("File") > "foo"
File changed to "bar"
GM_getResourceText("File") > "bar"
```
## Actual Behavior
```
GM_getResourceText("File") > "foo"
File changed to "bar"
GM_getResourceText("File") > "foo"
```

The page has to be refreshed for the resource to be reloaded.

## Specifications

- Chromium: 102.0.5005.63 (64-bit)
- TM: 4.16.1
- OS: Windows 10

## Script

```js
// ==UserScript==
// @grant        GM_getResourceText
// @resource   File  file:///C:/path/to/file
// ==/UserScript==
```

**Comment by derjanb** [comment]
This functions as intended. File content is not tracked, but updated on script execution.

**Comment by sdfdger** [comment]
It breaks a main part of my script, is there any workaround?
