### ISSUE TITLE
Beta doesn't work anymore : pagejs missing

### ISSUE THREAD

**Issue by BZHDeveloper** [Tampermonkey/tampermonkey#1525]
No more scripts work

## Expected Behavior

Functional script

## Actual Behavior

`Uncaught (in promise) pagejs missing`

## Specifications

- Chrome : 102.0.5005.61
- TM: 4.18.6163
- OS: Ubuntu (Linux) 22.04

**Comment by derjanb** [comment]
This should work after a browser restart.

**Comment by derjanb** [comment]
Not sure why Chrome does not load the second content script on forced extension updates. 🤷‍♂️
