### ISSUE TITLE
Debug messages in TM 4.18.6163

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1526]
Debug messages have started to appear since TM Beta 4.18.6163:

![image](https://user-images.githubusercontent.com/38133098/173183767-6ac2e12a-a9c6-4940-b97b-40a413c49ae1.png)

Try in https://example.com with one userscript enabled. Disabling the extension gets rid of the console messages.

**Comment by derjanb** [comment]
Duplicate of#1523
