### ISSUE TITLE
Beta breaks twMediaDownloader

### ISSUE THREAD

**Issue by LurkerHub** [Tampermonkey/tampermonkey#1529]
Install http://furyutei.github.io/twMediaDownloader/src/js/main_react.user.js on 4.18.6164
Navigate to https://twitter.com/NASAAmes/status/1536785805515149313

## Expected Behavior

Script should add an "img" button to each image/video

![image](https://user-images.githubusercontent.com/20542915/173704959-40ed4712-7fb9-4cbf-8040-e23fff3f3fc1.png)

## Actual Behavior

Button not added

## Specifications

- Firefox: 102.0b7 (64-bit)
- TM: 4.18.6164
- OS: Windows 10

## Script

http://furyutei.github.io/twMediaDownloader/src/js/main_react.user.js

**Comment by JourneyOver** [comment]
Yea it seems the beta version of tampermonkey has a really big issue right now with the `@match` and `@include` in that it sometimes just doesn't seem to get matched at all, and clicking the tampermonkey icon just shows that there is no scripts installed. Sometimes a refresh fixes it though not always.

**Comment by LurkerHub** [comment]
No, it shows the script as active on the page when I click the icon.

**Comment by LurkerHub** [comment]
Fixed the link
