### ISSUE TITLE
disable notification for Tampermonkey or any other script

### ISSUE THREAD

**Issue by nzarbayezid** [Tampermonkey/tampermonkey#1532]
(Please fill out the issue template with your details)

## Expected Behavior
an option for turning off notification

## Actual Behavior
there is no way that you can turn off notification for tampermonkey or any specific script

[look how annoying this is, every time I use this script this will pop up
](https://imgur.com/a/omuPwxA)
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact the script developer to add a config option to disable notifications or make them less annoying.
