### ISSUE TITLE
disable multi-space warnings gives keyword const is reserved error

### ISSUE THREAD

**Issue by Diskutant** [Tampermonkey/tampermonkey#1533]
I have a eslint config to disable multi-space warnings. Now when editing a script I get an error saying the "eslint: null - Parsing error: The keyword 'const' is reserved"

## Expected Behavior
No error

## Actual Behavior
Gives error "eslint: null - Parsing error: The keyword 'const' is reserved"

## Specifications
- Firefox: 101.0.1
- TM: 4.17.6161
- OS: macOS 12.4

## Script
my full eslint config: 

```js
{
    "rules": {
        "no-multi-spaces": "off"
    }
}
```

Now in the editor the line

```js
const debug = false;
```

will give the eslint error.

**Comment by derjanb** [comment]
You need to either provide a complete ESLint config like shown [here](https://github.com/Tampermonkey/tampermonkey/issues/1417) or disable this rule inline as done [here](https://github.com/Tampermonkey/tampermonkey/issues/1406#issuecomment-1054422851).
