### ISSUE TITLE
differences between GM_getValue and GM.getValue

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1535]
(Please fill out the issue template with your details)

## Expected Behavior
they do the same thing

## Actual Behavior

GM.getValue returns promise
GM_getValue returns a string

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

**Comment by jonnytest1** [comment]
oh also GM.xmlhttpRequest has a lowercase h but GM_xmlHttpRequest is uppercase

**Comment by derjanb** [comment]
This is how they were defined by GM 5 years ago... https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html

To unwrap the promise simply use 
```
const x = await GM.getValue('foo')
```
or keep using the synchronous API.
