### ISSUE TITLE
[Mac] Tempermonkey blocked google link on google search engine

### ISSUE THREAD

**Issue by atlonxp** [Tampermonkey/tampermonkey#1536]
## Expected Behavior
Links on google search engine should be clicked and redirect to the destination

## Actual Behavior
When enable Tempermonkey on Safari, Mac, the links on google.com (and other google.co.xx domains) do not work due to the following errors once I clicked on a link, see the image 

<img width="1142" alt="Screen Shot 2022-06-21 at 03 02 03" src="https://user-images.githubusercontent.com/38250872/174670780-3670f0f0-03f5-4ad6-b56f-4b7bf578bf5d.png">

When disable Tempermonkey in Safari, Mac. All functionalities come back and work properly. It seems TM has blocked somethings

## Specifications

- Safari: Version 15.5 (17613.2.7.1.8)
- TM: 4.17.6162
- OS: MacOS Monterey 12.4 (21F79)

## Script

No script. it is Tempermonkey issue

**Comment by atlonxp** [comment]
That works! Thanks.

**Comment by tandpfun** [comment]
@derjanb I seem to be having this issue as well. I paid for the extension but am disappointed it doesn't work :/
Happy to support the project tho cus it worked like a charm on chrome!

**Comment by okarin001** [comment]
I have the same issue, when I disable this particular extension I can click any search result's link from the `https://www.google.com/` otherwise, I have to manually open it in new tab.

- **Tampermonkey:** Version 4.17.6162
- **Safari:** Version 16.1 (18614.2.9.1.12)
- **macOS:** Version 13.0 (22A380)

**Comment by owah** [comment]
Same issue here, interesting enough it only happens on one of my two MacBooks, on the M1 everything is fine, on the Intel one I can't click on links. Disabling the extension makes it work again on the intel. Both devices are on Safari 16.1

**Comment by derjanb** [comment]
Tampermonkey was updated to 4.20.6184 which is currently rolled out and clicking search links is working fine here. Thanks for reporting.

**Comment by lehrian** [comment]
I am on 4.20.6184 and I am still having the exact same issue as described in the original post.


![Untitled](https://github.com/Tampermonkey/tampermonkey/assets/5253663/c24b1488-dc61-4414-9b54-e4706ecea88e)


**Safari:** Version 16.6 (18615.3.12.11.2)
**TM:** 4.20.6184
**OS:** MacOS Ventura 13.5 (22G74)

**Comment by derjanb** [comment]
Do you have 1Password or other extensions installed?

**Comment by Zekomood** [comment]
> * **:** Version 13.0 (22A3
111

**Comment by derjanb** [comment]
@Zekomood See https://github.com/Tampermonkey/tampermonkey/issues/1836#issuecomment-1767053041

**Comment by Zekomood** [comment]
``
