### ISSUE TITLE
Tampermonkey (.onclick ) event won't work properly

### ISSUE THREAD

**Issue by Chillszz** [Tampermonkey/tampermonkey#1541]
It execute immediately after refreshing the page, the goal is to console.log ("pressed") after pressing the button

```
// ==UserScript==
// @name         testing copy button
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*testing.com/*
// @grant        none
// ==/UserScript==

var copy_button = document.createElement('button');
copy_button.innerText = "Copy Fleet Manager";
copy_button.setAttribute('style','color:black;position:fixed; top:110px; z-index:11;left:730px;');
copy_button.setAttribute('id','but1');

document.body.appendChild(copy_button);
document.querySelector("#but1").onclick = console.log("hello");
````

**Comment by 7nik** [comment]
It's not TM's issue, it's just a wrong code: you call `console.log` and assign its result to `.onclick`.
You must assign a function:
`document.querySelector("#but1").onclick = () => console.log("hello");`
or even better way to this:
```js
function onButtonClick(event) {
  console.log("hello");
}
copy_button.addEventListener("click", onButtonClick);
```

**Comment by Chillszz** [comment]
> It's not TM's issue, it's just a wrong code: you call `console.log` and assign its result to `.onclick`. You must assign a function: `document.querySelector("#but1").onclick = () => console.log("hello");` or even better way to this:
> 
> ```js
> function onButtonClick(event) {
>   console.log("hello");
> }
> copy_button.addEventListener("click", onButtonClick);
> ```

im not familiar with the document.querySelector("#but1").onclick **= () => console.log("hello");** specifically the one that i bolded, would you mind sending a link for the explanation or just explain it here?

**Comment by 7nik** [comment]
You see it in the wrong way. It is `() => console.log("hello")` - arrow function or lambda function. It is mostly a shortening of a regular function:
```js
document.querySelector("#but1").onclick = function() {
  console.log("hello");
}
```
You can read about the arrow functions on the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by derjanb** [comment]
@7nik Thanks.
