### ISSUE TITLE
Sync scripts will popup a tab in firefox every time, it's annoying.

### ISSUE THREAD

**Issue by MisteryMonster** [Tampermonkey/tampermonkey#1547]
(Please fill out the issue template with your details)

## Expected Behavior
Sync scripts should be silence.

## Actual Behavior
When sync is operate, it will popup a tab every time and close it automatically.

## Specifications

- Firefox: 102.0.1
- TM: 4.17.6161
- OS: Windows 10 21H1

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Should be fixed at the latest BETA version. The tab now is opened in background and only focused when something needs to be done (e.g. account selection).

Please test the [BETA version from here](https://www.tampermonkey.net/index.php?browser=firefox)

**Comment by MisteryMonster** [comment]
Oh, When I start Firefox, some time it will popup once `https://login.live.com/oauth20_authorize.srf?response_type=token&client_id=#############&redirect_uri=https%3A%2F%2Fauth.tampermonkey.net%2Foauth.php&state=!!onedrive-#########################&scope=onedrive.appfolder`, after that no more popup.
