### ISSUE TITLE
Why are jQuery statements not accepted in TM *.user.js scripts?

### ISSUE THREAD

**Issue by pstein** [Tampermonkey/tampermonkey#1548]
I installed newest Tampermonkey v4.16.1 on newest Chrome browser on 64bit Windows 10.

Since Tampermonkey claims to be (almost) compatible with Greasemoinkey I tried it out.

I drag & drop a (working (!) Greasemonkey) script with the following first lines onto it

```
// ==UserScript== 
// @name            ChangeLayoutTWC
// @namespace       nsChangeLayoutTWC
// @description     Change Layout TWC
// @match           https://www.thewindowsclub.com/*
// @version         3.6.1
// @grant           GM_addStyle
// @require         http://code.jquery.com/jquery-latest.js
// ==/UserScript== 

$(".site-header").remove();

$("aside").remove();

GM_addStyle("body { width: 1024px !important; font-size: 14px !important; line-height: 14px !important; font-family: Arial !important; }");
```

As you can see nothing extraordinary except that the script uses jQuery statements.
left of all these jquery statement a yellow exclamation mark appears telling the user

eslint: no-undef - '$' is not defined.

Whats wrong?

How can I remove these yellow warnings and get the script working?

**Comment by pstein** [comment]
@7nik:

ok, thank you.
That seems to work.

Can users somehow tell Tampermonkey to AUTOMATICALLY insert this declaration statement at the top of each script?

There should be at least an option in TM settings

**Comment by 7nik** [comment]
In the settings, change Config mode to Advanced. After this, you can edit the userscript template - at the end of settings, edit the New userscript template: ECMAScript 5 field and press Save.

**Comment by derjanb** [comment]
Thanks @7nik 

> Can users somehow tell Tampermonkey to AUTOMATICALLY insert this declaration statement at the top of each script?

`@require`s might add every type of global variables and it is not possible to detect them on script installation/modification.
