### ISSUE TITLE
Search bar replacing entered phrase in script editor

### ISSUE THREAD

**Issue by wojnarw** [Tampermonkey/tampermonkey#1555]
## Expected Behavior
You press CTRL + F, then enter something in search bar, then click Next or Previous and searched phrase is highlighted and screen moved to its position.

## Actual Behavior
Search phrase changes in irrational manner, sometimes I'm sure it copies what you have in clipboard, removing what you entered in the search box and sometimes I have no idea where does the text come (but exists in code). Sometimes it removes what you entered and replaces it with selected text in editor, but sometimes it doesn't do that, even though you have selected text.

## Specifications

- Microsoft Edge
Version 101.0.1210.39 (Official build) (64-bit)
- TM: 4.16.1
- OS: Win 10 Pro 20H2

## Script
N/A

**Comment by jb222** [comment]
I agree the search bar is a bit confusing, especially the auto-paste of selected phrases. 

While we are used to start a search by Cmd+F (Mac) or Ctrl+F (Windows), in the TM editor the command shows the search bar and possibly pastes a selected phrase in the search bar. So the search has not even started yet. 

To start the search, we can click Next, Previous, Cmd+G (Ctrl+G) or press the Return (Enter) key. That last key inserts a line break or even deletes selected code when the search bar was not focused anymore. 

I could do without auto-paste, by copying/pasting myself. Also, if the search bar is permanently visible, Cmd+F (Mac) or Ctrl+F (Windows) can work as one would expect.

**Comment by anonghuser** [comment]
fwiw, search works as i would expect here. it never involves the clipboard, only the current selection, just like browser's built-in search and most any other app i've used

**Comment by wojnarw** [comment]
I didn't notice the same problem anymore, but I changed the browser to Firefox. It was either fixed or browser change helped.

**Comment by derjanb** [comment]
> only the current selection, just like browser's built-in search and most any other app i've used

Yes, that is intended behavior.

> I didn't notice the same problem anymore,

Ok. Please re-open if you encounter this issue again.
