### ISSUE TITLE
左键单击不显示正在运行的脚本

### ISSUE THREAD

**Issue by QQ907450131** [Tampermonkey/tampermonkey#1559]
![20220721184525](https://user-images.githubusercontent.com/73972296/180196044-17095e3d-8126-4722-af86-2ec3ddc83126.png)

左键单击不显示正在运行的脚本 使用的最新的beta版本

**Comment by derjanb** [comment]
I have no idea what issue is. Sorry. Can you explain more in detail please? Thanks.

**Comment by derjanb** [comment]
Also please add your browser vendor and version.

**Comment by 7nik** [comment]
It looks like he means that the popup menu doesn't show the running scripts. Note the icon says there are 16 running scripts. But the counter may be out of sync.

**Comment by QQ907450131** [comment]
![2345截图20220722102628](https://user-images.githubusercontent.com/73972296/180349352-d8e06272-020c-4a05-b1e1-50bebed69507.png)
这是目前使用的电脑系统和浏览器版本号

**Comment by QQ907450131** [comment]
![2345截图20220722102751](https://user-images.githubusercontent.com/73972296/180349484-b1ea9fa6-1d5c-41d6-8487-d1d412be0c13.png)
不显示单击正在运行的脚本

**Comment by Akkocy** [comment]
i have this problem too.

**Comment by Akkocy** [comment]
> 我不知道是什么问题。对不起。你能更详细地解释一下吗？谢谢。

I have this problem too.When the webpage is loading（a flash), it works correctly, but after loading is complete，the popup menu doesn't show the running scripts.

**Comment by Akkocy** [comment]
> I have no idea what issue is. Sorry. Can you explain more in detail please? Thanks.

I have this problem too.When the webpage is loading（a flash), it works correctly, but after loading is complete，the popup menu doesn't show the running scripts.

**Comment by derjanb** [comment]
Closing in favor of #1607
