### ISSUE TITLE
@match incorrectly count query string in

### ISSUE THREAD

**Issue by magicdawn** [Tampermonkey/tampermonkey#1560]
I have a script that expect to run only in the homepage of somesite, root path `/`

```
@match *://some-site.com/
```

## Expected Behavior

`@match *://some-site.com/` matches `some-site.com` & `some-site.com/` & `some-site.com/?abc`

## Actual Behavior

`@match *://some-site.com/` matches `some-site.com` 
but not `some-site.com/?abc`, `some-site.com/` can not be tested, chrome will trim last `/`

## Specifications

- Chromium: 103.0.5060.134 (x86_64)
- TM: 4.16.1
- OS: MacOS 12.5

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @match *://mywebsite.com/
// ==/UserScript==
```

the script: https://greasyfork.org/en/scripts/443530-bilibili-app-recommend
target site `@match *://www.bilibili.com/`

![image](https://user-images.githubusercontent.com/4067115/181506653-1027941e-4bf7-4892-9376-e5728c317807.png)

![image](https://user-images.githubusercontent.com/4067115/181506282-033cd1de-994c-4fd3-b20c-bf061885dd54.png)

---------

- AND the violentmonkey extension works as expected.
- just can not find a example that matches root path `/` on https://developer.chrome.com/docs/extensions/mv3/match_patterns/ , maybe my usage is incorrect.

**Comment by 7nik** [comment]
I don't think it is correct behavior - a server can take into account the value of the query string and return very different results.

[MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#path) and [Chrome docs](https://developer.chrome.com/docs/extensions/mv2/match_patterns/) say that the path part of `@match`  is matched against path + query parts of an URL, though it isn't said explicitly in Chrome docs.
Also, the MDN docs mention the usage of `?*` to match against the value of the query string.

Talking about VM, [their docs](https://violentmonkey.github.io/api/matching/) say `match patterns always ignore query string and hash`.

So, your solution is:
```js
// @match        https://example.com
// @match        https://example.com/?*
```

**Comment by derjanb** [comment]
@7nik as fast as always, so I deleted my half done post. :-)

I agree that the query part should be taken into account. The only thing I'd like to add is that MDN **requires** `/?*` to match query parts while Tampmonkey also matches it with `/*`.

I may need to change this, but I'd like to investigate the impact of this change first...

**Comment by magicdawn** [comment]
there is a stackoverflow answer that also says that query does not count in 🤦 

https://stackoverflow.com/a/20463282

maybe add a explicit document?

**Comment by derjanb** [comment]
Current behavior will be kept. `?*` only is needed to separate path from query string.
