### ISSUE TITLE
GM_download FilenameConflictAction

### ISSUE THREAD

**Issue by 86482t** [Tampermonkey/tampermonkey#1568]
Is there a way to specify what to do when the file downloaded already exists like with [firefox extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/FilenameConflictAction)? Basically, I would like to change it so that when the file already exists it gets replaced instead of adding (1) to the filename.

- Firefox Developer Edition 104.0b5
- TM v4.17.6161
- Windows 11 22000.795

**Comment by derjanb** [comment]
Should be fixed at 4.18.6167 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

It is now possible to add `conflictAction` to `GM_download.details`, but it works only in browser API download mode.

Possible values are [defined here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/FilenameConflictAction).
