### ISSUE TITLE
EXTENSION TEMPLATE

### ISSUE THREAD

**Issue by cihansayin** [Tampermonkey/tampermonkey#1570]
I add a plugin to the software, the plugin works fine. My question is: I want to be able to copy the plugin with my own settings and add it to different browsers as .zip output. When I take the file from the chrome I use and add it to a different chrome with my plugin settings, the plugin works, but the codes I added do not come. How can I achieve this? I would be really grateful if you could help.

**Comment by derjanb** [comment]
Please use Extensions Options > Utilities > Import and Export to achieve this. Make also sure "Include Tampermonkey settings" is enabled at the top.
