### ISSUE TITLE
Add file extensions to default Download allowlist?

### ISSUE THREAD

**Issue by perpil** [Tampermonkey/tampermonkey#1576]
I've successfully added file extensions to the allowlist for Downloads in settings and that works fine.  Is there a process to get an extension added to the defaults? In my case, I'd like `.yml` added to the defaults.

I tried searching for a good allowlist for non-malicious files and found a [blocklist](https://www.lifewire.com/list-of-executable-file-extensions-2626061) but not a great allowlist.

There are probably a few others worth adding, these are a few off the top of my head:
```
.pdf
.ttf
.otf
.woff
.rss
.svg
```

**Comment by perpil** [comment]
Thanks @derjanb Looks like you added all but `.yml` which was the original ask, was that intentional or was that missed because it was in the text.

**Comment by derjanb** [comment]
🙈😂

**Comment by derjanb** [comment]
Should be fixed at 4.19.6176 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by perpil** [comment]
Thank you! I'll test this this weekend and loop back.

**Comment by perpil** [comment]
Thank you again! I tested the beta in both FF for Mac 107.0.1 and Chrome for Mac 108.0.5359.94
I saw this in the whitelist `/\.(txt|pdf|yml)$/` and confirmed using GM_Download with the `.yml` extension worked without error in both browsers. :shipit:  Feel free to resolve when the release is pushed.
