### ISSUE TITLE
Emergency help for the Chinese garbled in the storage from each script

### ISSUE THREAD

**Issue by lyscop** [Tampermonkey/tampermonkey#1581]
(Please fill out the issue template with your details)

## Expected Behavior
It was normal yesterday that I got the Chinese data from the different script storage to show on the Web.

## Actual Behavior
No matter whether the Chinese data on the Web or storage is garbled, and I test different browsers like Edge or different PC which import the backup, the result is the same.

## Specifications

- Chrome 104.0.5112.102

the storage from the script https://greasyfork.org/scripts/393396
![image](https://user-images.githubusercontent.com/63564691/186474881-cb13173a-2964-4542-aefb-12a4502c7db1.png)

the result show on the Web which data is from the storage
![image](https://user-images.githubusercontent.com/63564691/186474982-83073093-02bf-49d5-8e21-0abf02121db9.png)

**Comment by derjanb** [comment]
Yes, the keyword blacklist is definitely broken. However I can not reproduce the issue. I can add via script, save/edit via storage editor keywords and everything is working fine. I can also import and export the script with Chinese keywords.

Can you please post some steps on how to reproduce the issue?

**Comment by lyscop** [comment]
Thank you for your attention.

Yesterday, my computer Ram overflowed when I watch a movie and using Chrome at the same time. Tampermonkey is broken.
I re-install it immediately, so the Chinese form the storage of each script comes out garbled.
Maybe my computer is something wrong with the text backup file.

So I try to copy the different time backup text files to the Server and import it, and there is no change.
The storage in the backup file seems encryption, I don't find any Chinese storage in it.
Here is one of the backup files from my PC

The screen script is from the script **GreasyFork Helper**(GreasyFork网站助手)
https://drive.google.com/file/d/12uS9VUywv64NtdsdS6Nff0IXdAbfraTQ/view?usp=sharing.
