### ISSUE TITLE
Allow the `ESC` key to close the dialog of `Show backups` (`Cloud` section)

### ISSUE THREAD

**Issue by contribucious** [Tampermonkey/tampermonkey#1584]
Hello, :wave:

This is just another small feature request.

_Thank you in advance! 🙂_
&nbsp;

## Steps to reproduce
1. Open the Tampermonkey dashboard.
2. Go to the `Utilities` tab > `Cloud` section > click on the `Show backups` button.
3. Try to press `ESC`.

## _Desired_ behavior
As a feature request, I would like the dialog to close.

:arrow_right_hook: In the same way that the tab of a userscript is closable.
:arrow_right_hook: And like the `Help` tab suggests too: `Esc` `back or close`.

## Others

<details>
<summary>Display it …</summary>

### Related bonus
- Allow to close the dialog also when a click outside of it is performed. Like on many websites.

### Other possible improvement(s)
- _A :heavy_multiplication_x: icon at the top right of this dialog._
Since this list is obviously not limited in height (i.e. no use of a box with its own scrollbar), when the latter becomes long, _although_ clicking on the `Show backups` button will go by default directly to the bottom where the `Cancel` button is (useful), if you scroll to go up to see all your backups, once at the top you expect to be able to click on an "X" at the top right to close this dialog, not instead having to scroll all the way down (where you came from) just to click `Cancel`. :relaxed:
</details>
&nbsp;

___
[_Environment_] &nbsp;**TM:** 4.17.6161 | **Firefox:** 103.0.2 | **OS:** Windows 10 Pro 21H2 (OS Build 19044.1889)

**Comment by derjanb** [comment]
Should be fixed at 4.18.6167 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

**Comment by contribucious** [comment]
Confirmed (`ESC` key now possible + close icon added :heavy_multiplication_x:).
Tested with the beta version 4.18.6168, in Firefox 104.0.2.

Thank you Jan! 🙂
