### ISSUE TITLE
Typo in donate page

### ISSUE THREAD

**Issue by jupiter104** [Tampermonkey/tampermonkey#1586]
![1399](https://user-images.githubusercontent.com/24752210/187013015-8c6213da-a4a3-456f-84d8-a54b4e16cb06.jpg)

This popup recently showed up while using Tampermonkey extension in Google Chrome.
It should say "a reasonable amount" not "an reasonable amount".

**Comment by derjanb** [comment]
Fixed. Thanks a lot.
