### ISSUE TITLE
Can't import or export script from cloud/local on firefox nightly android

### ISSUE THREAD

**Issue by Rosabis** [Tampermonkey/tampermonkey#1588]
(Please fill out the issue template with your details)

## Expected Behavior
Import or export script from local/cloud correctly.

## Actual Behavior
Browser will freeze after do this.

## Specifications

- Firefox: (i.e. 64.0.3282.140)106.0a1
- TM: (i.e. 4.5.5648)4.17.6161
- OS: (i.e. MacOS 10.13.4)Android 7.1

**Comment by derjanb** [comment]
Close in favor of #1126
