### ISSUE TITLE
Inject script functions in to current console context

### ISSUE THREAD

**Issue by Aphexus** [Tampermonkey/tampermonkey#1595]
When one is editing a script one can open a console in the same window. Usually when I have a script active on some web page I open the console which I can then execute commands and such that are loaded by the web page.

First, to be able to call functions within the local context I seem to have to jump through these hoops:

// @grant        unsafeWindow

...

unsafeWindow.indirectJS = function(js) { return eval(js); }

then window.indirectJS("<js code>") will execute the javascript code within the script context. This allows me to execute my defined functions.

This is a real pain but seems to work. This, of course, works only for a page that has a TM script on it but at least I can mess with the script(hopefully some genius won't somehow disable this functionality to "protect" us plebs from "hurting" ourselves).

But what would be very useful is if I could access my script functions directly from the console in the tampermonkey script window using similar functionality(or better). I realize that the script isn't going to be ran correctly since it expects to be executed in the context of the web page it is suppose to be active on but this doesn't mean I shouldn't be able to access the functions for testing purposes within a console that do not use page specific context. Currently I have to use the console and the above functionality on the web page and switch back and forth between the editor and web page and refresh when I make any changes. This is not the end of the world, of course, but ideally there would be a better way so that debugging functions in a script would be much quicker.

**Comment by derjanb** [comment]
Simply add a `debugger:` statement to the end of the script, open den dev tools  and you can access and execute all functions of the local userscript context.

**Comment by Aphexus** [comment]
I think you mean debugger;
