### ISSUE TITLE
jquery issues (allow for conditional requirements)

### ISSUE THREAD

**Issue by Aphexus** [Tampermonkey/tampermonkey#1597]
My script requires jquery, the page requires jquery... there is a conflict in versioning causing one or the other to fail. Allow for one to require dynamically.

This is the issue:

// @require      https://code.jquery.com/jquery-3.2.1.slim.min.js

e.g., (just an example of an idea on how to deal with it)

// @dynamicrequire[if (!jquery)]      https://code.jquery.com/jquery-3.2.1.slim.min.js

loads only if jquery is not defined. The idea is not to require me to use some fragile method to load a local jquery version to avoid conflicts. A better method might be
// @dynamicrequire[if (!jquery)][mjquery] https://code.jquery.com/jquery-3.2.1.slim.min.js

so that mjquery is a variable representing the script where all functionality can be accessed from it.

**Comment by 7nik** [comment]
Why do they conflict? Userscript is run in a sandbox that should allow you to run whatever libs you want without exposing them to the page.

**Comment by derjanb** [comment]
You can tell jQuery to restore the original page instance by adding something like the following line after jQuery was initialized. 

```javascript
const my$ = jQuery.noConflict(true);
```
