### ISSUE TITLE
Tampermonkey won't backup files after closing

### ISSUE THREAD

**Issue by m3k1e** [Tampermonkey/tampermonkey#1599]
Hello there, I was trying to browse the internet using Chrome but since my browser is very slow, I have to end the entire Chrome program all because of so many tabs on my 14gb ram (Yes, I have 30-70 tabs because I'm autistic. Please suggest me an extension so I can stop having so many tabs open). I tried fixing in the FAQs and none of them worked. Please show me a video on how to get rid of the warning pop up because there's literally zero results relating to that on YouTube and images spoke louder than words.
![chrome_ajExnXk1og](https://user-images.githubusercontent.com/41316133/192943170-e6cd0c9f-7ca5-49c1-835b-5d5af47754f9.png)

## Expected Behavior
Detected inconsistencies that indicate that your browser wiped the extension database

## Actual Behavior
Restarting the browser wiped the userscripts.
"Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab)."

## Specifications

- Chromium: Chrome 105
- TM: 4.16.1
- OS: Windows 10

## Script

GoodTwitter2, old Google search layout, I don't remember something.

**Comment by derjanb** [comment]
Looks like your browser profile is broken and extension data is not kept anymore. Can you please try with a new temporary profile?
