### ISSUE TITLE
Script editor shows "NL" character instead of rendering actual new line (v4.18.0)

### ISSUE THREAD

**Issue by scholtzm** [Tampermonkey/tampermonkey#1601]
## Expected Behavior
Don't show "NL", just render new line

## Actual Behavior
Shows red "NL" char

## Specifications
- Firefox: 105.0.1
- TM: 4.18.0
- OS: Win 10

## Screenshot
![obrázok](https://user-images.githubusercontent.com/2640934/193369692-84499969-3700-45b3-9154-4895620c0fa7.png)

**Comment by derjanb** [comment]
Can not reproduce. Can you please post some step how to get to this point?

**Comment by scholtzm** [comment]
More info sent by email.

**Comment by derjanb** [comment]
You script mixes multiple types of line endings. The start is "LF" (0x0a) only, while the rest uses "CRLF" (0x0d 0x0a).

This change (line ending detection) was introduced to preserve existing line breaks on edit. -> #1209 
I tend to not revert this since mixing line endings is rather uncommon.
