### ISSUE TITLE
Script update is not working

### ISSUE THREAD

**Issue by Sandor-Helper** [Tampermonkey/tampermonkey#1604]
(Please fill out the issue template with your details)

## Expected Behavior
Auto update installed script

## Actual Behavior
Installed script doesn't update in auto mode, nor in manual.

## Specifications

- FF (91.1.0esr x86)
- TM: (v4.18.0)
- OS: (Win7 x86)

## Script
https://greasyfork.org/scripts/431691

When installed script is updated Tampermonkey doesn't see it. Nor by auto scheduled check, nor by manual check.
No matter "Update switched off scripts" is set to On or Off.

I'm using only one script and it is enabled always.
My browser is Mozilla Firefox, but I heard that same behavior appears in Chrome.

**Comment by derjanb** [comment]
Update depends on browser caching. Simply clear "Cached Web Content" and the update should be visible instantly.
