### ISSUE TITLE
Is there way to modify html code before browser processes it?

### ISSUE THREAD

**Issue by rain1** [Tampermonkey/tampermonkey#1608]
Hi!

I want to remove `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` from http page before Firefox parses it and starts to enforce it. I have tried `// @run-at       document-start` but seems like by that time browser is already enforing this meta tag.

Is there any other ways of removing it?

**Comment by derjanb** [comment]
No, that requires its own extension.
