### ISSUE TITLE
`@run-at document-end` should run after the page's DOMContentLoaded listeners

### ISSUE THREAD

**Issue by ReclusiveRychuRychu** [Tampermonkey/tampermonkey#1615]
(Please fill out the issue template with your details)

## Expected Behavior
Using the "@run-at  document-end" header causes the script to be injected after the DOMContentLoaded event was dispatched.

## Actual Behavior
Using the "@run-at document-end" causes the script to not function at all.

## Specifications

- Chromium: (106.0.5249.103 (Official Build) (64-bit))

## Script

```js
// ==UserScript==
// @name         WaniKani - Full Progress Bar
// @namespace    http://tampermonkey.net/
// @version      1.2.1
// @description  Swap Kanji passed to Full Kanji Completed and Vocab Completed
// @author       Rychu (based off of Gorbit99's Better Progress Bar)
// @include      /^https://(www|preview).wanikani.com/(dashboard)?$/
// @icon         https://www.google.com/s2/favicons?domain=wanikani.com
// @grant        none
// @run-at       document-end
// @license      MIT

// ==/UserScript==

let kdElementChild1 = [];
let kdElementChild2 = [];
let vdElementChild1 = [];
let vdElementChild2 = [];

//Do these changes first, then load data
(function() {
    //Clone Progress Bar
    let k = document.querySelector(".progress-bar");
    let parentK = k.parentNode;
    let parentPK = parentK.parentNode;
    let kanjiDiv = parentK.cloneNode(true);
    //Change Kanji Div IDs
    kanjiDiv.className = 'kanji-bar';
    kanjiDiv.title = "Kanji Progress";
    kanjiDiv.id = 'kanji-bar-id';
    let kdElement = kanjiDiv.getElementsByClassName('progress-bar')[0];
    kdElement.id = "kanji-progress-bar-id";
    kdElement.style.backgroundColor = "#b1b1b1";
    kdElementChild1 = kdElement.getElementsByClassName('progress-bar__progress')[0];
    kdElementChild1.id = "kanji-actualprogress-id";
    kdElementChild2 = kdElement.getElementsByClassName('progress-bar__label')[0];
    kdElementChild2.id = "kanji-label-id";
    //Change Vocab Div IDs
    parentK.className = 'vocab-bar';
    parentK.title = "Vocab Progress";
    //Place New Progress Bar
    parentPK.insertBefore(kanjiDiv,parentK);

    //Modify New Progress Bar
    let v = document.querySelector(".vocab-bar");
    v.style.padding = "10px 0px 0px 0px";
    //Change Vocab Div IDs
    let vdElement = v.getElementsByClassName('progress-bar')[0];
    vdElement.id = "vocab-progress-bar-id";
    vdElement.style.backgroundColor = "#b1b1b1";
    vdElementChild1 = vdElement.getElementsByClassName('progress-bar__progress')[0];
    vdElementChild1.id = "vocab-actualprogress-id";
    vdElementChild1.style.backgroundColor = "#aa00ff";
    vdElementChild2 = vdElement.getElementsByClassName('progress-bar__label')[0];
    vdElementChild2.id = "vocab-label-id"
    Promise.resolve().then(ready_wkof);
})();

function ready_wkof() {
    'use strict';

    if (!window.wkof) {
        alert('Full Progress Bar requires Wanikani Open Framework.\nYou will now be forwarded to installation instructions.');
        window.location.href = 'https://community.wanikani.com/t/instructions-installing-wanikani-open-framework/28549';
        return;
    }
    wkof.include("ItemData");

    wkof.ready("ItemData").then(query_kanji);

};

function query_kanji() {
    wkof.ItemData.get_items({
        wk_items: {
            options: {assignments: true},
            filters: {item_type: ["kan"], level: '+0',}
        }
    }).then(handle_kanji);
}

function handle_kanji(items) {
    let kanji = items.filter(item => item.assignments !== undefined)
        .map(item =>
            item.assignments.passed_at !== null
                ? 1
                : Math.min(item.assignments.srs_stage, 1));

    if (kanji.length < 0) {
        return 0;
    }

    let kanjimax = items.length;
    let kanjiactual = kanji.reduce((sum, x) => sum + x, 0);
    let kanjiLevelUp = Math.ceil((kanjimax *90)/ 100);

    kdElementChild1.style.width = `${kanjiactual / kanjimax * 100}%`;
    kdElementChild2.innerText = `${kanjiactual} of ${kanjimax} Kanji Complete (${kanjiLevelUp})`;
    Promise.resolve().then(query_vocab);
}

function query_vocab() {
    wkof.ItemData.get_items({
        wk_items: {
            options: {assignments: true},
            filters: {item_type: ["voc"], level: '+0',}
        }
    }).then(handle_vocab);
}

function handle_vocab(items) {
    let vocab = items.filter(item => item.assignments !== undefined)
        .map(item =>
            item.assignments.passed_at !== null
                ? 1
                : Math.min(item.assignments.srs_stage, 1));
    if (vocab.length < 0) {
        return 0;
    }
    let vocabmax = items.length;
    let vocabactual = vocab.reduce((sum, x) => sum + x, 0);

    vdElementChild1.style.width = `${vocabactual / vocabmax * 100}%`;
    vdElementChild2.innerText = `${vocabactual} of ${vocabmax} Vocab Complete`;
}
```

I assume this is a result of TamperMonkey 4.18.0 update, it mentions:
"Remove document.addEventListener('DOMContentLoaded', ...) delayed event dispatching for document-start scripts executed later than the event"

**Comment by knakamura8** [comment]
Same, is there any way to revert this?

**Comment by derjanb** [comment]
> I assume this is a result of TamperMonkey 4.18.0 update, it mentions:
"Remove document.addEventListener('DOMContentLoaded', ...) delayed event dispatching for document-start scripts executed later than the event"

No, since the example code doesn't use `document.addEventListener`.

**Comment by derjanb** [comment]
Please explain the issue a little bit more in detail.

What is the `document.readyState` when the script is executed? What is it expected to be?

Does `document-idle` work?

What does the console print with an additionally installed script that logs `DOMContentLoaded` and `readystatechange` events?

**Comment by ReclusiveRychuRychu** [comment]
Looks like it may not be the @run-at header. My command line reads: 

"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')"

in regards to "let parentK = k.parentNode;"

Normally I'd say "Yup that's my codes issue" however it worked flawlessly until the Tampermonkey update.

So what gives? I should preface that I am not an expert in JS, this is the first script I made and it is far from clean. So if you have any suggestions I'm all ears.

**Comment by ReclusiveRychuRychu** [comment]
I'll also add that if I refresh the page enough times it will work as intended, and not have any issue afterwards. So something is loading slower after the update and it's unable to grab the parent node before something is cached maybe?

**Comment by derjanb** [comment]
Tampermonkey now might inject the scripts a little bit faster. I've tested it and as I suggested

`// @run-at document-idle`

works fine.

**Comment by ReclusiveRychuRychu** [comment]
Okay, I changed it to document-idle and it now loads fine the first time opening chrome, but then if I refresh the page it gets the same parentNode error, and then it's completely random if subsequent refreshes error or don't error.

Thank you for your help! I hope I can find a stable solution

**Comment by derjanb** [comment]
This means the element is created by the page later than `DOMContentLoaded` and you have to use `waitForKeyElements` or something similar. https://gist.github.com/BrockA/2625891

**Comment by derjanb** [comment]
Fixed at 4.18.1

**Comment by ReclusiveRychuRychu** [comment]
It was never fixed. Still behaves the same. Just saying.

**Comment by ReclusiveRychuRychu** [comment]
I was wrong, it appears to be fixed! Thank you thank you!
