### ISSUE TITLE
Problem with the new update

### ISSUE THREAD

**Issue by yasinULLAH** [Tampermonkey/tampermonkey#1620]
There is a problem with either the new chrome or tampermonkey update because some script won't load sometimes. Please fix this issue.... It often happen whenever we reload a page multiple times.... Than after exactly one or two times of reloading the script of tampermonkey stops working

**Comment by roger21** [comment]
you are probably in this case #1617

try: disable tm + restart chrome + enable tm

and if it is not working try: backup script + option, remove tm, reinstall tm, re-import backup as explained in the #1617

**Comment by keenhauberk** [comment]
me 2, no script is running properly since I got the update yesterday evening.
But I need it, I'm writing on my own script at moment and it is very sad because the javascript execution stops not on my userscript but in the page before for which I'm writing the script. So I have noch chance to make anything

**Comment by keenhauberk** [comment]
the solution with deactivating tm and activating it after restart chrome works for me.
Thanks roger21

**Comment by yasinULLAH** [comment]
I think the problem was with the amount of script used per page specifically >4 I tried disabling some of them and 3 scripts per page works properly.. Also I need to mention that in my page I am using iframes with means more scripts on one page....

**Comment by AetheralMeowstic** [comment]
This doesn't work for me, enabling (deprecated) synchronous mutation events in chrome://flags/ doe.n't work for me, using Tampermonkey Beta doesn't work for me...

Tampermonkey is completely broken in every single conceivable way with literally nothing anyone suggests fixing it for me. 

Latest version of Kiwi Browser, Android

**Comment by derjanb** [comment]
@AetheralMeowstic This is a bug in Kiwi. #2055 https://github.com/kiwibrowser/src.next/issues/1135
