### ISSUE TITLE
The properties of console should be enumerable

### ISSUE THREAD

**Issue by maple3142** [Tampermonkey/tampermonkey#1622]
(Please fill out the issue template with your details)

## Expected Behavior

The properties of console should be enumerable

## Actual Behavior

The properties of console is not enumerable, so `Object.keys(console)` is an empty array

## Specifications

- Chromium: 106.0.5249.119
- TM: 4.18.0
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         Test
// @match        https://example.com
// @grant        unsafeWindow
// ==/UserScript==

;(function () {
	'use strict'
    const DEBUG = false
	const createLogger = (console, tag) =>
		Object.keys(console)
			.map(k => [k, (...args) => (DEBUG ? console[k](tag + ': ' + args[0], ...args.slice(1)) : void 0)])
			.reduce((acc, [k, fn]) => ((acc[k] = fn), acc), {})
	const logger = createLogger(console, 'YTDL')
    logger.log('asd')
})()
```

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
