### ISSUE TITLE
Tampermonkey cannot communicate with GreasyFork on Firefox

### ISSUE THREAD

**Issue by wordpure** [Tampermonkey/tampermonkey#1623]
On Firefox, GreasyFork can't get Tampermonkey and script versions, but switching to Edge does.

![image](https://user-images.githubusercontent.com/68013962/196448365-03d5c620-6ca4-4d3c-a0e6-eb75aac216c3.png)

![image](https://user-images.githubusercontent.com/68013962/196444444-9e63c1a5-1f4e-491f-9f66-fd06fd418edd.png)

![image](https://user-images.githubusercontent.com/68013962/196451972-eceabad5-131c-40f3-bdab-213cbe75328a.png)

## Specifications

- Firefox: 106.0
- Edge: 106.0.1370
- TM: 4.18.0
- OS: Windows 21H2

**Comment by alexolog** [comment]
Can confirm.

FF 106.0b9
TM 4.18.0
Windows 10 pro 21H1

Same issue as wordpure reported.

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by wordpure** [comment]
After installing Beta 4.16.6171, the extension can communicate properly with GreasyFork, thanks for the fix.
