### ISSUE TITLE
Someone Please Help..All My Userscripts Over The Years I Gathered Are Gone After The Abrupt PC Shutdown. Is There A Way To Restore It?😭

### ISSUE THREAD

**Issue by rakitanc** [Tampermonkey/tampermonkey#1624]
Chrome Version 103.0.5060.114 (Official Build) (64-bit)
TM version 4.18.0

Running LInux OS

If anyone can help me in the situation. It would mean a world to me, I am very devastated right now to what just happened suddenly out of nowhere
![Screenshot from 2022-10-19 15-41-54](https://user-images.githubusercontent.com/64612555/196666953-0ec8c8d0-e21a-4197-b9ae-a4b51211ade6.png)

```

**Comment by derjanb** [comment]
Closing per https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0?permalink_comment_id=4342303#gistcomment-4342303
