### ISSUE TITLE
the number show is strange

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Tampermonkey/tampermonkey#163]
```
1.) What Tampermonkey version do you use? (go to 'chrome://extensions/' for
that information)
3.4.3568.10
2.) What browser version (go to 'chrome://chrome/') and operating system do
you use?
29

when i go to gmail,the Tampermonkey show 75 or even 115.
i don't know what it means.
would you let it show the number of working scripts for this page just like 
Scriptish ?
```

Original issue reported on code.google.com by `rpzrpz...@gmail.com` on 27 Sep 2013 at 12:07

**Comment by derjanb** [comment]
In order to change the meaning of the number shown at the badge icon simply go to the settings page, set the option mode to `Beginner` or `Advanced` and then you can change `Icon Badge Info` to `Unique running scripts` instead of `Running scripts instances`.
