### ISSUE TITLE
broken GM.saveTab

### ISSUE THREAD

**Issue by 7nik** [Tampermonkey/tampermonkey#1631]
GM.saveTab returns a promise that gets never resolved and the passed data do not appear in GM.getTab(s) result. But GM_saveTab seems to work correctly.

## Expected Behavior
The returned promise resolves and the passed data appears in the GM.getTab(s) result.

## Actual Behavior
The promise never resolves and the passed data do not appear.

## Specifications

- Chromium: Version 106.0.5249.119 (Official Build) Arch Linux (64-bit)
- TM: 4.18.0 and 4.18.6168
- OS: KDE Manjaro

## Script

```js
// ==UserScript==
// @name         Test GM tabs
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://example.com/
// @grant        GM.saveTab
// @grant        GM.getTabs
// ==/UserScript==


const name = Math.random().toString(36).slice(2);
console.log("saved", GM.saveTab({ name }));
console.log("tabs:", await GM.getTabs());
```

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
