### ISSUE TITLE
Tampermonkey doesn't run on Google News unless I hard refresh

### ISSUE THREAD

**Issue by nearcatch** [Tampermonkey/tampermonkey#1632]
For reference, I'm loading Google News from [this url](https://news.google.com/home?hl=en-US&gl=US&ceid=US:en).

Tampermonkey doesn't seem to run on the page if I click the refresh button, but if I hard refresh (ctrl+F5), then it will run on that load.

## Expected Behavior
Run on every refresh.

## Actual Behavior
Runs only on hard refreshes.

## Specifications

- Browser: Firefox Dev Edition 107.0b4 (64-bit)
- TM: Tampermonkey Beta 4.18.6168
- OS: Windows 10 Pro 21H2 19044.2130

## Script

<details>
<summary>sample script</summary>

```js
// ==UserScript==
// @name         Use Large Favicons
// @namespace    https://github.com/nearcatch/
// @version      2022.10.25
// @description  replace 16x16 favicons with larger favicons
// @author       nearcatch
// @match        *://*/*
// @match        https://support.mozilla.org/*
// @grant        GM_addElement
// @noframes
// @run-at       document-start
// ==/UserScript==

"use strict";
// Your code here...
document.addEventListener("DOMContentLoaded", () => {
  let favicon = document.querySelector('link:is([rel="shortcut icon"],[rel="shortcut-icon"])');
  if (typeof(favicon) === 'undefined' || favicon === null) {
    favicon = document.querySelector('link[sizes="16x16"]');
  }
  if (typeof(favicon) != 'undefined' && favicon != null) {
    const faviconNodeList = document.querySelectorAll('link[sizes]:not([sizes="16x16"],[rel^="apple-touch"])');
    const faviconArray = Array.from(faviconNodeList);
    const sortedfaviconArray = faviconArray.sort(sorter);
    function sorter(a,b) {
      return parseInt(a.getAttribute('sizes')) - parseInt(b.getAttribute('sizes'));
    }
    // push original favicon in case faviconArray was empty
    sortedfaviconArray.push(favicon);
    // console.log(sortedfaviconArray);
    // create newFaviconAttr object using attributes of first (hopefully smallest) item in faviconArray
    let newFaviconAttr = {};
    for (const attr of sortedfaviconArray[0].attributes) {
      newFaviconAttr[attr.name] = attr.value;
    }
    // overwrite parsed attribute size with "16x16" to force usage for small screens
    newFaviconAttr.rel = "icon";
    newFaviconAttr.sizes = "16x16";
    // use GM_addElement to make it obvious if favicon was modified
    GM_addElement(document.querySelector('head'), 'link', newFaviconAttr);
    console.log('"Use Large Favicons" userscript set this favicon:');
    console.log(newFaviconAttr);
  }
});
```
</details>

EDIT: debugger page. Top is hard refresh, bottom is normal refresh. Seems no scripts at all are loaded.
![image](https://user-images.githubusercontent.com/692914/197834957-0dcf0a6a-e67e-4546-b190-15b45475184e.png)
![image](https://user-images.githubusercontent.com/692914/197834755-5c64b306-b7c3-4329-a419-f17734c0123d.png)

**Comment by derjanb** [comment]
Does switching to "Content Script" API makes a difference? 
I see that the Tampermonkey icon badge number is not present if I simply reload the page, but my example script is running. So I can only reproduce another problem...

![image](https://user-images.githubusercontent.com/767504/198144278-cd33589e-a5a2-4f7c-927d-8310e6dc3cf4.png)

**Comment by nearcatch** [comment]
It does not make a difference. And now I can't get it to work even with a hard reload. No scripts will work on the news.google page linked above, even though the toolbar button icon indicates that 6 scripts are running on the page.

**Comment by derjanb** [comment]
Hmm. Working fine at FF 105.0 (64-bit)

Looks like this is a Firefox Dev issue. Tampermonkey already tries to prevent FF from caching the page, but this Version nonetheless does. And when this happens, then the page CSP is used.

A possible workaround is to add 
```JS
// @sandbox JavaScript
```

to the script.

**Comment by derjanb** [comment]
Once #1610 is fixed "Instant" injection mode will fix this issue as well.

**Comment by derjanb** [comment]
Note: 106.0.2 is working fine as well
