### ISSUE TITLE
[Firefox] uBlock blocks TM so no scripts can run

### ISSUE THREAD

**Issue by Owyn** [Tampermonkey/tampermonkey#1634]
## Expected Behavior
it runs scripts

## Actual Behavior
it doesn't (for one specific host - but from time to time it ran fine there before)

## Specifications

example url: https://fastpic.org/view/92/2019/1019/3c08433af555c0ece1326534dd07ef69.jpg.html 

- Firefox 106 / Chrome 106 (problem occurs in both browsers)
- TM: 4.18
- OS: Win 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace testest
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://fastpic.org/view/*.html
// @grant none
// ==/UserScript==
console.warn("hello");
```

![image](https://user-images.githubusercontent.com/1309656/198290105-7926bc6e-049b-4253-be8a-eb48ac739a03.png)
![image](https://user-images.githubusercontent.com/1309656/198290307-35a9fb82-0c41-4f40-b96b-e3cd7d4eb8b6.png)

as you can see on screen ther are scripts names in the TM but none have their menu items registered since scripts didn't get to run and there's no "hello" in the console

same in chrome:
![image](https://user-images.githubusercontent.com/1309656/198290436-7df72830-b298-481d-a166-6a0c0cc6b3a4.png)
![image](https://user-images.githubusercontent.com/1309656/198290632-cdbdb93b-15f4-44a2-9869-bf86fc12b6f8.png)

**Comment by LeCommonMan** [comment]
Another URL to test the bug:
https://fastpic.org/view/120/2022/1027/_d528b93b15906dff6bac64c972b9b7e4.jpeg.html

**Comment by derjanb** [comment]
Working fine at FF 105.0 (64-bit) and 107.0b5 (64-bit) and Chrome Version 108.0.5359.19 (Official Build) dev (64-bit)

Please try a new profile with only Tampermonkey installed.

**Comment by Owyn** [comment]
I think it's because of Ublock Origin https://github.com/gorhill/uBlock#ublock-origin , 
it doesn't let TM run any scripts cuz when I disable it scripts start working in both Chrome and Firefox, 

can TM bypass this conflict maybe? cuz uBlock is the most popular blocker I think

**Comment by derjanb** [comment]
> can TM bypass this conflict maybe?

In Firefox `// @sandbox JavaScript` should help.

**Comment by Owyn** [comment]
> > can TM bypass this conflict maybe?
> 
> In Firefox `// @sandbox JavaScript` should help.

It does help but it breaks other functionality: issue https://github.com/Tampermonkey/tampermonkey/issues/1636

**Comment by derjanb** [comment]
> I think it's because of Ublock Origin https://github.com/gorhill/uBlock#ublock-origin , it doesn't let TM run any scripts cuz when I disable it scripts start working in both Chrome and Firefox

Do you have special filter lists? A freshly installed uBlock origin is working fine here.

**Comment by Owyn** [comment]
Well, fastpic is a Ru host, so you'd probably need ru regional lists?
But I don't think I did anything to any lists or filters, so it's pretty much default

![image](https://user-images.githubusercontent.com/1309656/200536504-67337442-1426-4129-860f-17a12059c7c8.png)
![image](https://user-images.githubusercontent.com/1309656/200536538-78f5d64e-bf84-4692-8895-fa16970ea0ea.png)
![image](https://user-images.githubusercontent.com/1309656/200536570-958a4a5b-c130-40e6-9921-11a14952e96a.png)
![image](https://user-images.githubusercontent.com/1309656/200536607-f72f5302-0cf5-4bcb-a729-2c012d438c29.png)
![image](https://user-images.githubusercontent.com/1309656/200537030-20c3fb65-44c1-46ca-a8c2-dd87978e7b7b.png)

**Comment by derjanb** [comment]
Hmm. I can't reproduce the issue using the test script from above with uBlock origin installed and all settings and filter lists adapter to your settings neither at Chrome nor Firefox. 
Can you please try to reproduce it at a new profile with Tampermonkey and uBlock origin installed from scratch?

**Comment by Owyn** [comment]
funny thing: - I turn off either uBlock OR NoScript and the problem seems to go away, I turn one of them on and it's still ok, BUT if I turn back BOTH of them - problem happens
(I tried setting website to trusted or disabling restriction for the tab in NoScript - but that doesn't seem to fix it, only fully disabling the NoScript extension (or turning off the uBlock on the page))
![image](https://user-images.githubusercontent.com/1309656/200654229-0e95f01e-1410-4d1e-8fc0-470f9f6c4d2b.png)

**Comment by derjanb** [comment]
Ah, I now can reproduce the issue. But enabling NoScript is enough here.

Setting the domain to trusted works fine here. I don't think I can fix the issue, because both eval and script tag injection can be prevented by a CSP (except in `@sandbox JavaScript` mode) and if more than one extension modifies the CSP header then it is unclear which extension wins.

> funny thing: - I turn off either uBlock OR NoScript 

I suppose turning extensions on and off changes the order the CSP header is modified.

**Comment by derjanb** [comment]
Solution for now: In Firefox `// @sandbox JavaScript` should help.

**Comment by ViperCode7** [comment]
Had something similar on my end on Edge, at last just after disabling all regional filters it started to work, Prior to it I cleaned up the rules and my filters, purges, updated and wouldn't budge. Probably somewhere in the regional filters there might a conflict for fastpic.
