### ISSUE TITLE
FF @sandbox Javascript unsafeWindow access is broken

### ISSUE THREAD

**Issue by Owyn** [Tampermonkey/tampermonkey#1636]
(Please fill out the issue template with your details)

## Expected Behavior
undefined

## Actual Behavior
variable

## Specifications

- Firefox 106
- TM: 4.18
- OS: Win 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name		test
// @namespace	test
// @version		1
// @description	test
// @author		Owyn
// @match		*://*/*
// @grant		unsafeWindow
// @sandbox		JavaScript
// @run-at		document-end
// ==/UserScript==

(function() {
	'use strict';

console.warn(unsafeWindow);
console.warn(unsafeWindow.adsbygoogle);
})();

```
result: - can't access any variables in unsafeWindow
![image](https://user-images.githubusercontent.com/1309656/198827883-263c156d-ac11-4f6c-8fa6-6e0b5a830987.png)

**Comment by derjanb** [comment]
Should be fixed at 4.19.6172 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Owyn** [comment]
With 4.18.1 unsafewindow variables work fine again but there's a problem with functions... you can set functions in unsafewindow and call them but only from the userscript - the page itself can't do that due to restrictions
![изображение](https://user-images.githubusercontent.com/1309656/202415879-4e83429a-ebd4-4ea6-a081-15deffc8ca95.png)

````
// ==UserScript==
// @name		test
// @namespace	test
// @version		1
// @description	test
// @author		Owyn
// @match		*://*/*
// @grant		unsafeWindow
// @sandbox		JavaScript
// @run-at		document-start
// ==/UserScript==

(function() {
	'use strict';

unsafeWindow.myfunc = function (){return true;}
console.warn(unsafeWindow.myfunc);

})();
````

**Comment by Owyn** [comment]
and I think that also goes for listener functions, page can't access them so it also can't run them, example, my  `DOMContentLoaded` just stopped working cuz I was adding it from `unsafeWindow`

````
// ==UserScript==
// @name		test
// @namespace	test
// @version		1
// @description	test
// @author		Owyn
// @match		*://*/*
// @grant		unsafeWindow
// @sandbox		JavaScript
// @run-at		document-start
// ==/UserScript==

(function() {
	'use strict';

unsafeWindow.addEventListener("DOMContentLoaded", function(){ console.error("DOMContentLoaded unsafe"); }); // doesn't work

window.addEventListener("DOMContentLoaded", function(){ console.error("DOMContentLoaded window"); }); // works

})();
````

**Comment by derjanb** [comment]
I guess this is where `cloneInto` [needs to come in](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#cloneinto ) due to Firefox's security model. Will release a new BETA soon.

**Comment by Owyn** [comment]
If it will be a clone - that means cloned functions won't be able to access & monitor variables inside the userscript? (and especially gm.getvalue ones) (also call functions if no `cloneFunctions` option it seems as the wiki says)

**Comment by derjanb** [comment]
> If it will be a clone - that means cloned functions won't be able to access & monitor variables inside the userscript

No, the function keeps its scope and can access it

Should be fixed at 4.19.6176 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons`

**Comment by Owyn** [comment]
Am I doing something wrong? I'm using BETA
![image](https://github.com/Tampermonkey/tampermonkey/assets/1309656/c7ac38c5-6c1b-4852-9ef8-132eda30a09f)

![image](https://github.com/Tampermonkey/tampermonkey/assets/1309656/c2f51c67-05a8-443c-8448-70bc3796015a)

**Comment by derjanb** [comment]
`// @sandbox JavaScript` executes the script in an isolated sandbox.

```JS
// ==UserScript==
// @name		test
// @namespace	test
// @version		1
// @description	test
// @author		Owyn
// @match		*://*/*
// @grant		unsafeWindow
// @sandbox		JavaScript
// @run-at		document-start
// ==/UserScript==

(function() {
	'use strict';

    const f = exportFunction(function(){ console.error("DOMContentLoaded unsafe")}, unsafeWindow);
    unsafeWindow.addEventListener("DOMContentLoaded", f); // works now
    window.addEventListener("DOMContentLoaded", function(){ console.error("DOMContentLoaded window"); }); // works
})();
```
