### ISSUE TITLE
Disable/uninstall script does not work

### ISSUE THREAD

**Issue by xinbimingjingtai** [Tampermonkey/tampermonkey#1644]
(Please fill out the issue template with your details)

1. Install [AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列](https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97) in firefox, and in chrome not install any scripts.

2. Disabled/uninstalled/changed setting  
![script setting](https://user-images.githubusercontent.com/91510743/201539016-93eae5a5-4051-49ca-8489-18ec57becff1.jpg)

## Expected Behavior
1. Does not affect chrome (other browsers)

2. Back to what it was

## Actual Behavior
1. Affected chrome

2. Didn't back to what it was

## Specifications
- OS: windows 10  21H1 19043.2251
- TM: 4.18.0

1. firefox(32): 91.9.0esr
2. chrome(64): 107.0.5304.88

## Script
See [AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列](https://greasyfork.org/zh-CN/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97)

**Comment by derjanb** [comment]
Please contact the script developer for example here: https://greasyfork.org/en/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E5%BF%85%E5%BA%94%E6%90%9C%E7%B4%A2-favicon-%E5%8F%8C%E5%88%97/feedback
