### ISSUE TITLE
Sync 

### ISSUE THREAD

**Issue by SmartManoj** [Tampermonkey/tampermonkey#1646]
Fresh installation.

## Expected Behavior
Should sync

## Actual Behavior
Just shows this screen only
![image](https://imgur.com/LXiEzXX.png)

## Specifications

- Vivaldi 5.5.2805.42 (Stable channel) stable (64-bit) 
- TM: v4.18.0
- OS: Manjaro XFCE 21.3.7

**Comment by derjanb** [comment]
Can you please check the JavaScript console for messages or errors? If there is nothing, then please [check the background console](http://tmnk.net/faq#Q600) as well.

**Comment by YihangFu** [comment]
I have the same issue. I have two users and two accounts on Chrome. Sync works on one account only.

_Google Chrome 107
OS: macOS 12.6
System language: Chinese_

**Comment by 1JackBlack1** [comment]
I have had the same issue.

Opening the background console, I can see a lot of 401 errors.
Is tamper monkey currently caching credentials and then when the token expires, it doesn't actually detect that and instead it just tries to use them?

When I switch to debugging and tell it to sync it states it is scheduled to sync in 1 ms, but no other sync related messages.

Disabling Tamper monkey and re-enabling it appears to get it working to sync again.

**Comment by dev-jelo** [comment]
I also have the same issue when trying to sync using Google Drive.
Disabling and re-enabling doesn't work either.
Background console just says "sync: schedule sync for run in 1 ms".

**Comment by HoffmannP** [comment]
Same issue. No output in Console and Background Console

**Comment by derjanb** [comment]
Tampermonkey now has a "Recent Sync Log". Please post its content and a complete background console log after setting "Log Level" to debug. You can also send it to me per [mail](https://www.tampermonkey.net/imprint.php) if you don't want to share is publicly.

Without more data I can't fix the issue.

![image](https://user-images.githubusercontent.com/767504/224178668-9a81de16-a3cd-478b-91cb-ea8169ef6012.png)

**Comment by majutsushi** [comment]
I have the same issue with Firefox on Linux. It just hangs forever on the "Please wait" popup, regardless of the sync type. There is not output on the extension console, and the sync log remains empty as well. The only related output is this on the background console:

```
11:58:39.700 mh: request Object { method: "buttonPress", name: "run_sync", data: undefined, origin: "options" }
  sender: Object { contextId: 962072690590, id: "firefox@tampermonkey.net", envType: "addon_child", url: "moz-extension://4bfe652a-99c6-4f00-896f-961004c32b1b/options.html#nav=settings", tab: {…}, frameId: 0 } background.js:833:249
11:58:39.704 mh: request page: options extpage: true background.js:834:4
11:58:39.705 sync: schedule sync for run in 1 ms
```

Interestingly using Utilities -> Cloud to export the config works fine.

**Comment by lfxx** [comment]
> I have the same issue with Firefox on Linux. It just hangs forever on the "Please wait" popup, regardless of the sync type. There is not output on the extension console, and the sync log remains empty as well. The only related output is this on the background console:
> 
> ```
> 11:58:39.700 mh: request Object { method: "buttonPress", name: "run_sync", data: undefined, origin: "options" }
>   sender: Object { contextId: 962072690590, id: "firefox@tampermonkey.net", envType: "addon_child", url: "moz-extension://4bfe652a-99c6-4f00-896f-961004c32b1b/options.html#nav=settings", tab: {…}, frameId: 0 } background.js:833:249
> 11:58:39.704 mh: request page: options extpage: true background.js:834:4
> 11:58:39.705 sync: schedule sync for run in 1 ms
> ```
> 
> Interestingly using Utilities -> Cloud to export the config works fine.

same issue here

**Comment by YihangFu** [comment]
My sync function now works.
I'm not sure if it's something I did or if the update brought some fixes.

A small tip here.
After checking "Enable TESLA", DO NOT check "run now" (or "sync now", my interface is in Chinese). Just check "save", then REFRESH the page. Now you can check "run now". There will still be a "Please wait" popup keeps showing. But the textbox "Recent Sync Log:" shows the sync has been completed. And that's true, the sync does work.
