### ISSUE TITLE
MenuCommand runs twice sometimes?

### ISSUE THREAD

**Issue by Owyn** [Tampermonkey/tampermonkey#1649]
I press the menu command and action gets executed twice sometimes (I press it via hotkey) so maybe I keep hotkey pressed for too long and it triggers twice?) 

## Specifications

- Firefox: 107
- TM: 4.18.1
- OS: Win 10

my script: https://github.com/Owyn/Universal_Dark_Theme/ 

![изображение](https://user-images.githubusercontent.com/1309656/202795131-c05739f9-6f36-4dbc-aa67-2c9196d8d17f.png)

![изображение](https://user-images.githubusercontent.com/1309656/202794905-06287c3d-c902-4413-9118-3297613e3a52.png)

Here, I added resizing to my UI and... noticed there's a 2nd UI under it :D

yea, I understand I don't have a check to see if there's already a config window open BUT I'm sure I only pressed menu item once so it should've ran only once

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
