### ISSUE TITLE
The Chrome extention stopped working

### ISSUE THREAD

**Issue by MeSsI-AKA-FERNO** [Tampermonkey/tampermonkey#1656]
## Expected Behavior
The extension would work normally as well as the scripts.

## Actual Behavior
The extension is greyed out in the manager and none of the scripts works either
https://i.imgur.com/aHmx9p6.png

## Specifications

- Chromium: (i.e. 64.0.3282.140)

## Script
~none~

**Comment by derjanb** [comment]
Do you see errors at the background console? 
What are you Tampermonkey, browser and OS versions?

**Comment by lancelin0410** [comment]
I also have same problem.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'methods')
    at Object.init (background.js:251:14)
    at w.init (background.js:862:105)
    at background.js:873:78
    at background.js:873:84
    at background.js:873:88
```

**Comment by derjanb** [comment]
Looks like you used a unsupported option and switched to `sql` storage?! 

You can restore the default value by running 

```
localStorage.removeItem('#storage')
```

at the background page.
