### ISSUE TITLE
GM_download weirdly specific failure

### ISSUE THREAD

**Issue by martixy** [Tampermonkey/tampermonkey#1659]
## Expected Behavior
Work in all cases

## Actual Behavior
On this page: https://www.artstation.com/artwork/qP8mD (I hope you like feet.)
`GM_download` fails to download any of the main images with a `not_whitelisted` error.
Even though for every other matching page I've tested it has worked. (By this artist so far anyway.)

Edit: It also fails for (probably) the entirety of this artist's gallery: https://www.artstation.com/haohi
I couldn't find an example that works, but I didn't test every single artwork.
They're just `.jpg`s. They're whitelisted by default. Not to mention it works for all but one artwork of the first artist. I don't get it.

And again, no problem for this one: https://www.artstation.com/artwork/b5Lgqm

Unrelated, but does the `saveAs` option work in *any* scenario?

## Specifications

- Chromium: Version 107.0.5304.108
- TM: 4.18.0
- OS: Win10 22H1

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @include https://www.artstation.com/artwork/*
// @grant GM_download
// ==/UserScript==

GM_download("https://cdnb.artstation.com/p/assets/images/images/004/466/507/4k/linda-lithen-leggs-compilation2.jpg?1483974645", "blabla")
```

**Comment by Owyn** [comment]
Does trying to dl with "dl" button make a difference for you?

> Edit: It also fails for (probably) the entirety of this artist's gallery: https://www.artstation.com/haohi

tried 2nd image from there - It works for me in both browsers with my https://github.com/Owyn/HandyImage extension (ctrl+s hotkey) which uses GM_Download
![image](https://user-images.githubusercontent.com/1309656/204807964-f6d7b30d-a425-4a6f-a7dd-54461eb4fa70.png)


P.S. - I was having trouble getting gm_download to work at all when I was implementing it into my userscript, I had to reselect default DL method in TM a few times for it to start working

**Comment by martixy** [comment]
> Does trying to dl with "dl" button make a difference for you?

If you mean using the buttons already on the site, it does. The script I wrote fetches all images with a single button press, and composes sensible names for every file (something ArtStation is really bad with).

In either case it still totally fails on my end. In both firefox and chrome, with stable or beta TM.  Moreover changing the download mode has no effect.

***
P.S. If you'll allow some critique of your script: It is *painful* to read. Just looking at the function you use `GM_download` in, you have 3 indentation levels in a single block. Among other things. It looks like some kind of frankensteinian abomination. The least you could do paste the whole thing in some IDE like VSCode and hit Reformat. Not to mention requiring people disable adblock and tracking protections is a surefire way to guarantee no one ever uses it.

**Comment by derjanb** [comment]
@martixy Hmm. With download mode set to "Native" your example script starts a download called "blabla.jpeg", with download mode set to "Browser API" it downloads a files called "blabla".

Tested with:
Ubuntu + Chrome Version 111.0.5545.6 (Official Build) dev (64-bit) + TM 4.19.6176
Windows 10 + Chrome Version 107.0.5304.107 (Offizieller Build) (64-Bit) + TM 4.18.1

Are you sure there is not filtering proxy or something similar at your PC or network?

**Comment by martixy** [comment]
Could we have more than one example tested before closing perhaps?

I can now download the quoted script but still fails on anything from this artist: https://www.artstation.com/haohi

Also, what kind of filtering proxy could there possibly be that allows me to go to the address and save the file manually, but will not allow Tampermonkey to do so? Or that allows TM to download 90% of all files, but not the other 10%, and only by certain specific artists?

I have looked through the normal requests and I cannot find any commonality between them that could explain this behavior. I can post request and response headers, if you think they would prove helpful.

**Comment by derjanb** [comment]
But why posting an example that doesn't trigger the bug?

```
GM_download("https://cdna.artstation.com/p/assets/images/images/056/231/076/large/lessdraws-sword-small.jpg?1668748947", "foofoo");
```

Is working fine here as well. 

So please post an example that is not working. Thanks.

**Comment by martixy** [comment]
It didn't work at the time.

This fails:
`GM_download("https://cdna.artstation.com/p/assets/images/images/056/231/076/4k/lessdraws-sword-small.jpg?1668748947", "haohi-20221118-zDEPWD His bleeding heart by LessDraws ... [sword-small]");`

_With no error._

**Comment by derjanb** [comment]
The error is here:


```JS
GM_download({
    url: "https://cdna.artstation.com/p/assets/images/images/056/231/076/4k/lessdraws-sword-small.jpg?1668748947",
    name: "haohi-20221118-zDEPWD His bleeding heart by LessDraws ... [sword-small]",
    onerror: (e) => console.error(e),
    onload: (e) => console.info(e)
});
```

http://tmnk.net/docs#api:GM_download

**Comment by martixy** [comment]
Docs say the name should include the file extension. May we have **an error** when an extension is _not supplied_? Because so far it works without an extension and an otherwise valid name without dots will download with the correct extension.

Therefore code that does not actually include an extension in the name will appear to work well then spontaneously break in non-obvious ways such as this.

**This is still a bug IMO.**

> The error is here:

Yea, I keep forgetting TM still operates on callbacks, so errors are hidden unless you go look for them.

**Comment by derjanb** [comment]
> Yea, I keep forgetting TM still operates on callbacks, so errors are hidden unless you go look for them.

Yes, GM_ is based on callbacks, but you can use the GM. API as well.

```JS
const a = await GM.download("https://cdna.artstation.com/p/assets/images/images/056/231/076/4k/lessdraws-sword-small.jpg?1668748947", "haohi-20221118-zDEPWD His bleeding heart by LessDraws ... [sword-small]");
```
