### ISSUE TITLE
Encoding Bug on Update

### ISSUE THREAD

**Issue by m-neto** [Tampermonkey/tampermonkey#1665]
When I use the "Import from URL" in Utilities, the script is OK.
![image](https://user-images.githubusercontent.com/64424044/204873555-cb7fe728-c4b7-4369-b42f-084e15f34a68.png)

when updating version of @downloadURL the UTF-8 just doesn't work
![image](https://user-images.githubusercontent.com/64424044/204873948-278ec837-e566-4c40-a23a-8bac34a3c70b.png)
![image](https://user-images.githubusercontent.com/64424044/204874092-e6a5b591-8083-4356-894c-401d92cc3224.png)

## Specifications
- Chrome version: 107.0.5304.107
- Tampermonkey version: 4.18.1

## Script

Can get code in: https://erp.mneto.dev/tampermonkey/test

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Teste
// @namespace    http://tampermonkey.net/
// @version      1.2
// @description  try to take over the world!
// @author       You
// @match        https://google.com.br/*
// @grant        none
// @updateURL    https://erp.mneto.dev/tampermonkey/test
// @downloadURL  https://erp.mneto.dev/tampermonkey/test
// @run-at document-end
// ==/UserScript==

alert('this is a accent test! á é í ó ú');
// change the @version and re-enable updates to check
```

**Comment by derjanb** [comment]
Looks like something at your server is not configured correctly. Even Chrome and Firefox can't decode is correctly when opened in a tab: 

Compare  https://erp.mneto.dev/tampermonkey/test vs. http://ttt.tampermonkey.de/tmp/test

Import from URL loads a arrayBuffer an force decodes it via UTF-8, but this shouldn't be necessary at all.

**Comment by m-neto** [comment]
actually, trying to fix another bug, I ended up creating this one hahaha

SOLVED!
