### ISSUE TITLE
"@Exclude" not working as intended.

### ISSUE THREAD

**Issue by TsukiZero** [Tampermonkey/tampermonkey#1667]
I use some scripts on Twitch.TV with a "@Exclude" clause but it is being completely ignored for some reason.

## Expected Behavior
`// @exclude      *://clips.twitch.tv/*` is added to a script and said script should not run in any clips page

## Actual Behavior
Said script still runs in clips page despite being told not to

## Specifications

- Chromium: Whatever is in Firefox 107.0.1 (64-bit)
- OS: Windows 10 - Version 10.0.19044 Build 19044

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name Twitch Auto Channel Points Claimer
// @version 1.6
// @author PartMent
// @description Automatically claim channel points.
// @match        *://www.twitch.tv/*
// @match        *://dashboard.twitch.tv/*
// @exclude      *://clips.twitch.tv/*
// @license MIT
// @grant none
// @namespace https://greasyfork.org/users/310437
// ==/UserScript==
let MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver;
let claiming = false;
if (MutationObserver) console.log('Auto claimer is enabled.');
let observer = new MutationObserver(e => {
    let bonus = document.querySelector('.claimable-bonus__icon');
    if (bonus && !claiming) {
        bonus.click();
        let date = new Date();
        claiming = true;
        setTimeout(() => {
            console.log('Claimed at '+date);
            claiming = false;
        }, Math.random() * 1000 + 2000);
    }
});
observer.observe(document.body, {childList: true, subtree: true});
```

Example clip page: https://clips.twitch.tv/SpinelessDeterminedTarsierStinkyCheese-nMAAifQjVGza80B_

**Comment by derjanb** [comment]
I don't see the script being executed at the mentioned clip page. Most probably the page has some iframe with a matching URL? Please add `@noframes` either to the script or configure it at the script's settings page.

**Comment by TsukiZero** [comment]
> I don't see the script being executed at the mentioned clip page. Most probably the page has some iframe with a matching URL? Please add `@noframes` either to the script or configure it at the script's settings page.

That did appear to be the case. I'll bring another certain script's author some attention to it.

Oddly, from what I seem to recall, Tampermonkey used to acknowledge `@exclude` without needing `@noframes`? Maybe something changed? Or maybe my memory is rusted?

**Comment by derjanb** [comment]
`@noframes` has no effect on `@exclude`. However it prevents a script from running if the matching URL is not the top frame.

**Comment by TsukiZero** [comment]
OK, adding `@noframes` is a bogus for another issue: it means the script won't run in embeds, since those uses iframes.

And from what I understand of the documentation, `@exclude` should have priority over `@match` and `@include`, yet it does not

**Comment by derjanb** [comment]
> And from what I understand of the documentation, @exclude should have priority over @match and @include

Yes and it works this way. However the parent document hierarchy is not taken into account. 
If `@noframes` is not an option, then you have to find the iframe URL that matches your script and `@exclude` this one as well.
