### ISSUE TITLE
Amazon Stock Price on Phone tool is not working

### ISSUE THREAD

**Issue by arrenwells** [Tampermonkey/tampermonkey#1668]
(Please fill out the issue template with your details)

## Expected Behavior
show stock price on phone tool

## Actual Behavior
not showing up

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

// ==UserScript==
// @name           Add Amazon Stock Price on Phonetool
// @namespace      np1810@gmail.com
// @description    Add Amazon Stock Price on Phonetool
// @version        20200704
// @icon           https://phonetool.amazon.com/assets/phonefavicon-aa2514b9057258f3bd1f070c1136e8066e86726221b5c06cf67f0a8739644c48.png
// @updateURL      https://drive.corp.amazon.com/view/pathakni@/public/Greasemonkey-Scripts/amzn-stock-price.user.js
// @downloadURL    https://drive.corp.amazon.com/view/pathakni@/public/Greasemonkey-Scripts/amzn-stock-price.user.js
// @author         Nitin Pathak <pathakni@amazon.com>
// @match          https://phonetool.amazon.com/users/*
// @exclude        https://phonetool.amazon.com/users/*/org
// @grant          none
// ==/UserScript==

const MY_UNIBIT_FREE_API_KEY = "3EwAIq-U4vZToHzyofpKG9d1CQEFjfOI";
// 1. Get your own unibit free api key and follow the below steps
// 2. Use https://temp-mail.org/en/ to generate a temp email to avoid spam
// 3. Do free signup on https://unibit.ai/signup
// 4. Verify your own email or the temp-mail, you got in Step #2
// 5. Signin here https://unibit.ai/signin
// 6. Get your own free API key here https://unibit.ai/app/admin/apikey
// 7. Replace 3EwAIq-U4vZToHzyofpKG9d1CQEFjfOI with you own API key
//    which you got in Step #6 in the MY_UNIBIT_FREE_API_KEY variable
// FYI - 20 Credits/PhonetoolPage and 50000 Free Credits/Month Limit

const $ = window.$ || window.jQuery;
$(document).ready(function () {
  function get_hire_date() {
    return new Date($("div.HireDateRow .TableValue").text().trim() + " UTC");
  }

  function get_history_stock(hire_date, plus_days) {
    if (plus_days > 5) {
      $("#HistoryStockWrapper").remove();
      return;
    }
    hire_date.setDate(hire_date.getDate() + plus_days);
    var hire_date_str = hire_date.toISOString().split("T")[0];
    $.ajax({
      type: "GET",
      url:
        "https://api.unibit.ai/v2/stock/historical?tickers=AMZN&startDate=" +
        hire_date_str +
        "&endDate=" +
        hire_date_str +
        "&accessKey=" +
        MY_UNIBIT_FREE_API_KEY,
      error: function (error1) {
        $("#HistoryStockWrapper").remove();
        // console.error("History Error", error1);
      },
      success: function (success1) {
        try {
          var historyDate = success1.result_data.AMZN[0].date;
          var historyStockPrice = parseFloat(success1.result_data.AMZN[0].high);
          var historyStockText =
            historyStockPrice.toFixed(2) + " ( &#x1F51B; " + historyDate + " )";
          $("#HistoryStockValue").html(historyStockText);
          get_current_stock(historyStockPrice);
        } catch (exception1) {
          // console.log("History Exception", exception1);
          get_history_stock(get_hire_date(), ++plus_days);
        }
      },
    });
  }

  function get_current_stock(historyStockPrice) {
    $("#HistoryStockWrapper").after(
      '<span class="optional-wrapper" id="CurrentStockWrapper">' +
        '<div class="TableRow CurrentStockRow">' +
        '<div class="TableProperty">Current AMZN $</div>' +
        '<div class="TableValue" id="CurrentStockValue">Loading...</div>' +
        "</div></span>"
    );
    $.ajax({
      type: "GET",
      url:
        "https://api.unibit.ai/v2/stock/historical?tickers=AMZN&accessKey=" +
        MY_UNIBIT_FREE_API_KEY,
      error: function (error2) {
        $("#CurrentStockWrapper").remove();
        // console.error("Current Error", error2);
      },
      success: function (success2) {
        try {
          var currentStockPrice = parseFloat(success2.result_data.AMZN[0].high);
          var ratioChange = currentStockPrice / historyStockPrice;
          var ratioChangeText =
            currentStockPrice.toFixed(2) +
            " ( " +
            (ratioChange < 1 ? "&#x1F4C9; " : "&#x1F4C8; ") +
            ratioChange.toFixed(2) +
            " )";
          $("#CurrentStockValue").html(ratioChangeText);
        } catch (exception2) {
          $("#CurrentStockWrapper").remove();
          // console.error("Current Exception", exception2);
        }
      },
    });
  }
  $("div.UserDetailsTable").append(
    '<span class="optional-wrapper" id="HistoryStockWrapper">' +
      '<div class="TableRow HistoryStockRow">' +
      '<div class="TableProperty">Day1 AMZN $</div>' +
      '<div class="TableValue" id="HistoryStockValue">Loading...</div>' +
      "</div></span>"
  );
  get_history_stock(get_hire_date(), 0);
});

**Comment by derjanb** [comment]
Please contact the script developer ([np1810@gmail.com](mailto:np1810@gmail.com)?).
This looks like an internal site that I can't access.
