### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rabbit5506** [Tampermonkey/tampermonkey#1670]
(Please fill out the issue template with your details)

## Expected Behavior
most of pan baidu second linl extraction isn't working

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by makyen** [comment]
As an issue for Tampermonkey, there's not enough information for this "issue" to be actionable. IMO, it should just be closed.
