### ISSUE TITLE
eslint incorrectly warns about undefined $ when using @require jQuery

### ISSUE THREAD

**Issue by ludovic-tc** [Tampermonkey/tampermonkey#1673]
Tampermonkey incorrectly reports eslint warnings about undefined $ for lines using jQuery $ when requiring jQuery in the script header.

Specifically, the error message given is :-

`eslint: no-undef - '$' is not defined.`

## Expected Behaviour

When requiring jQuery with a line in the header such as :-
`// @require    https://code.jquery.com/jquery-3.6.1.slim.min.js`

The import / require is valid and works. The script should therefore not display these warnings: they are mistaken. 

## Actual Behaviour

eslint creates ⚠️ warning emoji and issues displays the warning message `eslint: no-undef - '$' is not defined.` as a tooltip for lines that include the jQuery $ symbol in a script that `@require`s jQuery. These warnings are incorrect and cause a lack of user confidence in a script that is actually working. 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name        s3loglinker
// @namespace   Broadbean
// @version     0.2
// @grant       none
// @run-at      document-end
// @match       https://opensearch.broadbean.net/*
// @match       https://ekk.broadbeantech.com/*
// @description Turn s3 Hybrid log entries in OpenSearch into clickable links.
// @require     https://code.jquery.com/jquery-3.6.1.slim.min.js
// ==/UserScript==
```

**Comment by 7nik** [comment]
Requires tell ESLint absolutely nothing about added global variables.

Add `/* global $ */` at the code beginning.

**Comment by makyen** [comment]
This isn't a bug/issue in Tampermonkey.

Tampermonkey doesn't, and shouldn't, auto-detect that you've used `@require` to load some resource. As is *absolutely normal* for eslint, you need to [tell eslint what global variables you're using and/or the environment your code it operating in](https://eslint.org/docs/latest/use/configure/language-options#specifying-globals). There are multiple ways to do that. In a single userscript, the easiest way to do it is to add an eslint `global` directive at the start of your userscript. For the ones which use jQuery, the simple, and most portable, thing is, as mentioned above, to add the following just under the the userscript comment block:
```
/* global $, jQuery */
```

Note: The [eslint documentation](https://eslint.org/docs/latest/use/configure/language-options#specifying-globals) indicates that you should use the `global` keyword for inline definitions, but `globals` also works.

**Comment by dnknn** [comment]
> There are multiple ways to do that.

@makyen Hi, can you tell me if there are any other methods? Because I don't want to add such comments in every script
