### ISSUE TITLE
External dependency won't load with `@require` if sandbox is disabled

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1676]
Consider this userscript:

```js
// ==UserScript==
// @name         Require with sandbox disabled?
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://example.com
// @require      https://cdn.jsdelivr.net/npm/sweetalert2@11.6.16/dist/sweetalert2.all.min.js
// @grant        none
// ==/UserScript==
/* globals Swal */

(function() {
    'use strict';

    Swal.fire(
        'Good job!',
        'You clicked the button!',
        'success'
    );
})();
```

It should load SweetAlert and show a message on http://example.com, but it throws a `Swal is not defined` error. If, however, I specify a `@grant` value (e.g. `GM_addStyle`) or add `// @unwrap`, the external JS file will load.

Why's that?

**Comment by 7nik** [comment]
in both cases  the lib is available under the `Sweetalert2` name

**Comment by double-beep** [comment]
@7nik the question is, why does `Swal` get exposed only on the second case?
