### ISSUE TITLE
broken userscript link in stack trace

### ISSUE THREAD

**Issue by j4k0xb** [Tampermonkey/tampermonkey#1681]
## Expected Behavior

Be able to click any link of a stack trace to open the userscript at the corresponding line.
Would be nice if it only showed the name like `'//# sourceURL=' + encodeURIComponent(scriptName)`:

![image](https://user-images.githubusercontent.com/55899582/215818193-e04280ef-665a-48e3-9e40-83864926f8b0.png)

## Actual Behavior

The link is cut off early due to symbols in the script name (should be urlencoded):
![image](https://user-images.githubusercontent.com/55899582/211881725-70b750a5-6dd9-45d0-b920-7de76ff881ca.png)

## Specifications

- Chromium: 108.0.5359.128
- TM: 4.18.1
- OS: Linux Manjaro

## Script

```js
// ==UserScript==
// @name         New Userscript (test)
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://example.com
// @grant        none
// ==/UserScript==

throw new Error();
```

**Comment by derjanb** [comment]
Should be fixed at 4.19.6177 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
