### ISSUE TITLE
Why is tampermonkey not free for Safari?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Tampermonkey/tampermonkey#1687]
Self explanatory, the extensions for Chrome and Firefox are free though

**Comment by derjanb** [comment]
In short: because no other browser requires me to pay an annual fee and, even more important, to buy hardware that I don't use for anything else than development of this extension. 🤷

See https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-542235500

**Comment by Explosion-Scratch** [comment]
Wow, didn't know there was an annual fee (or about the hardware). Makes sense, thanks for clarifying!
