### ISSUE TITLE
Pull request Description is not working with Bitbucket and Tempermonkey user script

### ISSUE THREAD

**Issue by saileshkhadka** [Tampermonkey/tampermonkey#1690]
We are using an user script for pull request description formatter with bitbucket, In previous it works without any issues but seems like there is version issue either it came from script or its a browser issue.

Tried to re-install script and temper monkey too but didn't work.

## Specifications

- Chrome: Version 109.0.5414.120 (Official Build) (64-bit)
- firefox: 109.0
- Edge: Version 109.0 (Official Build) (64-bit)
- OS: (i.e. Windows and Linux)
- Bitbucket version: lts

## Script
// ==UserScript==
// @name         Pull Request Description Formattor
// @namespace    Sailesh
// @version      2.0
// @description  try to take over the world!
// @author       Sailesh Khadka
// @match        https://bitbucket.org/*/pull-requests/new*
// @grant        none
// ==/UserScript==
var $ = window.jQuery;
function descAddControls() {
    if ($("#id_description").size() == 1 && $('#desc_description').size() === 0) {
        $('#id_description_group').hide();
        $('<div class="field-group desc_group"><label>Description</label><textarea id="desc_description" rows="4" cols="40" class="bb-mention-input" style="height: 90px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Old Pull Req. Link</label><input autofocus="autofocus" class=" text long-field" id="desc_pullReqLink" maxlength="500" type="text"></div>' +
          '<div class="field-group desc_group"><label>Root Cause</label><textarea id="desc_rootCause" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Fix</label><textarea id="desc_fix" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Design Doc. Link</label><input autofocus="autofocus" class=" text long-field" id="desc_docLink" maxlength="500" type="text"></div>' +
          '<div class="field-group desc_group"><label>Cross Module Impact</label><textarea id="desc_crossModuleImpact" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Unit Tests</label><textarea id="desc_unitTests" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Manual Tests</label><textarea id="desc_manualTests" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>FLS</label><textarea id="desc_fls" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>' +
          '<div class="field-group desc_group"><label>Stored / Reflected XSS</label><textarea id="desc_xss" rows="3" cols="40" class="bb-mention-input" style="height: 45px; min-height: 45px;"></textarea></div>')
            .insertAfter('#id_description_group');
        $('<label><input type="checkbox" class="desc_chkSetDescription" checked="true">Set Description on Submit </input></label>' +
          '<input type="button" class="aui-button aui-button-compact desc_btnSetDescription" value="Set Formatted Description"></input>' +
          '<input type="button" class="aui-button aui-button-compact desc_btnShowHideFormatterFields" value="Hide Formatting Fields"></input>')
            .insertAfter('#submitPrButton');
        $(".desc_btnSetDescription").click(descSetFormattedDescription);
        $(".desc_btnShowHideFormatterFields").click(descShowHideFormatterFields);
        $("#submitPrButton").click(descValidateAndSetFormattedDescription);
    }
}
function descValidateAndSetFormattedDescription(elm) {
    debugger;
    var isValid = true;
    if ($('.desc_chkSetDescription')[0].checked) {
        var crossModuleImpact = $("#desc_crossModuleImpact"),
            unitTests = $("#desc_unitTests"),
            manualTests = $("#desc_manualTests"),
            fls = $("#desc_fls"),
            xss = $("#desc_xss"),
            crossModuleImpactVal = crossModuleImpact.val().trim(),
            unitTestsVal = unitTests.val().trim(),
            manualTestsVal = manualTests.val().trim(),
            flsVal = fls.val().trim(),
            xssVal = xss.val().trim();
        if (crossModuleImpactVal.length == 0 || unitTestsVal.length == 0 || manualTestsVal.length == 0 || flsVal.length == 0 || xssVal.length == 0) {
            isValid = false;
            elm.preventDefault();
            alert("Cross Module Impact, Unit Tests, Manual Tests, FLS, Stored / Reflected XSS values must be set to submit this pull request.");
            if (crossModuleImpactVal.length == 0) {
                $("#desc_crossModuleImpact").focus();
            }
            else if (unitTestsVal.length == 0) {
                unitTests.focus();
            }
            else if (manualTestsVal.length == 0) {
                manualTests.focus();
            }
            else if (flsVal.length == 0) {
                fls.focus();
            }
            else if (xssVal.length == 0) {
                xss.focus();
            }
        }
        else {
            descSetFormattedDescription();
        }
    }
    return isValid;
};
function descSetFormattedDescription() {
    debugger;
    var formattedDescription = "",
        formattedDescription_Html = "",
        description = $("#desc_description").val().trim(),
        contPullReqLink = $("#desc_pullReqLink").val().trim(),
        pullReqTitle = "",
        rootCause = $("#desc_rootCause").val().trim(),
        fix = $("#desc_fix").val().trim(),
        designDocLink = $("#desc_docLink").val().trim(),
        crossModuleImpact = $("#desc_crossModuleImpact").val().trim(),
        unitTests = $("#desc_unitTests").val().trim(),
        manualTests = $("#desc_manualTests").val().trim(),
        fls = $("#desc_fls").val().trim(),
        xss = $("#desc_xss").val().trim();
    if (contPullReqLink.length) {
        var pullReqSelStart = contPullReqLink.indexOf("/pull-requests/") + 15;
        if (pullReqSelStart >= 15) {
            var pullReqSelEnd = contPullReqLink.indexOf("/", pullReqSelStart);
            if (pullReqSelEnd == -1) {
                pullReqSelEnd = contPullReqLink.length;
            }
            pullReqTitle = " " + contPullReqLink.substring(pullReqSelStart, pullReqSelEnd);
        }
        if (description.length) {
            description += "\n";
        }
        pullReqTitle = "Pull Request" + pullReqTitle;
    }
    formattedDescription = descGetSectionDetail(false, "Description", description
                                                + (pullReqTitle.length == 0 ? "" : "Continuation of " + descLinkify(false, contPullReqLink, pullReqTitle) + "."));
    formattedDescription_Html = descGetSectionDetail(true, "Description", description
                                                     + (pullReqTitle.length == 0 ? "" : "Continuation of " + descLinkify(true, contPullReqLink, pullReqTitle) + "."));
    formattedDescription += descGetSectionDetail(false, "Root Cause", rootCause);
    formattedDescription_Html += descGetSectionDetail(true, "Root Cause", rootCause);
    formattedDescription += descGetSectionDetail(false, "Fix", fix);
    formattedDescription_Html += descGetSectionDetail(true, "Fix", fix);
    formattedDescription += descGetSectionDetail(false, "Design Document Link", descLinkify(false, designDocLink, null));
    formattedDescription_Html += descGetSectionDetail(true, "Design Document Link", descLinkify(true, designDocLink, null));
    formattedDescription += descGetSectionDetail(false, "Cross Module Impact", crossModuleImpact, true);
    formattedDescription_Html += descGetSectionDetail(true, "Cross Module Impact", crossModuleImpact, true);
    formattedDescription += descGetSectionTitle(false, "Test Reports");
    formattedDescription_Html += descGetSectionTitle(true, "Test Reports");
    formattedDescription += descGetSectionDetail(false, "Unit Tests", unitTests, true, true);
    formattedDescription_Html += descGetSectionDetail(true, "Unit Tests", unitTests, true, true);
    formattedDescription += descGetSectionDetail(false, "Manual Tests", manualTests, true, true);
    formattedDescription_Html += descGetSectionDetail(true, "Manual Tests", manualTests, true, true);
    formattedDescription += descGetSectionTitle(false, "Security Reports");
    formattedDescription_Html += descGetSectionTitle(true, "Security Reports");
    formattedDescription += descGetSectionDetail(false, "FLS", fls, true, true);
    formattedDescription_Html += descGetSectionDetail(true, "FLS", fls, true, true);
    formattedDescription += descGetSectionDetail(false, "Stored / Reflected XSS", xss, true, true);
    formattedDescription_Html += descGetSectionDetail(true, "Stored / Reflected XSS", xss, true, true);
    formattedDescription = formattedDescription.trim();
    $("#id_description").val(formattedDescription); // this needs to be set while submitting pull request
    $(".ProseMirror").html(formattedDescription_Html); // set bitbucket description editor
}
function descGetSectionTitle(isHtml, title, isSubSection) {
    var level = (isSubSection ? "#" : "") + "## ";
    if (isHtml) {
        level = isSubSection ? "3" : "2";
        return "<h" + level + ">" + title + ":</h" + level + ">";
    }
    else {
        return level + title + ":\n\n";
    }
}
function descGetSectionDetail(isHtml, title, detail, isRequired, isSubSection) {
    var sectionDoc = "";
    if (isRequired || detail.length) {
        if (detail.length == 0) {
            detail = (isHtml ? "<br>" : "\n");
        }
        sectionDoc = descGetSectionTitle(isHtml, title, isSubSection);
        if (isHtml) {
            sectionDoc += "<p>" + detail.replace(/\n/g, "</p><p>") + "</p>";
        }
        else {
            sectionDoc += detail.replace(/\n/g, "\n\n") + "\n\n";
        }
    }
    return sectionDoc;
}
function descLinkify(isHtml, link, title) {
    if (link.length) {
        if (title === null) {
            title = link;
        }
        if (isHtml) {
            return '<a href="' + link + '">' + title + "</a>";
        }
        else {
            return "[" + title + "](" + link + ")";
        }
    }
    return "";
}
function descShowHideFormatterFields() {
    var showFields = false;
    if ($('#id_description_group:hidden').size() == 1) {
        $('.desc_chkSetDescription')[0].checked = false;
        $('.desc_btnShowHideFormatterFields').val("Show Formatting Fields");
    } else {
        showFields = true;
        $('.desc_chkSetDescription')[0].checked = true;
        $('.desc_btnShowHideFormatterFields').val("Hide Formatting Fields");
    }
    if ($('#desc_description').size() == 1) {
        if (showFields) {
            $('#id_description_group').hide();
            $('.desc_group').show();
        } else {
            $('#id_description_group').show();
            $('.desc_group').hide();
        }
    }
}
(function() {
    'use strict';
    descAddControls();
    $('#desc_description').val($('#id_description').val());
})();

**Comment by derjanb** [comment]
Not sure what the issue. The bitbucket instance that I have access to ,don't even has a HTML with id "id_description". Please double check the code. Maybe wait for the element to appear. 🤷
