### ISSUE TITLE
GM_webRequest not valid

### ISSUE THREAD

**Issue by damelco** [Tampermonkey/tampermonkey#1694]
(Please fill out the issue template with your details)

## Expected Behavior
GM_webRequest functional

## Actual Behavior
GM_webRequest not valid

## Specifications

- FF: 102.5.0esr (64-bit)
- TM: 4.18.1
- OS: Win7.1

## Script

// @grant          GM_webRequest

esLint: userscripts/no-invalid-grant - 'GM_webRequest' is not a valid @grant argument

has this been removed ... or have I overlooked something!

-DJ

**Comment by double-beep** [comment]
@derjanb seems [your fork](https://github.com/derjanb/eslint-plugin-userscripts) is outdated - why don't you use the main repo? All the changes you've made have been incorporated into it anyways.

**Comment by derjanb** [comment]
`GM_webRequest` is still experimental and available only at some Tampermonkey versions.

It's also not listed here: https://www.tampermonkey.net/documentation.php

**Comment by derjanb** [comment]
Also `GM_webRequest` needs to be re-implemented for Manifest v3. Please check #397 for future progress.

**Comment by damelco** [comment]
okay??
so ... what "versions" is it available in?
I would like to "experiment"
;)

-DJ

**Comment by damelco** [comment]
so far, script BLOCKING and REDIRECT seem very promising ...
however sub-frame requests are ignored.
have not tried xhr or websocket yet.

thank you for where you have it so far!
very cool.

-DJ
