### ISSUE TITLE
GM_download ignores name parameter when in Browser API mode.

### ISSUE THREAD

**Issue by skygate2012** [Tampermonkey/tampermonkey#1695]
## Expected Behavior
Downloads the image into random.jpg

## Actual Behavior
Downloads the image in its original filename. Prefixing subfolder has no effect as a consequence. Renaming works in Native download mode. But it doesn't support subfolders.
## Specifications

- Chromium: 109.0.5414.120
- TM: v4.18.1
- OS: Windows 10.0.19044

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://picsum.photos/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=picsum.photos
// @grant        GM_download
// ==/UserScript==

(function() {
    'use strict';

    GM_download({url: "https://picsum.photos/200/300", name: "random.jpg"});
})();
```

**Comment by derjanb** [comment]
Working fine here so far. It always works on Ubuntu and it worked on Windows 10 except one time where the name was ignored. I tend to say that this is a browser bug, because I can't do more than passing the wanted filename...

**Comment by derjanb** [comment]
![image](https://user-images.githubusercontent.com/767504/215474303-fdd60218-4d2b-46ae-9366-da3f3b8bd67c.png)

**Comment by derjanb** [comment]
Maybe related: 

* https://bugs.chromium.org/p/chromium/issues/detail?id=1008884
* https://bugs.chromium.org/p/chromium/issues/detail?id=1122898
