### ISSUE TITLE
GM_registerMenuCommand fires a function only in one iframe, instead of in top doc and all iframes

### ISSUE THREAD

**Issue by JakubMarcinkowski** [Tampermonkey/tampermonkey#1696]
## Expected Behavior
GM_registerMenuCommand fires a function in top document and all iframes.

## Actual Behavior
GM_registerMenuCommand fires a function in one iframe.
https://www.aliexpress.com/w/wholesale-example.html
Adding "// @noframes" fires function in top document, but disables working in all iframes.

## Specifications

- Chrome: (i.e. 108.0.5359.126 (64-bit))
- TM: (i.e. 4.18.1)
- OS: (i.e. Win 10)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Example
// @version      0.1
// @description  try to take over the world!
// @match        *://*/*
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
  'use strict';
  console.log(document.body);

  function example() {
    console.log(document.body);
  }

  if (GM_registerMenuCommand) GM_registerMenuCommand("Example", () => example());
})();
```

**Comment by 7nik** [comment]
There is a conception error in your code: GM_registerMenuCommand overrides the previously registered commands with the same name, so only the last call is effective.

You need to call the function only once in the context (iframe/top doc.) you need or, if you need to run the code in multiple contexts, register it once at the top level and coordinate the usercript instances (maybe via `postMessage`).

**Comment by JakubMarcinkowski** [comment]
Thanks, for very valuable info about GM_registerMenuCommand.
And an advice about postMessage, however I wasn't able to use it reliably with iframes of different origins.

But thanks to that I found
https://stackoverflow.com/questions/11769066/how-can-two-instances-of-a-userscript-communicate-between-frames
and now I am using GM_addValueChangeListener, so far seems to work fine.

```
// ==UserScript==
// @name         Example
// @version      0.1
// @description  try to take over the world!
// @match        *://*/*
// @grant        GM_registerMenuCommand
// @grant        GM_setValue
// @grant        GM_addValueChangeListener
// ==/UserScript==

(function() {
  'use strict';

  GM_addValueChangeListener("Example", doSomething);

  function doSomething() {
    console.log(document.body);
  }

  if (window.top === window.self) {
    GM_registerMenuCommand("Example", () => GM_setValue("Example", Date.now()));
  }
})();
```
