### ISSUE TITLE
All scripts wiped by Firefox browser 

### ISSUE THREAD

**Issue by Alexwsa** [Tampermonkey/tampermonkey#1698]
![image (1)](https://user-images.githubusercontent.com/124128171/215970753-2cc80c45-8f2e-48ba-8c6c-91f73857abbd.png)

## Expected Behavior
Scripts present at Firefox login

## Actual Behavior
Scrips dissapeard

## Specifications

- Firefox: 102.7.0esr (64-bit)
- TM: v4.18.1
- OS: Windows 10 Enterprise 21H2 19044.2486

## Script

(Please give an example of the script if applicable.)

N/A
Affecting all scripts
![image (1)](https://user-images.githubusercontent.com/124128171/215970864-09068997-6da0-48cf-a14a-fe99ea417512.png)

```

**Comment by derjanb** [comment]
Unfortunately there is nothing I can do for you. The messages says it all. 
The extension's database got corrupted (by a system crash, browser bug, storage failure, idk...) and the browser reset it to an empty state. 🤷
Please use your backup to restore them.
