### ISSUE TITLE
What is GM_info.script.evilness, .sync and .unwrap?

### ISSUE THREAD

**Issue by martixy** [Tampermonkey/tampermonkey#1701]
Most properties of GM_info are clear by their naming or contents.

But there are a few weird ones with no clear purpose and docs are unhelpful.
What are the following properties:
`GM_info.script.evilness`  
`GM_info.script.sync`  
`GM_info.script.unwrap`
?

## Specifications

- Chromium: v109
- TM: v4.19.6176
- OS: W10

**Comment by derjanb** [comment]
`evilness` and `sync` will be removed. 
`unwrap` represents [`@unwrap`](http://tmnk.net/documentation.php#meta:unwrap)
