### ISSUE TITLE
Some bug of `Sandbox Mode` and `Modify existing content security policy (CSP) headers`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#1704]
(Please fill out the issue template with your details)

### TM 4.19.6177 BETA
`Modify existing content security policy (CSP) headers` cannot be set to `Yes`, it will be forced to `Remove entirely (possibly unsecure)` after saving.
![csp](https://user-images.githubusercontent.com/15855068/217735146-b5d4e05a-08da-4bc4-8fa1-41bc2e233dca.jpg)

### TM 4.18.1 & TM 4.19.6177 BETA
When `Sandbox Mode` is set to `Force DOM` and accessing the website that applies the CSP policy, the following error will be reported: 
```log
Uncaught TypeError: Cannot read properties of undefined (reading 'userScripts')
```
![e1](https://user-images.githubusercontent.com/15855068/217734606-3842e3dd-b678-403b-b78b-873ce63c2a7d.jpg)

## Specifications

- Chromium: (i.e. 64.0.3282.140) Chromium: 110.0.5481.77
- TM: (i.e. 4.5.5648) TM 4.18.1 & TM 4.19.6177 BETA
- OS: (i.e. MacOS 10.13.4) Win10

**Comment by derjanb** [comment]
> `Modify existing content security policy (CSP) headers` cannot be set to `Yes`

In fact, the option only is removed (and `Remove entirely (possibly unsecure)` used as next possible value) if the value is set to `Yes`.

> Uncaught TypeError: Cannot read properties of undefined (reading 'userScripts')

This is a cosmetic issue. All scripts should work fine.

Both will be fixed at the next BETA. Thanks for reporting.

**Comment by F9y4ng** [comment]
> In fact, the option only is removed (and `Remove entirely (possibly unsecure)` used as next possible value) if the value is set to `Yes`.

In TM4.18.1, the option `YES` does not take effect on some sites that apply CSP policies, such as https://rss.rssforever.com/i/, but  `Remove entirely (possibly unsecure)` is ok. Maybe `YES` option can be removed in TM4.19.xxxx BETA.

> This is a cosmetic issue. All scripts should work fine.

Yes, all scripts work fine, only the console reports this error.

> Both will be fixed at the next BETA. Thanks for reporting.

thank you.

**Comment by F9y4ng** [comment]
It works fine at v4.19.6178, thanks.
