### ISSUE TITLE
Documentation for GM_listValues is wrong

### ISSUE THREAD

**Issue by piyushsoni** [Tampermonkey/tampermonkey#1708]
The documentation for GM_listValues present at [https://www.tampermonkey.net/documentation.php?locale=en#api:GM_listValues](https://www.tampermonkey.net/documentation.php?locale=en#api:GM_listValues) says it takes a callback functio which would be called back with the list of stored values. However, that example does not work. After struggling a lot I finally found out that it just returns the list of values synchronously and no callback is required.

**Comment by piyushsoni** [comment]
Strange. Looks like the documentation has changed in last two days since I logged the issue. It seems to be fixed now with addition of a lot of **GM.** async APIs. This issue can be closed now I guess. :)

**Comment by derjanb** [comment]
Yes, I've solved the problem, but haven't had time to report back here yet.
Thanks for reporting.
