### ISSUE TITLE
Injection or execution no longer works on bluemediafile

### ISSUE THREAD

**Issue by Black-Platypus** [Tampermonkey/tampermonkey#1709]
## Expected Behavior
Going to a [BlueMediaFile(s) page](https://bluemediafile.sbs/url-generator.php?url=+F30sKVGya5zG++539sIDbsFE0AATeJuw9p6T/LZc0AndHumitDmXOU2LdZ4dXfYBq8xguXpZQ1QeNRffHpbnD26TyyYt72XKf+qnT0RuKc=) with a UserScript targeting `// @include *://bluemediafile.*/url-generator.php*` will inject and run the script

## Actual Behavior
The script does not seem to run, there appear to be no connected errors

## Specifications
- Chromium: 110.0.5481.104 (Official Build) (64-bit)
- TM: 4.18.1
- OS: Win10 x64

## Script

```js
// ==UserScript==
// @name		BlueMediaFiles go to link
// @version		1.0.2
// @namespace	BP
// @include		*://bluemediafiles.*/url-generator.php*
// @include		*://bluemediafile.*/url-generator.php*
// @run-at		document-start
// @noframes
// ==/UserScript==

console.log("wtf?");
```
(Yes, "Preserve Log" option is checked in DevTools)

**Comment by 7nik** [comment]
Works for me.

Chromium: 110.0.5481.77 (Official Build) Arch Linux (64-bit)
TM: 4.18.1
OS: Manjaro KDE

**Comment by Black-Platypus** [comment]
Ouch!
Confirmed, seems to be a filter in uBlock Origin that's interfering :/

**Comment by Black-Platypus** [comment]
Oh, FWIW: Adding the rulle
`bluemediafile.*#@#+js(abort-on-property-read, open)`
in uBlock Origin did the trick
