### ISSUE TITLE
Tampermonkey messes with keyboard shortcut in Google Docs with no scripts running

### ISSUE THREAD

**Issue by Naturally-Delicious** [Tampermonkey/tampermonkey#1711]
## Expected Behavior

I am able to use the CTRL + SHIFT + E shortcut in Google Docs Chrome Browser to center a paragraph.

## Actual Behavior

Nothing happens.

## Specifications

- Chromium: (i.e. 110.0.5481.104)
- TM: (4.18.1)
- OS: (i.e. Windows 10)

## Script

N/A, no script is running.

I disabled all my extensions. I was then able to use Ctrl + Shift + E in Google Docs website to center a paragraph. I went back into my extensions and enabled each extension one by one and tested the short cut. It worked perfectly until I enabled Tampermonkey, in which the short cut stopped working. Other shortcuts work though, like Ctrl + Shift + R/L which will align the paragraph right or left respectively. 

For now I will disable Tampermonkey while in Google Docs, however I think it is worth knowing this issue exists.

Thanks for your time.

**Comment by derjanb** [comment]
Please check if needed modify the extension shortcuts at `chrome://extensions/shortcuts`.
