### ISSUE TITLE
Allow to specify inject target in GM_addStyle to style Shadow DOM on CSP sites

### ISSUE THREAD

**Issue by AlttiRi** [Tampermonkey/tampermonkey#1714]
I want to use Shadow DOM in order to isolate my userscript's popup from the page's CSS, and the page from my popup's CSS.
Also it will hide the popup's HTML from `body.textContent`, for example.

It's easy to do for usual sites.

However, on sites with enabled CSP I need to use `GM_addStyle` to add styles. But it (TM/VM) adds the styles into the `head` element.
So, it's impossible to style Shadow DOM on these sites (for example, https://mastodon.social/home). 

I want to be able to specify the place where to inject the style element.

Like this:
```js
let shadowRootDiv = wrapper.shadowRoot.querySelector("#href-taker-shadow");
GM_addStyle(`#href-taker-shadow {color: red;}`, shadowRootDiv);
```

## Script

```js
// ==UserScript==
// @name         Shadow DOM Style
// @namespace    gh.alttiri
// @version      0.1
// @description  Adds styles to Shadow DOM on CSP site
// @match        https://mastodon.social/*
// @grant        GM_addStyle
// ==/UserScript==


let insertPlace = document.querySelector("body"); // "html"
insertPlace.insertAdjacentHTML("afterbegin", `<div id="href-taker"></div>`);
let wrapper = document.querySelector("#href-taker");
wrapper.attachShadow({mode: "open"});
wrapper.shadowRoot.innerHTML = `
<div id="href-taker-shadow">
    <style>#href-taker-shadow {color: violet;}</style>
    <span>href-taker-content</span>
</div>`;
let shadowRootDiv = wrapper.shadowRoot.querySelector("#href-taker-shadow");

function addCSS(css, target = document.body) {
    const styleElem = document.createElement("style");
    styleElem.textContent = css;
    target.append(styleElem);
    return styleElem;
}
//addCSS(`#href-taker-shadow {color: green;}`, shadowRootDiv); // Works only on sites without CSP


// It works on sites with CSP, but I need to inject CSS into the shadow DOM element, not into "head" tag.
GM_addStyle(`#href-taker-shadow {color: red;}`);

// I want this
// GM_addStyle(`#href-taker-shadow {color: red;}`, shadowRootDiv);
```

**Comment by double-beep** [comment]
This should be possible via `GM_addElement()`.

**Comment by AlttiRi** [comment]
Yeah, it works.

I just found https://github.com/Tampermonkey/tampermonkey/issues/881#issuecomment-639705679 now.

Works fine in TM and VM.

**Comment by 7nik** [comment]
There is another way, which is even more preferable when you add multiple shadows due to re-using already parsed styles
```js
const css = `#href-taker-shadow {color: red;}`;
const sheet = new CSSStyleSheet();
// you may use replace() method as well, but I had a flickering issue in FF with it
sheet.replaceSync(css);
wrapper.shadowRoot.adoptedStyleSheets = [sheet];
```
Though Safari still didn't implement `adoptedStyleSheets`, maybe it will be in version 17.
https://caniuse.com/mdn-api_document_adoptedstylesheets

Here is our actual usage of this approach with fallbacks https://github.com/evazion/translate-pixiv-tags/blob/master/translate-pixiv-tags.user.js#L920-L941
