### ISSUE TITLE
Can not use "Userscript Sync" in Edge?

### ISSUE THREAD

**Issue by bowencool** [Tampermonkey/tampermonkey#1715]
(Please fill out the issue template with your details)

## Expected Behavior

Same as Chrome.

## Actual Behavior

There is no "Userscript Sync" section on the settings page in Edge.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/20217146/220517408-de4d414b-c6fb-4f62-b6a4-2691b5a89d0a.png">

## Specifications

- User Agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50
- TM: 4.18.1
- OS: MacOS Ventura

**Comment by derjanb** [comment]
Please set "Config mode" to "Advanced".

**Comment by derjanb** [comment]
Network requests are made from the background page.

**Comment by bowencool** [comment]
> Network requests are made from the background page.

background page didn't have any network neither after clicked "Run now"

**Comment by bowencool** [comment]
This works in chrome well.

**Comment by bowencool** [comment]
Sorry, I didn't clicked "Save" before clicked "Run now".

**Comment by Outlying3720** [comment]
> Sorry, I didn't clicked "Save" before clicked "Run now".

Thanks for your solution, which worked for me too.

**Comment by silverqx** [comment]
~I have this problem now, it doesn't work in the latest Edge, it ends up with `Please wait...` spinner infinite, Chrome and FF works fine~

After Edge update and restart it works fine, some weird glitch.
