### ISSUE TITLE
ISSUE - Requiring a file containing an export

### ISSUE THREAD

**Issue by Malix-Off** [Tampermonkey/tampermonkey#1717]
## Problem

Requiring a file containing an export causes an "`Unexpected token 'export'`" error
![image](https://user-images.githubusercontent.com/76160668/220612859-cd3dbc6b-8853-48ad-8047-b7adf4a68e88.png)
![image](https://user-images.githubusercontent.com/76160668/220611802-1370111e-6634-4058-9e34-c5bd4e3eba2e.png)

The userscript is not even running after it.

## Exemple

Requiring the firebase-app.js v9 files such as the [firebase-app.js v9.17.1 file](https://www.gstatic.com/firebasejs/9.17.1/firebase-app.js)
```js
// ==UserScript==
// @name         Firebase Implementation Example
// @version      1.0.0
// @description  Firebase Implementation Example
// @author       -
// @match        https://github.com/*
// @require      https://www.gstatic.com/firebasejs/9.17.1/firebase-app.js
// ==/UserScript==

(function() {

	'use strict';

	console.log("Tampermonkey: \"Firebase Implementation Exemple\" script start");

})();
```

**Comment by Malix-Off** [comment]
@derjanb do you know if there is a workaround?
This issue is completely blocking our production

**Comment by 7nik** [comment]
There is just no way to use ES modules in userscripts.

The best you can do is to use dynamic import:
```js
(async function() {

	'use strict';

        const firebase = await import("https://www.gstatic.com/firebasejs/9.17.1/firebase-app.js");

	console.log("Tampermonkey: \"Firebase Implementation Exemple\" script start", firebase);

})();
```

Another way is to build Firebase locally as UMD and host somewhere. 
Or build the entire userscript locally and ship compiled and tree-shaked code. There even are plugins for bundlers.

**Comment by derjanb** [comment]
> The best you can do is to use dynamic import:

Good idea! That was fast. :-) Thanks.

@Malix-Off 

`export` needs type `module` which is incompatible with Tampermonkey's sandbox.

Please use webpack as explained [here](https://firebase.google.com/docs/web/setup) to bundle your script.

or manually add a script tag. This (and dynamic import) however makes your code completely public to the page and works on pages with no CSP only!

```ts
// ==UserScript==
// @name         Firebase Implementation Example
// @version      1.0.0
// @description  Firebase Implementation Example
// @author       -
// @match        https://example.com/*
// @grant        GM_addElement
// ==/UserScript==

const s = GM_addElement('script', { textContent: `
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js";

window.initializeApp = initializeApp;
runOnLoad();
`, type: 'module' });

unsafeWindow.runOnLoad = () => console.log(unsafeWindow.initializeApp);
```

**Comment by Malix-Off** [comment]
Hello again @derjanb and @7nik and thanks you both for your answer, the dynamic import workaround did the trick.

@derjanb, from [your comment](https://github.com/Tampermonkey/tampermonkey/issues/1717#issuecomment-1439945811) i tried to bundle it with [this guide](https://firebase.google.com/docs/web/module-bundling), but i didn't found a workaround to make it work for an userscript unfortunately

**Comment by 7nik** [comment]
How exactly have you made the bundle?

I had a really good experience using [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey) to develop and build a userscript (TS + Svelte in my case)

**Comment by Malix-Off** [comment]
> How exactly have you made the bundle?
> 
> I had a really good experience using [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey) to develop and build a userscript (TS + Svelte in my case)

Hello again!

I'm currently doing the same thing now ahah, thanks for your advices <3
