### ISSUE TITLE
Always create a error log message on syntax errors

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1718]
(Please fill out the issue template with your details)

## Expected Behavior
Scripts load where they match

## Actual Behavior
Scripts listed in TM extension submenu, but don't appear in loaded JS sources

## Specifications

- FF 110.0
- TM: 4.18.1
- OS: Windows 11.22621

## Script

No example, not source code related (have run recently without code changes), also the browser had no recent updates or settings changes. This bug occurs on more previously working scripts simultaneously.
Some but not all of installed scripts stopped to load on matched URLs. Only sign of malfunction are warnings in developer console like this:
`09:59:24.992 injected: env: missing script "840d0dfb-4c5b-4dbb-8c02-bf0651148d40"! [content.js:8:1224](moz-extension://3cbb711c-422e-4056-919d-17aab1f155b6/content.js)`
By the ID I can locate the script, it's enabled and exposes no visible issues, I still can open the "missing" script in editor and make changes. On the hosted page it's shown as active in TM button's submenu, but in Dev tools/Sources window the script is not listed under Tampermonkey branch. This problem does not exist in Chrome so far.

**Comment by derjanb** [comment]
This happens for example on syntax errors. Do you see error mesasges befor the `missing script` log message?

**Comment by trumpeta** [comment]
No error messages, the manual syntax check in editor passes (less severe issues only).

**Comment by derjanb** [comment]
Do these scripts have a `@sandbox` or `@inject-into` tag?

What are the config values of the following settings:
* `Content Script API`
* `Sandbox Mode` and
* `Inject Mode`

This might help to get an idea where the bug is located.

**Comment by trumpeta** [comment]
@sandbox and @inject-into attributes undefined in concerned scripts

Global settings:
Content Script API: User scripts API
Sandbox Mode: Default
Inject Mode: Default

**Comment by derjanb** [comment]
I found some places that silently ignored syntax errors.
Should be fixed at 4.19.6178 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
