### ISSUE TITLE
zoom & mirror image wont work in fullscreen

### ISSUE THREAD

**Issue by seriousgigi** [Tampermonkey/tampermonkey#1719]
## Expected Behavior

zoom & mirror image should work in fullscreen

## Actual Behavior

zoom & mirror image wont work in fullscreen

## Specifications

- opera: Version:95.0.4635.46 and 96.0.4693.20
- Windows 10 IoT Enterprise LTSC

## Script

(Please give an example of the script if applicable.)

**Comment by 7nik** [comment]
Tampermonkey is just a userscript manager. Please get in touch with the script developers about the error. If there is a general problem with Tampermonkey, they will come back here.

**Comment by seriousgigi** [comment]
> Tampermonkey is just a userscript manager. Please get in touch with the script developers about the error. If there is a general problem with Tampermonkey, they will come back here.

yeah it is my bad i opened this thread in a wrong section :)
