### ISSUE TITLE
all tampermonkey's script didn't work on domain douyin.com

### ISSUE THREAD

**Issue by FollowTheTrend** [Tampermonkey/tampermonkey#1720]
all tampermonkey's script didn't work on douyin.com.
console print error message. 
![f12 console print ](https://cdn.jsdelivr.net/gh/FollowTheTrend/cdn/static/image/202302261628188.png)

https://www.tampermonkey.net/faq.php#Q208
I tried all ways, but failed.
reinstalls tampermonkey or chrome, but failed.
Please help me, thanks.

## Expected Behavior
 tampermonkey's script work on domain douyin.com

## Actual Behavior
I have 6 scripts, they works fine.
But all tampermokey script didn't work on domian douyin.com

f12 console print 
![](https://cdn.jsdelivr.net/gh/FollowTheTrend/cdn/static/image/202302261635597.png)
![](https://cdn.jsdelivr.net/gh/FollowTheTrend/cdn/static/image/202302261631676.png)

## Specifications

 (Chromium 102.0.5005.167)
- TM: (4.18.1)
- OS: ( win10 19044)

## Script

script install url 
 https://palerock.cn/node-service/scripts/install/@hook-js_timer/hook.timer.user.js
 
other script also work failed on domian douyin.com.

**Comment by derjanb** [comment]
This is working fine here. Please try [the BETA version](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf).

**Comment by FollowTheTrend** [comment]
It's working, thanks a lot.
