### ISSUE TITLE
Hi can any on give advice 

### ISSUE THREAD

**Issue by BIGB69666** [Tampermonkey/tampermonkey#1726]
https://github.com/BIGB69666/Chicken-workout/issues/2#issuecomment-1451530255

**Comment by 7nik** [comment]
1. It's rude to create multiple uninformative issues that don't report TM's problems or ask for features.
2. How will somebody help you if you link a private repo?
3. I doubt it is the appropriate place to ask for help. Instead, you can use StackOverflow or at least the discussion section here.
