### ISSUE TITLE
`openInTab()` with data URL or blob URL does not work in Firefox for Linux

### ISSUE THREAD

**Issue by chipzhang** [Tampermonkey/tampermonkey#1727]
(Please fill out the issue template with your details)

## Expected Behavior
When the script is triggered, a new tab with blob URL will open

## Actual Behavior
Nothing happens

## Specifications

- Firefox: 102.8.0esr (64-bit)
- TM: v4.18.1
- OS: Linux

## Script

```js
// ==UserScript==
// @name              Example
// @namespace         https://github.com/chipzhang
// @author            ChipZhang
// @match             *://*/*
// @version           0.0.1
// @run-at            document-end
// @grant             GM_openInTab
// ==/UserScript==

function openDataInTab(text) {
	const blob = new Blob([text], {type: 'text/plain'})
	const url = URL.createObjectURL(blob)
	GM_openInTab(url)
}

openDataInTab('abcdefg')

```

## Moreover

Data URLs do not work either.

**Comment by derjanb** [comment]
Can't be fixed without browser support: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url

Sorry.
