### ISSUE TITLE
ISSUE: Unclear Difference Between `@include` and `@match`

### ISSUE THREAD

**Issue by Malix-Off** [Tampermonkey/tampermonkey#1732]
Hello!

Even if I try, I do not understand the difference between [`@include`](https://www.tampermonkey.net/documentation.php#meta:include) and [`@match`](https://www.tampermonkey.net/documentation.php#meta:match).
Could someone enlighten me please?

Thanks <3

**Comment by derjanb** [comment]
`@match` requires another syntax that is described here: https://developer.chrome.com/docs/extensions/mv2/match_patterns/

**Comment by Malix-Off** [comment]
> Which one would you recommend, and also, i don't really see their syntax difference?

**Comment by derjanb** [comment]
> Which one would you recommend,

`@match` cause it's more difficult to accidentally match wrong URLs.
