### ISSUE TITLE
feature: save page as single file

### ISSUE THREAD

**Issue by tgowing** [Tampermonkey/tampermonkey#1743]
First of all thank you so much for the amazing extension!
We would like to save the page as mhtml or html + the resources folder.

We couldn't find such an API in Tampermonkey. Would it be possible to be implemented?

**Comment by jb222** [comment]
This is possible in Chrome, and probably in other browsers.

**Comment by derjanb** [comment]
Please try this https://support.google.com/chrome/answer/7343019

**Comment by 7nik** [comment]
99.99% of userscript users and devs don't need this feature ever. And implementing it is full of various pitfalls.

Use an appropriate tool like [Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof) or [Save Webpages Offline As MHTML](https://chrome.google.com/webstore/detail/save-webpages-offline-as/nfbcfginnecenjncdjhaminfcienmehn). Also check the Related tab - maybe there is a better tool for your task.

**Comment by 7nik** [comment]
I don't use them.

Many of them provide shortcuts, and you can try to trigger them.

Also, Save Page WE claim to be able to save multiple pages in one action:
> • Load a file containing a list of URLs in the Zoom Page WE Options dialog and then select the 'Save Listed URLs' menu item.

>There is an option to use automation mode, allowing a page to be saved from the command line.



You can go through these and similar extensions, read what they can do, test how well they save pages, and select the best extension.
