### ISSUE TITLE
WebDAV syncing doesn't work with nginx

### ISSUE THREAD

**Issue by majutsushi** [Tampermonkey/tampermonkey#1750]
Tampermonkey doesn't send a `/` at the end of the URL when sending the `MKCOL` command. The RFC says that clients SHOULD do that:

> In general, clients SHOULD use the trailing slash form of collection names.  If clients do not use the trailing slash form the client needs to be prepared to see a redirect response.

https://www.rfc-editor.org/rfc/rfc4918#section-5.2

nginx expects a `/` in the request and fails if it's not present:
```
1.2.3.4 - user [28/Mar/2023:23:54:04 +0200] "OPTIONS /dav HTTP/1.1" 404 125 "-" "Tampermonkey"
1.2.3.4 - user [28/Mar/2023:23:54:05 +0200] "PROPFIND /dav/Tampermonkey HTTP/1.1" 404 125 "-" "Tampermonkey"
1.2.3.4 - user [28/Mar/2023:23:54:05 +0200] "MKCOL /dav/Tampermonkey HTTP/1.1" 409 151 "-" "Tampermonkey"
```
```
2023/03/28 23:54:05 [error] 2622129#2622129: *158691 MKCOL can create a collection only, client: 1.2.3.4, server: _, request: "MKCOL /dav/Tampermonkey HTTP/1.1", host: "myhost"
```

This causes Tampermonkey to show an "Error: Action failed" error dialog when attempting an export to a WebDAV server.

## Expected Behavior

Tampermonkey sends a `/` at the end of collection-related WebDAV request URLs

## Actual Behavior

No `/` at the end of collection URLs

## Specifications

- Firefox: 111.0.1
- TM: 4.18.1
- OS: Debian unstable

**Comment by derjanb** [comment]
Thanks for reporting.

This should be fixed at 4.19.6181 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
