### ISSUE TITLE
Feature request: Present a confirmation dialog when clicking the trash icon on the script list

### ISSUE THREAD

**Issue by DanKaplanSES** [Tampermonkey/tampermonkey#1751]
## Expected Behavior
I mis-click the trash icon to delete a userscript, it pops up a confirmation dialog asking me if I'm sure, if I click the cancel button, the userscript is not deleted. 

## Actual Behavior
I mis-click the trash icon to delete a userscript, it says, "operation completed successfully", and now I have to rewrite that script.

## Specifications

- Firefox: 111.0.1 (64-bit)
- TM: 4.18.1
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

n/a

**Comment by derjanb** [comment]
Note: If the default settings are active, the recycle bin is also activated. The script will then be moved there.

**Comment by derjanb** [comment]
This should be fixed at 4.19.6181 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Note: if the trash is enabled the script is still moved to the trash without further confirmation, but the notification text was adapted to this fact.

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by jb222** [comment]
I just tried this in Chrome (Mac). The recycle bin icon is hardly visible and too big.
![Screen Shot 2023-05-11 at 13 24 07](https://github.com/Tampermonkey/tampermonkey/assets/61352184/831d1898-97c3-4099-bb2e-0f56ce1e8e0c)
