### ISSUE TITLE
[Firefox, Android] GM_openInTab ignores options 

### ISSUE THREAD

**Issue by oll37** [Tampermonkey/tampermonkey#1755]
It's not possible to open a tab in the background using 
```
GM_openInTab('https://google.com', { loadInBackground: true, insert: true })
```
or
```
GM_openInTab('https://google.com', { active: false, insert: true })
```

The new tab is always active and will be added to the end of the tab list.

## Specifications

- Firefox: 112.0b9
- TM: 4.18.1
- OS: Android 13

**Comment by derjanb** [comment]
It's a Fenix bug. 🤷 According to the bug report it works in Fennec.

https://bugzilla.mozilla.org/show_bug.cgi?id=1813931
