### ISSUE TITLE
Accessing more browser permissions

### ISSUE THREAD

**Issue by tgowing** [Tampermonkey/tampermonkey#1756]
What's the best way to access more browser permissions in a Tampermonkey script? We would like to have access to the `chrome.debugger` APIs, for example.

Would this be possible?

/cc @ionicabizau

**Comment by 7nik** [comment]
This API requires `debugger` permission which TM does not have. TM has only the following permissions:
`chrome://favicon/`
`clipboardWrite`
`contextMenus`
`cookies`
`declarativeContent`
`idle`
`notifications`
`storage`
`tabs`
`unlimitedStorage`
`webNavigation`
`webRequest`
`webRequestBlocking`
`<all_urls>`

If you need anything beyond these permissions, the solution is to create an extension with whatever permissions you need.

**Comment by derjanb** [comment]
Tampermonkey "wraps" different browser APIs. It is not designed to give direct access to them. So please post a use case that is not possible to implement at the moment using Tampermonkey and suggest how a new API could look like.
