### ISSUE TITLE
I need to see deleted messages logs (discord) 

### ISSUE THREAD

**Issue by AuryAury** [Tampermonkey/tampermonkey#1759]
I've deleted my discord messages with tamper monkey a week ago, I need to review my messages in the most absolute way because there were written very important things that I need for vital matters. 
I need to go back to the logs that you see when you delete the messages, where are they saved? How can I see them? 
Or at least is there a way to see the Google listing as it was as soon as it deleted the messages? 
You understood the request I think. 
Is there maybe a script that I can use to restore the logs? Please help me, everyone, who can help me helps me
 @derjanb 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by 7nik** [comment]
Tampermonkey is just a userscript manager. Please get in touch with the script developers about your problem.
I suppose it is here https://github.com/victornpb/undiscord/discussions/
