### ISSUE TITLE
UserScript without @match should run on all pages

### ISSUE THREAD

**Issue by Vampire** [Tampermonkey/tampermonkey#1766]
In Firefox I use GreaseMonkey, in Chrome TamperMonkey.
I copied over below UserScript that I use since years successfully in GreaseMonkey that makes code in the web actually properly readable in most situations, no matter what that page author decided to use as code font.
As this should work just everywhere, it has not `@match` tag which works fine in GreaseMonkey to just be effective everywhere, but in TamperMonkey it then is not executed anywhere.
I had to add `@match         *://*/*` in the TamperMonkey version to have it effective everywhere.

## Expected Behavior

A UserScript without `@match` tag should run on any page.

## Actual Behavior

A UserScript without `@match` tag is run nowhere.

## Specifications

- Chrome: 112.0.5615.121
- TM: 4.18.1
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name          Configured Monospace Font Everywhere
// @description	  Uses the configured monospace font everywhere
// @author        Vampire
// @version       1.0
// ==/UserScript==
(function() {var css = [
  // General tags
	"pre, code, samp, tt, kbd:not(.badmono), ",
  // ViewVC
  ".vc_file_line_number, .vc_file_line_text, .vc_diff_chunk_extra, .vc_diff_add, .vc_diff_remove, .vc_diff_change, .vc_diff_nochange, .vc_diff_line_number, .vc_idiff_add, .vc_idiff_change, .vc_idiff_remove, ",
  // GitHub
	".blob-code-inner, .blob-num",
  "{",
	"    font-family: monospace !important;",
	"}",
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
  }
}
})();
```

**Comment by derjanb** [comment]
Running without a single `@match` or `@include` is counter-intuitive and even can open security holes (e.g. intentional misspelling).

That's why this behavior was changes in 2016.
http://tmnk.net/changelog.php?show=gcal&more=true#v4.0.5090
