### ISSUE TITLE
no script is running

### ISSUE THREAD

**Issue by youngunix** [Tampermonkey/tampermonkey#1769]
Hello, 

I installed a script, enabled it but it's not running! Every site I go to and click on the extension it says "no script is running". 

## Expected Behavior
Run the installed script.

## Actual Behavior
The installed script is not running.

## Specifications

- Firefox: 112.0.1
- TM: 4.18.1
- OS: Gentoo
- 
## Script

I'm using [this](https://openuserjs.org/scripts/triceratops1/Navigator_Platform_Hider).

```js
// ==UserScript==
// @name        Navigator Platform Hider
// @namespace   meh
// @description fake your platform when browsing
// @include     *
// @version     1.1
// ==/UserScript==
```

**Comment by derjanb** [comment]
Working fine here in Ubuntu using FF 112.0.1 (64-bit) and TM: 4.18.1.

Please try a new temporary profile.

**Comment by youngunix** [comment]
Tried a fresh new profile and got the same results.
