### ISSUE TITLE
cannot open ui.tampermonkey.net in safari

### ISSUE THREAD

**Issue by EricE549X** [Tampermonkey/tampermonkey#1770]
## Expected Behavior

opens page like normal

## Actual Behavior

<img width="1552" alt="Screenshot 2023-04-24 at 5 35 43 AM" src="https://user-images.githubusercontent.com/86898409/233959071-a997a608-0129-4c24-84e1-a856112d1fbc.png">

## Specifications

- Safari: 16.4
- TM: 4.17.6162
- OS: macOS 13.3.1

## Script

[example script](https://ui.tampermonkey.net/ask.html?aid=f7ab8131-d090-4503-a0eb-4d17c1de0637) (affects all pages, including dashboard)

**Comment by derjanb** [comment]
I'm already working on a fix. Sorry for any inconvenience.

**Comment by EricE549X** [comment]
thanks
