### ISSUE TITLE
Script does not work in macOS Safari

### ISSUE THREAD

**Issue by umbrella-k** [Tampermonkey/tampermonkey#1773]
Hello,
I purchased Tampermonkey for Mac OS Safari and ran the script Good Twitter 2, which shows a badge indicating that it is running, but does not change the appearance.
It worked fine on Mac OS Chrome. I am not familiar with the script so I don't know why this problem occurs.
The script is at the following URL https://github.com/Bl4Cc4t/GoodTwitter2

## Expected Behavior

Run the installed script.

## Actual Behavior

The installed script is not running.

## Specifications

- Safari: 16.4
- TM: 4.17.6162
- OS: macOS 13.3.1

## Script

https://github.com/Bl4Cc4t/GoodTwitter2/raw/master/twitter.gt2eb.user.js

**Comment by codeninja-ru** [comment]
I guess all the scripts aren’t working on twitter because of the CSP policy

**Comment by derjanb** [comment]
Will be fixed at the next version.

**Comment by derjanb** [comment]
Fixed 4.20.6184 which is currently rolled out. Thanks for reporting.
