### ISSUE TITLE
Enhancement: Editor Header & Body

### ISSUE THREAD

**Issue by KominoStyle** [Tampermonkey/tampermonkey#1780]
It would be great if we could enhance the editor by separating the script header into a dedicated header area, while keeping the code in the body area. This way, we can conveniently make changes using a simple shortcut like "Select All" and "Paste," without affecting the header section.

By having a clear distinction between the script header and the code, it becomes easier to manage and modify specific sections of the script. We can ensure that the header remains intact with its "// ==UserScript==" starting and ending markers, while freely editing the code portion as needed. This would streamline the editing process and provide a more organized structure for working with user scripts.

**Comment by derjanb** [comment]
I think the current format is a better solution for the following reasons:

Consistency: The current format has been in place for a while, users may be accustomed to it. A sudden change could cause confusion or frustration, and there would be a learning curve for users to understand the new structure.

Simplicity: Separating the header and the code require additional coding, error handling, and maintenance, which could potentially introduce bugs or complications.

Ease of Export and Import: Having a unified format for the script ensures that it can be easily copied, pasted, or transferred as a single entity. Separating the header might cause difficulties when trying to share or move scripts between different environments.
