### ISSUE TITLE
FreeBSD: runtime.getPlatformInfo returns undefined

### ISSUE THREAD

**Issue by Remilia-NULL** [Tampermonkey/tampermonkey#1785]
## Expected Behavior
Extensions work

## Actual Behavior
Extensions not work
![Screenshot_20230602_100306](https://github.com/Tampermonkey/tampermonkey/assets/34256856/89d6d61e-9b06-45d4-ad0b-56c3c409da47)
![Screenshot_20230602_101223](https://github.com/Tampermonkey/tampermonkey/assets/34256856/291214a1-ef13-490b-8f5a-8257dd80a2d1)

## Chromium error
Uncaught (in promise) TypeError: Cannot destructure property 'arch' of '(intermediate value)' as it is undefined.

![Screenshot_20230602_101105](https://github.com/Tampermonkey/tampermonkey/assets/34256856/56575ed3-94e8-43eb-a4eb-3ac24d020c07)

## Specifications

- Chromium: (113.0.5672.126)
- OS: (FreeBSD 13.2-RELEASE amd64)

**Comment by derjanb** [comment]
As far as I read the spec `runtime.getPlatformInfo` should never return `undefined`, but this is what seems to happen. 
I'll add a workaround.

**Comment by DeciusMagnus** [comment]
This looks like what the problem I'm getting as well.

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Remilia-NULL** [comment]
Thinks!Fixed in BETA version.
