### ISSUE TITLE
GM addStyle should bypass Content Security Policy (CSP)

### ISSUE THREAD

**Issue by cyfung1031** [Tampermonkey/tampermonkey#1786]
If the page is set with CSP, inline style cannot be appended to `document.head`

**Tampermonkey** shall be capable to add style text like **Stylus** which bypass CSP settings.

If `nonce` is not specified in csp, currently there is no solution to append CSS to the page in userscript.

**Comment by derjanb** [comment]
Can you please add a example page? 
Styles added via `GM_addStyle` should be exempt from the page's CSP.

**Comment by cyfung1031** [comment]
You are right. Tampermonkey can use GM_addStyle to bypass CSP.
