### ISSUE TITLE
scripts not syncing

### ISSUE THREAD

**Issue by mrbeginnercoder** [Tampermonkey/tampermonkey#1788]
(Please fill out the issue template with your details)

## Expected Behavior
I have google Chrome on my work PC and home PC. I used tampermonkey on my home PC. I switched on google chrome sync to sync my tampermonkey script to my work PC. I expect to see the scripts in tampermonkey in my work PC.

## Actual Behavior
Scripts not synced to my work PC. Only extensions synced. Not sure why is this.

**Comment by derjanb** [comment]
Please see http://tmnk.net/faq#Q105 how to configure Tampermonkey to sync your scripts.
