### ISSUE TITLE
Logging Level value is ignored

### ISSUE THREAD

**Issue by iAmNikola** [Tampermonkey/tampermonkey#1790]
## Expected Behavior
Don't print anything except error logs.

## Actual Behavior
Prints out debug logs, despite logging level being set to `Error`. I have restarted and factory reset TM multiple times. I also exported settings to a file and sure enough logLevel value is correct, but yet it logs at debug level.

![image](https://github.com/Tampermonkey/tampermonkey/assets/58849671/f2173dd7-c703-4037-8fd7-3696c018591d)
![Debug logs of scripts logging into console](https://github.com/Tampermonkey/tampermonkey/assets/58849671/eb922f2f-cf54-4055-a82e-76d93798d73b)

## Specifications

- Chromium: (i.e.114.0.5735.106)
- TM: (i.e. 4.19.0)
- OS: (i.e. Ubuntu 20.04)

Thanks for the great project. This has served me for years.

**Comment by derjanb** [comment]
This is no Tampermonkey but userscript logging. You can either configure the console to hide the logging (click at Default levels) or modify the script.

**Comment by iAmNikola** [comment]
Oddly enough, the logs stopped showing up after a while without me doing anything additionally besides the things I mentioned doing when I created this issue
