### ISSUE TITLE
Script run not fast enough with `@run-at document-start` in `v4.19.0`

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [Tampermonkey/tampermonkey#1791]
(Please fill out the issue template with your details)

## Expected Behavior

I updated TM from 4.18.1 to the new version V4.19.0, but I found that the scripts are not running fast enough, especially in some scripts in `@run-at document-start`. It often happens that the script does not start executing until the page is loaded. But these problems do not exist in BETA 4.19.6183.

Although I can check the "Instant" injection mode, but in BETA 4.19.6183 this setting is not required to achieve the effect of `@run-at document-start`.

Can this problem be fixed? Or restore the same effect of BETA 4.19.6138.

Thanks.

## Specifications

- Chromium: (i.e. 64.0.3282.140) 114.0.5735.110
- TM: (i.e. 4.5.5648) 4.19.0
- OS: (i.e. MacOS 10.13.4) WIN10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// @run-at document-start <--------- When document-start, the script cannot be run before the document is loaded
// ==/UserScript==
```

**Comment by derjanb** [comment]
Have you tried to restart your browser (please make sure all processed are closed)? After extension updates often weird things happen to Tampermonkey's content scripts.

**Comment by Xia0xia0Xia0** [comment]
> Have you tried to restart your browser (please make sure **all** browser processes are closed)? After extension updates often weird things happen to Tampermonkey's content scripts.

I have restarted the browser, even reinstalled TM4.19.0 and all scripts, and the problem can still be reproduced. But BETA 4.19.6183 works fine.

**Comment by Xia0xia0Xia0** [comment]
I also found a new problem, if don't check the "Instant" injection mode, the internal style <style> is not inserted properly in some sites(some with CSP). I checked the scripts all used the same method to insert styles, as follows:
```
let s = document.createElement("style");
s.textContent = css;
document.head.appendChild(s);
```
and none of them used `GM_addStyle`, and all set `@run-at document-start`.


**None of these bugs, however, have appeared on BETA 4.19.6183.**

**Comment by Xia0xia0Xia0** [comment]
I tested TM4.19.0 on brave 1.52.122 Chromium: 114.0.5735.110 (64bit) today and it was fine.  But my Chrome kept having loading delays, even after I reinstalled Chrome, TM4.19.0 and user scripts, the problem still existed, I don't know if it was something else that caused the problem on Chrome. it was really weird.

**Comment by derjanb** [comment]
No problem. BTW: 4.19.6183 and 4.19.0 share the same source...
