### ISSUE TITLE
Firefox: My "@match https://*.meetup.com/*/rsvp/" never matches. Why?

### ISSUE THREAD

**Issue by DanKaplanSES** [Tampermonkey/tampermonkey#1803]
I posted this as [a discussion topic](https://github.com/Tampermonkey/tampermonkey/discussions/1795) but I think this might be a bug.

~~I'm probably doing something dumb here; some sort of typo I've become blind to.~~ Here is my script header:

```js
// ==UserScript==
// @name         Remove Meetup.com RSVP ad pop up
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*.meetup.com/*/rsvp/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=meetup.com
// @grant        none
// ==/UserScript==
```

The footer of some meetup.com pages looks like this: 

![image](https://github.com/Tampermonkey/tampermonkey/assets/373675/d740b5c3-bb2a-4724-8106-08a6737c9738)

When you click the Attend button on meetup.com (the red one on the right hand side), it redirects to a new page that ends in `/rsvp/`. But every time I reach that page, the plug-in acts like my script doesn't exist:

![image](https://github.com/Tampermonkey/tampermonkey/assets/373675/8554e295-da59-4a22-8993-83ce2d518312)

If I change the `@match` URL to `// @match        https://*.meetup.com/*`, it works as expected. That is, it works correctly on rsvp pages, but it also runs on all the other pages that have no relevance to the script.

I've read both the [TamperMonkey documentation](https://www.tampermonkey.net/documentation.php#meta:match) and the [Chrome Match Patterns documentation](https://developer.chrome.com/docs/extensions/mv2/match_patterns/), and I can't find anything saying that there's something wrong about `// @match        https://*.meetup.com/*/rsvp/`. So why doesn't it work as expected?

Here are two real URLs from the website that I would expect to match the `@match` field:

* `https://www.meetup.com/silicon-valley-leadership-project-meetup-group/events/293476326/rsvp/`
* `https://www.meetup.com/bayaln/events/290685976/rsvp/`

If you want to try to reproduce this, create a meetup.com account (free), visit a URL without the trailing `/rsvp/`, click Attend Online, and when you are redirected to the rsvp page, you'll see the script is not enabled.

## Specifications

I'm using Firefox 114.0.1 (64-bit) on windows 10 and TamperMonkey 4.18.1.

## Script

```js
// ==UserScript==
// @name         Remove Meetup.com RSVP ad pop up
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*.meetup.com/*/rsvp/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=meetup.com
// @grant        none
// ==/UserScript==
```

**Comment by j4k0xb** [comment]
> and when you are redirected to the rsvp page

it uses [history.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) instead of redirecting

you can hook it

**Comment by j4k0xb** [comment]
Hooking/monkeypatching is just overwriting the function, adding your custom logic and then calling the original
https://stackoverflow.com/a/64927639

**Comment by DanKaplanSES** [comment]
> Hooking/monkeypatching is just overwriting the function, adding your custom logic and then calling the original https://stackoverflow.com/a/64927639

Oh my bad: I've only known this by the term "monkeypatching." OK, thanks for the help.

Should this still be considered a bug? _Should_ tampermonkey recognize this as a url change?

**Comment by j4k0xb** [comment]
not a bug imo
tampermonkey only injects on site load, you wouldnt want to do it all the time in a single page webapp

**Comment by derjanb** [comment]
`window.onurlchange` might also help. -> http://tmnk.net/docs#api:window.onurlchange
