### ISSUE TITLE
why @match https://discord.com/* matches some fandom.com links?

### ISSUE THREAD

**Issue by Sadeko-Sa** [Tampermonkey/tampermonkey#1805]
(Please fill out the issue template with your details)

## Specifications

- Chrome

## Script

```js
// ==UserScript==
// @name         Discord prevent close
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://discord.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=discord.com
// @grant        none
// ==/UserScript==

    // Your code here...
    window.onbeforeunload = confirmExit;
    function confirmExit()
    {
        return '';
    }

$(window).bind('beforeunload', function() {
    return '';
});
```

it matches the link below for example
https://bluearchive.fandom.com/wiki/RABBIT_Platoon

and pretty much all bluearchive.fandom.com links

**Comment by derjanb** [comment]
It doesn't match the tab, but the discord iframe.

Simply add 

```
// @noframes
```

if this is unwanted behavior.

**Comment by Sadeko-Sa** [comment]
> It doesn't match the tab, but the discord iframe.
> 
> Simply add
> 
> ```
> // @noframes
> ```
> 
> if this is unwanted behavior.

thanks. worked
