### ISSUE TITLE
context-menu script is not run

### ISSUE THREAD

**Issue by martin-vavrusak** [Tampermonkey/tampermonkey#1807]
(Please fill out the issue template with your details)

## Expected Behavior
When script is invoked by right click on tampermonkey icon and selected from context menu, it is invoked same way as if run automatically.

## Actual Behavior
Script invoked manually from context menu is not run.
Same script is run normally when any other value is selected in "Run at" (other than "context-menu").

## Specifications

- Chome 114.0.5735.134 (Official Build) (64-bit)
- OS: Windows 11 Version	10.0.22621 Build 22621

## Script
```js
// ==UserScript==
// @name         mozzila page
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://developer.mozilla.org/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    alert("Page loaded");
})();
```

It is the same issue like:
https://github.com/Tampermonkey/tampermonkey/issues/953

**Comment by derjanb** [comment]
```JS
// ==UserScript==
// @name         mozzila page
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://developer.mozilla.org/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// @run-at       context-menu
// ==/UserScript==

(function() {
    'use strict';
    alert("Page loaded");
})();
```
Working fine here with:
* Ubuntu + Chrome Version 117.0.5897.3 (Official Build) dev (64-bit) 
* Windows 10 + Chrome Version 115.0.5790.102 (Offizieller Build) (64-Bit)
* Windows 10 + Chrome Version 115.0.5790.110 (Offizieller Build) (64-Bit)
