### ISSUE TITLE
Stylus's Patch CSP breaks Tampermonkey's script loading in specific cases

### ISSUE THREAD

**Issue by thakyZ** [Tampermonkey/tampermonkey#1808]
## Expected Behavior

Tampermonkey loads all scripts for a page without issue, and can patch the HTML's CSP and not conflict with Stylus

## Actual Behavior

No scripts get loaded unless stylus's option "Turn all styles off" is enabled or "Patch CSP to allow style assets" is disabled.

## Specifications

- FireFox: 114.0.2
- FireFox Developer Edition: 115.0b9
- WaterFox: G5.1.8 
- TM: 4.18.1
- OS: Windows 11 22H2 22621.1848

## Steps

1. Install TamperMonkey and Stylus in Firefox/WaterFox
2. Configure Stylus's options to enable "Patch CSP to allow style assets"
3. Install the script in TamperMonkey
4. Open the console
5. Navigate to a page such as <https://twitter.com/settings/your_twitter_data/twitter_interests>
6. Check to see if the word "soup" by itself in the console.
7. If it doesn't then disable "Patch CSP to allow style assets" in Stylus's options
8. Then try refreshing the page I linked on step 5.
9. Check to see if it did send the word "soup"

## Script

```js
// ==UserScript==
// @name         Twitter Test UserScript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://twitter.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=twitter.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    console.log("soup");
})();
```

## Additional Context

The bug report on Stylus's GitHub is: openstyles/stylus#1621

**Comment by derjanb** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/353#issuecomment-278456508 for more information.
