### ISSUE TITLE
Tampermonkey throws "Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab)" when installed in Chromium v113.0.5672.93

### ISSUE THREAD

**Issue by kenny1983** [Tampermonkey/tampermonkey#1810]
After installing Tampermonkey in Chromium v113.0.5672.93 (64-bit, the latest official version as of the time of writing) and refreshing any tab, I'm getting the error mentioned in the title in `background.html:1`.

## Expected Behavior

Tampermonkey loads and works properly on any site.

## Actual Behavior

Tampermonkey seems to be completely incompatible with the latest version of Chromium.

## Specifications

- TM: 4.19.0.
- OS: Windows 11 on ARM (Build 22621.1848), running through Parallels Desktiop 18 for Mac on a MacBook Pro M1 (macOS 13.4).

## Script

N/A, happens before any scripts are loaded.

**Comment by derjanb** [comment]
This is a cosmetic issue. Tampermonkey should work as expected.

I'll hide that warning in the next release.

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
