### ISSUE TITLE
同步脚本	 启用脚本同步 同步类型: 浏览器同步 无法工作

### ISSUE THREAD

**Issue by geekyouth** [Tampermonkey/tampermonkey#1811]
(Please fill out the issue template with your details)

## Expected Behavior
正常同步

## Actual Behavior

没有同步，而且卡住，控制台没有任何提示。

## Specifications

关于 Cent Browser
Cent Browser 徽标
Cent Browser
版本 5.0.1002.354（正式版本） （64 位） (Chromium 102.0.5005.167)

win10

![image](https://github.com/Tampermonkey/tampermonkey/assets/12899262/2c31a997-3a79-4c80-9664-2a3ed4fb3d6b)

**Comment by derjanb** [comment]
Please check `chrome://sync-internals/`. Also this is better reported to the Cent browser developers.
