### ISSUE TITLE
After removing the <iframe>, sometimes the running script is not deleted, resulting in a page crash.

### ISSUE THREAD

**Issue by Horjer** [Tampermonkey/tampermonkey#1812]
Bug Reproduction:

1. On the local [localhost](http://localhost:8080/index.html) page, write code to open the https://www.abc.com/index.html page every 10 seconds using an <iframe>.
2. I define a Tampermonkey script with @match set to https://www.abc.com/index.html, and in the script, execute console.log("page is open").
3. Close and remove the DOM element of the iframe window at this point.

Repeat this process N times, opening and removing the <iframe>. Normally, after removing the <iframe>, the corresponding @match script should also be removed. However, sometimes the running script instance is not removed, causing the accumulation of markers on the Tampermonkey icon, continuously increasing until the browser crashes.

**Comment by derjanb** [comment]
Sounds like a logic error in your script, but can't tell without code to test.
