### ISSUE TITLE
Save To Disk change in 4.19?

### ISSUE THREAD

**Issue by perpil** [Tampermonkey/tampermonkey#1816]
Is the change in 4.19 where it doesn't prompt you where to save your script when you click File->Save To Disk in the editor intentional?  I'm ok with it, but the UX is a bit clunkier for me.

## Expected Behavior
When clicking File->Save To Disk it opens a file dialog to prompt where to save to

## Actual Behavior
It writes the file to the users' Downloads directory using the default naming scheme i.e. Script.user.js, Script(1).user.js, Script(2).user.js

## Specifications

- FF: 115.0.2 
- TM: 4.19.0
- OS: Mac Ventura 13.4

## Script
N/A

**Comment by derjanb** [comment]
Can not reproduce.

Please try with a new temporary profile. "Save to disk" should save a file named `<scriptname>.user.js` respectively ask where to save and use the name with that formatting as suggestion.

**Comment by perpil** [comment]
I created a new profile, installed TamperMonkey, installed a script and saw the same behavior on pressing "Save to disk"

Here's a screen capture:

![tampermonkeylooped](https://github.com/Tampermonkey/tampermonkey/assets/97474956/3e0d7ee0-f14d-4013-92a5-c16c9833364d)

**Comment by vanowm** [comment]
In MS Edge on Windows, TM 4.19.0 doesn't show any save as dialogs, but it "obeys" browser's setting 
![image](https://github.com/Tampermonkey/tampermonkey/assets/511517/89b8a054-0e4c-4307-b697-cbae6b2f2a78)

If that setting is enabled, it shows download popup:
![image](https://github.com/Tampermonkey/tampermonkey/assets/511517/a2c2fdca-9f66-4502-b5de-d4447fca82be)
Otherwise, it automatically saves file into default download directory.

**Comment by perpil** [comment]
Very interesting! I enabled the same in Firefox and TM started showing save as dialogs.
<img width="707" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/97474956/c4713fdd-c1e3-4c83-a1cf-3db44adef923">
What's curious, is that the default setting for this changed to disabled in Firefox 98 which was way before TM 4.19.  @derjanb do you have this box checked?  Is it possible that changes to GM_download in 4.19 caused this change in behavior.  Maybe it started setting the content type and it wasn't previously set or something?  FWIW, I tried to add a download action for .js reading [this](https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file) and [this](https://support.mozilla.org/gl/questions/1372775) but for some reason Firefox 117.01/Mac doesn't have the "Always Open Similar Files" option that gets the type added to the Applications list so I can change it.

**Comment by perpil** [comment]
I'm going to resolve this, I've got a workaround and it isn't a big deal.
