### ISSUE TITLE
"tld" does not work in @match rule 

### ISSUE THREAD

**Issue by monperrus** [Tampermonkey/tampermonkey#1818]
## Expected Behavior
.tld in `@match` tags matches all top-level domains.

## Actual Behavior
it matches none

## Spec

`tld` worked with `@include` which has disappeared recently.

    @include *://scholar.google.tld/*

What is the equivalent for `@match`?

**Comment by derjanb** [comment]
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns

Match pattern don't know `.tld` and I don't want to add it to Tampermonkey because there is a chance that future implementations will rely on the browsers match pattern implementation.

> `@include` which has disappeared recently

`@include` should work as usual.

**Comment by monperrus** [comment]
ok, thanks.

**Comment by monperrus** [comment]
thanks for the answer.
