### ISSUE TITLE
tampermonkey extension dropdown is way too big

### ISSUE THREAD

**Issue by morrysillusion** [Tampermonkey/tampermonkey#1819]
for some reason, the tampermonkey extension drop down is massive. i cant imagine this is intentional, but i have no clue why and cannot find any resolution in the settings.

example:
![tapermonkey menu1](https://github.com/Tampermonkey/tampermonkey/assets/122761382/41c62599-604b-4046-a48a-a878c331987d)

## Specifications
using firefox 64bit version 115.0.2 on windows 10.

**Comment by derjanb** [comment]
Please set "Config Mode" to "Advanced" and search for "Custom CSS".

Paste this CSS rule and press "Save":

```
body {
      font-size: 50% !important;
}
```

What is your monitor resolution?

**Comment by morrysillusion** [comment]
the 50% made it way too small haha. i am on a 19201200 monitor. but about 80-85% worked fine.

**Comment by damiantrx** [comment]
I noticed that the gui size scaling issues may be due to the fact that the tampermonkey configuration page in firefox beta / firefox nightly opens as a mobile version (I have tested it with a completely new browser profile):
<html class="mobile default">.
instead of
<html class="desktop default">.

**Comment by derjanb** [comment]
Do you still see this issue on the latest FF beta/developer version? Thanks.

**Comment by morrysillusion** [comment]
doesnt seem so!

**Comment by derjanb** [comment]
> doesnt seem so!

Me neither. 😅 Closing this then for now.

**Comment by a0193143** [comment]
> > doesnt seem so!
> 
> Me neither. 😅 Closing this then for now.

This issue still present on Firefox 120.0.1 with Tampermonkey 5.0.0
The setting page in Chrome is a normal desktop layout, but in Firefox is mobile layout.

For comparison, this is how it looks under Firefox:
![f](https://github.com/Tampermonkey/tampermonkey/assets/32773311/1b130b45-ce1a-40e3-9cb3-a18bce33f37f)


And this is Chrome:
![c](https://github.com/Tampermonkey/tampermonkey/assets/32773311/f25a29da-99df-40f3-8403-821b5787dd07)

**Comment by dudeedud4** [comment]
This is still an issue with 5.0.0 Tampermonkey and FF 120.0.1.

**Comment by derjanb** [comment]
Do you have a touch device?

**Comment by dudeedud4** [comment]
> Do you have a touch device?

No, no touch input devices are connected to the pc.

**Comment by derjanb** [comment]
What's the output of 

```
window.matchMedia('(hover: none)').matches
```

when executed at a developer tools console?

**Comment by a0193143** [comment]
> What's the output of 
> 
> ```JS
> window.matchMedia('(hover: none)').matches
> ```
> 
> when executed at a developer tools console?

Mine is "true".

**Comment by derjanb** [comment]
It should be "false" if you're using a PC with a pointer device. 🤔

**Comment by dudeedud4** [comment]
> What's the output of
> 
> ```js
> window.matchMedia('(hover: none)').matches
> ```
> 
> when executed at a developer tools console?

Mine is true as well.

https://i.imgur.com/X7hmyaR.png

**Comment by a0193143** [comment]
@derjanb I have a suggestion, add a switch that could toggle between desktop and mobile layout as a temporary solution.
I think this is Firefox's own bug, if that detect method is reliable.
But don't know how to descript this bug.

**Comment by domeniczz** [comment]
> It should be "false" if you're using a PC with a pointer device. 🤔 I use this to detect devices without hover functionality, usually tablets and mobile phones...

Tampermonkey can provide a switch to let user toggle between "auto", "desktop", "mobile"!

I am using Tampermonkey on desktop and periodically encounter Tampermonkey mistakenly display mobile interface. Yes, periodically, it'll return to normal several days later, and becomes abnormal another several days later...

**Comment by Mapaler** [comment]
I have two 1920×1200 screens and a tablet, does it have anything to do with that?
![IMG_20240112_161733](https://github.com/Tampermonkey/tampermonkey/assets/6565860/8620c300-3b54-427b-89b2-e7a6f642f8f5)

**Comment by derjanb** [comment]
Don't think so. I found a solution... The next BETA version will fix this problem. 😅

**Comment by jorubyp** [comment]
This problem started happening for me when I got my tablet display (Huion 16 2021), it doesn't happen if I unplug the tablet.

**Comment by derjanb** [comment]
Should finally be fixed at 5.1.6193 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by dudeedud4** [comment]
Can confirm this works. Thanks :)

**Comment by zxzlf** [comment]
@derjanb 
Maybe the issue relate to OS version?
I have 4 computers using Firefox, only one of them has this issue, and its OS is Windows 10 **IoT** LTSC
I think this **IoT** cause the issue, I will test other OS versions in VM later
