### ISSUE TITLE
Top level await breaks linter

### ISSUE THREAD

**Issue by marcustyphoon** [Tampermonkey/tampermonkey#1820]
(Please fill out the issue template with your details)

## Expected Behavior

Scripts with an `await` keyword at the top level of the script are linted by eslint.

## Actual Behavior

A parsing error is thrown whenever an `await` keyword is not inside a function, breaking the linter.

![image](https://github.com/Tampermonkey/tampermonkey/assets/8336245/d4779740-e46f-4a59-b0fa-9202e7567bbb)

I saw the comment https://github.com/Tampermonkey/tampermonkey/issues/1686#issuecomment-1403657330 and I don't see why this isn't working?

`/* eslint-env es2022 */` doesn't help.

## Specifications

- Chromium: 114.0.5735.198
- TM: 4.19.0
- OS: MacOS 13.2.1 

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==


await new Promise();

console.log('hello world')
```

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
