### ISSUE TITLE
Utilities section inaccessible on Android in portrait mode

### ISSUE THREAD

**Issue by Jon8RFC** [Tampermonkey/tampermonkey#1821]
## Expected Behavior
To be able to access/scroll/view other Tampermonkey tabs/sections.

## Actual Behavior
Unable to view/access or scroll to other tabs, unless rotating phone to landscape mode.

## Specifications
- Firefox:
115.2.1 (Build #2015962859), 046c284cb9+
GV: 115.0.2-20230710165010
AS: 115.0
- TM:
4.19.0
- OS:
Pixel 7 Pro
Android 13
TQ3A.230705.001.A1

Screen recording reference:
https://github.com/Tampermonkey/tampermonkey/assets/12204953/db31bf73-f707-4dd4-9cec-110f52129f81

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

**Comment by Jon8RFC** [comment]
This will be great, thank you!
