### ISSUE TITLE
Script not working as intended: trying to replace certain texts with this script

### ISSUE THREAD

**Issue by neuralnermal** [Tampermonkey/tampermonkey#1823]
## Expected Behavior
find an element via class name,
check if that class has certain text in it,
if so replace it with another text

## Actual Behavior
It usually works, but sometimes it doesn't on certain elements

## Specifications

- Firefox 115.0.2(64bit)
- TM: 4.19.0 (I assume this means Tamper Monkey version?)
- OS: Windows 11

## Script

```js
// ==UserScript==
var elementsWithThisClassName = document.getElementsByClassName("class name");
for (var i = 0; i < elementsWithThisClassName.length; i++) {
    if (elementsWithThisClassName[i].innerHTML  == "the thing I want to replace") {
        elementsWithThisClassName[i].innerHTML = "replace with this"
    }
}
```

## Additional info

So I got this script from googling, it was originally for a code manipulator
This code usually works, but sometimes it doesn't.
On the exact same page where this worked, it would not work on some elements
I still can't tell what is different about elements that don't work.

I would appreciate it if someone could fix this script or
has a better script for this purpose

**Comment by 7nik** [comment]
1. Are you sure that those elements don't contain something else? E.g. spaces at the beginning and/or end.
2. Do those elements exist from the page start, or added dynamically? If later, you need to re-run the script.

**Comment by vanowm** [comment]
Make sure you have `// @run-at document-end`
If the problem still persists, it would suggest the elements are added/modified dynamically. In which case your best option would be to use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to detect when new elements added to the DOM and/or when `class` attribute changed:
```javascript
function replaceText (elementsWithThisClassName)
{
	for (let i = 0; i < elementsWithThisClassName.length; i++) {
		if (elementsWithThisClassName[i].innerHTML === "the thing I want to replace") {
			elementsWithThisClassName[i].innerHTML = "replace with this";
		}
	}
}
new MutationObserver(mutations =>
{
	// use the same query structure as in CSS
	const queryToSearch = ".some-class-name";
	for (let i = 0; i < mutations.length; i++)
	{
		if (mutations[i].type === "attributes" && mutations[i].target.matches(queryToSearch))
			replaceText( [mutations[i]] ); //note the array

		for (let n = 0; n < mutations[i].addedNodes.length; n++)
		{
			const element = mutations[i].addedNodes[n];

			if (!element.classList)
				continue;

			//check if element itself matches
			if (element.matches(queryToSearch))
				replaceText( [element] ); //note the array

			//find children
			const nodes = element.querySelectorAll(queryToSearch);
			if (nodes.length > 0)
				replaceText(nodes);
		}
	}
}).observe(document, {
	attributeFilter: ["class"],
	subtree: true,
	childList: true
});
```

With mutation observer, you can use `// @run-at document-start` directive
