### ISSUE TITLE
Can we get a simplified ESLint rules config in the editor?

### ISSUE THREAD

**Issue by abraxas86** [Tampermonkey/tampermonkey#1824]
(Please fill out the issue template with your details)

## Expected Behavior
A section in the in the global editor settings to toggle ESLint Rules.  It doesn't make sense to me that we have to include inline rules on every script to ignore multi-space and multi-line code.

## Actual Behavior
A text box to enter a custom config with no real guidance on what formatting it needs, making it exceptionally tricky to figure out for anybody not already familiar with ESLint.

## Specifications
- Chrome:  114.0.5735.199 
- TM: 4.19.0
- OS: Win 10

**Comment by abraxas86** [comment]
I fully accept that this is (to a degree) very much PEBCAK, but the current settings seem way too strict, and way too complicated to configure.  Even providing an example of how to write the config would be a significant help.

**Comment by derjanb** [comment]
Closing in favor of #1686.
