### ISSUE TITLE
Make local modifications more obvious

### ISSUE THREAD

**Issue by changchiyou** [Tampermonkey/tampermonkey#1825]
1. Install script from https://github.com/changchiyou/ChatGPT-to-Markdown-for-Trello via copy&paste in Tampermonkey's editor
2. Edit the `@version` from `1.0.1` to `1.0.0`(downgrade)
3. Update manually by clicking:
    1. Tampermonkey plugin icon
    2. Utilities
    3. Check for userscript updates

## Expected Behavior

Update from 

https://github.com/changchiyou/ChatGPT-to-Markdown-for-Trello/blob/bdd4a182b23021a1e1fe53569bca300ded8ade58/scripts/chatgpt2markdown.user.js#L9-L10

(the url works if I access it via browser directly)

## Actual Behavior

Got the notification:

```
Narf!
No update found, sry!
```

## Specifications
- Tampermoneky v4.19.0
- Google Chrome 115.0.5790.114 arm64
- MacOS Ventura 13.5（22G74）

## Script

https://github.com/changchiyou/ChatGPT-to-Markdown-for-Trello/blob/bdd4a182b23021a1e1fe53569bca300ded8ade58/scripts/chatgpt2markdown.user.js#L1-L96

**Comment by derjanb** [comment]
Editing a script will disable its automatic updates ("Check for updates") to prevent data loss.
The next BETA version will change this a bit and make the local modification more obvious.

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
