### ISSUE TITLE
Use user activation gated APIs in `GM_registerMenuCommand` callbacks

### ISSUE THREAD

**Issue by Sec-ant** [Tampermonkey/tampermonkey#1827]
Is it possible to use [user activation gated APIs](https://developer.mozilla.org/docs/Web/Security/User_activation) in `GM_registerMenuCommand` callbacks?

## Expected Behavior

When users click the registered menu buttons, they can use these APIs without an issue.

## Actual Behavior

Failed to execute `XXX` on 'Window': Must be handling a user gesture to XXX.

## Specifications

- Chromium: ungoogled 114.0.5735.199
- TM: 4.19.0
- OS: Windows 11 22H2 22621.1992

## Script

```js
// ==UserScript==
// @name         User Activation Test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=github.com
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
    GM_registerMenuCommand("Acquire Files", async () => {
        const files = await unsafeWindow.showOpenFilePicker();
        console.log(files);
    });
})();
```

I probably shouldn't use `unsafeWindow` but the window object of the pop-up window? However it is not exposed to the user.

**Comment by Sec-ant** [comment]
If I change `@run-at` to `context-menu`, this menu command can open the file picker window. However it seems that I have to click twice to see the sub-sub-level menu command.

**Comment by derjanb** [comment]
It always works using the context menu menu command even if executed not via `@run-at`  `context-menu`. 
However extensions can't forward the user gesture form the popup menu to the scripts callback.
