### ISSUE TITLE
Do not close the pop-up window when user clicks

### ISSUE THREAD

**Issue by Sec-ant** [Tampermonkey/tampermonkey#1828]
Currently if the user clicks the menu buttons registered by `GM_registeredMenuCommand`, the pop-up window will close. This can be annoying when the developer wants to design some stateful (not one-time) interactions in the pop-up menu. It would be great to provide an option or a callback argument in `GM_registeredMenuCommand` to let the userscript developer decide whether or when to close the pop-up menu.

## Expected Behavior

The `GM_registeredMenuCommand` callback accepts a function to close the pop-up menu, or an exposed pop-up window object. And developers can write their own logic to decide when to close the pop-up window.

## Actual Behavior

This is not possible at the moment.

## Specifications

- Chromium: ungoogled 114.0.5735.199
- TM: 4.19.0
- OS: Windows 11 22H2 22621.1992

**Comment by 7nik** [comment]
Note the user can turn on displaying the menu commands in the context menu. And there is no way to keep the context menu open after a click. And having different behaviour for the pop-up and context menus is a bad idea.

If you need a menu with complicated behaviour, it's better to implement your own on the page.

**Comment by Sec-ant** [comment]
@7nik Thanks for the explanation. I wasn't aware that menu commands can be displayed in the context menu. But if I understand correctly, for a single userscript, the menu commands are either in the pop-up or the context menu, but not both. So different behaviors should be acceptable? I do agree it might be a little confusing that they use the same `GM_registeredMenuCommand` API while having different capabilities if this is to be implemented.

> If you need a menu with complicated behaviour, it's better to implement your own on the page.

Yeah the reason why I choose to use `GM_registeredMenuCommand` is that the targeted website put many restrictions on the page interaction (like many removed or modified mouse event handlers), so If I want to provide some interactions that guarantees to work without having to digging into the logic of the targeted page, or worrying about breaking things, `GM_registeredMenuCommand` is a good choice.

**Comment by derjanb** [comment]
4.20.6185+ accepts an options object with an `autoClose` key. https://www.tampermonkey.net/docs#api:GM_registerMenuCommand

**Comment by Sec-ant** [comment]
This works as expected, thanks @derjanb
