### ISSUE TITLE
GM_setValue/getValue does not work with "any type"

### ISSUE THREAD

**Issue by Black-Platypus** [Tampermonkey/tampermonkey#1829]
The [documentation](https://www.tampermonkey.net/documentation.php?locale=en#api:GM_setValue) says:

> This value can be of any type (string, number, object, etc.)

While things like `RegExp`s, `Function`s, etc won't throw an error, they are not retrievably stored by TamperMonkey.
The way in which this fails feels a lot like `JSON.stringify`, `JSON.parse`. But when I tried to accomodate for this the other day, giving some classes a `.toJSON` function property where I could insert a replacer function, it was not triggered by `GM_setValue`, which added to the frustration.

At the very least, the documentation should reflect this and a warning logged. But really, common object instances like these should be handled to work

## Expected Behavior
Instances of [`RegExp`, `Function`] or Objects containing them are stored and can be retrieved faithfully.
```
var inputs = {
	RegExp: {
		instanceOf: RegExp,
		value: /https?:\/\/(?:[^/]+\.)?example\.com/i
	},
	Function: {
		instanceOf: Function,
		value: (foo)=>{console.log(foo);}
	}
};
GM_setValue("object", inputs);
var nested = GM_getValue("object", inputs);
for(let k in inputs){
	var obj = inputs[k].value;
	console.log(`Input ${k}:`, typeof obj, obj, obj instanceof inputs[k].instanceOf);
	GM_setValue(k, obj);
	var result = GM_getValue(k, "...");
	console.log(`Result ${k}:`, typeof result, result, result instanceof inputs[k].instanceOf);
	console.log(`Result ${k} nested:`, typeof nested[k].value, nested[k].value, nested[k].value instanceof inputs[k].instanceOf);			
}
```
should output

> Input RegExp: object /https?:\/\/(?:[^/]+\.)?example\.com/i true
> Result RegExp: object /https?:\/\/(?:[^/]+\.)?example\.com/i true
> Result RegExp nested: object /https?:\/\/(?:[^/]+\.)?example\.com/i true
> Input Function: function (foo)=>{console.log(foo);} true
> Result Function: function (foo)=>{console.log(foo);} true
> Result Function nested: function (foo)=>{console.log(foo);} true

## Actual Behavior
Instances of [`RegExp`, `function`] are replaced with empty objects, strings, or omitted outright and are not restored as instances of [`RegExp`, `function`]
The above outputs

> Input RegExp: object /https?:\/\/(?:[^/]+\.)?example\.com/i true
> Result RegExp: object {} false
> Result RegExp nested: object {} false
> Input Function: function (foo)=>{console.log(foo);} true
> Result Function: string (foo)=>{console.log(foo);} false
> Result Function nested: undefined undefined false

## Specifications

- Chromium: 113.0.5672.64 (Official Build) (64-bit)
- TM: 4.19.0
- OS: Microsoft Windows 10 Pro v10.0.19044.1889

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name setValue/getValue test
// @namespace http://mywebsite.com
// @Version 1.0
// @author Me
// @include *
// @grant		GM_getValue
// @grant		GM_setValue
// ==/UserScript==

var inputs = {
	RegExp: {
		instanceOf: RegExp,
		value: /https?:\/\/(?:[^/]+\.)?example\.com/i
	},
	Function: {
		instanceOf: Function,
		value: (foo)=>{console.log(foo);}
	}
};
GM_setValue("object", inputs);
var nested = GM_getValue("object", inputs);
for(let k in inputs){
	var obj = inputs[k].value;
	console.log(`Input ${k}:`, typeof obj, obj, obj instanceof inputs[k].instanceOf);
	GM_setValue(k, obj);
	var result = GM_getValue(k, "...");
	console.log(`Result ${k}:`, typeof result, result, result instanceof inputs[k].instanceOf);
	console.log(`Result ${k} nested:`, typeof nested[k].value, nested[k].value, nested[k].value instanceof inputs[k].instanceOf);			
}
```

**Comment by derjanb** [comment]
Documented
