### ISSUE TITLE
Editor: start search-as-you-type from the current cursor position

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1830]
(Please fill out the issue template with your details)

## Expected Behaviour
Feature revert to 4.18

## Actual Behaviour
Incremental search too much incremental

## Specifications

- Firefox latest
- TM: 4.19
- OS: WIn11/x64

## Script

[not reproducible by script]

This is minor yet annoying change in behaviour of the search feature in builtin editor.
While typing searched text, the cursor moves across file on each other pattern occurrence matching the typed text. That's fine but standard incremental search does not move the cursor on as long as currently entered pattern fits at current position, but TM does even if the pattern still matches. It's annoying when I need to find first text occurrence from current position. I'd request to conform with incremental standard or let the user to turn the incremental search off.

**Comment by derjanb** [comment]
This should be fixed at 4.20.6185+ ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
