### ISSUE TITLE
freezing / hanging issues on Tor Browser

### ISSUE THREAD

**Issue by chrimez** [Tampermonkey/tampermonkey#1833]
## Expected Behavior   ## Actual Behavior
I've been having issues with scripts freezing pages ("a script is slowing down the page. Stop it?") .... spiking CPU core load, and freezing the tab for... minutes.
This now also happened in the TM Dashboard, when simply opening a script for editing: it would load only the first few lines, then peak the CPU and freeze the browser tab.

Note: I mostly use TM on MS Edge, where this dies not happen. 

## Specifications

- Tor 12.5.2 (based on Mozilla Firefox 102.14.0esr) (64-bit)
- TM: (version=4.19.0)
- OS: (i.e. Win 10.0.19045 Build 19045 )

## Script

(Please give an example of the script if applicable.)

**Comment by derjanb** [comment]
Should be fixed at 5.0.1
