### ISSUE TITLE
4.20.6185 2023-08-03，Google drive无法正常同步

### ISSUE THREAD

**Issue by 1xiaocainiao** [Tampermonkey/tampermonkey#1834]
(Please fill out the issue template with your details)

## Expected Behavior
正常同步

## Actual Behavior
<img width="1338" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/7066030/d929115c-d738-40da-aa57-8dc5028fecd3">
无法像4.19.6183版本一样正常登录谷歌，导致无法同步数据，尝试降级4.19.6183测试版正常同步

## Specifications

Chrome 115.0.5790.170（正式版本） (arm64)

测试版4.20.6185
2023-08-03

macos 13.5

**Comment by derjanb** [comment]
Closing in favor of #1842 
Thanks for reporting
