### ISSUE TITLE
GM.xmlHttpRequest is not working on some sites

### ISSUE THREAD

**Issue by codeninja-ru** [Tampermonkey/tampermonkey#1838]
I have a simple script that calls GM.xmlHttpRequest to get an url on a third-party site.

and _GM.xmlHttpRequest_ is not working on some sites: twitter.com, github.com, etc

## Expected Behavior

it should show an alert box with ‘onload’ message, when twiter.com or github.com is opened.

## Actual Behavior

nothing happens. _onload_ or _onerror_ callback are never called.

but it’s working on google.com and some other site with less strict security policies, and _fetch_ seems working on any website.

## Specifications

- Safari: (Version 15.6.1)
- TM: (v4.20.6184)
- MacOS 10.15.7

## Script

```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*/*
// @grant    GM.xmlHttpRequest
// ==/UserScript==

(function() {
    'use strict';
    var URL = 'https://pastebin.com/raw/sm8tpnHq';
    GM.xmlHttpRequest({
        method: "GET",
        anonymous: true,
        url: URL,
        onload: function(response) {
            alert('onload');
        },
        onerror: function(err) {
            alert('onerror');
        }
    });
})();
```

**Comment by vanowm** [comment]
Works fine in MS Edge on Windows, TM shows this:
![image](https://github.com/Tampermonkey/tampermonkey/assets/511517/ad35cb6c-bc50-4946-9c86-d54b3fbf8f48)

**Comment by codeninja-ru** [comment]
@vanowm on safari, it shows this dialog and when I click on "allow one"/"Always allow domain" it doesn’t send the request to pastbin and doesn’t show any alert box

**Comment by derjanb** [comment]
Please re-try with 4.20.6188. Thanks.

**Comment by codeninja-ru** [comment]
@derjanb The issue is still present

It seems related to some security headers. For example, the script works well (the alert has shown) for google.com, but it doesn't work for github.com

**Comment by vanowm** [comment]
Pretty sure #1859 is a duplicate of this one, not the other way around...but whatever

**Comment by derjanb** [comment]
@vanowm To let the one with the most detailed description "win" makes things easier... ;-)
