### ISSUE TITLE
All behaviors to open new tab seems to be broken

### ISSUE THREAD

**Issue by thelastfantasy** [Tampermonkey/tampermonkey#1842]
(Please fill out the issue template with your details)

## Expected Behavior
From "Firefox menu -> addons -> Tempermonkey -> dashboard", click and new tab should be opened 

From "Firefox menu -> settings -> addons -> Tempermonkey -> settings -> Utilities tab -> show backups (Google Drive)", click and spinner shows, and new tab of google authorization page should be opened

## Actual Behavior
All behaviors to open new tab seems to be broken
Just like

From "Firefox menu -> addons -> Tempermonkey -> dashboard", click but nothing happen.

From "Firefox menu -> settings -> addons -> Tempermonkey -> settings -> Utilities tab -> show backups (Google Drive)", click and spinner shows, but no new tab is not opened.

## Specifications

- Firefox Android：116.3.0 (Build #2015968451), ba51cc4285+
GV: 116.0.3-20230815173142
AS: 116.0

- OS: Android 13 Latest Update （Pixel 7）

## Script

Fresh installation and no script installed

**Comment by derjanb** [comment]
Thanks for reporting.

This should be fixed at 4.20.6187 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi - still in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` once the review is finished.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
