### ISSUE TITLE
Disable "Sync now" button if there are unsaved changes

### ISSUE THREAD

**Issue by toomanynights** [Tampermonkey/tampermonkey#1844]
Hello!

I have a strange issue when I can't enable sync to Google Drive, because there's endless loading.
On my other PC, I managed to make it work by granting access to Google Drive in "Utilities" tab ("Cloud"). After that, sync finally started working in "Settings" tab, so I figured it was because the function on "Settings" tab wouldn't ask for Google auth. However, now on all my other devices this trick doesn't work, there's still endless loading o matter if I gave access or not.

## Expected Behavior
I can enable sync to Google Drive.

## Actual Behavior
Sync won't turn on' instead, I can see "Wait..." pop-up and endless loading.

## Specifications

- Mozilla Firefox: 117.0
- TM: 4.19.0
- OS: Windows 10

**Comment by vanowm** [comment]
Make sure after enabling sync you press `Save` button, not `Run now`

**Comment by toomanynights** [comment]
Yep. That did it. Thanks!Maybe it would be possible to make it so "save" would be performed automatically upon pressing "Run now". Would lessen the confusion for others :)6:28 PM, September 8, 2023, ***@***.***" ***@***.***>:
Make sure after enabling sync you press Save button, not Run now

**Comment by vanowm** [comment]
The whole settings page with multiple save buttons and multiple options that automatically save is a disaster.

**Comment by derjanb** [comment]
> settings page with multiple save buttons and multiple options that automatically save 

Agreed. For now the buttons will be disabled if there are unsaved changes.

**Comment by derjanb** [comment]
It saves the settings of the section it is located at. At the moment all text fields and text areas require a save button.

**Comment by derjanb** [comment]
At Tampermonkey 5.0.6189 the buttons are disabled if there are unsaved changes ([crx](https://data.tampermonkey.net/tampermonkey_beta.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by vanowm** [comment]
> It saves the settings of the section it is located at. At the moment all text fields and text areas require a save button.

Please consider an always visible single save button for everything.
