### ISSUE TITLE
[CSP] Modify existing content security policy not work

### ISSUE THREAD

**Issue by freemedom** [Tampermonkey/tampermonkey#1845]
(Please fill out the issue template with your details)

## Expected Behavior
Modify existing content security policy (CSP) headers: Remove entirely (possibly unsecure)

## Actual Behavior
not work, cannot remove csp headers
still show "Refused to load the script 'https://esm.sh/octokit' because it violates the following Content Security Policy directive"
Seems to have a version before is valid. I remember when I first wrote this script (a month ago) it worked.

## Specifications

- Chromium: (114.0.5735.199)
- TM: (v4.20.6185) beta
- OS: (windows10)

## Script

(Please give an example of the script if applicable.)

```js
	const { Octokit, App } = await import("https://esm.sh/octokit");
```

**Comment by freemedom** [comment]
now i use https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden
but it must manually click and refresh

**Comment by derjanb** [comment]
If it worked earlier you can switch "Modify existing content security policy (CSP) headers" from "Auto" to "Yes". This will restore the old behavior. However, Tampermonkey can't support CSP relaxing in Chrome when manifest v3 becomes mandatory and also won't support CSP relaxing in Firefox in the near future.

**Comment by freemedom** [comment]
@derjanb
