### ISSUE TITLE
TM breaks the Code Verify of WhatsApp Web

### ISSUE THREAD

**Issue by PureOcean** [Tampermonkey/tampermonkey#1846]
1) Install TamperMonkey extension.
2) Install [Code Verify](https://addons.mozilla.org/en-US/firefox/addon/code-verify/) extension.
3) Visit to https://web.whatsapp.com/

## Expected Behavior

When the WhatsApp web page is visited, the code integrity is indicated in the address bar as a green icon. No need log-in or scan the QR code.

## Actual Behavior

If TamperMonkey extension installed, [the Code Verify](https://github.com/facebookincubator/meta-code-verify) extension cannot confirm the code integrity with the red icon. Unfortunately, it does not work to add blacklist `https://web.whatsapp.com/*` or `https://*whatsapp.com/*` or `*://web.whatsapp.com/*` or `*whatsapp.com/*` in Tampermonkey settings. For now, the only solution is to completely disable Tampermonkey in Firefox.

## Specifications

- Firefox: 117 (Stable) or 118.0b3 (Beta) or 119.a1 (Nightly)
- TM: 4.19.0
- OS: Windows 11 10.0.22621.2134

**Comment by derjanb** [comment]
Please try the `Instant` injection mode -> https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595

**Comment by PureOcean** [comment]
> Please try the `Instant` injection mode -> [#211 (comment)](https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595)

Thank you for the tip. I just tried the _**Inject Mode**: Instant_ in Settings -> General -> (Config mode: Advanced) -> Experimental. Problem is solved! Tampermonkey no longer breaks the integrity control of the Code Verify extension.
I would also like to thank you for adding this special setting. Tampermonkey 's great wide structure is always fascinated.
