### ISSUE TITLE
Tampermonkey takes a very long time to load, after which it issues an error message. While tampermonkey is loading, the browser tabs are also not working

### ISSUE THREAD

**Issue by WorSt-Pr0grAmmeR** [Tampermonkey/tampermonkey#1847]
I tried to open tampermonkey via the icon but it didn't load.
Then I tried to open it using hotkeys to edit a new script, but after opening the tab, it remains empty and after some time reports an internal error.
2 times reload browser and laptop
## Specifications

- Chrome: v116.0.5845.177
- Microsoft Edge: v116.0.1938.69
- Yandex browser: v23.9.0.1734 beta (64-bit)
- Tampermonkey beta: v4.20.6185
- OS: Windows 7 Service Pack 1 (Build 7601)
![image](https://github.com/Tampermonkey/tampermonkey/assets/127094790/f73243e6-cd7f-4fb0-ad7f-9199565c81fd)
![image](https://github.com/Tampermonkey/tampermonkey/assets/127094790/668f0784-e4e8-45b6-98ea-8b76eb32b1fe)

**Comment by derjanb** [comment]
@WorSt-Pr0grAmmeR You can export your scripts to zip file and later import it again. Go to the options page, select the "Utilities" tab and click at "Zip" -> Export.

**Comment by derjanb** [comment]
This should be fixed at 5.0.6189 ([crx](https://data.tampermonkey.net/tampermonkey_beta.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
Thanks for reporting.
