### ISSUE TITLE
Globals defined in Linter config does not prevent no-undef warnings

### ISSUE THREAD

**Issue by Tecfan** [Tampermonkey/tampermonkey#1854]
The following example script and example linter config will result in an no-undef warning on line 17 and line 18, even though the globals "Promise" and "waitForKeyElements" have been defined in the linter config.

Placing `/* global waitForKeyElements, Promise */` anywhere in the code will remove the warnings, so in-line configuration of globals do work, just not from config.

## Expected Behavior
no-undef warnings for globals disappear when defining the appropriate rules in the linter config

## Actual Behavior
The globals tag in the linter config does not seem to have any effect and in-code eslint code is required

## Specifications

- Chromium: 116.0.5845.188 (Official Build) (64-bit)
- TM: 4.19.0
- OS: Win 11

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Google Hello World (written by chatGPT)
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Displays "Hello World" when the <body> element is visible on Google.com
// @author       Your Name
// @match        https://www.google.com/*
// @grant        none
// @require      https://cdn.jsdelivr.net/gh/CoeJoder/waitForKeyElements.js@v1.2/waitForKeyElements.js
// ==/UserScript==

(function() {
    'use strict';

    // Function to wait for the <body> element to become visible
    function waitForBody() {
        return new Promise(function(resolve) {
            waitForKeyElements('body', function() {
                resolve();
            });
        });
    }

    // Main function
    async function main() {
        await waitForBody(); // Wait for <body> element to become visible
        alert('Hello World');
    }

    // Start the script
    main();
})();
```

With the following linter config which gives no errors and that I have confirmed with ESlint devs should not be problematic:
```
{
    "env": {
        "browser": true,
        "greasemonkey": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Promise": "readonly",
        "waitForKeyElements": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": false,
            "jsx": false
        },
        "ecmaVersion": 8,
        "sourceType": "script"
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "no-multi-spaces": [
            "error",
            {
                "ignoreEOLComments": true
            }
        ]
    }
}

**Comment by derjanb** [comment]
This should be fixed at 5.0.6189 ([crx](https://data.tampermonkey.net/tampermonkey_beta.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
