### ISSUE TITLE
What is easy way to debug local script

### ISSUE THREAD

**Issue by nanikit** [Tampermonkey/tampermonkey#1855]
This is closer to a feature request, so I put aside provided template.

## Motivation
I'm managing userscript dependency by `@resources`, so metadata header can be changed frequently.
Currently I'm testing/debugging the script by `@require` local files like the following.
```
// ==UserScript==
// @name           local script
// @version        2106161617
// @match          https://bbs.s.s/*/*
// @connect        *
// @grant          GM_xmlhttpRequest
// @grant          GM_getResourceText
// @grant          GM_setValue
// @grant          GM_getValue
// @grant          window.close
// @run-at         document-start
// @require        https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.js
// @require        file://D:/Repo/script.user.js
// @resource       @stitches/react     https://cdn.jsdelivr.net/npm/@stitches/react@1.2.8/dist/index.cjs
// @resource       fflate              https://cdn.jsdelivr.net/npm/fflate@0.8.0/lib/browser.cjs
// @resource       jotai               https://cdn.jsdelivr.net/npm/jotai@2.4.2/index.js
// @resource       jotai/react         https://cdn.jsdelivr.net/npm/jotai@2.4.2/react.js
// @resource       jotai/react/utils   https://cdn.jsdelivr.net/npm/jotai@2.4.2/react/utils.js
// @resource       jotai/utils         https://cdn.jsdelivr.net/npm/jotai@2.4.2/utils.js
// @resource       jotai/vanilla       https://cdn.jsdelivr.net/npm/jotai@2.4.2/vanilla.js
// @resource       jotai/vanilla/utils https://cdn.jsdelivr.net/npm/jotai@2.4.2/vanilla/utils.js
// @resource       object-assign       https://cdn.jsdelivr.net/npm/object-assign@4.1.1/index.js
// @resource       react               https://cdn.jsdelivr.net/npm/react@18.2.0/cjs/react.production.min.js
// @resource       react-dom           https://cdn.jsdelivr.net/npm/react-dom@18.2.0/cjs/react-dom.production.min.js
// @resource       scheduler           https://cdn.jsdelivr.net/npm/scheduler@0.23.0/cjs/scheduler.production.min.js
// @resource       other_local_script  file://D:/Repo/deps.user.js
// ==/UserScript==
```

It is error-prone process because I should update this metadata only in tampermonkey dashboard whenever the `@resource` list is changed.
Sometimes it's not just about changing the resource list, but also the script name(I should change the script name if I copy whole header) and some dependency paths(`other_local_script` would have been the `https:` url, so I need to change it.). And when you have a lot of scripts like this, it becomes a pain.
Although it would be root cause that I'm not using bundling, it is valid usage according to greasyfork policy.

Back to the title, is there recommended approach for this?

## Considered changes

If there is no appropriate method for this, how about loading local file directly if update URL is file:// URL?

## Specifications

- Chromium: 116.0.5845.188
- TM: 4.20.6187
- OS: Windows 11

**Comment by 7nik** [comment]
Have you tried a WebDAV? E.g. [TamperDAV](https://github.com/Tampermonkey/TamperDAV)

**Comment by nanikit** [comment]
I tried it and think this is worth. I'll close it and open it if there's a problem.
