### ISSUE TITLE
macOS sonoma: tampermonkey stops working on safari after 30 mins

### ISSUE THREAD

**Issue by EricE549X** [Tampermonkey/tampermonkey#1856]
(Please fill out the issue template with your details)

## Expected Behavior
run in the background the whole time

## Actual Behavior
about 30 minutes (rough estimate) after i open a window, tampermonkey just stops working. no userscripts run, the toolbar icon doesn't do anything, and all `ui.tampermonkey.net` links effectively break.

however, when i quit and reopen safari, tampermonkey works as normal, at least until it breaks again.

i've tried uninstalling and reinstalling tampermonkey, didn't fix it.

## Specifications

- Safari: 17.0
- TM: 4.20.6184
- OS: macOS 14.0
- Device: MacBook Air (M1)

## Script

N/A

**Comment by mistydemeo** [comment]
I'm seeing the same issue; I'm happy to provide any info needed for debugging.

**Comment by LuGHuaaa** [comment]
same issue; what happens?

**Comment by ivandrago228** [comment]
Same

**Comment by derjanb** [comment]
Unfortunately my MacBook can't update to Sonoma so I need to buy a new one. This will take some days. Sorry for any inconvenience.

**Comment by EricE549X** [comment]
> Unfortunately my MacBook can't update to Sonoma so I need to buy a new one. This will take some days. Sorry for any inconvenience.

all good!

**Comment by classicsc** [comment]
As a temporary workaround, I've found it works again immediately if I disable and re-enable the extension in settings, no need to relaunch Safari.

**Comment by CyberSkull** [comment]
It seems to me that after a certain number of page loads using userscripts it just seem to give up.

**Comment by lucdesign** [comment]
Same (mis)behaviour here. Scripts stop loading, menu stops working. Safari 17, Sonoma, Mac Studio M1. Disabling/reenabling extension helps - for a short while.

**Comment by EricE549X** [comment]
> It seems to me that after a certain number of page loads using userscripts it just seem to give up.

yep, that seems to be what's happening

**Comment by snipe** [comment]
Following this thread as well - huge thanks to @classicsc for the disable/enable trick. Works a treat. 

@derjanb let us know if we can help in any way with debugging/testing/etc, and thanks so much for working on such an important extension. <3

**Comment by gracjangk** [comment]
I can confirm this behaviour. Extension freezes up after some time. Also, the settings panel cannot be opened. Disabling and reenabling the extension help temporarily. It's also visible as frozen in Force Quit dialog box (⌥ + ⌘  + ⎋).

**Comment by derjanb** [comment]
References for my further research: 

https://1password.community/discussion/141639/extension-is-working-unreliably-in-safari-17-beta
https://developer.apple.com/forums/thread/738567

**Comment by zappy** [comment]
> FYI: A new MacBook Air is on the way and should arrive within the next two days. Sorry again for any inconvenience...

No worries, rather let us know if there is anything we can do to help with analysis or fixing the issue :)

**Comment by CyberSkull** [comment]
I'm not sure, but it seems to give up quicker with cross-site stuff. That could just be confirmation bias on my part since most of the scrips I used are for pulling data from one site to another.

**Comment by derjanb** [comment]
I setup my new MacBook and reproduced #1862.

One question when Tampermonkey stops working does the Activity Monitor then looks like this -> "Not responding"?
https://github.com/Tampermonkey/tampermonkey/issues/1862#issuecomment-1761076251

**Comment by mistydemeo** [comment]
Yes, I'm seeing the same "not responding" process like in that comment.

**Comment by CyberSkull** [comment]
<img width="331" alt="Screenshot 2023-10-18 at 3 10 35 AM" src="https://github.com/Tampermonkey/tampermonkey/assets/201815/f72d0457-7ac4-4605-8ad7-a23e4de43c1f">
This is what happens when I look at Activity Monitor.

**Comment by derjanb** [comment]
The App is "Waiting for Review" now. Forgot to click the button to move it to this state, because "Ready for review" sounded quite good... 🙈

I hope that it will fix the "Not Responding" issue. I was able to reproduce this with 6184, but sometimes it took a long time to make it happen and then it happened multiple times within some minutes. I've never seen it with 6188 (the next version) so I hope it'll be fixed.

**Comment by derjanb** [comment]
The submission was accepted. Please update to 4.20.6188 and the issue hopefully is gone. Thanks.

**Comment by mistydemeo** [comment]
Seems fine for me too; thanks for the fast turnaround on this! I really appreciate it.

**Comment by lucdesign** [comment]
thx a lot!

**Comment by Emerelle** [comment]
No further issues since update for me too, thanks a lot. :-)

**Comment by snipe** [comment]
Thanks so much! <3

**Comment by CyberSkull** [comment]
I'm not having any problems. 🥹

**Comment by mocenigo** [comment]
It does not work here. 14.4 Beta (23E5196e). Safari Version 17.4 (19618.1.14.11.2). I just see the spinning thingy.
