### ISSUE TITLE
🐞: `@icon file:///...`  is invalid

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1857]
- Chromium: 86
- OS: Win10

## Script

- Unable to display local icon 👇 (It used to be displayed normally, but I don't know which version has stopped displaying it.)
```js
// @icon	file:///D:/path/iconName.png
// @icon64	file:///D:/path/iconName.png
```

```js
// ==UserScript==
// @name MyName
// @Version 1.0
// @description try to take over the world!

// @icon	file:///D:/path/iconName.png
// @icon64	file:///D:/path/iconName.png

// ==/UserScript==
```

**Comment by derjanb** [comment]
Working fine here at all OSes if "Allow access to file URLs" is enabled. 
Can you please try to disable and re-enable the setting?

Tested:
TM 4.19.0 + 4.20.6187
Windows 11 + Ubuntu
image.ico and image.png

**Comment by dnknn** [comment]
> Working fine here at all OSes if "Allow access to file URLs" is enabled. Can you please try to disable and re-enable the setting?
> 
> Tested: TM 4.19.0 + 4.20.6187 Windows 11 + Ubuntu image.ico and image.png

I know the problem lies, it is related to Chrome kernel version.
I tested it on Chrome V108 and the icon can be displayed normally!
So I closed the feedback on this issue, thank you!
