### ISSUE TITLE
will unsafeWindow be set for the included scripts?

### ISSUE THREAD

**Issue by younes-zeboudj** [Tampermonkey/tampermonkey#1860]
I want to use Tamper monkey to execute a script in some pages and use GM_webRequest to block requests, I want to know if the unsafeWindoe is also set for the included script. For instance, will `window` in the included `http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js` script be the browser's window object?

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
> For instance, will window in the included http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js script be the browser's window object?

* in `// @grant none` mode `window` is the regular page window.
* in any other mode `window` is the sandboxed "safe" window

**Comment by younes-zeboudj** [comment]
I am aware about :
`// @grant none`
thanks.

But I see that this could be confusing, for example jQuery will be loaded in the Tamper monkey window, that is, it will not be visible for in-page scripts. Is this intended? 
And I want to understand the Tampermonkey window, does it expose all members in the regular window, for instance: `alert`, `document`...?

**Comment by younes-zeboudj** [comment]
I also want to understand the contexts handling. For example, in a function that is declared in Tamper monkey scripts like:

`function check(){ console.log(window)}`

then attached to a DOM element event with:

`window.unsafeWindow.document.querySelector("#anId").onclick= check;`

will the `window` in `check` be the `unsafeWindow` or the Tamper monkey `window` when the element `#anId` is clicked?
