### ISSUE TITLE
[Safari] Tampermonkey 4.20.6184 GM_info.userAgentData return a wrong version result.

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#1861]
## Actual Behavior
[Safari] Tampermonkey 4.20.6184 GM_info.userAgentData return a wrong version result:
```js
{platform: "macOS", brands: [{brand: "Safari", version: "undefined"}], mobile: false}
```
the brand version was undefined.

## Specifications

- Safari: 16.3
- TM: 4.20.6184
- OS: MacOS

**Comment by derjanb** [comment]
Fixed at  4.20.6188. Thanks for reporting.
