### ISSUE TITLE
Event listener callback error when callback is an object and window is script's window

### ISSUE THREAD

**Issue by hyperstown** [Tampermonkey/tampermonkey#1863]
## Expected Behavior

After registering event listener on script's window (default, scoped) with object as callback it calls handleEvent method of that object. So basically works same as client window or in script unsafeWindow.

## Actual Behavior

After registering event listener on script's window (default, scoped) with object as callback instead of calling handleEvent method it throws an error:
`TypeError: Function.prototype.apply called on incompatible Object` in Firefox or `VM21:9 Uncaught TypeError: Function.prototype.apply was called on [object Object], which is an object and not a function` in Chromium.

## NOTE
Important note that I can confirm it worked in version 4.17 as I worked on that version, then updated to latest and it stopped working.

## Specifications

- Firefox: 118
- TM: 4.19.0
- OS: Linux 6.1 LTS

## Script
Example script

```js
// ==UserScript==
// @name         test
// @version      0.0.0
// @encoding     utf-8
// @description  test
// @author       You
// @match        *://127.0.0.1:5500/*
// @grant        GM.xmlHttpRequest
// @grant        GM_addStyle
// @grant        unsafeWindow
// @run-at       document-end
// ==/UserScript==


(function() {
  'use strict';

  const exampleObj = {
    testV: 1,
    name: "test object",
    handleEvent(e) {
      console.log(e);
    }
  }

  console.log("window", window)
  console.log("unsafeWindow", unsafeWindow)
//unsafeWindow.addEventListener("click", exampleObj); // This works
  window.addEventListener("click", exampleObj); // This doesn't
  
})();
```

## Additional resources:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters

**Comment by derjanb** [comment]
This should be fixed at 5.0.6189 ([crx](https://data.tampermonkey.net/tampermonkey_beta.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
