### ISSUE TITLE
Add wildcard for domain part

### ISSUE THREAD

**Issue by Machou** [Tampermonkey/tampermonkey#1864]
Hello

Tampermonkey didn't support wildcard for domain part.

Like this :

wildcards (`*`) at any position, e.g. `www.google.*`;

Can we expect this feature to be added?

Regards

**Comment by 7nik** [comment]
`@match` follow [the match patterns](https://developer.chrome.com/docs/extensions/mv3/match_patterns/#what).

But you can use [`@include`](https://www.tampermonkey.net/documentation.php#meta:include), which allows wildcards at any place and regexp. Also, in `@include`, you can use `.tld` to match against any top-level domains.

**Comment by derjanb** [comment]
> Can we expect this feature to be added?

No, as @7nik explained. Sorry.

**Comment by jb222** [comment]
What about the ESLint warning? 
`Using @include is potentially unsafe and may be obsolete in Manifest v3 in early 2023. Please switch to @match.`

**Comment by derjanb** [comment]
> What about the ESLint warning?

See https://github.com/Tampermonkey/tampermonkey/issues/644#issuecomment-1222063721 for further updates.
