### ISSUE TITLE
Add `id` to `GM_registerMenuCommand`'s third parameter (`options`) to Recreate Menu Command.

### ISSUE THREAD

**Issue by helloworldSB** [Tampermonkey/tampermonkey#1865]
Same as violentmonkey/violentmonkey#1928.
> Some user-adjustable Boolean configurations require to use GM_registerMenuCommand.
After user click the Menu Command, script will change the Storage value, then Re-register Menu Command
In order to maintain the relative order, every Menu Command will be Re-register, it's very time-consuming.

This is VM's solution:
> Calling GM_registerMenuCommand with the same id in the `options` parameter will allow updating the item in-place.

Hope same feature will be implemented in Tampermonkey, please!

**Comment by helloworldSB** [comment]
@derjanb 
I think that `id` param should be a string, not a number, please !

**Comment by derjanb** [comment]
`id` was added in 5.0.6189 ([crx](https://data.tampermonkey.net/tampermonkey_beta.crx)|xpi in review)
`string` values will work as well.

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by verifymyuncle-jpg** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/1865

**Comment by verifymyuncle-jpg** [comment]
[](url)facebook.com
