### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by liquidmetalrob** [Tampermonkey/tampermonkey#1866]
The error I mentioned a year ago has come back. I'm running the newest version of Tampermonkey Beta (4.20.6187). Any page, even without a script is getting the error:

`Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by liquidmetalrob** [comment]
Why am I getting this error message?

**Comment by derjanb** [comment]
I don't see this. Do you have special settings applied?

**Comment by derjanb** [comment]
What is you browser ad OS version ?

**Comment by liquidmetalrob** [comment]
The error has stopped appearing now. It must have been caused by another extension.
