### ISSUE TITLE
Doesn't work in my browser

### ISSUE THREAD

**Issue by xiaoyuhaoge** [Tampermonkey/tampermonkey#1868]
(Please fill out the issue template with your details)

## Expected Behavior

Be able to run tampermonkey and inject scripts properly, save script data

## Actual Behavior

The latest version of TM keeps getting me stuck in the interface
![IMG_0656](https://github.com/Tampermonkey/tampermonkey/assets/134502767/7432ed6e-e61b-4d15-99ba-ff19f2e04432)

## Specifications

- Orion Browser: (1.3.4)
- TM: (4.20)
- OS: (ios 17.0.3)

This is an introduction to this browser, which allows Apple systems to run third-party extension
https://browser.kagi.com/

It even runs in ios! But unfortunately I installed the latest version of TM in ios Orion and it would keep getting stuck in the loading screen, but I tried installing version 4.14 and I can get to the screen normally and run some scripts, but it won't save the data of the scripts I've set up 😔 This browser can install extensions locally, and I've also tried Violentmonkey, which also has Violentmonkey also has some compatibility issues. But it runs the scripts normally and saves the script data.

**Comment by spiralx** [comment]
Same here as of earlier today with version 5.0.6189 on:

Windows 10
Chrome version 121.0.6114.0 (Official Build) canary (64-bit)

**Comment by spiralx** [comment]
The console shows this error in the background page:

```
Uncaught (in promise) TypeError: Error in invocation of tabs.get(integer tabId, function callback): Error at parameter 'tabId': Value must be at least 0.
    at et (background.js:240:433)
    at background.js:951:467
    at new Promise (<anonymous>)
    at background.js:951:456
    at Array.map (<anonymous>)
    at background.js:951:432
    at async K.init (background.js:951:372)
```

**Comment by derjanb** [comment]
Should be fixed at 5.0.6190 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Dead-TR** [comment]
Manual update fixed the problem

**Comment by CRYST4LF1GHT3R** [comment]
Any updates?

**Comment by Louie-G-is-cool** [comment]
Anyone able to fix this? Still trying to find out how to manually update on Orion.

**Comment by Louie-G-is-cool** [comment]
> Manual update fixed the problem

Teach me your ways.
