### ISSUE TITLE
Macbook Air M2 Sonoma 14.0 Safari 17.0

### ISSUE THREAD

**Issue by kristol** [Tampermonkey/tampermonkey#1871]
(Please fill out the issue template with your details)

## Expected Behavior
When clicking on the Tapermonkey icon it should open the modal 

## Actual Behavior
After clicking a small modal opens and there is a green and blue circles loading, after a while they disappear and only a white modal is visible

## Specifications
- Safari 17.0
- OS: Sonoma 14.0

**Comment by derjanb** [comment]
Duplicate of #1862
