### ISSUE TITLE
Can it support utf-8 reading of local file?

### ISSUE THREAD

**Issue by nanikit** [Tampermonkey/tampermonkey#1875]
## Expected Behavior
I expected the following should be prompted intact, but it didn't.
```javascript
prompt('안녕하세요');
```

## Actual Behavior
<img width="325" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/45276129/4ac1aa2d-fcef-4d71-8938-6240d6f53e53">

## Specifications

- Chromium: 118.0.5993.118 
- TM: 4.20.6187
- OS: windows 10.0.22621.2506

## Script

I loaded the local file by GM_getResourceText with file:/// scheme.

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @resource       somefile    file:///...script.user.js
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
With a file `bla.txt`

```
안녕하세요
```

and a script with:

```
...
// @resource      bla  file:///home/foo/bla.txt
// @grant         GM_getResourceText
...
prompt(GM_getResourceText('bla'))
...
```

This works fine here. Please add more details.

**Comment by nanikit** [comment]
I misinformed you, correct reproducible code is the below.
```
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @resource       somefile    file:///...script.user.js
// @grant none
// ==/UserScript==

alert(GM.info.script.resources[0].content)
```

I think this might be the intended behavior, so I'll close it for now.
