### ISSUE TITLE
"uncaught exception: Object" errors 

### ISSUE THREAD

**Issue by Purfview** [Tampermonkey/tampermonkey#1877]
Why there are "uncaught exception: Object" errors on `onerror` and `ontimeout` events from  `GM.xmlHttpRequest`?

## Script

```js
// ==UserScript==
// @name         uncaught exception: Object
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://www.blankwebsite.com/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=blankwebsite.com
// @connect      *
// @grant       GM.xmlHttpRequest
// ==/UserScript==

(function() {
    GM.xmlHttpRequest({
      method: "GET",
      url: "https://sfhgepiufh4hysfih4suhfsifudh.com",
      onload: function(response) {
        if (response.status != 200) {
          console.log("!!! HTTP Status " + response.status);
        }
      },
      onerror: function() {
        console.log("!!! Request Error");
      }
    });
})();
```

**Comment by derjanb** [comment]
Should be fixed at 5.0.6190 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
