### ISSUE TITLE
@match doesn't match partial domain with *

### ISSUE THREAD

**Issue by vanowm** [Tampermonkey/tampermonkey#1878]
When `*` used in domain, the domain doesn't match:
```
// @match https://example.*/*
```

Example:
```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://example.*/*
// ==/UserScript==

alert(1);

```

TM: v4.19.0
Edge: 118.0.2088.76

**Comment by 7nik** [comment]
It's correct behavior: `@match` follows [this specs](https://developer.chrome.com/docs/extensions/mv3/match_patterns/):
> If you use a wildcard in the host pattern, it must be the first or only character, and it must be followed by a period (.) or forward slash (/).

Use `@include`.

**Comment by vanowm** [comment]
The problem with `@include` is that creates a warning telling it's depreciated...Perhaps the warning need to be adjusted to allow cases like this.

**Comment by derjanb** [comment]
Thanks @7nik 

> The problem with @include is that creates a warning telling it's depreciated...

See https://github.com/Tampermonkey/tampermonkey/issues/644#issuecomment-1222063721
