### ISSUE TITLE
Make Tampermonkey Editors available to Firefox

### ISSUE THREAD

**Issue by ngdangtu-vn** [Tampermonkey/tampermonkey#1880]
I tried the link in the doc (https://vscode.dev/?connectTo=tampermonkey) from Firefox with the latest Tampermonkey (4.19.0) but it doesn't seems to work. Is this feature only for Chrome atm or this is a bug in Firefox edition?

**Comment by derjanb** [comment]
Another browser extension is needed to make this work, but it is available for Chrome only at the moment.

https://chrome.google.com/webstore/detail/lieodnapokbjkkdkhdljlllmgkmdokcm

**Comment by iamqiz** [comment]
@derjanb do you plan to make the Editors extension open source?  (i am very curious about its mechanism)

**Comment by derjanb** [comment]
Note sure atm. The first step is to make it available to Firefox.

**Comment by derjanb** [comment]
Fixed: https://addons.mozilla.org/addon/tampermonkey-editors/

You have to use the BETA version from http://tmnk.net for now.
