### ISSUE TITLE
Tampermonkey not fully loading at the start of the session (Firefox)

### ISSUE THREAD

**Issue by TsukiZero** [Tampermonkey/tampermonkey#1885]
Okay, this issue is an odd one to explain, but has happened at least four times now: Basically in rare instances Tampermonkey will be stuck "loading" shortly after starting a session with Firefox, and in turn no script will load. It can be dealt with by disabling and enabling Tampermonkey, which forces it to load appropriately. So in short, a small and rare nuisance that might be worth investigating.

**Comment by krystian3w** [comment]
Same for 4.19 and 5.x releases.

For 5.x with some changes in settings and installed some scripts it is locked at all load pages (even lan router panel). So investigate is needed to avoid ban addon or version by Moz://a team in 2024+.

**Comment by krystian3w** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/1888

**Comment by derjanb** [comment]
> Okay, this issue is an odd one to explain, but has happened at least four times now:

@TsukiZero Can you please check the background console when this happens. Do you see errors? 

-> https://extensionworkshop.com/documentation/develop/debugging/

**Comment by TsukiZero** [comment]
I could try, but it is completely unpredictable when it will happen. If I just had a more consistent trigger....

**Comment by krystian3w** [comment]
My 5.x is still broken.

**Comment by derjanb** [comment]
> My 5.x is still broken.

Can you please check the background console when this happens. Do you see errors?

**Comment by krystian3w** [comment]
I see these error:

```yml
Uncaught (in promise) Error: Type error for parameter tabId (Integer -1 is too small (must be at least 0)) for tabs.get.
    $e moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:244
    init moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:969
    init moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:969
    init moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:969
    init moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:969
    <anonymous> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
    <anonymous> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
    <anonymous> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
[background.js:244:251](moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js)
    init moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
    AsyncFunctionThrow self-hosted:856
    (asynchroniczny: async)
    <anonimowa> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
    <anonimowa> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
    <anonimowa> moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js:986
alarm: init done 
Object {  }
 
Object {  }
[background.js:433:413](moz-extension://d18ff8a1-d4d0-496e-be8f-3c1ba2950a69/background.js)
```
​

**Comment by derjanb** [comment]
Thanks a lot!

**Comment by derjanb** [comment]
Should be fixed at 5.0.6190 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by krystian3w** [comment]
I can try latter, and you mean hard jump 4.19 stable go 5.x stable without 4.20+ line?

**Comment by XanPL** [comment]
The plugin blocks access to websites and the router's home page!
Version 5.0.0
[console-export-2023-12-13_16-43-48.txt](https://github.com/Tampermonkey/tampermonkey/files/13663048/console-export-2023-12-13_16-43-48.txt)

**Comment by derjanb** [comment]
@XanPL Your issues is tracked here: https://github.com/Tampermonkey/tampermonkey/issues/1921

**Comment by XanPL** [comment]
> @XanPL Your issue is tracked here: #1921

Thank you for your help. Everything is back to normal. Regards!
