### ISSUE TITLE
Documentation for GM_saveTab is wrong

### ISSUE THREAD

**Issue by LightAPIs** [Tampermonkey/tampermonkey#1889]
The [documentation](https://www.tampermonkey.net/documentation.php?locale=en#api:GM_saveTab) says:

> The `GM_saveTab` function saves the provided tab information, so that it can be retrieved later using the `GM_getValue` function.

The `GM_getValue` here should be `GM_getTabs`.

**Comment by derjanb** [comment]
Fixed. Thanks for reporting.
