### ISSUE TITLE
webhook to sync code not work

### ISSUE THREAD

**Issue by a1mersnow** [Tampermonkey/tampermonkey#1891]
## Expected Behavior
When there is a release, github will send a request to tampermonkey.com, then the site will update the script via the specified url.

## Actual Behavior
Granted, github send the request, but it failed.

## Specifications

- Chromium: 119.0.6045.105
- TM: 4.19.0
- OS: MacOS 14.1

## Detail
Here is my settings:
<img width="528" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/1bf75926-3b1b-4589-891b-434da56493df">
<img width="820" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/46e4de23-2bf9-4b7a-9199-e7ec863891f1">

When a release is created, released, published, it will send three requests:
<img width="789" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/13db7932-8a81-487b-99ef-d58a251c6f2e">
However, the last one always failed.

And, there is no error message telling me why:
<img width="844" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/59ddd01c-5472-4b37-9b06-7d2b2c75028b">

**Comment by derjanb** [comment]
I don't get what you're asking for here. Sorry.

**Comment by a1mersnow** [comment]
1. Go to one of your script e.g. https://greasyfork.org/en/scripts/479295-%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98%E6%89%B9%E9%87%8F%E9%87%8D%E5%91%BD%E5%90%8D?locale_override=1
2. On the top area of the page, there are Info, Code...Admin.
3. Switch to the Admin tab.
4. Scroll to the `Source Syncing` part.
5. There is a `set up a webhook` link, enter this link.
6. I follow the `Github` part of the doc.
7. But I did't get the script synced successfully when I release my script's new veresion. I checked the github side, and found that github had already send the requests.

**Comment by derjanb** [comment]
Please report your issue here -> https://github.com/JasonBarnabe/greasyfork/issues
