### ISSUE TITLE
Managent panel and popup menu are too large at 100 zoom 

### ISSUE THREAD

**Issue by 11Ye** [Tampermonkey/tampermonkey#1894]
(Please fill out the issue template with your details)
In the Firefox 119 version, the default size of the management panel and popup menu is too large. Although the menu size can be zoomed out by CTRL+Mouse Wheel, it will restore its original size when reopened or opening a new tab.

## Expected Behavior
![2](https://github.com/Tampermonkey/tampermonkey/assets/34735453/a6dc602f-adf3-460e-a434-a6e80f1b6db5)

## Actual Behavior
![1](https://github.com/Tampermonkey/tampermonkey/assets/34735453/de9a6d4d-3bb9-4a89-84ed-27620ac7c218)

## Specifications

- Firefox: (119.0.1)
- TM: (4.19.0) / (5.0.6189)
- OS: (Windows 11 23H2)

## Script
--

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/1819#issuecomment-1646451238
