### ISSUE TITLE
tampermonkey activates the cloudflare security page not working.

### ISSUE THREAD

**Issue by monkeyde98** [Tampermonkey/tampermonkey#1895]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```
tampermonkey activates the cloudflare security page not working.

**Comment by derjanb** [comment]
What OS and browser are you using? Do you have a page that triggers the cloudflare page?

**Comment by monkeyde98** [comment]
this faucet when you enter the page cryptoearns.com/faucet.  after logging in and going to this page.

**Comment by monkeyde98** [comment]
I tested blacklisting cloudflare.com.  and in filter mode I put both, so I can access the sites.  However, I have to whitelist the sites I want to access.

**Comment by derjanb** [comment]
Please try "Instant" `Injection Mode` in Chrome or `Content Script API` set ot "Userscripts API Dynamic" in Firefox.

**Comment by NGSpace** [comment]
didn't work for me!

**Comment by derjanb** [comment]
Duplicate of #2057?
