### ISSUE TITLE
Microsoft Edge Extensions shop always in old ver

### ISSUE THREAD

**Issue by tkp206093** [Tampermonkey/tampermonkey#1899]
(Please fill out the issue template with your details)

## Expected Behavior
update

## Actual Behavior
https://microsoftedge.microsoft.com/addons/detail/tampermonkey-beta/fcmfnpggmnlmfebfghbfnillijihnkoh
![image](https://github.com/Tampermonkey/tampermonkey/assets/29872453/936cef86-b805-40ed-8f90-43d9aebca09e)
https://chromewebstore.google.com/detail/%E7%AF%A1%E6%94%B9%E7%8C%B4%E6%B8%AC%E8%A9%A6%E7%89%88/gcalenpjmijncebpfijmoaglllgpjagf
![image](https://github.com/Tampermonkey/tampermonkey/assets/29872453/87149d09-5a6e-49e7-97e3-93b38475bdad)

## Specifications

- Microsoft Edge 119.0.2151.72
- TM: 5.0.6189
- OS: Windows 11 23H2 22631.2787

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Already uploaded the latest version. Should be auto-update after review soon. Thanks for reporting.
