### ISSUE TITLE
Confirmation popup for when removing scripts from the Dashboard?

### ISSUE THREAD

**Issue by KilliK69** [Tampermonkey/tampermonkey#1901]
Hello.
I would like to know if TM has an option to enable a confirmation dialog box whenever I delete a script from the Dashboard?
Right now, if I click the trash bin, the script gets removed immediately. That makes it a bit risky to accidentally delete a different script.
I looked into the options, but I only found a setting for a confirmation when saving a script.

and this tutorial shows that a confirmation popup does exist, at least when the guide was written:

https://www.wikihow.com/Delete-a-Script-in-Tampermonkey

So does this feature exist? if yes, how do i enable it. if not, is it possible to implement it?
thank you.

**Comment by 7nik** [comment]
Userscripts go to the trash bin, where you can easily restore them or completely delete them with a confirmation popup.

**Comment by derjanb** [comment]
... and if "Trash Mode" is set to "disabled", then you'll be asked whether you really want to delete the script immediately.
