### ISSUE TITLE
Inject mode instant doesn't work with local files

### ISSUE THREAD

**Issue by Murka007** [Tampermonkey/tampermonkey#1903]
I don't know if this was intentionally designed or not, but when I have `Inject Mode Instant` enabled, loading local files from the computer using `@require` is significantly slower than loading from a localhost server. This completely disrupts my development process as I cannot speed up the execution of my code. I noticed one detail: when loading from localhost, we can see a request from `chrome-extension` in the network tab, whereas there are no logs for local files. I haven't tested yet whether file size affects injection speed. But my file weighs only 406KB.

![image](https://github.com/Tampermonkey/tampermonkey/assets/54054900/32063c1c-39b3-4fca-b963-56949e23ce84)

## Specifications

- Chromium: 119.0.6045.160
- TM: v4.19.0

### Injects slower than usual, doesn't show any requests in the network tab
```js
// ==UserScript==
// @run-at document-start
// @require file:///C:/Users/Danil/Desktop/host-connector/dist/hoster.user.js
// ==/UserScript==
```

### Instant injection, shows request in the network tab
```js
// ==UserScript==
// @run-at document-start
// @require http://localhost:8081/dist
// ==/UserScript==
```

**Comment by derjanb** [comment]
That is correct. Local files are never cached, but read from the disk while the page continues to load. `http` resources are cached and are therefore available instantly.
