### ISSUE TITLE
URLs from gitlab are not recognized as user scripts

### ISSUE THREAD

**Issue by vitoyucepi** [Tampermonkey/tampermonkey#1911]
## Expected Behavior

URLs from gitlab.com and self-hosted instances, should be recognized as userscripts.
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/raw/main/main.user.js?ref_type=heads
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/snippets/3626987/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/wikis/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/raw/main/main.user.js?ref_type=heads
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/snippets/3626988/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/wikis/main.user.js

## Actual Behavior

These URLs are not recongized as userscripts.
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/snippets/3626987/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/s1/-/wikis/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/raw/main/main.user.js?ref_type=heads
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/snippets/3626988/raw/main/main.user.js
1. https://gitlab.com/tampermonkey-issue-1911/g1/s2/-/wikis/main.user.js

## Specifications

- Chromium: *119.0.6045.199*
- TM: *4.19.0*, *5.0.0*
- OS: Linux

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
