### ISSUE TITLE
[5.0] Feature detection with addEventListener not work now

### ISSUE THREAD

**Issue by Ocrosoft** [Tampermonkey/tampermonkey#1913]
## Expected Behavior
```
    window.addEventListener("test", null, Object.defineProperty({}, 'passive', {
        get: function () { supportsPassive = true; }
    }));
```
Feature detection not work with version 5.0.
I found this in the changelog, maybe I should use 'unsafeWindow'?
`Make sandbox window addEventListener support EventListenerObjects`

## Actual Behavior
The 'get' function was not called.

## Specifications

- Chromium: (120.0.6099.63)
- TM: (5.0.0)
- OS: (Windows 11)

**Comment by derjanb** [comment]
Should be fixed at 5.0.6192 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
