### ISSUE TITLE
added load event listener on window object doesn't run when tab is not focussed

### ISSUE THREAD

**Issue by devnull69** [Tampermonkey/tampermonkey#1916]
I add a load event listener to the window object in my userscript. I can see that it is triggered whenever the tab is focussed. But when it is not focussed, the event listener is never triggered. The script uses setTimeout to reload the page, which works.

## Expected Behavior
window load event should trigger the execution of the user script code also when tab is not on focus

## Actual Behavior
When tab is out of focus, load event listener is not triggered

## Specifications

- Chrome (current version)

## Script

```
// ==UserScript==
// @name         XXXXXXXXXXXXXX
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  XXXXXXXXXXXXXXXXX
// @author       You
// @match        https://www.xdjkfhskdhfksdhfksd.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    setTimeout(() => {
        window.location.reload();
    }, 60*1000);
    console.log("Timer started ... 60 sec");

    window.addEventListener("load", e => {
        console.log("Executing script...");
    }, false);
})();
```

I can see the "Timer started ... 60 sec" output every time, but the "Executing script..." only appears when tab is on focus

**Comment by derjanb** [comment]
You're using no 

```
// @run-at document-start
```

statement.

Therefore the userscript is potentially injected after the "load" event.
