### ISSUE TITLE
UX request: Change the official site favicon to differentiate it from the extension dashboard.

### ISSUE THREAD

**Issue by DanKaplanSES** [Tampermonkey/tampermonkey#1918]
I will use this image to demonstrate the motivation for this suggestion:

![image](https://github.com/Tampermonkey/tampermonkey/assets/373675/0b0a6e3a-c526-4542-97be-6acf054fbdaf)

Which of these tabs contains the script your editing and which one contains the documentation? I've cheated by obscuring the tab names, but I'd like to be able to answer this question at a glance. Because they use the same icons, I find myself clicking on the wrong one a lot of the time, which is a very minor annoyance, but it occurs multiple times as I developed a script.

If this is a reasonable request, I don't think it needs to be a big change. For example, making one icon a shade lighter/darker would likely suffice.

**Comment by derjanb** [comment]
You can use the BETA version for development. It uses a red icon. 😉

**Comment by derjanb** [comment]
Some research showed that others are handling this the same way. Favicons are often used at more than one place.

**Comment by DanKaplanSES** [comment]
> Favicons are often used at more than one place.

To clarify, you mean often *reused* in multiple places?

**Comment by DanKaplanSES** [comment]
@derjanb Sorry, forgot to ping you above ^
