### ISSUE TITLE
5.0 UI looks broken after an update

### ISSUE THREAD

**Issue by mozew** [Tampermonkey/tampermonkey#1922]
![brave_IFELGfPdY6](https://github.com/Tampermonkey/tampermonkey/assets/10653234/341731ea-d483-4279-a428-8f797eb53997)
![brave_fECpvsBa52](https://github.com/Tampermonkey/tampermonkey/assets/10653234/a3f429a8-7d1c-474b-a3db-8b5014888e95)

**Comment by derjanb** [comment]
Please use "Default - Dark" as a temporary workaround...

**Comment by mozew** [comment]
that's not needed, as a temporary workaround I use this custom css style:
![msedge_YeqOFzZASs](https://github.com/Tampermonkey/tampermonkey/assets/10653234/975c7c81-1cb2-48bc-9653-ad9d9e866559)

**Comment by derjanb** [comment]
"Duplicate" of #1928 (at least it fixes the issue)

**Comment by derjanb** [comment]
Seems to be a Chrome issue. 

Can reproduce at:
* Version 120.0.6099.71

Can't reproduce at:
* Version 121.0.6167.16
* Version 122.0.6170.5

**Comment by mozew** [comment]
You might have noticed that the "scrollbar-width" property is grayed out in the screenshot above. It looks like it hasn't been implemented in Chrome until version 121.
![brave_GOF03HpoUP](https://github.com/Tampermonkey/tampermonkey/assets/10653234/a0ce4efc-c53b-4323-b04c-fb610357f746)

**Comment by mozew** [comment]
Discovered that custom CSS rules are not applied to the installation page.

**Comment by derjanb** [comment]
Both issues are fixed at 5.0.1

Thanks for reporting
