### ISSUE TITLE
Add ability to disable "release notes" after updates

### ISSUE THREAD

**Issue by chascode** [Tampermonkey/tampermonkey#1926]
## Expected Behavior

I open my browser without any new and annoying tabs opening.

## Actual Behavior

An annoying new tab opens to tell me what's new with Tampermoney.

## Specifications

- Firefox 120.0.1
- Debian Bookworm

## Script

N/A

**Comment by derjanb** [comment]
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/427#issuecomment-319625319
