### ISSUE TITLE
UX request: In the dashboard, add a label to the trash icon tab

### ISSUE THREAD

**Issue by DanKaplanSES** [Tampermonkey/tampermonkey#1928]
![image](https://github.com/Tampermonkey/tampermonkey/assets/373675/ee5560db-f16e-4fac-b04e-8415904e059c)

Given the way the blue circled trash icons work, clicking on this red trash icon can be a little intimidating: "Is this going to delete all my scripts?" A label would set some expectation of what clicking on the red icon will do. I recommend calling it "Trash Bin" or something similar, but not "Trash". I can't explain why, but "Trash" doesn't clarify what clicking on it will do. 

I personally like the icon and think it should remain. My request is about _adding_ a label, not _replacing_ the icon.

## Specifications

-     Firefox 120.0.1 (64-bit)
-     TM: 5.0.0
-     OS: Windows 10

## Script

n/a

**Comment by jb222** [comment]
BTW. In Chrome (Mac) the icon looks different, is hardly visible and is too big. Why not use a similar (simple) icon as used in the action column?
![Schermafbeelding 2023-12-10 om 21 24 12](https://github.com/Tampermonkey/tampermonkey/assets/61352184/e96c03e7-259f-40aa-815b-a5c595de5465)
![Schermafbeelding 2023-12-10 om 21 24 31](https://github.com/Tampermonkey/tampermonkey/assets/61352184/c9bae94b-08e3-4358-ab54-dedce3f62979)

**Comment by derjanb** [comment]
Should be fixed at 5.0.6192 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
