### ISSUE TITLE
Version 5.0.0 Endless Loading

### ISSUE THREAD

**Issue by DanR2000** [Tampermonkey/tampermonkey#1929]
- Firefox 120.0.1 (64-bit)
- OS: (Windows 10 Pro 22H2 - build 19045.3693)

Since updated to Version 5.0.0 - Tampermonkey has stopped working, the result of this issue is a neverending loading of the extension, with browser blank pages
![tampermonkey-endless](https://github.com/Tampermonkey/tampermonkey/assets/153353124/8371afc2-182e-4717-ab42-c308b527b23d)
.
I have tried to find the solution in the browser settings and changing user profile ... none of them worked.
I downgraded to version 4.19.0, hoping that this issue gets resolved in the next version _

**Comment by derjanb** [comment]
Thanks for your bug report. Please see https://github.com/Tampermonkey/tampermonkey/issues/1921#issuecomment-1846906251
