### ISSUE TITLE
refreshed require for specific links

### ISSUE THREAD

**Issue by ttodua** [Tampermonkey/tampermonkey#1933]
As an echo for https://github.com/Tampermonkey/tampermonkey/issues/475#issuecomment-348594785

Is it possible that you implemented a functionality, so instead of :
```
// @require      http://127.0.0.1/file.js
```
we could
```
// @require-fresh      http://127.0.0.1/file.js
```

so everytime the userscript is loaded, it got the fresh content (of `http://127.0.0.1/file.js`) instead of having a cached version embeded. 
or you provided some easier way to always load the fresh content.  (the `Update Interval> Always` setting is nowhere near a solution, because users want to specifically mark which files should be loaded as fresh everytime, and not a global setting for tapermonkey which would affect all "require"-d script)

**Comment by derjanb** [comment]
In Chrome it is not possible to do asynchronous operations while Tampermonkey is blocking a web request for bundling all things together to run a script and net resources can only be read synchronously by a synchronous XHR, which is deprecated.

In Firefox you can do asynchronous things while blocking a web request, so it would work there.

However, `@require` is not intended for regular updates and you can do it by yourself by using a synchronous XHR (don't forget the CORS header at your HTTP server) in your script and simply evaluating the code.

**Comment by ttodua** [comment]
thanks for answer, but
> ... don't forget the CORS header at your HTTP server
what I we want to load script, but we don't control that server? i.e. `unpkg.com/package-name@latest`, or even some 3rd party site that we don't control, but we want to load the fresh content from the script/link. so, there is no other easy way with TM?

**Comment by ttodua** [comment]
as a side comment, maybe you could apply this:
> the Update Interval> Always

was available per script-level settings and not in global TM settings only
