### ISSUE TITLE
`GM_OpenInTab` opens a new tab on every event page reload

### ISSUE THREAD

**Issue by derjanb** [Tampermonkey/tampermonkey#1935]
In Firefox with Tampermonkey 5.0.0, the GM_OpenInTab call is correctly opening the specified page.  After 30 seconds or so, a blank tab will open for each call that was made to OpenInTab.  This repeats forever unless each "stream" of opening tabs is closed before they spawn new ones.

## Specifications

- Firefox

**Comment by pootz10** [comment]
I came to report exactly this. That started to happen after the 5.0.0 update.
I'm happy it's already known.

Another day I was idle for 10 hours of new tabs opening.
Imagine, the trouble, I had to hold ctrl+W for a long time to close all.

**Comment by ejm554** [comment]
I'm not sure if my problem is the same as #1935, or if I should report it as a new Issue, but I've been noticing that my Firefox browser has been opening new tabs from Microsoft. When I leaving my device unsupervised, it will do this repeatedly, and I will discover an absurd number of new Microsoft tabs. See screenshot.

After examining the URL of these new tabs, I can see that Tampermonkey is the source. The address includes a reference to OneDrive.
```https://login.live.com/oauth20_authorize.srf?response_type=token&client_id=000000004C1A3122&redirect_uri=https%3A%2F%2Fauth.tampermonkey.net%2Foauth.php&state=!!onedrive-0393aecb-5830-4c48-a0de-c2ed8d2f9f44&scope=onedrive.appfolder```

I subsequently turned off the Tampermonkey features that were set (by me) to use OneDrive, i.e. **Utilities > Cloud** backup and **Settings > Userscript Sync**. (See additional screenshots.) 

If you would like me to report this as a new issue, let me know.

### Screenshots

**Example of new-tabs issue**
![image](https://github.com/Tampermonkey/tampermonkey/assets/26723535/1c9877c1-5110-422c-81f7-952b5f9f4d36)

**Examples of suspect Tampermonkey features**
![image](https://github.com/Tampermonkey/tampermonkey/assets/26723535/4588ef84-20ad-42eb-906e-70449af037c4)

![image](https://github.com/Tampermonkey/tampermonkey/assets/26723535/ca8bae27-16ed-4e02-9aa6-7d87dd3314fe)

**Comment by derjanb** [comment]
@ejm554 Is is the same issue. Sorry for any inconvenience. A new BETA is already in review since 2023-12-14 but it takes some time to run through...

**Comment by trumpeta** [comment]
I think I have the same issue, after invoking a script by TM, a dozens of blank tabs are opened randomly at idle time.

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by pootz10** [comment]
Thank you, I'll try it.

**Comment by derjanb** [comment]
5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/

Sorry for any inconvenience!
