### ISSUE TITLE
GM_registerMenuCommand in shortcut mode Chrome not showing

### ISSUE THREAD

**Issue by anlv** [Tampermonkey/tampermonkey#1936]
## Expected Behavior
In shortcut mode of Chrome (Three dot > More tools > Create shortcut > Open as window) the menu should display when click icon tampermonkey.
![image](https://github.com/Tampermonkey/tampermonkey/assets/8207962/2183c934-144e-42ea-8aad-b9c42374475e)

## Actual Behavior
In shortcut mode, the menu command is not showed.
![image](https://github.com/Tampermonkey/tampermonkey/assets/8207962/09ae8659-de9f-4762-ac6a-8666e8d14a7a)

## Specifications
After update tampermonkey to 5.0.0, it doesn't show the menu.
- Chromium: 120.0.6099.71
- TM: 5.0.0
- OS: Windows 10

## Script

```js
GM_registerMenuCommand("Dark Mode", sendDarkMode, 'k');
```

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by anlv** [comment]
It is fixed.
