### ISSUE TITLE
Small improvement of the User Interface of Tampermonkey Dashboard if possible

### ISSUE THREAD

**Issue by SunSea88** [Tampermonkey/tampermonkey#1938]
Hello,

I don't know if this idea has already been mentioned here before, but if so I apologize for that.

It's possible to add a column with the author's name to the Dashboard of Installed userscripts between "Features" and "Homepage" : a new column Author please ?

Thank you in advance

**Comment by SunSea88** [comment]
Also if it's possible to add a search feature for scripts in the dashboard, because it's really useful when you have more than 50 scripts...

For example : be sure that you have already installed a particular script or quick access to a particular script...

**Comment by derjanb** [comment]
Does Ctrl/Cmd+F work for you?

**Comment by SunSea88** [comment]
> Does Ctrl/Cmd+F work for you?

Thank you very much and Very sorry because it's works very well ; maybe I misread the FAQ before contacting you for the search feature 😥

**Comment by derjanb** [comment]
Author column is tracked here: #1990
