### ISSUE TITLE
Forced to donate, donation dialog won't close

### ISSUE THREAD

**Issue by thojanssens** [Tampermonkey/tampermonkey#1941]
![2023-12-14_14-48-27](https://github.com/Tampermonkey/tampermonkey/assets/39990638/77cdc147-ce69-4cf5-bafd-12c7716cb1b0)

As seen on the print screen attached, I am forced to donate. There is no way I can close the dialog box. I tried to click outside but the modal remains open. There is no Close button.

So TamperMonkey is a paid software or a free service for which one can optionally donate?

Is it possible to make up one's mind? Because as it is now, it seems a fake free service, and donations are actually subscriptions but users are deceived into thinking the service is free and ask for some generosity while it is not.

**Comment by derjanb** [comment]
Why not simply click at "Remind my later" or one of the other buttons? If you click at one of the other you won't be ask again.

**Comment by thojanssens** [comment]
I thought these buttons were in the disabled background. Ty

**Comment by derjanb** [comment]
Yes, probably because of missing dark mode support... I'll take care of that.
