### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by LeoCPlays** [Tampermonkey/tampermonkey#1942]
I thinked it would load,

But it didnt,it got to the loading icon and remained there,the loading icon was moving by the way.

 Specifications of browser:

Google Chrome	120.0.6099.71 (Build ufficiale) (a 64 bit) (cohort: Stable) 
Revision	9729082fe6174c0a371fc66501f5efc5d69d3d2b-refs/branch-heads/6099_56@{#13}
Sistema operativo	Windows 11 Version 22H2 (Build 22621.2861)
JavaScript	V8 12.0.267.8
User-agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command line	"C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=WebGPU

![Screenshot 2023-12-14 171951](https://github.com/Tampermonkey/tampermonkey/assets/140756217/4588cace-4251-4657-b903-5831850aacb8)

**Comment by derjanb** [comment]
Please check the background page console for errors.

**Comment by maboroshin** [comment]
On my Windows 10 it occurs in FireFox, not Chrome. TamperMonkey are both 5.0.0.

All sites take 1 minute to load. And the loaded site is not running JavaScript. TanperMonkey remains as a rotating icon. (Same image as pasted by LeoCPlays) I can't open options.html from FireFox add-ons page.

From Ctrl-Shift-J:```
Async method failed in safeAsyncMethod Error: The target doesn't support creating highlighters by types or BoxModelHighlighter is unknown
    getHighlighterByType resource://devtools/client/fronts/inspector.js:148
async-utils.js:65:17

Error while calling actor 'watcher's method 'watchResources' An attempt was made to use an object that is not, or is no longer, usable Actor.js:105:13
    writeError resource://devtools/shared/protocol/Actor.js:105
    handler resource://devtools/shared/protocol/Actor.js:244

DOMException: An attempt was made to use an object that is not, or is no longer, usable
    addOrSetSessionDataEntry resource://devtools/server/connectors/js-window-actor/DevToolsFrameParent.sys.mjs:108
Actor.js:112:15

AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved ConduitsParent.sys.mjs:362

AbortError: Actor 'Conduits' destroyed before query 'RunListener' was resolved 2 WebRequest.sys.mjs:1072
```

**Comment by maboroshin** [comment]
Tampermonkey BETA (5.0.6191) is working. Install scripts that worked at all sites. https://adsbypasser.github.io/ Still, TamperMonkey is working.

**Comment by derjanb** [comment]
Just to be sure: TM BETA 5.0.6191 fixed the issue, right?

**Comment by maboroshin** [comment]
Yes, I had this happen with Firefox.

However, the stubble version doesn't work, so the registered scripts can't be reproduced.

**Comment by derjanb** [comment]
5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/

Sorry for any inconvenience!

**Comment by maboroshin** [comment]
Yes, The issue has been fixed in 5.0.1.
