### ISSUE TITLE
How to activate DevTools Device Tool bar (Mobile view) using Tampermonkey script?

### ISSUE THREAD

**Issue by SalimF** [Tampermonkey/tampermonkey#1943]
## Expected Behavior
I want to  activate DevTools Device Tool bar (Mobile view button), in one of my pages without need to 

open DevTools each time I do that 

![image_2023-12-15_200240788](https://github.com/Tampermonkey/tampermonkey/assets/16048674/221aacea-0bc7-499a-99ec-b5b6b830007d)

## Actual Behavior
None

## Specifications

- Opera: (Version:98.0.4759.6)
- TM: (i.e. 4.5.5648)
- OS: (i.e. ArchLinux 6.5.5)

**Comment by derjanb** [comment]
This is not possible. Tampermonkey has no access to the browser's developer tools.
