### ISSUE TITLE
Make GM_registerMenuCommand re-registrations of top frame scripts win if multiple instances are executed

### ISSUE THREAD

**Issue by Owyn** [Tampermonkey/tampermonkey#1951]
Tried to open my scripts config menu (menu - > `D` hotkey) via `GM_registerMenuCommand` menu
but got the CSP error instead `Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

Then I scrolled down and saw my menu being open in the disqus comments iframe insteads, so that's probably why 🤔 
![image](https://github.com/Tampermonkey/tampermonkey/assets/1309656/2ec2cd19-2f1b-423f-bd0a-035057229e38)

other hotkey (menu ->`T`) was working fine

also reloading the page helped to make it work normally again

## Expected Behavior
no error and menu hotkeys working for the top level

## Actual Behavior
error and weird behavior

## Specifications

- Chromium: Firefox 121
- TM: v5.0
- OS: Win 10

## Script
https://github.com/Owyn/Universal_Dark_Theme/raw/master/uni_dark_theme.user.js

**Comment by derjanb** [comment]
What is the page the script is running on?

**Comment by Owyn** [comment]
> What is the page the script is running on?

On the screen it was https://manhuaus.com/manga/im-an-evil-god-1/chapter-408/ (the very bottom of the page) and it was reproducable every time, now when I press it it seems to work

btw, but https://github.com/Tampermonkey/tampermonkey/issues/1270 seem to get reproduced just fine if I use the menu to ON & OFF it continuously - it just gets broken after a short while (or right off the start menu hotkeys do nothing) - not sure if it's related, but maybe - since it's also a menu-invoked issue

**Comment by derjanb** [comment]
> now when I press it it seems to work

So this issue seems to be that the script or code is not running at the top frame and therefore the menu command executed at a iframe. The question is why and what exactly could not be executed at the main frame.

Tampermonkey recently switched from automatic CSP relaxing to falling back to a Firefox userScript API sandbox, which can cause issues.

That issue might be related: #1949 

Please reopen if you see this issue again.

>  it just gets broken after a short while

I reopened #1270

**Comment by derjanb** [comment]
Note the config dialog does not work anymore if the menu command is clicked while another dialog is open.

**Comment by Owyn** [comment]
> Note the config dialog does not work anymore if the menu command is clicked while another dialog is open.

What  do you mean?
I tried clicking the TM config dialog while uBlock menu was open and it worked

but I usually just click the TM icon and that's it

**Comment by derjanb** [comment]
> What do you mean?

If you click "Dark Theme Configuration" twice, then the dialog looks like this and can't be closed anymore.

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/c122493c-dd6e-4214-83af-3869cb6c96df)

**Comment by Owyn** [comment]
ah, I know about that, I didn't do it it that way :-)

**Comment by derjanb** [comment]
> it was reproducable every time, now when I press it it seems to work

This happens when you wait for at least 30 seconds after page load and the background event page is unloaded and started again. Then a click at the menu command triggers a CSP error.

I don't know why it works before the background page is restarted (yet?!). 
It's probably triggered by `onclick='return false;'` inside the attached config dialog div.

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
