### ISSUE TITLE
All scripts wiped by Firefox browser after update

### ISSUE THREAD

**Issue by luizhrios** [Tampermonkey/tampermonkey#1954]
Second time it happened now, after every update the scripts are being deleted, and now there's a chance I lost some because the backup is not new. I doubt there's any corruption, even less possible to be twice in a row, I just restarted the browser to update and everything wiped.
Is there any way to recover from the browser files?

## Expected Behavior

Scripts to not be deleted

## Actual Behavior

All scripts deleted after update

## Specifications

- Firefox: 122.0b3
- TM: 5.0.0
- OS: Windows 10

**Comment by derjanb** [comment]
> Is there any way to recover from the browser files?

Do you have a backup of Firefox's profile folder?

> Scripts to not be deleted

Tampermonkey can only rely on the storage API provided by Firefox. If this storage is unreliable then there is nothing a browser extension can do. Sorry.

**Comment by luizhrios** [comment]
> Do you have a backup of Firefox's profile folder?

Before the wipe? No

> Tampermonkey can only rely on the storage API provided by Firefox. If this storage is unreliable then there is nothing a browser extension can do. Sorry.

I don't know what you mean by storage unreliable, I've been using it forever and just in a short amount of time, I got the same problem on 2 different devices, same version of browser / extension

**Comment by luizhrios** [comment]
> > Is there any way to recover from the browser files?
> 
> Do you have a backup of Firefox's profile folder?
> 
> > Scripts to not be deleted
> 
> Tampermonkey can only rely on the storage API provided by Firefox. If this storage is unreliable then there is nothing a browser extension can do. Sorry.

**Comment by derjanb** [comment]
References: 

* https://bugzilla.mozilla.org/show_bug.cgi?id=1522188
* https://bugzilla.mozilla.org/show_bug.cgi?id=1519859

**Comment by derjanb** [comment]
Do you see errors being logged at the background page?

https://extensionworkshop.com/documentation/develop/debugging/#debugging-background-scripts

**Comment by derjanb** [comment]
Do you use [script sync](#1739)?

**Comment by luizhrios** [comment]
It just happened again after updating to 122.0b5, this is probably gonna make me change browser, way too annoying and it's really the browser because it happens with multiple extensions, some still have data like normal but some were wiped like I just installed, and also some websites I'm logged off (lost data) and others normal. This still never happened with Chrome, which I also use the extension.

![tampermonkey](https://github.com/Tampermonkey/tampermonkey/assets/15158462/d5e89c5a-20f0-4b5d-a511-ac651ba37a92)

Since it's probably the browser somehow messing everything up, you can close it. If you can give tips to try to recover scripts, if it's possible, would be nice.

> Do you see errors being logged at the background page?

After the wipe, I'm not seeing any errors. I'm gonna check everytime the browser asks to restart, if I still keep using firefox.

> Do you use script sync?

No

**Comment by hellresistor** [comment]
no backups :(

**Comment by derjanb** [comment]
Sorry. :(
