### ISSUE TITLE
Check for script update

### ISSUE THREAD

**Issue by Sandor-Helper** [Tampermonkey/tampermonkey#1955]
Hi,
After updating to v.5.0.0, when editing the script and saving changes, the “check for updates” checkbox continues to be displayed.
In fact, it seems to be disabled and only displayed as it does not automatically check for script updates.

**Comment by derjanb** [comment]
The dashboard shows that the script was modified and therefore needs a manual update:

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/71d62473-ec4b-4e0c-bf70-277d11bd88df)
