### ISSUE TITLE
[BUG] GM_download is limited to single-threaded

### ISSUE THREAD

**Issue by CrayonSSR** [Tampermonkey/tampermonkey#1956]
## Expected Behavior
**All downloads should start downloading at the same time(±500ms).**

## Actual Behavior
**The first download will start immediately.** 

**The second download will not start until the first download is complete.**

```js
// looks like
await download 1st task 
await download 2nd task 
await download 3rd task 
```

## Specifications

- Chromium: (120)
- TM: (Stable 5.0.0 & Beta 5.0.6192)
- OS: (Window 10)

## Extension config

**Download mode: [browser API]**

## Script

```js
// ==UserScript==
// @name                 MyName
// @namespace           http://mywebsite.com
// @version             1.0
// @description         try to take over the world!
// @author              Me
// @match               https://www.tampermonkey.net
// @match               https://www.tampermonkey.net/*
// @connect             *
// @grant               GM_info
// @grant               GM_xmlhttpRequest
// @grant               GM_download
// @grant               GM_setValue
// @grant               GM_getValue
// @grant               GM_cookie
// ==/UserScript==

// The following links are valid test links
const urls = [
    'https://file-examples.com/storage/fe444bc7be658b44e9c7550/2017/10/file_example_JPG_2500kB.jpg',
    'https://file-examples.com/storage/fe444bc7be658b44e9c7550/2017/10/file_example_JPG_2500kB.jpg',
    'https://file-examples.com/storage/fe444bc7be658b44e9c7550/2017/10/file_example_JPG_2500kB.jpg',
]
GM_download(urls[0], '01.jpg')
GM_download(urls[1], '02.jpg')
GM_download(urls[2], '03.jpg')
```

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
