### ISSUE TITLE
[BUG] Tampermonkey Interface abnormally zoomed, seemingly using mobile UI on desktop

### ISSUE THREAD

**Issue by domeniczz** [Tampermonkey/tampermonkey#1957]
## Expected Behavior
Zoom correctly

## Actual Behavior

The UI is abnormally large

<img width="450" alt="1" src="https://github.com/Tampermonkey/tampermonkey/assets/42294390/2baff5ba-030b-47a0-8683-424cdb2c0338">

<img width="450" alt="2" src="https://github.com/Tampermonkey/tampermonkey/assets/42294390/de7a1b35-ecb2-4a68-a514-b920378100fe">

## Specifications

- Firefox: 121.0 (64-bit)
- TM: 5.0.0
- OS: Windows 11 23H2, build 22631.2861

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/1819#issuecomment-1646451238 for a workaround.
