### ISSUE TITLE
Documentation regarding '@run-at context-menu' is outdated or misleading

### ISSUE THREAD

**Issue by fonic** [Tampermonkey/tampermonkey#1960]
## Current documentation

The [current documentation](https://www.tampermonkey.net/documentation.php?locale=en#meta:run_at) on `@run-at context-menu` states that this will work on "desktop Chrome-based browsers only".

Assuming "Chrome-based" means "based on Google Chrome", this information seems outdated as I can confirm this also works fine on Firefox 121.0 + Tampermonkey 5.0.0.

## Expected documentation

The documentation should either be clarified (in case "Chrome-based" means something other than "based on Google Chrome") or updated to reflect which browsers currently support `@run-at context-menu` (in case the information currently given is outdated).

## Specifications

- Firefox 121.0
- Tampermonkey 5.0.0
- Ubuntu Linux (x64)

## Script

N/A

**Comment by DanKaplanSES** [comment]
I spent a minute or two trying to submit a PR from this but I got stuck on the first step: I can't find the source of the tampermonkey website. [It _seems_ like it should be https://github.com/Tampermonkey/web-i18n but it's an empty repo](https://github.com/Tampermonkey/web-i18n).

**Comment by krystian3w** [comment]
The add-on code has been closed/private source for over 6 years, so there are no source files for the latest versions for the world.

All we have to do is wait for the author to find free time and show us where the language files are if he doesn't want to learn a dozen or so human languages.

**Comment by fonic** [comment]
> The add-on code has been closed/private source for over 6 years, so there are no source files for the latest versions for the world.

This issue is about a shortcoming of the _documentation_ and @DanKaplanSES was referring to the sources of the _website_, not the add-on.

**Comment by krystian3w** [comment]
But website also can be with public code 6-7 years ago until someone used this to DDoS or other evil ideas (0-day Security vulnerabilities).

**Comment by DanKaplanSES** [comment]
@krystian3w Thank you, that explains why I couldn't find the source code.

The owner is very responsive in my experience, so I'm sure it'll be fixed soon.

**Comment by fonic** [comment]
> But website also can be with public code 6-7 years ago (Wordpress/Drupal/joomla with list of all plugins) until someone used this to DDoS or other evil ideas (0-day Security vulnerabilities) so gone from www after fix all hidden Access to webpage for devils.

Now it makes sense. Thank you.

**Comment by derjanb** [comment]
> it should be https://github.com/Tampermonkey/web-i18n but it's an empty repo

You're right, but I haven't found the time to upload the translation files yet... 

> The documentation should either be clarified...

Fixed. Thanks for reporting...
