### ISSUE TITLE
GM_getTabs not working

### ISSUE THREAD

**Issue by filefi** [Tampermonkey/tampermonkey#1962]
# GM_getTabs not working

## Expected Behavior
return all tabs info as doc says

## Actual Behavior
return empty object {}

## Specifications

- Chromium: 120.0.6099.130 64bit
- TM: 4.19.0
- OS: win10

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.tampermonkey.net/documentation.php
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net
// @grant        GM_getTabs
// @grant        GM.getTabs
// ==/UserScript==

(function() {
    'use strict';

    GM_getTabs((tabs) => {
        for (const [tabId, tab] of Object.entries(tabs)) {
            console.log(`tab ${tabId}`, tab);
        }
    });

    async function run(){
        const tabs = await GM.getTabs();
        console.log(tabs);
    }
    run();

})();
```

**Comment by 7nik** [comment]
It doesn't return _info_ about tabs - it returns all data you bound to tabs using `GM_saveTab`.

It even said in the docs:
> The _"tabs"_ object that is passed to the callback function contains objects, with each object representing the **saved tab information stored by `GM_saveTab`**.
