### ISSUE TITLE
CPU load and memory allocation constantly increasing over time - even with no script active

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [Tampermonkey/tampermonkey#1965]
## Description
Using Tampermonkey for several years now, with no problem at all - IOW: Great stuff, BIG thanks for maintaining!

But: Since about four or five weeks now, Firefox has started to gradually slow down after running for 15 to 20 minutes. After about 30 minutes, pages barely respond to input, fan starts running and task manager shows that at least two cores are at 100 %.  And in about:processes, CPU of "Extensions" is at 50+ % and Memory is 500+ MB.

After some trial and error, it turned out that CPU load goes down immediately when (and *only* then) I disable TM (i. e. switch it off in the list of extensions). I have of course also tried to disable one script after the other, but this has no effect at all. Even if TM is running "completely naked", i. e. without any script at all, CPU load remains high resp. goes up after a Firefox restart within half an hour at the latest.

Questions are:
- Is this behavior common and already known or do I have a local problem?
- Any already known steps to get a grip on this?
- Any way to analyze/debug it?

Any hint will greatly be appreciated.

## Expected Behavior
TM should just use as many resources as are *really* needed (esp. in idle mode).

## Actual Behavior
After a while, TM takes all CPU and memory it can get ... until I deactivate the entire extension.

## Specifications
- Firefox 121.0 (64 bit)
- TM: (5.0.1 as of 2024-01-03)
- OS: (Windows 10 Pro 22H2 19045.3803)

## Script
None at all.

**Comment by derjanb** [comment]
Thanks a lot for you bug report! I read about the issue at addons.mozilla.org, but nobody created a report with details yet.

Do I have to use Firefox (navigate around, open new tabs) or does this happen e.g. with only one page open all the time?
Do you have other extensions installed?
Are scripts running at some of the pages, in case you navigate to web pages until the issue happens?

**Comment by MagpieFourtyTwo** [comment]
Response takes some more time, still collecting reliable data and trying to construct scenarios ...

But what I can say already now: Growth of CPU seems to need at least one "real" tab open:
   - Left FF alone this night, with just FF's starting page open,
     but this morning everything was still running fine (although in fact nothing ran anyway ;) ).
   - Then opened heise.de and left home for work - i. e. FF/TM sat there untouched ...
      but when I looked at it about two hours later, one CPU core was at 50 % again.
      And - as expected - dropped to ~5 % as soon as I disabled/enabled TM in the extensions list.

And all this although TM is running "naked", i. e. just enabled in the list of extensions and in it's own menu, but without any scripts activated plus no page opened, which would trigger any of the installed scripts (if they would be activated).

Possibly interesting observation:
- As long as TM is enabled in the extensions list, but *disabled* in the TM menu, there is no unusual growth in CPU load.
- As soon as I *additionally* enable it in the TM menu, CPU core load starts to increase.
- BUT: core load does *not* go down, after I disable TM in the TM menu only
- TM must be disabled in the extension list, only then CPU core load immediately drops
- after a second or so TM can safely be re-enabled again, and everything is fine ... at least for the next hour ...

BTW; First thought of a possible memory leak, but RAM seems not to be unusually affected by dis/enabling TM:
Disabling it in the extension list decreases RAM by just about 16 MB and enabling it again, increases it by about 6 MB.
Nothing unusual.  And before memory allocation starts to be a problem, the amounts must most probably be way higher.

Hope I can get a grip on some scenarios with even more extensive growth or whatever ... still testing around.
Moreover there was a TM update this morning, will check if this makes a difference (although changelog seems not to contain anything which may be related).

**Comment by derjanb** [comment]
I just read through the Heise Newsticker as well and might have observed that behavior, but only when no ad blocker was installed. Do you use an ad blocker?

**Comment by MagpieFourtyTwo** [comment]
Yep - there is AdBlock Plus installed.  Other AddOns:
- Google Analytics Opt-out
- Kee
- Open Tabs Next to Current
- Screengrab!
- Select After Closing Current
- uBlock Origin
- uMatrix
- YouTube Ad Auto-skipper

... plus a bunch of deactivated stuff I just activate if needed.  But foll. my observation this makes no difference over here, as I already tried one by one - and it turned out that with TM only the problem comes up, i. e. even if AdBlock Plus is deactivated.

There was another question still open, concerning my typical usage scenario;
I usually have about 15 to 20 tabs open and - of course - switch between them.
Most of the time between the most recent 5 or so, keeping the others in background to just look s/th up or to fork a new tab from one of them from time to time (by <Ctr>-clicking a link).
None of these tabs was running a script for sure, cause a) none of their pages would trigger any of my scripts, and b) although TM was running (aka activated), it was completely "naked", with all scripts deactivated anyway.
But in fact it makes no difference at all, how many tabs are open, it just takes longer until the problem builds up:
Whereas with 15-20 tabs it takes about an hour for FF to become inresponsive,
when just having one tab in use, it takes a few hours (see heise example),
although with just one tab it's only one core running at 100 %,
IOW: Although it takes longer with one tab, it will eventually happen anyway.

**Comment by MagpieFourtyTwo** [comment]
Some say ... sometimes just talking about a problem already helps ... ;)
Don't know if the current state is final (hope so) or just intermediate, a whim of the universe,
but after I installed the newest updates for TM and FF (both were offered to me just today),
the error is gone ... just as if it has never been there.
And now, although I have the exact same tabs opened as yesterday (stored them as bookmark group),
and FF running for multiple hours now, max. CPU core load is still at about 10 %, resp. 5 % in total,
which I would consider perfectly fine.  Strange.

Anyway, I'll keep an eye on it tomorrow and come back to this topic tomorrow evening ...

What about your's? Said, you were able to reproduce in combination with ad blocker - is this still the case?

**Comment by derjanb** [comment]
> but after I installed the newest updates for TM and FF (both were offered to me just today),
the error is gone

That sounds good.

> What about your's? Said, you were able to reproduce in combination with ad blocker - is this still the case?

I thought that I have seen it **without** an ad blocker. Hence the question, because it could simply have been caused by ads reloading. When using a ad blocker, I could not reproduce it with 5.0.1. 
You probably run 5.0.0 before the update. Mozillas review took some time and the new version was released on Monday.

> Anyway, I'll keep an eye on it tomorrow and come back to this topic tomorrow evening ...

👍

**Comment by MagpieFourtyTwo** [comment]
Next day, next evening @home, surfing, with lots of news, github, youtube ... FF usage actually similar to the last few weeks, but ... although the load of the busiest core is nearly twice as high as yesterday, I would consider these 15-20 % (10 % in total, with 12 cores) to be absolutely acceptable.

Especially as the load level seems to remain constant resp. stays on this level, and does not keep increasing as it has in the last few weeks.

Don't know why this has changed so dramatically, guess there *was* a (possibly unintentional) fix in one of these two updates, but even w/o knowing I'm of course happy with it and therefore close this issue for now. And I'm keeping my fingers crossed that FF/TM aren't just playing nice out of fear of the pros right now ...  ;)

**Comment by MagpieFourtyTwo** [comment]
However - thanks a lot for reading and cross-checking, really appreciate it! 😎👍🏻

**Comment by sino1641** [comment]
Hi @derjanb ,
I also get a similar issue on the latest Chrome 120 with TamperMonkey 5.0.1, it occurs randomly but scenarios are similar:
1. open a real webpage even with no TM scripts activated on it.
2. Wait some hours. AFK or doing other jobs.
3. Then CPU raised to 100% and no more new webpage can be loaded which seems I am disconnected from the Internet.
  - I also see TM was eating all CPU from Chrome Task Manager.
4. Turns TM off and on again.
5. Everything is back to normal; CPU loads down and re-connected to Internet.

Should I raise a new ticket for more details or how can I get the logs from TM when CPU is 100%? 
Appreciated for the great work!

**Comment by MagpieFourtyTwo** [comment]
Over here everything is still fine ... but who knows ... ;)

**Comment by derjanb** [comment]
@sino1641 

Yes, please open a new ticket. The issue here was Firefox-specific and can't cause the same symptoms at Chrome.

FAQ entry 600 explains how to see Tampermonkey's logs: http://tmnk.net/faq#Q600

Thanks.
