### ISSUE TITLE
Multiple @require insertion order not respected

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Tampermonkey/tampermonkey#197]
```
1.) What Tampermonkey version do you use? (go to 'chrome://extensions/' for
that information)
3.9

2.) What browser version (go to 'chrome://chrome/') and operating system do
you use?
Version 39.0.2171.27 beta-m

3.) Does a Userscript cause the problem? If so, from where can it be
downloaded?
NO

4.) Did this work before? Have you checked the script's bug
tracker/discussion page for that problem?
not sure. Yes, haven't found anything about this behavior.

5.) Are there other Userscripts installed and running?
N/A, some are

6.) Steps to reproduce the problem:
a. create a local script using 
// @require ./lib/jquery-2.1.1.min.js
// @require ./lib/purl.js
b. run it

7.) What is the expected behavior? What went wrong?
Expected: jQuery is inserted before purl (which depends on it).
Actual result: The order is sometimes (?) not respected leading the script to 
crash on purl function calls.

8.) Please provide any additional information below.


```

Original issue reported on code.google.com by `tyf0xj...@gmail.com` on 16 Oct 2014 at 11:51

**Comment by jobevers** [comment]
I think this bug has shown up again.

In a recent install of tampermonkey ( 3.12.58) and chrome (Version 48.0.2564.116 (64-bit)), when trying to require the hasher library, which depends on the js-signals library:

// @require      https://cdnjs.cloudflare.com/ajax/libs/js-signals/1.0.0/js-signals.min.js
// @require      https://cdnjs.cloudflare.com/ajax/libs/hasher/1.2.0/hasher.min.js

I get `TypeError: Cannot read property 'Signal' of undefined` which is the result of the hasher library trying to access the signal object, which is not defined yet.

**Comment by derjanb** [comment]
The problem is that ```JS Signals``` attaches the ```signals``` property to ```this```

    /*
     JS Signals <http://millermedeiros.github.com/js-signals/>
     Released under the MIT license
     Author: Miller Medeiros
     Version: 1.0.0 - Build: 268 (2012/11/29 05:48 PM)
    */
    (function(i) {
        [...]
        var f = e;
        f.Signal = e;
        typeof define === "function" && define.amd ? define(function() {
            return f
        }) : typeof module !== "undefined" && module.exports ? module.exports = f : i.signals = f
    })(this);

while ```Hasher``` reads it from ```window```.

    /*!
     * Hasher <http://github.com/millermedeiros/hasher>
     * @author Miller Medeiros
     * @version 1.2.0 (2013/11/11 03:18 PM)
     * Released under the MIT License
     */
    (function() {
        [...]
        if (typeof define === "function" && define.amd) {
            define(["signals"], a)
        } else {
            if (typeof exports === "object") {
                module.exports = a(require("signals"))
            } else {
                window.hasher = a(window.signals)
            }
        }
    }());

At Tampermonkey scripts with ```@grant none``` the ```this``` scope is different from ```window```. So you either need to restore the full sandbox via

    // @grant GM_log

or ask @millermedeiros to decide between ```window``` and ```this```.
