### ISSUE TITLE
Is there an API for calculating MD5 values?

### ISSUE THREAD

**Issue by Mapaler** [Tampermonkey/tampermonkey#1971]
I have the need to calculate MD5. 
A query of MDN found that [SubtleCrypto](https://developer.mozilla.org/docs/Web/API/SubtleCrypto/digest) does not support MD5

I found that TM natively supports MD5. Is it possible to provide the MD5 API directly without introducing third-party libraries?
![firefox_tLIbEjmT6W](https://github.com/Tampermonkey/tampermonkey/assets/6565860/f0ea1149-b6f0-40e6-ae07-1b306029e0e6)

**Comment by derjanb** [comment]
Unfortunately no. However the MD5 algorithm is quite small, e.g. https://stackoverflow.com/questions/1655769/fastest-md5-implementation-in-javascript#answer-60467595
