### ISSUE TITLE
Save script to disk not working

### ISSUE THREAD

**Issue by suyiv** [Tampermonkey/tampermonkey#1972]
## Details
When save script to disk from the editor (File > Save to disk), an error message “Action failed” appears.

## Expected Behavior
The "Save to disk" should work as expected.

## Actual Behavior
The "Save to disk" stopped working since the end of last year.

## Specifications

- Chromium: 121.0.6167.16 64bit
- TM: 5.0.6192
- OS: Win11

**Comment by cleuton4k** [comment]
I'm facing the same problem

**Comment by Javierdsv** [comment]
Same problem here, but it seems to be only affecting Chrome (Chromium). 
You can Save to disk on Firefox.

**Comment by SunSea88** [comment]
> Same problem here, but it seems to be only affecting Chrome (Chromium). You can Save to disk on Firefox.

Hello,

That's how it's for me too 😥

**Comment by Sampisa** [comment]
Same problem on Chrome 121.0.6167.140, italian version.
![image](https://github.com/Tampermonkey/tampermonkey/assets/169363/da11da4f-88be-49d7-9e7c-85132adb0118)

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
