### ISSUE TITLE
Feature request: GM_fetch

### ISSUE THREAD

**Issue by martixy** [Tampermonkey/tampermonkey#1977]
It would be really nice to have access to all the convenience of the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) through a GM-provided function.

The Request, Response and Headers interfaces in particular are quite convenient, compared to the simple `response`/`responseType` properties.

The primary reason for this feature request is actually **_security_**.

Many websites these days use very strict CSPs (which is a good thing). However these frequently prevent `window.fetch` from working. At which point it becomes a trade between maintaining security (by using `GM_xmlhttpRequest`) or stripping CSPs in favour of convenient access to `window.fetch`.

**Comment by 7nik** [comment]
Neither TM's developer nor VM's one are willing to implement GM_fetch: https://github.com/Tampermonkey/tampermonkey/issues/1278#issuecomment-894608244. There is also [a fetch wrapper](https://github.com/Tampermonkey/tampermonkey/issues/1278#issuecomment-1004568936), though I dunno how good it is.
