### ISSUE TITLE
Github Gist -> raw, does not always allow install of userscript

### ISSUE THREAD

**Issue by f-steff** [Tampermonkey/tampermonkey#1981]
(Please fill out the issue template with your details)

## Expected Behavior
With Tampermonkey running, userscripts hosted as a Github Gist can be installed when accessing the gist page and clicking "raw" on the script. 

## Actual Behavior
I recently published a script as a Github Gist, and it always just shows the raw script when I attempt to install it clicking on raw, so I'm assuming something is wrong on the page so that TM doesn't pick it up.

This is the script: https://gist.github.com/f-steff/ace84434e1ee4e1107bcf0ba8d72ed2b

## Specifications

- Chrome: Version 120.0.6099.216 (Official Build) (arm64)
- TM: 5.0.0
- OS: MacOS 14.1.1 (23B81)

## Script

(Please give an example of the script if applicable.)

**Comment by 7nik** [comment]
The filename (url) must end with `.user.js` but not just `.js`

**Comment by f-steff** [comment]
Ahh.. Critical error on my side! Sorry!!

Thanks you for your assistance!
