### ISSUE TITLE
Cannot display icons using local Font-Awesome Pro Fonts

### ISSUE THREAD

**Issue by YuruiHong** [Tampermonkey/tampermonkey#1983]
## Expected Behavior
When I disable remote fonts (like by setting `gfx.downloadable_fonts.enabled` to false) but have the font locally (I believe it's Font-Awesome Pro since the class names contain `far` and I can comfirm relevant icon names), the icons should be displayed correctly.

## Actual Behavior
Neither the popup window nor the dashboard page displayed the icons correctly.

![image](https://github.com/Tampermonkey/tampermonkey/assets/83064277/adc81dd1-3698-4888-bc2a-e3f9910cfca3)

## Specifications

- Mozilla Firefox 124.0a1
- TM: 5.0.1
- OS: Debian 6.6.13-1

**Comment by derjanb** [comment]
Please report this to Mozilla https://bugzilla.mozilla.org/

If and how Firefox decides to use Fonts is outside of the scope of a browser extension.
