### ISSUE TITLE
Workaround for unsafe-eval not being in CSP Chrome?

### ISSUE THREAD

**Issue by perpil** [Tampermonkey/tampermonkey#1984]
I have a script that uses `eval` by creating a `new Function` with user provided input.  I discovered it recently stopped working in Chrome, but still works in Firefox with TamperMonkey 5.0.1.  Whenever I try to eval something I get this error:

```
Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src github.githubassets.com".
```

This could be for 3 reasons

1. Chrome started enforcing it
2. Github modified their CSP to remove unsafe-eval
3. TamperMonkey changed something

I've tried a few things, but the only thing that worked was to use the `Disable Content-Security-Policy extension` which is less than ideal.

Before I explore running my JavaScript on a server or some other workaround, could this be related to the changes made to support MV3? If so is there any way I can run eval on a page that doesn't have `unsafe-eval` in the CSP.  Do I need to do some sort of weird iframe trick like this? https://medium.com/geekculture/how-to-use-eval-in-a-v3-chrome-extension-f21ca8c2160c

## Expected Behavior

It is possible to execute a function with user provided content

## Actual Behavior

```
Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src github.githubassets.com".
```

## Specifications

- Chromium: 121.0.6167.85
- TM: (i.e. 5.0.1)
- OS: (i.e. MacOS 14.2.1)

## Script

```js
// ==UserScript==
// @name         Github CSP test
// @namespace    http://tampermonkey.net/
// @version      1.00
// @description  Test eval on github
// @sandbox      JavaScript
// @author       You
// @match        https://github.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=github.com
// ==/UserScript==

(function() {
    new Function('console.log("hello world")')();
})();
```

Go to any github page and look in the console to see the output.

**Comment by perpil** [comment]
I had tried setting "Modify existing content security policy (CSP) headers" to "Yes", but didn't realize there was a "Save" button.  Setting it to "Yes" and clicking "Save" fixed the issue.
<img width="797" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/97474956/930bc69f-0af2-40ec-bae6-b7b73d3b423f">

**Comment by derjanb** [comment]
Another options would be `GM_addElement` -> https://github.com/Tampermonkey/tampermonkey/issues/881#issuecomment-639705679

**Comment by perpil** [comment]
Thanks! I'll give that a shot.  It seems like a much better solution than having my users change TamperMonkey configuration.

**Comment by muzso** [comment]
FYI

Meanwhile the Tampermonkey setting (for the workaround) changed a bit.

In TM v5.4.0 its name is still "Modify existing content security policy (CSP) headers", but the choices are now:
- Auto
- Remove entirely (possibly insecure)
- No

"Remove entirely" works as a workaround.

P.S.: for this setting to become visible, you've to change the "Config mode" to "Advanced" (at the top of the TM settings page).
