### ISSUE TITLE
Zip export no longer working

### ISSUE THREAD

**Issue by webvia** [Tampermonkey/tampermonkey#1985]
## Expected Behavior
- When the zip export button is pressed, the save file dialog should appear.

## Actual Behavior
- The save file dialog does not appear. (Tested in the Brave browser, with popups, redirects and automatic downloads allowed.)

## Specifications
- Brave desktop 1.62.153
- Chromium 121.0.6167.85
- Tampermonkey 5.0.1
- Windows 11 Home version 23H2 build 22631.3085

**Comment by derjanb** [comment]
Related: #1972

**Comment by derjanb** [comment]
Should be fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
