### ISSUE TITLE
No scripts running on youtube.com if ijected method is set to instant

### ISSUE THREAD

**Issue by ShiroiBara** [Tampermonkey/tampermonkey#1991]
If tampermonkey mode of injections set to instant it stops running any scripts on youtube.com. Clearing youtube cookies and refreshing page once helps, but if refresh page 2nd time no scripts running again and you need clear cookies once more.

## Specifications

- Firefox: 122.0.1
- TM: 5.0.1
- OS: Arch Linux 6.6.16-1-lts

**Comment by derjanb** [comment]
This is working fine here. Do you see errors at the page's console?

BTW: "Content Script API" set to "UserScripts API Dynamic" is a better alternative to "Instant" "Inject Mode".
