### ISSUE TITLE
能否增加后台脚本编写功能

### ISSUE THREAD

**Issue by GuoChen-thlg** [Tampermonkey/tampermonkey#2000]
(Please fill out the issue template with your details)

## Expected Behavior
可以编写后台脚本 设置定时任务处理一些事情

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by 7nik** [comment]
No. But you can make a script that runs on all sites, stores a list of tasks and does setTimeout for the nearest task.
