### ISSUE TITLE
GM_download should take Content-Disposition:filename into consideration

### ISSUE THREAD

**Issue by willhancn** [Tampermonkey/tampermonkey#2001]
## Expected Behavior

When `GM_download` is called with the `name` parameter empty or is null, it should:
1. Read `filename*` or `filename` from HTTP Response header `Content-Disposition` ;
2. If it is not obtained, read the last segment from the URL path as the file name;

Then compare with the whitelist to decide whether to allow downloading (if this is not possible in native mode, then please at least add such capability in browser API mode).

### 1. Native mode
- When `GM_download` is called with the `name` parameter is `null`,  found error: 'not_whitelisted';
- When `GM_download` is called with the `name` parameter is `""`, found error: 'not_whitelisted';

### 2. Browser API mode
- When `GM_download` is called with the `name` parameter is `null`,  found error: 'not_whitelisted';
- When `GM_download` is called with the `name` parameter is `""`, found error: 'not_whitelisted';

### 3. Native mode and with `//` in whitelist
- When `GM_download` is called with the `name` parameter is `null`, file name = `File.download`
- When `GM_download` is called with the `name` parameter is `""`, file name = `File.download`

### 4. Browser API mode and with `//` in whitelist
- When `GM_download` is called with the `name` parameter is `null`, file name = `File.svg`
- When `GM_download` is called with the `name` parameter is `""`, file name = `File.svg`

## Specifications

- Google Chrome: 122.0.6261.95
- TM: 5.0.1
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         Test for GM_download
// @namespace    http://tampermonkey.net/
// @version      2024-03-11
// @description  try to take over the world!
// @author       You
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net
// @match        https://www.google.com.hk/*
// @match        https://www.google.com/*
// @grant        GM_download
// ==/UserScript==

(function() {
    'use strict';

    document.querySelector('[alt="Google"]').addEventListener('click', function(){
        console.log("a click on Google icon.");
        GM_download({
            "url": "https://www.w3.org/assets/logos/w3c/w3c-no-bars.svg",
            "name": null,
            "saveAs": true,
            "onload": function(e) {
                console.log("onload: %o", e);
            },
            "onerror": function(e) {
                console.log("onerror: %o", e);
            },
            "onprogress": function(e) {
                console.log("onprogress: %o", e);
            },
            "ontimeout ": function(e) {
                console.log("ontimeout : %o", e);
            }
        });
    });
})();
```

My needs are based on the following reasons:
1.  I cannot get `Content-Disposition` : `filename` in advance. In some scenarios, this file name is valuable information, and I don’t want to lose it;
2. It is more convenient to leave `name` parameter empty, rather than manually write code to read path, parse the file name, and then assign it to the `name` parameter.

BTW, The official documentation doesn't describe enough what the different options of `downloadMode` actually do, and it took me some time to figure out; I hope some more text can be added in this regard. Thanks.

**Comment by Owyn** [comment]
not yet in 5.1,
![изображение](https://github.com/Tampermonkey/tampermonkey/assets/1309656/bcdbeca2-248f-462e-a2fc-d456904d87bc)

I can confirm that having to specify a filename can be a big problem - some filenames are just hashes without any extensions, e.g.: 
![изображение](https://github.com/Tampermonkey/tampermonkey/assets/1309656/34a3e223-42d8-47fa-b1a4-df116717b232)
but when you save them normally they get readable good filenames - but currently you can't have this with `GM_Download`

**Comment by derjanb** [comment]
Should be fixed at 5.1.6194 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by Owyn** [comment]
Tested in chrome: 
With default download mode:
- it gets the server filename and downloads right away, even thought I have `saveAs` enabled and it should show me the save as dialogue

with native browser api download mode:
- it downloads and shows save as dialogue fine if I specify the save-filename but **errors** if there is no filename specified (where it should use the filename from the server):
![image](https://github.com/Tampermonkey/tampermonkey/assets/1309656/43bc273d-0331-4052-a540-62e726ad8da3)

hopefully you can make it work for "save as" because that's what I'm using...

**Comment by 7nik** [comment]
from docs:
> saveAs: [...] This option works in browser API mode only.

AFAIK, it's a limitation by the Webexention API.

**Comment by willhancn** [comment]
Works well for me, good job!

**Comment by willhancn** [comment]
Works well for me, great job!

**Comment by derjanb** [comment]
@Owyn 

>  but errors if there is no filename specified (where it should use the filename from the server):

This is working fine here in browser api download mode using the example script from the first post. Can you please add details to make the example fail?

**Comment by Owyn** [comment]
> @Owyn
> 
> > but errors if there is no filename specified (where it should use the filename from the server):
> 
> This is working fine here in browser api download mode using the example script from the first post. Can you please add details to make the example fail?

Looks like it's the browser APi mode in chrome which is broken, just errors every time whether the filename is null or not
![image](https://github.com/Tampermonkey/tampermonkey/assets/1309656/71f428fe-8a22-4cc5-885a-febe69710a17)

but If I set download mode to `default` - it works fine and even shows SaveAs dialogue (in Chrome)

so just set download mode in Chrome to browser APi for it to fail

btw, about filenames:

https://i123.fastpic.org/big/2024/0501/c8/5a84c2ae74672fe5dccbfc2dee218cc8.jpg ( the main picture )

with filename null the filename it suggests is: `5a4822f4-6ac4-48b5-abac-2ed22f4431b6.jpg` for some reason, but If I just right click the image and choose "Save image as" via browser - it gives me `5a84c2ae74672fe5dccbfc2dee218cc8.jpg` filename which is the one servers sends I suppose ( the correct one ) ? so where does ``5a4822f4-6ac4-48b5-abac-2ed22f4431b6.jpg`` come from? (for another website it works fine)

testing with TM 5.1.6194 + chrome 122.0.6261.112

**Comment by Owyn** [comment]
@derjanb derjanb

Just tested it in Firefox and the new stable TM

`default` download mode works almost fine, but some hosts (e.g. fastpic example above) result in wrong filenames unlike `Native` download mode which gets their filenames right (and all others too),
and there's also `browser api` mode which does not use server filenames at all here (by design?)

**Comment by Owyn** [comment]
@derjanb 
also about this implementation - now when I do GM_download - it now has at least a few second delay or even like 10 seconds for the save_as window to pop_up - even **if I don't use original** filename but set up my own - could you perhaps make it fetch original filename only if `name` is `null` but not otherwise?
