### ISSUE TITLE
GM_registerMenuCommand not trigger click callback in firefox browser

### ISSUE THREAD

**Issue by WhiteSevs** [Tampermonkey/tampermonkey#2005]
## Expected Behavior

期望修复注册顺序和点击回调无效的问题

## Actual Behavior

注册菜单 => `test1`->`test2`->`test3`
  ↓
卸载菜单
↓
注册菜单 => `test2`->`test3`->`test1`

问题：在最后注册完菜单完成后，菜单顺序不同，且菜单`test2`和`test3`的点击事件不触发，只有`test1`的点击事件触发
该测试在`Edge`+`TamperMonkey BETA 5.1.6193`下又是正常的

## Specifications

- Firefox: 123.0.1
- TM: 5.1.6193
- OS: Win 10

## Script

```js
// ==UserScript==
// @name            Debug GM_registerMenuCommand
// @version         0.1
// @author          WhiteSevs
// @match           *://*/*
// @run-at          document-start
// @grant           GM_registerMenuCommand
// @grant           GM_unregisterMenuCommand
// ==/UserScript==

(function () {
  const menuIdMap = {};
  const menuList = [
    {
      text: "test1",
      callback(event) {
        console.log(`test1 click`, event);
      },
    },
    {
      text: "test2",
      callback(event) {
        console.log(`test2 click`, event);
      },
    },
    {
      text: "test3",
      callback(event) {
        console.log(`test3 click`, event);
      },
    },
  ];
  function register() {
    menuList.forEach((item) => {
      let menuId = GM_registerMenuCommand(item.text, item.callback);
      menuIdMap[menuId] = item;
    });
  }
  function unRegister() {
    for (const key in menuIdMap) {
      GM_unregisterMenuCommand(key);
    }
  }
  register();
  unRegister();
  register();
})();

```

**Comment by derjanb** [comment]
Should be fixed at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
