### ISSUE TITLE
[BUG] Scripts randomly stops working due to deprecation of 'DOMSubtreeModified' mutation event

### ISSUE THREAD

**Issue by KohGeek** [Tampermonkey/tampermonkey#2007]
The issue was first reported here:
https://github.com/KohGeek/SortYoutubePlaylistByDuration/issues/3

It's currently unknown whether Chrome Canary or Tampermonkey is at fault here, but I will describe the steps to reproduce as clear as I can.

## Steps To Reproduce (Inconsistent)

> [!NOTE]
> Subsequent testing with a complete clean Chrome Canary install cannot reproduce this.
0. Ensure extension developer mode and TM is enabled
1. Download any userscripts with prior versions
2. Download the previous version of the userscript and set it to a position before the latest script
3. Disable the old script
4. Load the webpage, the extension should still behave as expected
5. Restart the browser
6. Load the webpage, the extension will now fail to load userscripts

Step one and step two maybe simplified down to scripts targeting the same page - but this is unknown.

### Possible prerequisite
- You may need to have upgraded Chrome from a previous version, with leftover browsing data.
- A third disabled script targeting the same site may need to put behind the active script, basically sandwiching it.
- You may need to enable Tamperscript before developer mode.

## Expected Behavior
The disabled script remains disabled, and the enabled script will run.

## Actual Behavior
Tampermonkey reports no script to be found - in fact, it reports no script for all other webpages. 

Once TM enters this state, it may seem completely impossible to fix it. A list of things that have been tried:
- Reenabling the scripts
- Deleting all scripts and reinstalling them
- Factory reset TM
- Reinstall TM
- Wipe all browsing data from Chrome
- Factory reset Chrome
- Downgrading TM
- Switching to TM Beta

None of this will bring TM back into a functional state.

## Temporary resolution
- Switch settings to Advanced Mode
- Switch the Inject mode from Default to Instant

## Permanent resolution
- Reinstall Chrome and delete all previous browsing data

## Specifications

- Chromium: Canary Version 124.0.6367.0 amd64, extension developer mode enabled
- TM: 5.1.0
- OS: Windows 11 22621.2715

## Script

New version: https://github.com/KohGeek/SortYoutubePlaylistByDuration
Old version: https://gist.github.com/KohGeek/65ad9e0118ee5f5ee484676731bcd092/da58d22823f2c170c08346ec1c3dda238e3ca49c

**Comment by KohGeek** [comment]
Tested:

### Chromium 122.0.6261.129, TM 5.0.0, Windows 11 22631.3296 
Cannot reproduce

### Chromium 123.0.6312.59, TM 5.1.0, Windows 11 22631.3296
Partially reproduced

On first load, the script loads, but TM reports no script:
![image](https://github.com/Tampermonkey/tampermonkey/assets/6839340/f3ac6c97-66ba-4f7f-9761-014ce80d17d9)

Reloading works subsequently.

**Comment by epoweripione** [comment]
May be cause by deprecated `MutationEvent`:
> [Deprecation] Listener added for a 'DOMSubtreeModified' mutation event. This event type is deprecated, and will be removed from this browser very soon. Usage of this event listener will cause performance issues today, and represents a large risk of future site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information.

Temporary solution:
Goto `[Chrome Experiments](chrome://flags/)`, find & enable `Enable (deprecated) synchronous mutation events` , restart chrome, all user scripts come back again.

But I think this is not a long-term solution and needs to be improved in the future.

**Comment by jespertheend** [comment]
Can confirm, I'm seeing the `MutationEvent is not defined` error even when no scripts are enabled

**Comment by epoweripione** [comment]
According to the [Feature: Deprecate Mutation Events](https://chromestatus.com/feature/5083947249172480) & [Mutation events will be removed from Chrome](https://developer.chrome.com/blog/mutation-events-deprecation): `Mutation event` support will be disabled by default starting in **Chrome 127**, around July 30, 2024.

It may be in test now and only ship to a small set of users.

**Comment by srsman** [comment]
I encountered an error on Chrome 124.0.6356.6 dev version, then backed up, and restored the backup on canary (125.0.6370.0), encountering the same issue. After enabling 'Enable (deprecated) synchronous mutation events,' both Chrome 124.0.6356.6 dev and canary (125.0.6370.0) automatically resumed normal operation.

**Comment by Vstory** [comment]
Same problem, after updating Chrome Dev to 125.0.6368.2, all scripts become invalid.

**Comment by derjanb** [comment]
Thanks @epoweripione for the workaround.

I'm posting it here again to make it more prominent:

Goto `Chrome Experiments (chrome://flags/)`, find & enable `Enable (deprecated) synchronous mutation events`, restart chrome (Relaunch at the bottom right)

**Comment by Vstory** [comment]
> Should be fixed at 5.1.6194 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)
> 
> Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
> 
> For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

When will it be pushed to the official version?
