### ISSUE TITLE
notifications dont work anymore

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#2008]
(Please fill out the issue template with your details)

## Expected Behavior
GM.notification({ text: "Click me." });
or 
GM_notification({
  text: "This is the notification message.",
  title: "Notification Title",
  url: 'https:/example.com/',
  onclick: (event) => {
    // The userscript is still running, so don't open example.com
    event.preventDefault();
    // Display an alert message instead
    alert('I was clicked!')
  }
});

triggers a notification 

## Actual Behavior
it doesnt 

## Specifications

- Chromium: 122.0.6261.129
- TM:v5.1.6193
- OS: (i.e. MacOS 10.13.4)

## Script

GM.notification({ text: "Click me." });
or 
GM_notification({
  text: "This is the notification message.",
  title: "Notification Title",
  url: 'https:/example.com/',
  onclick: (event) => {
    // The userscript is still running, so don't open example.com
    event.preventDefault();
    // Display an alert message instead
    alert('I was clicked!')
  }
});

**Comment by derjanb** [comment]
You're using MacOS? If so can this have caused the issue? 

https://github.com/Tampermonkey/tampermonkey/issues/1798#issuecomment-1941102326

**Comment by jonnytest1** [comment]
ok it seems to be a more severe problem - when i just do `new Notification("test")` in terminal i also dont get a notificaiton
