### ISSUE TITLE
An Internal Error Occurred

### ISSUE THREAD

**Issue by hutber** [Tampermonkey/tampermonkey#2010]
(Please fill out the issue template with your details)

## Expected Behavior
I can click on tampermonkey and it will open the dialog box

## Actual Behavior
I click the extension button on any site and the following happens:
![image](https://github.com/Tampermonkey/tampermonkey/assets/1344898/e9dc8b2d-1d62-4f51-a776-2ee74983462c)
![image](https://github.com/Tampermonkey/tampermonkey/assets/1344898/4af31dca-0055-470c-982d-04aa470c5776)

## Specifications
Linux Version 122.0.6261.111 (Official Build) (64-bit)
Tampermonkey 5.0.1

## Script
Accessing the dialog and or the dashboard

**Comment by hutber** [comment]
I have removed the the old context from .config and repaired and its working again, however how can I restore the scripts I had? I took a BK from /home/hutber/.config/google-chrome/Default/Extensions/tamperMonkey/5.0.1_1 before removing it.

**Comment by derjanb** [comment]
Please check [this gist](https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0) for how to extract your scripts from a profile folder.
