### ISSUE TITLE
Uncaught ReferenceError: MutationEvent is not defined

### ISSUE THREAD

**Issue by quisido** [Tampermonkey/tampermonkey#2011]
## Expected Behavior

Not to see the error `MutationEvent is not defined` in my browser console

## Actual Behavior

`Uncaught ReferenceError: MutationEvent is not defined`

in `content.js`

```
                M_i: MutationEvent.prototype.initMutationEvent,
                M_pA: MutationEvent.prototype.ADDITION,
                M_pAT: MutationEvent.AT_TARGET,
```

## Specifications

Irrelevant. [See MDN](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent):

```
Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible
```

## Script

N/A

**Comment by geliegeliegelie** [comment]
I have also encountered such problems on multiple devices

**Comment by derjanb** [comment]
Temporary workaround:

Goto `Chrome Experiments (chrome://flags/)`, find & enable `Enable (deprecated) synchronous mutation events`, restart chrome (Relaunch at the bottom right)

**Comment by TenviLi** [comment]
![image](https://github.com/Tampermonkey/tampermonkey/assets/30214981/707f6088-1bf2-4f8b-9469-f9a03d2cba31)

**Comment by bekoeppel** [comment]
Thank you!

**Comment by rodrigograca31** [comment]
All scripts stopped working as of today on Chrome Version 125.0.6420.3 (Official Build) dev (64-bit)


due to this problem/bug

**Comment by Pikamander2** [comment]
@derjanb - This doesn't appear to be resolved. My scripts stopped working today and I had to enable the chrome://flags/#mutation-events flag for them to start working again. Is there a permanent fix planned?
