### ISSUE TITLE
Select all SPAN elements which contain a "foobar" property? If possible with jQuery

### ISSUE THREAD

**Issue by pstein** [Tampermonkey/tampermonkey#2014]
How can I select (from Tampermonkey script) all SPAN elements in current webpage which contain a property "foobar"?

The assigned value is unimportant.

So elements like the following should be matched:

`<span aaa="bbb" foobar="23452345" .....>...</span>`

I tried:

`$('span[foobar^=""]').remove();`

but it didn't work.

And

`$('span').attr('foobar').remove(); `

didn't work either.

**Comment by 7nik** [comment]
To use `$` (jQuery), you need to add it to the userscript:
```js
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
```
or use [document.querySelectorAll()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll).

**Comment by pstein** [comment]
Yes, I already added:

// @require         http://code.jquery.com/jquery-latest.js

So this is not the problem/solution

**Comment by 7nik** [comment]
>  \* jQuery JavaScript Library v1.11.1
>  \* Date: 2014-05-01T17:42Z

It's more ancient than mammoths.

**Comment by 7nik** [comment]
> // @require http://code.jquery.com/jquery-latest.js

It seems to work. Can you provide an entire minimal userscript where it doesn't work?

**Comment by pstein** [comment]
Hmm, interesting.

However your suggested cloudflare URL  contains a version number ("v3.2.1")
Is there a version number independent cloudflare URL which redirects to always the latest jQuery library (similar to my URL)?

**Comment by 7nik** [comment]
here you can choose a link with a loose version https://www.jsdelivr.com/package/npm/jquery

but it seems something is wrong with your environment and jQuery cannot define `$`

**Comment by derjanb** [comment]
@7nik thanks for helping out! The issues doesn't seem to be a Tampermonkey issue.
