### ISSUE TITLE
TamperMonkey does not activate scripts on stable release (Chrome Canary)

### ISSUE THREAD

**Issue by mm12** [Tampermonkey/tampermonkey#2020]
(Please fill out the issue template with your details)

## Expected Behavior
When visiting a site, userscripts should run. 

## Actual Behavior
The userscripts do not run, and are not shown in tampermonkey ('no scripts running') 

Note that in 5.1.6194 beta, the same settings work (imported), however I cannot find information about this bug on GitHub or the chnagelog. 

## Specifications

- Chrome Canary  125.0.6384.0
- TM: 5.1.0
- OS: Windows 11 23H2 

## Script

https://github.com/Sasquire/Idems-Sourcing-Suite 1.00053 is an example of a script this occurs on, however it has happened with all scripts i have tested.

**Comment by derjanb** [comment]
Please try this: https://github.com/Tampermonkey/tampermonkey/issues/2011#issuecomment-2016887028
