### ISSUE TITLE
[feat] add "Dont Check for updates" button to ask.html

### ISSUE THREAD

**Issue by Outlying3720** [Tampermonkey/tampermonkey#2029]
Hi!
Could you add a "Dont Check for updates" button to ask.html(which appear when update push to us), that will be much more convenience than open dashboard to check.

Thansk!

**Comment by derjanb** [comment]
Should be fixed at 5.3.6209 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
