### ISSUE TITLE
Tampermonkey Script Icons grays out and cannot be used

### ISSUE THREAD

**Issue by rosee77** [Tampermonkey/tampermonkey#2031]
(请在问题模板中填写您的详细信息）

##预期行为

## 实际行为
Hello! Today, it was discovered that the tampered monkey script icon has turned gray and cannot be used.
![image](https://github.com/Tampermonkey/tampermonkey/assets/145031867/7a766863-e657-4284-83e9-4ddc15961439)
I clicked on it and couldn't enter it in circles. All the plugins inside couldn't be used.
![image](https://github.com/Tampermonkey/tampermonkey/assets/145031867/46ee42a0-c4fc-4efb-a6f5-965e6d2b6bca)
The computer and browser have been restarted, but the above situation still persists. Please assist in handling it. Thank you!

## 规格
Tampermonkey version: 5.1.0
OS: Windows 10
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

##脚本

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by kid20210528** [comment]
同问。。。

**Comment by derjanb** [comment]
Can you please check the background page for errors? -> http://tmnk.net/faq#Q600
Thanks.
