### ISSUE TITLE
Hides out the subscription bar in the homescreen

### ISSUE THREAD

**Issue by ashish2508** [Tampermonkey/tampermonkey#2035]
(Please fill out the issue template with your details)

## Expected Behavior

Uploading Recording 2024-04-18 101016.mp4…

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please add more information...

**Comment by ashish2508** [comment]
Sometimes when the script is working and I go back to the home screen , the
bar where the subscribed channels are listed just vanishes and then i
am unable to access ,
sorry to say i changed my script long time ago so i won't be able to
provide any video for now but if i recall correctly i already provided the
video of my glitch in the previous complaint
