### ISSUE TITLE
Tam mentions Q204 on Firefox

### ISSUE THREAD

**Issue by Gurkenglas** [Tampermonkey/tampermonkey#2037]
Tam asked "Do you want to know how to allow Tampermonkey access to local file URIs?".

## Expected Behavior
Tam should check whether it would only be rubbing salt in an old wound.

## Actual Behavior
Tam brings my hopes up, and then I get to read "File access for Tampermonkey is only available at Chrome and derivates.".

**Comment by derjanb** [comment]
Will be fixed at 5.2.6196 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review) which is currently in review.

Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
