### ISSUE TITLE
After update Firefox and Tampermonkey addon all scripts GONE

### ISSUE THREAD

**Issue by hellresistor** [Tampermonkey/tampermonkey#2038]
## Expected Behavior
All scripts gone after tampermonkey update.

## Actual Behavior
Have zero scripts
How Can I get that back?

## Specifications
- Firefox: (125.0.2 (64-bit))
- TM: (v5.1.0)
- OS: (Win 10 X64 )

**Comment by derjanb** [comment]
I'm sorry. Duplicate of #1954

> All scripts gone after tampermonkey update.

Do you have a backup of Firefox's profile folder?
