### ISSUE TITLE
Redirect Reddit to new.reddit.com infinite loop?

### ISSUE THREAD

**Issue by prisoneer** [Tampermonkey/tampermonkey#2041]
(Please fill out the issue template with your details)

## Expected Behavior

https://www.reddit.com/r/OldElectronicMusic to get redirected to https://new.reddit.com/r/OldElectronicMusic

## Actual Behavior

Infinite loop

## Specifications

- Chrome Dev: (126.0.6439.0)
- TM: (5.1.0)
- OS: (Windows 10 22H2, OS build 19045.4291)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Redirect Reddit URLs
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Redirect Reddit URLs from www to new subdomain
// @author       Ivo
// @match        https://www.reddit.com/r/OldElectronicMusic/*
// @grant        none
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    // Get the current URL
    var currentUrl = window.location.href;

    // Replace "www" with "new" in the URL
    var newUrl = currentUrl.replace("www.reddit.com", "new.reddit.com");

    // Redirect to the new URL
    window.location.replace(newUrl);
})();
```
This is the link in question:
https://www.reddit.com/r/OldElectronicMusic/comments/1cbsq0s/dead_or_alive_hooked_on_love_1987/

Screencast: https://streamable.com/3eysyp

**Comment by 7nik** [comment]
Can it be that Reddit just redirects you back to www on that page? Have you checked what's going on in the network tab in devtools?

**Comment by prisoneer** [comment]
There was an issue with the cookies. I reinstalled Chrome and everything is back to normal.
