### ISSUE TITLE
`GM_xmlhttpRequest`: `redirect: "manual"` does not work

### ISSUE THREAD

**Issue by PRO-2684** [Tampermonkey/tampermonkey#2042]
## Expected Behavior
Setting `redirect` to `manual` would stop `GM_xmlhttpRequest` from following redirects.

## Actual Behavior
`GM_xmlhttpRequest` still follows redirects.

## Specifications

- Chromium: Edge 124.0.2478.67 & Chrome 124.0.6367.63
- TM: 5.1.0
- OS: Windows11 23H2 22631.3447

## Script

```js
// ==UserScript==
// @name         Redirect Manual Demo
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       PRO
// @match        https://www.tampermonkey.net/*
// @icon         http://tampermonkey.net/favicon.ico
// @grant        GM_xmlhttpRequest
// @connect      b23.tv
// @connect      www.bilibili.com
// @license      gpl-3.0
// ==/UserScript==

(function() {
    'use strict';
    const initUrl = "https://b23.tv/SI6OEcv";
    GM_xmlhttpRequest({
        url: initUrl,
        method: "HEAD",
        onload: (r) => {
            console.log(r.finalUrl);
            if (r.finalUrl !== initUrl) console.log('`redirect: "manual"` does not work');
        },
        redirect: "manual"
    });
})();
```

## Other
I noticed that `GM.xmlHttpRequest` has a capitalized `H`, while `GM_xmlhttpRequest` has `h`. Is this intended for some reason?

**Comment by derjanb** [comment]
> background.js:725 mh: xhr.details.redirect is available in beta versions only

There is a warning logged at the console.

> Is this intended for some reason?

Yes, this was defined by Greasemonkey this way years ago.
https://wiki.greasespot.net/GM.xmlHttpRequest

**Comment by PRO-2684** [comment]
> background.js:725 mh: xhr.details.redirect is available in beta versions only

So it will be available on the next stable release? Can't wait to see it in action 👍
