### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by touzilaoda** [Tampermonkey/tampermonkey#2047]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by cyfung1031** [comment]
<img width="686" alt="Screen Shot 2024-05-07 at 0 33 24" src="https://github.com/Tampermonkey/tampermonkey/assets/44498510/f0331908-64e0-46cc-9b6a-dd48577852cb">

**Comment by derjanb** [comment]
Well then there is nothing I can do...
