### ISSUE TITLE
Script editor for android is cut off and only shows a couple lines at a time

### ISSUE THREAD

**Issue by rthfhgyhy567** [Tampermonkey/tampermonkey#2048]
Script Editor is Cut off and not displaying as the full height of the screen.  Look at all this wasted space.  It makes it impossible to edit scripts if you can only see 6 lines at a time.

## Specifications

- Tamper Monkey for Kiwi Browser V 5.1.1
- Kiwi Browser V124.0.6327.4

Device: Samsung S23 Ultra SM-S9180
Android 13

![image](https://github.com/Tampermonkey/tampermonkey/assets/104237805/fe51ac5c-bb72-43e4-9318-a04b6ae4d1bc)

**Comment by derjanb** [comment]
Should be fixed at 5.3.6206 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by rthfhgyhy567** [comment]
That worked!  Now can you add another option to disable the "whats new" new tab after it updates?  I generally can't stand any software that has to grab my attention to notify about updates being installed.  I like the "Apple approach" where all that is done in the background without my knowledge.  Thank you for fixing this!

![image](https://github.com/user-attachments/assets/0b31858e-2c93-4dd7-8be0-49d823d03360)

**Comment by derjanb** [comment]
@rthfhgyhy567 Kiwi can't run newer Tampermonkey versions. Please follow up on their bug report: https://github.com/kiwibrowser/src.next/issues/1135

**Comment by tathastu871** [comment]
A simple solution to both issues cut off and auto zoom in in kiwi browser
https://github.com/Tampermonkey/tampermonkey/issues/2190


Solution: Edit The Html
document.querySelector('#table_bWFpbl90YWJsZWRldGFpbHNuZXd1c2Vyc2NyaXB0X3VuZGVmaW5lZA').style.minHeight = '1000px'



Currently height is responsive based on 100% of its container when we try to input text keyboard appears and its containers shrinks


Previously:



https://github.com/user-attachments/assets/80f26683-745b-41e0-ac8f-92e0c87cca25



After Solution


https://github.com/user-attachments/assets/8079dc61-f7dc-4c7a-979c-8bb25c2ab286

**Comment by tathastu871** [comment]
A simple solution to both issues cut off and auto zoom in in kiwi browser
https://github.com/Tampermonkey/tampermonkey/issues/2190


Solution: Edit The Html
document.querySelector('#table_bWFpbl90YWJsZWRldGFpbHNuZXd1c2Vyc2NyaXB0X3VuZGVmaW5lZA').style.minHeight = '1000px'



Currently height is responsive based on 100% of its container when we try to input text keyboard appears and its containers shrinks


Previously:



https://github.com/user-attachments/assets/80f26683-745b-41e0-ac8f-92e0c87cca25



After Solution


https://github.com/user-attachments/assets/8079dc61-f7dc-4c7a-979c-8bb25c2ab286


    overall problem is in code mirror css

**Comment by rthfhgyhy567** [comment]
Can you repeat how to do the fix as if I am a dummy that doesn't know how to code?  I know it sounds ironic for a tamper monkey user but I just use AI to write scripts.

**Comment by tathastu871** [comment]
its a manyal fix you have to run it manually in devtools or as bookmarklet. 
wait till dev themselves add this solution to tampermonkey code css

**Comment by tathastu871** [comment]
> Can you repeat how to do the fix as if I am a dummy that doesn't know how to code?  I know it sounds ironic for a tamper monkey user but I just use AI to write scripts.  

DOWNLOAD TAMPERMONKEY LEGACY SOURCECODE 
OPEN style.css in editor
search .tr_content and edit css property height from 100% to 1000px'

**Comment by tathastu871** [comment]
> Can you repeat how to do the fix as if I am a dummy that doesn't know how to code?  I know it sounds ironic for a tamper monkey user but I just use AI to write scripts.  

![Screenshot_20241006-125848_Kiwi Browser.jpg](https://github.com/user-attachments/assets/8e35adb9-661c-4966-bb12-87355585dac0)



NEW EASY SOLUTION TO THIS PROBLEM

1)go to tampermonkey setting
2)chage config mode to advance
3) In custom css add
.tr_content {
height: 1000px;
}

4) SAVE

SEE IMAGE ABOVE
@derjanb

**Comment by tathastu871** [comment]
Really customizability of this exension is damn good
worth donation

**Comment by tathastu871** [comment]
Some glithes with this solution when we try to type in editor quickly text is not added we have to type slow

**Comment by derjanb** [comment]
> Some glithes with this solution

And there are more... Therefore my solution was to fix it via `viewport`. 

Unfortunately Kiwi users don't benefit from the latest fix because Kiwi updated its version number to a version that should support MV3's `userScripts` API, [but it does not](https://github.com/kiwibrowser/src.next/issues/1135) and newer Tampermonkey versions (5.2+) are not working anymore.

The workaround is to use Tampermonkey 5.1.1, but without the fix. 🤷

If you're searching for another (better maintained?!) mobile Chrome based browser that supports extensions (MV2 and MV3 atm): https://play.google.com/store/apps/details?id=com.microsoft.emmx.canary
The stable version [will get more extension support soon](https://www.userscript.zone/howto?env=edge_android) as well.

**Comment by tathastu871** [comment]
viewport related settings but even if we enable desktop version on android browser
 what about zoom in problem as shown in video as soon as we click to enter text it zooms in to cursor,  whats the root behind this problem ??


till then we can use script sync feature over webdav so we can use native os editor ??

Also to notify webdav import backup is not working struck in please wait. only import via file works
