### ISSUE TITLE
Userscripts without no include and no match are not ran

### ISSUE THREAD

**Issue by jesus2099** [Tampermonkey/tampermonkey#2059]
Take the example script with no match and no include.

## Expected Behavior

The script should run (like with Greasemonkey and Violentmonkey).

## Actual Behavior

Userscripts with no include and no match don't run at all in Violentmonkey.

## Specifications

I tested Vivaldi (latest version) and Firefox with latest version of Tampermonkey, on Windows.
Someone tested on Linux with same result.

Maybe it's on purpose? Like a security or something?

## Script

```js
// ==UserScript==
// @name MyName
// @Version 1.0
// @description shows a popup
// @grant none
// ==/UserScript==
alert("boo");
```

You have to add `// @match *://*` and then only the script will run with Tampermonkey.

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/1766#issuecomment-1516740141

**Comment by jesus2099** [comment]
Then I think you should issue a warning that this script won't be run anywhere because missing match and include, each time it is saved (install, update or edit).
Otherwise, it is counter-intuitive. ;)
