### ISSUE TITLE
5.2.6195 or up the Dark mode is damaged

### ISSUE THREAD

**Issue by tkp206093** [Tampermonkey/tampermonkey#2061]
(Please fill out the issue template with your details)

## Expected Behavior
the page is black

## Actual Behavior
the page is white

## Specifications

- Chromium: 124.0.2478.109
- TM: 5.2.6196
- OS: Win11 23H2 22631.3593

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
