### ISSUE TITLE
The script menu can not be refresh correctly when the menu content changes. `v5.2.6196 BETA`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2062]
## Expected Behavior
Make the script menu refresh correctly.

## Actual Behavior
The script menu can not be refresh correctly when the menu content changes in v5.2.6196 BETA.

## Specifications

- Chromium: Chrome 125.0.6422.61
- TM: 5.2.6196 BETA
- OS: Win10

## code 
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        GM_registerMenuCommand
// @grant        GM_unregisterMenuCommand
// @run-at       document-start
// ==/UserScript==

(function() {
  'use strict';
  const menu1 = GM_registerMenuCommand("1st menu, please wait...", ()=>{});
  setTimeout(()=>{
    GM_unregisterMenuCommand(menu1);
    GM_registerMenuCommand("2nd menu, it changed!!!", ()=>{});
  },3000)
})();
```

### TM v5.1.1 (correct)
![screenshot_2024-05-18_22-53-37](https://github.com/Tampermonkey/tampermonkey/assets/15855068/fd499e7e-0404-4094-b9c6-06ebba381a22)

### TM v5.2.6196 BETA (incorrect)
![screenshot_2024-05-18_22-54-27](https://github.com/Tampermonkey/tampermonkey/assets/15855068/985aceed-181b-4596-b05b-5bd7a7d9f700)

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
Thanks.
