### ISSUE TITLE
[beta] The downloaded blob is re-encoded as UTF-8 text

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#2064]
1. install the script below and open https://www.tampermonkey.net/
2. open the downloaded image in the browser or viewer

## Expected Behavior

![image](https://github.com/Tampermonkey/tampermonkey/assets/1310400/e6aa13b4-8aff-4073-9baa-c651a27dd9c9)

## Actual Behavior

Blank/empty image. The size is 45% bigger than the actual image and the contents looks re-encoded as UTF-8 text.

## Specifications

- Chromium: 125 and 128
- TM: beta 5.2.6195 and 5.2.6196
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         gmxhr
// @namespace    http://tampermonkey.net/
// @match        https://www.tampermonkey.net/*
// @grant        GM_download
// @connect      www.tampermonkey.net
// ==/UserScript==

GM_download('https://www.tampermonkey.net/images/icon48.png', 'icon48.png');
```

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)
