### ISSUE TITLE
Tampermonkey v5.2.6196 doesn't respect the language option in settings

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#2066]
I'm using Tampermonkey v5.2.6196 with Microsoft Edge v125.0.2535.51.

![image](https://github.com/Tampermonkey/tampermonkey/assets/38133098/5d9aefbf-ac79-492f-85df-6c3d0ae4a8f7)

As you can see, language is set to English, yet the language the userscript is displayed is Greek (browser's selected language). I seem to get this issue since the update to v5.2.6196.

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
