### ISSUE TITLE
set-cookie, being ignored from xmlHttpRequest 

### ISSUE THREAD

**Issue by v8dave** [Tampermonkey/tampermonkey#2068]
(Please fill out the issue template with your details)

## Expected Behavior
TamperMonkey is meant to set cookies sent within the xmlHttpRequest request.

## Actual Behavior
It seems to be ignoring the set-cookie headers.

## Specifications
TM: 5.2.6196

(apologies if something has changed in cookie handling that i've not updated for, but the script I use has been working fine for the past 6 months, i've made no changes, but the latest TM update has stopped updating the cookies)

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

**Comment by v8dave** [comment]
> Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)
> 
> Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

i've installed it and it still behaving the same and ignoring the set-cookie, however I can't do a proper test until later this evening when i can reboot the server it's running on.

**Comment by v8dave** [comment]
> Thanks for reporting. Should be at 5.2.6197 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)
> 
> Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

Ok, tested that fully and it still not behaving as it should, it isn't storing the cookie values at all..

![CookieFail](https://github.com/Tampermonkey/tampermonkey/assets/19746621/d1c9d925-81b6-4eed-8134-eadee4e8a812)

**Comment by v8dave** [comment]
Thanks, ok, looks to be something in the handling when not using https, this here doesn't return the set cookies

`// ==UserScript==
// @name         xxx
// @namespace    xxx
// @version      xxx
// @description  xxx
// @author       xxx
// @match        https://example.com
// @grant        GM.xmlHttpRequest
// @connect      httpbin.org
// ==/UserScript==

const d = Date.now();

await GM.xmlHttpRequest({
  //url: 'https://httpbin.org/response-headers?set-cookie=nonpartitioned=' + d + ';path=/;expires=Wed,%2021%20Sep%202033%2015:59:37%20GMT;httponly;secure;samesite=none'
    url: 'http://httpbin.org/response-headers?set-cookie=nonpartitioned=' + d + ';path=/;samesite=none'
})

const r = await GM.xmlHttpRequest({ url: 'http://httpbin.org/cookies' });

console.log('Cookie Value should be ' + d);
console.log(r.responseText);`

**Comment by derjanb** [comment]
Please see: https://stackoverflow.com/questions/60822936/where-to-add-samesite-none#:~:text=When%20the%20SameSite%3DNone%20attribute,provide%20protection%20against%20network%20attacks.

Opening `http://httpbin.org/response-headers?set-cookie=nonpartitioned=1111;path=/;samesite=none` in a browser tab doesn't set the cookie either.

**Comment by v8dave** [comment]
wow, taken me hours of rewriting and and banging my head against the wall, making it work, then it not working, i've found it!

it works with a single cookie
it fails if there are multiple,

i'm unsure how to replicate that on your site, but if dm's are similar are possible, i can demonstrate on my own.

**Comment by v8dave** [comment]
also, slightly worried that just editing to update with the correct paste won't be obvious, so could you reread the previous response ^^ (thank you)

**Comment by derjanb** [comment]
>  there is definitely a multiple cookie issue

Yes, I found the issue. Will be fixed at the next BETA.

**Comment by v8dave** [comment]
Works perfectly in release, thank you so much for this and for everything you do.

**Comment by tawwin251102** [comment]
[freebitco.txt](https://github.com/user-attachments/files/21583480/freebitco.txt)

// ==UserScript==
// @name         Copy Cookie for Freebitco.in
// @match        https://freebitco.in/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';
    setTimeout(() => {
        const cookie = document.cookie;
        alert("📋 Cookie copied:\n\n" + cookie);

        // Optional: Auto-copy to clipboard
        const temp = document.createElement("textarea");
        temp.value = cookie;
        document.body.appendChild(temp);
        temp.select();
        document.execCommand("copy");
        document.body.removeChild(temp);
    }, 3000); // 3 sec wait for page load
})();
