### ISSUE TITLE
GM_cookie.set cannot set the sameSite value to None

### ISSUE THREAD

**Issue by zqff99** [Tampermonkey/tampermonkey#2070]
When the value of sameSite is set to Lax/Strict, it is successful. When it is set to None, the execution fails (execution should be allowed when secure is true).The browser is able to set sameSite to None using document.cookie.

## Expected Behavior
Cookie set successfully.

## Actual Behavior
The message port closed before a response was received.
![image](https://github.com/Tampermonkey/tampermonkey/assets/50626023/b8466896-5224-42b0-9f63-14fc1ccbb85f)

## Specifications

- Chromium: (i.e. 64.0.3282.140)

## Script
GM_cookie.set({
  url: 'https://www.google.com/',
  name: 'test',
  value: 'value111',
  domain: '.google.com',
  path: '/',
  secure: true,
  httpOnly: true,
  sameSite: "None",
  expirationDate: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 30)
}, function(error) {
  if (error) {
    console.error(error);
  } else {
    console.log('Cookie set successfully.');
  }
});

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://www.google.com/
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @grant        GM_cookie
// @grant        unsafeWindow
// ==/UserScript==
(function() {
    'use strict';
unsafeWindow.GM_cookie = GM_cookie;//Debugging in the browser
  GM_cookie.set({
    url: 'https://www.google.com/',
    name: 'test',
    value: 'value111',
    domain: '.google.com',
    path: '/',
    secure: true,
    httpOnly: true,
    sameSite: "None",
    expirationDate: Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 30)
  }, function(error) {
    if (error) {
      console.error(error);
    } else {
      console.log('Cookie set successfully.');
    }
  });
})
```

**Comment by derjanb** [comment]
Thanks for reporting.  Please use `sameSite: "no_restriction"` -> https://developer.chrome.com/docs/extensions/reference/api/cookies#type-SameSiteStatus

Tampermonkey 5.2.6198 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)) will now also report this issue via the error argument.

Just download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
