### ISSUE TITLE
Tampermonkey beta 5.2.6197 cannot be run every time after restarting Chrome. You need to close the extension and then open it again.

### ISSUE THREAD

**Issue by Tback1** [Tampermonkey/tampermonkey#2075]
Tampermonkey cannot be run every time after restarting Chrome. You need to close the extension and then open it again.And it can only be closed in the expansion management. After closing and opening again, everything will be normal. But after restarting Chrome, it doesn’t work again.

![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/5a7636e3-7b88-44cf-be05-6d7e307e2b48)

![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/f82363b6-bd7a-49dd-b0cc-e7867190f8f8)

![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/44a8a78d-76d5-485a-9123-34c1089dfc29)

## Specifications

![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/6ecff146-0882-423a-8038-156c4ce7ed36)

- Chrome stable : (125.0.6422.61)
- TM: (5.2.6197)
- OS: (Windows 10 LTSC (21H2) 19044.3324)

**Comment by derjanb** [comment]
Can you please run this snippet and attach the output here? You can remove 'userscript-api' entries if any.

```
(async () => {
    const usc = chrome.userScripts;
    const all = await usc.getScripts();
    console.log('before remove', all);
})();
```

Then please run this and check if the output changes and whether tzis fixes the issue. Thanks!

```
(async () => {
    const usc = chrome.userScripts;
    await usc.unregister({ ids: ['content|mtwhl|r'] });
    const all = await usc.getScripts();
    console.log('after remove', all);
})();
```

**Comment by Tback1** [comment]
Sorry there some work I can't restart browser
after test the code still no effect
![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/18d5912f-d891-4973-a0ee-ff1200c71d91)

**Comment by Tback1** [comment]
![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/f80cad55-e234-416e-a7c4-febabfaaa9a1)

Even after I disable and enable the Tampermonkey extension, there are still some error messages in the devtool

**Comment by derjanb** [comment]
OK. Thanks. Then please run this as final test:

```
(async () => {
    const usc = chrome.userScripts;
    let all = await usc.getScripts();    
    await usc.unregister({ ids: all.map(s => s.id) });
    all = await usc.getScripts();
    console.log('after remove', all);
})();
```

**Comment by Tback1** [comment]
> OK. Thanks. Then please run this as final test:
> 
> ```
> (async () => {
>     const usc = chrome.userScripts;
>     let all = await usc.getScripts();    
>     await usc.unregister({ ids: all.map(s => s.id) });
>     all = await usc.getScripts();
>     console.log('after remove', all);
> })();
> ```

unfortunately, it's still not solve the question
![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/a95a6da9-1514-4acf-bcbb-832c7de35fab)

**Comment by derjanb** [comment]
Tested with 125.0.6422.112 and 125.0.6422.113.
Maybe this is a 125.0.6422.61 issue? Can you update your Chrome?

**Comment by derjanb** [comment]
Please also try 5.2.6198 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)) *.
It won't fix the underlying issue, but Tampermonkey should at least start again so that you can export your scripts.
Then would it be possible to test again using a new temporary Chrome profile?

\* Just download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

**Comment by Tback1** [comment]
> Tested with 125.0.6422.112 and 125.0.6422.113. Maybe this is a 125.0.6422.61 issue? Can you update your Chrome?

updated to  125.0.6422.113 still
![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/1203e5b8-c9a2-47e8-a617-047211c4faef)

**Comment by Tback1** [comment]
> Please also try 5.2.6198 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)) *. It won't fix the underlying issue, but Tampermonkey should at least start again so that you can export your scripts. Then would it be possible to test again using a new temporary Chrome profile?
> 
> * Just download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

this version solve this question
**1.in the new blank profile ,it's work**
![image](https://github.com/Tampermonkey/tampermonkey/assets/8872546/ca406cb4-b412-4a06-9f40-15d96e47f60a)

2. in my daily profile . it's work well too.
