### ISSUE TITLE
whether script execute at inline page without open any site page?

### ISSUE THREAD

**Issue by chopins** [Tampermonkey/tampermonkey#2077]
I has 2FA script, the script not run at any page, now need open a page for run.
so, hope tampermonkey can be built a page of execute foreground scripts, instead of open one page.
 The inline page will opened in new tab.

**Comment by 7nik** [comment]
Userscripts are designed to be run on _sites_ to modify them for whatever reason.
If you need to run a script once per browser session - create a browser extension, it isn't that hard.

**Comment by chopins** [comment]
yes, it is not hard， and I found scriptcat extension has similar features.
i will add that features to scriptcat extension.
