### ISSUE TITLE
Microsoft Edge no more working with YouTube

### ISSUE THREAD

**Issue by yaf79** [Tampermonkey/tampermonkey#2078]
Sure, here is the issue template filled out with your details:

---

## Expected Behavior

Tampermonkey should work correctly with Microsoft Edge on Debian 12 Bookworm.

## Actual Behavior

Tampermonkey does not work with Microsoft Edge on Debian 12 Bookworm.
T.M.  no more working on YouTube within Microsoft Edge

## Specifications

- OS: Debian 12 Bookworm

**Comment by derjanb** [comment]
Is this a duplicate of https://github.com/Tampermonkey/tampermonkey/issues/2083#issuecomment-2154885537 ?
