### ISSUE TITLE
scripts run slow

### ISSUE THREAD

**Issue by WhiteSevs** [Tampermonkey/tampermonkey#2079]
(Please fill out the issue template with your details)

## Expected Behavior

让脚本@run-at document-start能够稳定在document.body前加载出来
这样的话我需要劫持页面的函数就可以正常运行

### v: 5.1.1(正常的)
![5a1290c99948b43c186d032d973877fa](https://github.com/Tampermonkey/tampermonkey/assets/50544447/8c119505-90ab-45e8-90d1-02dffbe89eff)

### v: 5.2.6198(不正常的)

在beta版本中，这个触发不太稳定，有时候是在document.body加载前，有时候是在document.body加载完成后
![a3d74c7ef8e1c7869b66939c1442f4a3](https://github.com/Tampermonkey/tampermonkey/assets/50544447/eb0c059e-73b2-4a8f-92fa-5a572b2e16e4)

### 两个版本一起运行

![Clip_2024-06-02_12-59-55](https://github.com/Tampermonkey/tampermonkey/assets/50544447/082c4963-4fde-421d-af58-9f44ab39f5f7)

## Specifications

- Chromium: (i.e. 125.0.2535.79)
- TM: (i.e. 5.1.1)
- TM-beta: (i.e. 5.2.6198)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match *://*/*
// @grant none
// ==/UserScript==
(()=>{
console.log("document.documentElement ↓");
console.log(document.documentElement)
console.log("document.body ↓");
console.log(document.body);
})()
```

**Comment by WhiteSevs** [comment]
### v: 5.2.6198
当我设置TM的日志记录级别-调试时
console输出如下
![Clip_2024-06-02_13-02-16](https://github.com/Tampermonkey/tampermonkey/assets/50544447/43ac86a3-a106-44da-b32c-7f52fbba9c4d)

**Comment by derjanb** [comment]
Please try `Content Script API` set to `UserScripts API Dynamic`. This is the best replacement for instant injection that is possible at manifest v3 at the moment.

Please also see #211

**Comment by WhiteSevs** [comment]
> Please try `Content Script API` set to `UserScripts API Dynamic`. This is the best replacement for instant injection that is possible at manifest v3 at the moment.
> 
> Please also see #211

I have some question, when select `UserScripts API Dynamic`,i can not use `@require file://....` to load local file,it can solve?

**Comment by KeepssMe** [comment]
I would really like to return the **instant injection**. **UserScript Dynamic API** does not allow me to do what I want. I need to have some listeners even before the first script starts running on the site page.

The script runs as it should only when the page is hard-reloaded.

Can you tell me how else it can be done?
(I apologize for my poor knowledge of English)
