### ISSUE TITLE
Start tampermonkey to report an error

### ISSUE THREAD

**Issue by IdealBoy709** [Tampermonkey/tampermonkey#2085]
How to solve the following errors, my Chrome console saw this information.

Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

![image](https://github.com/Tampermonkey/tampermonkey/assets/25577631/d1ed4673-c133-44c6-a7f4-3a5434c23511)

**Comment by derjanb** [comment]
What browser and Tampermonkey version?
