### ISSUE TITLE
The scripts are not injected fast enough, even in UserScripts API dynamic API.

### ISSUE THREAD

**Issue by Maxwelline** [Tampermonkey/tampermonkey#2086]
In Tampermonkey 5.1.1 and older versions (MV2), setting the `Injection Mode` to `Instant` can solve the problem of script injection delay, and the experience is very good.

After upgrading to Tampermonkey 5.2.0 (MV3), even with `Content Script API` set to `UserScripts API Dynamic`, script injection is still a bit slow, which may cause delays in loading styles or make some feats invalid.

@derjanb, Could you continue to optimize the injection timing so that the delay disappears or is as low as possible? 

Thanks.

**Comment by derjanb** [comment]
Should be at 5.3.6200 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode'). For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
What a masterpiece! It's executing very quickly now! Thank you!

**Comment by derjanb** [comment]
> I also tested 5.3.6200 on MS Edge

Edge store version is still 5.2.6198 or did you install the CRX manually? 
If so, then it should work once switched to `UserScripts API Dynamic`.
