### ISSUE TITLE
[BUG] GM_download.abort may take too much time

### ISSUE THREAD

**Issue by CrayonSSR** [Tampermonkey/tampermonkey#2088]
## Expected Behavior
After executing the abort method, GM_download will attempt to terminate the request as promptly as possible.

## Actual Behavior
GM_download will wait for the server's response head before cancelling the request, then triggers the onerror event.

## Specifications

- Chromium: (120)
- TM: (Stable 5.2.0 & Beta 5.2.6198)
- OS: (Window 10 2024.05)

## Script

* A simple server using `python` which could respond to requests with a specified duration.
```py
from flask import Flask, send_from_directory
from time import sleep

app = Flask(__name__)

@app.route('/assets/<int:wait_time>/<path:name>')
def get_image(wait_time, name):
    
    sleep(wait_time) # seconds

    return send_from_directory('assets', name, mimetype='image/png')


if __name__ == '__main__':
    app.run(host='0.0.0.0',port=7777,debug=True)
```

* Test abort cost
```js
// ==UserScript==
// @name                GM_download abort test
// @match               https://www.tampermonkey.net/*
// @connect             127.0.0.1
// @connect             *
// @grant               GM_download
// @run-at              document-start
// @version             1.0
// ==/UserScript==

// tampermonkey download mode: browser

const start = Date.now()

const downloader = GM_download({
    url: 'http://localhost:7777/assets/15/test.png',
    name: 'test/test.jpg',
    timeout: 5000,
    onerror(event) {
        console.log(`Abort cost ${( Date.now() - start - 300) / 1000}s`, event)
    },
    ontimeout(event) {
        console.log(`ontimeout cost ${( Date.now() - start) / 1000}s`, event)
    },
})

setTimeout(() => downloader.abort(), 300)
```

## Test log
```js
// Note: URL rule: '/assets/<wait_time(s)>/<file_name>'
// Note: Without abort, GM_download could successfuly save the file after <wait_time>
// Note: The timeout event never trigger.

// url: 'http://localhost:7777/assets/10/test.png'
// log: Abort cost 10.286s { details: {current: 'USER_CANCELED'} }

// url: 'http://localhost:7777/assets/15/test.png'
// log: Abort cost 15.082s { details: {current: 'USER_CANCELED'} }

// url: 'http://localhost:7777/assets/33/test.png'
// log: Abort cost 33.996s { details: {current: 'USER_CANCELED'} }
```

**Comment by derjanb** [comment]
The "Download Mode" setting is untouched ("Default")? Is this correct?

**Comment by CrayonSSR** [comment]
> The "Download Mode" setting is untouched ("Default")? Is this correct?

Yes, it won't happen on `Download Mode: Default`.

![image](https://github.com/Tampermonkey/tampermonkey/assets/93774795/8c7e2028-fee3-4e53-9d12-7bfb1fece7da)

It seems that this issue only occurs in  `Download Mode: Browser API` .

**Comment by JsGarcia5** [comment]
sorry to bother you. You're KC Enhancer's developer, right? I see your name in the script. Now that afdian is dead, where will you post updates?

**Comment by CrayonSSR** [comment]
> sorry to bother you. You're KC Enhancer's developer, right? I see your name in the script. Now that afdian is dead, where will you post updates?

Afdian is dead ???

Afdian has two domains, **[afdian.com](https://afdian.com/)** and **[afdian.net](https://afdian.net/)**.

Are you saying that [afdian.net](https://afdian.net/) has been abandoned.
