### ISSUE TITLE
'Yes' option removed from Modify existing CSP setting

### ISSUE THREAD

**Issue by perpil** [Tampermonkey/tampermonkey#2090]
My script requires the ability to call `unsafe-eval` on content that comes from GitHub web pages.  The CSP for GitHub doesn't allow this, so I need to set the `Modify existing CSP setting` in TamperMonkey for Chrome.  The default settings seem ok with FireFox.  Between TamperMonkey 5.1.1 and 5.2.0, the option for `Yes` was removed in Chrome and I now need to set it to `Remove entirely (possibly insecure)`.  I assume this change was intentional.  What is the difference between `Yes` and `Remove entirely (possibly insecure)` and is the change something that is now required due to MV3?

Screenshot:
<img width="661" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/97474956/f5c3c44a-3e9f-466c-95bf-88efcdf31a58">

## Expected Behavior
The less scary `Yes` is an option for Modify existing CSP setting

## Actual Behavior
`Yes` is no longer an option

## Specifications

- Chrome 125.0.6422.142 
- TM: 5.2.0
- OS: MacOS Sonoma 14.5

## Script

[Link](https://github.com/No-Backspace-Crew/Speedrun/blob/main/Speedrun.user.js)

**Comment by derjanb** [comment]
`Yes` relaxed the CSP while the other option removed it. Unfortunately relaxing is not possible in Manifest v3 anymore. 
Please use `GM_addElement` or try to run your script and eval the sources at `@run-at document-start` when  `Content Script API` is set to `UserScripts API Dynamic`.
