### ISSUE TITLE
Missing Inject Mode Option in Tampermonkey Safari Settings

### ISSUE THREAD

**Issue by bigplayer-ai** [Tampermonkey/tampermonkey#2093]
## Expected Behavior
The Inject Mode option should be available in the settings, allowing users to choose between different script injection modes, including an "Instant" mode.

## Actual Behavior
The Inject Mode option is not visible in the Tampermonkey settings interface for Safari, version 5.2.6199. There is no Experimental tab or section where this setting could potentially be found.

## Specifications

- Browser: Safari Version 17.5 (19618.2.12.11.6)
- TM: 5.2.6199
- OS: MacOS Version 14.5 (23F79)

## Script

Not applicable as this is an issue with the Tampermonkey interface itself and not a specific userscript.

**Comment by devnoname120** [comment]
It's also missing for me but on Chromium:

![image](https://github.com/user-attachments/assets/d936b8dd-80f9-4af4-b338-c10b82042627)

<img width="883" alt="image" src="https://github.com/user-attachments/assets/adb3f83e-3162-4eae-b643-8987e5a7119c">

**Comment by derjanb** [comment]
`UserScripts API Dynamic` is what you're looking for.

https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-2222196181
