### ISSUE TITLE
[Bug] Using the browser to go back to the history page in some sites will cause the running script to disappear. `MV3`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2097]
## Actual Behavior
On some sites (such as [greasyfork.org](https://greasyfork.org/)), the browser's forward or backward operation will cause the script manager's script menu to disappear.

To emphasize: the script loads successfully and runs fine, but only the script menu disappears.

## screenshot
![screenshot_2024-06-17_20-28-55](https://github.com/Tampermonkey/tampermonkey/assets/15855068/1a5eeb50-b88b-4b9b-8dab-a844752d5533)

## Specifications

- Chromium: Brave 126.0.6478.71 (64-bit)
- TM: 5.2.0 / 5.2.6198 / 5.3.6200 / 5.3.6201 / 5.3.6202
- OS: win10

**Comment by F9y4ng** [comment]
@derjanb, the following three sites all have issues with the script menu disappearing when using the browser's backward action:

1. greasyfork.org
2. openuserjs.org
3. www.userscript.zone

**Comment by F9y4ng** [comment]
This issue has been fixed in Tampermonkey 5.2.1.

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.3.6204 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

**Comment by F9y4ng** [comment]
Thanks, it works fine now.
