### ISSUE TITLE
switch to Manifest V3 broke @require and @resourse for local files

### ISSUE THREAD

**Issue by arkady-sunrock** [Tampermonkey/tampermonkey#2098]
I have a file myscript.user.js
It has:
// @require     display.js
// @resource    css    display.css
Both files are local and in the same directory as myscript.user.js
TM no longer finds these files in version 5.2

## Expected Behavior
TM should continue to find these files as before.

## Actual Behavior
TM no longer finds these files in version 5.2

## Specifications

TM 5.2
Chrome 126.0.6478.62

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyScript
// @require     display.js
// @resource    css    display.css
```

**Comment by derjanb** [comment]
This is working fine here.  

Both requiring files with complete path: "file://C:\Users\me\Documents\bla.user.js",

as well as only "bla.user.js" when the script was installed from that location.

Please check whether "Update URL" shows something like "file:///C:/Users/me/Documents/local_require.user.js"

**Comment by derjanb** [comment]
> My @require does not have complete paths

Yes, as mentioned, I tested this as well.

> My extension for included file is .js, yours is .user.js.

Doesn't matter.

> Please check whether "Update URL" shows something like "file:///C:/Users/me/Documents/local_require.user.js"

^^^ Please check the Update URL at the script's settings page.

**Comment by arkady-sunrock** [comment]
The update URL does show full paths.

One more important thing!
The problem disappears if I set URL detection to Legacy. Which I am guessing turns of some of the changes that happened between 5.11 and 5.2.
The problem only happens if URL detection is set to Auto.

**Comment by derjanb** [comment]
Ah I see. Installation via drag and drop to the extension page doesn't allow Tampermonkey to read the file location, therefore it can't resolve relative resources.

Root cause is #2099
