### ISSUE TITLE
5.2 Manifest V3 update broke script installation from local files

### ISSUE THREAD

**Issue by arkady-sunrock** [Tampermonkey/tampermonkey#2099]
I have trouble installing user scripts from local files
I used to be able to drag and drop myscript.user.js into almost anywhere in the browser and it would install it.
Since TM 5.2 and the Manifest V3 update, TM rejects the local scripts.
The only workaround is to go to the TM options page->Installed scripts and there is an area where the local files can be dropped and accepted.

## Expected Behavior
I should be able to continue to install local .user.js scripts by dropping them into the browser

## Actual Behavior
Since TM 5.2 and the Manifest V3 update, TM rejects the local scripts.
The only workaround is to go to the TM options page->Installed scripts and there is an area where the local files can be dropped and accepted.

## Specifications

TM 5.2
Chrome 126.0.6478.62

**Comment by derjanb** [comment]
Workaround: Switch "Userscript URL detection" from "Auto" to "Legacy".

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.3.6201 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by dimdamin** [comment]
> Thanks for reporting. Should be at 5.3.6201 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Hi, can i get for firefox now? Maybe an unsigned one if needed!
