### ISSUE TITLE
Add per script auto-update toggle

### ISSUE THREAD

**Issue by Theo1996** [Tampermonkey/tampermonkey#2100]
It would be nice if you can select which userscripts update automatically , because sometimes , newer versions of superscripts break and you want to disable auto update for just one script .

**Comment by 7nik** [comment]
Open a userscript, tab Settings, and in the section Updates, check/uncheck Check for updates.

**Comment by derjanb** [comment]
Thanks @7nik

**Comment by Theo1996** [comment]
thanks

**Comment by bottleblue** [comment]
> Open a userscript, tab Settings, and in the section Updates, check/uncheck Check for updates.

Can I configure it to notify me if a script has an update but not to autoupdate?
