### ISSUE TITLE
Chrome 126+ STATUS_ACCESS_VIOLATION/SIGSEGV

### ISSUE THREAD

**Issue by yang10560** [Tampermonkey/tampermonkey#2101]
var:
Microsoft Edge
v 126.0.2592.61 

When I send an XHR request. Then obtain the content, fill it into the body of the webpage, and a blank page will appear. And prompt error code: STATUS ACCESS VIOLATION、

This situation will not occur in other browsers

**Comment by derjanb** [comment]
Most probably #2094 is the reason.

[Tampermonkey Stable](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd) is working as expected, right?

**Comment by derjanb** [comment]
Interesting... Chrome 120, 122, 124 and 125.0.6422.112 are working fine.
Chrome 126.0.6478.62 and 126.0.6478.115 is crashing...

I create a Chrome issue here: https://issues.chromium.org/issues/348407284

**Comment by derjanb** [comment]
Seems to be caused by 

```
responseType: "stream"
```

without this it doesn't crash...

**Comment by derjanb** [comment]
Fixed at Chrome.
