### ISSUE TITLE
`@run-in` support

### ISSUE THREAD

**Issue by cyber-sec0** [Tampermonkey/tampermonkey#2102]
## Expected Behavior
// @ GM.tab_types incognito
This should define tampermonkey "tab_types" in a script

## Actual Behavior
This doesn't exist

## Specifications

- Edge: Latest
- TM: Latest
- OS: W11

**Comment by derjanb** [comment]
And what should `tab_types` to?

**Comment by cyber-sec0** [comment]
![a](https://github.com/Tampermonkey/tampermonkey/assets/91571849/0ac047bd-033d-48d4-9fb4-7ed886cd5254)
The same thing this does.

**Comment by derjanb** [comment]
5.3.6205 has a new meta tags called [`@run-in`](http://tmnk.net/docs#meta:run_in).

([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by cyber-sec0** [comment]
I haven't tested it, but thank you for adding it!
