### ISSUE TITLE
Tampermonkey BETA causes PDFs to infinitely refresh

### ISSUE THREAD

**Issue by GriffinCodes** [Tampermonkey/tampermonkey#2106]
## Expected Behavior
PDF pages do not refresh automatically

## Actual Behavior
When the TM Beta extension is enabled, even when all scripts are disabled and/or TM is disabled via TM's menu, PDF pages will begin to infinitely refresh after a random period of time, usually 0-120 seconds. Once disabling TM Beta via chrome://extensions, PDFs immediately work normally and never refresh again.

![SHTkOVzpMH](https://github.com/Tampermonkey/tampermonkey/assets/12417961/d78524c8-934b-4e1c-a0c7-cd662b3cdc31)

## Specifications

- Chrome: 125.0.6422.113 (Official Build) (64-bit)
- TM: BETA 5.3.6201
- OS: Windows 10

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.3.6202 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

**Comment by GriffinCodes** [comment]
Looks good, thank you!
