### ISSUE TITLE
Setting {accessKey : "+"} to GM_registerMenuCommand hides all scripts from the popup menu

### ISSUE THREAD

**Issue by Sibsen1** [Tampermonkey/tampermonkey#2113]
## Expected Behavior

Scripts should be visible in the popup menu.

## Actual Behavior

All scripts are hidden in the menu. Only the number of scripts is still visible on the button.

## Specifications

- Chromium: 126.0.6478.127 (Official Build) (64-bit)
- TM: 5.1.1
- OS: Windows 11 Home 23H2

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Test
// @include       *://*
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
    'use strict';

    GM_registerMenuCommand("foo", () => {}, {accessKey: "+"});
})();
```

**Comment by derjanb** [comment]
Good catch!
