### ISSUE TITLE
Annoying 'Script is slowing down your page load' doesn't go away even after script removal

### ISSUE THREAD

**Issue by adamlui** [Tampermonkey/tampermonkey#2116]
(Please fill out the issue template with your details)

## Expected Behavior

Message go away

## Actual Behavior

![image](https://github.com/Tampermonkey/tampermonkey/assets/10906554/b50cd1f8-33df-442a-bac2-5d19d85d9690)

## Specifications

- Chromium: 126.0.6478.127
- TM: 5.2.0
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

Thousands of lines too long to paste, src code @ https://github.com/KudoAI/googlegpt/blob/main/greasemonkey/googlegpt.user.js

Also I tested the actual load times with and without it on, it didn't slow the page load at all, so the "warning" is unhelpful (the script's main div is the new LCP and loads near instantaneously)

**Comment by adamlui** [comment]
## Suggested action

Remove this unhelpful warning outright, or add a dismiss button

**Comment by derjanb** [comment]
This is displayed if evaluating a script's `@include` or `@match` needs more than a second. The message will disappear after 5 minutes automatically. But you're right a dismiss button would be good.

**Comment by adamlui** [comment]
> if evaluating a script's @include or @match needs more than a second

What do you mean? The script matches a lot of different Google domains, so Tampermonkey took more than a second to determine which one the script applied to, thus it was determined GoogleGPT added to Google's load time, even though Google loaded in exactly the same time?

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.3.6204 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by adamlui** [comment]
Did you get rid of the warning? Or you are only making it go away immediately? Because if the latter, the warning is still not useful if it's based on matches as you revealed

**Comment by derjanb** [comment]
Manifest v3 versions don't show the warning anymore.

**Comment by adamlui** [comment]
When will you publish this to CWS as the latest ver?

**Comment by derjanb** [comment]
As soon as the version was reviewed.

**Comment by adamlui** [comment]
You mean by Chrome team or your own reviewers before you submit for Chrome review

**Comment by derjanb** [comment]
The crx is already signed by the Chrome Webstore, but the version must be reviewed by their team before release.
