### ISSUE TITLE
"@run-at  document-idle"  can not work?  Anyone can help me please?

### ISSUE THREAD

**Issue by os9sur** [Tampermonkey/tampermonkey#2119]
## Expected Behavior
Running my script after the page and all resources are loaded and page scripts have run.
Because I want to cover the style(color) of an element marked as **!important** on a web page.

## Actual Behavior
can not work

## Specifications

- Chromium: ( 126.0.6478.127)
- OS: (Windows 10  22H2)

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// @run-at document-idle
// ==/UserScript==

(function() {
    'use strict';
  var content=document.querySelectorAll(".Answer-content");
    for (let i = 0; i< content.length; i++) {
        content[i].style="background-color:#191b1f !important";
    }
})();

```

**Comment by derjanb** [comment]
You need to use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#basic_usage) to wait for your elements to appear.

**Comment by derjanb** [comment]
> if the element doesn't have '!important' in its style, then the script works fine

You have to ensure your selector is more specific.

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
