### ISSUE TITLE
pixeltris' twitchadsolutions VAFT userscript almost never auto updates even though there are new versions of it every 2-3 weeks

### ISSUE THREAD

**Issue by ComfortableMilk4454** [Tampermonkey/tampermonkey#2124]
## Expected Behavior
for script to autoupdate 

## Actual Behavior
script doesn't auto update/ takes weeks to auto update

## Specifications

- Firefox release 128.0
- TM: (i.e. 4.5.5648) idk what this is sorry :(
- OS: macOS 14.5

## Script

 https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft.user.js

**Comment by derjanb** [comment]
The update URL redirects to `raw.githubusercontent.com` from where Tampermonkey requests the file just fine...

Do you see this issue also when manually clicking "Check for userscript updates" either at the action menu or the the script's settings tab?

**Comment by ComfortableMilk4454** [comment]
hey, thanks for the response. ill have to check when a new update comes out, cuz rn i believe i have the latest version as i had to reset my mac to factory settings so when i made the OP i had just added the userscript.
