### ISSUE TITLE
[BUG] Some scripts will not be executed properly in `UserScripts API Dynamic` mode. `MV3`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2126]
## Actual Behavior
In `UserScripts API Dynamic` mode, the scripts without `@run-at document-start` will not be executed properly, and background.js reports an error in the DevTools console.

![console](https://github.com/user-attachments/assets/53637e72-2eb0-46e9-baba-fafbd4909b5c)

I installed and tested the following three scripts at the same time:

1. https://greasyfork.org/scripts/24204
2. https://greasyfork.org/scripts/416688
3. https://greasyfork.org/scripts/445274

Either script 2 or script 3 will cause script 1 to fail to load. I think it's those `@run-at document-start` scripts which cause the error when registering scripts at other load times.

**But in `UserScripts API` mode, everything is normal.**

## Specifications

- Chromium: 126.0.6478.127
- TM: 5.2.1
- OS: Win 10

**Comment by derjanb** [comment]
Good catch! Thanks.

**Comment by derjanb** [comment]
Thanks for reporting. Should be at 5.3.6204 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
Thanks, it works fine now.
