### ISSUE TITLE
[BUG] Greasyfork.org cannot get version information of the script in `UserScripts API Dynamic` mode. `MV3`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2127]
## Actual Behavior
Greasyfork.org cannot get version information of the script in `UserScripts API Dynamic` mode. 

### UserScripts API
![Userscript API](https://github.com/user-attachments/assets/06b8afe2-d2a2-466a-ae1d-c8d605bd7520)

### UserScripts API Dynamic
![Userscript API Dynamic](https://github.com/user-attachments/assets/bd0f1917-8697-47a8-8b29-7b1c442df778)

#### And a prompt will pop up when you click the install button:
![install prompt](https://github.com/user-attachments/assets/a79bb571-f6c2-4f13-9c90-8ded4f30e9ba)

## Specifications

- Chromium: 126.0.6478.127
- TM: 5.2.1
- OS: Win 10

**Comment by derjanb** [comment]
Another good catch!

Should be at 5.3.6204 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
Thanks, it works fine now.
