### ISSUE TITLE
Не включается скрипт в Яндекс Браузере Версия 24.6.3.729 (64-bit)

### ISSUE THREAD

**Issue by First-j** [Tampermonkey/tampermonkey#2128]
Не работает скрипт в Яндекс Браузере Версия 24.6.3.729 (64-bit)

На сайте https://www.gwars.io

[555555 - июль 2024.txt](https://github.com/user-attachments/files/16233447/555555.-.2024.txt)
(Please fill out the issue template with your details)

## Specifications

- Chromium: Yandex Browser
- TM: 24.6.3.729 (64-bit)
- OS: Windows 10 Pro

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name Andrei
// @namespace https://www.gwars.io
// @Version 24.6.3.729 (64-bit)
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by First-j** [comment]
Заработало, установил Tampermonkey Legacy (MV2)

Chrome >= 71

**Comment by derjanb** [comment]
Interesting. The script doesn't seem to contain anything that could have been broken in TM 5.2.

Did you enable "Developer Mode" to allow Tampermonkey to execute the script?

> Tampermonkey Legacy

Glad you found a workaround.
