### ISSUE TITLE
谷歌浏览器脚本不能启动运行，需要手动关闭再启动，然后刷新浏览器才能正常运行脚本

### ISSUE THREAD

**Issue by zpiao119** [Tampermonkey/tampermonkey#2131]
Chrome浏览器不能正常运行tampermonkey扩展，需要手动关闭再启动，然后刷新浏览器才能正常tampermonkey扩展

**Comment by derjanb** [comment]
请添加更多详细信息或截屏视频。我不明白到底是什么不起作用以及刷新浏览器意味着什么。您是否需要将浏览器或 Tampermonkey 更新到新版本？

**Comment by zpiao119** [comment]
每次电脑开机，首次运行Chrome浏览器tampermonkey扩展图标都是灰色的，在chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo中

   - Service Worker 是无效的，需要关闭Chrome，重新打开才会恢复，


Jan Biniok ***@***.***> 于2024年8月2日周五 15:35写道：

**Comment by derjanb** [comment]
Please add your Tampermonkey and browser versions.

**Comment by zpiao119** [comment]
吴迪 ***@***.***> 于2024年9月18日周三 21:39写道：

**Comment by zpiao119** [comment]
![1](https://github.com/user-attachments/assets/3b62fbc0-91f0-4168-b201-934267de1bad)
![4](https://github.com/user-attachments/assets/17b34d4e-b63a-439b-aa4e-e318d7565b00)

**Comment by zpiao119** [comment]
重新打开浏览器后Service Worker 恢复正常
![5](https://github.com/user-attachments/assets/854a92df-7777-493d-b05a-bf2c80d4e328)

**Comment by derjanb** [comment]
Superseded by #2221

**Comment by zpiao119** [comment]
TM在Chrome下与网页版抖音不兼容，在开启TM时鼠标滑动到抖音视频框会自动隐藏鼠标，而且无法使用，也会出现当打开网页版抖音时时常无法加载视频
