### ISSUE TITLE
can't open popup menu of tampermonkey

### ISSUE THREAD

**Issue by denmarmon** [Tampermonkey/tampermonkey#2133]
## Expected Behavior
when i click the tampermonkey extension a popup will appear

## Actual Behavior
instead this happens:
![Screenshot (29)](https://github.com/user-attachments/assets/518f2f55-5d6d-4610-babf-23953e8f0a54)

It happened when chrome crashed
i tried restarting chrome a few times but no luck
can anyone help?

## Specifications

im using chrome on windows 10

**Comment by derjanb** [comment]
Please check the background page for error. Thanks. https://tmnk.net/faq#Q600

**Comment by zpiao119** [comment]
我和你的问题一样，需要重新启动tampermonkey 扩展，刷新Chrome解决

**Comment by antisober** [comment]
Я переустановил расширение и проблема исчезла.
