### ISSUE TITLE
[BUG] The GM_xmlhttpRequest finalURL lost the hash 

### ISSUE THREAD

**Issue by youxiaohou** [Tampermonkey/tampermonkey#2134]
When using GM_xmlhttpRequest to obtain the final redirect link after 302, the hash value of the final link will be lost, as shown in the following figure: all the content after login_success# is lost

Violentmonkey is ok, Tampermonkey and Tampermonkey Beta both have this problem

## Expected Behavior

![image](https://github.com/user-attachments/assets/e7f07960-22b3-44fb-b9f9-f43810628ffe)

## Actual Behavior

![image](https://github.com/user-attachments/assets/092a7601-dfdc-4633-8200-25dd2fc4fb53)

## Specifications

- Chromium: 123.0.6312.123
- TM: Tampermonkey: 5.2.3 & Tampermonkey Beta: 5.3.6204
- OS: Windows 11

**Comment by derjanb** [comment]
Should be fixed at 5.3.6205 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
