### ISSUE TITLE
[BUG]tampermonkey Beta 5.3.6206版本在狐猴浏览器beta版本中无法安装脚本！

### ISSUE THREAD

**Issue by yaohuow** [Tampermonkey/tampermonkey#2138]
如视屏所示，在Android客户端中无法下载脚本了！

https://github.com/user-attachments/assets/ce690ca0-f3dc-4a71-806f-9fd5a19b4b8c

![Screenshot_2024-07-30-21-29-16-506_com lemurbrowser exts beta-edit](https://github.com/user-attachments/assets/859f0004-bbbd-4844-ba81-6b2b90b6e499)

**Comment by derjanb** [comment]
您的浏览器和版本是什么？  你的 Tampermonkey 版本是什么？

使用 Tampermonkey BETA 5.3.6206，脚本安装在 Firefox Mobile 128.0.1 和 MS Edge Canary 128.0.2730 上运行良好。

--- 

What is your browser and version?  What is your Tampermonkey version?

Script installation is working fine here at Firefox Mobile 128.0.1 and MS Edge Canary 128.0.2730 using Tampermonkey BETA 5.3.6206.

**Comment by derjanb** [comment]
您可以尝试在设置页面将“用户脚本 URL 检测”设置为“旧版”。
---
You can try to set "Userscript URL detection" to "Legacy" at the settings page.

**Comment by yaohuow** [comment]
有一个chrome运行时错误：保留扩展端口的页面被移动到向后/向前缓存中，消息通道被关闭！

tampermonkey Beta 5.3.6204版本开始有这个bug，option页面使用sendMessage方法，与后台通信的时候，被放到缓存中，消息通道被关闭，所以无法与后台进行通信，也就安装不了脚本

问题应该出tampermonkey beta 5.3.6204版本，这个版本添加了一个浏览器前进后退缓存功能存在bug导致的

**Comment by yaohuow** [comment]
tampermonkey_beta_v5.3.6207依然无法安装插件

**Comment by yaohuow** [comment]
> 您可以尝试在设置页面将“用户脚本 URL 检测”设置为“旧版”。
> 
> You can try to set "Userscript URL detection" to "Legacy" at the settings page.

OK，改了后可以了，谢谢！

**Comment by turbe** [comment]
Where can I see the source code for tampermonkey v5.3
