### ISSUE TITLE
Help to Clear cache cookies ...

### ISSUE THREAD

**Issue by funmolde** [Tampermonkey/tampermonkey#2139]
Hello, I can't create a script to delete from a site: cache , cacheStorage ,cookies ,indexedDB ,localStorage.
Is there a way to do this?
Chrome extensions work but not with tampermonkey. 
What's the point of tampermonkey if it can't do the same thing as the extensions?
Thank you -_-

- Edge :  127.0.2651.74 (Version officielle) (64 bits)
- OS: (Windows 11 64bits)
-Tampermonkey: 5.1.1

**Comment by derjanb** [comment]
`localStorage` and `indexedDB` be deleted by a userscript running at the page. You can delete cookies via `GM_cookie`.
Cache can't be deleted by userscripts.
