### ISSUE TITLE
Throw error "Uncaught DOMException: Failed to execute 'createEvent' on 'Document': The provided event type ('MutationEvent') is invalid." in tampermonkey in content.js 

### ISSUE THREAD

**Issue by htfc786** [Tampermonkey/tampermonkey#2143]
# The bug in tampermonkey in content.js make my script can't running successful.

Hello,thank you for you reading. I'm only a senior school student in China.  
So my English is not very good, if you can speak Chinese...请跳转到页面底部阅读中文版本。。。  

## Expected Behavior
The script I installed running successful in the page.  

## Actual Behavior
It throw an error before the script loaded.  
like this:  
![image](https://github.com/user-attachments/assets/939fa7ca-dba6-44f9-b7eb-f10c7118c386)  
Then, I use a simple html page and write a simple script that only print string "test..." to the console.  
But when I open the page, it throw the error too.  
![image](https://github.com/user-attachments/assets/d82149b1-7f5d-4fe8-9d12-d5cc43908786)    
![image](https://github.com/user-attachments/assets/910999a1-dd9c-4915-8ff0-03f6ba5766d8)      
The most important is that I think the script I write may be not running!  
Because of the string I write is not print to the console.  
I am not sure this problem is bucause of  mine or the tampermonkey.  
I think it perhaps a bug of the tampermonkey,so I write this to ask for help.  
I'm very sorry to disturb you,Thank you for your answer.  

## Specifications

- Chromium: 127.0.6533.89（正式版本） （64 位）  
- TM: 4.9  
- OS: Windows 10 1809 build 17763.6054  

## Script
The test script I write:
```js
// ==UserScript==
// @name         test...
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://htfc786.github.io/maths/grid.html
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    console.log("test...");
    // Your code here...
})();
```  
The error script: 
<https://greasyfork.org/zh-CN/scripts/458087-%E5%9B%BD%E5%AE%B6%E4%B8%AD%E5%B0%8F%E5%AD%A6%E6%99%BA%E6%85%A7%E6%95%99%E8%82%B2%E5%B9%B3%E5%8F%B0-%E5%85%8D%E7%99%BB%E5%BD%95%E6%9F%A5%E7%9C%8B%E7%94%B5%E5%AD%90%E8%AF%BE%E6%9C%AC>

# Tampermonkey扩展中的content.js或许出现了bug使我的脚本无法正常运行

## 预期行为
我安装的脚本正常运行。  

## 实际行为
在我的脚本运行之前，就有程序报错了  
像这样：  
![image](https://github.com/user-attachments/assets/939fa7ca-dba6-44f9-b7eb-f10c7118c386)  
之后我就在一个简单的html页面上使用我写的一个简单的脚本做测试  
然后我打开页面之后它还是报错！  
![image](https://github.com/user-attachments/assets/d82149b1-7f5d-4fe8-9d12-d5cc43908786)    
![image](https://github.com/user-attawchments/assets/910999a1-dd9c-4915-8ff0-03f6ba5766d8)     
最重要的是，我写的脚本或许根本就没有运行，因为我这个最简单的脚本中的输出内容都没有输出到控制台上！  
我不清楚这个问题是因为我写的脚本有bug还是油猴插件本身的问题  
我想这个问题是可能是因为油猴插件的bug。。。所以提交这个issue寻求帮助。  
我非常抱歉的打扰到您，感谢您的回复。  

## 环境

- 谷歌浏览器: 127.0.6533.89（正式版本） （64 位）  
- 油猴插件版本: 4.9  
- 操作系统: Windows 10 1809 build 17763.6054  

## 脚本
我编写的测试脚本：
```js
// ==UserScript==
// @name         test...
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://htfc786.github.io/maths/grid.html
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    console.log("test...");
    // Your code here...
})();
```
出问题报错的脚本：
<https://greasyfork.org/zh-CN/scripts/458087-%E5%9B%BD%E5%AE%B6%E4%B8%AD%E5%B0%8F%E5%AD%A6%E6%99%BA%E6%85%A7%E6%95%99%E8%82%B2%E5%B9%B3%E5%8F%B0-%E5%85%8D%E7%99%BB%E5%BD%95%E6%9F%A5%E7%9C%8B%E7%94%B5%E5%AD%90%E8%AF%BE%E6%9C%AC>

**Comment by derjanb** [comment]
Please update Tampermonkey to version 5.1.1 or above.

Duplicate of #2011

**Comment by htfc786** [comment]
Thank you for you reply!The problem successfully resolved successfully！
