### ISSUE TITLE
Chrome is warning TM will be disabled!! What's happening?

### ISSUE THREAD

**Issue by jeisonfriedman** [Tampermonkey/tampermonkey#2145]
What does it mean? 

![ChromeExtensionsPage](https://github.com/user-attachments/assets/2541d8a6-d848-4f8d-82c4-3a0c1d9be160)

## Specifications

- Chromium: 127.0.6533.89
- TM: 5.5.1
- OS: Windows 10

**Comment by derjanb** [comment]
Please open ["chrome://extensions/"](chrome://extensions/), and press "Update" at the top. Tampermonkey should then update to a MV3 version.

**Comment by jeisonfriedman** [comment]
OMG! Thank you! I was scared!

**Comment by TienLenNguyenVN** [comment]
use chrome 126 and disable update or use Edge....

**Comment by derjanb** [comment]
@TienLenNguyenVN 

Please open "chrome://extensions/", enable "Developer Mode" and press "Update" at the top. Tampermonkey should then update to a MV3 version.

**Comment by ntt77** [comment]
find the Tampermonkey on webstore, the newest Tampermonkey supported MV3 must be there

**Comment by devnoname120** [comment]
@derjanb Is MV3 the reason instant mode injection is not available anymore? :(

**Comment by derjanb** [comment]
`UserScripts API Dynamic` is what you're looking for.

https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-2222196181
