### ISSUE TITLE
win11的星愿浏览器无法添加--篡改猴测试版

### ISSUE THREAD

**Issue by saludossol** [Tampermonkey/tampermonkey#2146]
安装显示“程序包无效。详细信息This extension requires Twinkstar version 120 or greater.”
![12b09d4616ffce93e07a556c6d2e0dda](https://github.com/user-attachments/assets/6593b7b6-2408-4f20-b3c0-713fe59720b1)

但是星愿浏览器为最新版本

浏览器已经是最新版本
当前版本 9.1.2000.2407 (Chromium: 119.0.6045.205) Res: (2407.622) （64 位）

**Comment by saludossol** [comment]
篡改猴版本为测试版 5.3.6206

**Comment by derjanb** [comment]
Please use [Tampermonkey Legacy](https://chromewebstore.google.com/detail/lcmhijbkigalmkeommnijlpobloojgfn) for now, but keep in mind that Chrome's support for it will end in 2025.
