### ISSUE TITLE
When setting up Nextcloud as a WebDAV synchronization target, automatic folder creation is failing, which leads to synchronization issues.

### ISSUE THREAD

**Issue by XM-8JD2** [Tampermonkey/tampermonkey#2149]
![Snipaste_2024-08-09_10-11-45](https://github.com/user-attachments/assets/6c223440-44de-40b8-972c-a5a4a19162cd)
![Snipaste_2024-08-09_10-11-54](https://github.com/user-attachments/assets/3dc77913-2ada-4335-86fe-65470e63c62e)

It appears that the `Tampermonkey` and `Tampermonkey/sync` folders are expected to be created automatically in the WebDAV file directory. However, this does not happen in Nextcloud, so I had to create these folders manually.

You might want to ask users whether they permit the automatic creation of these folders. Otherwise, these additional paths will not appear in the URL provided by the user, leading them to encounter synchronization failures without being able to resolve the issue on their own.

Using the manually created folders, the two functions in the image work correctly on my PC.

I use a link similar to this to access Nextcloud via WebDAV. `https://192.168.x.x/remote.php/dav/files/userName/Tampermonkey` This method works in Joplin, so there should not be any issues with the access itself.

---

P.S.: Can the Tampermonkeyadhere to SwitchyOmega's proxy settings? When using SwitchyOmega to connect Chrome to a proxy server, if Nextcloud is located on a local network rather than the internet, the two functions in the image will not work because the requests cannot be sent to Nextcloud.

---

chrome 127.0.6533.100
win10
Nextcloud

**Comment by derjanb** [comment]
Should be fixed at 5.3.6208 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
Thanks for reporting!
