### ISSUE TITLE
Deleting `@require` resource won't update it on reload

### ISSUE THREAD

**Issue by PRO-2684** [Tampermonkey/tampermonkey#2151]
## Expected Behavior
I can access the latest version of the required resource in the browser (in this case, the latest version can be identified by searching `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ`).

![image](https://github.com/user-attachments/assets/27db7630-7c48-4983-988d-d0270fafa76a)

I'd expect deleting that resource from Tampermonkey settings and re-activate the script would cause the resource to be refreshed.

![image](https://github.com/user-attachments/assets/4a22c540-47d4-4144-b5f7-e76b7635ae94)

## Actual Behavior
The reloaded resource is still the old version.

![image](https://github.com/user-attachments/assets/19252b87-a70c-43cf-86c8-a54bf47b949a)

This behavior cannot be reproduced using localhost, either using `Etag` or `Last-Modified` header.

## Specifications

- Chromium: `127.0.6533.100`
- TM: `5.1.1`
- OS: Windows11 23H2

## Script
[GreasyFork](https://greasyfork.org/scripts/492480)

**Comment by derjanb** [comment]
Added a refresh button at 5.3.6208 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
