### ISSUE TITLE
[Feature Request] User-Defined Script Groups

### ISSUE THREAD

**Issue by hospotho** [Tampermonkey/tampermonkey#2154]
Problem:
Managing numerous scripts (40+) is challenging, especially with multiple scripts for the same site or with similar functionality (eg 6 different youtube scripts, 10+ similar hotkey scripts for different websites).

Feature Request:
Add user-defined grouping for scripts, allowing users to:
1. Create custom groups (e.g., by site, function, or purpose)
2. On/Off/Action for the group
3. Collapse/expand groups in the script list

Benefits:
1. Improved organization and navigation
2. Faster script management
3. Enhanced user experience for advanced user / developer

**Comment by derjanb** [comment]
Duplicate of #267

Please try the latest beta.
