### ISSUE TITLE
Scripts not loading  for site yandex.ru 

### ISSUE THREAD

**Issue by LutAle** [Tampermonkey/tampermonkey#2155]
(Please fill out the issue template with your details)

## Expected Behavior

Script not been execute, TM count running script  is 0. TM icon clear without red mark  numbers running script.  
Problem for yandex.ru site

## Actual Behavior

Do normal running script and apropriate indication it 

## Specifications
Chromium:126.0.6478.183
TM: 5.1.6194 2024-03-27
WIN10: 22H2 19045.4651 

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      2024-08-11
// @description  try to take over the world!
// @author       You
// @match        *
// @icon         https://www.google.com/s2/favicons?sz=64&domain=yandex.ru
// @grant        unsafeWindow
// ==/UserScript==

(function() {
    'use strict';
     document.querySelectorAll('a[target=_blank]').forEach((el)=>el.removeAttribute('target'));

    // Your code here...
})();

**Comment by derjanb** [comment]
You have to use a valid `@match` rule:

```js
// @match        *://*/*
```
