### ISSUE TITLE
Illegal chars in GME_Download filename. How to fix generally.

### ISSUE THREAD

**Issue by Aphexus** [Tampermonkey/tampermonkey#2156]
I'm trying to download files using GM_Download and sometimes I get errors due to invalid characters. I've removed most invalid windows filename characters but these seem to be related to unicode.

Download Error: filename must not contain illegal characters for ' by 1,518.98% in latest 13F is $41,068,238 USD. � .jpg'

Note this is a "constant thing" in that it's not just that specific filename but many others. Some I hardcode a character replacement if it is obvious what the illegal character is and I can get at it. e.g., that � is 🔥or 🔥[these are different?]and my guess it is the error rather than the % and $.

What would really be amazing is if it listed the illegal characters. It clearly "knows" what they are since it is detecting the error(unless it's passing on an error).

But I can't replace or remove an illegal character if I don't know what it is and it would be nice if I could find the best legal approximation to them.

Maybe add an option to GM_Download to sanitize the filename? Again, I am heavily processing the FN to remove or change all the known illegal characters but this doesn't fix every case.

What is interesting is that if I paste🔥into a filename from windows file explorer it works but gives a BW version I guess due to the font. So these aren't technically illegal.

-----
Ok, somewhere the character is getting converted to � and if I replace on that rather than on 🔥it does pass.  I'm not sure where that is coming from but it seems to be internal to GM_download

**Comment by derjanb** [comment]
Firefox file name sanitizing is quite complex: https://searchfox.org/mozilla-central/source/uriloader/exthandler/nsExternalHelperAppService.cpp#3547

So please write your own function according to your needs.

```ts
function replaceNonPrintableAndUnicode(input: string): string {
    // Regex to match non-printable and Unicode characters
    const regex = /[^\x20-\x7E]/g;

    // Replace matched characters with "_"
    return input.replace(regex, "_");
}

// Example usage:
const input = "Hello, 世界! \u0000 \u0001";
const output = replaceNonPrintableAndUnicode(input);
console.log(output); // Output: "Hello, _! __"
```

**Comment by 7nik** [comment]
I used this regexp to exclude forbidden characters:
```js
const badChars = /[\u0000-\u001F"*/:<>?\\|\u007F\u200B]|[\u200D\uD800-\uDB7F\uDC00-\uDFFF]+|\.+\s*$/g;
let name = data.name.replace(badChars, "_").trim();
```
plus, a fallback like this
```js
try {
    await download(url, name);
} catch (ex) {
    if (ex?.error === "not_whitelisted") {
        // the extension isn't whitelisted error
    } else if (ex?.error === "not_succeeded") {
        // failed to download the file
    } else if (!("error" in ex)) {
        let newName = prompt(`Couldn't save the file "${name}" from ${url}
Seems the name contains forbbiden characters. Try to remove them.
Press Cancel to try auto-renaming.`, name);
        name = newName || name.replace(/[^\u0020-\u007F]/g, "_");
        // re-try downloading
    }
}
```
