### ISSUE TITLE
GM_xmlhttpRequest does not work anymore with required Windows Authentication

### ISSUE THREAD

**Issue by msteinic** [Tampermonkey/tampermonkey#2157]
## Expected Behavior
Website with required Windows Authentication ->
Windows Authentication needs to get passed via GM_xmlhttpRequest (as it worked in previous Tampermonkey Mv2, f.e. 5.1.1) to be able to get access to the requested file/website.

![chrome_Mv2_direct_to_https_tpmLegacy_5 1 1](https://github.com/user-attachments/assets/14568eaa-a143-47e5-afd5-d2b843db7515)

## Actual Behavior
In Tampermonkey for Mv3 (f.e. v5.2.3 and latest beta 5.3.6207) the Windows Authentication apparently does not get passed to the page/file i try to access via GM_xmlhttpRequest.
Due to that im getting a 401 unauthorized when trying to access the page/file which requires the Windows Authentication.

![chrome_Mv3_direct_to_https_tpmLatestBeta](https://github.com/user-attachments/assets/7d666075-0e04-4720-adb8-b49a61fc4b8c)

## Specifications

- Chromium: 127.0.6533.120
- TM: 5.3.6207
- OS: Windows 11

## Script

// ==UserScript==
// @name Script
// @match https://exampleWebsite.com/*
// @grant GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  method: "GET",
  url: "https://example.com/json/jsonData.json",
  responseType: "json",
  onload: function (result) {
  console.warn(result.status);
  }
});

**Comment by derjanb** [comment]
Should be fixed at 5.3.6208 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by msteinic** [comment]
Tested it in several scripts. This new version fixed the bug.
Thank you very much.
