### ISSUE TITLE
Tabview youtube no longer works

### ISSUE THREAD

**Issue by hitmonray** [Tampermonkey/tampermonkey#2159]
(Please fill out the issue template with your details)

## Expected Behavior
tabview youtube used to work (live chat, comments, etc all in tabs to the right of video)

## Actual Behavior
complete failure of youtube as a whole as of 2 days ago. Works after disabling tampermonkey

Pages barely load if it all. Video might play for a second then stop. Chat / comments never load.

started happening randomly 2 days ago. disabling tampermonkey everything works normal.

tabview youtube is the only tampermonkey script enabled.

using brave browser on windows

## Specifications

- Chromium: brave browser1.68.141

windows

## Script

Tabview youtube

script is too long, it won't let me post it here. it's just the default tabview youtube script idk where i got it from

**Comment by 7nik** [comment]
It's unrelated to TM: https://github.com/tabview-youtube/Tabview-Youtube/issues/49#issuecomment-2294924616
