### ISSUE TITLE
feedly.com is loaded very slow and highCPU with tampermonkey 

### ISSUE THREAD

**Issue by mapx-** [Tampermonkey/tampermonkey#216]
-windows XP
-chrome 43
-tampermonkey extension (3.10.109) installed and enabled in the extensions page
-tampermonkey is disabled on all pages (click TM icon and click enable/disable)

go to feedly.com ==> loading very slow, high-CPU.

**Comment by derjanb** [comment]
What page exactly or just the welcome page?

**Comment by mapx-** [comment]
https://feedly.com/i/my

**Comment by mapx-** [comment]
not only windows xp, for windows 7 it's the same issue

**Comment by tophf** [comment]
It's probably because of some userscript.

**Comment by mapx-** [comment]
As I wrote, I tested with TM disabled on all pages, so no userscript could impact.

However, now, the current version Tampermonkey 3.12.58 seems to work fine.
