### ISSUE TITLE
eslint Error "@exclude-match" is not a valid userscript header" still unsupported?

### ISSUE THREAD

**Issue by pstein** [Tampermonkey/tampermonkey#2161]
I imported a couple of Greasemonkey *.user.js scripts from Firefox into Tampermonkey on Chrome.

When I look at them the left of the lines

//@exclude-match ....

a yellow exclamation mark is show with the text:

"@exclude-match" is not a valid userscript header"

So why is @exclude-match still not supported in Tampermonkey?
@exclude-match is urgently recommended over @exclude 

How can I fix it (for ALL SCRIPTS AT ONCE) in Tampermonkey WebExt on Chrome?

Do I really have to change all *.user scripts manually to @exclude?

**Comment by derjanb** [comment]
@pstein Why should a non-standard `@exclude-match` be preferred over a standard `@exclude` that is recognized by all userscript managers?

**Comment by pstein** [comment]
> > ` @exclude-match` is urgently recommended over `@exclude`
> 
> @pstein Why should a non-standard `@exclude-match` be preferred over a standard `@exclude` that is recognized by all userscript managers?

Maybe because of this:

https://github.com/quoid/userscripts/issues/650

and this ("all major browsers and script managers support @match"):

https://github.com/quoid/userscripts/issues/649#issuecomment-2085725872

**Comment by 7nik** [comment]
> [Greasemonkey](https://github.com/greasemonkey/greasemonkey/blob/master/src/parse-user-script.js#L134) has no `@exclude-match` support either.

But VM has.

> Maybe because of this:
> 
> [quoid/userscripts#650](https://github.com/quoid/userscripts/issues/650)

Though `@exclude-match` should be a bit more performant, it doesn't increase security like `@match`.
Plus, `@match`/`@exlude-match` is less precise than `@include`/`@exclude` due to simple matching patterns.
And it doesn't make sense to get rid entirely of `@include` and `@exclude` because thousands of userscripts still use them, and nobody will update them, or it's tricky because `@match` is more coarse.

**Comment by jez9999** [comment]
It's rather annoying this isn't supported in TamperMonkey; I just switched from ViolentMonkey and some of my scripts use it.  Seems like TM could quite easily add support for it.  *shrug*
