### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'updatable')

### ISSUE THREAD

**Issue by kkmuffme** [Tampermonkey/tampermonkey#2162]
## Expected Behavior

When clicking on the icon in the "Last updated" column on `chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=dashboard` I expect the update to work. 
It does work for some scripts.

## Actual Behavior

It's showing the spinning wheel forever and console error:

```
Error handling response: TypeError: Cannot read properties of undefined (reading 'updatable')
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/extension.js:699:407
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/extension.js:782:341
```

on url `chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#url=aHredacted==&nav=dashboard`

followed by

```
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

## Specifications

- Chromium: 127 + 128
- TM: 5.1.1
- OS: Win 11

## Script
url's are redacted.

```
// ==UserScript==
// @name		Foo Bar
// @namespace	https://foo.com
// @version		1.0.0
// @description utility buttons for Foo
// @author		Foo
// @updateURL	https://sub.foo.com/bar.js
// @downloadURL	https://sub.foo.com/bar.js
// @supportURL	https://foo.com
// @match		https://bar.com/*
// @grant		none
// ==/UserScript==
```

I have another script that is basically identical, except that it has a @match for `https://*.foo.com/*` where the update works, so I know the update works in general.

**Comment by derjanb** [comment]
Thanks for reporting. Fortunately this issue is already fixed at the BETA version.
