### ISSUE TITLE
Cannot redirect/open tampermonkey extension page with JS

### ISSUE THREAD

**Issue by kkmuffme** [Tampermonkey/tampermonkey#2165]
When trying to open a link to the tampermonkey extension from JS, Chrome will display an error that the page is blocked.
When pressing F5 it loads correctly.
It seems this is due to some (mis)configuration of the tampermonkey extension, as I found a similar issue reported + resolved for another extension here: https://github.com/nwjs/nw.js/issues/6694 => https://github.com/nwjs/nw.js/issues/6631

## Expected Behavior

Display tampermonkey settings page

## Actual Behavior

Page blocked by Chrome.

## Specifications

- Chromium: 127
- TM: 5.2.3
- OS: Win 11

## Script

```
window.open( 'chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#url=&nav=dashboard', '_blank' );
```

**Comment by derjanb** [comment]
Unfortunately this is not possible.

https://stackoverflow.com/questions/38428586/open-chrome-extension-in-html
