### ISSUE TITLE
Video unavailable Playback on other websites has been disabled by the video owner Watch on YouTube

### ISSUE THREAD

**Issue by csptt** [Tampermonkey/tampermonkey#2166]
## Expected Behavior
Play video without "![error](https://github.com/user-attachments/assets/28ca7699-9314-40e2-8328-2d3fee8a80c4)", with Tampermonkey on

## Actual Behavior
When trying to play a video it comes up "Video unavailable Playback on other websites has been disabled by the video owner Watch on YouTube" When tampermonkey is off

The video at hand - https://www.youtube.com/watch?v=RGFtqhv4Hwg

## Specifications

- Edge
- OS: (Windows)

## Script
5.6

**Comment by derjanb** [comment]
Can not reproduce. Please contact the script developer...
