### ISSUE TITLE
Disable page zooming on mobile

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#2167]
(Please fill out the issue template with your details)

## Expected Behavior
The page keeps zooming in whatever I edit the script. This is annoying and unnecessary, and it makes it hard to scroll.

https://github.com/user-attachments/assets/ac30daa3-6712-4122-9bcb-d00c3b50875f

## Actual Behavior
No zooming at all

## Specifications

- Firefox 129.0.2 (Build #2016039455), hg-c6f0209c7923+
- TM: 5.1.1
- OS: Android 14

**Comment by derjanb** [comment]
Thanks for your bug report. This issue is fixed at the [BETA version](http://tmnk.net/index.php?browser=firefox).
