### ISSUE TITLE
Re-registering existing menu commands will move it to the end of the menu

### ISSUE THREAD

**Issue by PRO-2684** [Tampermonkey/tampermonkey#2175]
## Expected Behavior
When I call `GM_registerMenuCommand` with an existing `id`, that menu command should be updated in place. (as mentioned in #1865)

## Actual Behavior
The re-registered menu command appears at the end of the menu.

## Specifications

- Chromium: Edge 128.0.2739.79
- TM: 5.3.6208
- OS: Windows 23H2 22631.4169

## Script

```js
// ==UserScript==
// @name         Test GM_registerMenuCommand
// @namespace    http://tampermonkey.net/
// @version      0.1.0
// @description  try to take over the world!
// @author       PRO-2684
// @match        https://www.tampermonkey.net/*
// @icon         http://tampermonkey.net/favicon.ico
// @license      gpl-3.0
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
    'use strict';
    const total = 3;
    const cnts = [];
    function onClick(i) {
        cnts[i]++;
        GM_registerMenuCommand(`Item ${i}: ${cnts[i]}`, () => onClick(i), { id: i, autoClose: false });
    }
    for (let i = 0; i < total; i++) {
        cnts.push(0);
        onClick(i);
    }
})();
```

**Comment by derjanb** [comment]
Should be fixed at 5.3.6211 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
