### ISSUE TITLE
无法从云还原备份

### ISSUE THREAD

**Issue by Alex950808** [Tampermonkey/tampermonkey#2176]
无法从云显示备份进行还原备份操作

## Expected Behavior
点击**显示备份**能够显示备份列表，进行还原操作

## Actual Behavior
点击**显示备份**一直卡在这个界面，控制台显示如下错误，卸载重装也无法解决
![image](https://github.com/user-attachments/assets/d9926ef4-4622-42a8-a1cb-e05270f7dd28)

## Specifications

- Chromium:  Google Chrome 126.0.6478.183（正式版本） （64 位）
- TM: 5.3.6209
- OS: Windows 11

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Closed in favor of #2177
