### ISSUE TITLE
Cloud functions don't work in chrome

### ISSUE THREAD

**Issue by asgeirtj** [Tampermonkey/tampermonkey#2177]
Cloud functions don't work in chrome for me. All the buttons, export, show backups, revoke access tokens. And doesn't matter which cloud provider is selected. It just Loads endlessly and get this error in console:
![image](https://github.com/user-attachments/assets/0fa9bf2b-14ba-4302-85e4-548f1dcd02eb)

![image](https://github.com/user-attachments/assets/9adf2b6b-cbb2-44ab-a698-893d18386483)

![image](https://github.com/user-attachments/assets/423da75a-3393-4a69-96dd-4b1d80761215)

Works in Firefox though.

## Specifications

Version 129.0.6668.59 (Official Build) (arm64)
[Tampermonkey BETA](https://chromewebstore.google.com/detail/gcalenpjmijncebpfijmoaglllgpjagf) 5.3.6209
MacOS 15.1 Beta (24B5046f)

**Comment by derjanb** [comment]
Should be fixed at 5.3.6211 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by AvenCores** [comment]
> Should be fixed at 5.3.6211 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)
> 
> Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
> 
> For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

When will this fix be in the release version? I can't import my backup from Google Drive
