### ISSUE TITLE
After canceling the script installation, the page does not return. `v5.3.0`

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2180]
## Actual Behavior

After canceling the script installation operation, the installation page does not return to the original URL, but stays at `https://www.tampermonkey.net/script_installation.php#url=https://update.greasyfork.org/scripts/.....`

## Specifications

- Chromium: 129.0
- TM: 5.3.0
- OS: win10

**Comment by derjanb** [comment]
Should be fixed at 5.3.6212 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
Thanks for the fix.
