### ISSUE TITLE
Protocol-relative URLs don't get parsed correctly by GM.xmlHttpRequest

### ISSUE THREAD

**Issue by dandrei** [Tampermonkey/tampermonkey#2185]
## Expected Behavior
[Protocol-relative URLs](https://en.wikipedia.org/wiki/URL#prurl) (URLs without a protocol e.g. `//www.example.com`) fetched with `GM.xmlHttpRequest` should be resolved correctly, so either the `http` or `https` version should be retrieved, depending on the page the script is running on.

## Actual Behavior
The host part seems to be stripped completely, so starting from:

    //cdn.jsdelivr.net/npm/left-pad@1.3.0/index.min.js

The `finalUrl` that gets reported in the thrown exception is:

    https://npm/left-pad@1.3.0/index.min.js

The caught object:

    {
     "readyState": 4,
     "responseHeaders": "",
     "finalUrl": "https://npm/left-pad@1.3.0/index.min.js",
     "status": 0,
     "statusText": "",
     "responseText": "",
     "DONE": 4,
     "HEADERS_RECEIVED": 2,
     "LOADING": 3,
     "OPENED": 1,
     "UNSENT": 0,
     "RESPONSE_TYPE_TEXT": "text",
     "RESPONSE_TYPE_ARRAYBUFFER": "arraybuffer",
     "RESPONSE_TYPE_BLOB": "blob",
     "RESPONSE_TYPE_DOCUMENT": "document",
     "RESPONSE_TYPE_JSON": "json",
     "RESPONSE_TYPE_STREAM": "stream"
    }

## Specifications

- Firefox 130.0.1 
- TM 5.1.1
- Windows 10

## Script

```js
// ==UserScript==
// @name         Test
// @namespace    http://tampermonkey.net/
// @version      2024-09-30
// @description  Test
// @author       You
// @match        *
// @grant        GM.xmlHttpRequest
// ==/UserScript==


async function test() {
    'use strict';

    try {
        await GM.xmlHttpRequest({
            method: "GET",
            url: "//cdn.jsdelivr.net/npm/left-pad@1.3.0/index.min.js",
            onload: async response => {
                console.log('[GM.xmlHttpRequest] OK');
                console.log(response);
            }
        });
    } catch (e) {
        console.log('[GM.xmlHttpRequest] ERR');
        console.log(JSON.stringify(e, null, 1));
    }
}

test().catch(console.error);

```

**Comment by derjanb** [comment]
Should be fixed at 5.3.6213 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
