### ISSUE TITLE
Package invalid. Details: this extension requires chromium 120+

### ISSUE THREAD

**Issue by RedSteel-1** [Tampermonkey/tampermonkey#2186]
## Expected Behavior
Updated extension

## Actual Behavior
Stuck on 5.1.1

## Specifications

- Chromium: 108.0.0.0 (Vivaldi 5.6)
- TM: 5.1.1
- OS: Windows 7 SP1 x64

## Describe the bug

I noticed that the extension is not being updated automatically and the installed version remains 5.1.1, despite the fact that the newest version is 5.3.0.
I downloaded the latest version manually and tried to install. What I saw is in the name of the issue.

Could you fix the extension so that it installs on chromium v108?
So that Windows users can update and use the latest version.
(As you know the last chromium versions for Win7 are 108-109).

**Comment by derjanb** [comment]
Please use [Tampermonkey Legacy](https://chromewebstore.google.com/detail/lcmhijbkigalmkeommnijlpobloojgfn) for now, but keep in mind that Chrome's support for it will end in 2025.

**Comment by alexchexes** [comment]
> keep in mind that Chrome's support for it will end in 2025.

You mean, it will be deleted from the Chrome web store, but we _still_ can use it on old chrome by manually downloading and installing it, right?

**Comment by derjanb** [comment]
@alexchexes 

> it will be deleted from the Chrome web store

Probably, but one can only tell, when the time arrives, I guess.

> we still can use it on old chrome by manually downloading and installing

Yes, old Chrome browsers should install MV2 extensions as usual.
