### ISSUE TITLE
[BUG] Settings -> Editor Unable to save correct data after changing.

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#2189]
## Actual Behavior
When editing the data related to the Editor and clicking the save button, the checkbox is always saved as selected all.

![screenshot_2024-10-03_00-03-46](https://github.com/user-attachments/assets/3eb3e60e-2b22-46c3-b359-91e996fc9be6)

## Specifications

- Chromium: 129
- TM: 5.3.0 / 5.3.6212
- OS: Win10

**Comment by derjanb** [comment]
Should be fixed at 5.3.6213 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by F9y4ng** [comment]
Thanks for the fix.
