### ISSUE TITLE
GM_registerMenuCommand keypress not working

### ISSUE THREAD

**Issue by kalobkalob** [Tampermonkey/tampermonkey#2192]
(Please fill out the issue template with your details)

## Expected Behavior
Menu Item is made.
Opening menu and pressing hotkey activates code.

## Actual Behavior
Menu Item is made.
Menu hotkey input is ignored.

## Specifications
Safari 18.0.1
TM 5.3.6210
Mac OS 15.0.1

## Script

```js
// ==UserScript==
// @name         test
// @namespace    http://tampermonkey.net/
// @version      1
// @description  test.
// @author       You
// @match        https://*.fanfiction.net/*
// @icon         https://www.google.com/s2/favicons?domain=fanfiction.net

// @grant        GM_registerMenuCommand
```

**Comment by Owyn** [comment]
same with Firefox, no hotkeys work at all currently

FF: 131.0.3
TM: v5.3.1

**Comment by derjanb** [comment]
> Perhaps the latest fix for hotkeys in frames broke it?

No, this was broken when working on a fix for #2113

**Comment by derjanb** [comment]
Should be fixed at 5.3.6216 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
@kalobkalob I'll release a new Safari version soon...

**Comment by Owyn** [comment]
> 5.3.6216
> Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons`

am I too early to test firefox? 
no updates found it says, I downloaded it right off your website
![image](https://github.com/user-attachments/assets/618b1f1d-7c59-4d47-b054-b7070630de39)
it's still 6213 there (broken hotkeys)

**Comment by pehaa** [comment]
@derjanb I can confirm the issue also in Chrome (Version 130.0.6723.70 (Official Build) (arm64))
Strangely, the keypress works when Caps Lock is on 🤔

**Comment by derjanb** [comment]
> am I too early to test firefox?

@Owyn 5.3.6216 is available now. 😅

Review in 4 days. That was fast. 🚀

**Comment by Owyn** [comment]
Firefox works now 👍🏻

**Comment by kalobkalob** [comment]
After reviewing it, looks like lower case works just fine which is sufficient at this point. However, both shift and caps lock both prevent it from firing. Feels like it should default to case insensitivity with the option to be case sensitive although any caps doesn't work. Feels like I'd be alright with closing this one but it's still an issue that should be further fixed.
