### ISSUE TITLE
HP Chromebook Remotely Managed Without My Permission - FLOSS Disabled.

### ISSUE THREAD

**Issue by janeofmany** [Tampermonkey/tampermonkey#2202]
My HP Chromebook appears to be remotely managed without my permission. New to code, I have my computer in dev mode and am going through the process to un-fuck my computer and free it from OS after actory resettings. As an Intel processor, my device has Linux pre-installed but I don't see it's full potential unlocked at this time.

For you experts out there, help me understand what about the below script isn't stock, how to remove it, and WHY there's a Google Enterprise or some odd overlord *all up in my database* on multiple devices. STARTING WITH THIS ONE - I want out of Chrome/Google altogether. I am on Dev mode, but Linux is too large for my files @ 4G and nearly full. 

I have a DropBox - USB is not an option at this time. 

## Expected Behavior
Free code - open source browsing so that I can install and use Windows and get out of Google

## Actual Behavior
Monitored, security hacked, biased web searches, with all my passwords compromised. 

## Specifications

Blooguard version 131.16063.0
Intel (R) Celeron (R) N4120 CPU @ 1.10 Gl-z (4 threads, 2.60 GHz)

TAKEN FROM DEVICE INFO- 

Google Chrome131.0.6778.0 (Official Build) dev (64-bit) 

Revision24f4010b9bd3b881979bcfdf47fe58767541d118-refs/branch-heads/6778@{#1}

Platform16063.2.0 

(Official Build) dev-channel octopusFirmware VersionGoogle_Bloog.11297.440.0Customization IDblooguardARC12489862 

SDK Version: 33JavaScriptV8 13.1.201User AgentMozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

COMMAND LINE-

/opt/google/chrome/chrome --enable-native-gpu-memory-buffers --enable-webgl-image-chromium --enable-features=Pepper3DImageChromium,UmaStorageDimensions,ArcAdbSideloading,Crostini,SmartDim,OnDeviceSpeechRecognition --gpu-sandbox-failures-fatal=yes --gpu-sandbox-start-early --video-capture-use-gpu-memory-buffer --disable-features=FlossIsAvailable --enable-logging --log-level=1 --use-cras --enable-wayland-server --user-data-dir=/home/chronos --defer-external-display-timeout=0 --extra-web-apps-dir=blooguard --system-developer-mode --disable-mojo-broker --ash-use-cros-mojo-service-manager --cros-healthd-uses-service-manager --login-profile=user --has-chromeos-keyboard --enable-touchview --form-factor=CHROMEBOOK --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/hp_default_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/hp_default_small.jpg --default-wallpaper-is-oem --device-help-content-id=blooguard --ozone-nnpalm-properties={} --arc-availability=officially-supported --enable-arcvm --arc-erofs --enable-houdini --enable-houdini64 --enterprise-enrollment-initial-modulus=15 --enterprise-enrollment-modulus-limit=19 --ml_service=enabled --ondevice_handwriting=use_rootfs --ondevice_document_scanner=use_rootfs --feature-management-level=0 --feature-management-max-level=1 --feature-management-scope=0 --login-manager --first-exec-after-boot --enable-features=ArcAdbSideloading,Crostini,OnDeviceSpeechRecognition,Pepper3DImageChromium,SmartDim,UmaStorageDimensions --disable-features=FlossIsAvailable --flag-switches-begin --flag-switches-end

and thennnnn....... hundreds of variations in number lists

"a stranger, signaling to you from the void in which we are foundering"
-Baby Reindeer
HELP!

**Comment by derjanb** [comment]
Not related to Tampermonkey. Closing...
