### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Tcspy34** [Tampermonkey/tampermonkey#2204]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
![Ekran Alıntısı](https://github.com/user-attachments/assets/2dbdc3b4-c5b8-47c9-893e-622a6788ccc8)
Are you the owner of the tampermonkey plugin? Please tell me how to remove the plugin developer mode force for selenium c#
```

**Comment by Luckz** [comment]
Use the manifest v2 version if you don't like manifest v3 https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn

And wtf is that post.

**Comment by derjanb** [comment]
Yes, please use [Tampermonkey Legacy](https://chromewebstore.google.com/detail/lcmhijbkigalmkeommnijlpobloojgfn) for now, but keep in mind that Chrome's support for it will end in 2025.


refs: #2146
