### ISSUE TITLE
Tampermonkey no longer working on Brave browser

### ISSUE THREAD

**Issue by ochompsky** [Tampermonkey/tampermonkey#2207]
(Please fill out the issue template with your details)

## Expected Behavior
Scripts should execute

## Actual Behavior
No scripts appear to be detected at all

## Specifications

Brave (chromium) 1.71.114
TM: 5.0.1
MAC 15.0.1

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Old Reddit Redirect
// @namespace    https://pelican.gq/
// @version      1.0.0
// @description  Automatically redirects you to the old reddit
// @author       sk1pp3rFTW
// @match        https://www.reddit.com/*
// @match        https://reddit.com/*
// @grant        none
// @run-at       document-start
// @downloadURL https://update.greasyfork.org/scripts/377047/Old%20Reddit%20Redirect.user.js
// @updateURL https://update.greasyfork.org/scripts/377047/Old%20Reddit%20Redirect.meta.js
// ==/UserScript==

(function () {
	'use strict';
	top.location.hostname = "old.reddit.com";
})();

```

Above is an example script, it doesn't execute at all on reddit.  Even if I remove the matchers, tampermonkey shows no script running.  All permissions are given to Brave. Script is enabled.

**Comment by derjanb** [comment]
Tampermonkey 5.0.1 is quite old. Please update. [Tampermonkey 5.3.1](https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) and [TM Legacy 5.1.1](https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn) are working fine here with Brave version 1.71.114

**Comment by AkyunaAkish** [comment]
I was having this issue too even on the newest versions (I tried up to `v5.3.6223` - Brave version `[Version 1.73.104 Chromium: 131.0.6778.204 (Official Build) (arm64)](https://brave.com/latest/)`)

My workaround is:
1. Type `brave://extensions` in the browser URL bar and hit enter
2. Toggle on "Developer mode" in the top right of the page
3. Click the "Update" button in the top left area 
4. Refresh the page you need the Tamper Monkey script to work and it `should` hopefully work! 

<img width="1225" alt="Screenshot 2024-12-19 at 12 51 59 PM" src="https://github.com/user-attachments/assets/032d6757-354a-4a2c-a883-039a7f8b5bb4" />

**Comment by Hash-D25** [comment]
yeah this works :+1:

**Comment by AkyunaAkish** [comment]
I ran into this issue again when reinstalling tamper monkey. In addition to what I said above, also you can scroll down to toggle on other needed settings:

<img width="1909" height="720" alt="Image" src="https://github.com/user-attachments/assets/ef1b4dbf-4694-4533-814d-69d4a25b03ef" />

Then press the "Update" button in the top left area then refresh the page you need the Tamper Monkey script to work on and it should work!

**Comment by whtepony** [comment]
Bump, still doesn't work.

I've enabled Developer, even updated nothing works.

**Comment by derjanb** [comment]
If you're using [Tampermonkey 5.3.3](https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo), then make sure "Allow UserScripts" is enabled at the extension settings at newer Brave versions, while "Developer Mode" needs to enabled at older Brave versions.

> <img width="1909" height="720" alt="Image" src="https://github.com/user-attachments/assets/ef1b4dbf-4694-4533-814d-69d4a25b03ef" />

**Comment by matthew-fornear** [comment]
> If you're using [Tampermonkey 5.3.3](https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo), then make sure "Allow UserScripts" is enabled at the extension settings at newer Brave versions, while "Developer Mode" needs to enabled at older Brave versions.
> 
> > <img alt="Image" width="1909" height="720" src="https://private-user-images.githubusercontent.com/11621938/463849848-ef1b4dbf-4694-4533-814d-69d4a25b03ef.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1MzYxNTYsIm5iZiI6MTc2NDUzNTg1NiwicGF0aCI6Ii8xMTYyMTkzOC80NjM4NDk4NDgtZWYxYjRkYmYtNDY5NC00NTMzLTgxNGQtNjlkNGEyNWIwM2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTMwVDIwNTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhN2YwYWE3NjBlZWNjNjViZWU1YzkyNGJkYWIwMjQ3ZjZjZjRiNDJhYzU5N2U5ZTFlYWVmZDZmZGI5OGJmMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dRk7RO_XRaR2yivig93c0wNB0UwfN7mtnH4tFSxSzD8">

this plus pkill -f brave or you wont see a result
