### ISSUE TITLE
When using El País - CLEANED PAGE & Sin Límite de noticias, there is always a red point alarming me

### ISSUE THREAD

**Issue by Sara0329** [Tampermonkey/tampermonkey#2222]
(Please fill out the issue template with your details)

## Expected Behavior
See vip texts in El Pais without block.

## Actual Behavior
When using El País - CLEANED PAGE & Sin Límite de noticias, there is always a red point alarming me
![image](https://github.com/user-attachments/assets/8f09b7f9-b689-4efc-990c-f2f00a89363f)
You can see that I've actived the program but the result is that the vip block always exists.
![image](https://github.com/user-attachments/assets/d4e8a949-678f-47c2-b827-a3eda35cb837)
I use the Chrome.
So how to solve this problem? It seems like something in the Chrome prohibit the function of this program.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please set "Icon badge info" from "All-time running instances" to "Disabled".
