### ISSUE TITLE
Why does the script editor behave like this on mobile?

### ISSUE THREAD

**Issue by rthfhgyhy567** [Tampermonkey/tampermonkey#2233]
Version 5.1.1 legacy and Latest version of Kiwi Browser

The script editor has some serious issues.  One, is that you cannot "select all" and delete or cut the existing template in order to conveniently paste code over it.  If I get my script from AI or from a DM, I have to save it into a file and then use the import utility to do so.  This editor makes it so that I have to delete line by line of the existing template before pasting the code, but even then, causes permanent line breaks that can't be removed either.

It reminds me of how the text editor for custom filters in uBlock work.

Please fix this by making the editor function like a normal text editor with none of these quirks.  I make scripts that I only use on mobile and these quirks are so annoying that I end up procrastinating on them because it's too much of a hassle to have to use a _normal_ text editor to code and reinstall the new version using a utility for every time I make a revision that involves anything more than changing a few characters. 

https://youtu.be/z_iPryCfRgw

**Comment by derjanb** [comment]
Please set config mode to "Advanced", then disable "Editor" > "Enable enhanced editor".
