### ISSUE TITLE
All userscripts gone after Firefox refresh/reinstall (profile was backed up)

### ISSUE THREAD

**Issue by Max-Pare** [Tampermonkey/tampermonkey#2238]
I have regular backups for my entire Firefox profile (%appdata%\Mozilla\Firefox\Profiles\[etc.])
I do not have any backup made directly from the TM interface (txt, zip, etc.)
I reinstalled Firefox and I'm not able to restore my Tampermonkey userscripts. I tried restoring all the "moz-extension+++{id}" directories to new profile generated by Firefox after the refresh, as well as replacing every current file with the backup ones, but TM still doesn't show my userscripts.

The data is there, I dumped the .sqlite database for TM and the scripts are there but they are encrypted and/or compressed.

- Firefox 132.0.1
- TM: v5.3.2
- OS: Windows 11

**Comment by derjanb** [comment]
I'm sorry, but I can't do more than forwarding you to the official Firefox documentation how to restore a profile:
https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles

If this doesn't help Firefox maybe archived some data:
https://www.reddit.com/r/firefox/comments/1e0onek/comment/lenee06/

Tampermonkey just uses the API offered by Firefox and saves your scripts via this API.
