### ISSUE TITLE
Documentation for GM_xmlhttpRequest does not include all supported HTTP methods

### ISSUE THREAD

**Issue by bdr99** [Tampermonkey/tampermonkey#2239]
The documentation for [GM_xmlhttpRequest](https://www.tampermonkey.net/documentation.php#api:GM_xmlhttpRequest) lists GET, HEAD, and POST as the only values that can be passed in for the `method` property. But other methods like PUT and DELETE seem to work fine. Can this documentation be updated so it doesn't state that GET, HEAD, and POST are the only compatible methods?

## Expected Behavior
Documentation should list all possible methods.

## Actual Behavior
Documentation only lists GET, HEAD, and POST.

## Specifications
N/A - documentation issue

## Script
N/A - documentation issue

**Comment by derjanb** [comment]
Fixed. Thanks for reporting.
