### ISSUE TITLE
Some question `GM.getResourceURL` and `GM.getResourceUrl`

### ISSUE THREAD

**Issue by WhiteSevs** [Tampermonkey/tampermonkey#2249]
(Please fill out the issue template with your details)

## Expected Behavior

`GM.getResourceURL`

## Actual Behavior

`GM.getResourceUrl`

## Specifications

- Chromium: (i.e. 131.0.2903.51)
- TM: (i.e. 5.3.6216)
- OS: (i.e. Window 11)

## Script

文档中该Api是以`URL`结尾，而实际的Api是`Url`，这或许是文档里写错了？

[https://www.tampermonkey.net/documentation.php?ext=gcal&version=5.3.6216#api:GM_getResourceURL](https://www.tampermonkey.net/documentation.php?ext=gcal&version=5.3.6216#api:GM_getResourceURL)

![PixPin_2024-11-18_20-06-40](https://github.com/user-attachments/assets/c35f139f-27ac-4975-adf9-0448e64c8906)

**Comment by 7nik** [comment]
It is `GM_getResourceURL` and `GM.getResourceUrl`, plus `GM_xmlhttpRequest` and `GM.xmlHttpRequest`. But the docs should warn about the names difference.

**Comment by derjanb** [comment]
> But the docs should warn about the names difference.

Fixed. Thanks @7nik
