### ISSUE TITLE
"Limited runtime host permissions" in chrome 131.0.6778.69

### ISSUE THREAD

**Issue by crashvb** [Tampermonkey/tampermonkey#2250]
## Expected Behavior

Runtime host permissions are available when running with developer mode enabled. No banner is displayed. Scripts work.

## Actual Behavior

A yellow banner is displayed under the extension context menu: `Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!`

Toggling on / off developer mode has no effect. Including restarting TM via `TM > Dashboard > Settings`, nor on `chrome://restart` + page refresh.

## Specifications

- Chromium: 131.0.6778.69
- TM: 5.3.2
- OS: Linux Mint 20.1

## Script

N / A

**Comment by derjanb** [comment]
Developer mode is not related to this.

Tampermonkey warns that it does not have access to all URLs, which might break or complicate some features.

![image](https://github.com/user-attachments/assets/eebc5258-fc9e-44f7-9c1a-0ceda39a3cc7)

**Comment by crashvb** [comment]
Thank you for the response.

I've changed the setting as pictured above; however, simple things like importing scripts are not working (i.e. `https://www.tampermonkey.net/script_installation.php#url=...` is not working / closing). The following error is displayed across the top of the page:

`Apps, extensions, and user scripts cannot be added from this website`

**Comment by derjanb** [comment]
Hmm, this sounds strange. Please backup your scripts (you might want to include Tampermonkey's config as well) and re-install the extension or try a new temporary browser profile first.

**Comment by crashvb** [comment]
Yeah, it was all working before, then I restarted chrome to finish an update and  ... plop ... nothing's working. I tried a new profile and a fresh install but it's still not able to install scripts w/o downloading first. For the scripts (if I import them manually), I did some more digging, and it looks like it's the `GM_xmlhttpRequest` that's failing.

**Comment by crashvb** [comment]
I think I may have found the issue. The scripts in use were published from a jailed httpd instance exposed on the loopback address, _and_ they consumed APIs from the same endpoint. It would appear that `https://localhost:1234` is no longer accessible by the extension, nor by the scripts ...

e.g.:
```
<tampermonkey> -- fetch script --> https://localhost:1234/static/script.user.js
<user script> -- @require --> https://localhost:1234/static/{css,libs}
<user script> -- GM.xmlHttpRequest --> https://localhost:1234/service/api
```

... Once I bound the httpd instance to a non-loopback interface everything started working =/.

I did a cursory search and found #1329, implying that this should be supported; would this be considered a regression?

**Comment by derjanb** [comment]
Accessing localhost should always work. This, however, can't really be related to the "Limited runtime host permissions" warning.
