### ISSUE TITLE
ttrock bot does not work

### ISSUE THREAD

**Issue by labmaster666** [Tampermonkey/tampermonkey#2254]
it just does not work at all and it is a bug

```

**Comment by 7nik** [comment]
It's wrong place, you should ask it in [ttrockstars-bot](https://github.com/jibstack64/ttrockstars-bot) repo, though there are a bunch of such issues.

**Comment by derjanb** [comment]
> It's wrong place, you should ask it in [ttrockstars-bot](https://github.com/jibstack64/ttrockstars-bot) repo, though there are a bunch of such issues.

Yes. Thanks @7nik
