### ISSUE TITLE
TM popup window in Safari doesn't scroll

### ISSUE THREAD

**Issue by llity** [Tampermonkey/tampermonkey#2256]
macos
![image](https://github.com/user-attachments/assets/ce22fba2-e42a-455a-91d2-03e1c57cc937)

**Comment by derjanb** [comment]
What is your Tampermonkey and Safari version?

**Comment by rongpengli** [comment]
I have a different bug at Safari of iPadOS 15.2 Safari with the latest Tampermonkey. In my case, the tampermonkey popup window keep circling without any result.

**Comment by derjanb** [comment]
The scroll issue should be fixed in 5.3.6220
