### ISSUE TITLE
Some scripts can be used in the beta version, but cannot be used in the official version!

### ISSUE THREAD

**Issue by Whys8182** [Tampermonkey/tampermonkey#2257]
Some scripts can be used in the beta version, but cannot be used in the official version, for example:
https://greasyfork.org/zh-CN/scripts/432415-onedrive-%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E7%9B%B4%E9%93%BE
This has been a long time since I last saw this question, and I hope it can be fixed. I hope to get the Tampermonkey plugin for iOS/iPadOS!

**Comment by derjanb** [comment]
> Some scripts can be used in the beta version, but cannot be used in the official version

Probably related to HttpOnly cookies... Please see https://github.com/Tampermonkey/tampermonkey/issues/465#issuecomment-2479061865

> I hope to get the Tampermonkey plugin for iOS/iPadOS!

Sure, you can request a promo code at https://tmnk.net/promo.php

**Comment by Whys8182** [comment]
Thank you. I have applied for a promotional code through this feedback interface, but have not received any response. Is there a feedback result?

**Comment by derjanb** [comment]
What is your promocode ID?

**Comment by Whys8182** [comment]
f58dd1d5-87c5-4a50-b8cf-c3d5f379a1d5
________________________________
发件人: Jan Biniok ***@***.***>
发送时间: 2024年11月22日 1:44
收件人: Tampermonkey/tampermonkey ***@***.***>
抄送: Whys8182 ***@***.***>; Author ***@***.***>
主题: Re: [Tampermonkey/tampermonkey] Some scripts can be used in the beta version, but cannot be used in the official version! (Issue #2257)


What is your promocode ID?

―

**Comment by derjanb** [comment]
To be honest: I don't know. However, the app works on macOS and iOS, so the promo code should work for both.

**Comment by Whys8182** [comment]
First of all, I am very grateful for your help. I wonder if the possibility you mentioned can be solved in the official version, and whether this script can run normally in Safari?
In addition, I have two scripts, I hope you can help me check them, and in the future, I hope they can run normally through Safari, including iOS/IPados and macOS:
The first one is "115 Big Assistant (full)":
Link address:
https://greasyfork.org/zh-CN/scripts/474231-115%E4%B8%8D%E5%A4%A7%E5%8A%A9%E6%89%8B-full
The second one is "OneDrive SharePoint File Batch Download"/"OneDrive File download direct link":
Link address:
https://greasyfork.org/zh-CN/scripts/502807-onedrive-sharepoint-%E6%96%87%E4%BB%B6%E6%89%B9%E9%87%8F%E4%B8%8B %E8%BD%BD
https://greasyfork.org/zh-CN/scripts/432415-onedrive-%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E7%9B%B4%E9 %93%BE

In fact, I can't tell which one of the second scripts has the problem.

**Comment by derjanb** [comment]
Please contact the script developers. They can debug things much faster, and probably have accounts there already.
They can also get a promocode if needed...

**Comment by Whys8182** [comment]
I will try to contact the developer. In addition to these scripts, I have another request. Please be sure to add a Chinese mode to this tampermonkey application. Although many users can understand it, I still hope it can support Chinese. Because there are a large number of Chinese users using your product. If necessary, I can also help translate it.
________________________________
发件人: Jan Biniok ***@***.***>
发送时间: 2024年11月22日 2:12
收件人: Tampermonkey/tampermonkey ***@***.***>
抄送: Whys8182 ***@***.***>; Author ***@***.***>
主题: Re: [Tampermonkey/tampermonkey] Some scripts can be used in the beta version, but cannot be used in the official version! (Issue #2257)


Please contact the script developers. They can debug things much faster, and probably have accounts there already.
They can also get a promocode if needed...

―

**Comment by derjanb** [comment]
The web extension itself already should use Chinese, if the browser is configured to use it as primary language. Otherwise it can be configured at the settings page.
Only the application needs to be translated, which is at my TODO list. :-)

**Comment by Whys8182** [comment]
When I tried to check it, I found that it did have a simplified Chinese translation in the plugin settings, but it didn't seem to automatically match the device language of my iPad (my device is simplified Chinese, just for the US region). Even if I manually set its language, it was still not fully translated, for example, in "System Tags", the five options are still in English. And in the little monkey's dialog box, except for the word "disable", the other descriptions are still in English.

**Comment by derjanb** [comment]
> it didn't seem to automatically match the device language 

Should be fixed in 5.3.6220

> Even if I manually set its language, it was still not fully translated

You can add translations here: https://github.com/Tampermonkey/tampermonkey-i18n
