### ISSUE TITLE
Can't grant cross origin permissions (button does nothing)

### ISSUE THREAD

**Issue by adapowers** [Tampermonkey/tampermonkey#2263]
(Please fill out the issue template with your details)

## Expected Behavior
I would expect that when a script relies on an external dependency, I get a CORS permission request with the options "OK" and "Cancel", and clicking "OK" will grant the permission and dismiss the page.

## Actual Behavior
Clicking does nothing. When I open the console, I see:
"Error: Invalid call to permissions.request(). The 'permissions' value is invalid, because an object is expected."

## Specifications

- Safari: 18.1
- TM: 5.3.6219
- OS: Sequoia 15.1

## Script

Several; literally any that require an external dependency.

**Comment by derjanb** [comment]
Should be fixed at 5.3.6220
