### ISSUE TITLE
Can't open dashboard on Safari iPadOS

### ISSUE THREAD

**Issue by derjanb** [Tampermonkey/tampermonkey#2264]
I have a different bug at Safari of iPadOS 15.2 Safari with the latest Tampermonkey. In my case, the tampermonkey popup window keep circling without any result.

_Originally posted by @rongpengli in https://github.com/Tampermonkey/tampermonkey/issues/2256#issuecomment-2496508623_

**Comment by derjanb** [comment]
I've seen this when Safari asks for a host permission and the page is navigated away.

In my case it helped to "minimize" Safari (e.g view the desktop) and open it again. It then successfully asked for permission to access a given URL.

Does this help in your case?

**Comment by rongpengli** [comment]
Unfortunately, I tried to minimize Safari when TM asked for permission. But it does not help. I notice that the setting tab can not be load as well.

**Comment by derjanb** [comment]
Does the settings page open if opened via:

Settings -> Safari -> Extensions -> Tampermonkey, Settings

**Comment by rongpengli** [comment]
It opens a blank page — the setting page does not render correctly.

**Comment by derjanb** [comment]
Is there a chance to update? All other issues (#2271, #2260) could be resolved by updating Safari.

**Comment by rongpengli** [comment]
Currently, I don't want to do that -- the update may make the old iPad run too slowly.

**Comment by derjanb** [comment]
Well then I'm kind of sorry. From my point of view this is a Safari issue, which only can be fixed by an update.
