### ISSUE TITLE
Wrong Display of Number of Scripts and it keeps increasing

### ISSUE THREAD

**Issue by TheMasterOfMadness** [Tampermonkey/tampermonkey#2265]
(Please fill out the issue template with your details)

## Expected Behavior
So the number of scripts enabled should be 12 based on the screenshot but when I freshly open the page it says 21. Within a few clicks it changes to 25.
![image](https://github.com/user-attachments/assets/2eafb30c-1919-455b-aead-d30f15fbedaa)

## Actual Behavior
Then moving further, if I keep using the website and performing actions on it, I have seen it reach to 50+ at times and reverts back to 21 if I refresh the entire page.

## Specifications

- Firefox 132.0.2 (64-bit)
- TM 5.3.2
- OS: (i.e. Windows 11 Pro 24H2)

**Comment by derjanb** [comment]
Please set "Logging Level" to "Debug" and check the page console what script is executed at what embedded frame.

You can also set "Icon badge info" from "All-time running instances" to "Unique Running Scripts".

**Comment by TheMasterOfMadness** [comment]
Thank you for the prompt response. I've made those changes. Icon does display correctly now. I'll pay attention to the execution of scripts as well, like you pointed out. Appreciate the help.

**Comment by realyukii** [comment]
So, the number on the red square is incremented each time the script is executed? I thought it was telling me how much the user script was enabled on the current page, but it seems I misunderstood it.

![Image](https://github.com/user-attachments/assets/00769934-324f-4116-ac93-39dcb3f52914)

I'm not sure why the same userscript is executed over and over at the same page ten times, how I can identify the cause of this behaviour?

related: [discussion](https://github.com/Tampermonkey/tampermonkey/discussions/2355)

**Comment by derjanb** [comment]
Simply add this to your script to check which frame is loaded multiple times...

```
console.log(location.href)
```
