### ISSUE TITLE
[Feature Request] Make "Content Script API" a per-script configuration

### ISSUE THREAD

**Issue by myocytebd** [Tampermonkey/tampermonkey#2266]
"Content Script API"=Dynamic or not results in different behavior.  
This is a problem because the setting is global. It effectively breaks the backward compatibility when affected.

I think it should be possible to run different modes for different url/tab.  
Or maybe it is possible to run each script with different mode.
Or maybe it is possible to enable two extension instances to host scripts with different modes.

So I would suggest to support different "Content Script API" mode at a finer grade, either per-url or per-script.
- Each userscript can set a mode preference; (default to [non-dynamic?])
- Given a webpage:
  * If per-script mode is supported or scripts do not have mode confliction, use the mode preference.
  * If per-script mode is unsupported and scripts have mode confliction , log a warning and use [dynamic?].
This way script maintenance would be simpler.

**Comment by derjanb** [comment]
Please check [`@sandbox` ](https://www.tampermonkey.net/documentation.php#meta:sandbox)
