### ISSUE TITLE
window.external.Tampermonkey.isInstalled returns results even after script is deleted from TM

### ISSUE THREAD

**Issue by JasonBarnabe** [Tampermonkey/tampermonkey#2267]
1. Visit https://greasyfork.org/en/scripts/1-greasemonkey-tampermonkey-violentmonkey-test-style (or any script you have never installed).
2. Click "Install this script", complete TM's UI to install it.
3. Reload the Greasy Fork page. Note that the page now says "Reinstall version x.y.z".
4. Delete the script from TM.
5. Reload the Greasy Fork page.

## Expected Behavior

Page's button says "Install this script" again.

## Actual Behavior

Page still says "Reinstall version x.y.z". Behaviour persists even after restarting the browser.

## What Greasy Fork is doing

Greasy Fork is using `window.external.Tampermonkey.isInstalled` to determine the currently installed version of the script and updating the button's text accordingly. It seems like this is still returning the script's version even after it is deleted from Tampermonkey.

https://github.com/greasyfork-org/greasyfork/blob/6426a11783c8a507c5e1fe05997e0b9ff1349b21/app/javascript/versioncheck.js#L6-L16
https://github.com/greasyfork-org/greasyfork/blob/6426a11783c8a507c5e1fe05997e0b9ff1349b21/app/javascript/managers.js#L1-L3

## Specifications

- Firefox 132.0.2
- TM: 5.3.2
- OS: Ubuntu 24.04.1

**Comment by derjanb** [comment]
It seems that the API list scripts that are in the trash. Will be fixed in the next version.

**Comment by derjanb** [comment]
Should be fixed at 5.3.6221 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
Fixed at 5.3.3. Thanks for reporting.
