### ISSUE TITLE
Developer mode is needed to communicate via `window.external.Tampermonkey`

### ISSUE THREAD

**Issue by JasonBarnabe** [Tampermonkey/tampermonkey#2268]
1. Visit https://greasyfork.org/en/scripts/1-greasemonkey-tampermonkey-violentmonkey-test-style (or any script on Greasy Fork) with Chrome.
2. Click the green install button

## Expected Behavior

Immediately open Tampermonkey's UI. This works in Firefox.

## Actual Behavior

Greasy Fork opens a "how to install user scripts" modal. This is because Greasy Fork is not able to detect that Tampermonkey is installed, as `window.external.Tampermonkey` is undefined.

(Note that you can bypass this check by following the "I already have..." link, after which point Greasy Fork won't open that modal again.)

## Specifications

- Chrome: 131.0.6778.85 
- TM: 5.3.2
- OS: Ubuntu 24.04.1

**Comment by derjanb** [comment]
You need to enable "Developer Mode" to make it work first. Besides this, it is working fine here.
Was this the issue?

**Comment by JasonBarnabe** [comment]
Yes, once Developer Mode is enabled, it works.

**Comment by derjanb** [comment]
Fixed at 5.3.3. Thanks for reporting.
