### ISSUE TITLE
not getting any response while clicking on popup menu for iOS 

### ISSUE THREAD

**Issue by mehash6** [Tampermonkey/tampermonkey#2271]
hi. I am having an issue with the extension popup menu, on iPhone running iOS 18.0.1.

## Expected Behavior
the popup menu shows up after clicking the extension from reader menu. it should render the list of installed scripts and their respective settings

## Actual Behavior
I do not get any response after clicking the menu items, except enable/disable
the installed scripts are not visible even though the scripts are enabled

I followed these steps to finally access the dashboard : Settings -> Safari -> Extensions -> Tampermonkey, Settings

the dashboard shows up on any profile but the default profile.

upon restoring scripts using a back up, I would close the dashboard page and follow the same steps to access it again, and the scripts disappear.

## Specifications
- Safari: Version 18.0.1 
- Tampermonkey v5.3.6220

**Comment by caffeinatedwater** [comment]
I'm having the same issue on macOS. The popup menu buttons don't work, and it's not showing the list of running scripts (which I can't access their settings because of it).

macOS 14.7
Safari 18.0.1
Tampermonkey 5.3.6220

**Comment by derjanb** [comment]
@caffeinatedwater Please check #2260 if you see the same error or create a new one, because this one is for iOS. Thanks.

**Comment by mehash6** [comment]
Updated to iOS 18.1.1 and the issue has been resolved

**Comment by caffeinatedwater** [comment]
Ok, updated my macOS to 14.7.1 and Safari to 18.1.1 and the issues are gone as well. Seems like the person on the macOS thread also got it resolved after updating macOS. Thanks for the replies.
