### ISSUE TITLE
iOS version’s database will always being wiped by Safari

### ISSUE THREAD

**Issue by gugu-hw** [Tampermonkey/tampermonkey#2274]
## Expected Behavior
Scripts and settings will remain

## Actual Behavior
Every time when launching Safari, the extension will indicate that the browser has wiped the extension database, resulting a total loss of extension data

## Specifications
OS: iPadOS 18.1.1
Extension version latest on App Store 5.3.6220

**Comment by gugu-hw** [comment]
Supplement: It’s not every time opening Safari. Every time refreshing the extension page will result in a database wipe, even in same Safari launch.

https://github.com/user-attachments/assets/46662963-415b-4038-a3d4-041dcbea10ee

**Comment by derjanb** [comment]
This happens when the extension storage is cleared -> "Clear Storage" at the Safari extension settings.
Please close your browser completely (by swiping it out of the open app overview screen). The message should then disappear.

![image](https://github.com/user-attachments/assets/ff8af321-0d89-4665-926c-c4c741e9ec91)

**Comment by gugu-hw** [comment]
Things are quite different, at least on my device. First, the plugin will be automatically disabled in settings after some time. Second, although I installed a script, there is no “Clear Storage” button available in settings. Third, although every refresh will encounter the popup message, but the script will not be deleted every refresh. But it will be deleted after some time (about dozens of minutes). All in all, the data loss in my device is always but can’t find a particular way to reproduce until now (but just put it there for about an hour, then the data will be deleted for sure, and for pages that loaded the script but haven’t refresh, the plugin popup menu will say “script deleted”. So the plugin here is totally unusable. Glad to help with any debugging.

**Comment by gugu-hw** [comment]
It’s just 10 minutes that the plugin has been wiped and the scripts are all lost.
https://github.com/user-attachments/assets/c06a8291-154b-4af1-95a7-b155fbd3dadc

**Comment by derjanb** [comment]
There [was a bug in Safari](https://forums.developer.apple.com/forums/thread/764057) that wiped the extension database when updating iOS, but this should be fixed.

The problem, that the storage is wiped in different intervals makes me think, that Tampermonkey is unable to store data at all. Internally a cache is used, which is re-initialized when the background page is started. 

So if this is correct, then you should be able to reproduce data-loss at a rate of 100% by reboot your iPad. Do you see this?
If so, please uninstall Tampermonkey. Reboot, and re-install it. Maybe the extension database is somehow corrupted and can be refreshed, by reinstalling Tampermonkey.

**Comment by gugu-hw** [comment]
Yes, rebooting can 100% reproduce data loss. I reinstalled, and find that it seems to be working. First, I finally see the clear storage option in settings. Second, backup restore is now functioning (not working before). Third, refreshing will no longer trigger the database wipe alert. I will keep monitoring and will comment below if another data loss happened.

**Comment by derjanb** [comment]
Thanks for trying out! And yes, please comment if the issue appears again.
