### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by cyber-sec0** [Tampermonkey/tampermonkey#2275]
## Expected Behavior

I can sign in using SSO or MS 365.

## Actual Behavior

I can't do that using an organization email on Onedrive.

**Comment by derjanb** [comment]
Only personal account can login to onedrive.live.com.

https://answers.microsoft.com/en-us/msoffice/forum/all/cant-login-to-livecom-using-my-office-email-that/b558134a-0845-4ec6-bd04-c30585c5fa84

Related: #2243

**Comment by cyber-sec0** [comment]
I was hoping that simply changing the URL would work and adding oauth after would show the permissions screen, so I tried doing that manually but it didn't work.

I think that this may also be related to some kind of configuration that you did on your end, that I can't change.

Technically it should work.

Does MS not allow login pages like the one below?
[](https://login.microsoftonline.com/common/oauth2/authorize?client_id=00000002-0000-0ff1-ce00-000000000000&redirect_uri=https%3a%2f%2foutlook.office365.com%2fowa%2f&resource=00000002-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&scope=openid&msafed=1&msaredir=1&client-request-id=8649c0f6-a1ca-9f42-f4b2-d59d308098d0&protectedtoken=true&claims=%7b%22id_token%22%3a%7b%22xms_cc%22%3a%7b%22values%22%3a%5b%22CP1%22%5d%7d%7d%7d&nonce=638689765847414179.8a3dbd18-442f-405a-8d30-8eba38e3f9d7&state=DctBEoAgCEBRrOk4pAYKHgcH3bbs-rF4f_cTAJzhCKlEQDpp1yG9KQtXrjJuNfLpVZH52cilGapTQV3TSBft4ZLivfL7Wf4B)
