### ISSUE TITLE
TM interferes with web pages even when no scripts are installed

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#2276]
1. Create new FF profile
2. Install TM beta, do not install any scripts
3. Browse to https://is.gd/xteTsv
4. If the image does not load (or disappears after loading) hit CTRL-F5
5. Check console (CTRL-SHIFT-J) for errors

## Expected Behavior

No errors in the console.

## Actual Behavior

An error:
```
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' 'unsafe-eval' 'unsafe-inline' 'nonce-1242151439834284684714' https://yastatic.net https://yastat.net https://s3.mds.yandex.net https://static-mon.yastatic.net https://static-mon.yandex.net https://suggest-beta.s3.yandex.net https://yandex.com https://ya.ru https://*.ya.ru https://an.yandex.com https://mc.yandex.com https://social.yandex.com https://export.yandex.com https://suggest.yandex.com https://notifications.yandex.com https://bs.yandex.ru https://pass.yandex.com https://mc.webvisor.com https://mc.webvisor.org https://mc.yandex.md https://yandex.ru https://mc.yandex.ru https://an.yandex.ru https://yandex.sx https://static.yandex.sx https://social.yandex.ru https://an.webvisor.org https://mc.webvisor.org https://yabs.yandex.com https://yabs.yandex.ru” 2 content.js:68:265
```

## Specifications

- FF dev: 134.0b3 (64-bit)
- TM: v5.3.6216
- OS: Windows 10

## Script

No scripts

**Comment by derjanb** [comment]
Please set "Config Mode" to "Advanced" and then "Content Script API" to "UserScripts API Dynamic". This allows Tampermonkey to get the number of executed scripts at `document-start` what makes some initialization that is done otherwise obsolete.

**Comment by alexolog** [comment]
> Please set "Config Mode" to "Advanced" and then "Content Script API" to "UserScripts API Dynamic". This allows Tampermonkey to get the number of executed scripts at `document-start` what makes some initialization that is done otherwise obsolete.

Shouldn't it be the default then?

**Comment by derjanb** [comment]
"UserScripts API Dynamic" is still a bit experimental... So please report back if you encountered issues when using it.
