### ISSUE TITLE
Help applying a script to a website.

### ISSUE THREAD

**Issue by Newbie1551** [Tampermonkey/tampermonkey#2277]
(Please fill out the issue template with your details)

## Expected Behavior

Manual change via the developer tools works, but using the script i found on the net regarding this issue didn't work.

## Actual Behavior

Identify the website and works but script changes does not apply.

## Specifications

- GoogleChrome

## Script

(Please give an example of the script if applicable.)

// ==UserScript==
// @name         Translation to website - Qidian.com
// @namespace    http://tampermonkey.net/
// @version      2024-12-04
// @description  try to take over the world!
// @author       You
// @match        https://www.qidian.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=qidian.com
// @grant        none
// ==/UserScript==
(function() {
    'use strict';

    // javascript: (function(){let html_tag = document.getElementsByTagName("https://www.qidian.com/*")[0];html_tag.setAttribute("translate", "yes");html_tag.classList.remove("notranslate");})();
})();

**Comment by sabelliadriano** [comment]
getElementsByTagName accepts only valid html tags, not urls

**Comment by sabelliadriano** [comment]
try with this // javascript: (function(){let html_tag = document.getElementsByTagName("html")[0];html_tag.setAttribute("translate", "yes");html_tag.classList.remove("notranslate");})();
