### ISSUE TITLE
篡改猴测试版视乎无法启动

### ISSUE THREAD

**Issue by Jeivns** [Tampermonkey/tampermonkey#2290]
![q](https://github.com/user-attachments/assets/f59b0421-0499-4c1f-914b-8c349e16f65a)

如图，无法进入仪表盘界面

**Comment by derjanb** [comment]
I need more information. Tampermonkey BETA, browser and OS version. Thanks.

**Comment by long912** [comment]
![image](https://github.com/user-attachments/assets/422eb23d-b1ba-46dd-ab1c-a074c62d5712)
![image](https://github.com/user-attachments/assets/07718d05-989f-4937-a563-3b8dde6162b2)
![image](https://github.com/user-attachments/assets/5c397a2f-eee0-4f47-9212-23547f1929c8)
Win10

**Comment by derjanb** [comment]
Got no feedback, but it's probably related to #2305
