### ISSUE TITLE
[Feature request] Content Script API enhancement

### ISSUE THREAD

**Issue by ten4dinosaur** [Tampermonkey/tampermonkey#2291]
It would be ideal if the script manifest could be enhanced to allow the script to request the usage of the "UserScripts API Dynamic" API, or, even better, make it the default behavior. This feature is critical for many use cases where overriding the script logic in the `<head>` tag is necessary.

Currently, end-users, who are often not tech-savvy, face difficulties in understanding how to manually enable this setting. Additionally, explaining why this setting is required adds unnecessary complexity to the user experience.

By implementing this change, the process would be simplified, reducing confusion for non-technical users and improving overall usability.

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the manifest.json.google.com file to include the 'userScriptsAPI' permission, which enables the UserScripts API Dynamic functionality by default. This change simplifies the process for users and eliminates the need for manual configuration.

You can review changes in this commit: https://github.com/kkpo4553/Tampermonkey-tampermonkey-2291/commit/6d58de5a62e2980d1cf59209962ad994dd766df0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ten4dinosaur** [comment]
> True. However, dynamic mode has some disadvantages:

It will be perfect it it will be script manifest setting like `// @script-api: dynamic`, so dynamic mode will be anabled only for matching url, not for all websites. Also it will solve main issue with end-users
