### ISSUE TITLE
[MV3] Service worker is not registered

### ISSUE THREAD

**Issue by fz0758** [Tampermonkey/tampermonkey#2293]
篡改猴

大小: 5.1 MB 版本: 5 . 3 . 3

Microsoft Edge
版本 131.0.2903.86 (正式版本) (64 位)

Windows规格
版本Windows10专业工作站版
版本号22H2
操作系统内部版本19045.5247
体验Windows Feature Experience Pack
1000.19060.1000.0

错误如下,无法启动
![image](https://github.com/user-attachments/assets/95f0ede2-3c1a-4aa1-a6c3-a85511ca9d46)

**Comment by fz0758** [comment]
![2024-12-12_16-57-47](https://github.com/user-attachments/assets/b8473132-ee58-47ee-8963-8a22b5d7a43b)
options页面也无法打开.无法获取调试信息

**Comment by derjanb** [comment]
Please go to "chrome://extensions" and disable and re-enable Tampermonkey. Does that solve the issue?

Also, please open `chrome://serviceworker-internals/` and search for the entry

```
Scope: chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/
```
or
```
Scope: chrome-extension://iikmkjmpaadaobahmlepeloendndfphd/
```

What information is shown there if Tampermonkey is not working.

Finally, if there is a service worker entry, please open 

`chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo`
or
`edge://extensions/?id=iikmkjmpaadaobahmlepeloendndfphd`

ensure, developer mode is enabled, and click at `Inspect views` > `service worker`, then select the console tab. Do you see errors there?

**Comment by fz0758** [comment]
1, disable and re-enable Tampermonkey,操作后仍旧无法启动
2,开启了 service worker
![2024-12-12_17-10-30](https://github.com/user-attachments/assets/2c126f4e-df22-4a10-9146-c706e95acfa2)

3,  console tab
![2024-12-12_17-12-07](https://github.com/user-attachments/assets/06a28515-c992-4d3a-b211-0ac6473b8317)

**Comment by derjanb** [comment]
Thanks, but this is not the right console. Please open this link: 

![image](https://github.com/user-attachments/assets/cdb0fae6-6e90-47d0-8d43-07a37ca0b075)

**Comment by fz0758** [comment]
![2024-12-12_17-24-39](https://github.com/user-attachments/assets/90d87375-bd0f-4ac6-952c-167f657fe909)
我试过 点击这个链接,但无法打开(没有任何反应),可能就像上面的 console tab显示的js错误导致无法打开

**Comment by fz0758** [comment]
![2024-12-12_17-31-08](https://github.com/user-attachments/assets/4ef7f1a0-5fe4-4fa3-9b23-1c709344b8ce)

**Comment by derjanb** [comment]
Thanks. This should never happen, because Chrome/Edge must register the extension's service worker. 

The only ways I know to cleanup things are disabling and enabling Tampermonkey or a reinstallation (which will cause data loss)

![image](https://github.com/user-attachments/assets/1ebf7ec5-8c7b-4f20-a34e-5376b3221393)

**Comment by derjanb** [comment]
This is the Chrome bug report. Looks like sometimes even re-installing the extension doesn't work.

https://issues.chromium.org/issues/40805401

**Comment by fz0758** [comment]
根据你截图中的AppData\Local\Microsoft\Edge\User Data\Default\文件路径,我检查后发现是Service Worker目录被我用软链接指向了Ramdisk,因windows更新重启后Service Worker没有正确重新建立,导致无法启动扩展,

我删除了软连接后,edge自动重新创建了Service Worker目录,现在篡改猴能正常启动了.
感谢排除故障.
