### ISSUE TITLE
The extention stopped workin out of blue on Windows 7

### ISSUE THREAD

**Issue by Vidarr27** [Tampermonkey/tampermonkey#2295]
So, I've been usin Tampermonkey for... a year now I guess.
I open my opera GX today only to find out it (the extention) was stuck on pernament loadin screen.

It stopped workin, I tried everythin even reinstallin.
I went on Opera's forums.
Still didn't help.

**Comment by derjanb** [comment]
Tampermonkey's manifest requires Chrome 120 and above. So the opera store should not update to 5.3.6222 at Opera GX (which is based on Chromium 112). Otherwise this is a bug.

If you want to install Tampermonkey at Opera GX, then please install Tampermonkey Legacy from the Chrome Web store.

https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn

**Comment by Vidarr27** [comment]
> Tampermonkey's manifest requires Chrome 120 and above. So the opera store should not update to 5.3.6222 at Opera GX (which is based on Chromium 112). Otherwise this is a bug.
> 
> If you want to install Tampermonkey at Opera GX, then please install Tampermonkey Legacy from the Chrome Web store.
> 
> https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn

Oh yea, saw this solution on Opera forum
It didn't work
All it did was spit out a massage "Download interrupted with a reason: Bad_server_content".

**Comment by derjanb** [comment]
Opera says that Windows 7 is no longer supported. Sorry, there is nothing I can do...

https://forums.opera.com/topic/67695/solved-can-t-install-extensions-from-the-new-chrome-web-store/67

**Comment by Vidarr27** [comment]
> Opera says that Windows 7 is no longer supported. Sorry, there is nothing I can do...
> 
> https://forums.opera.com/topic/67695/solved-can-t-install-extensions-from-the-new-chrome-web-store/67


Thank you
I used the extenrion for only Youtube, but it will be missed nonetheless
Keep up the good work

I'll make sure to install this extention when I'll be forced to update to Win10
