### ISSUE TITLE
Auto-updates all flood at once

### ISSUE THREAD

**Issue by adamlui** [Tampermonkey/tampermonkey#2298]
(Please fill out the issue template with your details)

## Expected Behavior

Spread them out a little so tabs don't bombard the user

## Actual Behavior

Many tabs open at once, causing slight lag + potentially disrupting workflow

![image](https://github.com/user-attachments/assets/1c2d8c9b-d9be-413a-925b-d521cd462e21)

## Specifications

- FF 133.0
- TM 5.3.2
- OS: Win10

Another drawback is for script authors, this incentivizes users to click "Disable Updates" to penalize authors for doing nothing wrong

**Comment by derjanb** [comment]
> Spread them out a little so tabs don't bombard the user

I'd argue that it is better to disrupt the user once with a larger number of tabs than to disrupt them multiple times with a smaller number of tabs.
Also updates usually don't open a new tab, unless the script permissions have changed.

**Comment by adamlui** [comment]
> I'd argue that it is better to disrupt the user once with a larger number of tabs than to disrupt them multiple times with a smaller number of tabs.

That's just really bad UX but whatever it's your userbase you stand to turn off

> Also updates usually don't open a new tab, unless the script permissions have changed.

This is simply untrue (all those updates were for my authored scripts and I changed no permissions) also every update I've ever received has always opened new tabs

**Comment by adamlui** [comment]
I don't understand how you think lagging a user's browser is better but feel free to close this issue since I cannot talk sense to you

**Comment by adamlui** [comment]
In fact users stand to remove even TM (not just punish me by disable updates for my scripts) for (correctly) assuming the manager hurts browser performance (which it does when 10+ updates flood)

**Comment by adamlui** [comment]
From env info shared by my users during troubleshooting I learned they mostly use VM anyway, was just trying to look out for the minority who still use TM but looks like they're on their own

**Comment by adamlui** [comment]
(I link to managers to install in all my docs and don't place TM high is probably why, but for good reason that it crashes when streaming AI response so I cannot highly recommend unlike VM)

**Comment by derjanb** [comment]
> This is simply untrue (all those updates were for my authored scripts and I changed no permissions) also every update I've ever received has always opened new tabs

Then you probably disabled "Don't ask me for simple script updates".

OK, so closing this as WAI for the moment.

**Comment by adamlui** [comment]
> Then you probably disabled "Don't ask me for simple script updates".

It's already checked makes no difference

![image](https://github.com/user-attachments/assets/460658c6-4f33-45ec-9e00-d9b29849f6cc)

...also it's very peculiar how you typically blame the victims (or other browsers) of your bugs or poor UX decisions for trying to improve your software

> OK, so closing this as WAI for the moment.

What is that

**Comment by adamlui** [comment]
Like I'm handing you gold on a platter how to not turn off your users (who will punish me too if you don't appease) but you are so resistant or don't even understand how the default behavior of your own software works for a reason I cannot understand because you stand to benefit if you just humbly heed my advice and don't ruin people's browser experience like your competitors respectfully don't

**Comment by adamlui** [comment]
(obtrusively spamming them as mentioned in https://github.com/Tampermonkey/tampermonkey/issues/2242 is another indicator + your bizarre responses here that gradually exposes you really don't care or respect their UX)

**Comment by adamlui** [comment]
In fact based on my tracking analytics I'm almost 100% certain my last updates which changed no permissions but merely met a lines changed threshold and applied to 10 of my scripts caused unstarring/uninstalls due to this alarming flood behavior (since users of my scripts often use multiple of them based on their feedback)

**Comment by adamlui** [comment]
Also I recall it always asks even if it's 1 line but even if not, you are ignoring the underlying issue which is if there are a lot of pending updates, it is horribly wrong to flood them at once and potentially lock up their browser vs. spreading it out. There is nothing worse than creating lag and a user of your software knows it's the direct cause, what do you think follows? Uninstalls...

**Comment by adamlui** [comment]
Tampermonkey is hardly the only serious player in the game nowadays and I think you're strangely reasoning from a position of sitting in a former throne like you have nothing to lose when that is far from the case now (i.e. every wrong decision you make drives existing users who were only loyal like me from longtime familiarity to switch to Pepsi, which new users are increasingly preferring at least ~50% if not more)

**Comment by adamlui** [comment]
Also Chrome/FF only counts weekly/daily active users respectively so you actually stand to get dethroned, like my GF scripts user stat only goes up but your Web store user stat can go down, you had years of head start so creates dangerous and inflated sense of safety

**Comment by adamlui** [comment]
No monopoly ever went down overnight (except w/ government intervention like Microsoft v. DOJ in the 90s) just reflect on that and what is the current state of userscript managers and choices users have today (not 2013)

**Comment by adamlui** [comment]
Also reflect on how you originally overtook Greasemonkey, really ask yourself why did users switch, then are there TMs of today (not 2013) and are you doing anything to supply new reason to switch

**Comment by derjanb** [comment]
> It's already checked makes no difference

If this option is enabled, then Tampermonkey requires user confirmation in case of:

* Script version downgrade
* Script data reset (intentional reset or on re-installation of the same version)
* New/changed `@connect`
* New/changed `@include` or `@match`
* Update URL change
* Updating a locally modified script (changes will be overwritten)
* Script modification, which disables further updates
* No include information (the script is not executed on any page)
* Modification conflict with another tab
* Deleted by script hoster
* Blacklisted

So if you see the confirmation dialog and none of the above applies, it's a bug. Please create an issue with detailed information how to reproduce the issue.
If you feel that one of the above points should not trigger a confirmation dialog, please create an issue and explain why.

As mentioned, I want to keep the current behavior of showing all updates at once. So I'm closing this issue.

**Comment by adamlui** [comment]
None of those applied (you can visit my https://github.com/adamlui/ai-web-extensions commit history to verify) but why are you making me do the all the work when I'm already helping you out with unpaid labor? You create the issue if you want to improve your code (you already copy many ideas from me for free, like you added `GM_getValues` mere weeks after completing my https://github.com/Tampermonkey/tampermonkey/issues/2158 which shared code from a script that did the same thing, even your new marketing albeit overly spammy was clearly influenced by me, show some appreciation it's good karma and do it yourself sir

**Comment by derjanb** [comment]
> you already copy many ideas from me for free

Don't think so: #2045

> You create the issue if you want to improve your code

Creating an issue about something that I can't neither read in the code nor reproduce makes no sense.

**Comment by adamlui** [comment]
What does "can't read in the code" mean. You listed criteria for a thing occurring, I explicitly revealed said criteria was not met and thing still occurred, thus it is an issue. GitHub Issues are then created to try to reproduce and solve (so not sure what you cannot reproduce withuot even trying yet prevents you from not being lazy and instead force me to do your work unpaid)

**Comment by adamlui** [comment]
> Don't think so: https://github.com/Tampermonkey/tampermonkey/issues/2045

A months old idea you lazily set aside for not having elegant solution to detecting multi-val or not until my concise one then you suddenly release within weeks is coincidence? Get out of here

**Comment by adamlui** [comment]
I think I'm going to start removing Tampermonkey from all my docs after I do some recovering from COVID (your selfishness simply cannot be rewarded with my steady traffic)

**Comment by adamlui** [comment]
Even your defense is so awkward and weak (innocent programmer would adamantly deny, guilty one says they don't "think" so like subconsciously you didn't completely convince yourself yet since it's untrue)
