### ISSUE TITLE
All Tampermonkey settings are sometimes lost

### ISSUE THREAD

**Issue by realityexists** [Tampermonkey/tampermonkey#2300]
## Expected Behavior
TM never loses its settings.

## Actual Behavior
I've sometimes found that all TM settings are wiped - all scripts are gone, all settings are reset to defaults, it prompts me again whether to report anonymous usage statistics.

It seemed to happen after the disk containing my Firefox profile ran out of space, but I could not reproduce it by just filling up the disk. Another time it happened when a "zombie" Firefox process was left after I closed the main Firefox window and then tried to run Firefox again. (And the disk may also have been full.)

So I cannot reproduce this, but it has happened to me at least 4 times over the years I've been using Tampermonkey, and is really annoying.

## Specifications

- Firefox 115.18.0esr (also happened with earlier Firefox versions)
- TM: 5.3.2 (also happened with earlier TM versions)
- OS: Windows 7 x64

**Comment by derjanb** [comment]
There are several issues related to broken storage at Firefox. Unfortunately there is nothing I can do, because extensions can only rely on the browser to store their data securely. Sorry.

https://bugzilla.mozilla.org/show_bug.cgi?id=1522188
https://bugzilla.mozilla.org/show_bug.cgi?id=1519859
https://bugzilla.mozilla.org/show_bug.cgi?id=1926832

Somehow related #1954 #668 #536 #470 #458

**Comment by realityexists** [comment]
Thanks for the quick response!

I should add that I have at least 8 other extensions with settings that I changed (e.g. uBlock Origin, Stylus, NoScript, Cookie AutoDelete, ...) and none of those extensions have ever had their settings lost/reset, while with TM it has happened at least 4 times. That's not to say that this is TM's "fault", but it seems like TM is at least doing something differently to those other extensions.

If FF storage did get corrupted, would TM at least be able to detect that somehow and tell me? Or does Firefox just _completely silently_ present empty storage to the extension as if it had just been freshly installed? Is there some kind of logging I can enable that would help to track it down when it does happen (since I'm unable to repro)?

The first of those Mozilla bugs was closed 2 years ago as "not happening anymore", and I'm using the latest ESR version. The second I don't quite understand, but it seems to be about a crash/error, and I'm not seeing that. The third is for Thunderbird, not Firefox. So I'm not sure that those are relevant here - but I'm not an extension developer.

**Comment by dajotim937** [comment]
Also using the lates ESR and also my scripts were wiped. The most strange thing is that only tampermonkey settings/scripts were deleted. Several other extension are fine and alive. Don't really understand hot this happened.

**Comment by realityexists** [comment]
Just happened again with TM v5.3.3 on Firefox 115.22.0esr and the drive where the Firefox profile is stored was again low on disk space (but not at 0). This time Privacy Badger also popped up its "thanks for installing" screen, but other extensions, like uBlock Origin and Cookie AutoDelete kept their settings. I also got logged out of Pandora (which I believe uses local storage for this), but not out of sites that use cookies for authentication.

So it's not just TM, but still, it doesn't happen to most extensions.

@derjanb are you sure it's caused by those FF issues you linked? The first is resolved, the second is about a crash and I did not see Firefox crash recently, and the third seems to be an enhancement (notify user when data is corrupted).

**Comment by enchained** [comment]
Happened a few times to me during the last couple of weeks on Firefox 139.0.1 (64-bit), Windows 10. I had multiple BSODs during this time so that might be the cause, but I can't pinpoint the exact times it was wiped since there is no warning after. No other extension settings were affected except this one. I guess Firefox crashes do corrupt specific data.

**Comment by Nes370** [comment]
I recently ran out of storage space on my Windows 10 (build 19045.5965) PC and all of my tampermonkey scripts disappeared from Firefox (v139.0.4 64-bit).

**Comment by Dramorian** [comment]
Encountered TM extension corruption today and all scripts went to the shadow realm after restoration. No backup either.
Make backups, guys.
