### ISSUE TITLE
Can't delete HttpOnly cookie

### ISSUE THREAD

**Issue by cyber-sec0** [Tampermonkey/tampermonkey#2303]
## Expected Behavior
JS by itself can't delete HttpOnly cookies, but perhaps a browser extension can?

## Actual Behavior
The script says the cookie was deleted, but it wasn't.

## Script

```js
// ==UserScript==
// @name         t
// @namespace    t
// @version      3
// @description  t
// @author       t
// @match        *
// @run-at       document-end
// @grant        GM_cookie
// ==/UserScript==

GM_cookie.delete({ name: 'gds' }, function(error) {
    if (error) {
        document.title = 'worked'
    } else {
        document.title = 'failed'
    }
});
```

**Comment by derjanb** [comment]
Seems to work fine. Please make this fail:

```JS
// ==UserScript==
// @name         xxx
// @namespace    xxx
// @version      xxx
// @description  xxx
// @author       xxx
// @match        https://example.com/*
// @match        https://httpbin.org/*
// @grant        GM.xmlHttpRequest
// @grant        GM.cookie
// @connect      httpbin.org
// ==/UserScript==

const value = Math.random().toString(36).substr(2, 10);

await GM.xmlHttpRequest({
  url: 'https://httpbin.org/response-headers?set-cookie=nonpartitioned=' + value + ';path=/;expires=Wed,%2021%20Sep%202033%2015:59:37%20GMT;httponly;secure;samesite=none',
  onload: r=>console.log(r.responseText),
  onerror: console.error
})

await GM.xmlHttpRequest({
  url: 'https://httpbin.org/cookies',
  onload: r=>console.log('GET cookies 1', r.responseText),
  onerror: console.error
})

await GM.cookie.delete({ name: 'nonpartitioned', url: 'https://httpbin.org/' }, function(error) {
    if (error) {
        console.log('GM.cookie.delete worked')
    } else {
        console.log('GM.cookie.delete failed')
    }
});

await GM.xmlHttpRequest({
  url: 'https://httpbin.org/cookies',
  onload: r=>console.log('GET cookies 2', r.responseText),
  onerror: console.error
})
```

**Comment by cyber-sec0** [comment]
Do I have to use connect and declare the url parameter as well?

`
// ==UserScript==
// @name         t
// @namespace    t
// @version      3
// @description  Unlimited free usage (without login)
// @author       t
// @match        https://www.adobe.com/acrobat/online/*
// @run-at       document-end
// @grant        GM.cookie
// ==/UserScript==

GM_cookie.delete({ name: 'gds' }, function(error) {
    if (error) {
        document.title = 'worked'
    } else {
        document.title = 'failed'
    }
});
`

**Comment by derjanb** [comment]
> Do I have to use connect and declare the url parameter as well?

https://tmnk.net/docs#api:GM_cookie.delete 😉

**Comment by cyber-sec0** [comment]
Doesn't work.

![image](https://github.com/user-attachments/assets/6caac60f-e4a6-48b9-a3a2-408cb356a552)

```
// ==UserScript==
// @name         t
// @namespace    t
// @version      3
// @description  Unlimited free usage (without login)
// @author       t
// @match        https://www.adobe.com/acrobat/online/*
// @run-at       document-end
// @grant        GM.cookie
// @connect      adobe.com
// ==/UserScript==

GM.cookie.delete({ name: 'gds', url: 'https://www.adobe.com/' }, function(error) {
    if (error) {
        document.title = 'worked'
    } else {
        document.title = 'failed'
    }
});
```

**Comment by cyber-sec0** [comment]
I've tried that but I forgot to update my connect tag, even thought I changed it it still doesn't work.
Both console.log() return an empty array.

```
// ==UserScript==
// @name         t
// @namespace    t
// @version      3
// @description  free usage (no login)
// @author       t
// @match        https://www.adobe.com/acrobat/online/*
// @connect      services.adobe.com
// @run-at       document-end
// @grant        GM.cookie
// ==/UserScript==

console.log(await GM.cookie.list({ name: 'gds' }));
GM.cookie.delete({ name: 'gds', url: 'https://services.adobe.com/' })
console.log(await GM.cookie.list({ name: 'gds' }));
```

**Comment by derjanb** [comment]
Depending in you Tampermonkey version you need to set `Security` > `Allow scripts to access cookies` to `All` in order to list and read them. Deleting should be possible though.

**Comment by cyber-sec0** [comment]
Oh ok, now I see 1 HttpOnly cookie, but seems like none of the cookies under the services domain shows up, so I still can't delelte the "gds" cookie.

**Comment by derjanb** [comment]
> to update my connect tag, even thought I changed it it still doesn't work

`@connect` is not needed for `GM.cookie`, but `GM_xhr` only.

```
console.log(await GM.cookie.delete({ name: 'gds', url: 'https://services.adobe.com/' });
```

should log an error, because your script does not `@include` "services.adobe.com", so you need to add it.

**Comment by cyber-sec0** [comment]
@derjanb 

I'm not using GM_xhr.

It works now, thank you!
