### ISSUE TITLE
UI almost unusable for low vision/screen reader users

### ISSUE THREAD

**Issue by tgrushka** [Tampermonkey/tampermonkey#2315]
Hi, thank you for Tampermonkey. I am a legally blind developer, and I use font sizes much larger than most people. The UI is mostly accessible for me, except that the top banner, script title, and Editor/Settings tab take half the vertical space on my screen, such that I have to strain to work with the code editor in only the bottom half of my screen. Also, the code editor font size only allows 150% of normal, so I can't just "zoom out" because the code editor font size is then too small.

I would be very grateful if you could allow me to hide the banner, reduce the height of the script title and tabs area, and enlarge my editor font size beyond 150%.

I tried to use Stylus, but even when security is overridden (these browser makers keep restricting things so I can't make them accessible), Stylus can no longer customize add-on pages (major bummer).

EDIT: There's another problem. I've written a custom screen reader that reads the X selection aloud when I hit a shortcut key. It works in almost everything else, except the Tampermonkey editor. Somehow the Tampermonkey editor is not allowing standard copy/paste operations on Linux.

Thank you.

## Expected Behavior

I hope the font size of the editor could allow at least 200-300% and the Tampermonkey editor could be expanded to take more of the screen height.

EDIT: I also hope the editor could be fixed to expose its selection to the clipboard (xsel on Linux).

## Actual Behavior

This is what it looks like.

![Screenshot from 2024-12-28 15-41-25](https://github.com/user-attachments/assets/6dbed1bf-3632-4395-9425-6a0858b998ea)

## Specifications

- Firefox 133.0.3 (64-bit)
- TM: 5.3.3
- OS: Linux framework-mint 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## Script

N/A

**Comment by derjanb** [comment]
> I would be very grateful if you could allow me to hide the banner

You can modify the page as needed by configuring custom CSS code. This post explains how to remove the banner -> https://github.com/Tampermonkey/tampermonkey/issues/495#issuecomment-361388615

> Somehow the Tampermonkey editor is not allowing standard copy/paste operations on Linux.

The editor is third-party software named CodeMirror editor. Please check if you find workarounds for it.
