### ISSUE TITLE
Support for Firefox Mobile on Android

### ISSUE THREAD

**Issue by devnoname120** [Tampermonkey/tampermonkey#250]
As far as I know, no Usercript engine works on Firefox Mobile.
Would it be possible to port TamperMonkey to it?

Thank you for this extension.

**Comment by derjanb** [comment]
I already ported TM to FF, but the WebExtension API is still a little bit flaky. WebExtension Android support is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1185785
If both issues are solved then TM should be able to work in FF Mobile as well. :)

**Comment by devnoname120** [comment]
Nice!
Would it be possible to get a beta version? (If the missing Api does not prevent Tampermonkey from working altogether.)

**Comment by derjanb** [comment]
Unfortunately not. :) I'll upload TM for FF as soon as AMO supports WebExtensions: https://bugzilla.mozilla.org/show_bug.cgi?id=1210037

**Comment by purpasmart96** [comment]
This would be awesome if you could have this for firefox. +1

**Comment by derjanb** [comment]
At least the desktop FF version is already uploaded: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey-original/

**Comment by LockeAnarchist** [comment]
Now Firefox for Android beta (52) seems to have a much better support for webextensions but tampermonkey is still not working.

**Comment by derjanb** [comment]
Tampermonkey 4.5.5570 works at Firefox for Android 56+.

Notes: 
* FFfA 56: it's not possible to open the popup menu or the options page, but installing and executing scripts is working.
* FFfA 57+: the popup menu might look a little bit odd since it's not optimized for mobile browsers (yet).
