### ISSUE TITLE
use a service for getting sites' favicons

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#252]
currently, in the installed userscripts list, the @-included sites' favicons are loaded from `http(s)://site.tld/favicon.ico`

this doesn't work for sites that serve their favicon with a different filename, format or path using a `link` element

``` javascript
"https://www.google.com/s2/favicons?domain=" + encodeURIComponent(/* url or hostname */)

// these all work:
// https://www.google.com/s2/favicons?domain=tampermonkey.net
// https://www.google.com/s2/favicons?domain=https://tampermonkey.net/
// https://www.google.com/s2/favicons?domain=https://tampermonkey.net/index.php
```

something like this would work better

google's favicon service isn't the only one out there btw, it's just what i use

**Comment by tiansh** [comment]
vote -1 for user privacy
google already knows too much

**Comment by 18763C27** [comment]
my dad says that too

i found these alternate favicon services for you via google(tm):

https://icons.better-idea.org/

https://grabicon.com/

**Comment by derjanb** [comment]
Closing this in favor of https://github.com/Tampermonkey/tampermonkey/issues/396
