### ISSUE TITLE
Beta 4.0.5022 fails to display userscript config dialog (GM_registerMenuCommand)

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#258]
1. Install a userscript that has GM_registerMenuCommand dialog, for example [Linkify++](https://greasyfork.org/scripts/4255-linkify-plus-plus)
2. Reload the current tab and click TM icon, then the userscript config menu item
3. Nothing happens

Here's an error message from the console:

>Error in event handler for (unknown): TypeError: c.sendMessage is not a function 
at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/content.js:11:471

**Comment by tophf** [comment]
I've temporarily edited it to `c.postMessage` to be able to invoke the config dialog.

**Comment by derjanb** [comment]
Sorry for the delay...
http://tampermonkey.net/changelog.php?version=4.0.5035&ext=gcal
