### ISSUE TITLE
Chrome 50 breaks TM (beta) editor layout

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#259]
Below is what I see in 50.0.2633.3 dev and TM 4.0.5047.
The editor doesn't stretch to the full window height.
Doesn't happen in stable Chrome 48 + TM beta.

![1-fs8](https://cloud.githubusercontent.com/assets/1310400/12703094/8e84b1ee-c842-11e5-83d3-2db73b13b9dd.png)

I can fix it by removing `position: relative;` from `.tv_contents` rule and setting `top: 175px;` in `.editor_outer`. Although this is quite probably Chrome-dev's fault. 

Maybe you can investigate it and submit a bug report on crbug.com if that's what it is.

P.S. Still your CSS could be simpler, for example I'd try using `display: flex` (available since [Chrome 21](https://www.chromestatus.com/feature/4837301406400512)) which would make the layout more robust by eliminating the need to redefine every element's height, width, position.

**Comment by derjanb** [comment]
Chrome 50 is downloading... :) Unfortunately Firefox behaves exactly the same way :-/

> P.S. Still your CSS could be simpler

The whole layout needs a refresh and I plan to use a framework like Twitter bootstrap or material design lite some day, but it will take a lot of time to implement.

**Comment by derjanb** [comment]
Fixed. Thanks for reporting. http://tampermonkey.net/changelog.php?version=4.0.5054&ext=gcal
