### ISSUE TITLE
New "grey" icons are too bright on dark Chrome themes

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#260]
Being lighter than the original red one the "grey" icon is **MUCH BRIGHTER** when used with dark Chrome themes. On greyish themes it looks... well, funky.

I think a semi-transparent original icon would be much more universal, here's my take using 30% opacity:

![icon_grey38](https://cloud.githubusercontent.com/assets/1310400/12774821/2eb4eb4c-ca51-11e5-8ec7-d0e821c001d0.png)

![icon_grey19](https://cloud.githubusercontent.com/assets/1310400/12774820/2eb4b38e-ca51-11e5-9f0e-9ae9730e0bab.png)

I've used [pngquant --quality 50-80](https://github.com/pornel/pngquant) to optimize the images.

Didn't desaturate them, but maybe I should have.

**Comment by derjanb** [comment]
Fixed. http://tampermonkey.net/changelog.php?version=4.0.5059&ext=gcal

**Comment by tophf** [comment]
The exact same issue has re-appeared again a few days ago.

**Comment by derjanb** [comment]
@tophf Should be [fixed again](http://tampermonkey.net/changelog.php?version=4.3.5443&ext=gcal). :)
