### ISSUE TITLE
anti-adblock-killer v9.2 doesn't work with latest beta (4.0.5054)

### ISSUE THREAD

**Issue by offhub** [Tampermonkey/tampermonkey#261]
`ERROR: Execution of script 'Anti-Adblock Killer | Reek' failed! Cannot read property 'bind' of undefined`

`TypeError: Cannot read property 'bind' of undefined
    at Object.Aak.registerConsole (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:241:46)
    at Object.Aak.initialize (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:98:9)`

I also tested Aak 9.2 with previovus TM Beta versions, here are the results:

- Aak 9.2 + TM Beta 4.0.5054 = Failed
- Aak 9.2 + TM Beta 4.0.5047 = Failed
- Aak 9.2 + TM Beta 4.0.5035 = Failed
- Aak 9.2 + TM Beta 4.0.5008 = Ok

I'm using Chrome Beta 49.0.2623.28 (64-bit). Also tested with Chrome 48.

**Comment by derjanb** [comment]
Fixed. http://tampermonkey.net/changelog.php?version=4.0.5059&ext=gcal
