### ISSUE TITLE
(beta 4.0.5070) missing console methods

### ISSUE THREAD

**Issue by 18763C27** [Tampermonkey/tampermonkey#263]
reproduction steps:

1. install TM beta

2. use `console.dir` from a userscript

(un)expected outcome:

    TypeError: console.dir is not a function(…)

---

![image](https://cloud.githubusercontent.com/assets/12559208/13036106/4c756b92-d367-11e5-8f30-e6bf6ab1d0b2.png)

its missing a lot of others too (do  `console.__proto__.__proto__` in the console or see the [mdn article](https://developer.mozilla.org/en-US/docs/Web/API/Console))

what even is the point of mirroring the console like that?

**Comment by derjanb** [comment]
Fixed. Thanks for reporting. http://tampermonkey.net/changelog.php?version=4.0.5084&ext=gcal
