### ISSUE TITLE
(beta 4.0.5070) simple editor loses your changes on save

### ISSUE THREAD

**Issue by 18763C27** [Tampermonkey/tampermonkey#264]
1. install TM beta

2. disable the enhanced editor in the settings

3. go to edit a script

4. change something and hit the save button

result:

the text area reverts all of your changes

the script gets saved though so nothing is lost

also, i think it'd be more appropriate to use a monospaced font even in the simple editor

**Comment by derjanb** [comment]
Both issues are fixed. http://tampermonkey.net/changelog.php?version=4.0.5084&ext=gcal
