### ISSUE TITLE
user script was not loading

### ISSUE THREAD

**Issue by ztoddw** [Tampermonkey/tampermonkey#266]
I couldn't get my user script to load for about the first ten tries, then all of a sudden it loaded.  On the last two tries this is what I changed :  (tampermonkey put this line in- I dunno what it is or what it does.)

try # 9-- changed this line:
/* jshint -W097 */    

to this:
/* js hint -W097 */    

try # 10-- changed it back to the original:
/* jshint -W097 */    

Did changing that line really have anything to do with why it started working?  Or was it just incidental?

This is how my script starts:

// ==UserScript==
// @name         helpTranscribeBillionGraves
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://billiongraves.com/transcribe/?media_id=*
// @grant        none
// @require http://code.jquery.com/jquery-latest.js
// ==/UserScript==
/* jshint -W097 */    //what is this stuff? tampermonkey put it in- I dunno what it is
//'use strict';        //what is this stuff? tampermonkey put it in- I dunno what it is
//
// Your code here...

**Comment by derjanb** [comment]
This is just a comment which is us by the JSHINT based syntax check, but it has nothing to do with the script injection itself.
Please attach some background page log message in case this happens again.
