### ISSUE TITLE
Bookmark issues

### ISSUE THREAD

**Issue by chadestes** [Tampermonkey/tampermonkey#268]
I cannot select a bookmark. When I try to click on the star I only get the pop up balloon. I can't get the star to light up and put a bookmark on the map.

**Comment by tophf** [comment]
There's no "map" or "bookmark" in Tampermonkey.
Is the issue specific to some userscript you've installed?

**Comment by chadestes** [comment]
This is specific to the Ingress Intel Total Conversion that uses Tampermonkey to install the scripts. Perhaps I've posted my question in the wrong location.

**Comment by derjanb** [comment]
> Perhaps I've posted my question in the wrong location.
Yes, please contact the IITC authors regarding this issue. Thanks.
