### ISSUE TITLE
@require external resources retrieval failure (using file:// protocol to a file server)

### ISSUE THREAD

**Issue by Tyf0x** [Tampermonkey/tampermonkey#269]
**Originally imported from [tampermonkey bug forums](https://forum.tampermonkey.net/viewtopic.php?f=17&t=1659&sid=36a7fa09d7ab91e3f3263f00026b0b48)**

1.) UserAgent: (please keep this as it is)
* Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

2.) What Tampermonkey version do you use? (go to 'chrome://extensions/' for that information)
* 3.12.58

3.) Is this the browser where the problem occurs? If not: What browser version (go to 'chrome://chrome/') and operating system do you use?
* See user agent

4.) Does a Userscript cause the problem? If so, from where can it be downloaded?
* No

5.) Did this work before? Have you checked the script's bug tracker/discussion page for that problem?
* Yes, many versions ago. Don't know when it stopped working.

6.) Are there other Userscripts installed and running?
* Yes. But this is not related (Still occurs from a blank profile)

7.) Steps to reproduce the problem:
* a. Create a script with relative @require(s). i.e:
```
// @require ./lib/jquery-2.1.1.min.js
// @require ./lib/purl.js
// @require ./lib/cheet.min.js
```

* b. Host the script and resources in a folder on a file server or shared folder. Example: \\myserver\myscriptfolder\myscript.tamper.js

* c. Drag the script in chrome and install it

8.) What is the expected behavior? What went wrong?
* Expected: The script gets installed and the resources are downloaded.
* Actual result: The script is installed but the resources failed to be downloaded

9.) Please provide any additional information below.

* I've attached a screenshot of the tampermonkey extension debugger.

* From what I understand the issue comes from the resources being downloaded from a file:/// instead of file:// (notice the 3 slashes instead of 2).

* My script lives at file://myserver/path/to/script/folder/myScript.tamper.js but my resources are downloaded from file:///myServer/path/to/script/folder/lib/ (notice the 3 slashes).

* "file:///" is equivalent to "file://localhost/", which is incorrect in this case.

* This issue was not happening in the past and nothing changed on my side. I only noticed it because I needed to install the script on a new computer. The exact same script is still working as expected on computers where it has been installed a while ago.

![file protocol issue](https://cloud.githubusercontent.com/assets/6980921/13478013/1242b4ba-e123-11e5-8858-7c587e9e358b.png)

**Comment by derjanb** [comment]
Fixed. :) http://tampermonkey.net/changelog.php?version=4.0.5099&ext=gcal
