### ISSUE TITLE
DO NOT CLOSE TAB ON SAVE!!!!

### ISSUE THREAD

**Issue by DerekZiemba** [Tampermonkey/tampermonkey#270]
Just lost a pretty big script I was working on because Tampermonkey closed the editor on save.  Unbelievable. 

I pasted the wrong script Sublime into TamperMonkey, which overwrote my work.  Upon saving it completely the tab closed and I couldn't Ctrl+z.

**Comment by derjanb** [comment]
Fixed: http://tampermonkey.net/changelog.php?version=4.0.5103&ext=gcal

**Comment by Sentero-esp12** [comment]
It still closes the tab for me the first time I save a new script. Is there any option to disable this?
