### ISSUE TITLE
Tampermonkey in chrome is conflict with the extension "Kaspersky Protection"

### ISSUE THREAD

**Issue by mickey464376** [Tampermonkey/tampermonkey#272]
![default](https://cloud.githubusercontent.com/assets/8627068/13624630/e9a6a9cc-e5ea-11e5-8241-91e311174344.PNG)

i don't know how to deal with it

**Comment by derjanb** [comment]
Unfortunately this can not be solved by Tampermonkey, because this is a Chrome limitation:
https://bugs.chromium.org/p/chromium/issues/detail?id=391128

**Comment by drhouse** [comment]
If you want to make TM not modify the requests anymore, in settings you need to set its "Config mode" to "Advanced" and then disable the option "Add Tampermonkey to the site's content security policy (CSP).

https://forum.tampermonkey.net/viewtopic.php?t=1985

**Comment by derjanb** [comment]
> If you want to make TM not modify the requests anymore, in settings you need to set its "Config mode" to...

This does indeed prevent the message, but please note that changing this setting also might prevent Tampermonkey from executing your scripts at these pages!
