### ISSUE TITLE
Popup layout suggestions

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#273]
New popup layout is beautiful, however I have a few suggestions:
1. Add `Edit` to every script under the "More" icon, currently finding the script in dashboard list is quite bothersome when many scripts are installed
2. The "More" icon is not vertically centered to the script name on my PC
3. The script titles aren't aligned to the left - each one starts at different horizontal position as you can see on the screenshots 1-2 below (I've fixed it on the 3rd).
4. Do something to the background
   - Now:
     
     ![1-fs8](https://cloud.githubusercontent.com/assets/1310400/13773999/838679c0-eaad-11e5-875b-80f5c4695d00.png)
   - Suggestion 1:
     
     ![2-fs8](https://cloud.githubusercontent.com/assets/1310400/13774006/93e350ea-eaad-11e5-8f96-70fe6c91acbc.png)
     
     (Or use white for the overall background)
   - Suggestion 2:
     
     ![3-fs8](https://cloud.githubusercontent.com/assets/1310400/13774372/b785f44c-eaaf-11e5-85d9-941cde92510f.png)

**Comment by derjanb** [comment]
1) For the moment you can use Ctrl+click to achieve this
2) I've never seen this. Neither at Ubuntu nor MacOS nor Windows. However, I made a change which might fix this issue. Can you please verify? Thanks.
3) Should be fixed now
4) Everything else will be moved to the 4.1 release

http://tampermonkey.net/changelog.php?version=4.0.5137&ext=gcal

**Comment by tophf** [comment]
re 2: nailed it, Chrome breaks rendering of special font characters when DirectWrite is disabled.

Personally I hate DirectWrite font rendering as it's slighly blurrier than the standard GDI on Windows where fonts are 'hinted' to be displayed crisply on small font sizes. However DirectWrite is enabled by default and it correctly renders custom web fonts unlike GDI, so I guess I would have to switch to it one day anyway.

BTW, Github site [switched from custom fonts to SVG](https://github.com/blog/2112-delivering-octicons-with-svg) so I'd advocate to do the same at least for the reason of better pixel antialiasing.

**Comment by derjanb** [comment]
Ok, let's try again. :)

http://tampermonkey.net/changelog.php?version=4.0.5142&ext=gcal

**Comment by tophf** [comment]
Yay! Fixed.

**Comment by tophf** [comment]
1. It'd be nice to have GM_registerMenuCommand items right after the userscript (maybe below it on a separate differently styled line), currently it's not very clear that a userscript is configurable, especially for new users.
2. It'd be nice to have a mode when script icons are displayed instead of the on/off toggle, which is used rarely I think. The switch could go to the action menu (three-dot) for all I care.

I understand these are quite radical changes, of course. So what about allowing us use custom CSS for the popup? It's trivial to implement: a textbox in settings and a simple style injection. Some extensions do that (Feedly Notifier, and naturally Stylish), it's awesome. For example, I'd like to reduce the height of items in the popup to avoid scrolling on pages with many enabled userscripts.

**Comment by derjanb** [comment]
>  So what about allowing us use custom CSS for the popup?
Sounds good.

**Comment by derjanb** [comment]
> So what about allowing us use custom CSS for the popup?

Implemented at [the latest beta](http://tampermonkey.net/changelog.php?version=4.3.5403&ext=gcal)

**Comment by tophf** [comment]
![clip192](https://cloud.githubusercontent.com/assets/1310400/22996960/aa4ddad8-f3e1-11e6-828f-d3a26e82aa99.png)

**Comment by derjanb** [comment]
Spartanic, but I understand your point of view. 😄

**Comment by tophf** [comment]
:smile: It would look better if the userscripts icons were shown. However, I doubt you'll implement it because icons don't fit in the default layout.
