### ISSUE TITLE
Agar.io keeps refreshing when Tampermonkey is enabled. [El Capitan Safari]

### ISSUE THREAD

**Issue by Eybster** [Tampermonkey/tampermonkey#274]
The scripts I am using: 
1) AgarioMods evergreen script
2) AgarioMods script

This is very irritating because game modes such as Hunger Games can only be played using these (if only one of them is required, please tell me which one I should remove and which one is better) mods. 

When I enter Agar io after enabling Tampermonkey, the screen keeps refreshing and I am not able to play. I am playing on a Mac and in Safari by the way, but this didn't use to happen.

**Comment by derjanb** [comment]
Do you see the same behavior when all scripts are disabled?

**Comment by XtremePlayzCODE** [comment]
Evergreen AND non-evergreen shouldn't be on at the same time.

**Comment by derjanb** [comment]
I assume this is the solution. Closing this now. Please re-open if there is anything left to do for me.
