### ISSUE TITLE
CPU 100% when try to change position of script

### ISSUE THREAD

**Issue by CrendKing** [Tampermonkey/tampermonkey#275]
Noticed this in the latest 4.0. First install the YouTubeCenter dev build (https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version), then drag any other script, and hover on the YouTubeCenter script, the page will hang and CPU usage stays 100% for that core. I need to kill the process and reload the extension. I can drag YouTubeCenter to any other place without problem. Also, the dropdown in script's settings page works for all scripts.

It looks like some bug in the drag and drop handler. Is it because YouTubeCenter is a large script?

**Comment by derjanb** [comment]
This was caused by some element height miscalculation due to the recently introduced grey borders.

Fixed. http://tampermonkey.net/changelog.php?version=4.1.5165&ext=gcal
