### ISSUE TITLE
visiting a long data url stalls the extension

### ISSUE THREAD

**Issue by epicgirl1998** [Tampermonkey/tampermonkey#276]
so i made a script that would request some json data and display it in a new tab

i noticed that using it would cause all subsequent page loads to hang with "waiting for tampermonkey" until i restarted the extension

here's an example of it:

```javascript
// ==UserScript==
// @name         test
// @match        http://example.com/
// @grant        GM_registerMenuCommand
// ==/UserScript==

var SIZE = 1000;

GM_registerMenuCommand("test", function () {
	var data = Array(SIZE).fill(true);
	var json = JSON.stringify(data, undefined, "    ");
	var dataurl = "data:application/json;base64," + btoa(json);
	location.href = dataurl;
});
```

1. install this script
2. open http://example.com/
3. click the menu command

tampermonkey should now be frozen for ~8 seconds (probably depends on your cpu)

increasing the value of the `SIZE` variable makes it be frozen for longer (try `2000`, `3000`...)

my chrome and tampermonkey are both the latest available stable version

**Comment by derjanb** [comment]
> my chrome and tampermonkey are both the latest available stable version
Latest available versions do change over time. ;) Do you use 3.11.58, 4.0 or 4.0.10?

**Comment by epicgirl1998** [comment]
4.0.10

the beta version also seemed to have the issue though

**Comment by derjanb** [comment]
Thanks for reporting. http://tampermonkey.net/changelog.php?version=4.1.5175&ext=gcal
