### ISSUE TITLE
Syntax checking and template strings

### ISSUE THREAD

**Issue by trlkly** [Tampermonkey/tampermonkey#277]
It would be nice if the syntax checker in the script editor understood template strings (which start and end with `, and can take up multiple lines.

Right now, it complains that the character is illegal, then complains of multiple syntax errors if the string takes up more than one line. 

I do note that template strings do actually work when the script is run.

**Comment by derjanb** [comment]
Please post an example. What TM version?

**Comment by trlkly** [comment]
Sure. It's TamperMonkey 4.0.10 on Chromium 49.0.2623.108 on Linux 32-bit. Here's the type of code I tend to use template strings for:

    var style = document.createElement('style'); style.textContent = `
        .comment-permalink { display: initial !important; }
        textarea#comment { width: 98.5%; }
        #sidebar-left { padding-right: 0px; }
        .narrowcolumn { padding: 0; width: 510px; }
        textarea { resize: vertical !important; }
    `; document.head.appendChild(style);

And this is what I see in the editor:
![tampermonkey-template-quotes](https://cloud.githubusercontent.com/assets/5460654/14242887/ecabf2c6-fa17-11e5-9c22-166db801c810.png)

(The warnings on the top and bottom say ``Unexpected '`'.``)

<sup>And if you wonder why I don't use GM_addStyle, it's so I can use `@grant none`</sup>

**Comment by epicgirl1998** [comment]
you need to enable `esnext` mode

put this somewhere in your code:

    /* jshint esnext:true */

IMO it should be on by default as chrome already supports like 99% of the features in es6

**Comment by derjanb** [comment]
You are right. ```esnext``` now is enabled by default:
http://tampermonkey.net/changelog.php?version=4.1.5175&ext=gcal
