### ISSUE TITLE
Strong mode is going away, so remove it

### ISSUE THREAD

**Issue by epicgirl1998** [Tampermonkey/tampermonkey#278]
it would be good if there was a setting to do `console.time` and `console.timeEnd` ([mdn page]) before and after running each script to see how long they take to run

like how there already is an option for "debug scripts"

```javascript
console.time("script name");
setTimeout(function () {
	console.timeEnd("script name");
}, 100);
// logs something like: `script name: 100.000ms`
```

also, [strong mode is going away] so you might want to remove the option for it

[mdn page]: https://developer.mozilla.org/en-US/docs/Web/API/Console/time
[strong mode is going away]: https://groups.google.com/forum/#!msg/strengthen-js/ojj3TDxbHpQ/5ENNAiUzEgAJ

**Comment by derjanb** [comment]
As you can see at your own example: TM can't know when the script "ended". Which timeout is the last one? This is impossible to know.
You have to add ```console.time``` and ```console.timeEnd``` manually. 

However, thanks for the strong mode hint.

**Comment by epicgirl1998** [comment]
> As you can see at your own example: TM can't know when the script "ended". Which timeout is the last one? This is impossible to know.

it's just an example of how the `time` functions work

the setting would only apply to the synchronously executed part of scripts

it might be useful for finding out what scripts are affecting page load performance (js is single-threaded and blocks rendering after all)

**Comment by derjanb** [comment]
OK, I got it. When "debug scripts" is enabled then also the script timing is done. So you need to have the dev tools closed when reloading the tab. Then you can open it and check the timing issues.
Strong mode is also removed.
http://tampermonkey.net/changelog.php?version=4.1.5180&show=gcal
