### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by GreenLunar** [Tampermonkey/tampermonkey#280]
> the update check will now never run more than once per hour except it was triggered by a user action

From: https://github.com/OpenUserJs/OpenUserJS.org/issues/944#issuecomment-207865477

I think, a check per a couple of days is a sensible minimum interval to check for updates.

**Comment by derjanb** [comment]
1h is the safety net to never allow endless happening automatic checks again. The configurable minimum interval is 6h. However, the user can do it more often by initiating a manual check.
