### ISSUE TITLE
Dolphin add-on problem

### ISSUE THREAD

**Issue by maynak00** [Tampermonkey/tampermonkey#281]
Hi. I can't install userscript to Tampermonkey Dolphin 4.0 (with Install button in tampermonkey.not found in installed userscripts page)
I tried:
https://greasyfork.org/scripts/4294-antiadware/code/AntiAdware.user.js
https://raw.githubusercontent.com/HandyUserscripts/AntiAdware/master/AntiAdware.user.js
(also I reported to https://github.com/HandyUserscripts/AntiAdware/issues/31#issuecomment-208850522)

**Comment by derjanb** [comment]
Only very few users are using TM Dolphin now...
