### ISSUE TITLE
Changelog does not show release date

### ISSUE THREAD

**Issue by SamHasler** [Tampermonkey/tampermonkey#282]
This page: http://tampermonkey.net/changelog.php?ext=dhdg

does not show release dates. This makes it hard to know what releases to look through when tampermonkey updates, or when trying to work out when a script broke.

e.g.: I have a written a userscript for a website that I visit infrequently. Upon revisiting it I notice that the userscript is now broken. I know I last when to this website 2 months ago. Which releases notes for tampermonkey do I need to look through to see what might have caused the issue?

**Comment by derjanb** [comment]
Finally fixed. :)
