### ISSUE TITLE
@connect should include self by default

### ISSUE THREAD

**Issue by Watilin** [Tampermonkey/tampermonkey#283]
Hi,

the new `@connect` metadata behaves in a non intuitive way: when you set it, requests to the current domain are not allowed anymore. One have to explicitely add `@connect self`.
This is non intuitive in comparison with the regular, unpriviledged `XMLHttpRequest` which can send requests to the current domain without need for any authorization.

**Comment by derjanb** [comment]
Already fixed at the beta version and will be ported to the next 4.0.x release.

**Comment by Watilin** [comment]
Ok, great :)

**Comment by derjanb** [comment]
http://tampermonkey.net/changelog.php?version=4.0.69&show=dhdg
