### ISSUE TITLE
Non allowed x-domain requests should not be 403 errors

### ISSUE THREAD

**Issue by Watilin** [Tampermonkey/tampermonkey#284]
`HTTP 403` is a server response code. To receive it implies that the request did occur. Issuing a 403 whereas the request has been aborted is kinda deceptive.

Using the unpriviledged `XMLHttpRequest`, when performing a non allowed cross-domain request, the user is given an error message and the request object’s `status` code is `0`.
Likewise, `GM_xmlhttpRequest` should raise an error instead of issuing a 403 when the request is not allowed.

Here’s an example of error message:
> XMLHttpRequest cannot load `http://example-b.com/`. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin `'http://example-a.com'` is therefore not allowed access.

**Comment by derjanb** [comment]
Fixed at the beta version: http://tampermonkey.net/changelog.php?version=4.1.5210&ext=gcal

**Comment by derjanb** [comment]
http://tampermonkey.net/changelog.php?version=4.0.69&show=dhdg
