### ISSUE TITLE
[HELP] // ==UserScript== and how to detect

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Tampermonkey/tampermonkey#285]
I am a developer and I would like to design something like this. How do I detect things like:
// ==UserScript==
and
// @name: TestExtension
?

**Comment by derjanb** [comment]
To be honest: I have no idea what you want to detect. ```// ==UserScript==``` is usually just a comment and interpreted as the start of your userscripts header. ```// @name: TestExtension``` needs to be written without ```:``` and represents the name of you script. You can access it via ```GM_info```.

Please re-open this one if you feel that there is anything I should do.

**Comment by XtremePlayzCODE** [comment]
I want to detect the name and stuff so I could use it later. But I could find other ways, thanks for helping. :)
