### ISSUE TITLE
Cross browser sync

### ISSUE THREAD

**Issue by ivysrono** [Tampermonkey/tampermonkey#288]
There is not this feature in firefox 46.0, Tampermonkey BETA 4.0.5054

By the way, would you support sync scripts between firefox and chrome? Just like Xmarks/Lastpass.

**Comment by derjanb** [comment]
It still needs some time until FF implements chrome.storage.sync: https://bugzilla.mozilla.org/show_bug.cgi?id=1220494

However, this will allow only a per-browser sync.

**Comment by derjanb** [comment]
I'll check how difficult it is to implement a sync via Dropbox or something similar.

**Comment by renyouguo** [comment]
Violent monkey sync via onedrive/dropbox between chromes and operas.
If you can sync between firefox and chrome,Great!

**Comment by derjanb** [comment]
The latest beta allows backup and restore via some cloud storages (Google Drive, Dropbox and OneDrive). I know its not exactly the same, but it should ease the pain a little bit.

**Comment by derjanb** [comment]
The [latest beta version](http://tampermonkey.net/changelog.php?version=4.4.5484&ext=gcal) now supports syncing your scripts from and to Google Drive. More cloud storage services will follow. Please note that this implementation is in experimental state. So backups are very good idea... ;)
