### ISSUE TITLE
Install script from URL (Chrome)?

### ISSUE THREAD

**Issue by deanishe** [Tampermonkey/tampermonkey#289]
How do I install a userscript in Tampermokey for Chrome from a URL?

Pasting the URL into the Omnibox (as recommended in the FAQ) just results in a Chrome error (you can't install extensions from this site).

Tampermonkey itself doesn't appear to offer an "install from URL" feature.

**Comment by derjanb** [comment]
At the "Utilities" tab there is a input field named "URL" with an "Import" button.

However, pasting the URL into the Omnibox should work. Can you tell me the URL?

**Comment by deanishe** [comment]
My bad. I tried the Utilities > URL box, but I had accidentally overwritten the userscript with the contents of the meta.js file and was getting a `This script does not provide any @include information` error. 

Fixed and everything working now. Also from the Omnibox.

Sorry for wasting your time.

**Comment by eadmaster** [comment]
the most intuitive location for that button should be in the "Installed Userscript" tab, or maybe in the userscript code editor (File->Open from URL...)
