### ISSUE TITLE
Don't override browser keybindings in script editor

### ISSUE THREAD

**Issue by cpcallen** [Tampermonkey/tampermonkey#292]
I was recently using Tampermonkey to edit [a script to prevent the WMD Stackexchange markdown editor from overriding my browser's default keybindings](https://meta.stackexchange.com/questions/2980/is-there-a-way-to-disable-the-hotkeys), when I discovered that *the Tampermonkey editor itself does this* for certain commoly-used emacs keybindings otherwise properly supported by Chrome (including at least C-k and C-d, which should delete to end of line and delete current character, respectively, but are heinously overridden to toggle comment and delete whole line instead).

Please do not override editor keybindings, or at least provide an easy-to-find preference option to disable such overrides.

I was going to write a Tampermonkey script to prevent Tampermonkey from overriding key bindings, but it seems that user scripts cannot modify chrome-extension: URL scheme pages…  :-(

**Comment by derjanb** [comment]
Please set the "Config mode" setting to "Advanced". Then you'll see an "Editor" section. There you can change the "Key Mapping". There also is a tab called "Help" with all current keybindings. 

Please re-open this issue if something is missing.

**Comment by cpcallen** [comment]
Oh, nice!
