### ISSUE TITLE
Tampermonkey extension update issue

### ISSUE THREAD

**Issue by mozkan007** [Tampermonkey/tampermonkey#293]
Hi.I am using Tampermonkey v4.0.25 on Chrome v50.I am trying to update Tampermonkey clicking update extension now button from v4.0.25 to v4.0.69 but it does not update.How can solve this issue?

**Comment by derjanb** [comment]
Updates are distributed to an low percentage of people first and then to an over time increasing number of users. This is done to not deploy a maybe faulty version to all users.

You can download the current version with one of the many crx downloaders out there or from here:
https://tampermonkey.net/test/versions/stable/4.0.69/f3ea8490c/dhdgffkkebhmkfjojejmpbldmpobfkfo_main.crx

Then you have to drag and drop the file to Chrome's extension overview page.

**Comment by mozkan007** [comment]
Ok.It is done.Thank you.
