### ISSUE TITLE
GM_xhr only supports string urls

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#294]
chrome 50.0.2661.102 stable, TM v4.0.69 stable

1. navigate to http://example.com/ and install the script below:

```javascript
// ==UserScript==
// @name         test
// @match        http://example.com/
// @grant        GM_xmlhttpRequest
// ==/UserScript==

var events = ["load", "error", "readystatechange", "progress", "loadstart", "timeout"];

test(location.href, "location.href");
test(location, "location object");
test(new URL(location.href), "url object");

function test (url, urldescription) {
	var init = {
		method: "GET",
		url: url,
	};
	for (let event of events) {
		init["on" + event] = request =>
			console.log("request to %s: %s event fired", urldescription, event);
	}
	GM_xmlhttpRequest(init);
}
```

the request to location.href succeeds, and the other two fail silently

![image](https://cloud.githubusercontent.com/assets/18557590/15365128/c333a1ae-1d27-11e6-9418-fbaa69d8c9e4.png)

this was in the background page's console:

![image](https://cloud.githubusercontent.com/assets/18557590/15364735/5597f9ca-1d26-11e6-8cf1-972e84d7ae28.png)

i'm guessing it expects the urls to be strings only, and the location and url objects were turned into plain objects when sending them to the background page

XMLHttpRequest and fetch both support location and url objects iirc so i think GM_xhr should too

**Comment by derjanb** [comment]
Fixed at the latest TM beta version: http://tampermonkey.net/changelog.php?version=4.1.5240&ext=gcal
