### ISSUE TITLE
GM_xhr.fetch messes up response headers

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#295]
chrome 50.0.2661.102 stable, TM v4.0.69 stable

1. navigate to http://example.com/ and install the script below:

```javascript
// ==UserScript==
// @name         test
// @match        http://example.com/
// @grant        GM_xmlhttpRequest
// ==/UserScript==

test(false);
test(true);

function test (useFetch) {
	var using = useFetch ? "fetch" : "xhr";
	GM_xmlhttpRequest({
		method: "GET",
		url: "http://example.com/",
		fetch: useFetch,
		onload (request) {
			console.info(
				"response headers using %s:\n%c%s",
				using,
				"color: blue",
				request.responseHeaders);
		}
	});
}
```

![image](https://cloud.githubusercontent.com/assets/18557590/15365705/e446840e-1d29-11e6-9ef4-ea24c95bd2e8.png)

the two requests are identical in the background page's dev tools network tab, so it must be a bug in how the extension handles the headers

**Comment by derjanb** [comment]
Regarding the number of headers please see: https://fetch.spec.whatwg.org/#forbidden-header-name

**Comment by derjanb** [comment]
Fixed at the latest TM beta version: http://tampermonkey.net/changelog.php?version=4.1.5240&ext=gcal
