### ISSUE TITLE
Safari: Script unable to bypass CSP

### ISSUE THREAD

**Issue by silverwind** [Tampermonkey/tampermonkey#296]
Using Tampermonkey 4.1 on Safari 9.1.1, a userscript seems unable to bypass a site's CSP, like for github.com in our case ([here's](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark-Script/master/github-dark-script.user.js) the script). This error is being logged in the console:

```
GitHub-Dark-Script:0 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com".
```

I've been searching for an option menu with the CSP option, but there appears to be none available in the Safari version of this extension.

Ref: https://github.com/StylishThemes/GitHub-Dark-Script/issues/13

**Comment by derjanb** [comment]
According to the CSP spec a CSP should not interfere with extensions and add-ons [1], but Safari doesn't care and stops Tampermonkey when it injects a script into the page. 

Unfortunately there is nothing I can do to fix this. So this actually this is more a "can't fix" than a "won't fix".

[1] https://www.w3.org/TR/CSP3/#extensions

**Comment by legendtang** [comment]
@derjanb I'm also curious why some adblocker extensions and some extensions that is actually a wrapper for some scripts work like a charm?

**Comment by derjanb** [comment]
@legendtang Can you please send a link to such an extension? 
I assume they're running the script within the extension context, which is fine until the script uses extension functionality to modify the extension storage and for example installs a second script without user interaction.

**Comment by legendtang** [comment]
@derjanb For example, uBlock Origin https://github.com/gorhill/uBlock
In advanced options, they even allow you to change the website dynamically.

**Comment by derjanb** [comment]
@legendtang I have issues to find out how to define a custom JavaScript that is injected into the page. Can you please give some guidance or send a backup with that for example injects ```alert('foo')``` into every page?

**Comment by legendtang** [comment]
@derjanb They're restricting the use of external scripts and only applying pre-defined rule-based scripts in [resource.txt](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt) instead. But it will **not work** in CSP websites.

Don't be so upset. Below is what exactly I noticed the behaviors. There're some extensions already achieving that. https://github.com/Safari-FIDO-U2F/Safari-FIDO-U2F/issues/26#issuecomment-356762829 This extensions do successfully loaded the script on any websites, even for CSP-enabled GitHub. The `bridge.js` is doing the real magic. You may take a glance of that.

**Comment by derjanb** [comment]
> So does this mean that no userscript will ever work in Safari?

No, it means a site with a very strict CSP _can_ prevent scripts from running or prevent some features from working.

**Comment by michaelmesser** [comment]
I think Userscripts solves this by using eval instead of creating a script tag when @inject-into content is in the script. https://github.com/quoid/userscripts/blob/14297fb38e46dc5f5a51a857d9c8f034a69b8730/extension/Userscripts%20Extension/UserscriptsSafari.js#L33

**Comment by amityweb** [comment]
Hi @michaelmesser are you saying there is a solution to this issue? 

I only use Tampermonkey to add CSS to webpages to customise them. 

I use a addGlobalStyle function to add the style, but the script is blocked. 

I tried another app to add CSS called Cascadea and that works fine. 
https://apps.apple.com/app/cascadea/id1432182561

So it is possible to at least inject CSS into webpages. I dont know if Tampermonkey has another working way, or just does not implement the same way as Cascadea does it.

**Comment by jesus2099** [comment]
@amityweb, if you only need custom CSS, you could use [Stylus](https://github.com/openstyles/stylus). 
Here is a random [example user stylesheet](https://github.com/jesus2099/konami-command/blob/master/facebook_NO-CONNECT-NAG.user.css), that runs with Stylus.

**Comment by codeninja-ru** [comment]
> I think Userscripts solves this by using eval instead of creating a script tag when @inject-into content is in the script. https://github.com/quoid/userscripts/blob/14297fb38e46dc5f5a51a857d9c8f034a69b8730/extension/Userscripts%20Extension/UserscriptsSafari.js#L33

so it’s possible. unfortunately I cannot install userscripts since it requires mac v12

**Comment by krystian3w** [comment]
But may fail with disabled relax mode in 4.20 - I must found solution to move this to anohter addon.

**Comment by deevroman** [comment]
Apologies for necroposting, but I recently discovered a workaround for Safari to add CSS on a website with an even stricter CSP than GitHub, namely openstreetmap.org

If the page has a `<style>` element, you can add your own CSS to innerText. 

```js
// ==UserScript==
// @name         Safari CSS workaround
// @match        https://www.openstreetmap.org/*
// @match        https://github.com/*
// @grant        GM_addElement
// @grant        GM_addStyle
// ==/UserScript==

console.log("start");
const styleText = `* { color: red; } `;

// works on GitHub and OpenStreetMap.
document.querySelector("style").innerHTML += styleText;

// works only on GitHub
// GM_addElement(document.head, "style", { textContent: styleText });
```

The advantage of this method is that it works not only in TamperMonkey, but also in GreasyMonkey and Userscripts for Safari. I hope this will be useful to someone.

p.s. of course, not all CSS will work, for example, you will not be able to add new fonts, this is a separate problem https://github.com/w3c/webextensions/issues/839
