### ISSUE TITLE
GM_xhr returns undefined

### ISSUE THREAD

**Issue by ccloli** [Tampermonkey/tampermonkey#297]
On earlier versions, when calling `GM_xmlhttpRequest` it should return an object that contains an `abort()` method to stop GM_xhr request, but it now returns `undefined` so that we can't use `abort()` method or even makes script stop working.
![qq 20160531223233](https://cloud.githubusercontent.com/assets/8115912/15678103/9ed24560-277f-11e6-84df-ebd4436f5927.png)

It works fine in Tampermonkey Stable (v4.0.69):
![qq 20160531224227](https://cloud.githubusercontent.com/assets/8115912/15678447/f90d07bc-2780-11e6-9386-d747b101d90c.png)

User-Agent:
`Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36`

Tampermonkey Version: `BETA v4.1.5240`

Example Script:
```js
// ==UserScript==
// @name         GM_xhr test
// @version      1.0
// @include      http://*
// @grant        GM_xmlhttpRequest
// @connect      *
// ==/UserScript==

var url = 'http://localhost/test.mp3';

var xhr = GM_xmlhttpRequest({
    method: 'GET',
    url: url,
    responseType: 'arraybuffer',
    timeout: 10000,
    onload: function(res){
        var t = new Date();
        console.log('File loaded at ' + t);
    },
    onerror: function(res){
        console.log('Can\'t load file.');
    },
    ontimeout: function(){
        console.log('Request timed out!');
    }
});

console.log(xhr);
console.log("Request started!");

setTimeout(function(){
    xhr.abort();
    console.log("Request aborted!");
}, 5000);
```

**Comment by derjanb** [comment]
http://tampermonkey.net/changelog.php?version=4.1.5248&show=gcal
