### ISSUE TITLE
script update doesn't apply to incognito session

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#299]
chrome 51.0.2704.79 stable, tampermonkey v4.0.69 stable
1. create a new userscript that logs "1" in the console
2. navigate to some page in incognito mode (`ctrl + shift + n`)
3. edit the script to log "2" instead
4. refresh the incognito tab

you should see "1" logged in the console

the current incognito session will continue using the older version of the script until you end it and start a new one

``` javascript
// ==UserScript==
// @name         test 123 abc
// @match        *://*/*
// @grant        none
// ==/UserScript==

console.log(1);
```

**Comment by derjanb** [comment]
FAI. Please set "Security" > "Store data in incognito mode" to "Permanent" in order to sync changes between normal and incognito mode tabs.

Note: there is a URL-based scripts to execute cache which will prevent you from seeing the new number being logged when doing a simple reload. You have to navigate to another URL to execute the new script.

**Comment by abernier** [comment]
ok, found option in `Settings` tab in `Advanced` config mode:
![image](https://user-images.githubusercontent.com/76580/41591756-ecd15c90-73ba-11e8-8020-926dd3e0b338.png)

Thank you

**Comment by derjanb** [comment]
@kmnvq Please set "Config Mode" to "Advanced".

**Comment by vanowm** [comment]
This setting doesn't exist in v5.1.1 ?

**Comment by usama-kabel** [comment]
The setting is exists already.
need first to change "Config mode" to Advanced 
then will see the option "Store data in incognito mode:" under Security Section

**Comment by WithoutPants** [comment]
To others who might have made the same mistake, `Store data in incognito mode` won't show up if you are _in_ incognito mode. Feels dumb in retrospect, but maybe including the disabled option but would make it clearer.
