### ISSUE TITLE
Do you ask what location to add the plug-in data storage, the use of file format to store it?

### ISSUE THREAD

**Issue by move132** [Tampermonkey/tampermonkey#301]
Do you ask what location to add the plug-in data storage, the use of file format to store it?

**Comment by derjanb** [comment]
I don't understand the question. Sorry.

**Comment by move132** [comment]
// ==UserScript==
// @name         vote
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @grant        none
// ==/UserScript==

Where is the script data stored in this file?

**Comment by derjanb** [comment]
What is script data? Do you mean the script's code? This depends on your Tampermonkey extension/app.

Do you use Chrome + Derivates, Safari, Firefox, Dolphin Browser or UCWeb to run Tampermonkey?
