### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by 788WAQAS** [Tampermonkey/tampermonkey#302]
Tampermonkey is not working properly on my facebook. I can,t download videos from my facebook account and i have installed tampermonkey 7 i aslo the added the extension to chrome and it,s enabled. Please sole this problem as fast as possible. Waqas Ahmad wARRAICH.

**Comment by derjanb** [comment]
Please give me a detailed description of what you're doing to reproduce the issue. 

Also there are several inconsistencies in your report:
* there is no Tampermonkey version 7
* Tampermonkey doesn't do anything without scripts
