### ISSUE TITLE
scripts with `@match http*://*/*` don't get the padlock icon

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#303]
chrome 51.0.2704.103 stable, tampermonkey v4.0.69 stable & v4.1.5248 beta

in "installed userscripts", scripts that run on `https:` pages have a padlock icon in the features column denoting that

this script runs on https://example.com/ pages but doesn't have the icon:

``` javascript
// ==UserScript==
// @name         test
// @match        http*://example.com/
// ==/UserScript==

// do nothing
```

**Comment by derjanb** [comment]
Your match pattern is invalid: https://developer.chrome.com/extensions/match_patterns

```@include``` instead of ```@match``` should work fine.

**Comment by derjanb** [comment]
Hmm, I'll check if I can detect such kind of includes to outline the https access.
