### ISSUE TITLE
Tampermonkey cause Jira to stop working

### ISSUE THREAD

**Issue by EddieLukeAtmey** [Tampermonkey/tampermonkey#305]
My company use jira to manage projects and everything. My jira page suddenly become very slow to response / not response / crash. As I investigate for a solution, I found it here:

https://jira.atlassian.com/browse/JRA-37268?focusedCommentId=752129&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-752129

As Kai Mechel mentioned, I also try to blacklist jira in tampermonkey setting, and then it works normaly again.

I don't know if this information is helpful or anything, nor requesting anything. Just mention here for you guys to check it later. (kinda like log a bug issue)

Regards.

**Comment by derjanb** [comment]
What Chrome version do you use? And do you have scripts installed (and running at JIRA)?

**Comment by EddieLukeAtmey** [comment]
Sorry for the late response, I use the latest chrome version (51.0.2704.103). I have some script install, but the only script that running at Jira is anti-AdBlock-killer (REEK).

**Comment by tophf** [comment]
And what happens if you disable that script in Tampermonkey popup/dashboard?

**Comment by EddieLukeAtmey** [comment]
I'm not sure about this anymore. I've removed Jira from black list (still haven't disable the script) and it work fine currently. Maybe Jira has cached data or some sort like that. I'll report later.
