### ISSUE TITLE
expose chrome.tabs.captureVisibleTab

### ISSUE THREAD

**Issue by jandob** [Tampermonkey/tampermonkey#307]
Any chance `chrome.tabs.captureVisibleTab` could be exposed in the tampermonkey api?

**Comment by derjanb** [comment]
What are possible use cases of this? Thanks.

**Comment by jandob** [comment]
I wanted to use it to make a screenshot of an element (without restrictions in terms of CORS/tainted canvas). Had to implement it as an extension instead...

**Comment by Andyyun1982** [comment]
ok

**Comment by velikashkin** [comment]
The same problem, canvas.toBlob & html2canvas not workable in the case of different domains and s.mydomen.com mydomen.com.
I would like to support.

**Comment by derjanb** [comment]
Seems like only few people are interested in this, sorry.

**Comment by ethernidee** [comment]
Tab screenshot API would be highly appreciated.
