### ISSUE TITLE
Content Security Policy and unsafeWindow

### ISSUE THREAD

**Issue by SamHasler** [Tampermonkey/tampermonkey#308]
If I try and run a script on github.com that uses `unsafeWindow` I get the following error in the console:

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com".

Chrome: Version 52.0.2743.116 m
TM: 4.1

**Comment by derjanb** [comment]
// ==UserScript==
    // @name       Github test
    // @namespace  http://use.i.E.your.homepage/
    // @version    0.7.1
    // @description  enter something useful
    // @match      *://github.com/*
    // @grant      unsafeWindow
    // @copyright  2012+, You
    // ==/UserScript==
    
    console.log(unsafeWindow);

is working fine here with:

Version 54.0.2824.0 dev
Version 52.0.2743.116 m
Version 51.0.2704.79 Ubuntu 16.04 (64-bit)

Do you have another extension installed that also tries to modify the response headers?

**Comment by SamHasler** [comment]
Yes, it must be another plugin causing the problem. If I view the page in incognito with only TM running the script works fine.

**Comment by derjanb** [comment]
I'm still not sure why it sometimes doesn't work for you, however #310 will fix it as a side effect.

**Comment by derjanb** [comment]
Can you please re-check with the latest beta? 
http://tampermonkey.net/changelog.php?version=4.2.5283&show=gcal

Thanks.
