### ISSUE TITLE
Script stopped working after installing Tampermonkey  4.1.10

### ISSUE THREAD

**Issue by jus7forfun** [Tampermonkey/tampermonkey#309]
Hi

After updating Tampermonkey to 4.1.10 this script stopped working: [https://greasyfork.org/en/scripts/19427-sort-remove-youtube-watch-later-list/code](url)
There is no problem with old versions and Tampermonkey-beta, except tampermonkey  4.1.10.

Thanks

**Comment by derjanb** [comment]
The script is not working at all for me. None of the key elements exists at the page. I also don't see anything that could break the script from beta to the stable build. Please retry with a new profile.

**Comment by jus7forfun** [comment]
worked fine with new profile, thanks

this scripts adds two new button (sort and clear) in this page: https://www.youtube.com/playlist?list=WL
