### ISSUE TITLE
Suggestion: Microsoft Edge support

### ISSUE THREAD

**Issue by vpontin** [Tampermonkey/tampermonkey#311]
As apparently is relatively easy to perform this conversion (as stated [here](https://github.com/pfn/passifox/issues/495)), there are plans to bring Tampermonkey to MS Edge?

Thanks in advance!

**Comment by derjanb** [comment]
It looks like Tampermonkey will be available at the Windows Store soon. I'll keep you posted.

**Comment by vpontin** [comment]
Thank you so much!

**Comment by lychichem** [comment]
So how the issue is going on? Maybe you can release a test pack for us to sideload it in edge to test it before ordinary users use it.

**Comment by derjanb** [comment]
You can simply try it out... ;)

http://tampermonkey.net/index.php?browser=edge
https://twitter.com/MSEdgeDev/status/771448889442316288

**Comment by vpontin** [comment]
THANK YOU SO MUCH FOR THIS!!!! <3
