### ISSUE TITLE
Salted HTTP header while using GM_xmlhttpRequest in Firefox

### ISSUE THREAD

**Issue by legnaleurc** [Tampermonkey/tampermonkey#313]
Just like #241 .

The headers become: `tm_xxxxxHost`, `tm_xxxxxOrigin`, `tm_xxxxxReferer`.

**Comment by derjanb** [comment]
Unfortunately this is a FF issue and I can't do anything to fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1273138

**Comment by derjanb** [comment]
Fixed at FF 52
