### ISSUE TITLE
[MS Edge] GM_xhr failed on MsEdge

### ISSUE THREAD

**Issue by tiansh** [Tampermonkey/tampermonkey#316]
GM_xhr failed on ms-edge browser:

``` javascript
// ==UserScript==
// @name        XHR Test
// @namespace   https://github.com/tiansh/
// @description test
// @include     *
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  'method': 'GET',
  'url': 'http://www.example.com/',
  'onload': function (resp) {
    alert(resp.responseText);
  },
  'onerror': function () {
    alert('error while xhr');
  }
});
```
1. Install this script
2. Open http://www.example.com/
3. Click <kbd>Allow</kbd>
4. Got alert

**Comment by derjanb** [comment]
Hmm, "unfortunately" this is working fine here. Can you please enable the developer mode and check the background page for errors, responsiveness, network errors, ...?  [This page](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/debugging-extensions/) explains how to get there after enabling the developer mode (hopefully).

![screenshot from 2016-09-03 19-29-05](https://cloud.githubusercontent.com/assets/767504/18226571/fd0140fa-720c-11e6-94b0-3d1d697b0120.png)

**Comment by tiansh** [comment]
After I enabled debugging and reinstalled this addon. the bug seems gone. I don't know why. But after I change the xhr target from example.com to localhost, it failed again...

```javascript
// ==UserScript==
// @name        XHR Test
// @namespace   https://github.com/tiansh/
// @description test
// @include     http://localhost/*
// @version     1
// @grant       GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
  'method': 'GET',
  'url': 'http://localhost/',
  'onload': function (resp) {
    alert(resp.responseText);
  },
  'onerror': function () {
    alert('error while xhr');
  }
});
```

visit http://localhost/

The background console print

> SCRIPT7002: XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。

(Network Error 0x2efd, could not complete the operation due to error 00002efd.)

**Comment by tiansh** [comment]
BTW, I was trying to debug another script, while it seems that GM_xhr do not send all cookies to server. I want to reproduce it in localhost, then I find all XHR was failed. So I try to do a simple possible XHR to example.com ... Please take a look on cookies also...

**Comment by tiansh** [comment]
This issue will no longer exist when Edge is based on Chromium.
