### ISSUE TITLE
[MS Edge] Import/export not working

### ISSUE THREAD

**Issue by Revadike** [Tampermonkey/tampermonkey#317]
For some reason, when I try to export on MS Edge, it won't let me download the file. It asks me what to do with the download (Save, Save As and Cancel with source; about:blob), but the save buttons don't do anything. It could be a bug with MS Edge itself, but I am able to download other things, while I can't for the tampermonkey export. Only TextArea export seems to work.

All importing options, don't work for me. When I try to load an export from chrome, it seems to work at first, but then after it's loaded/imported and asks me to install/import (ask.html) and confirm it, nothing is actually imported. I think it's either the file size problem (https://github.com/Tampermonkey/tampermonkey/issues/314) or faulty code for the importing handler.

**Comment by derjanb** [comment]
This is already mentioned at the [version notes](https://www.microsoft.com/en-us/store/p/tampermonkey/9nblggh5162s) (I agree that the formatting is kind of ugly).

However, cloud storage based export and import is working fine here. Is this this work for you?

**Comment by Royalgamer06** [comment]
Yes cloud based it working! Too bad chrome doesn't have cloud export. But I found a workaround by exporting as zip and manually upload it to the cloud.
Weird that it works like that, but other methods doesn't.

**Comment by derjanb** [comment]
@Royalgamer06 Cloud export is currently a "beta" feature, but the stable version will get it at the next release. 

OK, I found this issue at the Edge bug tracker, therefore I'll add the "external" flag, because this needs to be fixed in MS Edge.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8477778/
