### ISSUE TITLE
When going to Tampermonkey's options page the page is blank/white.

### ISSUE THREAD

**Issue by NaturalHarmonia** [Tampermonkey/tampermonkey#318]
I got my Tampermonkey 4.1.10 from the chrome web store.

![screenshot 47](https://cloud.githubusercontent.com/assets/16900516/18251517/22433de4-734f-11e6-84fc-1e3614d0bd26.png)

**Comment by derjanb** [comment]
What is your Chrome version? OS?

**Comment by NaturalHarmonia** [comment]
Windows 10 and Version 53.0.2785.89 beta-m.

**Comment by derjanb** [comment]
This combination is working fine here. Can you please check the background console for errors? [ This page](http://tampermonkey.net/faq.php#Q600) explains how to get there.

**Comment by NaturalHarmonia** [comment]
[dhdgffkkebhmkfjojejmpbldmpobfkfo-1473105127796.txt](https://github.com/Tampermonkey/tampermonkey/files/455563/dhdgffkkebhmkfjojejmpbldmpobfkfo-1473105127796.txt)

![screenshot 48](https://cloud.githubusercontent.com/assets/16900516/18256260/7eeb1412-7378-11e6-91b2-18150253a2ae.png)

**Comment by derjanb** [comment]
Well, the error messages indicate that Chrome can't find the extension files. This means something is really really broken.
Can you please [create a new temporary profile](https://support.google.com/chrome/answer/142059?hl=en) and install Tampermonkey again?

**Comment by NaturalHarmonia** [comment]
I installed Tampermonkey again a few days ago and everything is working now.
