### ISSUE TITLE
Hit Datebase II not showing weekly earnings correctly

### ISSUE THREAD

**Issue by KristeneT** [Tampermonkey/tampermonkey#320]
My Mturk Hit Database II suddenly is not showing weekly earnings correctly. It is only pulling the days earning into the weekly spot.

**Comment by tophf** [comment]
Why do you think it's Tampermonkey's fault/bug? 
I'd say this question should be directed to the userscript's author: 
https://greasyfork.org/scripts/11733-mturk-hit-database-mk-ii/feedback

**Comment by KristeneT** [comment]
Oh I thought I was directing it at the scripts author. I do not think it is
tampermonkey. I think it is a script error.
