### ISSUE TITLE
Auto repair when lost internet connection or other network error

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Tampermonkey/tampermonkey#323]
Can you add some simple mechanism to handle lost internet connection or other network error? Actually we can't do anything because script not run on error page. Step to reproduce:
1. Open some page, like google.com
2. Turn off internet connection.
In address bar we still see https://www.google.com but script not work and we can't do anything via Tampermonkey.

Maybe add some metadat config option, like `@refreshNetError someMiliseconds`, and when network error occur, adress from adress bar match to include/exclude TM rules then refresh tab after `someMiliseconds`. When our internet will work again then this refresh repair everything because we land on correct page and TM can work again. This is just an example, surely it can be done on xxx ways (like define `GM_netError` function).

Of course we can fix this with using other addons, but it is another unnecessary dependency. Or maybe there is in TM solution to handle network error but I don't know them?

**Comment by pyhedgehog** [comment]
GreaseMonkey (which we want to be compatible) decides not to do so: greasemonkey/greasemonkey#2436

**Comment by car24x7** [comment]
Looking for reliable [HVAC repair services in Winnipeg](https://cars24x7.ca/havc-repair-services-winnipeg/)? We've got you covered. Our expert team specializes in fast, professional HVAC repairs. They keep your home or business comfortable all year. Contact us today for efficient and affordable solutions!

**Comment by langren1353** [comment]
Have we reconsidered adding this feature?

This function does not have to given userscript to have this execution permission. It can be set to a built-in switch and turned off by default. Then the user can choose to turn on this function manually.
