### ISSUE TITLE
TM breaks AJAX requests on Chrome that use gzip Accept-Encoding

### ISSUE THREAD

**Issue by ganon0** [Tampermonkey/tampermonkey#324]
Hello,

Our company has an internal website we use for viewing code. In April of this year,  we received many reports around TamperMonkey causing this website to start breaking on AJAX requests in Chrome. At the time, users were told to either disable the plugin on chrome://settings (which works), or use a different browser.

This issue has resurfaced and I'm looking for a solution that allows users to keep TamperMonkey turned on. I unfortunately have no repro case I can provide; our website is not accessible outside of our network. However, I can give this information:
- It only impacts AJAX requests
- Using a different plugin (Modify Headers) that changes the Accept-Encoding request header from gzip to something else (like \* or a made up encoding) fixes the issue.
- Disabling TamperMonkey in the plugin settings does not resolve the issue; it only goes away if you disable the entire thing on Chrome settings.
- No changes to settings I tried impacted the behavior.
- The issue started in April, and has continued since then in spite of upgrades both to TM and Chrome.

Our website is a Django app running on Apache.

Any help or advice you can provide would be greatly appreciated.

**Comment by tophf** [comment]
Debug those requests by inspecting the headers and request/response contents:

* Tampermonkey's [background page devtools](https://stackoverflow.com/a/10258029) Network panel
* your django app (I don't know how it's debugged properly but there must be good methods)
* Fiddler proxy
* WireShark

**Comment by derjanb** [comment]
@ganon0 Sorry for the delay. I've checked the source and I'm not sure what exactly could cause your issues. 
Can you please send a screenshot (Ctrl+Shift+J -> Network tab) of such an AJAX request? You can blur all sensitive information if you want. The screenshot should look like this and show the request headers. Thanks. Jan

![image](https://cloud.githubusercontent.com/assets/767504/19215642/ad0abbfa-8da3-11e6-9c1e-83c35e5b6af4.png)

**Comment by derjanb** [comment]
@ganon0 I've changed a minor webRequest related issue [at the latest beta version](http://tampermonkey.net/changelog.php?version=4.2.5330&ext=gcal). I don't think that it could cause your issue, but please re-test this with version 4.2.5330. Thanks.

**Comment by ganon0** [comment]
Thank you so much for your response, and sorry it's taken so long to get back to you; we've been very busy on other things.. After some internal research, we've found a workaround that solves the problem for our users. We disabled our server's gzipping of response content for AJAX requests, and now our users are able to use TM with our internal website again.

Thanks,

ganon0
