### ISSUE TITLE
Dashboard Searc

### ISSUE THREAD

**Issue by TimidScript** [Tampermonkey/tampermonkey#326]
A search button in the dashboard to filter out the scripts by name

**Comment by derjanb** [comment]
You can press Ctrl+f or click at the sinkhole (shown at the upper left of this screenshot). 
Note: TM BETA 4.2.5336+ is required.

![image](https://cloud.githubusercontent.com/assets/767504/19558867/07fbc478-96cd-11e6-9e90-3442050e76f4.png)

**Comment by TimidScript** [comment]
I do not have beta yet. Will wait for the release.  Thank you.

**Comment by tophf** [comment]
The filtering is a great feature but it almost always fails to find anything for me when I search by a substring of a `@match` or `@include` or `@author`.

**Comment by derjanb** [comment]
```@author``` should work fine. Can you give me an example where it's not working?

```@match``` or ```@include``` can be searched by entering a URL. For example searching for "http://github.com/" will find scripts with an ```@include``` like ```http://github.com/```.

Maybe I'll add another filter that does a plain search in the includes.

**Comment by derjanb** [comment]
[Fixed](http://tampermonkey.net/changelog.php?version=4.2.5341&ext=gcal) :)
