### ISSUE TITLE
[MS Edge]Can't install JS after enable tampermonkey on Win10 Edge browser

### ISSUE THREAD

**Issue by zephyrxie** [Tampermonkey/tampermonkey#329]
Installed tampermonkey on Win10 Edge from Microsoft Store, then go to GreasyFork, browse to any JS, click "Install this script" button, but Edge only pop-up to just let me "save" or "save as" the JS page, not open it.

Please advise how to correctly install JS in Edge browser.

**Comment by derjanb** [comment]
What is your Windows build/MS Edge version?

**Comment by derjanb** [comment]
@zephyrxie ?

**Comment by nguyenhthai** [comment]
I can relate to this problem. Currently running on Windows 10 Anniversary, build 14393.447 with Edge version 38.14393.0.0. When going to sites that allow you to download like GreasyFork or OpenUserJS and install scripts, Edge can only ask for location to save the download file but not be able to activate the protocol _ms-browser-extension_ to call Tampermonkey to install those scripts. The only workaround that I found is that you need to directly go to the GitHub repo that hosts the script source (if available) and install from there by viewing the code in raw mode.

**Comment by derjanb** [comment]
@nguyenhthai Thank you very much for your reply. Do you have other extensions installed? If so, can you please disabled them an retry? Thanks.

**Comment by nguyenhthai** [comment]
Yes I was able to install scripts from GreasyFork and OpenUserJS (after little bit wait time, could be network issue) after installing Tampermonkey and disabling all other extensions.

**Comment by derjanb** [comment]
@nguyenhthai 

> OpenUserJS (after little bit wait time, could be network issue)

They use a very special type of DDoS protection. You can't install a script from the same IP address twice without waiting some time. https://github.com/OpenUserJs/OpenUserJS.org/issues/957#issuecomment-214201140

OK, that's somehow good news, because it means that this is another type of extension interference just like #319, but the other way around.

**Comment by ibrokemypie** [comment]
I am also unable to install userscripts on msEdge. Have tried disabling all other extensions and tried multiple sources, as well as restarting tampermonkey, still just pops up to save or save as.

**Comment by derjanb** [comment]
Updating to the Creators Update will fix the issue. Please re-open if someone can reproduce this at a Windows 10 build number higher than 15063. Thanks.
