### ISSUE TITLE
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

### ISSUE THREAD

**Issue by pendave** [Tampermonkey/tampermonkey#335]
How could GM_xmlhttpRequest fetch the 'Location' in the Response Headers?

It displays status:200 when I use GM_xmlhttpRequest, but actually it needs to be 302.

![xqpv_1 o9a o tosue_gg i](https://cloud.githubusercontent.com/assets/1331881/20587628/22e43eb2-b24a-11e6-8031-ca3ad79fd44f.png)

**Comment by derjanb** [comment]
[Redirects are handled transparently](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#infrastructure-for-the-send()-method), but you can use the finalUrl property of GM_xmlhttpRequest to detect redirects.

    var url = "http://google.com";
    GM_xmlhttpRequest ( {
        method: "GET",
        url: url,
        onload: function (response) {
            console.debug ('Redirected: ' + (url != response.finalUrl));
        }
    } );

**Comment by pendave** [comment]
Yes it reports:

Redirected: true

How can I get the real redirected URL?

**Comment by derjanb** [comment]
```response.finalUrl```

**Comment by pendave** [comment]
response.finalUrl is not the correct Location
