### ISSUE TITLE
[Firefox] Tampermonkey icon sometimes disappears

### ISSUE THREAD

**Issue by rcmero** [Tampermonkey/tampermonkey#337]
The button is still there, and I can still click on it, but the icon disappears for no reason. This often happens when no scripts are being executed.

![sem titulo](https://cloud.githubusercontent.com/assets/5708421/20667321/8e474da2-b560-11e6-8ea8-f5bccf612ad8.png)

**Comment by uBlock-user** [comment]
Yes, this happens on about:newtab page so far. Reproducible as well.

**Comment by rcmero** [comment]
Yes, this happens with many of Firefox's internal pages, but those aren't
the only ones. The above screenshot was taken from youtube.com.

**Comment by derjanb** [comment]
Fixed at the [latest (but not yet reviewed) beta version](https://addons.mozilla.org/en-Us/firefox/addon/tampermonkey/versions/?page=1#version-4.3.5384)
