### ISSUE TITLE
script can not run at iframe page

### ISSUE THREAD

**Issue by dosey** [Tampermonkey/tampermonkey#338]
I set the  script options [Run only in top frame:] Default.
the script can not run at iframe page .
And then I set the  script options [Run only in top frame:] No.
the script still can not run at iframe page .
Am I use TM with a wrong style ?

**Comment by derjanb** [comment]
@dosey Running scripts at iframes in general should work. There is an issue in case the iframe is reloaded or navigates to another URL. Is this the problem that you're seeing?

**Comment by dosey** [comment]
@derjanb :Yes,it is.
I knew it already fixed in the TM bate. 
thanks for your help again.
this issue will be closed

**Comment by dosey** [comment]
This problem is fixed in TM Beta 4.3.5358.
thanks.
