### ISSUE TITLE
Chrome: GM_xmlhttpRequest and relative URLs

### ISSUE THREAD

**Issue by silverwind** [Tampermonkey/tampermonkey#339]
It seems the behaviour of relative URLs in `GM_xmlhttpRequest` in Chrome is different than in Greasemonkey in Firefox. A URL like `"../file"` results in the current page being requested instead of the intended page, while in Greasemonkey for Firefox, it is able to correctly resolve the URL.

Observed in Tampermonkey v4.1.10, Chrome 57.0.2939.0 canary (64-bit)

**Comment by derjanb** [comment]
This should be fixed at the [latest beta version](http://tampermonkey.net/changelog.php?version=5364&ext=gcal).
