### ISSUE TITLE
Script does not rerun when iframe is reloaded v4.2

### ISSUE THREAD

**Issue by Dj-H** [Tampermonkey/tampermonkey#340]
I use a lot of userscripts in TamperMonkey that run within iframe. Today I found that when I would right click in the frame and select 'reload frame' my scripts would not rerun at all. 

Finally figured out this was v4.2 only, as I reverted back to v4.1.10 and everything is working as expected.

**Comment by derjanb** [comment]
A new version was released. You can download it from [here](https://test.tampermonkey.net/versions/stable/156a5e9/stable_4_2_7.crx) and drag and drop it to Chrome's extension page if it doesn't auto-update yet.

**Comment by Dj-H** [comment]
Thank you!
