### ISSUE TITLE
TM doesn't apply scripts to "homepage" on browser launch [Chrome]

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#345]
TM Beta, Latest Chrome stable

Homepage is set to Google, for which I have a couple scripts enabled. Scripts are not applied on browser launch. The page has to be refreshed for them to be applied.

**Comment by derjanb** [comment]
Works for me. Tested with Tampermonkey Stable and Beta (4.2.7/4.3.5364) and Chrome Version 56.0.2924.28, Version 57.0.2950.4 and Version 55.0.2883.87 at Windows 10 and Ubuntu 16.04.

What OS, Chrome Version, Scripts are you using?

**Comment by narcolepticinsomniac** [comment]
Tested in Chromium Stable Version 55.0.2883.87 (64-bit) and Dev Version 57.0.2952.0 (64-bit) with TM Beta Version 4.3.5364 on Win 8.1. 

I shouldn't imply that it never works, but more often than not, scripts fail to load on the homepage (Google) until the page is reloaded. Seems like a crap-shoot whether or not extensions are fully loaded before the page loads, and since I have quite a few extensions, the race is usually lost. Stylish used to be the same way, but they fixed it.

As far as the scripts, one is for opening links in a new tab, and one is a "scroll to top". Not sure how what their content is would affect whether they get injected, but neither is gigantic or anything. Happy to paste-dump if you really think it's a factor.

**Comment by narcolepticinsomniac** [comment]
Made a screen record to demonstrate: 
[TM.zip](https://github.com/Tampermonkey/tampermonkey/files/658691/TM.zip)

**Comment by tophf** [comment]
I've fixed Stylish. The issue was that Chrome lazy-loads background page of extension so content script should account for that and repeat any self-initiated message requests in case of null response.

**Comment by derjanb** [comment]
> so content script should account for that and repeat any self-initiated message requests in case of null response.

Tampermonkey works that way since 2012, but it checks for an ```undefined``` response. ;) But thank you very much for pointing me in that direction.
The issue is caused by a double script run protection which was added for #211. It simply prevents the repeated request data from being used. 🙄

Long story short: fixed at the latest beta. Thanks for reporting and all the hints.
