### ISSUE TITLE
[MS Edge] Cannot load script from private GitHub; infinite new tabs spawned

### ISSUE THREAD

**Issue by adaugherity** [Tampermonkey/tampermonkey#346]
(This is in Edge; not sure if it also applies to other browsers.)

I put a user script into a repo in our organization's private GitHub enterprise instance (which requires authenticating to view, even for so-called "public" repos; this is out of my control).

When browsing to my script in Edge, I get the "Invalid UserScript. Sry!" message.  Clicking the "Raw" button in GitHub causes an infinite amount of new tabs showing that same message to spawn, about one per second, and I have to close Edge completely.

I tried creating a Gist instead, and in that case, the "Raw" view of the script never loads, but the browser just spins indefinitely.

Workaround
====
Disable TamperMonkey extension; navigate to raw view of user script; enable TamperMonkey; refresh tab.  The script gets installed and works perfectly then.

**Comment by adaugherity** [comment]
Update: with the current versions of Tampermonkey (4.5.5570) and Edge (41.16299.15.0), I still get the "Invalid UserScript. Sry!" message when viewing scripts in our GitHub, but clicking Raw works and I can successfully install scripts!  No more infinite tabs, and no need to disable/re-enable Tampermonkey to avoid that.  Gist raw view also works.

So at least the major pain points are gone, and it's now just an annoying warning I can click past.

I also see this exact behavior ("Invalid UserScript. Sry!" on view; Raw works) with Chrome 61 so this at least does not appear to be Edge-specific.

**Comment by derjanb** [comment]
> I also see this exact behavior ("Invalid UserScript. Sry!" on view; Raw works) with Chrome 61 so this at least does not appear to be Edge-specific.

Chrome and Firefox should be fixed at [4.5.5597](http://tampermonkey.net/changelog.php?version=4.5.5597&ext=gcal). A new MS Edge version will be released soon.
