### ISSUE TITLE
[Microsoft Edge] Tampermonkey does not automatically ask to install script

### ISSUE THREAD

**Issue by rcmero** [Tampermonkey/tampermonkey#350]
When I click a link to a .user.js file, from say Greasyfork, Tampermonkey on Microsoft Edge does not ask me to install the script--Edge simply displays the script as a regular text file as if Tampermonkey is not installed. I need to copy the link to the script and access Tampermonkey's settings to install it from there.

**Comment by derjanb** [comment]
Please disable all other extensions and retry and see https://github.com/Tampermonkey/tampermonkey/issues/329#issuecomment-269178757 for more information.
