### ISSUE TITLE
Use external editor on firefox: Enable @require file://... support?

### ISSUE THREAD

**Issue by pmorch** [Tampermonkey/tampermonkey#351]
I've created the forum post [Use external editor on firefox: Enable @require file://... support?](https://forum.tampermonkey.net/viewtopic.php?f=17&t=2009&sid=00f1cb82cca0994482c990aad30a0631) without any comments for 5 days, so I'm guessing this is not (yet) supported. Therefore, I add this issue:

I'm trying to use the Firefox Tampermonkey extension.

For script development I want to use an external editor. So I follow the [FAQ](https://forum.tampermonkey.net/viewtopic.php?f=16&=78&p=693&hilit=Allow+access+to+file+URLs+firefox#p693). 
It and other places suggests:
> Goto Chromes extensions page, enable the "Allow access to file URLs" checkbox at the Tampermonkey item". But no, I'm on firefox. I don't see such a setting anywhere.

I've tried both of:

    // @require file:///home/peter/script.js
    // @require http://server/capmon/script.js

Only the last one works. If I look at file:///home/peter/script.js by itself in a new tab, the contents show up fine.

How do I use an external editor in firefox?

1.) UserAgent: (please keep this as it is)
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

2.) What Tampermonkey version do you use? (go to 'chrome://extensions/' for that information)
Version 4.3.5384.
On firefox!

3.) Is this the browser where the problem occurs?

Yes

4.) Does a Userscript cause the problem? If so, from where can it be downloaded?
Yes. It can't be downloaded anywhere. Anything with `// @require file://...` will do I think

**Comment by derjanb** [comment]
This is not implented by Firefox yet. Please see #347 for more information.

**Comment by pmorch** [comment]
Wups. Sorry for not noticing that.
