### ISSUE TITLE
[Bug] Error message in Chrome - Software conflict with uBlock Origin

### ISSUE THREAD

**Issue by kovacsattila-hun** [Tampermonkey/tampermonkey#353]
Sometimes unexpected error

![tampermonkey1](https://cloud.githubusercontent.com/assets/19515287/22746512/42b6098a-ee24-11e6-8369-52b95e2311ae.png)
![tampermonkey2](https://cloud.githubusercontent.com/assets/19515287/22746517/46e4bf74-ee24-11e6-8bc9-2fd33083c88f.png)

Latest Tampermonkey, Latest Chrome on Windows 10

**Comment by derjanb** [comment]
This is a Chrome limitation and can happen if a script is supposed to run and another extension tries to modify a network requests. Please see #272 and #85 for more details.
