### ISSUE TITLE
videos not playing on cnn.com

### ISSUE THREAD

**Issue by createconsume** [Tampermonkey/tampermonkey#354]
videos not playing on cnn.com...and other sites.

**Comment by derjanb** [comment]
What browser and Tampermonkey version?

**Comment by createconsume** [comment]
chrome. osx el capitan 10.11.6 (15G1217), tampermonkey 4.2.7

**Comment by derjanb** [comment]
This is working fine here with Chrome 56.0.2924.87 (64-bit) and OX El Capitan 10.11.6.
Can you please check the JavaScript console for errors?

**Comment by createconsume** [comment]
There were some errors. see screenshot.
![errors](https://cloud.githubusercontent.com/assets/25509342/22914486/b2eb54bc-f23e-11e6-979d-32df33705286.jpg)

**Comment by derjanb** [comment]
Is this still an issue? If so, please re-open.
