### ISSUE TITLE
Conflict with uBlock Origin

### ISSUE THREAD

**Issue by jimmydg** [Tampermonkey/tampermonkey#355]
Got this error on Chrome Version 56.0.2924.87 (64-bit)

> Warning:
> This extension failed to modify the response header "Content-Security-Policy" of a network request because the modification conflicted with another extension (uBlock Origin).

Extension versions:
Tampermonkey 4.2.7
uBlock Origin 1.11.0

**Comment by derjanb** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/353#issuecomment-278456508 for more information.

**Comment by Festum** [comment]
me2

**Comment by drhouse** [comment]
If you want to make TM not modify the requests anymore, in settings you need to set its "Config mode" to "Advanced" and then disable the option "Add Tampermonkey to the site's content security policy (CSP)".

https://forum.tampermonkey.net/viewtopic.php?t=1985

**Comment by ViperCode7** [comment]
Can't find the option mentioned above, must have been removed over the years.
