### ISSUE TITLE
Chrome hotkey to open dashboard

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#357]
It'd be nice to have a hotkey to open TM dashboard in addition to the activate/toggle hotkey.

On a related note, I think having a default hotkey like the current Ctrl+Shift+E is asking for trouble since extension hotkeys override site hotkeys, and Chrome doesn't send such hotkeys to webpage that may need it (text editors e.g. Microsoft Office Online, remote access, vim-like navigation, and so on). In modern Chrome versions (since at least 2015) the default hotkey isn't mandatory for the chrome.commands API.

**Comment by tophf** [comment]
The new hotkey commands are awesome!
This one in particular:

>Open the dashboard with the current tab's URL used as filter

**Comment by derjanb** [comment]
After this was implemented it felt as if the whole filter feature was just written for this command. 😁
