### ISSUE TITLE
[Firefox] TreeWalker doesn't work with @grant

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#360]
@Keith94 reported that Linkify Plus Plus script doesn't work under Firefox 54 with Tampermonkey (https://github.com/eight04/linkify-plus-plus/issues/7). After I fiddled around, I found that if you `@grant` something instead of `@grant none`, `TreeWalker` failed to return the correct result.

When using `@grant none`, this script correctly prints out the first text node.
```JavaScript
// ==UserScript==
// @name        test
// @version     0.0.0
// @namespace   eight04.blogspot.com
// @include     *
// @grant       none
// ==/UserScript==

var filter = {
    acceptNode(node) {
        if (node.nodeName == "WBR" || node.nodeType == 3) {
            return NodeFilter.FILTER_ACCEPT;
        }
        return NodeFilter.FILTER_SKIP;
    }
};
var walker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ELEMENT + NodeFilter.SHOW_TEXT,
    filter
);
console.log(walker.nextNode());
```

When using `@grant GM_getValue` or whatever, the result becomes `null`.

Firefox Nightly 54.0a1
Tampermonkey 4.3.5384

**Comment by derjanb** [comment]
Since you are Nightly user, you can get an unofficial, but fixed version from here: https://tampermonkey.net/xpi/46544b6d654f61/firefox-5410beta.xpi

It might take a little longer for the offical version to be fixed: https://github.com/Tampermonkey/tampermonkey/issues/352#issuecomment-285466789

**Comment by eight04** [comment]
Tried with nightly and it works!
