### ISSUE TITLE
[Firefox] Tampermonkey failed with CSP error

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#361]
Visit github.com, you can find an error in the console:
```
 Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'unsafe-eval' https://assets-cdn.github.com”). Source: (function (a,x,m,I){var c={safeWindow:{}....
```
And neither of the scripts works.

Firefox Nightly 54.0a1
Tampermonkey 4.3.5384
Windows 7

**Comment by derjanb** [comment]
The CSP issues are already fixed since 18 days ago. Unfortunately the AMO review lasts ages these days... https://github.com/Tampermonkey/tampermonkey/issues/352#issuecomment-277352469

**Comment by ulrichb** [comment]
Hmm ... I also get CSP errors in the F12 console for a site with script-src: 'self' CSP.

> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

Completely disabling Tampermonkey in the Add-On manager removes the errors. Note that blacklisting the site, or disabling Tampermonkey in the toolbar _does not_ remove these errors.

Tampermonkey: v4.8.5847 (Firefox)

Should I open a new issue?

**Comment by derjanb** [comment]
@ulrichb Yes, please open a new issue. Thanks.
