### ISSUE TITLE
Some problems about global

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#362]
Someone reported that [Linkify Plus Plus makes disqus fail to load](https://greasyfork.org/en/forum/discussion/18136/breaks-all-disqus-embedded-comment-sections-on-all-sites-for-some-reason). I found that it is because browserify would assign a `require` to global, and conflict with disqus. Here is an userscript to illustrate what happened (try it on [this page](https://disqus.com/embed/comments/?base=default&version=fbe5a2d3e47779b1f7a40136dabc24cf&f=ansiproject&t_i=5617&t_u=http%3A%2F%2Fansi.loli.tw%2Fansiarts%2F5617&t_d=%E9%AB%98%E6%B5%B7%E5%8D%83%E6%AD%8C%20-%20ansiProject%20-%20ansiProject&t_t=%E9%AB%98%E6%B5%B7%E5%8D%83%E6%AD%8C%20-%20ansiProject%20-%20ansiProject&s_o=default)):
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include	     *
// @grant        none
// ==/UserScript==

foo = "123";	// now you can access 'foo' from page script
console.log(typeof require);	// you can also access the variable defined by page script, if it is assigned to global
```
So, it seems that userscript share the same global with page script. Is it by-design or a bug?

**Comment by tophf** [comment]
This is exactly what `@grant none` does by design.

**Comment by eight04** [comment]
You can `@grant` other stuff instead of `@grant none`, the result won't change.

**Comment by tophf** [comment]
Houston we've got a problem. Could be an old one.
I've tested this:

```js
// ==UserScript==
// @name         Sandbox bug
// @include	     *
// @grant        GM_getValue
// ==/UserScript==

foo = "123"; 
console.log(require);
```

* With `@grant` other than `none`, the variable `foo` was never exposed (strictly speaking it's an expando property on `window`)
* On the first load the actual `require` object was displayed, also on normal refresh via F5, also on hard-refresh via Ctrl-F5 but with a 50/50 chance.

**Comment by derjanb** [comment]
> Is it by-design or a bug?

It's "by-design" because there is no way in JavaScript and with the currently usable APIs to catch such global variable declarations. But this can be solved by the userscripts:

```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include	     *
// @grant        GM_log
// ==/UserScript==

window.foo = '123';
this.bar = '123';

(function() {
    'use strict';
    blub = 1; // throws an error
})();
```

**Comment by eight04** [comment]
Currently I added a `var require;` statement to the script (https://github.com/eight04/linkify-plus-plus/blob/29058566a2a2eefc491cfabe706503d8ac937181/linkify-plus-plus.user.js#L31), but I'm not sure if it is the correct way to fix it, and will still work in the future.

**Comment by tophf** [comment]
@eight04, I think you should use `var` in the initial declaration inside linkify-plus-plus-core.js. Currently it adds an expando property in DOM `window`, which is shared with the page, and AFAIK this is the "correct" behavior from the standpoint of JavaScript in the absence of `'use strict'`.

**Comment by derjanb** [comment]
Indeed, using "var" also is a valid solution.

**Comment by eight04** [comment]
Browserify uses a strategy similar to:
```
require = function(){
	if (typeof require == "function") return require;
	return createRequireFunction();
}();
```
, to detect "require" in current scope.

I guess I have to make a custom build.

**Comment by tophf** [comment]
browserify and other web-related stuff doesn't account for the use case of sandboxed scripting environment running alongside the web page.

**Comment by derjanb** [comment]
I have no chance to check if it is working at the moment, but you can try to require another script first, that does nothing else than to declare a variable "require" at the current scope?

**Comment by eight04** [comment]
> require another script first, that does nothing else than to declare a variable "require" at the current scope

I can confirm that this method works. It also works if I put the new require script (the script declaring the "require" variable) AFTER linkify-plus-plus-core.

**Comment by CollinChaffin** [comment]
I was the one that reported this bug to @eight04 in his awesome linkify.  Just caught up on this thread and have to say you guys absolutely rock in how quickly you drilled down to the root cause on this one!  I was trying to debug it myself and just am not nearly the JS guru that you guys are, so thank you!
