### ISSUE TITLE
Tampermonkey prevents a specific site from loading scripts. Possibly a bug with the website.

### ISSUE THREAD

**Issue by mrhappypenguin** [Tampermonkey/tampermonkey#363]
I wrote a script to hide specific user posts on a forum. The script itself seems to work fine but if it's enabled it causes some parts of the forum to no longer function, even if there are no matching elements to hide. For example, the change theme button on the bottom left no longer functions. This is the only site I have had this happen on, but I am not sure if it is a bug with Tampermonkey, the site, or the script.

Browser: Firefox
Site: http://forums.gamersfirst.com/
Test Page: http://forums.gamersfirst.com/topic/400671-otw-update-10-11-2016/

Here's the script:

`// ==UserScript==
// @name        Block posts on G1 forums
// @namespace   blockposts
// @include     *forums.gamersfirst.com*
// @version     1
// @grant       none
// @require     https://code.jquery.com/jquery-3.1.1.js
// ==/UserScript==

$(document).ready(function() {
  $('a[href*="639937-sallybloodstorm"]').parent('span').parent('div[class="post_username"]').parent().parent().parent().hide();  
});`

**Comment by tophf** [comment]
See the documentation: with `@grant none` the userscript runs in the web page context, not in a sandbox, meaning your jquery conflicts with the site's jquery. Remove `@grant none`.

**Comment by mrhappypenguin** [comment]
Thanks. The site works normally with the script now!
