### ISSUE TITLE
Show GM_ values in script settings

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#366]
It'd be nice to view the values set by GM_setValue on the script settings page. Could be a table with three columns: name, type, value. What do you think?

**Comment by Mattwmaster58** [comment]
I second this. It would be very useful in developing scripts. In the mean time you could try something like [this](http://stackoverflow.com/questions/42775277/access-gm-getvalue-outside-of-script) for access to the values

**Comment by derjanb** [comment]
[Fixed at the latest beta](http://tampermonkey.net/changelog.php?version=4.3.5430&ext=gcal)
