### ISSUE TITLE
[Firefox] Tampermonkey fails to load on Developer version (Firefox 54)

### ISSUE THREAD

**Issue by jaromanda** [Tampermonkey/tampermonkey#368]
Clicking on Tampermonkey icon produces a blank "popup"

Console error:

`b is undefined` ...  on line `action.js:15`

**Comment by derjanb** [comment]
Please use the unofficial, but fixed version from here: https://tampermonkey.net/xpi/46544b6d654f61/firefox-5410beta.xpi

The extension update review now already takes [almost 2 month](https://github.com/Tampermonkey/tampermonkey/issues/352#issuecomment-285466789). :pensive:

**Comment by jaromanda** [comment]
Thanks, can confirm it works in Firefox 54 at least
