### ISSUE TITLE
Alt-Left/Right should not change tab on Mac OS X

### ISSUE THREAD

**Issue by joeytwiddle** [Tampermonkey/tampermonkey#369]
On Macs, the keystrokes Alt-Left and Alt-Right are used in editors to move the cursor whole words, much like Ctrl does on Linux and Windows.

However when we are in TamperMonkey, those keystrokes move us between TamperMonkey's tabs.

No doubt that is a useful feature by itself, but when editing a script in TamperMonkey, trying to move or select a whole word does something completely different from what was expected!

Expected: In all editors on Mac, Alt-Left will move a whole word. What happens: In TamperMonkey's editor, Alt-Left changes to a different tab!

My suggestion is to **disable** the tab-switching keystrokes when we are in the script **editor** (or indeed in any input or textarea) on Mac OS X. Alternatively disable those strokes **entirely** on Mac OS X.

If you want to provide alternative keystrokes for switching tabs on Mac, I can suggest Alt-Up/Down. These are used in Skype, Slack and messenger.com to switch between conversations. Conversations/channels are effectively the app's tabs, on a layer below the browser's tabs. (Although conversations are usually stacked vertically, I don't think it matters conceptually.)

**Comment by derjanb** [comment]
Fixed at TM BETA http://tampermonkey.net/changelog.php?version=4.3.5421&ext=gcal

**Comment by joeytwiddle** [comment]
Great thanks!
