### ISSUE TITLE
Like, Hope, but too complicated

### ISSUE THREAD

**Issue by evinierato** [Tampermonkey/tampermonkey#370]
Why can't I just click on an issue ( e.g. overlay or video sounding but no visual ) and then Tampermonkey.
A simplistic version that's idiot proof.

**Comment by derjanb** [comment]
Please explain the issue a little bit more in detail. Thanks.

**Comment by evinierato** [comment]
TM is installed but I don't know how to use it. My FF has many adblocker extensions; yet, ads continue to display. This is when I click on TM and hope the issue disappears. Sometimes it works and sometimes not.

**Comment by derjanb** [comment]
Tampermonkey itself doesn't block or hide ads, but there are scripts which are doing this. Please search for such a script and/or contact the script author regarding problems.
