### ISSUE TITLE
Refocus the originally active tab after closing dashboard

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#374]
By providing `openerTabId` in [chrome.tabs.create](https://developer.chrome.com/extensions/tabs#method-create) it's possible to make the browser automatically refocus the originally active tab, where the user invoked Tampermonkey dashboard, after the dashboard was closed. This would be very helpful in case there are many tabs open and the active tab is not the last one in the tab strip.

**Comment by tophf** [comment]
BTW Firefox doesn't accept this parameter at all (these small discrepancies are really irritating!) so one has to special-case it.

**Comment by derjanb** [comment]
This should work at the [latest beta](http://tampermonkey.net/changelog.php?version=4.4.5484&ext=gcal)
