### ISSUE TITLE
[Request] Consider having a development channel of the add-on on AMO

### ISSUE THREAD

**Issue by FatOrangutan** [Tampermonkey/tampermonkey#377]
AMO review queues seem to be progressing pretty slowly at the moment. It has been nearly two months since an update to the add-on has been stuck there.

So maybe consider having a development channel of the add-on, like uBlock Origin [does](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?src=ss#beta-channel) (and also [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/?src=ss#beta-channel)). This should allow Firefox users to opt for the dev channel to get your updates instantly, bypassing the review queue. You can also suggest people to consider switching to it in the add-on description.

**Comment by derjanb** [comment]
Thanks for the suggestion. It looked like dev versions also need a review. Therefore I thought it would also be slow, but the versions are published immediately.
