### ISSUE TITLE
[Firefox] won't run correctly on ESR edition (firefox 45.x)

### ISSUE THREAD

**Issue by DhannyNara** [Tampermonkey/tampermonkey#378]
please add support for ESR edition too please. 
it won't run correctly

update: when i update to 52.0 its still buggy

**Comment by derjanb** [comment]
@DhannyNara Have you tried the development channel? 

![image](https://cloud.githubusercontent.com/assets/767504/24839290/dec47d7c-1d57-11e7-9cf4-aca59604b911.png)

**Comment by DhannyNara** [comment]
> Have you tried the development channel? What exactly is buggy?
this:
![doesnt appear](https://cloud.githubusercontent.com/assets/5054847/24840179/e36e5c10-1d9a-11e7-8c6a-dab0979ee5fc.JPG)

**Comment by derjanb** [comment]
I meant Tampermonkey's development channel. :) 

> do you know this

Yes, and it's fixed at TM 4.3.5430beta
