### ISSUE TITLE
[Firefox] Toolbar icon is sometimes blurry

### ISSUE THREAD

**Issue by Keith94** [Tampermonkey/tampermonkey#382]
If you open a new tab or navigate to an internal page (for example `about:addons`) the tampermonkey toolbar icon is replaced with a very blurry version. It does not happen on normal website pages.

Blurry:
![image](https://cloud.githubusercontent.com/assets/5490615/24907586/a97575fc-1e71-11e7-89df-641cdf58727a.png)

Normal:
![image](https://cloud.githubusercontent.com/assets/5490615/24907590/ad824332-1e71-11e7-9078-22028e43206b.png)

**Comment by derjanb** [comment]
Interesting... https://github.com/Tampermonkey/tampermonkey/issues/364

Thanks for the bug report.

**Comment by Keith94** [comment]
Fixed.
