### ISSUE TITLE
[Firefox] Google reverse image search pages sometimes hang up the browser

### ISSUE THREAD

**Issue by FatOrangutan** [Tampermonkey/tampermonkey#383]
Windows 10, Firefox 55.0a1 (2017-04-12), e10s enabled, Tampermonkey 4.3.5430beta, [Tampermonkey settings](http://i.imgur.com/B0nlMPD.png).

STR: Not 100% reproducible, but I get this often enough.

1) Go to https://images.google.com.
2) Click 'Search by image' camera icon -> Paste Image URL -> paste `https://i.imgur.com/9QwIDV7.png`.
3) Click Search by image.

AR:

1) Throbber in the tab bar spins a lot, until eventually the entire browser hangs up, with the titlebar saying 'Not responding.'
2) I get the following error in the Browser Console:
![capture](https://cloud.githubusercontent.com/assets/8336638/24989045/574aa9b6-2027-11e7-8aa6-6511eeff5643.PNG)

I am running the [same scripts (I can provide more details / links)](https://i.imgur.com/GUuj3G6.png) in Tampermonkey that I was in Greasemonkey, but GM would never hang up the browser on Google. Note that I once managed to get this hang even though I had disabled every single userscript from the dashboard. (I only ever have one of TM or GM enabled.)

Is TM causing the hang or a particular script? If it is the latter, how can I find out which one it is?

Thanks.

**Comment by derjanb** [comment]
@FatOrangutan Have you found the root cause?

**Comment by FatOrangutan** [comment]
I can reproduce the hang with the following:

0) Be on a fresh profile of Firefox Nightly 55.0a1, no add-ons installed and no settings changed. Install Tampermonkey 4.3.5430beta with default settings. Add this minimal userscript:

`// ==UserScript==
// @name Redirector
// @namespace test@home.com
// @description Redirect from one thing to another
// @include /.*://.*\.media\.tumblr\.com\/.*(jpg|jpeg|png|bmp|webp)/
// ==/UserScript==

var oldUrl = window.location.href;
var newUrl = oldUrl;
if ( newUrl != oldUrl )
	location.replace(newUrl);`

1) Go to https://images.google.com.
2) You now need an image that is a few hundred KB's in size. Sample image -> http://i.cubeupload.com/98zcBO.jpg.
3) You can either use the 'Paste image URL' method, or download the above image and use the 'Upload an image' method.

AR: tab throbber stops spinning, eventually leading to a browser hang.

Note that once you install the above script, even if you go ahead and disable it from the dashboard, and follow the above STR's again, the tab will still hang. This is why I was able to reproduce a hang even with all scripts disabled in my original report.

The only way to stop getting hangs is to either remove the above script, or change the `include` URL to `/(http|https)://.*\.media\.tumblr\.com\/.*(jpg|jpeg|png|bmp|webp)/`.

Both those `include` URLs work in Greasemonkey just fine though.

**Comment by FatOrangutan** [comment]
Gentle poke @derjanb : were you able to reproduce this?
