### ISSUE TITLE
Cannot download mp4 file with GM_download

### ISSUE THREAD

**Issue by korridor** [Tampermonkey/tampermonkey#386]
I would like to download a mp4 file with GM_download, but it only downloads a 14KByte big file.
If I go to the download URL and save the site with cmd + s it downloads the mp4 file.
The download site has the following MIME type: video/mp4
I tried the same thing in Chrome and GM_download didn't work at all there.
The file extension ".mp4" is whitelisted in the tampermonkey settings of Firefox and Chrome.
The only problem I can image is that the URL has the following format:
https://website.com/something/number?something=something.mp4

**Comment by derjanb** [comment]
@korridor I can not reproduce this issue. Please add more details or attach a sample script. Thanks.
