### ISSUE TITLE
[Firefox] Google Maps Lite Mode fails to load with Tampermonkey and Waterfox.

### ISSUE THREAD

**Issue by mrhappypenguin** [Tampermonkey/tampermonkey#388]
If I try viewing Google maps in lite mode, I get a blank page when Tampermonkey is enabled. I do not have any scripts currently running.

Tampermonkey v4.3.5393
Waterfox 52.0.1

EDIT: This appears to have been fixed in v4.3.5421 beta. Took a while to find a link.

**Comment by derjanb** [comment]
Is it working with the development channel? https://github.com/Tampermonkey/tampermonkey/issues/372
