### ISSUE TITLE
Bitbucket userscripts

### ISSUE THREAD

**Issue by Mottie** [Tampermonkey/tampermonkey#392]
While attempting to look at a userscript source file on Bitbucket, the URL appears to be a valid link directly to a script, but the request serves HTML. I end up seeing two tabs showing that I attempted to load an invalid userscript. 

This happens in Chrome, not Firefox. I didn't test other browsers.

![](https://cloud.githubusercontent.com/assets/136959/25550595/f703f4f2-2c3f-11e7-844a-648ced682a90.gif)

Here is a link to the screenshot page: https://bitbucket.org/mottie/bitbucket-userscripts/src/

**Comment by derjanb** [comment]
Should be fixed at the beta version.
