### ISSUE TITLE
IPFS redirect userscript: Tampermonkey seems to redirect http to https for localhost:8080

### ISSUE THREAD

**Issue by JayBrown** [Tampermonkey/tampermonkey#393]
I'm currently getting into the [IPFS](https://ipfs.io), and for Safari (10.1, 10.11.6) I'm using [this redirect userscript](https://github.com/loadletter/ipfs-redirect-userscript) for Tampermonkey (latest stable release).

Now whenever I go to a relevant website, e.g. one of the [subpages linked here](https://ipfs.io/docs/examples/), I get redirected to `https://localhost:8080` instead of `http://localhost:8080`, and Safari then tells me that "it can't open the page, because it can't establish a secure connection to the server localhost". The problem doesn't seem to originate from Safari, because when instead I use the (unfinished and apparently abandoned) Safari extension [IPFS Catcher](https://github.com/NeoTeo/ipfs-catcher), the redirect correctly goes to `http://localhost:8080`.

So it might be a problem with Tampermonkey. Anyone with IPFS can confirm? Or anyone know if there's a way to tweak these kind of things (redirects etc.) in Tampermonkey settings? (Couldn't find anything.)

See also the corresponding issue here: https://github.com/loadletter/ipfs-redirect-userscript/issues/1

**Comment by JayBrown** [comment]
When looking at the scripts, the Safari extension is actually [setting a new URL](https://github.com/NeoTeo/ipfs-catcher/blob/master/ipfs-catcher.safariextension/startscript.js#L25) with `var newUrl = "http://localhost:8080"+defaultProto`, which Safari seems to accept, when coming from an extension, while the userscript [only has `localhost`](https://github.com/loadletter/ipfs-redirect-userscript/blob/master/ipfs-gateway-redirect.user.js#L14) with `var local_gw = "localhost:8080";` to replace e.g. `*://ipfs.io/ipfs/*`. (Don't know *for sure*, if that's the reason.)

**Comment by derjanb** [comment]
Closing because it's related to Safari < 13.
