### ISSUE TITLE
Error: console.time is not a function

### ISSUE THREAD

**Issue by Ack0** [Tampermonkey/tampermonkey#395]
Hi, 

Today I updated Chrome to version 60.0.3080.5 + Tampermonkey Beta 4.3.5445 and some scripts are not loading. This error shows up in the console:

```
ERROR: Execution of script 'Steam Store - Game Owned Checker' failed! console.time is not a function
ERROR: Execution of script 'YouTube Link Title' failed! console.time is not a function
ERROR: Execution of script 'ESGST' failed! console.time is not a function
```

That is a Tampermonkey's bug or should I contact the userscript's developer?

Thanks in advance.

**Comment by derjanb** [comment]
Should be fixed at the latest beta version (4.3.5447).
