### ISSUE TITLE
Including unsafe sites causes Tampermonkey dashboard to also show the unsafe warning

### ISSUE THREAD

**Issue by DakuTree** [Tampermonkey/tampermonkey#396]
Viewing the dashboard when one of the userscripts you have has an `@include` site with an [unsafe site warning](https://support.google.com/chrome/answer/99020) causes it to also throw the same chrome warning.  
This seems to be caused by the auto-loading favicons which can't be disabled as far as I can tell.

Example `@include` where this occurs:
```// @include      /^http:\/\/(?:www\.)?mangahere\.co\/manga\/.+\/.*\/?.*\/.*$/```

![](http://i.imgur.com/Eq8WXEU.png)

**Comment by tophf** [comment]
In Stylus extension we're using `https://www.google.com/s2/favicons?domain=github.com`

**Comment by tophf** [comment]
See also #252
