### ISSUE TITLE
Saving userscript in edit mode triggers browser save page dialog in Vivaldi

### ISSUE THREAD

**Issue by xdpirate** [Tampermonkey/tampermonkey#398]
Just a li'l bug report:
Pressing Ctrl+S to save in the userscript editor triggers the "save page" dialog box in Vivaldi. It doesn't override the intended function though; It still saves the userscript, but also triggers the save page box.

- Windows 10 Pro x64 (also observed in Win 7 Ultimate x64)
- Vivaldi 1.9.818.49
- Newest Tampermonkey from Chrome Web Store

Thanks for an awesome extension.

**Comment by tophf** [comment]
That's the browser developers' stance on hotkeys: they intentionally don't allow js code to prevent the default behavior.

**Comment by derjanb** [comment]
I tested this again and it working fine now with Vivaldi 1.13.1008.40 (Stable channel) (64-bit). Please re-open the issue if you still see this problem.
