### ISSUE TITLE
[Firefox] Editor settings aren't being saved

### ISSUE THREAD

**Issue by XspeedPL** [Tampermonkey/tampermonkey#399]
I am trying to disable the automatic syntax checking, since it hangs the whole browser while I type the scripts in.

Yet, when I change the editor settings and press 'Save', the extension indeed reloads but my settings are not being preserved.

I use Firefox 53.0.2 x64 with Tampermonkey v4.3.5393 on Windows 10.

**Comment by derjanb** [comment]
This is fixed at the development channel. I've also uploaded a new stable version on 2017-04-11, but review takes very long these days (Queue Position: 99 of 228).

Sorry for any inconvenience.
