### ISSUE TITLE
[Chrome] Icon popup window frequently shrinks down to be unusable 

### ISSUE THREAD

**Issue by wickles** [Tampermonkey/tampermonkey#401]
Often when I click the extension icon to bring up the quick popup menu, the menu appears for a split second and then shrinks down to just show the bottom left corner, the "i" Help icon. This happens probably more than half the time I click the button, it's super annoying. 

![screen shot 2017-05-26 at 11 57 53 am](https://cloud.githubusercontent.com/assets/4229542/26507005/b63eb88a-420b-11e7-99eb-0cea99c14fb7.png)

I feel like this must have been identified before but I didn't find anything in search.

**Comment by tophf** [comment]
Sounds like a bug in Chrome, I think I saw this one on https://crbug.com

**Comment by derjanb** [comment]
@wickles I guess you're using MacOS and Tampermonkey 4.2.7?

If so, then it's a [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=428044) and [workarounded at the latest stable version](http://tampermonkey.net/changelog.php?version=4.3.6&ext=dhdg).

**Comment by wickles** [comment]
tyvm for the quick fix!
