### ISSUE TITLE
Sync by WebDav ?

### ISSUE THREAD

**Issue by ivysrono** [Tampermonkey/tampermonkey#407]
Related: #288 
Users can use WebDav on Box / jianguoyun / build by themselves

**Comment by evaryont** [comment]
I'd love for official support of WebDav or some other protocol that can be self-hosted! ([remoteStorage](https://remotestorage.io/) comes to mind as a possible simpler alternative.)

**Comment by DJaeger** [comment]
:+1:

**Comment by derjanb** [comment]
WebDAV support was added in version 4.7.5811 ([Chrome BETA](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf) and [Firefox BETA](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

I've tested this with OwnCloud and it should work with NextCloud as well. If you're using another WebDAV server and you're experiencing issues, then it would be a great if you could mail me some test credentials for debugging.
