### ISSUE TITLE
Not support //@name:*

### ISSUE THREAD

**Issue by ivysrono** [Tampermonkey/tampermonkey#408]
// @name
// @name:en
// @name:zh-CN
// @name:zh-TW 

https://greasyfork.org/zh-CN/scripts/2600

**Comment by derjanb** [comment]
// @name
    // @name:en
    // @name:zh

These ones are working fine. However there seems to be in issue with the optional optional ISO 3166 country codes.

**Comment by derjanb** [comment]
http://tampermonkey.net/changelog.php?version=4.4.5499&ext=gcal
