### ISSUE TITLE
KeepVid Download Button on YouTube went Missing

### ISSUE THREAD

**Issue by St4rDu5t** [Tampermonkey/tampermonkey#410]
It has  been there since its installation, but it disappeared yesterday.  Running Windows 10, Google Chrome Version 59.0.3071.109 (Official Build) (64-bit)

**Comment by tophf** [comment]
Uhm, do you have any proof that Tampermonkey is the reason it disappeared? Userscripts often stop working because the site changed its structure so the first thing is to report the issue to the userscript author.

**Comment by jcmmanuel** [comment]
KeepVid certainly stopped working because of the new Youtube layout - which was not yet in June (the date of this thread) but a little later.
