### ISSUE TITLE
Broken since 2017-10-07 nightly.

### ISSUE THREAD

**Issue by Betsy25** [Tampermonkey/tampermonkey#417]
Tampermonkey is no longer working since 2017-10-07 nightly.
The toolbar icon is there but just flash instead of opening upon clicking & the scripts seems to be non-working. To be specific, they don't work upon loading the page it should target, but only kick in after refreshing the page after loading.

Multiprocess  = Enabled.
dom.ipc.processCount = 2
dom.ipc.processCount.extension = 1

**Comment by tophf** [comment]
Works for me in 2017-11-07.
Breaking things is expected of Nightly.

**Comment by derjanb** [comment]
Was and is (56.0a1 (2017-07-26) (64-bit)) working here as well. Please re-open of the issue persists.
