### ISSUE TITLE
Mal execution of a simple script (doesn't happen in Greasemonkey)

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#419]
I store my sites at DigitalOcean (DO).

DO requires you to login each time a new per browser session. No matter to what page you go under digitalocean.com you will be redirected to a login form (login details though, are stored at local storage, if you allow it as I did).

I created the following code to click "login" for me, in each new session:

```
// @match        https://cloud.digitalocean.com/login*

setTimeout ( function() {
document.querySelector("input[type=submit]").click();
}, 1000);
```

This code sometimes work and sometimes don't in Tampermonkey, while it **always** works in Greasemonkey.

To reproduce, open an account in DO, store your login details in local storage and try this script.

**Comment by Royalgamer06** [comment]
try changing it to
```
window.onload = function() {
document.querySelector("input[type=submit]").click();
};```

**Comment by derjanb** [comment]
It's always difficult to make an educated guess based on script snippets. Does your script have a "@run-at" statement?
