### ISSUE TITLE
userscripts source code always resides in memory

### ISSUE THREAD

**Issue by yfdyh000** [Tampermonkey/tampermonkey#420]
I see them in `about:memory` - strings. While this is a small overhead, I want them to be serialized (parsed) to keep, or only keep meta (for panel display) for disabled scripts.

In addition, I was seeing "strings" growing over time (i.e. memory leaks) to xxx MB, and I suspect it was related to Tampermonkey, but there was no clear evidence, disable the extension no eliminate these occupations.

**Comment by derjanb** [comment]
Unfortunately this is necessary to ensure fast script execution. However, I'll check if I can reproduce the mem leak issue.

**Comment by derjanb** [comment]
Memory footprint was reduced in 4.7.5798+.
