### ISSUE TITLE
Tampermonkey BETA + script with document.addEventListener breaks site interface

### ISSUE THREAD

**Issue by lainverse** [Tampermonkey/tampermonkey#422]
Tampermonkey BETA 4.4.5514 (issue doesn't reproduce with Tampermonkey 4.3.6)
Google Chrome 59.0.3071.115 (Official Build) (64-bit)
Also tested with Vivaldi 1.10.867.48 (Stable channel) (32-bit)

Script:
```
// ==UserScript==
// @name         Test
// @namespace    lainverse_test
// @version      1
// @description  try to take over the world!
// @author       lainverse
// @match        *://*/*
// @run-at       document-start
// ==/UserScript==

document.addEventListener('DOMContentLoaded',()=>null,false);
```
Site:
https://mail.ex.ua/

Issue:
When you open site in a new tab interface doesn't appear.
This issue is unstable and may not occur from the first try. However, in my tests it happen almost always.

Expected behaviour:
Site interface doesn't break.

BTW, I spent ~20 minutes on http://tampermonkey.net/ trying to find anything that mentions a bugtracker. Was it intentional or am I just blind?

**Comment by lainverse** [comment]
Oh, right, wrong place. Reported here:
https://forum.tampermonkey.net/viewtopic.php?f=17&t=2223

**Comment by derjanb** [comment]
Fixed at the latest [beta](http://tampermonkey.net/changelog.php?version=4.4.5520&ext=gcal).
