### ISSUE TITLE
[Firefox] Use local icons (at about:addons)

### ISSUE THREAD

**Issue by luxoflux** [Tampermonkey/tampermonkey#423]
FF 54 | TM 4.3.5447

Tampermonkey currently makes 3rd-party requests to
`https://addons.cdn.mozilla.net/user-media/addon_icons/683/683490-64.png`
and `https://addons.cdn.mozilla.net/user-media/previews/thumbs/170/170870.png` 
to retrieve icons. This creates a problem if one were to block those types of requests.

Please use local icons for the browser Add-on page(s). A very minor enhancement issue.

Thanks.

**Comment by derjanb** [comment]
Local icons? One needs to upload an extension icon and a screenshot to the Mozilla Add-On page for every published extension. This is nothing I can change. The images then are used here: [https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) This again is something I can not change.
And in case you're talking about ```about:addons```: this is how the addons page works. Some of the content is loaded from remote. I don't know a way to change this. 
Sorry. 😳

**Comment by luxoflux** [comment]
Hmm. None of my other addons make 3rd-party request for the `about:addons` icons.

Example (I block 3rd-party):

![example](https://user-images.githubusercontent.com/9421932/28634550-65ac9f16-71ec-11e7-926a-1be5d8b0030a.png)

In the TM package I see all icons are included, why are those not used?

**Comment by derjanb** [comment]
Interesting. OK, I'll double check that.
![screenshot from 2017-07-26 19-40-45](https://user-images.githubusercontent.com/767504/28635331-7f9bc994-723a-11e7-8363-d968f4c5fb23.png)

**Comment by luxoflux** [comment]
Yes, the screenshot/preview image is the exception. And yes, Greasemonkey and some others have the same "issue". But most addons use local resources from what I see.

**Comment by derjanb** [comment]
Fixed at the development channel.
