### ISSUE TITLE
Specify GPLv3

### ISSUE THREAD

**Issue by davidhedlund** [Tampermonkey/tampermonkey#424]
Please replace "Released under Custom License" with "GPLv3" and add a copy of the license on https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/

**Comment by derjanb** [comment]
Tampermonkey **is** released under a proprietary license, therefore there is no need to change it at AMO. See [README](https://github.com/Tampermonkey/tampermonkey/blob/master/README.md).

**Comment by davidhedlund** [comment]
@derjanb 

> This repository contains the source of the Tampermonkey extension up to version 2.9. All newer versions are distributed under a proprietary license.

Sorry.

Do you know if there's any forks on version 2.9?

**Comment by davidhedlund** [comment]
https://tampermonkey.net/ says
> Tampermonkey is a free browser extension

Can you please change that? Perhaps by replacing free with gratis?
