### ISSUE TITLE
Replace "free" with "gratis" on tampermonkey.net

### ISSUE THREAD

**Issue by davidhedlund** [Tampermonkey/tampermonkey#425]
https://github.com/Tampermonkey/tampermonkey says
> This repository contains the source of the Tampermonkey extension up to version 2.9. All newer versions are distributed under a proprietary license.

While https://tampermonkey.net/ says
> Tampermonkey is a free browser extension

"Free" is used to describe free software that Tampermonkey used to be. Now its just gratis.

**Comment by eight04** [comment]
As a non-native English speaker, may I ask what is the difference between "free" and "gratis"?

**Comment by yfdyh000** [comment]
@eight04 Free like https://en.wikipedia.org/wiki/Free_software

**Comment by davidhedlund** [comment]
@yfdyh000 Hi =)

**Comment by derjanb** [comment]
Corrected.

**Comment by davidhedlund** [comment]
Can you please change the [project page](https://github.com/Tampermonkey/tampermonkey) here on GitHub too. Its also using ther term "free":
> Tampermonkey is a free browser extension...

**Comment by davidhedlund** [comment]
@derjanb And finally on [AMO](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/):
> Tampermonkey is a free browser extension and the most popular userscript manager.

**Comment by derjanb** [comment]
I'll update AMO when the currently queued release is published. It's waiting since 2017-06-10 for a review and I'm not gonna risk to be moved to the beginning of the queue. 😉

**Comment by davidhedlund** [comment]
@derjanb I understand.

What about https://github.com/Tampermonkey/tampermonkey/issues/425#issuecomment-319458925?

**Comment by davidhedlund** [comment]
And then, please re-open this issue and change the title to
>  Replace "free" with "gratis" on AMO

**Comment by davidhedlund** [comment]
I'm trying to make sense of this issue.

**Comment by davidhedlund** [comment]
@derjanb Thank you for fixing https://github.com/Tampermonkey/tampermonkey/issues/425#issuecomment-319458925

**Comment by davidhedlund** [comment]
Can you please re-open this issue and change the title to
>  Replace "free" with "gratis" on AMO

**Comment by davidhedlund** [comment]
Thank you for removing "free" in

> Tampermonkey is a free browser extension

from
* https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/
* https://github.com/Tampermonkey/tampermonkey
* https://tampermonkey.net/
