### ISSUE TITLE
TM (beta) lists side-loaded theme in the script manager

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#426]
I recently modified a theme and began using it as a side-loaded extension in Chromium stable Version 60.0.3112.78 (Official Build) (64-bit). Surprisingly, it shows up in the list of installed scripts in TM manager. I guess it's detecting it as a native script, and providing the option to import? I'm not that familiar with the native script feature, but this doesn't strike me as standard procedure.

Not sure what exactly occurs internally once the theme is loaded, but the theme itself has no real script to speak of, just a manifest and images. It's in a local folder which is not the same as Chromium. Listed in the TM manager, it has no id# and the name isn't clickable to open. There's an option to import, which fails if attempted (I was curious). Turning it off does turn the theme off, or more likely unloads it altogether. Turning it back on does nothing. Deleting also unloads the theme.

Not some terrible bug since it does nothing if left alone. It always appears at the top of the list, no matter which sorting option is selected, so I could even hide it with CSS if need be. I doubt many users are side-loading themes, so you may determine that accounting for this odd behavior is unnecessary, but odd behavior can potentially be an indication of more serious underlying issues, so I figured it worth mentioning.

![tm](https://user-images.githubusercontent.com/14100003/28854992-153cba4a-7708-11e7-865f-8ac8d078c9e3.png)

![tm-error](https://user-images.githubusercontent.com/14100003/28854995-1a4e36bc-7708-11e7-87d0-05c8b4836a6f.png)

**Comment by tophf** [comment]
On an unrelated note, that's a good dark UI theme. Would be nice if it's incorporated in TM as a simple toggle option...

**Comment by narcolepticinsomniac** [comment]
@tophf 

My TM style is basically a companion to my Stylus theme, so you might not be a fan of the buttons or my CodeMirror scheme (slightly different but similar). Buttons are a simple fix and all the CodeMirror CSS is grouped together and labeled, so that should be pretty simple as well.

The only other caveats IIRC, is a pseudo-element that serves as a sort of floating border under tabs in the editor, and a rather odd hack for subtle alternating `tr` backgrounds in the manager. Depending on which sorting filters/directions you select, somewhat random `tr[style="display: none;"]` elements are added/removed. I don't do a ton of alternating backgrounds. There are probably smarter, much simpler solutions, but the hack I came up with appeared to work with all filters/directions. At least it did before the bug reported here. I'd be interested in any simpler solution I missed though.

As for any other sloppily written code, that's sort of my trademark. Anyone is welcome to use however much of it they find useful.

https://pastebin.com/UWJN4ehN

**Comment by derjanb** [comment]
@narcolepticinsomniac This is a really nice dark theme. I'm better in programming than in styling. 😭

> As for any other sloppily written code, that's sort of my trademark. Anyone is welcome to use however much of it they find useful.

I would like to add it to Tampermonkey, but I'd need to make some changes (i.e. make the editor themes work again and such things). I can add a footer with a link to you or pay you a little something, whatever suits you best. But I'm also fine if you don't want me to use your theme. 😊

**Comment by narcolepticinsomniac** [comment]
Yeah, of course you can use it. I'd be happy to contribute. =)  Make whatever changes you need to. Obviously you'd need to make CodeMirror themes optional. I wasn't all that thorough with CodeMirror in TM, but if you like the general scheme, I'll go through and tweak it. That code could be added as a `codemirror\theme` file, and it could switch to it by default if the dark theme is selected (but still be optional). Otherwise, you could just scrap the CodeMirror code and use one of the built-in ones instead.

I probably didn't style the donation overlay and possibly other overlays I haven't seen. Pretty sure I got all the common ones and notifications. I tend to be heavy-handed with the `!important` declarations, because I don't like doing things twice. Checking might be a PITA, so that's up to you.

A credit in the footer would be cool, but I won't cry about it if you decide against it for whatever reason. If you do, I'd suggest:

Theme by narcolepticinsomniac from the [Stylus](https://github.com/openstyles/stylus) project.

**Comment by narcolepticinsomniac** [comment]
@derjanb 

I went through and fixed a lot of stuff in the dark theme, especially for Firefox compatibility. I also got rid of the main `color:` wildcard, so now CodeMirror is left alone (hopefully I didn't miss anything).

Scrollbars now have zoom adjustment screens, so they remain the same size 100%-150% zoom levels. This is just something I did recently in my browser scrollbar style, so I incorporated it because it's a cool detail. I have a companion XUL scrollbar style, but I doubt you can incorporate it in a WebExtension. I'll include it separately anyway.

Since FF scrollbars aren't included, I used `@supports` screens to exempt them from CodeMirror scrollbar property changes. I used a similar screen for FF specific overrides to fix buttons, selects, .etc. Browser specific classes on html would be preferable, but the screens seem to work fine for now.

I also went through and made a much more complete, companion CodeMirror theme. You could include it with the other CM themes as an option.

[TM Theme.zip](https://github.com/Tampermonkey/tampermonkey/files/1236022/TM.Theme.zip)

**Comment by derjanb** [comment]
Thanks a lot. I'll check the CodeMirror theme later. For now I've adapted your changes and created a new repo for a easier collaboration. :)

https://github.com/Tampermonkey/tampermonkey-layout

Oh, and BTW: this issue is fixed at the latest beta version (4.4.5541).
