### ISSUE TITLE
Disable update tab

### ISSUE THREAD

**Issue by kingio** [Tampermonkey/tampermonkey#427]
On every update, tampermonkey opens a tab showing the changelog.
¿Could be there an option to disable that tab opening?
I'm currently forced to use https://greasyfork.org/en/scripts/6040-disable-tampermonkey-update-tab

**Comment by yfdyh000** [comment]
Update_Notification in tampermonkey options with Config_Mode to Beginner or Advanced.

**Comment by derjanb** [comment]
@yfdyh000 Thanks.

**Comment by kingio** [comment]
¡Ty!
I will leave a screensot here for easier instruction:
![http://i.imgur.com/ya9xOSS.png](http://i.imgur.com/ya9xOSS.png)

**Comment by jbruett** [comment]
running 4.5, this still happens, even after updating the settings above.  I'm finding that the Config Mode setting is not saved through a browser restart.

**Comment by tophf** [comment]
@jbruett, sounds like you didn't click the `Save` button. Or try updating to the current 4.6. Otherwise it may be a bug in the browser - see if you can reproduce in a new user profile.

**Comment by jbruett** [comment]
I saved, but I think I needed to restart TM at the bottom a second time.  I just noticed the tab is no longer opening, after updating the settings a second time and restarting TM manually.

**Comment by x2on** [comment]
This setting doesn't help here. I setup to not show any changelog, but when i restart the browser the changelog will be opend again.
Every time i start the browser this anoying changelog tab is opend :(

**Comment by derjanb** [comment]
Most probably you profile is broken and Tampermonkey can't save any/new information. Please try with a new temporary profile.

**Comment by DenMurphy** [comment]
This issue is occuring on the latest 4.10 release. Had to manually disable in Chromium browser on Raspbian as every reboot caused the new Tab with changelog to appear. Can this be programmatically changed so manual user intervention is not required after a Tamper Monkey update on a new Device (Raspberry Pi/PC etc)?

**Comment by TRIPSLORD** [comment]
Jan, it's been 6 years and people are still complaining about tampermonkey opening an update tab. Maybe it should be changed?

**Comment by AndnixSH** [comment]
Any update?
