### ISSUE TITLE
OS X Safari: Installation

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#428]
Hello @derjanb 

I've been considering adding a page to OUJS for Safari and Tampermonkey for some time now however there seems to be some issues with getting it "out of the box".

Attached is a zip of the mp4 video of what's happening, or in this case not happening. Clearly someone has gotten it installed at some point last year from https://github.com/Tampermonkey/tampermonkey/issues/344#issuecomment-266614937 but doesn't seem to be happening for this machine which is barely used.

Current Platform: OS X 10.12.6 with all the latest updates and the remainder is the video from a download today.

Thanks for any suggestions that you might have.
OUJS Admin

[Tampermonkey installation failure with OS X Safari.zip *(543.9KiB SHA256 f2291092e32b5e75e58dbf03ee8ab6725957127cc7023209d55d136030c3c88b)*](https://github.com/Tampermonkey/tampermonkey/files/1195307/Tampermonkey.installation.failure.with.OS.X.Safari.zip)

**Comment by derjanb** [comment]
In normal the grey icon should "jump" to the "Downloads" icon at the dock. Then you have to click at the icon which looks like a Lego® brick and Safari should ask you whether you want to trust this extension.

**Comment by Martii** [comment]
> should "jump" to the "Downloads" icon at the dock. Then you have to click at the icon which looks like a Lego® brick and Safari should ask you whether you want to trust this extension.

That's the same as a right click then Open With &rarr; Safari (default) in Finder. 

Tried it anyhow from the stack and same effect as the video. Never installs. :\

**Comment by Martii** [comment]
Ahh love the Mac \*cough\* \*cough\* .... related to [this comment](https://apple.stackexchange.com/questions/214760/force-installing-untrusted-safari-extensions#answer-261116) on [https://apple.stackexchange.com/questions/214760/force-installing-untrusted-safari-extensions](https://apple.stackexchange.com/questions/214760/force-installing-untrusted-safari-extensions) e.g. have to do it direct on the machine \*eyeroll\*.

Apologies for the noise. Closing.
