### ISSUE TITLE
No support certain @-moz-document regexp()

### ISSUE THREAD

**Issue by ivysrono** [Tampermonkey/tampermonkey#432]
https://userstyles.org/styles/138388/discuz-phpwind

`@-moz-document regexp("^https?://[^\/]+/.*((thread-)|(viewthread)).*")`

No @include or @match if installed by Tampermonkey.

**Comment by derjanb** [comment]
Because there is no **@include** at the script source. [userstyles.org](userstyles.org) just needs to add 

```
// @include /^https?://[^\/]+/.*((thread-)|(viewthread)).*/
```
to the generated userscript source and everything should work fine.

**Comment by derjanb** [comment]
"Duplicate" of #467
