### ISSUE TITLE
Allow add/remove user-included domain from UI popup

### ISSUE THREAD

**Issue by yfdyh000** [Tampermonkey/tampermonkey#433]
For some generic scripts, like My Novel Reader.
Add to user included / excluded (If the script specified).

May provide a "meta" and a user-option to allow this operation for script, also set sub/main domain preference.

**Comment by tophf** [comment]
You mean in addition to the already existing UI in dashboard?

![clip358-fs8](https://user-images.githubusercontent.com/1310400/30520715-5d8d1762-9bbc-11e7-96b8-7150cf9760cd.png)

Not sure how that would work in UI popup, but it might be useful indeed.

**Comment by yfdyh000** [comment]
Yes, open the dashboard UI, find, go to and add is cumbersome and slow.
I would like to allow adding domain from UI popup for particular scripts.

**Comment by tophf** [comment]
Current workaround is to Ctrl-click or Right-click the script in the popup to open it, then switch to its Settings tab. Two clicks. And another one to add an URL. The idea you suggest would make it a bit more convenient and obvious though.

**Comment by derjanb** [comment]
Adding as user-exclude would be simple, because the script runs at that page and I can add a sub-menu entry for that. But how would "add as user-include" work? The script is not shows at the action menu and showing all (unrelated) scripts would make the popup confusing.  So by saying

> May provide a "meta" and a user-option to allow this operation for script, also set sub/main domain preference.

you suggest to introduce a new meta tag, i.e @allow-user-includes to make TM show these scripts at every page? Or would it be OK to enable this feature if the original script include list matches the page URL, but is disabled? 🤔

**Comment by yfdyh000** [comment]
>@allow-user-includes to make TM show these scripts at every page? 

Yes. Also provide an option for scripts that allow users to override this option.

This may require two or more menus, the full subdomain and the root-domain.

> Or would it be OK to enable this feature if the original script include list matches the page URL, but is disabled?

I am not sure.

**Comment by derjanb** [comment]
Please check the latest Tampermonkey Beta version 4.6.5737. 

![image](https://user-images.githubusercontent.com/767504/37542863-df9768bc-295f-11e8-89c3-ac7e6de4d84a.png)

**Comment by darkred** [comment]
@derjanb Unfortunately the 3-dots icon is not available in TM (beta 4.7.5811) for Firefox 61.0.1 x64 win 10.

Screenshot:
![2018-07-08_121247](https://user-images.githubusercontent.com/723651/42418389-4ce33012-82a8-11e8-9920-0d46b6f2f981.jpg)

**Comment by diyijing** [comment]
how to undo this operation in popup menu ?

**Comment by derjanb** [comment]
> how to undo this operation in popup menu ?

Open the Dashboard and find the script, then click at it and open the "Settings" tab. You can remove the entry from "User excludes".
