### ISSUE TITLE
Match local "chrome://" URLs

### ISSUE THREAD

**Issue by vibinr** [Tampermonkey/tampermonkey#436]
I'm trying to match a single webpage - "chrome://inspect/#devices", after having "Allow access to local file URLs" switched on, in the extensions page.

I tried with 
```
// @match        chrome://*
// @match        file:///*
```

I'm able to match file:///... URLs, but not "chrome://inspect/#devices".

**Comment by vibinr** [comment]
Found a forum thread where replies say it's not possible. :( https://forum.tampermonkey.net/viewtopic.php?t=875

**Comment by derjanb** [comment]
Yes, unfortunately that's the truth....

**Comment by vibinr** [comment]
That was fast...and disappointing. I can't even get bookmarklets to work on these chrome:// pages actually.

**Comment by tophf** [comment]
If you enable `chrome://flags/#extensions-on-chrome-urls` flag and learn to ignore the yellow warning displayed on each browser start, you can write your own extension, add `chrome://*/*` to [content scripts](https://developer.chrome.com/extensions/content_scripts) section `matches` and then use normal DOM methods. Writing an extension is easy if you start with an existing [sample](https://developer.chrome.com/extensions/samples) (use those with content.js).

**Comment by vibinr** [comment]
@tophf thank you for the pointers!
