### ISSUE TITLE
`debugger;` break debugging on pages

### ISSUE THREAD

**Issue by yfdyh000** [Tampermonkey/tampermonkey#440]
Tampermonkey 4.4.5546beta on Firefox 57.

`{if(-1!=(k=k.search(/\*\//))){h[v]=x.insert(h[v],k+2,0,"debugger;");break}}else{h[v]="debugger;"+h[v];break}`

**Comment by yfdyh000** [comment]
The "break" meaning interference debugging process, I have to click to continue every time.

**Comment by derjanb** [comment]
You mean when debugging (developer tools open) a page (where a script is running at), then the debugger stops at the mentioned line, correct?

Hmm, this is working fine here with FF nightly 57.0a1 (2017-08-29) (64-bit). What version are you using?

**Comment by yfdyh000** [comment]
Same the 57.0a1 (2017-08-29) (64-bit), with https://greasyfork.org/scripts/10433-super-preloaderplus-one

**Comment by derjanb** [comment]
Hmm, even with this is script everything is working as expected here. 🤔
Can you maybe post a screenshot or a little gif? And just to be sure: the "Debug scripts" option is disabled, right?

**Comment by yfdyh000** [comment]
Oh, I see the "Debug scripts" option is enabled by me, I don't really understand its meaning before... It should have a description.
