### ISSUE TITLE
KeepVid script not working anymore

### ISSUE THREAD

**Issue by jcmmanuel** [Tampermonkey/tampermonkey#443]
The KeepVid script for Google Chrome stopped working when YouTube launched its new layout (in August I think). I wonder why I can't find anyone complaining about it - maybe no one is using KeepVid for YouTube downloads? It's an excellent program, but it doesn't work since day 1 of the new layout - more precisely: the red download button does not appear anymore on top of YouTube videos.

**Comment by derjanb** [comment]
Hi, this is a issue of the script. Please contact the script's author for a fix. 
See also #410
