### ISSUE TITLE
Include title tag everywhere in the dashboard

### ISSUE THREAD

**Issue by Smile4ever** [Tampermonkey/tampermonkey#444]
Case 1

* Open the dashboard.
* Look at the tab title. It will be a unreadable mess. The word "Dashboard" could be shown there.

Case 2

* Open the dashboard
* Edit a user script
* Look at the tab title.  It will be a unreadable mess. Something useful could be shown there.

**Comment by Smile4ever** [comment]
Thanks for adding this to 4.5.5553. (http://tampermonkey.net/changelog.php?version=4.5.5553&ext=fire&updated=true&old=4.4.5484&intr=true)

It doesn't seem to work though. I still see the addon id in the tab title and there is no "title" tag to be found in the HTML code in rendered mode.

**Comment by tophf** [comment]
Update to 4.5.5559beta

**Comment by derjanb** [comment]
Yes, 5553 was uploaded to AMO on 2017-08-08 and does not contain the fix.

**Comment by Smile4ever** [comment]
Then why is there "Add a title to all extension tabs" in the changelog for 4.5.5553? 😆 

@tophf Thanks.
