### ISSUE TITLE
Scripts are not executed on svg image pages

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#445]
For example: https://developer.cdn.mozilla.net/static/img/web-docs-sprite.22a6a085cf14.svg
Is it possible to run scripts on these pages?

**Comment by tophf** [comment]
Currently TM only recognizes HTML and XHTML documents.
The fix is simple: page.js should create `script` element with SVG namespace e.g.:

```js
if (document.documentElement instanceof SVGSVGElement) {
  var el = document.createElementNS('http://www.w3.org/2000/svg', 'script');
}
```
