### ISSUE TITLE
Do not use red as background for the toolbar button indicator

### ISSUE THREAD

**Issue by Smile4ever** [Tampermonkey/tampermonkey#446]
Red means "warning" and "error", not info. Red asks for attention. I prefer to have a gray background for something neutral.

By "toolbar button indicator" I mean the userscript count on the toolbar button.

**Comment by derjanb** [comment]
I think "warning" is OK, since it tells you that there is a script running at this page.

If you want to change the color, you can easily do so by switching "Config mode" to "Advanced" and the altering the "Icon Badge Color" setting.
