### ISSUE TITLE
global variables, window variables malfunction when @grant GM_webRequest

### ISSUE THREAD

**Issue by jasonkhanlar** [Tampermonkey/tampermonkey#448]
Tested with both Tampermonkey v4.3.6 and Tampermonkey Beta v4.5.5553 using Chromium web browser

Code snippet:
```javascript
window.myVar = 'myValue';
```
Checking this in developer console after page loads, myVar doesn't exist when @grant line value is GM_webRquest, but works when value is none

**Comment by derjanb** [comment]
Just use `@grant unsafeWindow` and change the code to:

```javascript
unsafeWindow.myVar = 'myValue';
```

**Comment by AugustoResende** [comment]
@derjanb any news about GM_webRequest?
