### ISSUE TITLE
pop up happens every so many hours

### ISSUE THREAD

**Issue by AhSwuhPwn** [Tampermonkey/tampermonkey#449]
https://i.gyazo.com/e4582cf95a0ac5736663e0a8ce9d066a.gif
^^ this keeps poppin up and im sick of it
im watching movies play'n games or anything and all of a sudden this thing pops up like i care about it
i dont even got tampermonkey or w/e i never even heard of it 
so how do i get rid of this thing .. i cant even task manage and find the issue that allows this to pop up every few hours or so

**Comment by derjanb** [comment]
You've installed this malware: https://chrome.google.com/webstore/detail/tampermonkey-for-chrome/lbjhpacjceckhhojhidpnpoopbkoango

You can remove it by opening chrome://apps, a right-click at this app and "Uninstall".
But please also report this app to Google ("Report Abuse") first.

You can find the real Tampermonkey extension here:
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
