### ISSUE TITLE
Breaks internal Firefox pages (about:addons, about:preferences and info window)

### ISSUE THREAD

**Issue by rugk** [Tampermonkey/tampermonkey#451]
Directly after installation I got this:

![grafik](https://user-images.githubusercontent.com/11966684/30922458-81db1f8e-a3a9-11e7-9aba-1b0d7161f34c.png)
![grafik](https://user-images.githubusercontent.com/11966684/30922479-914fb13c-a3a9-11e7-9d90-0101da5a4b7e.png)

After a browser restart it worked again.
Firefox 55

**Comment by derjanb** [comment]
Do you still see this issue? I can not reproduce it. Thanks, Jan.

**Comment by rugk** [comment]
Did not try…

**Comment by derjanb** [comment]
Closed for now. Please re-open if you see the issue again.
