### ISSUE TITLE
sync script values set by GM_setValue

### ISSUE THREAD

**Issue by kkot** [Tampermonkey/tampermonkey#453]
I think it would be useful to sync values set between computers. WebExtension API support storage.sync to maybe it can be used for that.

**Comment by tophf** [comment]
storage.sync is [**severely** limited](https://developer.chrome.com/extensions/storage#property-sync) so it's not suited for anything that can grow unpredictably. Such as script data.

**Comment by derjanb** [comment]
Yes, this unfortunately can disrupt TM's use of storage.sync. 

But you(or the script author) can use [Google Drive](https://developers.google.com/drive/v3/web/quickstart/js) or something similar to sync data by your own.

**Comment by filbo** [comment]
Given your progress with TESLA and its various back-ends other than native browser sync -- is there any possibility of eventually having script storage sync?

**Comment by SukkaW** [comment]
@derjanb Sorry to bother you. But I wonder if I use Third Party Service (Google Drive, WebDav, and so on) to sync, will TamperMonkey sync those stored values?

**Comment by andrewdbond** [comment]
> ![image](https://user-images.githubusercontent.com/40715044/106448465-c4e6f900-64bd-11eb-8515-4b460f659d4e.png)

Note that the screenshot is *not* from the Sync section, but is instead from the Utilities page which seems to be about manual backups, etc.

(FYI the Violentmonkey userscript manager has an open issue for the same functionality at https://github.com/violentmonkey/violentmonkey/issues/48 but no volunteers yet to code it. 😊)
