### ISSUE TITLE
`@match` too wide

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#456]
Currently the `@match` pattern of:

`@match somesite.com/*` works with TM v4.4

Ref(s)
* https://openuserjs.org/scripts/bNj/Zone-Telechargement.ws_Direct_Link_Revealer/issues/probl%C3%A8me_avec_linstallation_du_script
* https://developer.chrome.com/extensions/match_patterns

Thanks for the look.

**Comment by derjanb** [comment]
Thanks for reporting. However, I'll leave it as it is because:

* Chrome match patterns work as expected
* it is intuitively clear that every protocol is allowed
* a change might break existing scripts
