### ISSUE TITLE
Typo in GM.xmlHttpRequest

### ISSUE THREAD

**Issue by zeus81** [Tampermonkey/tampermonkey#457]
The latest version added compatibility with greasemonkey 4.0 new api but there's a typo with xhr.
It's GM.xmlHttpRequest
not GM.xmlhttpRequest

**Comment by zeus81** [comment]
It probably first was a typo in the legacy api they decided to fix in the new one I guess.

**Comment by yfdyh000** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2559#issuecomment-332222144

**Comment by tophf** [comment]
> It probably first was a typo in the legacy api they decided to fix in the new one I guess.

Makes sense.
I remember forgetting the wrong legacy spelling a couple of times and typing GM_xml**H**ttpRequest instead.

**Comment by derjanb** [comment]
Will change it. Thanks. :)
