### ISSUE TITLE
[Firefox] Scripts disappear after update everytime

### ISSUE THREAD

**Issue by maxjame5432** [Tampermonkey/tampermonkey#458]
When I updated new version Tampermonkey on Firefox It was disappeared after reopen Firefox. But If updated and not reopen it still has the scripts. I don't know why but the problem is happening everytime when I update from first release version to the present version. 

But it strange on newest version(4.5.5570) because everytime I'm going to setting for enable Sync (after Scripts is gone) it don't have a warnning status on the top but the newest version(4.5.5570) it has a warnning on the top. It show like this " Tampermonkey detected inconsistencies that indicate that your browser wiped the extension database! " (see photo) What's happen ? I click on the status and read the solve but i don't understand it. 

Tampermonkey : 4.5.5570
Firefox Dev 57.0b8

![https://flic.kr/p/YpLqek](https://farm5.staticflickr.com/4488/37024924853_5e5bb0f4ab_z.jpg)

**Comment by derjanb** [comment]
Do you have have some special settings like

`privacy.resistFingerprinting`
`dom.storage.enabled` or
`Accept cookies from websites`

modified?

**Comment by maxjame5432** [comment]
I think it's no. because I rarely enter ```about:config``` if not necessity. (see photo)

![https://flic.kr/p/ZBukJU](https://farm5.staticflickr.com/4493/37813942676_f8593dca32_o.png)

**Comment by AmineHadef** [comment]
Same problem here.. using Firefox Quantum!

**Comment by havrancek** [comment]
same here

**Comment by derjanb** [comment]
Can you please check if this workaround is working for you as well? 
https://github.com/Tampermonkey/tampermonkey/issues/470#issuecomment-345389658

**Comment by RussiaVk** [comment]
ME TOO , AND LOST MY ALL SCRIPT ,FUCK.....
