### ISSUE TITLE
Tampermonkey on Firefox - Improvement

### ISSUE THREAD

**Issue by vrackfall** [Tampermonkey/tampermonkey#460]
I was using Greasemonkey before but I switched to Tampermonkey about a year ago because Greasemonkey wasn't working anymore. I don't know which of them is the more secure.
So, sorry if this was already asked by someone else, but those are my ideas:
- Making Tampermonkey on Firefox using an interface like the one that was used before by Greasemonkey or like in Stylish (I mean to make it's GUI into the about:addons tab).
- Making Tampermonkey more secure by analysing the scripts to install and the one that have been already installed because some users are poorly cautious and some doesn't understand english.
- Making Tampermonkey block the ability of some advertiser companies to look what you are doing on your browser trough the about: and chrome:// protocols.

**Comment by DanaMW** [comment]
You should read up on "web extensions" which is how it is going to be in firefox (already is for some of us). You will see that the new method makes some of what your asking too difficult or impossible. The about and chrome pages are off limits. Well you will see when you google web extensions. Take care.

**Comment by derjanb** [comment]
> Making Tampermonkey on Firefox using an interface like the one that was used before by Greasemonkey or like in Stylish (I mean to make it's GUI into the about:addons tab). 

Not possible (yet?). Web extensions only do have a very limited API to interact with the browser.

> Making Tampermonkey block the ability of some advertiser companies to look what you are doing on your browser trough the about: and chrome:// protocols.

Don't understand. Tampermonkey has no access to these pages.

> Making Tampermonkey more secure by analysing the scripts to install and the one that have been already installed because some users are poorly cautious and some doesn't understand english.

If you install [this script](https://github.com/ameboide/webcomic_reader/blob/master/webcomic_reader.user.js) and then [this one](https://github.com/anka-213/webcomic_reader/blob/master/webcomic_reader.user.js) a page which shows a diff between the two versions and also the complete new source code will be opened (as shown at the attached image below). So user can easily see the differences. A little bit understanding of JavaScript is needed though. But that's true for every script installation.

![image](https://user-images.githubusercontent.com/767504/32379614-47155adc-c0ae-11e7-8984-92b38dda0bd6.png)
