### ISSUE TITLE
Chrome automatically downloads userscript after about 30 sec on slow internet connection

### ISSUE THREAD

**Issue by ZiaUrR3hman** [Tampermonkey/tampermonkey#462]
I've installed the tempermonkey extension, when i open .user.js file then after about 30 sec Chrome automatically downloads userscript to local machine instead of showing me install button to install script... also i've tried to install from utilities > URL, i'm getting "Unable to parse this! :(" error...
copying userscript from file to new userscript works fine... 
please fix this issue...

![image](https://user-images.githubusercontent.com/9167406/32378386-773a6f04-c0cc-11e7-81ae-504ddd7c73c5.png)

**Comment by derjanb** [comment]
@ZiaUrR3hman can you tell me the URL of this script?

**Comment by ZiaUrR3hman** [comment]
script URL is [Here](https://www.linkedinsocialtoolkit.com/LinkedInSocialToolKit.user.js)

**Comment by derjanb** [comment]
Impressive script. Do you maintain all the selectors and inserted HTML code manually? 😲

Anyway, I'll increase the script retrieval timeout from 15 to 60 seconds.

**Comment by ZiaUrR3hman** [comment]
Thanks... yes, everything is maintain manually...
i would suggest retrieval timeout to 90 Sec... 
Send me your LinkedIn profile link i'll send you activation key, if you want to test script... :)

**Comment by derjanb** [comment]
Timeout was increased at TM beta 4.5.5590.

**Comment by ZiaUrR3hman** [comment]
I've tested on TM beta 4.5.5590 on chrome same issue...

**Comment by derjanb** [comment]
> I've tested on TM beta 4.5.5590 on chrome same issue...

Can you please [open the background page dev tools](http://tampermonkey.net/faq#Q600) and select the network tab and then try to import the script from URL. I do see a "unable to load" error message. What does the network tab show?

![image](https://user-images.githubusercontent.com/767504/32680350-83463e06-c66a-11e7-8f62-95792e6e537f.png)

**Comment by ZiaUrR3hman** [comment]
Well script is fetched immediately, when it opens prompt message to install script gives error unable to parse and then chrome asks to download or not...
[Check this URL](https://www.linkedinsocialtoolkit.com/LinkedInSocialToolKit.min.user.js) without enabling throttling...

![tmkit](https://user-images.githubusercontent.com/9167406/32682546-27e7a18a-c697-11e7-8c4f-87f8f131532f.png)

**Comment by derjanb** [comment]
> Check this URL without enabling throttling...

Well this is working fine here. 🤔 Can you please select the request and choose the response tab? Please copy the content. Is it possible to install it by pasting this at the new script tab and press save? Is the content different from what you've uploaded to the server?

**Comment by ZiaUrR3hman** [comment]
> Well this is working fine here. 🤔
Remove the old installed script and try [This URL](https://www.linkedinsocialtoolkit.com/LinkedInSocialToolKit.min.user.js)

>  Can you please select the request and choose the response tab? 
yes, content are same... and I've copied response and pasted it in new user script it is working..

**Comment by derjanb** [comment]
> Remove the old installed script and try This URL

Working fine. I'll start a Windows 10 machine. Just to be sure... 
You you please try a new [temporary Chrome profile](https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DDesktop&hl=en)? 

![image](https://user-images.githubusercontent.com/767504/32683085-e04b99da-c678-11e7-94ab-2a52e5c7ae81.png)

**Comment by ZiaUrR3hman** [comment]
Same Problem on other profile as well 
![image](https://user-images.githubusercontent.com/9167406/32683212-6e66e428-c69b-11e7-8a0a-fba8669261f7.png)

**Comment by ZiaUrR3hman** [comment]
![image](https://user-images.githubusercontent.com/9167406/32683247-bab2310c-c69b-11e7-9f39-3ee3dc411a89.png)

**Comment by derjanb** [comment]
Interesting. At least I do see an error now (timeout while connecting the page). But it's different from your issue:

![image](https://user-images.githubusercontent.com/767504/32683413-5123ed4a-c67b-11e7-9e74-5bc25b0702f3.png)

**Comment by ZiaUrR3hman** [comment]
[Watch Recording here](https://youtu.be/HukDc0ctbm0)

**Comment by derjanb** [comment]
Microsoft (owner of LinkedIn) doesn't like you domain. ;)

![image](https://user-images.githubusercontent.com/767504/32683472-b53e041e-c67b-11e7-945a-068970e54419.png)

**Comment by ZiaUrR3hman** [comment]
i'm getting same problem from [GitHub As well](https://gist.github.com/ZiaUrR3hman/1702bf3daef8134cd1ea2abdf34bc6e9/raw/cd6274fb6c134196b21ea9ca60cbf39215e77a03/linkedinSocialtoolkit.user.js)

**Comment by derjanb** [comment]
Ah OK. So this is not a network problem, but the tab is not responding for too long due to editor rendering the code.
Hmm, I need to check if I can somehow speed this up. 
A possible workaround for the moment is to not have too long lines. This is something that the CodeMirror editor doesn't really like.

**Comment by ZiaUrR3hman** [comment]
Yes, I also think so that is editor problem...

**Comment by derjanb** [comment]
A possible workaround for the moment is to not have too long lines. This is something that the CodeMirror editor doesn't really like. Is this an option? 
You can also disable the advanced editor, but this works only for you.

**Comment by ZiaUrR3hman** [comment]
how many maximum columns CodeMirror can handle?

**Comment by derjanb** [comment]
This depends on your hardware and the script itself. I think if you find a row count which makes CodeMirror render the code within 10 seconds, then everything should be fine.

**Comment by ZiaUrR3hman** [comment]
OK..
