### ISSUE TITLE
webRequest

### ISSUE THREAD

**Issue by AugustoResende** [Tampermonkey/tampermonkey#464]
How set types?

types: ["script"] or types: ["xmlhttprequest"]

`chrome.webRequest.onBeforeRequest.addListener(
  function(details) {
      return {cancel: true};
  },
  {
    urls: [
      "*://example.js"
    ],
    types: ["script"]
  },
  ["blocking"]
);`

**Comment by derjanb** [comment]
This is not possible at the moment. Please see https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-306470906 for more details.
