### ISSUE TITLE
GM_cookie - HttpOnly Cookie

### ISSUE THREAD

**Issue by augustresende** [Tampermonkey/tampermonkey#465]
Is possible add GM_cookie to remove/manipulate HttpOnly cookies?

```
chrome.webRequest.onBeforeRequest.addListener(
  function(details) {
    removeCookies('https://www.example.com');
  },
  {
    urls: [
      "*://*.example.com/*"
    ]
  }
);

**Comment by derjanb** [comment]
You can either manipulate cookies via `document.cookie` or retrieve resources via [GM_xhr and the anonymous](https://tampermonkey.net/documentation.php#GM_xmlhttpRequest) option set. Besides this it's not possible to modify cookies at the moment.

**Comment by janekptacijarabaci** [comment]
However, some inspiration is here:
https://github.com/greasemonkey/greasemonkey/issues/1802
(https://github.com/janekptacijarabaci/greasemonkey/commit/dc5487ece1391e8a0a9b195f4ea02f13ed2575cc)

e.g.:
``` javascript
var cookies = GM_cookie("list");
console.log(JSON.stringify(cookies));

GM_cookie("set", {
  "name": "cookieName",
  "value": "cookieValue",
  "path": "/path",
  "expirationDate": Date.parse("Jan 17, 2037") / 1000,
  "secure": true,
  "httpOnly": true,
  "session": false,
});

GM_cookie("delete", {
  "name": "cookieName",
});
```

**Comment by AugustoResende2** [comment]
@derjanb httponly cookies can't be set or modified using document.cookie

**Comment by maple3142** [comment]
Can I set cross domain cookie with `GM_cookie` or `GM_xmlhttpRequest`?
Because a site has domain A & domain B.
To enter domain B you have to login in domain A, but they don't has 'Allow-Control-Allow-Origin'.
So I use `GM_xmlhttpRequest` to simulate login on domain A, but cookie is not set on domain A.
Is there any work around to achieve it?

**Comment by derjanb** [comment]
I finally found some time to implement GM_cookie. :) Please let me know if you find bugs or issues.

```Javascript
// ==UserScript==
// @name        GM_cookie examples
// @namespace   test
// @version     0.1
// @include     https://example.com
// @run-at      document-end
// @grant       GM_cookie
// @grant       GM.cookie
// ==/UserScript==

// GM_cookie(method, details, cb) is implemented for compatibility reasons, but due to its asynchronous nature a callback needs to be given
// * method is one of list, set and delete
// * details might contain different method-dependent properties
//   -> details.url defaults to the current documents URL 
//      Note: Tampermonkey checks if the script has @include or @match access to that URL!

GM_cookie('list', { name: 'name' }, function(cookies, error) {
    if (!error) console.log(cookies);
});

// GM_cookie.list details supports url, domain, name and path
GM_cookie.list({ url: 'https://example.com' }, function(cookies, error) {
    if (!error) console.log(cookies);

    /* logs something like this:
    [
        {
            domain: "https://example.com"
            hostOnly: true
            httpOnly: false
            name: "name"
            path: "/"
            sameSite: "no_restriction"
            secure: false
            session: true
            value: "some_value"
        }
    ]
    */
});

GM.cookie.list({ name: 'name' }).then(function(cookies) {
    console.log(cookies);
});

// GM_cookie.set details supports all properties defined here: https://developer.chrome.com/extensions/cookies#method-set
GM.cookie.set({ name: 'name', value: 'foo', httpOnly: true }, function(error) {
    console.log(error || 'success');
});

GM.cookie.set({ name: 'name', value: 'foo', secure: true })
.then(function() {
    console.log('done');
}, function(error) {
    console.log(error);
})

// GM_cookie.delete details supports url, name
GM_cookie.delete({ name: 'name' }, function() {
    console.log(error || 'success');
})

```

**Comment by Couchy** [comment]
Does anyone have a use case that doesn't involve stealing logins? This seems like a security issue. HttpOnly cookies are usually set that way for a reason.

**Comment by derjanb** [comment]
I don't think GM_cookies ads a new level of insecurity. Scripts can only access cookies of URLs where they are allowed to run at. And since they are allowed to run there, they can steal logins and password directly while they are entered, right? GM_cookie only allows access to potential access tokens. But of course, I'm open to discussions.

@rodorgas What is your use case for accessing HttpOnly cookies?

**Comment by Pytness** [comment]
@Couchy @derjanb i have a case were the user id is in a HttpOnly cookie. I could take the uid from an anchor, but that would make me load fetch the page and search for it. Having a method to acces that cookie would save me time

**Comment by bbshih** [comment]
Is this in the beta? I'm seeing "GM_cookie" is not defined

**Comment by derjanb** [comment]
@bbshih While using this?

```JS
// @grant       GM_cookie
// @grant       GM.cookie
```

**Comment by bbshih** [comment]
It's now showing up, however I'm unable to list the entire cookie. I was doing GM.cookie.list({}).then(...) but now the promise return is giving me back a "not supported" error. Do I have to past a value in the list parameter object?

**Comment by halflife3** [comment]
@bbshih  It's because in the recent version 4.9.5914 , the GM_cookies support  is disabled.
@derjanb But why disable it? or perhaps there is a better way to get http only cookies?

**Comment by salembeats** [comment]
> Does anyone have a use case that doesn't involve stealing logins? This seems like a security issue. HttpOnly cookies are usually set that way for a reason.

I have a scraper that works best in a standard browser window rather than a headless one _(for fingerprinting reasons)_, and the site that it scrapes accumulates extra cookie-info on each request, leading to a `400 Bad Request - Request Header Or Cookie Too Large` every `X` requests.

Without `GM_cookie`, I either have to elevate to an extension, pursue other possibilities, or continue manually clearing cookies.

**Comment by saroar** [comment]
here I have an error 

```
// @grant        GM_cookie
// @grant        GM.cookie

```

https://prnt.sc/olvmg4

**Comment by NabiKAZ** [comment]
How can I use `GM_cookie`?
Is it usable in current release version?

**Comment by seiry** [comment]
is `GM_cookie` was removed in stable version? @derjanb

**Comment by vcheckzen** [comment]
> is `GM_cookie` was removed in stable version? @derjanb

stable version never supported, but beta version has been doing

**Comment by navchandar** [comment]
@derjanb when will this feature be available in the stable version?

**Comment by magicdawn** [comment]
for chrome, there is `chrome.cookies.<method>` https://developer.chrome.com/extensions/cookies

if the userscript platform does not support it,  I have to upgrade userscript to a browser extension.

**Comment by lainverse** [comment]
Two improvements:
* Make GM_cookie.delete pass cookie object which it received to delete into callback to be able to perform some other actions with it. GM.cookie.delete should return a promise and pass the same object as a result.
* Hide own TM_... cookies during a startup since apparently script at document-start with instant injection mode can occasionally see and remove them.

**Comment by qsniyg** [comment]
Sorry for bumping, but are there any updates on mainlining this?

My use case for this is to support sites like twitter which add CSRF checks through cookies to their API calls (the value of a csrf cookie needed to be present in the headers). Yes it's possible to access those cookies through `document.cookie` (they're not httponly, and can't be as their client-side code requires reading them), but only if the user is on that page (twitter.com). My script needs to perform those API calls on any page (wherever there's a link to twitter etc. that the user wants to pop up). While I'm able to support this for the extension version of my script, I'd like to be able to offer the same functionality for userscript users.

Thanks for your work on this!

**Comment by mpeters-edu** [comment]
Some problems in Firefox:
- GM.cookie.set hangs:
	- when .session is present (just try to set any cookie returned by GM.cookie.list)
	- when .sameSite is incorrect (e.g. none instead of no_restriction)
- GM.cookie.set breaks with .hostOnly flag:
	- seems ignore .hostOnly (always false) 
	- seems to add a '.' character before the domain (which causes duplicate cookie instead of modifying existing)

**Comment by Anonymous941** [comment]
> Does anyone have a use case that doesn't involve stealing logins? This seems like a security issue. HttpOnly cookies are usually set that way for a reason.

@Couchy Syncing logins between multiple computers.

**Comment by piit79** [comment]
Just to check as it's unclear to me - is the GM_cookie functionality available in beta at the moment or not? :) Thanks!

**Comment by marios88** [comment]
Currently not working (firefox + tampermonkey beta) , hope to see this in stable!

**Comment by jonnytest1** [comment]
i have a functionality that doesnt involve stealing credentials ^^ - i want to try to implement an advanced tab share that recreates the tab on another device (get all the httponly cookies and copy them into the new tab , until session expires)

**Comment by BaHeK1994** [comment]
GM_cookie.list return error "not supported" on Google Chrome. How fix it?

**Comment by JenieX** [comment]
> GM_cookie.list return error "not supported" on Google Chrome. How fix it?

Only the beta version is supported.

**Comment by JenieX** [comment]
> 

Did they just add it recently?

**Comment by derjanb** [comment]
`GM_cookie` is enabled at all but the [Chrome Webstore stable version](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo]).

**Comment by yuezk** [comment]
Hi @derjanb, when will it be available in the stable version?

**Comment by KaKi87** [comment]
> Does anyone have a use case that doesn't involve stealing logins?

I do.

I created [Dark Reader dynamic blacklist](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/README.md), a userscript that, among other things, automatically enables a website's official dark theme when not enabled by default.

Fortunately, most websites rely on [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to save that setting, but unfortunately, there are also websites that use cookies instead.

Here's how I handle that kind of website :
1. The page loads ;
2. The userscript does not see a dark theme cookie so it sets one and reloads the page ;
3. The page reloads ;
4. The userscript sees the cookie.

On websites that use cookies for multiple settings, modifying any setting from the UI rewrites all cookies, making those invisible from my userscript because of the `HttpOnly` attribute.

Here's what's happening in that situation :
1. The page loads ;
2. The userscript does not see a dark theme cookie so it sets one and reloads the page ;
3. The page reloads ;
4. The userscripts sees the cookie ;
5. The user changes any setting unrelated to the dark theme ;
6. The page reloads with all cookies rewritten with the `HttpOnly` attribute ;
7. The userscript does not see the dark theme cookie despite being there, so it tries setting it again and reloading the page, in a loop.

But with the `GM_cookie` API, the userscript would see that the cookie exists despite having the `HttpOnly` attribute and thus not get stuck.

Thanks

**Comment by tophf** [comment]
@KaKi87, document.cookie is synchronous but GM_cookie is asynchronous meaning there will be a potentially long pause before the result is returned e.g. in case the site runs a big script bundle right after your script calls the API - I've seen delays over 1 second in such cases.

**Comment by KaKi87** [comment]
There's already a delay anyway, so I'm fine with providing a best-effort thing here.

That's not our fault if modern applications continue using ancient stuff like cookies instead of localStorage.

**Comment by zxfwinder** [comment]
GM_cookie return "not supported" in the latest stable Version 4.19.0.

**Comment by derjanb** [comment]
> GM_cookie return "not supported" in the latest stable Version 4.19.0.

Please use the BETA version for now.

**Comment by KaKi87** [comment]
As a developer creating userscripts for end users, I can't ask them to install a beta.

**Comment by KaKi87** [comment]
> [We will implement it once it's out of beta in Tampermonkey and actually works.](https://github.com/violentmonkey/violentmonkey/issues/603#issuecomment-1636676682)

Violentmonkey already has features that other userscript managers don't have *(that's one of the reasons why I ask my users to use it)*, so why couldn't `GM.cookie` be one of those ?

As I previously mentioned, this feature is the **only** thing that can fix my issue : no workaround exists.

Thanks

**Comment by KaKi87** [comment]
@tophf ?

**Comment by JingMatrix** [comment]
@KaKi87 For Android browsers, I have implemented the `GM_cookie` API in [ChromeXt](https://github.com/JingMatrix/ChromeXt), see docs given in https://github.com/JingMatrix/ChromeXt/issues/115 .
Could you please try the implement or provide a UserScript with `@grant GM_cookie` to test if your previously described idea works?

**Comment by ContrapunctusII** [comment]
Why are there no plans for GM_cookie to be included in the stable release?

**Comment by KaKi87** [comment]
@tophf 

> TM enabled GM_cookie in its stable version, so I guess it means we can add it too except for HttpOnly (TM beta only).

HttpOnly is the one reason why this feature is needed (as issue title indicates), so adding the function without this support makes it virtually useless.

**Comment by Luckz** [comment]
> @tophf
> 
> > TM enabled GM_cookie in its stable version, so I guess it means we can add it too except for HttpOnly (TM beta only).
> 
> HttpOnly is the one reason why this feature is needed (as issue title indicates), so adding the function without this support makes it virtually useless.

Sure, but the potential for abuse is pretty obvious, so users have to "opt in" by installing beta TM. Makes sense, no?

**Comment by tophf** [comment]
An option in script's settings in the extension would be a more reliable signal, if abuse is a concern.

**Comment by KaKi87** [comment]
> Sure, but the potential for abuse is pretty obvious, so users have to "opt in" by installing beta TM. Makes sense, no?

There is obvious potential for abuse regarding all functions in the GM API, that's what the `@grant` metadata keyword is for.

Also, installing beta doesn't mean opting in for sensitive features, it means opting in for experimental features.

Userscript managers and even extensions in general are sensitive on their own, which is why these already require opting in.

If there was an actual need for such a separation, then there would be an "advanced edition" but still released as stable.

**Comment by r4m0n** [comment]
I haven't been able to read httpOnly cookies on Brave for about 3 months now (using the latest beta versions at the times). Is it me, Brave or the extension?

**Comment by derjanb** [comment]
@r4m0n 

A test script is doing fine here...

![image](https://github.com/user-attachments/assets/052b6e1b-5046-438a-b6ee-f5deac3a012c)

```js
// ==UserScript==
// @name         xxx
// @namespace    xxx
// @version      xxx
// @description  xxx
// @author       xxx
// @match        https://*/*
// @grant        GM.xmlHttpRequest
// @grant        GM.cookie
// @connect      httpbin.org
// ==/UserScript==


const getRandomString = () => (new Date()).getTime().toString(36) + Math.random().toString(36).slice(2);

const d = getRandomString();
await GM.xmlHttpRequest({ url: 'https://httpbin.org/response-headers?set-cookie=partitioned='+d+';path=/;expires=Wed,%2021%20Sep%202033%2015:59:37%20GMT;httponly;secure;samesite=none;partitioned' })
await GM.xmlHttpRequest({ url: 'https://httpbin.org/response-headers?set-cookie=nonpartitioned='+d+';path=/;expires=Wed,%2021%20Sep%202033%2015:59:37%20GMT;httponly;secure;samesite=none' })

console.log('expected value', d);
const cs = await GM.cookie.list({ url: 'https://httpbin.org/', partitionKey: {} });
console.log(cs);
```

**Comment by r4m0n** [comment]
> @r4m0n
> 
> A test script is doing fine here at Brave Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64-bit)...

Passing the partitionKey parameter fixed it, either the defaults changed somewhere in the middle or the cookie's. Thanks :-)

**Comment by derjanb** [comment]
> or the cookie's

Browsers started to support partitioning.

**Comment by derjanb** [comment]
Added a setting to control `HttpOnly` availibility at 5.3.6209 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by ttodua** [comment]
@derjanb can we get Cookies that have been set using `Secure` flag by website? 
![image](https://github.com/user-attachments/assets/bce3868a-77f3-42e8-9f3c-1d5f1b791f2e)
I see them in chrome inspector, but GM_cookie list does not return it.

**Comment by derjanb** [comment]
@ttodua 

Stable versions return non-`HttpOnly` cookies by default only.

Set `Config Mode` to `Advanced` and change `Security` >  `Allow scripts to access cookies` to `All` to change this.

**Comment by ttodua** [comment]
> @ttodua
> 
> Stable versions return non-`HttpOnly` cookies by default only.
> 
> Set `Config Mode` to `Advanced` and change `Security` > `Allow scripts to access cookies` to `All` to change this.

Thanks !
