### ISSUE TITLE
Regexp not working properly from userstyles.org generated userscript

### ISSUE THREAD

**Issue by RaitaroH** [Tampermonkey/tampermonkey#467]
The css code [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkMaterial.css)
```
@-moz-document regexp('https?:\/\/(?!gaming\.).*youtube\.com\/.*') {
...
}
```
The generated script [here](https://userstyles.org/styles/144962/youtube-deepdark-material)
```
// ==UserScript==
// @name          YouTube DeepDark Material
// @namespace     http://userstyles.org
// @description	  <p style="font-weight: bold;">
// @author        RaitaroH
// @homepage      https://userstyles.org/styles/144962
// @run-at        document-start
// @version       0.20171105141604
// ==/UserScript==
(function() {var css = "";
if (false || (new RegExp("^https?://(?!gaming.).*youtube.com/.*$")).test(document.location.href))
	css += [
...
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
```

I have found this issue: #432 
BUT I think it's necessary to point out that only Tampermonkey doesn't work. Greasemonkey has the exact same file (userstyles.org generates the same file regardless of what addon is used) and it still implements the theme, in Firefox<57 and Waterfox. Violentmonkey also works.

**Comment by derjanb** [comment]
Please add `// @include *` or `// @include /^https?://(?!gaming.).*youtube.com/.*$/` to the script's header. I know that this is different from other script managers, but Tampermonkey wants scripts to explicitly name the site they want to run at while others simply assume `*` if no `@include` is given. This way it's much more clear to the users at what pages a script will run.

**Comment by RaitaroH** [comment]
I cannot edit the JS code myself. I CANNOT ADD @include myself. I write the CSS code and userstyles.org generated the JS without @include. Tampermonkey is unable to understand the file even though greasemonkey and violentmonkey can. 
The problem is at your end.

**Comment by derjanb** [comment]
After installing the script the user can add a `@include` or userstyles.org can modify its userscript creation algorithm to  include `*` or even better the regex, because this avoids script injection at unrelated pages.

**Comment by derjanb** [comment]
@RaitaroH @ivysrono (#432)

The Tampermonkey [Chrome and Firefox beta versions](http://tampermonkey.net/changelog.php?version=4.5.5600&ext=gcal) should now work with userstyles using `@-moz-document regexp('...')`.

**Comment by RaitaroH** [comment]
Nice work.
