### ISSUE TITLE
[Firefox 57+] All Scripts and Settings Disappear Every Time I Quit Firefox

### ISSUE THREAD

**Issue by pootz10** [Tampermonkey/tampermonkey#470]
I import my scripts from greasemonkey to tampermonkey.
I just read this topic
https://github.com/Tampermonkey/tampermonkey/issues/458
trying to find a solution, but it didn't solve it.

Today I reset firefox to it's default settings trying to see if that would solve the problem but it didn't.
After quit Firefox, the next time I open everything is gone inside tampermonkey. Fortunately all scripts and settings can be imported very quick but this issue.

after open the firefox tampermonkey dashboard
https://i.imgur.com/WNCYGIN.png

**Comment by derjanb** [comment]
Do you have have some special settings like

`privacy.resistFingerprinting`
`dom.storage.enabled` or
`Accept cookies from websites`

modified?

**Comment by pootz10** [comment]
There were on it's default before the reset and should be now, I'm going to check it again.
I'm sorry I had to edit the topic because I hit enter by mistake and the topic was created before my full post be ready.

**Comment by derjanb** [comment]
Can you please create a new Firefox profile and check? If that's not working, then can you please check Tampermonkey's background console? https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging#Debugging_background_scripts

**Comment by pootz10** [comment]
By resetting firefox defaults it created a new profile and I don't have another. Do I still need to create another?
I'm not certain if that's the screenshot you want to see, I enabled the debug mode on about:debugging
and reopened the firefox, clicked debug button on tampermonkey and take the screenshot.
https://i.imgur.com/JiHHriy.png

I also made the import of the zip file and see the debug mode importing without error only warn about xmlhttprequest

**Comment by AmineHadef** [comment]
Same problem here :(

**Comment by derjanb** [comment]
Hmm, I don't have an idea why Firefox forgets the data of `browser.storage.local`. 😧

However, as a workaround you can switch Tampermonkey to use `localStorage` only. Please note, that this storage (even though it is an extension storage) is cleared or not available if:

* all recent browser data is cleared, 
* cookies are not remembered
* dom.storage.enabled is off
* Accept cookies from websites is off
* privacy.resistFingerprinting ios true 
🙄

In order to switch to localStorage please execute this command at the console tab of the developer tools (your screenshot):

```localStorage.setItem('#storage', 'localStorage')```

and re-start Firefox. Does this make any difference? You can remove this setting at the Storage tab > "Local Storage".

**Comment by AmineHadef** [comment]
Thanks @derjanb !
I executed that command and now the problem is fixed!

**Comment by pootz10** [comment]
I get undefined
https://i.imgur.com/1cMEJIO.png

I'm starting to think if that issue is not a firefox 57 fault, because I installed violentmonkey extension, imported the scripts and after quit and open installed scripts tab was empty there too.

**Comment by AmineHadef** [comment]
@pootz10 getting undefined is normal.. restart Firefox, your scripts will be gone, but import them again and restart Firefox you will see that they will be saved :)

**Comment by pootz10** [comment]
You're right AmineHadef that solved the problem, thank you. Thank you derjanb.

**Comment by SteegHobland** [comment]
I don't really get what you're doing to fix the problem, and I have the problem, too. Could someone please put instructions for fixing this issue into a tidy, easy to follow, series of steps?

**Comment by AmineHadef** [comment]
Hi, here is how:
* Go to **about:debugging#addons** 
* **Enable add-on debugging**
* Scroll down to **Tampermonkey** and click **debug** and confirm the message with **Ok**
* Type this: **localStorage.setItem('#storage', 'localStorage')**
in the console and press **Enter** 

That's it, restart Firefox and import your scripts again.. they will not disappear after.

**Comment by derjanb** [comment]
Most probably fixed at Firefox some time ago...
