### ISSUE TITLE
CSP detection using old X- version of the header which is no longer used

### ISSUE THREAD

**Issue by rslifka** [Tampermonkey/tampermonkey#472]
Having trouble adding scripts in Chrome and getting CSP rejections.

```
Refused to load the script 'https://openuserjs.org/src/libs/sizzle/GM_config.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://apis.google.com https://www.google-analytics.com https://widget.battleforthenet.com ...
```

I noticed the following:

https://github.com/Tampermonkey/tampermonkey/blob/ea33f0a0065185ef3e2b839a02ef4fc81cda2fe5/src/background.js#L5905

...and am wondering if we need to include `content-security-policy` since that's that the contemporary version of the header? Via [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP):

> To enable CSP, you need to configure your web server to return the Content-Security-Policy HTTP header (sometimes you will see mentions of the X-Content-Security-Policy header, but that's an older version and you don't need to specify it anymore).

Something like a .toLowerCase() too, just to remove that as a source of potential discrepancy :)

Thanks so much! TM is awesome!

**Comment by derjanb** [comment]
Tampermonkey only adds an exception for itself to work. It looks like GM_config.js is being added via a script tag to the page? Have you tried to just `@require` GM_config.js?

**Comment by rslifka** [comment]
Thanks for the prompt reply @derjanb!

I'm working on breaking up my script so I can test it but by doing that (and using @require to include the component parts) it so aggressively caches them I can't change them and reload. If there's a way to flush the TM cache or something, that would be terrific.

**Comment by derjanb** [comment]
> it so aggressively caches them I can't change them and reload

Just go to Tampermonkey's dashboard, open your script, select the "Externals" tab and delete the cached `@require` data.

**Comment by rslifka** [comment]
Awesome, thanks!
