### ISSUE TITLE
[Firefox] Scripts do not run when the "responsive design mode" from the devtools is open.

### ISSUE THREAD

**Issue by Ramblurr** [Tampermonkey/tampermonkey#473]
This is on Firefox 57 (not sure if it applies to older versions).

When you run the responsive design mode (ctrl+shift+m, or from the phone icon in the devtools), user scripts no longer run. 

I'm trying to develop a user script for mobile, so using the responsive design mode is required.

**Comment by derjanb** [comment]
I can reproduce this at FF 57.0.1. This is because Tampermonkey is not injected by Firefox.
However, FF 58.0b9 is working fine, so I guess this is fixed, but not back-ported to FF 57.
