### ISSUE TITLE
Tesla sync is not enabled by default

### ISSUE THREAD

**Issue by adrianofoschi** [Tampermonkey/tampermonkey#478]
I am logged in with google account in two chrome istances.

On the first instance:

- I installed tampermonkey
- Enabled TESLA with "browser sync" option
- Imported a user script via remote URL

Then I opened the second chrome instance.
It synced extension but not synced the user-script. In the advanced settings TESLA is disabled.

**Comment by derjanb** [comment]
You have to enable script synchronization at both instances. This option only synchronizes the scripts, but not the Tampermonkey options.

**Comment by adrianofoschi** [comment]
Is there no way to sync setting
