### ISSUE TITLE
Tampermonkey 4.5.5648 breaks compatibility with "RSS+Atom Feed Subscribe Button Generator" userscript

### ISSUE THREAD

**Issue by dartraiden** [Tampermonkey/tampermonkey#479]
Userscript:
https://greasyfork.org/ru/scripts/6261-rss-atom-feed-subscribe-button-generator

Example:
https://github.com/Tampermonkey/tampermonkey/commits/master.atom

Tampermonkey 4.5.5633: feed display correctly
Tampermonkey 4.5.5648: feed display is broken (almost empty)

**Comment by derjanb** [comment]
Should be fixed at the latest beta version. Can you please confirm? Thanks

https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/beta

**Comment by dartraiden** [comment]
Yes, fixed. Thanks!
