### ISSUE TITLE
Tampermonkey 更新到4.5.5648版后回复帖子提示“内部数据错误”

### ISSUE THREAD

**Issue by nonono33333** [Tampermonkey/tampermonkey#482]
Tampermonkey的插入CSP选项关掉后就正常了，所以是5648中“Some CSP related fixes”的影响。

**Comment by derjanb** [comment]
Can you please try the latest beta version? Thanks.

你可以请尝试最新的测试版本？ 谢谢。

https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/beta
