### ISSUE TITLE
Stop opening a new tab/window automatically, to show software update

### ISSUE THREAD

**Issue by ozmium** [Tampermonkey/tampermonkey#483]
Every few days, the Tampermonkey extension will automatically open a popup web page to alert the user about a software update. It's like a spam popup advert, and there is no way to turn it off.

It's really annoying, because it happens randomly when doing work and disrupts the user a lot, especially when typing text or interacting with a web page. It's even worse when it keeps happening every few days.

Please turn this off as soon as possible.

**Comment by bkidwell** [comment]
I agree this is completely inappropriate. A whole window is not the way to announce a new changelog for the user to read. Stop doing this immediately.

**Comment by tophf** [comment]
>Stop doing this immediately.

Or else!
:grin:

**Comment by tophf** [comment]
@derjanb, I like the changelog tab and it never irritated me, but generally a better UX might be to use chrome.notifications API or change the toolbar icon on updates like Chrome does - it puts a different icon in its three-dot-menu-icon.

**Comment by derjanb** [comment]
@bkidwell @tophf @ozmium Please see #427

**Comment by Petschko** [comment]
Hey there~

Sad there is no option to disable this, sometimes it's quite annoying, when you work/write on somthing and then a new Tab opens. It would be super awesome if there is an option to disable the "Update Notifications-Tab".

I would love a "Silent update" option or a different time when it happens... I'm personally interested in update notifications, but may it would be better if it updates (and open the tab) when you open the Browser (on startup), instead randomly. (On startup is no interuption to the workflow)

Thanks so far for this great extension!^-^

**Comment by tophf** [comment]
@Petschko, see #427, it's linked in the message above yours.

**Comment by Petschko** [comment]
@tophf Ahh sorry, I missed that >.< Thanks for responding anyway

**Comment by ozmium** [comment]
I think this should be disabled by default. It's a big usability problem.

And it's difficult to find the setting to switch it off in #427, so I recommend the following:

Rename it to something like:
* **"Automatically open a new tab to show Tampermonkey software update details [Disabled]"**
* Move this option to the top, in it's own section, not within the "Appearance" section.

Hopefully this would prevent more people raising bugs about it, when they can't find how to turn it off.
