### ISSUE TITLE
[Firefox] Sometimes document-end script is executed before document loaded

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#485]
Try to install this script:
```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include *
// @grant        none
// @run-at document-end
// ==/UserScript==

(function() {
    'use strict';
    console.log(location.href, document.readyState, document.body != null);
})();
```
Then go to https://jsbin.com/wokulacatu/edit?js,console . You might need to refresh the page multiple times. Here is what I got:
![image](https://user-images.githubusercontent.com/1324510/34437603-bed9b25e-ecda-11e7-9fda-202e413a25db.png)

Tampermonkey v4.5.5660
Firefox Developer Edition 58.0b13

**Comment by tophf** [comment]
I remember observing a similar/same quirk: FF initializes the tab with a dummy empty document which is completely loaded, thus fools the extensions into happily running, then starts to load the actual page. Fun.
