### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by boxsnake** [Tampermonkey/tampermonkey#487]
Here are some suggestions:

1. Add timeout argument for `GM_notification`, ie `GM_notification(title, content, image, timeout = 0)`
2. Add functionality of exporting an archieve file for selected scripts rather than all (for benefiting distribution). Something like
- Selected Script
√ Script1
× Script2
- Options
√ Include config
√ Include storage
[ Export ]

**Comment by derjanb** [comment]
> Add functionality of exporting an archieve file for selected scripts rather than all (for benefiting distribution)

Simply select (the checkbox at the first column - you can also select via Shift+Up/Down) one or more scripts at the dashboard, select "Export" at the "Apply this to all selected scripts" drop-down and press "Start"
 
> Add timeout argument for GM_notification

The fourth parameter is used as onclick callback, but you can pass a timeout argument by providing a details hash: http://tampermonkey.net/documentation.php#GM_notification
