### ISSUE TITLE
Update local script

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Tampermonkey/tampermonkey#49]
```
Hi,
I've put into TM an local script, named .tamper.js
All is good...
But when I update the local file, the script doesn't want to upgrade into TM 
(even with the update check).
In TM in the update URL field I have :file:///C:/my_script.tamper.js
```

Original issue reported on code.google.com by `ozzi...@gmail.com` on 6 Jul 2011 at 9:11

**Comment by CoeJoder** [comment]
But isn't that what "Allow Access to File URLs" is for?  Last year, Chrome fixed a bug regarding this feature too.  Maybe tampermonkey can finally implement local file updates.

**Comment by derjanb** [comment]
This issue is from 2011. In the meanwhile there was a lot of improvement and it's now possible to access local files. This FAQ entry shows how to run and edit scripts from local disk: http://tampermonkey.net/faq.php#Q402
