### ISSUE TITLE
VIDEO TITLE DOESNT SHOW

### ISSUE THREAD

**Issue by SHAKA12** [Tampermonkey/tampermonkey#491]
Whenever i click the green download button on YouTube, instead of showing the name of the video it shows 'videoplayback' for all the videos, problem just started a few days ago after i been using this for years. This sucks cos now i have to open each video i DL so i can rename it... Can anyone please help me solve this problem?

**Comment by Skeave** [comment]
VIDEO TITLE DOESNT SHOW. Whenever i click the green download button on YouTube, instead of showing the name of the video it shows 'videoplayback' for all the videos, problem just started a few days ago after i been using this for years. This sucks cos now i have to open each video i DL so i can rename it... Can anyone please help me solve this problem?

**Comment by Skeave** [comment]
Solution: Здравствуйте, скорее всего вы пользуетесь браузером Google Chrome.
Зайдите в настройки Tampermonkey, включите режим настройки «продвинутый»,
пункт Downloads BETA, дальше Download Mode: browser api
Перезагрузить ТМ, должно работать.

**Comment by SHAKA12** [comment]
Hello Russian friend, i did exactly what you instructed and it made the problem worse because  it didnt want to DL completely when i clicked the DL button. So i reset tampermonkey and reinstalled Save from Net but the problem STILL persists. I tried using YouTube down-loader as an alternative and even that doesn't want to show the title of the videos I downloaded, it keeps showing 'videoplayback' instead of the video title...Can you offer another solution?

**Comment by derjanb** [comment]
Hi, unfortunately this is a little bit incomplete issue report, but from what I've read here is that you're trying to download a file (with the correct name) by using SaveFrom.net helper, right?

I've tested this and it is working fine here with SaveFrom.net helper 7.55.2 and TM beta 4.5.5663.

Please contact the script author if the problem persists.

**Comment by SHAKA12** [comment]
Hi guys,

Yes i DL using SaveFromNet, problem still persisting..This is weird cos its doing the same thing with YouTube downloader, all vids aI DL now dont have a title just 'videoplayback.' What is also strange is that it only shows the video title if i DL in HD...This is actually the 2nd time it does this, 1st time was a few years ago but the problem self corrected after a while...Hope someone has a solution would greatly be appreciated...
