### ISSUE TITLE
GM_download functionality too limited

### ISSUE THREAD

**Issue by L0laapk3** [Tampermonkey/tampermonkey#493]
it would be nice to have some extra control over `GM_download` while it is happening. I for example have multiple downloads going on from multiple sites and I want to cancel the slowest ones.

Proposed extra functionality:

1. `GM_download.onStarted`
Event that fires when the connection has established and the download has started.

2. `GM_download.onProgress`
Event that fires when download progress has been made.

3. `bool GM_download.abort()`
Attempts to cancel the download. Returns true if cancelled. Possibly, if the action of saving the file is asynchronous, another event to signal that the download is finalising and cannot be cancelled anymore.

**Comment by derjanb** [comment]
In fact Tampermonkey already supports onprogress, onload, onerror, ... listeners. I've updated the documentation to reflect that. 

http://tampermonkey.net/api#GM_download

Note: if "Download Mode" is set to "Browser API" onprogress listeners will start to work at TM (beta) 4.6 and above.
