### ISSUE TITLE
[Firefox] 4.6.5694beta - very sluggish interaction with the editor (opening scripts/typing/selecting text with mouse/scrolling)

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#497]
The issue is that, interaction with the editor (opening scripts/typing/selecting text with mouse/scrolling) has become very sluggish with the latest beta.
This has been introduced in the latest TM 4.6.5694beta and only for Firefox:
_none of the above happen with the latest beta in Chrome ,
and it also didn't happen with the in previous beta version, 4.5.5663 in Firefox,_

STR

In a fresh FF 58.0.1 profile with only TM 4.6.5694beta, install e.g. this script [MPIV](https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer).
open dashboard and click the Edit button for the script. 
You'll notice that:

- it takes unusually long (5 sec) just for the script to become visible in the Editor
- typing anything on the script is painfully slow to the point it becomes unusable,
- even selecting script parts with mouse is very slow
- scrolling, especially with the mousewheel is super slow, to the point that, at any time, with every mousewheel scroll, momentarily only half the screen has content and then the rest content is displayed.

**Comment by DanaMW** [comment]
I am still having this problem. TM is much slower to load a script into the editor, and once loaded it takes nearly 3 seconds per keystroke. (FF only)

**Comment by gsbabil** [comment]
I'm having the same issues in `4.6.5694beta`. My Firefox version is `59.0b7 (64-bit)`.

**Comment by DanaMW** [comment]
The last beta fixed this for me. Thank you. Closed for me.

**Comment by darkred** [comment]
@derjanb Thanks for the update. 
The performance has improved a lot (and there's no delay while typing anymore.), 
although for comparison it's still slower than in Chrome:
- in FF it still requires ~2-3 sec for the script to become completely visible in the Editor, it's opened partially, one third of the viewport at a time _(in Chrome the script opens almost instantly)_. 
- selecting script text with mouse is still a bit slower than in Chrome.
- n FF, with every scrolling there is still a delay before the last few lines of the viewport are displayed.

If there's no room for further improvement, please feel free to close this.

**Comment by derjanb** [comment]
Hi all, can you please re-test with the latest beta version from here: http://tampermonkey.net/?browser=firefox
Linting now is done in background.
Thanks.

**Comment by gsbabil** [comment]
Hi @derjanb , 

I'm currently using the following and can confirm that the
sluggishness I previously reported is gone.

- Firefox: `60.0b8 (64-bit)`
- Tampermonkey: `4.6.5741beta`

Thanks a lot.

**Comment by darkred** [comment]
@derjanb 
This issue is fixed for me. (FF 59, TM 4.6.5741beta )
Thank you.
