### ISSUE TITLE
Disable update checks on a script

### ISSUE THREAD

**Issue by JasonBarnabe** [Tampermonkey/tampermonkey#499]
Scripts on Greasy Fork do not have `@updateURL` or `@downloadURL`, so when checking for updates, the URL originally installed from is used when checking for updates. This is good.

Greasy Fork also allows users to install previous versions of a script. The install URL includes a parameter indicating in the version. In this case, updates still "work", but there will never be any changes. To save some resources on the client and the server side, I would like to indicate to Tampermonkey to not check for updates. Is there something I can put in the script to do this?

**Comment by derjanb** [comment]
Hi @JasonBarnabe, unfortunately there is no (non-hacky) way to achieve this at the moment. I think the best solution is to let Tampermonkey do this internally. Other solutions like reacting on a special response header, invalid downloadURL headers and so on don't seem to be the right solution. TM already recognizes GreasyFork as a script source and uses that information for issue URLs and some icons. I'll implement an additional  lookup for the version string and avoid update checks if it's there.

**Comment by JasonBarnabe** [comment]
A special value for `@downloadURL` like `@downloadURL none` wouldn't work? I'm not against you doing the special check for Greasy Fork but it seems like it should be something that can be used by other managers and hosts.

**Comment by derjanb** [comment]
> ```@downloadURL none``` wouldn't work?

That would work, but only for new script installations. If that's OK for you, then this is indeed a more elegant solution. Also there are no noteworthy negative side effects, at least at Tampermonkey. So from my point of view you can start to deliver this header as soon as you want.

**Comment by JasonBarnabe** [comment]
I have implemented this on Greasy Fork.

Do update: https://greasyfork.org/scripts/1-greasemonkey-test-style/code/Greasemonkey%20test%20style.user.js
Do not update: https://greasyfork.org/scripts/1-greasemonkey-test-style/code/Greasemonkey%20test%20style.user.js?version=172243
