### ISSUE TITLE
Sometimes not working on the top iframe

### ISSUE THREAD

**Issue by Ahaochan** [Tampermonkey/tampermonkey#500]
Chrome 63.0.3239.108 + Tampermonkey v4.5

I can not determine the exact timing of trigger this issue.
But this problem often appears when I first launch the browser.
This problem cause many unpredictable bug when I coding. 

such like this issue.
http://tieba.baidu.com/p/5542597610

 I try to run `console.log(location.href)` in `https://s.taobao.com/search?q=1060Ti`
But this `script` run in sub iframe and print `https://www.taobao.com/markets/search/search-suggest-history-iframe`, even if I use `//@noframes`.

After I restart Tampermonkey, the bug was fixed.
But this problem happened so often. I hope to resolve it. Thank!
![img1](https://s1.ax1x.com/2018/02/06/9Q5JtP.png)

**Comment by derjanb** [comment]
Should be fixed at MV3 with "Content Script API" set to UserScript Dynamic
