### ISSUE TITLE
Script editor find is only case sensitive for strings with caps

### ISSUE THREAD

**Issue by mattdeckard** [Tampermonkey/tampermonkey#501]
Say you have 3 instances of "foo" in your script, and 2 instances of "Foo". With the script editor open if you use the Search feature to find the string "foo" it sill match all 5 instances but if you search "Foo" it will only find the 2 that match case. This seems like very odd behavior.

**Comment by tophf** [comment]
That's the intended behavior of CodeMirror search. All lowercase input enables case-insensitive searching.

**Comment by derjanb** [comment]
Please check the latest Tampermonkey Beta version 4.6.5737.
