### ISSUE TITLE
GM_Download onload callback is called before download completion

### ISSUE THREAD

**Issue by granack** [Tampermonkey/tampermonkey#503]
I'm using the onload callback to know when a file has completed downloading. I'm downloading multiple files at once and want to add them to a list when completed.

I'm testing with an alert in the callback function, and the alert is popping up for files before Chrome even starts downloading them. 

(the files download fine, so furl and fname are good)

     function onDLcomplete(pid){
        alert("completed: " + pid);
    }
    
    GM_download({url: furl, name: fname , onload:onDLcomplete(id)});

The page I'm testing with has 6 files, but it will eventually be used with 100's of files. Chrome will only download 1-2 at a time, but I'm looping through an array to build urls and initiate the download, which is almost instant. I fully expect to be waiting for those 'success' callbacks.

**Comment by derjanb** [comment]
Should be fixed at the latest beta version (4.6.5703). Thanks for reporting.

**Comment by granack** [comment]
excellent, thank you!

**Comment by granack** [comment]
hmm, maybe I'm doing something wrong as I've never used callbacks before, but using beta 5703, i've added an 'onerror' callback. I get both onload and onerror alerts popping up for each file before Chrome even tries to download, both for valid downloads and invalid downloads due to garbage URL. 

    GM_download({url: furl, name: fname , onload:onDLcomplete(id), onerror:onDLerror(id)});

    function onDLcomplete(pid){
        alert("completed: " + pid);
    }
    function onDLerror(pid){
        alert("error on " + pid);
    }

**Comment by derjanb** [comment]
What download mode do you use? The two different ones are "Native" and "Browser API". "Default" uses "Browser API" if the download permission was granted and "Native" otherwise.

I'm testing with the following script:

```javascript
// ==UserScript==
// @name         Multiple GM_downloads
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://tampermonkey.net/empty.html
// @grant        GM_download
// ==/UserScript==

console.log(GM_info.downloadMode);
var start = Date.now();

for (var i=0; i<4; i++) {
    (function(c) {
        var url = "http://ipv4.download.thinkbroadband.com/10MB" + (c % 2 == 0 ? 'invalid' : '') + ".zip?ts=" + Date.now() + '&id=' + c;
        GM_download({
            name: "10MB-" + c + ".zip",
            url: url,
            onload: function() {
                console.log(c, 'success after', Math.round((Date.now() - start) / 1000), 'seconds', url, arguments);
            },
            onerror: function() {
                console.warn(c, 'error after', Math.round((Date.now() - start) / 1000), 'seconds', url, arguments);
            }
        });
    })(i);
}
```

The script's output in "Native" mode is:
```
native
0 "error after" 0 "seconds" "http://ipv4.download.thinkbroadband.com/10MBinvalid.zip?ts=1518897468736&id=0" Arguments
2 "error after" 0 "seconds" "http://ipv4.download.thinkbroadband.com/10MBinvalid.zip?ts=1518897468737&id=2" Arguments
1 "success after" 7 "seconds" "http://ipv4.download.thinkbroadband.com/10MB.zip?ts=1518897468737&id=1" Arguments
3 "success after" 8 "seconds" "http://ipv4.download.thinkbroadband.com/10MB.zip?ts=1518897468738&id=3" Arguments
```

and in "Browser API" mode:

```
browser
0 "error after" 0 "seconds" "http://ipv4.download.thinkbroadband.com/10MBinvalid.zip?ts=1518897381227&id=0" Arguments
2 "error after" 0 "seconds" "http://ipv4.download.thinkbroadband.com/10MBinvalid.zip?ts=1518897381229&id=2" Arguments
1 "success after" 5 "seconds" "http://ipv4.download.thinkbroadband.com/10MB.zip?ts=1518897381229&id=1" Arguments
3 "success after" 12 "seconds" "http://ipv4.download.thinkbroadband.com/10MB.zip?ts=1518897381229&id=3" Arguments
```

So everything seems to work as expected here.

**Comment by granack** [comment]
yep, wrapping the function in a function worked. totally not intuitive.  I'll mark this closed and go delve into learning about JS callbacks...  
Thank you much!
