### ISSUE TITLE
[Firefox] Right-clicking script in action menu breaks with auto syntax checking disabled

### ISSUE THREAD

**Issue by valacar** [Tampermonkey/tampermonkey#504]
If you disable the editor setting "Automatic syntax check on typing", right-clicking the name of script in the action menu just takes you to dashboard when it should actually open a tab with the script loaded in the editor. It makes no sense that auto syntax checking disables this feature.

Currently running Firefox 58.0.2 (64-bit) on Windows 7 with Tampermonkey 4.5.5660.

**Comment by derjanb** [comment]
Should be fixed at the latest beta version (4.6.5703beta). Thanks for reporting.

**Comment by valacar** [comment]
I installed 4.6.5703 beta and confirmed it's working properly now.  Thanks for fixing it so quickly.
