### ISSUE TITLE
'Use strict' breaks webforms postback in Firefox

### ISSUE THREAD

**Issue by nykkole** [Tampermonkey/tampermonkey#506]
Repro steps:
1) Use tampermonkey on asp.net webforms website
2) Have script click a submit button that causes a postback

Result:
Console error: "TypeError: access to strict mode caller function is censored"
![use strict error](https://user-images.githubusercontent.com/9709474/36185915-a2c6f740-10f0-11e8-9c97-e4a67cf03b31.png)

The error seems similar to [this](https://stackoverflow.com/questions/14533585/jqueryui-dialog-firefox-asp-net-access-to-strict-mode-caller-function-is-c). The solution called out here didn't work in tampermonkey. 

It appears that tampermonkey may be adding 'use strict' in a wrapping method:
![use strict in function](https://user-images.githubusercontent.com/9709474/36186021-3729ce76-10f1-11e8-833e-14ba1fb148a0.png)

Thank you

**Comment by derjanb** [comment]
@nykkole Using strict mode at this point is necessary. However, you're script run's only in script mode if you specify it. So you should be able to click that button by wrapping the caller inside a setTimeout callback:

```javascript
window.setTimeout(function() { button.click(); }, 0);
```

**Comment by nykkole** [comment]
@derjanb Unfortunately this workaround doesn't seem to be working for me. I still get the same error. Is there another workaround to escape strict mode?
