### ISSUE TITLE
[Firefox] Trying to retrieve iFrame content is unsuccessful

### ISSUE THREAD

**Issue by fakoukas** [Tampermonkey/tampermonkey#507]
Steps to reproduce the problem:
Cross origin iFrame can't retrieve content, like this:
$("#j-iframe").contents();

Expected behavior:
Contents are retrieved so something like this can work:
$("#j-iframe").contents().find(".btn1").click();

Tried the above code on chrome and got an exception, but using this command --disable-web-security --user-data-dir when launching chrome fixed the exception and now the script clicks the button normally. On firefox, nothing happens, no exception but no clicking the button either.

**Comment by derjanb** [comment]
You have to make your script run at the iframe URL as well. You can then use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to let the scripts communicate.

**Comment by fakoukas** [comment]
Thanks for the response, but i'm still uncertain on how to do it.
On my example i've tried clicking a button, how would i do that with postMessage?
