### ISSUE TITLE
Tampermonkey and aliexpress page

### ISSUE THREAD

**Issue by nic35025** [Tampermonkey/tampermonkey#508]
Hello,
When script run on url (exam. https://www.aliexpress.com/item/Car-Stereo-Bluetooth-HD-7-Touch-Screen-12V-2-Din-FM-Car-Radio-ISO-power-Aux/32821346518.html?spm=a2g0s.9042311.0.0.NUKRD4).
Chrome (63.0.3239.132 (Oficjalna wersja) (64-bitowa)): is ok
FireFox (57.0.2 (64 bity)): is not ok
Tampermonkey (4.6.5703 2018-02-19)
Script no see whole page but only see part of language menu( top of right).
- window.location.href  is as upper in url
- document.body.getElementsByClassName("total-price-show").length == 0 result is  true
This same check in console work ok result is false its ok
I use only configuration
// @match        *.aliexpress.com/*
add
// @match        *.aliexpress.com/item/* - also not work
On main page aliexpress also work ok.
Main problem is all elemnts when url have "https://www.aliexpress.com/item/*"

Best Reagards
nic35025

**Comment by derjanb** [comment]
Please use a valid match pattern: https://developer.chrome.com/apps/match_patterns

```javascript
// ==UserScript==
// @name         Match aliexpress
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*.aliexpress.com/*
// @match        *://*.aliexpress.com/item/*
// @grant        none
// ==/UserScript==

console.log(location.href);
```
