### ISSUE TITLE
when trying to edit requires it jumps to the edit tab of the base script

### ISSUE THREAD

**Issue by elypter** [Tampermonkey/tampermonkey#510]
when clicking the edit button of a require lib in the externals tab the browser gets sluggish for a few seconds and then jump to the edit tab of the base script. the edit tab of the require lib is being loaded but when clicking on it it always jumps to the base script tab. it does not happen with resources.

i am also suffering from the generally sluggish editor.

Tampermonkey v4.6.5703 in firefox 57.0.1 32bit on linux mint mate 18.3 32bit

**Comment by derjanb** [comment]
> when clicking the edit button of a require lib in the externals tab the browser gets sluggish for a few seconds and then jump to the edit tab of the base script. 

I can not reproduce this. :( Can you please try to create a new temporary profile and check that fixes the issue?

> i am also suffering from the generally sluggish editor.

Have you maybe noticed some speed related improvements at version 4.6.5709?

**Comment by elypter** [comment]
it happens if you open the second external of https://greasyfork.org/de/scripts/36901-blockhead

it is still very slow. especially when changing quotes because that temporarily creates many syntax errors.
