### ISSUE TITLE
Tampermonkey reruns the script if the page emits DOMContentLoaded

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#511]
Is it the intended/desired behavior?

To reproduce install the following userscript and scroll any long group on FB ([example](https://www.facebook.com/joancornella/)): when the page is dynamically updated by the site script you'll see multiple `=========== 123` in devtools console.

```js
// ==UserScript==
// @name   123
// @match  https://www.facebook.com/*
// ==/UserScript==
console.log('=========== 123');
```

**Comment by derjanb** [comment]
Wahh, I'll fix that...

**Comment by tophf** [comment]
FWIW, content scripts (`"run_at": "document_end"` or none specified) don't rerun on FB in this scenario.

**Comment by derjanb** [comment]
```javascript
// ==UserScript==
// @name   123
// @match  https://www.facebook.com/*
// ==/UserScript==
console.log('=========== 123', location.href);
```

Hmm, the location is different at each log. Do you see this as well? Most probably they're using iframes to load the content...

**Comment by tophf** [comment]
Indeed.
So it's not a bug.
A workaround would be to add `@noframes` in the metadata comment.
