### ISSUE TITLE
Notupdate script in Incognito mode

### ISSUE THREAD

**Issue by diyijing** [Tampermonkey/tampermonkey#512]
Chrome 
OS X
case:
Open an  Incognito window, then change and save the code in tampermonkey's editor, Refresh the Incognito window, the script still the old version

**Comment by derjanb** [comment]
This functions as intended. Please set "Config Mode" to "Advanced" and then change "Store data in incognito mode" to "Permanent".

**Comment by farzadmf** [comment]
@derjanb Can you please let me know where this settings is; this is what I see when I'm in Advanced config mode:

![image](https://user-images.githubusercontent.com/5768792/52654812-ce39be00-2ec0-11e9-8ad5-e05c9ed861d5.png)
