### ISSUE TITLE
update all script automatically (ever)

### ISSUE THREAD

**Issue by gabri25ele** [Tampermonkey/tampermonkey#513]
Is possibile to set update all the script automatically, without opening window with confirmation?
I selected the "update for simple script" in the advanced settings but no change.

**Comment by derjanb** [comment]
If "Don't ask me for simple script updates" is set and Tampermonkey still shows the update tab, then there were some warnings which Tampermonkey wants you to see. So this works as intended. Have you tried to confirm all updates? Most probably the next script updates will not trigger such a dialog again.

**Comment by gabri25ele** [comment]
I will try, thanks
