### ISSUE TITLE
[Firefox] Help. All scripts are gone.

### ISSUE THREAD

**Issue by AMZMA** [Tampermonkey/tampermonkey#517]
Help, all my scripts are gone after my laptop went bluescreen-ed.
Is any folder in firefox profile that store all my scripts? Where I can find it?

Thank you.

**Comment by derjanb** [comment]
Please locate your profile folder. (You should find it here: `%APPDATA%\Mozilla\Firefox\Profiles` or `~/.mozilla/firefox/`)
It should contain a file called `[your_profile_id]/browser-extension-data/firefox\@tampermonkey.net/storage.js` which stores all Tampermonkey data.

**Comment by AMZMA** [comment]
sorry for the late reply.
I found the "storage.js", but only with 1 KB.

**Comment by Technical-13** [comment]
I've found a `storage.js.migrated` file, (note: it's in `%APPDATA%\Roaming\Mozilla\Firefox\Profiles\[your_profile_id]/browser-extension-data/firefox@tampermonkey.net/`) how do I import it back into tampermonkey?

**Comment by beppe9000** [comment]
what is the path for this in the newer versions of firefox ?
