### ISSUE TITLE
tampermonkey wont make dans stay open in chrome 

### ISSUE THREAD

**Issue by viper78boy** [Tampermonkey/tampermonkey#520]
tampermonkey wont make dans stay open in chrome was working again up till tonight 3/8/2018 was working again up till tonight 3/8/2018 for zooworld classic game on facebook or in zooworld game period

**Comment by derjanb** [comment]
Hi, please contact the script's author. If there is an issue with Tampermonkey the he will contact me with some more technical details about the issue.
