### ISSUE TITLE
Execute script @ the unsafe context

### ISSUE THREAD

**Issue by sethfri** [Tampermonkey/tampermonkey#521]
I have a few Tampermonkey scripts in Safari 11.0.3, macOS 10.12.6. A few of them work great, but one of them only seems to run about 20-30% of the time. When I turn on the debug setting, I see that, for the scripts that work, they all emit this line:

```
[Debug] env: execute script [script name] @ the safe context now!
```

However, for the script that *doesn't* work, it emits the following line:

```
[Debug] env: execute script [script name] @ the unsafe context now!
```

It emits this line even when it does work.

What are the safe context and the unsafe context? How can I make the script that isn't working run in the safe context? That seems to be the only difference between the scripts that work and the one that doesn't work.

**Comment by derjanb** [comment]
If your script uses ```// @grant none``` then it will run at the "unsafe" context. If it uses any other value then "none" (i.e. ```// @grant GM_addStyle``` -> safe context) and including no ```@grant``` statement was given at all, then it will run at the "safe" context.

However, this shouldn't make a difference in timming. What ```@run-at``` values do these scripts have?

You may try to add ```// @run-at document-end``` to some scripts.
