### ISSUE TITLE
[Firefox] AMO no longer supports Beta versions

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#524]
[AMO has discontinued support for Beta versions](https://blog.mozilla.org/addons/2018/02/28/discontinuing-support-for-beta-versions/): it only supports signing self-hosted (unlisted) versions now.
_Before that, they were listed in https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/beta_

@derjanb, I've [noticed](https://tampermonkey.net/changelog.php?ext=dhdg&show=firb) that you've made a new beta version for Firefox, v4.6.5737 , two days ago.
What's the URL to install it? _(if you don't host it already, you could consider hosting it in GitHub, like e.g. uBO and uMatrix FF betas, or, obviously, in your site, tampermonkey.net)_

**Comment by derjanb** [comment]
...but it's still possible to upload betas. 😅 
https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/beta?page=1#version-4.6.5737beta

However, I have not thought about the future of FF betas yet.
And BTW, I think it's a pity to drop the possibility to have multiple channels, because it used to be very convenient.

**Comment by tophf** [comment]
I think creating a separate extension entry in the store - just like you do it already in Chrome gallery - will be much more convenient for users and will expose the extension to a wider audience. This is what I will do for Stylus in Firefox when the time comes. According to our statistics, a separate Chrome extension for Stylus beta has 10 times more users compared to the AMO beta channel users (the amount of stable channel users is roughly the same).

**Comment by FatOrangutan** [comment]
>I think creating a separate extension entry in the store

[From what I understand, this is being disallowed too.](https://github.com/gorhill/uBlock/issues/3538#issuecomment-367749878)

**Comment by tophf** [comment]
I don't see it being disallowed in the rules. Looks like an opinion of that particular reviewer.

**Comment by derjanb** [comment]
Firefox beta versions can be downloaded from here: http://tampermonkey.net/?browser=firefox
