### ISSUE TITLE
Use a worker for automatic syntax checking

### ISSUE THREAD

**Issue by blackholeearth** [Tampermonkey/tampermonkey#526]
editor  freezes  for 1 to 3 seconds when syntax error happens.

instead of checking sytax cant you make it about 2 or 5 second  interval .  or in seperate thread.

thanks

**Comment by derjanb** [comment]
You can also disable automatic syntax checking (`Automatic syntax check on typing`) or limit the max script size further (`Automatic syntax check max size`).

**Comment by tophf** [comment]
@derjan, are you using web worker for the linter? We've switched to that in Stylus so the page is no longer blocked/frozen.

**Comment by derjanb** [comment]
Fixed at TM BETA 4.6.5752
