### ISSUE TITLE
Tampermonkey script not auto-updating

### ISSUE THREAD

**Issue by reeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [Tampermonkey/tampermonkey#527]
```
// ==UserScript==
// @name         Test script
// @description  testing auto-update
// @namespace    http://tampermonkey.net/
// @author       newbie
// @version      1.0.0
// @updateURL    https://github.com/mygithubaccount/test/raw/master/test.user.js
// @downloadURL  https://github.com/mygithubaccount/test/raw/master/test.user.js
// @match        http://awebsite.com/*
// @run-at       document-end
// @grant        GM_getResourceText
// @grant        GM_addStyle
// @grant        GM_xmlhttpRequest
```

Please note that these values are just for example.

When I make changes on the script and increase the version number on github and then push the changes to master it updates the raw script link, however I don't get auto-updates from Tampermonkey as in popups saying the script has an update. It will only update if I manually go to the link and reinstall the script to update it.

How can I make this auto-update with popups?

**Comment by derjanb** [comment]
Please also see https://github.com/Tampermonkey/tampermonkey/issues/763#issuecomment-533284433

**Comment by derjanb** [comment]
Tampermonkey already requests a [revalidation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#cache_validation), but if the server/github responds with old/cached data there is nothing Tampermonkey can do.

![image](https://user-images.githubusercontent.com/767504/105348284-6a5dbb00-5be8-11eb-82ed-0397854ec3bb.png)
