### ISSUE TITLE
[Editor] Tab key not working for template strings

### ISSUE THREAD

**Issue by Eccenux** [Tampermonkey/tampermonkey#530]
Steps:

1. Create a user script.
2. Add template string (example below).
3. Use select part of a template string.
4. Press tab.

Result: No effect.
Expected: Selection should increase indentation.

Example code:
```javascript
    function addCss() {
        var cssText = `
.nux-ux-buttons {
position: fixed;
top: 0;
left: 0;
background: rgba(255, 255, 255, 0.5);
}
.nux-ux-buttons a {
display: block;
padding: .5em;
}
.nux-ux-buttons a:hover {
background: white;
}
`;
        GM_addStyle(cssText);
    }
    addCss();
```

**Comment by derjanb** [comment]
From my point of view this functions as intended, because adding indent levels modifies the template content, which is OK for CSS, but the editor can't know for what purpose the string will be used.

**Comment by MrAmericanMike** [comment]
As a reference and for those using (a different keyboard I guess) In my case with an spanish keyboard the combination for this was:

`Control + '` and `Control + ¡`

**Comment by Neutrino-Sunset** [comment]
Why in God's name do I need to press CTRL+[ in order to get a tab! And is there any way to configure it so that the tab key does what it does in every other editor I've ever used?

I've spent an hour trying to work out why the editor is broken!

**Comment by derjanb** [comment]
@Neutrino-Sunset You're searching for  `Settings > Editor > TabMode`

**Comment by Neutrino-Sunset** [comment]
Thanks, found it in the end. Pretty confusing though, especially as the setting isn't even visible in the default settings mode of `novice`.
