### ISSUE TITLE
Can't find the script-backup.zip in google drive 

### ISSUE THREAD

**Issue by WiliTest** [Tampermonkey/tampermonkey#533]
It's supposed to have backup the scripts 
![image](https://user-images.githubusercontent.com/24194840/38854319-61400936-4220-11e8-892b-85a74ace7d8c.png)

But when I look into the google drive I don't find the file:

![image](https://user-images.githubusercontent.com/24194840/38854437-c34368bc-4220-11e8-9367-793ef57430ac.png)

**Comment by derjanb** [comment]
Unfortunately application data is hidden from you by Google Drive. Maybe you can use this Python tool to access it: https://github.com/nelenkov/gdrive-appdata

**Comment by filbo** [comment]
I've just encountered this as well.  I do not have active / continuous gdrive sync turned on (haven't even checked to see if that's an option).  I manually saved via TM dashboard > Utilities > Cloud > Export.

When manually exporting, is it necessarily required (by the APIs you're using) to stuff it into the 'app' black hole?  Or could you just upload it as a regular file to the user's regular gdrive directory structure -- perhaps with slightly different APIs?

I realize that if you were to change that today, people's existing processes would be broken.  But suppose it was kept, renamed 'Google Drive (app storage)', and a new item 'Google Drive (user-accessible file)' was added?

I saw elsewhere that a similar issue applies with DropBox, so if you added this, I'd suggest adding it for both cloud back-ends.

Thanks!

**Comment by derjanb** [comment]
> When manually exporting, is it necessarily required (by the APIs you're using) to stuff it into the 'app' black hole?

@filbo Access to non-app folders needs another permission. With this permission is would indeed be possible to store Tampermonkey's data at a user visible folder, but Tampermonkey would get access to all Google Drive data as well.
Also Google reviews all apps/extensions that need this kind of permission and it would be hard to explain, why app data is not stored at the app data folder:

Scope | Meaning | Usage
-- | -- | --
https://www.googleapis.com/auth/drive | Full, permissive scope to access all of a user's files, excluding the Application Data folder. | Restricted

Restricted - These scopes provide wide access to Google User Data and require you to go through a restricted scope verification process. For information on this requirement, see Google API Services: User Data Policy and Additional Requirements for Specific API Scopes. if you store restricted scope data on servers (or transmit), then you need to go thru a security assessment.

https://developers.google.com/drive/api/v3/about-auth

**Comment by filbo** [comment]
Ok, I understand the tangle of conflicting goals here.

The _correct_ solution (but which Google is unlikely to do) is for them to add an API flag which amounts to 'do, or do not, expose this app's data to user view within their regular Google Drive folder hierarchy' -- defaulting to 'do not', of course, for backwards compatibility.  That would give the app no additional permission to the user's data; only give the _user_ additional permission to the _app_'s data.  (Which we really ought to have in the first place, but presumably Google has their reasons for that and would only give it up on a per-app basis as chosen by the app's authors -- in turn probably driven by user-set app options.)

**Comment by alexchexes** [comment]
More and more happy that I use Dropbox instead of this "Google knows-better-than-you-what-you-need Drive".
