### ISSUE TITLE
Youtube Download Script is GONE!!!!!!!

### ISSUE THREAD

**Issue by marcelo-anexa** [Tampermonkey/tampermonkey#534]
I can not even see that DOWNLOAD button anymore...

**Comment by derjanb** [comment]
Do you still see it being installed in Tampermonkey?

**Comment by joeytwiddle** [comment]
Which script ... ?

This might just be a change on Youtube's site, rather than a bug with TamperMonkey.

**Comment by marcelo-anexa** [comment]
So, what?
How to fix that, please?

**Comment by joeytwiddle** [comment]
You need to provide more information if you want someone to help you.

A link to the **webpage** where the script is hosted would be good. Failing that, the name of the script would be a start.

----

(Personally I gave up on gantt's userscript and started using [youtube-dl](https://rg3.github.io/youtube-dl/) instead.)

**Comment by marcelo-anexa** [comment]
"Download Youtube Videos and Subtitles" - not working
"Youtube Best Video Downloader 2" - not working
"Youtube Subtitle Downloader v15" - not working

And I have no idea how to use youtube-dl.

**Comment by joeytwiddle** [comment]
Here is another one, although the source code is rather difficult to read: https://openuserjs.org/scripts/laidbacktempo/EasyVideoDownload/source

**Comment by marcelo-anexa** [comment]
Thank you Joey, but it seems that http://savefrom.net site is dead...

**Comment by derjanb** [comment]
This issue is caused by a third-party script. Please contact the script's author.
