### ISSUE TITLE
ESLint not recognizing async keyword

### ISSUE THREAD

**Issue by minimeh** [Tampermonkey/tampermonkey#535]
TM version: 4.6.5757

Browser: Firefox 59.0.2 (64-bit); Chrome  66.0.3359.117 (Official Build) (64-bit); Vivaldi 1.15.1146.5 (Official Build) (32-bit)
Steps to reproduce: Mark any function with "async"
Expected: eslint accepts syntax
Found: eslint flags as "Parsing error: Unexpected token function"

Similar to issue #519 "Editor complains on async" which is marked "Fixed at TM BETA 4.6.5752".

![tm-v4 6 5757-async-error](https://user-images.githubusercontent.com/9537103/38966144-8e216e0c-4335-11e8-93a3-a80134468420.jpg)

**Comment by derjanb** [comment]
Fixed at the latest beta.
