### ISSUE TITLE
[BUG] strange dragging bug in github projects

### ISSUE THREAD

**Issue by noe132** [Tampermonkey/tampermonkey#539]
## what's happend
I can't drag cards in github repo's projects from one column to another.

## what caused this
tampermonkey.
As long as I disable the tampermonkey extension from chrome extensions, or, disable all userscript from dashboard, I can drag the cards again.

## step to reproduce
1. get a fresh chrome profile by running `chrome --user-data-dir=c:\new_profile\`
2. install `tampermonkey` from chrome store
3. create a new script contain following codes:
```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      *
// @grant        GM_addStyle
// ==/UserScript==

// GM_addStyle('a{color:green}');
document.createElement('span');
```
4. login into github and create a test repo, and create a project, then add some column and cards
5. if the userscript above was saved and enabled, then you can'y drag the cards to another column, or drag the column to sort them, it shows that a forbidden mouse cursor.

## enviroments
Chrome 66.0.3359.139
Windows 10 1803
Tampermonkey 4.5

## screenshots
![image](https://user-images.githubusercontent.com/2271900/39668082-dfc285d8-50f6-11e8-9904-8d593287e52c.png)
![image](https://user-images.githubusercontent.com/2271900/39668086-e52bb666-50f6-11e8-97cd-bfab1c5c2450.png)

## additional infomation
If I change code to 
```javascript
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      *
// @grant        none
// ==/UserScript==

// GM_addStyle('a{color:green}');
document.createElement('span');
```
the drag works again like normal.

**Comment by derjanb** [comment]
Fixed at the beta version (#498). A new stable version will be released soon.
