### ISSUE TITLE
Request for a Searchbox in the Script Manager

### ISSUE THREAD

**Issue by mikhoul** [Tampermonkey/tampermonkey#540]
Hi,

I'm new to Tamper Monkey and I have lot of scripts, what would be really useful for users that have lot of scripts like me would be to have a "search box" in the Userscript Manager page.

Instead of scrolling to find a script we would have just to type few letter to find the relevant Userscript.

Regards :octocat:

**Comment by tophf** [comment]
Press Ctrl-F or Cmd-F or the filter funnel icon in the column header.

**Comment by mikhoul** [comment]
@tophf Thaks a lot :+1:  

A small suggestion maybe you could add some light colors to the Funnel icon or to make it like a button like a button, I was assuming it was just a part of the header to show that you can click on the "headers themselves to sort like in windows.

![funnelbutton](https://user-images.githubusercontent.com/5678673/39938453-03a646e6-5521-11e8-8687-3bcbc3cbe31d.png)
![funnelbutton2](https://user-images.githubusercontent.com/5678673/39938454-03b84b02-5521-11e8-8bd1-21e61e008ffc.png)


Regards :octocat:
