### ISSUE TITLE
Tampermonkey icon taking half of the addressbar space

### ISSUE THREAD

**Issue by Arcnor** [Tampermonkey/tampermonkey#541]
After today's update, Tampermonkey is taking half of my addressbar space:

![tampermonkey_issue](https://user-images.githubusercontent.com/28616/40205992-943c854e-5a71-11e8-9712-756a6c83a243.jpg)

**Comment by derjanb** [comment]
I don't think this is related to Tampermonkey's update and even if it is, then your address bar width is out of reach for browser extensions. 

However, you should be able to fix this by clicking at the little space right of the address bar (marked with the red circle) and moving the mouse to the right while keeping the left mouse button pressed.

![image](https://user-images.githubusercontent.com/767504/40222518-058f0132-5a80-11e8-967e-60572e35a235.png)
