### ISSUE TITLE
Extension crashes while reordering userscripts

### ISSUE THREAD

**Issue by Mottie** [Tampermonkey/tampermonkey#543]
Using Tampermonkey BETA 4.6.5769 in Chrome 66.0.3359.181 (Official Build) (64-bit).

While reordering userscripts, if the handle is moved too far from the vertical column, the browser locks up. In the console (cut off in the screenshot), only this warning is shown:

> [Violation] Forced reflow while executing JavaScript took 32ms

![](https://user-images.githubusercontent.com/136959/40389176-41669cec-5dd7-11e8-86d4-e840a62cf9c6.gif)

The only way to recover the tab is to end the process in the task manager, then reload the extension.

![](https://user-images.githubusercontent.com/136959/40389458-253ea4b4-5dd8-11e8-9b7f-ff5246d37986.png)

**Comment by derjanb** [comment]
Please excuse the delay. I was on parental leave. :) Fixed at TM BETA 4.9.5960.
