### ISSUE TITLE
When we blacklist a page, can we blacklist all its iframes too?

### ISSUE THREAD

**Issue by joeytwiddle** [Tampermonkey/tampermonkey#544]
My example case is GMail.

I have a few userscripts which run on every page. Usually this isn't a problem, but GMail opens a great many iframes! Some of my scripts check if they are in an iframe and immediately exit, but not all of them.

I added `https://mail.google.com/*` to Tampermonkey's global blacklist, which worked, but it only applied to the top level window.

Despite being red-eye disabled, Tampermonkey still loaded more than 100 userscripts for all of GMail's iframes!

**So, would it make sense to blacklist all iframes under a blacklisted page?**

> Alternatively (and more controversially) we could have an option to disable all userscripts in iframes until they are specifically enabled? (E.g. a checkbox for each script, or a meta `@allowed-in-iframes`.) I suggest this because most scripts don't need to run in iframes, but most userscript authors fail to add a check to prevent it.

**Comment by derjanb** [comment]
> I added https://mail.google.com/* to Tampermonkey's global blacklist, which worked, but it only applied to the top level window.

This is how Tampermonkey works, URL-based not frame-based. That's why it doesn't make sense to blacklist all frames of blacklisted top-level frame URLs.

I understand your issue, but all I can suggest at the moment is to manually overwrite the "Run only in top frame" setting of each script.
