### ISSUE TITLE
[Firefox] Can not work in container tabs

### ISSUE THREAD

**Issue by FlandreDaisuki** [Tampermonkey/tampermonkey#545]
## Step to reproduce:
1. Open a [container tab](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers) and write userscript that `console.log` something

## Expect:
see output in console

## Actual:
see nothing in console

**Comment by derjanb** [comment]
A simple test script seems to work fine in container tabs in FF Nightly 62.0a1. What version are you using?

```JavaScript
// ==UserScript==
// @name         Log location
// @namespace    http://tampermonkey.net/
// @version      0.1
// @match        *://*/*
// @grant        none
// ==/UserScript==

console.log("...", location.href);
```

**Comment by bashenk** [comment]
This issue has resurfaced in the Firefox Beta channel.
My Firefox version is 72.0b3 (64-bit).

Steps to reproduce:

1. Create a new Firefox profile and open a new browser session with that profile.
2. Install Tampermonkey and add the test script from [derjanb's comment](https://github.com/Tampermonkey/tampermonkey/issues/545#issuecomment-393279055).
3. Open a new tab in any container (i.e., any container that is not the lack of a container) and browse to any website.
4. View the console and note there is no respective log entry.

The only exceptions I have found are when navigating to a site that uses a redirect (i.e., HTTP 301; e.g., https://gmail.com) or when the browser is first launched and the current tab is loaded for the first time.
