### ISSUE TITLE
YAYS app not working on youtube

### ISSUE THREAD

**Issue by Gorothomas** [Tampermonkey/tampermonkey#546]
Hi,

I've been using YAYS script on tamper monkey for almost an year. When I first installed the script I got extra controls on the video via tamper monkey script. 

But as of late I'm not getting the usual "gears" icon that i previously had. I'm forced to always select the video quality from the currently playing video settings. 

I've slow connection and don't stream HD videos on Youtube. can anyone guide me on what I've missed or overlooked.

Thanks in advance for your efforts to sorting out the issue.

regards
Thomas

**Comment by derjanb** [comment]
Please contact the script developer. Thanks.
