### ISSUE TITLE
The 'Aa' (case sensitive) option in Editor search works opposite than expected

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#548]
Currently (TM 4.6 stable/4.6.5769 beta in Chrome 66 and Firefox 60), when pressing Ctrl+F in Editor,
it does a case-sensitive search by default, 
and enabling the 'Aa' option does a case-insensitive search, instead of the opposite, as expected,
i.e. yes 'Aa' is disabled(unticked) by default:
![2018-05-26_001905](https://user-images.githubusercontent.com/723651/40566680-865424a0-607a-11e8-9647-11a5494199ac.jpg)
**but** if you enable it, it will do a case-insensitive search.

---

In contrast, for reference, in popular editors such as Sublime Text and Visual Studio Code
the search works case-insensitive by default, 
i.e. the relevant 'Aa' option (which in both cases is disabled by default as well)
means to enable case-sensitive search.

Thank you

**Comment by derjanb** [comment]
Fixed at TM Beta 4.7.5788

**Comment by darkred** [comment]
Thanks for the fix!
