### ISSUE TITLE
[CHROME] Only download the first video (vimeo.com) if have posted multiple

### ISSUE THREAD

**Issue by radovskiy** [Tampermonkey/tampermonkey#550]
Only download the first from video player.vimeo.com if have posted multiple. [CHROME] 
Can someone fix?

**Comment by tophf** [comment]
Multiple automatic downloads are disabled in new Chrome. You can inform the author of the userscript for vimeo and suggest they implement the workaround mentioned in https://crbug.com/822542#c16

**Comment by derjanb** [comment]
@radovskiy Have you tried to set "Download Mode" to "Browser API"?

**Comment by radovskiy** [comment]
I'll describe the problem in more detail. On the page there is a frame in which the video player is displayed and there are several buttons - video # 1, video # 2, video # 3 ... and so on. Default viewing of video # 1. When you press # 2 or # 3 ... - the frame is overloaded and you can view the next video # 2 or video # 3 ... But the Savefrom.net script button always loads video # 1 when switching to video # 2 or # 3 .. .

**Comment by derjanb** [comment]
Well then this is a script related problem, isn't it? Have you tried to contact the script author?

**Comment by radovskiy** [comment]
I understood, thank you
