### ISSUE TITLE
Script keeps getting removed

### ISSUE THREAD

**Issue by hemlok89** [Tampermonkey/tampermonkey#551]
I have been using a script called Kissanime downloader for a long time. But suddenly the script along with some other scripts got deleted from Greasyfork. And Tampermonkey keeps deleting the script contents. I have to manually paste the scipt in editor each time. Is there any way to stop this or at least detaching the script from its update source?

**Comment by derjanb** [comment]
Just open the Dashboard, open the script, click at the script's settings tab and un-check "Check for updates".

I don't think I should do something to "fix" this, because there might be a good reason for Greasyfork to remove a script (i.e. malware). Can you please send the update URL of such a deleted script?

**Comment by hemlok89** [comment]
This is the authors page link.

https://greasyfork.org/en/users/135934-anime-bro

This is the github link 

https://github.com/Eltion/Kissanime-Downloader

**Comment by derjanb** [comment]
And what was the Greasyfork URL? You can find it at the script's settings tab:
![image](https://user-images.githubusercontent.com/767504/40880696-e8b02716-66b5-11e8-95a1-345c690e54cf.png)

**Comment by filbo** [comment]
There's a https://greasyfork.org/en/scripts/31080-kissanime-downloader which greasyfork claims 'This script has been deleted', while still offering code in the Code tab (?!?)

**Comment by derjanb** [comment]
@filbo Thanks a lot.

@hemlok89 OK, the "problem" is Greasyfork delivers an empty but valid version of the script. This is nothing that Tampermonkey can/should detect. Greasyfork also states:

> This script was deleted from Greasy Fork, and due to its negative effects, it has been automatically removed from your browser.

This means they are aware of  the removal. So I assume they do have theirs reasons to remove it from all user's browser.

Please manually configure the script to not update or file a new issue at [Greasyfork](https://github.com/JasonBarnabe/greasyfork).

![image](https://user-images.githubusercontent.com/767504/41004791-66a45248-691b-11e8-83a0-9ef343361e61.png)

**Comment by filbo** [comment]
greasyfork moderately at fault here for not documenting 'its negative effects' with at least a link to bug report, discussion or whatever...
