### ISSUE TITLE
[Firefox Android] TM has no effect on all existing tabs

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#555]
Re: https://github.com/OpenUserJS/OpenUserJS.org/pull/1376#issuecomment-393463295

@derjanb 
So here's some test data:

Portable: Samsung Galaxy S8 *(near 100% charge)*
AndroidOS: 8.0.0 *(all updates including Apps... Android security patch level 2018-05-01)*
Fx: 60.0.1
TM: 4.6.5757

1. Install TM for Fx Android ... Cleared private data first and restarted App... only Add-on besides the Cisco x.264 video default with Fx
2. Attempt to install oujs - Meta View... result **FAIL** ... Create New User Script... result **PASS** *(then deleted)* *(possible work-around point)*
3. Attempt to install GM_config Unit Test... result **PASS** *(Glad this works on Android Fx)*
4. Uninstall TM, reclear Private Data, Restart App, repeat step 1, repeat Create New User Script... **PASS** *(then deleted)*... Attempt to install oujs - Meta View... result **FAIL**... attempt to install GM_config Unit Test... result **FAIL** *(work-around point possibility failed)* 

Animated screen caps *(Note: these will be deleted as soon as you respond)*
* https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/TMtemp/FxInstall.gif
* https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/TMtemp/FxTry3.gif
* https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/TMtemp/FxTry4.gif
* Try1 and Try2 were undocumented other than my comments starting at https://github.com/OpenUserJS/OpenUserJS.org/pull/1376#issuecomment-393388344 ... both times were only tested for script installs from OUJS.

Results for Try3 and Try4:
* Create New User Script ... 100% PASS *(2 tests)* on script store and script injection
* Install User Script *(either from OUJS or GF)* ... 20% PASS *(5 tests)* on script intercept, script store, and script injection
* Current state... refuses to intercept script source from OUJS and GF
* Remote Debugging over WiFi didn't show anything in the Console... not worth screenshotting at this time
* Latest GM 4.4.0 works 100% of the time *(so far)* on script installs when tested a few days ago.
* Learned Samsungs default On Screen Keyboard *(OSK)* is not the greatest when it comes to using the needed <kbd>Ctrl</kbd> + <kbd>S</kbd> to save new scripts... learned about a little adapter in my phone box too that allowed me to hook up a real keyboard. Learned I still prefer a real computer such as a desktop. ;) :)

Let me know if you want me to try anything else or need some more general data.

Official business of OUJS Active Maintainer
Thanks for the look.

**Comment by derjanb** [comment]
Looks like this is a known Firefox Android issue. You have to open a new tab to make all the magic work.

https://bugzilla.mozilla.org/show_bug.cgi?id=1410749 https://github.com/gorhill/uBlock/issues/3148

**Comment by Martii** [comment]
Goofy unexpected error of them... seems to be the work-around from the last state of not wanting to show. Thanks for looking into this. I'll run through some more tests again with this in mind and update OUJS ... all after some sleep first. :)

**Comment by Martii** [comment]
So don't know if you want this closed or not. Testing passed with closing all tabs and starting new tabs from scratch and our docs are updated to reflect. Appreciate the research again.

**Comment by Martii** [comment]
It's actually all tabs... not just the first tab

**Comment by derjanb** [comment]
Of course. Thanks. :)
