### ISSUE TITLE
Support for opera?

### ISSUE THREAD

**Issue by hemlok89** [Tampermonkey/tampermonkey#556]
I recently tried switching to opera browser. Most of my extensions are supported but when I searched for Tampermonkey, it has not been updated for over a year! Is there any chance that Opera will get an updated version?

**Comment by tophf** [comment]
Opera's review process for their extensions gallery often takes many months so developers simply forget about it. Instead, you can simply install Tampermonkey from the Chrome WebStore: [tutorial](https://www.techsupportalert.com/content/how-install-chrome-extensions-opera.htm).
