### ISSUE TITLE
[macOS plus Safari]: Script installs seem to invoke browser back in history

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#557]
Steps to reproduce:

1. Navigate to https://openuserjs.org/scripts/sizzle
2. Then click on The GM_config Unit Test in the script list.
3. Click the install buttons *(ours then yours)*
4. Watch as the other tab does what looks like a back history action.

This was just reinstalled from scratch so here's what we post for the installation currently... notice that it's on sizzles script list page instead of the Unit Test:

<a href="https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/tampermonkey_sa4.gif"><img src="https://raw.githubusercontent.com/wiki/OpenUserJS/OpenUserJS.org/images/tampermonkey_sa4.gif" alt="TM for Safari Script Install oddity" title="Click to enlarge" width="89" height="54" /></a>

Is this normal? *(seems like it is generating extra traffic that really shouldn't happen)*

**Comment by derjanb** [comment]
Indeed. Will be fixed at the next release. Thanks for reporting.

**Comment by Martii** [comment]
@derjanb 
Does this mean it's been fixed? or did you give up on it? Without downloading it, which is a pain to install via VNC since macOS Safari is stupid on not allowing installations via remoted keyboards... there really isn't a way on your site to tell what version you have posted that I see readily.

**Comment by derjanb** [comment]
It's fixed. :) http://tampermonkey.net/changelog.php?version=4.7.5788&ext=G3XV

**Comment by Martii** [comment]
Thanks.
