### ISSUE TITLE
add support for getResponseHeader method on GM_xmlhttpRequest

### ISSUE THREAD

**Issue by volkirik** [Tampermonkey/tampermonkey#562]
Could you please add support for getResponseHeader method on GM_xmlhttpRequest

## Expected Behavior
same as XMLHttpRequest.getResponseHeader(headerName)
please see : https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader

## Actual Behavior
undefined function

## Specifications
- Chrome: 66.0.3359.181
- TM: v4.6
- OS: Windows NT 10.0; Win64; x64

## Script
Applies to all user-scripts

**Comment by volkirik** [comment]
Please see : https://github.com/Tampermonkey/tampermonkey/pull/563

**Comment by derjanb** [comment]
Please use `response.responseHeaders`.

```JavaScript
// ==UserScript==
// @name         Get Response Header
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://test.tampermonkey.net/empty.html
// @connect      tampermonkey.net
// @grant        GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
    url:      'http://tampermonkey.net/faq',
    onload:   function(r) {
        console.log(r.responseHeaders);
    }
});
```

**Comment by volkirik** [comment]
I can't, I am feeding hls.js with GM_xmlhttpRequest, please implement the function

**Comment by derjanb** [comment]
Then you have to write your own wrapper, i.e. something like this: https://github.com/damoclark/gmxhr/blob/master/index.js
