### ISSUE TITLE
Accessing and editing files with the help of NiklasGollenstede's native-ext

### ISSUE THREAD

**Issue by brunoais** [Tampermonkey/tampermonkey#567]
Even if as an extension to tampermonkey, are there any opinions or tests for making code to work in conjunction with [NiklasGollenstede's native-ext](https://github.com/NiklasGollenstede/native-ext) to provide back file editing in the user's preferred editor?

**Comment by cmalard** [comment]
Just discovered it in the [reStyle extension](https://addons.mozilla.org/fr/firefox/addon/re-style/), [suggested by Stylus](https://github.com/openstyles/stylus/wiki/Styling-Firefox-UI).
Would be awesome :tada:

**Comment by derjanb** [comment]
I've choosen to implement my own solution which is based on Tampermonkey's recently added WebDAV support.

[Tampermonkey/tamperdav](https://github.com/Tampermonkey/tamperdav#readme)

**Comment by derjanb** [comment]
You can now [make the editor track a local file](https://github.com/Tampermonkey/tampermonkey/issues/2722#issuecomment-4177792617) (File > Track from disk; Chrome+MS Edge Only)
