### ISSUE TITLE
TamperMonkey  v4.7.5798 Beta Issue with File save.

### ISSUE THREAD

**Issue by DanaMW** [Tampermonkey/tampermonkey#570]
(Please fill out the issue template with your details)

## EB
When clicking in the editor to save the file to the hard drive it should use the saved file name, apply it and save.
## AB
When I edit internally and save it to HD it appends an extra .user.js to the file name.
## Spec
Firefox Developers Ed.  v62.0b3
TM v4.7.5798 Beta
PS C:\> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
10     0      17134  0       
## Script
```
// ==UserScript==
// @name          SienaAutoLogon.user.js
// @namespace    file:///D:/MyScripts/js/SienaAutoLogon.user.js
// @version        0.0.1
// @description  An Open Router Auto logon Script
// @author        Dana MW
// @match        http://***.**.**.46:1111/web/Siena.html
// @icon           https://danamw.github.io/img/eyeball128.png
// @require      https://code.jquery.com/jquery-latest.js
// @grant        none
// ==/UserScript==

(function($) {
    'use strict';
    console.log('DEBUG: JQuery loaded!');
})(jQuery);

$(window).load(function() {
    console.log('DEBUG: The Window Load Is Complete ');
});
```
========================
`I had just started writing it and after putting something in the editor to be able to save iti, save noticed the problem. I unloaded the script restarted the browser  created a new one, pasted it back in, still did it. I Attempted it again but this time loaded it from the HD and still it did it.It may be me somehow I tried triple checking but i figured you would like to know ,  Thank you J.B.

**Comment by derjanb** [comment]
```@name``` usually does not end up on ".user.js". Just name your script "SienaAutoLogon" and Tampermonkey will save it as "SienaAutoLogon.user.js".

**Comment by DanaMW** [comment]
So has this been corrected or did you just closed it?
