### ISSUE TITLE
Powerbot + not working.

### ISSUE THREAD

**Issue by Galvatron1** [Tampermonkey/tampermonkey#571]
(Please fill out the issue template with your details)

## Expected Behavior
enter "kingdoms of camelot" facebook game by RockYou and powerbot tabs are usually available.

## Actual Behavior
no powerbot tabs of any kind

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact the script author. Thanks.
