### ISSUE TITLE
Doubles the extension(s)

### ISSUE THREAD

**Issue by DanaMW** [Tampermonkey/tampermonkey#576]
When I rename a user.js and save it to hard drive it doubles the  extensions. *.user.js.user.js
It even retained that property after removing it and reinstalling the script without cycling TM or  restarting  the browser implying that the saved info wasn't removed till cycle or restart. Thought you would care to know.

Spec
Windows 10 Pro 10.0.7134.0
TamperM 4.7.5811

Script
Any User script. ( filename.user.js )

Thanks again.

**Comment by derjanb** [comment]
Duplicate of #570

**Comment by DanaMW** [comment]
Sorry about that. I did an inadequate search, I missed it.
