### ISSUE TITLE
TamperMonkey package manager file / export list of installed scripts' updateURLs

### ISSUE THREAD

**Issue by PatMyron** [Tampermonkey/tampermonkey#577]
## Expected Behavior

I'd like some way to better manage the installed userscripts between multiple machines. 

One idea would be the ability to export/import a list of the installed userscripts' URLs

## Actual Behavior

N/A

## Specifications
- Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- TamperMonkey: Version 4.6
- MacOS Sierra 10.12.6 (16G1510)

## Script

N/A

**Comment by derjanb** [comment]
Please see #288 for a working cross browser sync (Google Drive, Dropbox, OneDrive). Tampermonkey BETA recently got WebDAV based sync (OwnCloud, NextCloud, ...) #407.

If you want to export and import scripts manually, then you can do this at the "Utilities tab".
