### ISSUE TITLE
User script not executed, if javascript disabled

### ISSUE THREAD

**Issue by guraga** [Tampermonkey/tampermonkey#582]
Steps to reproduce:
* open "chrome://settings/content/siteDetails" and disable javascript;
* create user script like following:
```js
// ==UserScript==
// @name        Simple user script
// @version     1
// @include     http://*
// @include     https://*
// ==/UserScript==

console.log("Hello from user script");
```
* open console and open any page.

Actual behavior: user script not executed and do not print text to console.

Expected behavior: for each user script provide option to enable or disable script execution, if javascript disabled.

Versions:
- official build of 64-bit google chrome 68.0.3440.75;
- TamperMonkey 4.6 from "https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo".
- OS: ubuntu 16.04.

**Comment by derjanb** [comment]
JavaScript execution is needed in order to execute userscripts. There is no way for Tampermonkey to inject the scripts if this setting is disabled. That's why I'm setting this to `wontfix` even though it's more a `cantfix`.
