### ISSUE TITLE
Changelog opens every time chrome is launched

### ISSUE THREAD

**Issue by KaelWD** [Tampermonkey/tampermonkey#583]
## Expected Behavior
Nothing

## Actual Behavior
Every time I open chrome, the tampermonkey changelog is opened in a new tab. The exact URL is https://tampermonkey.net/changelog.php?version=4.6&ext=dhdg&updated=true&old=4.5&intr=true

## Specifications

- Chromium: 68.0.3440.84
- TM: 4.6
- OS: kubuntu 17.10

"On start-up" is set to "Open the New Tab page", so it isn't just chrome starting where I left off.

**Comment by derjanb** [comment]
Looks like your Chrome profile is broken. Please try a new temporary profile.
