### ISSUE TITLE
#/ in URL not capturing by Tampermonkey

### ISSUE THREAD

**Issue by sachinsunny27** [Tampermonkey/tampermonkey#584]
Hello Experts

i am just a beginner and learned Javascript just to fullfil my requiement on a specific website. learned over www.w3schools.com and many problem solved by stackoverview answers, not on my question but answers on others questions which was similar to my problem.  After 40 days i made the script of almost 200 lines which is store here on a URL  and working well by clicking bookmarklet which is inserting script on the page.

Now i want to run it automatically on the specific URL .

after some reading i came to know that it can be done through Tampermonkey Script 

i made  and tried and tried but no changes then started reading again and came to know that my URL is having #/ (Fragment Identifier) thats why it is not working as @ match and @including doesn't support it

i just made a simple bookmarklet for other website and tried with tampermoney. it is working well

i am just a beginner so not being able to find any solution after reading as well 

// ==UserScript==
// @name         SACHIN
// @namespace    https://www.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal/index.html
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal/index.html?sap-client=001&sap-language=EN#/Depot-Dispatch-Detail/6*
// @grant         NONE
// ==/UserScript==

my script

I also want to say that before 40 days i even don't know, what javascript is.
please help experts

Thanks in Advance

SACHIN

**Comment by derjanb** [comment]
The hash component is not taken into consideration when Tampermonkey determines if a script needs to be executed, because it is not send to the server anyway and it can change without a page reload.

**Comment by sachinsunny27** [comment]
Sir,
as a beginner i am not being able to understand. can you explain?

**Comment by tophf** [comment]
The purpose of issues here is to report bugs in Tampermonkey or suggest features, this is not the right place to ask about writing JS code.

**Comment by sachinsunny27** [comment]
ok sir then consider my issue as a suggestion
,

**Comment by tophf** [comment]
Handling # in the URL is not Tampermonkey's job as explained above, it's something you can do in your userscript with a relative ease, and I believe there are many answers for that on stackoverflow.com. Off the top of my head, there's a `hashchange` DOM event.
