### ISSUE TITLE
Windows 10 RS5 broke Tampermonkey's require function

### ISSUE THREAD

**Issue by lychichem** [Tampermonkey/tampermonkey#585]
(Please fill out the issue template with your details)

## Expected Behavior
Userscripts included other scripts by `@reqiure` should work properly.

## Actual Behavior
On Windows 10 RS5 build 17741, scripts with `@reqiure` cannot work properly.

## Specifications
One of a test script can be found here: https://github.com/zanetu/direct_google . After install, the script should work as it clamed, but it not work and the console says "$ is not defined". And tampermonkey says the outer script it required is 0 KB. The issue is not limited just to this script. 
- Edge: 18.17741
- TM: 4.6.5757
- OS: Windows 10 build 17741

## Script
https://github.com/zanetu/direct_google (not limited to single script, the issue affects many scripts)

Besides, not all `@require` will be broken. Some will work. But I don't know why.

**Comment by derjanb** [comment]
I've seen this as well. Unforuntely I don't know a wa to fix it. https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18723722/

**Comment by lychichem** [comment]
@derjanb The link you give is also reported by me😂 I report this issue to Edge issue tracker just want to tell Microsoft programmers "hey there is a bug, and maybe only you Microsoft guys can fix it".

**Comment by derjanb** [comment]
I found a workaround. Will be fixed at the next MS Edge version.
