### ISSUE TITLE
User definable script update (sync) interval?

### ISSUE THREAD

**Issue by Swiftnesses** [Tampermonkey/tampermonkey#588]
I'm now using WebDav and would like to sync my scripts every few minutes, rather than every 6 hours, could this be made possible?

**Comment by derjanb** [comment]
Tampermonkey will poll for changes every 30 minutes. If you want to decrease the poll interval (for example to 1 minute) you can run this code at Tampermonkey's background console:

```JavaScript
localStorage.setItem('webdav_poll_interval', 1 * 60 * 1000)
```
