### ISSUE TITLE
Search in editor is buggy when search for current highlighted keyword

### ISSUE THREAD

**Issue by Haocen** [Tampermonkey/tampermonkey#594]
## Expected Behavior

When pressing ctrl+F with a keyword highlighted, the keyword will be filled into search box and the `Aa(caps lock)` should remain unchanged. If I press `previous` or `next` it should not toggle itself on its own.

## Actual Behavior

When pressing ctrl+F with a keyword highlighted, the keyword will be filled into search box and the `Aa(caps lock)` would be **checked**. If I press `previous` or `next` it **will** toggle itself on its own.

## Specifications

Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Window 10

## Script

N/A

**Comment by raszpl** [comment]
I can confirm this particular quirk (toggling aA), but there is more weird going on when highlighting first and pressing ctrl+F versus ctrl+F and manually entering search word.

_highlighting then ctrl+F_ causes Next/Previous to work in seemingly random order and miss some found words. You can see all the words have been found and underlined/marked on the right margin, but Next/Previous ignores some positions completely skipping them over.

**Comment by derjanb** [comment]
Fixed at TM BETA 4.10.6106
