### ISSUE TITLE
A bug on multiple requires when no semicolon appear on the first script.

### ISSUE THREAD

**Issue by maple3142** [Tampermonkey/tampermonkey#595]
## Expected Behavior

No error.

## Actual Behavior

![image](https://user-images.githubusercontent.com/9370547/45265216-516e6800-b47a-11e8-8c2c-0806b27fe0c9.png)

An error was thrown because of the first script doesn't end with a semicolon.
It seems that Tampermonkey use string concat to evaluate external scripts.

## Specifications

- Chromium: 67.0.3396.99
- TM: 4.8.5847
- OS: Windows 10 x64 build 1803

## Script

```js
// ==UserScript==
// @name         Bug
// @match        https://example.com/
// @require      https://unpkg.com/xfetch-js@0.0.6/xfetch.js
// @require      https://unpkg.com/gmxhr-fetch@0.0.3/gmxhr-fetch.min.js
// @grant        none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Tampermonkey will not add separators between requires, because the code author has to be aware of potential issues especially if semicolons are omitted and the code is intended to be included by other scripts.

You can workaround the issue by requiring a script with a single semicolon. :) Reversing the ```@require``` statements might also work.

```JavaScript
// @require      https://unpkg.com/xfetch-js@0.0.6/xfetch.js
// @require      https://gist.githubusercontent.com/derjanb/2d241de9f54b79871ac00b31ad4d73e9/raw/262c57c88eb36785d496c85519f97f0b0d2df9a5/semicolon.js
// @require      https://unpkg.com/gmxhr-fetch@0.0.3/gmxhr-fetch.min.js
```

**Comment by maple3142** [comment]
I don't think it should be taken into consideration.
Because normal script loaders(script tag, node require,...) won't concat the script, semicolon should not affect how modules should be evaluated.
