### ISSUE TITLE
Page Issue even with empty script

### ISSUE THREAD

**Issue by engycz** [Tampermonkey/tampermonkey#596]
Page source [Bakalari.zip](https://github.com/Tampermonkey/tampermonkey/files/2371007/Bakalari.zip)

## Page OK without script
1) Open file `prubzna_.aspx.html` from archive, 
2) Click on the big black one
3) Window with details appears

## Page issue with script
1) Install script `Bakalari_script.user.js` from archive (empty script which does nothing)
2) Open file `prubzna_.aspx.html` from archive, 
3) Click on the big black one
4) Window will appear but without details

## Specifications

- Chrome / FF - latest 
- TM: 4.7.5788
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         Bakalari - prumery
// @version      1.2
// @author       engy@centrum.cz
// @license MIT
// @include      *prubzna.aspx*
// @grant        none
// @icon         https://image.prntscr.com/image/QpmNM_LxSfuaJL2vzUvczw.png
// ==/UserScript==
(function() {
})();
```

**Comment by engycz** [comment]
The issue still persist.

**Comment by derjanb** [comment]
This is working fine here. Any additional hints to reproduce the issue?

![image](https://user-images.githubusercontent.com/767504/58582184-79446c80-8251-11e9-873b-8f2d4858294e.png)

**Comment by engycz** [comment]
Really, it's fixed now.
