### ISSUE TITLE
Session Persist the "Disable update tab"

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#599]
## Expected Behavior
Re: #427 , #598

1. Change the "Show TM update notification" level from "Open the changelog" to either entry. 
2. Restart TM or the browser. 
3. Persist the setting between browser sessions and extension session

## Actual Behavior

Seems to forget this value in general between sessions. Usually I set it back to novice for some clients as well so it should persist there as well. e.g. it goes back to "Open the changelog". No automatic cleanup in test profiles.

## Specifications

- Chromium: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/66.0.3359.181 Safari/537.36 (64bit)
- Chrome: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36 (64bit)
- Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0 (64bit)

- TM: 4.7 (September 4, 2018) for Chromium based browsers; 4.8.5847 for Gecko browsers
- OS: Linux for sure... untested on Win and macOS atm but suspect it's there too since there are multiple browser issues.

## Script

n/a

Thanks for the relook.

**Comment by Martii** [comment]
n/m... little save button could be more prominent on changes detected. \*hint, hint\* ;) Don't use some features of TM a lot and missed that on my way out the door.

**Comment by derjanb** [comment]
Yes, I know it might be confusing, that some sections need a save, while others don't. Enabling the button on change detection only might help.
