### ISSUE TITLE
How to use website objects inside tampermonkey script?

### ISSUE THREAD

**Issue by ganduras** [Tampermonkey/tampermonkey#601]
Inside source of website I create object.
In my script I want to set another attributes , but my function doesn't see the method where i create object.

**Comment by tophf** [comment]
https://wiki.greasespot.net/UnsafeWindow
https://stackoverflow.com/questions/13485122/accessing-variables-from-greasemonkey-to-page-vice-versa

**Comment by ganduras** [comment]
Ok I get the object but now when I call object method, it not found it.
