### ISSUE TITLE
user script not work on some page

### ISSUE THREAD

**Issue by giveup** [Tampermonkey/tampermonkey#603]
## Expected Behavior
User script works fine

## Actual Behavior
user script not work,
The console log like this:

> Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
content.js:28

But it works fine on Chrome.

## Specifications

- Safari: (Version 11.1.2 (13605.3.8))
- TM: (4.8.5847)
- OS: (MacOS 10.13.6 (17G65))

## Script
https://greasyfork.org/scripts/16203/

```js
// ==UserScript==
// @name            谷歌翻译提示框扩展
// @description     谷歌翻译选中文本至提示框。Fork自https://greasyfork.org/scripts/662/
// @namespace       https://greasyfork.org/scripts/16203/
// @homepage        https://greasyfork.org/scripts/16203/
// @version         1.24
// @icon            http://translate.google.com/favicon.ico
// @include         *
// @grant           GM_getValue
// @grant           GM_xmlhttpRequest
// @grant           GM_log
// @grant           GM_deleteValue
// @grant           GM_addStyle
// @grant           GM_openInTab
// @grant           GM_registerMenuCommand
// @grant           GM_setValue
// ==/UserScript==
```

**Comment by derjanb** [comment]
#296 Sorry. 😔
