### ISSUE TITLE
In a specific GreasyFork script page, the "Install this script" button title doesn't change to "Reinstall version x.x.x" after script install

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#605]
Tested with both TM 4.8.5850 beta and TM 4.7/4.8.5847 stable in Chrome 69 and Firefox 62 (win 10).

The issue is that in this specific script page https://greasyfork.org/en/scripts/7664-faviconizegoogle
the `Install this script` button title doesn't change to `Reinstall version 1.4.2` after script install (and reloading the page).
![2018-09-28_022210](https://user-images.githubusercontent.com/723651/46179745-5c702780-c2c5-11e8-89ed-b1e6e61e36d4.jpg)

_It's the only GreasyFork script page I've noticed this._

**Comment by derjanb** [comment]
Fixed at the beta version...

Note: the fix only affects newly installed scripts.

**Comment by darkred** [comment]
Thank you for fixing this.
