### ISSUE TITLE
GoR BoTToL

### ISSUE THREAD

**Issue by nakigirl** [Tampermonkey/tampermonkey#608]
Is the issue with no-one being able to use the GoR BoTToL on FaceBook Ever going to be fixed? Has this got anything to do with the GDPR (General Data Protection Regulation). I miss the Bottol :-(

## Actual Behavior
TamperMonkey says bottol is enabled but no-one is able to see it on the game 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

GoR 3.8.1
// ==UserScript==
// @name           GoR BoTTols
// @version        3.8.1
// @namespace      Tiestoale
// @description    GoR BoTTols (Bot+Tools) for Glory Of Rome
// @copyright	   © Alessandro Bello (aka Tiestoale) - Games Power Team
// @include        *gloryofrome*/*gameChrome_src.php*
// @include		   *gloryofrome*/*iframeCanvas.php*
// @include		   *gloryofrome*
// @include 	   *facebook.com/4oh4.php
// @include		   *facebook.com/dialog/feed*
// @icon           http://gamespowerita.com/Tools/GoR/Plugins/Icon.jpg
// @resource       smileys http://gamespowerita.com/Tools/GoR/Plugins/smileys.js
// @grant       GM_getValue
// @grant		unsafeWindow
// @grant		GM_deleteValue
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_listValues
// @grant       GM_addStyle
// @grant       GM_xmlhttpRequest
// @grant       GM_log
// @grant		GM_getResourceText
// @grant 		GM_getMetadata
// @grant		GM_info
// ==/UserScript==

**Comment by derjanb** [comment]
Please contact the script author regarding this issue.
