### ISSUE TITLE
GM_xmlhttpRequest with Safari

### ISSUE THREAD

**Issue by csch0** [Tampermonkey/tampermonkey#610]
I have the problem that with a non cross domain request, GM_xmlhttpRequest does not work as expected in Safari. I am not sure if its connected to #241 

## Expected Behavior
That GM_xmlhttpRequest works same as xmlhttprequest

## Actual Behavior
GM_xmlhttpRequest works different, looks like 'Referer' is not filled at all, and I also cannot fill it manual. Is this a limitation of Safari? Its working on Firefox and Chrome.

## Specifications

- Safari: 11.1 (13605.1.33.1.2)
- OS: MacOS 10.13.4

**Comment by derjanb** [comment]
Yes, unfortunately Tampermonkey Safari can only rely on header modification that is directly supported by Safari.

**Comment by csch0** [comment]
But its working with GM_xmlhttpRequest as well as jquery.ajax on the same page.

**Comment by derjanb** [comment]
> But its working with **GM_xmlhttpRequest** as well as jquery.ajax on the same page.

You meant XmlHttpRequest, right?

GM_xhr is sent from the extensions background page, therefore it's a cross domain request even if the script that initiated it is on the same origin as the request destination.

**Comment by csch0** [comment]
Yes I was talking about XmlHttpRequest. Ok understood, makes sense then!

Thanks for the explanation.
