### ISSUE TITLE
Hope to support query and modify http only cookies.

### ISSUE THREAD

**Issue by monkeyWie** [Tampermonkey/tampermonkey#611]
`document.cookie` can't get http only cookie,but using chrome extension API can do.
The doc from:[https://developer.chrome.com/extensions/cookies](https://developer.chrome.com/extensions/cookies),other browsers should also have the same API, I think can add `@grant GM_cookie` API to query and modify cookies.
So what do you think?

**Comment by derjanb** [comment]
Duplicate of #465

**Comment by monkeyWie** [comment]
Thank for your reply, I saw this question,but there is no solution.
