### ISSUE TITLE
Tampermonkey on iOS

### ISSUE THREAD

**Issue by Ruko2010** [Tampermonkey/tampermonkey#612]
Is there a tiny chance that Tampermonkey will run on iOS Devices?

**Comment by derjanb** [comment]
Unfortunately not. Even if #558 is fixed, then is seems like iOS it not supported.

> Safari app extensions are available in macOS 10.12 and later, and in OS X 10.11.5 with Safari 10 installed.

https://developer.apple.com/documentation/safariservices/safari_app_extensions

**Comment by kfur** [comment]
@Ruko2010 you can use [https://itunes.apple.com/us/app/safari-snippets/id1126048257?mt=8](https://itunes.apple.com/us/app/safari-snippets/id1126048257) for injecting scripts manually

**Comment by sohcah** [comment]
This should be possible with iOS 15 🎉 
Can this be re-opened?
![Screenshot 2021-06-07 at 20 49 15](https://user-images.githubusercontent.com/51970078/121079269-d4f74800-c7d1-11eb-8256-4fd068f0026e.png)

**Comment by derjanb** [comment]
Duplicate of #1258
