### ISSUE TITLE
【Feature Request】run some script when we click it.

### ISSUE THREAD

**Issue by xialvjun** [Tampermonkey/tampermonkey#613]
current status:
we write scripts, tell it to run when it come across websites match its `match`. The whole process is automatically.

expected behavior:
we can add another script type. The scripts of that type will show it in tampermonkey‘s Popup menu when it come across websites match its `match`, but it will not run automatically. Then we can click it in tampermonkey‘s Popup menu, then it runs.

**Comment by derjanb** [comment]
Please check:
```JavaScript
// @run-at context-menu
```

https://tampermonkey.net/documentation.php#_run_at

and 

```JavaScript
GM_registerMenuCommand('Run my Script', function() {
   alert('it runs!');
})
```
https://tampermonkey.net/documentation.php#GM_registerMenuCommand
