### ISSUE TITLE
Five UI bars is gratuitous

### ISSUE THREAD

**Issue by FullMetalLion** [Tampermonkey/tampermonkey#615]
> "Every vertical pixel used for the UI bar signifies a theft from those who hunger and are not fed, those who are cold and are not clothed." 
>-- Fakey Fakerson

When editing a user script, I find I have five UI bars which permanently take up space at the top of the screen. Surely some of these could be made smaller, removed, combined, or overlaid.

![image](https://user-images.githubusercontent.com/8519679/48096341-8b3ebf00-e1dc-11e8-8076-c1297c8634fe.png)

**Comment by derjanb** [comment]
See #495
