### ISSUE TITLE
Unable to login on some sites with instant injection mode enabled on Firefox 52-58

### ISSUE THREAD

**Issue by lainverse** [Tampermonkey/tampermonkey#617]
## Expected Behavior
Can login on mediafire.com with Facebook just fine.
Can login on forum.ru-board.com with own profile.

## Actual Behavior
Unable to login with instant injection mode enabled. Tested Mediafire only with Facebook since didn't want to create a separate profile there, but as I understand it affects all login methods. Login on ru-board kinda works, but you end up logged in as a "Guest" user instead of your own.

## Specifications
- Firefox 52.0 ESR (also tested in 56 and reported that it's like this up to 58).
- TM 4.8.5847
- Windows 10

## Script
Not required.

**Comment by derjanb** [comment]
Obsolete... ;-)
