### ISSUE TITLE
Infinite Loading Screen On Roll20 (Better20-5etools)

### ISSUE THREAD

**Issue by Enricoboschin** [Tampermonkey/tampermonkey#618]
Infinite loading screen on roll20 after the latest update (yesterday night everything worked fine)

http://prntscr.com/lklblk

**Comment by otsassis** [comment]
Same problem here, the screen just doesn't open

**Comment by derjanb** [comment]
Seems to work fine here with this test script. 
Please add more details: Browser, OS, Tampermonkey version? 
Does it work with only this script enabled? Does it work with a temporary new profile?

```JavaScript
// ==UserScript==
// @name         Test Roll20
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://app.roll20.net/*
// @grant        none
// ==/UserScript==

console.log('Works!', document.location.href);
```
![image](https://user-images.githubusercontent.com/767504/48920789-3b7a1c00-ee9b-11e8-9e10-0e18ada70fc5.png)

**Comment by derjanb** [comment]
As I said, I can not reproduce this with my simple script. Can you please point me to a URL from where Better20-5etools can be downloaded?

**Comment by BraldheimWiltdorf** [comment]
Oh, ok. I found this script here https://5etools.com/
link to script: https://get.5e.tools/script/betteR20-5etools.user.js
Thanks for your time derjanb!

**Comment by derjanb** [comment]
This issue is not caused by the latest update. With TM 4.7 the page fails to load as well. The issue is caused by the script (or a change at the page).

In order to fix the issue simply make line 73 look this way:

```	if (typeof d20 !== "undefined" && d20.engine) {```

and the page will load. Since I don't looked at the whole script this just hides this error. I'm not sure if the script still works, but that's not my construction site. ;)

**Comment by BraldheimWiltdorf** [comment]
Thanks mate! We try this in our D&D play tommorow.

**Comment by BraldheimWiltdorf** [comment]
After test with GM and players, sadly, 90% of script functions doesn't work. :/
Still, thanks for your time

**Comment by DMsGuild201** [comment]
I'd suggest reading the script's wiki
