### ISSUE TITLE
Allow blocking urls

### ISSUE THREAD

**Issue by xicelord** [Tampermonkey/tampermonkey#622]
I'd like to request a feature that allows userscripts to block urls.
This would allow us to replace whole scripts of the webpage we try to modify.

Maybe use something like `// @block http://example.com/script.js` in the header?

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-299949037

**Comment by xicelord** [comment]
Wow, thank you!
