### ISSUE TITLE
GM_deleteValue function is not working

### ISSUE THREAD

**Issue by max-tian** [Tampermonkey/tampermonkey#623]
(Please fill out the issue template with your details)

## Expected Behavior
GM_deleteValue should work as design.

## Actual Behavior
GM_deleteValue is not working.

## Specifications
Use GM_deleteValue in any UserScript and refresh the page.

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
GM_setValue('test', true);
GM_deleteValue('test');

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
GM_setValue('test', true);
GM_deleteValue('test');
```

## Screenshots
![screen shot 2018-12-12 at 16 53 53](https://user-images.githubusercontent.com/4463267/49858302-839fb500-fe2f-11e8-9cca-4fc0a05b3b35.png)

**Comment by derjanb** [comment]
Please change

```Javascript
// @grant none
```
to
```Javascript
// @grant GM_setValue
// @grant GM_deleteValue
```

**Comment by max-tian** [comment]
> Please change
> 
> ```js
> // @grant none
> ```
> 
> to
> 
> ```js
> // @grant GM_setValue
> // @grant GM_deleteValue
> ```

Changed.
Please open this issue.

**Comment by derjanb** [comment]
```Javascript
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @include http://example.com/*
// @grant GM_setValue
// @grant GM_deleteValue
// ==/UserScript==
GM_setValue('test', true);
GM_deleteValue('test');
alert('all done');
```

is working fine at http://example.com. So what is the issue?

**Comment by max-tian** [comment]
> ```js
> // ==UserScript==
> // @name MyName
> // @namespace http://mywebsite.com
> // @Version 1.0
> // @description try to take over the world!
> // @author Me
> // @match http://mywebsite.com/*
> // @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
> // @include https://mywebsite.com/*
> // @include http://example.com/*
> // @grant GM_setValue
> // @grant GM_deleteValue
> // ==/UserScript==
> GM_setValue('test', true);
> GM_deleteValue('test');
> alert('all done');
> ```
> 
> is working fine at http://example.com. So what is the issue?

Sorry for the misunderstanding.
I updated the original post.

**Comment by derjanb** [comment]
``` Javascript
// @grame        GM_deleteValue
```

You wrote ```@grame``` instead of ``@grant``

**Comment by max-tian** [comment]
> ```js
> // @grame        GM_deleteValue
> ```
> 
> You wrote `@grame` instead of `@grant`

Sorry for the typo.
