### ISSUE TITLE
uBO filters interfering with TM Beta popup

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#626]
Chromium 70.0.3538.110
Tested in Canary as well.
TM Beta

Certain adblock filters are causing the badge counter to be removed, along with the list of active scripts in the popup. First noticed on the [userstyles forum](https://forum.userstyles.org/) where whitelisting this filter: `/analyticstick.` restores functionality. Just noticed again on Youtube, where unblocking doubleclick seems to do the trick. I'm using [Ultimate List](https://www.fanboy.co.nz/r/fanboy-ultimate.txt
), but I imagine the analytics filter is in anti-tracking and doubleclick should probably be in Easylist.

**Comment by DanaMW** [comment]
This is also happening to Firefox (65 0b4) the pop-down lists none the badge list 5 on a site i have 3 scripts running on, Disabling UBlock returns TM to correct listings.

**Comment by narcolepticinsomniac** [comment]
I think what they all may have in common is that they're XHR filters.

**Comment by derjanb** [comment]
@narcolepticinsomniac If I understand correctly, then uBO make Tampermonkey's popup menu look different? The popup is an extension page, uBO should not be able to influence in any way. 😳

**Comment by narcolepticinsomniac** [comment]
Nah, the filters are blocking communication with the popup somehow. I checked the release notes and you tweaked some XHR code, so I'm guessing it's that.

**Comment by derjanb** [comment]
Communication is done via [extension internal messaging](https://developer.chrome.com/extensions/messaging). It would be a major issue if other extensions could interfere this.

So you still see the scripts running at the page?

Unfortunately I can not reproduce this. I installed uBlock Origin, imported "Fanboy+Easylist-Merged Ultimate List" and tried at Youtube an other pages and the popup and the badge number are working fine. Is there something else to do to reproduce this?

**Comment by DanaMW** [comment]
runing scripts on a given page i have three running on discord the popdown says none but they still run. Disabling ublick and the popdown shows the three,

**Comment by narcolepticinsomniac** [comment]
IDK man, check [USO](https://forum.userstyles.org/) or Discord. Make sure your subscriptions are updated.

**Comment by DanaMW** [comment]
![2018-12-13 2](https://user-images.githubusercontent.com/12940577/49963564-2ce8b880-fecd-11e8-988b-a838698f4565.png)
![2018-12-13 3](https://user-images.githubusercontent.com/12940577/49963565-2eb27c00-fecd-11e8-993f-a29efe23f1bd.png)
letting you note that Ublock active then inactive.

**Comment by narcolepticinsomniac** [comment]
Oh, and it's not affecting script injection AFAICT, just communication between the page and popup.

**Comment by derjanb** [comment]
I've found the issue. uBO makes some requests fail and TM erroneously resets the tab information. 🤦
Will be fixed soon.

**Comment by eight04** [comment]
Is this fixed? I've encountered this issue on 4.8.5881 beta.

**Comment by derjanb** [comment]
🤦 4.8.5885 is on the way now! :)

**Comment by TrueXakeP** [comment]
This issue with popup appear at the site xnxx.com with a clean Firefox profile and TM Beta 4.8.5881 while with TM 4.8.5847 is not.
