### ISSUE TITLE
[Firefox] TM crashes when dealing with local externals

### ISSUE THREAD

**Issue by 0xCA** [Tampermonkey/tampermonkey#627]
## Expected Behavior
Userscripts are loading from disk and working.

## Actual Behavior
TM crashes on opening a tab with enabled local-hosted userscript.
It also crashes (with tab crash) when saving userscript after adding @require local path.

## Specifications

- Firefox 64.0
- TM: v4.8.5847
- OS: Windows 10 1809

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @require file:///d:\Dev\ujs\dev.user.js
// ==/UserScript==
```

**Comment by jonathanmcdougall** [comment]
[#347](https://github.com/Tampermonkey/tampermonkey/issues/347) seems to suggest this feature is broken on anything but Ubuntu right now. I was able to work around it by serving the scripts through a local web server, with something like `@require http://127.0.0.1/tampermonkey/script.js`.

**Comment by 0xCA** [comment]
> 
> 
> [#347](https://github.com/Tampermonkey/tampermonkey/issues/347) seems to suggest this feature is broken on anything but Ubuntu right now. I was able to work around it by serving the scripts through a local web server, with something like `@require http://127.0.0.1/tampermonkey/script.js`.

It was brilliantly working until 2 weeks ago. I guess the reason is some changes in FF 64.

**Comment by 0xCA** [comment]
Same on FF dev 65.0b12.
No issue on FF ESR 60.4.0, scripts are loading from disk instantly.

**Comment by derjanb** [comment]
Local file access is going to be disabled in general in FF.
