### ISSUE TITLE
[Chrome] JavaScript memory grows with each page refresh and eventually crashes.

### ISSUE THREAD

**Issue by alainbryden** [Tampermonkey/tampermonkey#628]
## Expected Behavior
Memory footprint remains fairly stable over the course of hours and days, even if running scripts frequently.

## Actual Behavior
Memory footprint (specifically JavaScript memory according to Chrome Task Manager) of the Extension: Tampermonkey grows unbounded. While reloading a page that was running a script frees some of the memory allocated, it does not free it all.

I've been having this problem since the 11-11 update. When I saw the recent changelog "Fix a memory leak when using GM_xmlhttpRequest which could lead to crashes", I thought for sure that was going to solve this issue, but I still wake up every 2 days or so to chrome having killed Tampermonkey and having to restart the browser.

Here's an image of the memory footprint after reloading the page with the TM script about 50 times, even though all tabs with TM scripts are now closed:
![image](https://user-images.githubusercontent.com/2285037/50157647-6001c200-02a8-11e9-8553-39b110d6e0b2.png)

## Specifications

- Chromium: 71.0.3578.98 (Official Build) (64-bit)
- TM: 4.7.54 (2018-12-16)
- OS: Windows 10 Pro x64 w/ 32 GB RAM

-----

## Script

The script I have that suffers from this issue is ~1500 lines, so I'll try to summarize. It involves:
- reloading the current page every 5 minutes,
- loading data from session storage
- sometimes loading some other pages in the background (using `GM.xmlHttpRequest`) and collecting new info to add to session storage
- modifying the current page
- sometimes submitting forms automatically
- running several timers (setInterval) to count down until the next page reload

The expectation is that when the page is reloaded, the memory slate is wiped clean (except perhaps the session store), but I'm finding that even closing the tab keeps some memory alive. Only restarting the browser frees it.

I'll extract a few bits that may be relevant (happy to share the whole thing if desired). Unfortunately it only runs on a site you need to sign up for. I'm anonymizing the name of the target site to "giveaways.com" in the pasted code but you could guess the actual site if you wanted to.

```javascript
// ==UserScript==
// @name        Giveaways
// @include     *.giveaways.com/
// @include     *store.steampowered.com/agecheck/*
// @include     *store.steampowered.com/*/agecheck
// @version     7.5
// @grant       GM.xmlHttpRequest
// ==/UserScript==
// modified    12/05/2018

var DISABLE_ERROR_HANDLING = false;
var showTextArea = false;

(function() {
    //Mini script for doing steam age checks automatically (used when scraping steam sites)
    if (/agecheck/i.test (location.pathname) ) {
        console.log('Age Check Required.');
        var ageForm = document.querySelector ("#agegate_box form");
        if (ageForm !== null)
        {
            ageForm.querySelector ("[name='ageDay']").value = 18;
            ageForm.querySelector ("[name='ageMonth']").value = 'August';
            ageForm.querySelector ("[name='ageYear']").value = 1987;
            var newFrame = document.createElement('frame');
            newFrame.name = "PostResult";
            document.body.appendChild(newFrame);
            ageForm.target = newFrame.name;
            ageForm.submit();
        }
        else
        {
            var btnContinue = document.querySelector ("#app_agegate .btn_medium:nth-of-type(1)");
            btnContinue.innerHTML = "<span>Continuing...</span>";
            btnContinue.click();
        }
        setTimeout( function(){ window.close(); }, 30000);
        console.log('Performed Age Check.');
    }
    else //Otherwise, we're on giveaways!
    {
     ... // 1400 more lines of code
```

One thing I do that holds onto memory intentionally is to cache page scrape data in sessionStorage:
```javascript
            //Since many of the same games appear in giveaways, we can cache the steam info for that which has already been requested.
            var SteamRequestCache = {};
            // Restore session-persisted cache
            var sessionStore = sessionStorage.getItem("steam_cache");
            if (sessionStore) {
                //console.log(sessionStorage.getItem("steam_cache"));
                SteamRequestCache = JSON.parse(sessionStore);
                //console.log(SteamRequestCache);
                console.log('Restored cache of steam information (' + Object.keys(SteamRequestCache).length + ' games)');
            }
```
But I've tested this between page reloads (`sessionStorage.getItem("steam_cache").length`) and it remains steady (at 131,336 cache entries) while memory continues to grow.

Other than that, my script basically identifies a game on "giveaways", loads the corresponding steam page in the background using `GM.xmlHttpRequest`, scrapes the page for additional information about the game, and then creates a bunch of new DOM elements and css on the "giveaways" page with the additional information from steam. If it finds a good game, it will auto-register for it by creating an iFrame on the main page and navigating to the giveaway, then entering it:

```javascript
            var myIFrame = document.createElement('iframe');
            myIFrame.setAttribute('id', 'Entry' + asyncRequests);
            document.body.insertBefore(myIFrame, document.getElementsByClassName('page__outer-wrap')[0]);
            myIFrame.width = '100%';
            myIFrame.addEventListener("load", function() { toRunOnLoad(myIFrame.contentWindow.document); });
            myIFrame.src = giveaway.url;

        var toRunOnLoad = function(e){
            console.log('Registration frame loaded for ' + giveaway.title);
            registerGiveawayPage(e);
            asyncRequests --;
            registrations ++;
            console.log('Registered for ' + giveaway.title);
        };

       function registerGiveawayPage(document)
       {
            //Check to see this giveaway is still enterable (in case of a multiple instances conflict)
            var enterButton = document.querySelector(".sidebar__entry-insert");
            if( !enterButton.classList.contains('is-hidden') ) { 
               enterButton.click();
            } else {
                console.log('Was already registered for ' + document.location);
            }
       }
```

Once it's done its thing, it reloads the page every 5 minutes to get a fresh list of giveaways:

```
    function refreshWhenReady()
    {
        var modifiedRefreshTime = RefreshTime + (registrations > 0 ? RegistrationTime : 0);
        //Show how long we've been waiting
        getOrCreateCustomElement('RefreshTime', headerInsertionPoint).innerHTML =
            'Refreshing in T-' + ((modifiedRefreshTime - pollingAttempts * pollingInterval ) / 1000) + ' Seconds.';

        if( pollingAttempts >= modifiedRefreshTime / pollingInterval )
        {
            window.clearInterval(polling);
            window.location = 'http://www.giveaways.com';

            //In case we have trouble connecting, retry every 15 seconds:
            pollingAttempts = 0;
            polling = setInterval(keeptryingToRefresh, pollingInterval);
        }
        else
            pollingAttempts += 1;
    }

    function keeptryingToRefresh()
    {
        updateAsyncRequestsStatus();
        pollingAttempts += 1;
        if(pollingAttempts % (RefreshTime / pollingInterval) === 0)
        {
            // try to kick off a fresh request.
            window.location = 'http://www.giveaways.com';
        }
        //Show how long we've been trying to refresh
        getOrCreateCustomElement('RefreshTime', headerInsertionPoint).innerHTML =
            'Reloading for ' + ((pollingAttempts * pollingInterval) / 1000) + ' seconds.';
    }
```
That's about it. The rest is mostly parsing json, computing "scores", and building DOM. I'm happy to share the full script if necessary, but as I said, you may not be able to run it without registering accounts on steam and on the giveaways site.

**Comment by derjanb** [comment]
> TM: 4.7.54 (2018-12-16)
>  I thought for sure that was going to solve this issue, but I still wake up every 2 days or so to chrome having killed Tampermonkey and having to restart the browser.

Just to be 100% sure, you are using 4.7.**5**4 and not 4.7.**4**4 and you're still seeing crashes, right? I'm asking because 4.7.54 was released 43 hours ago and there are not too many 2 days within this timeframe. ;)

**Comment by alainbryden** [comment]
I can confirm I have the latest (4.7.54). 

Sorry the "every 2 days or so" had been established in my mind in the weeks leading up to the update. After updating, I got another crash after about 36 hours, so I immediately assumed that the pattern hadn't changed. I can confirm that in the days following this report, it has continued to crash/get killed.

I also have some other potentially useful info - I also installed Tampermonkey for Firefox (which appears to be at version 4.8.5847 2018-09-05) and the same page/auto-reloading script has been running about a week on there without issues. `about:memory` appears to show the process associated with extensions as holding on to ~28 GiB (most of which appears as `heap-unclassified`, ~3.5GiB explicitly linked to Tampermonkey). I wonder if the problem is equally bad in both versions, but Chrome is just more aggressive at terminating extensions when their RAM usage creeps up?

![image](https://user-images.githubusercontent.com/2285037/50401188-f92a5000-0762-11e9-9572-e28ecceffca1.png)

Sadly, I don't know enough about browsers or javascript to have any ideas of how to troubleshoot or profile what's sitting in the heap. If you have any tips or suggestions, I'm happy to do some legwork.

**Comment by alainbryden** [comment]
It's been running in chrome for ~2 days now since my last restart. The extension hasn't been killed, and the memory footprint remains quite low. I haven't seen the version number increase, but I did see the webstore updated on the 24th. If you changed anything, it appears to be working.

In Firefox, the add-ons process was sitting at around 4000 MB RAM this morning. I repeated the "disable add-ons" experiment in the add-ons manager to see what was holding on to the RAM.
- Disabled Tampermonkey first and it dropped to 900 MB (~3100 MB held)
- Disabling 8 other extensions (waiting 10 seconds after each) only took it down to 870 MB.
- Finally, disabling 'LastPass' took it down to 418 MB (~450 MB held),
- Performing a 'Minimize memory usage' operation in `about:memory` once all were disabled left the process with 96 MB. (Next time I run this experiment, I'll do this action first, and then again after each add-in is disabled.)

**Comment by alainbryden** [comment]
Alright, 2 days later, Chrome is still running the add-on great.

In Firefox, I'm at 4672 MB add-on memory. I kicked it off with a 'minimize memory usage' but it had no effect on its own. My plan is to disable every add-in except two - Tampermonkey and some other well-known one, just in case memory dropping is actually linked to removal of the first or last add-on.
- After disabling all other add-ons except Tampermonkey and uBlock, calling 'Minimize memory usage', and waiting a while, add-on process is still carrying 4,666 MB.
- After disabling Tampermonkey, this dropped over the next few seconds to 1063 MB. Calling 'Minimize memory usage' caused it to drop a little more, to 670 MB, where it sat a few minutes.
- Finally, I disable the last add-on (uBlock) and this took us to 623 MB.

I know this doesn't help you figure out what's going on, but hopefully it helps reassure that the memory does appear to be held onto by Tampermonkey. I had my doubts when I found the other add-on with even bigger problems affecting my install (which I've since found a replacement for) - but given Firefox's lack of a per-add-on tracker, this seems like a pretty clear link between memory usage and Tampermonkey.

Good luck tracking down the issue! Hopefully it's no worse than the one with the Chrome release that appears to now be solved.

**Comment by sadransh** [comment]
I have the same issue... With firefox 73 and 83 ... Tamermonkey 4.11.6120

**Comment by Quadrum1** [comment]
I am having the same issue on Firefox.
It has been more than 3 years since this was reported first, has there been any work towards it at all?

**Comment by mok419** [comment]
Can confirm this is present today on latest chrome (v121.0.6167.184) , hovering tab on refresh shows memory increase for tab.

Also observing performance monitor can see heap memory rise on every refresh. (all js scripts are cached in memory or disk, so why would refreshing increase memory usage?) 

Test on youtube in incognito and see for yourself!
