### ISSUE TITLE
Anti-Adblock killer reek fails

### ISSUE THREAD

**Issue by kesarling** [Tampermonkey/tampermonkey#630]
(Please fill out the issue template with your details)

## Expected Behavior
Should "fool" site into believing that no ad-blocking is enabled

## Actual Behavior
crashes on some sites 
eg- xmovies8.im (Exclusively makes you disable ad-block to watch a movie)

## Specifications
-Latest Chrome browser
-OS: Windows 10 Home Single Edition
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
anti-adblock killer reek
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please try ["Instant" injection mode](https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595). If this is not working, please contact the script author.
