### ISSUE TITLE
Vivaldi not showing "access to local files" option

### ISSUE THREAD

**Issue by brasofilo** [Tampermonkey/tampermonkey#636]
I was about to try the local files feature but it's not showing up on Vivaldi (v2.2.1388.37). The option shows ok on Chrome (v71.0.3578.98) and Opera (v57.0.3098.106). 
I'm on OS X 10.11.6
I'm facing the issue with TM 4.8.5890 and 4.7.63

I tried looking for relevant Vivaldi settings that could block the feature but didn't find anything related. Inspecting the extension page shows a message *"Try to load layout default"* so I tried to change TM layout to `default-dark` but settings keep the same.

> ![screenshot of settings page](https://i.stack.imgur.com/7uXBz.jpg)

Not sure if this would this be better reported at Vivaldi forums... (?)

**Comment by derjanb** [comment]
And you have granted file access to Tampermonkey at Vivaldi's extension settings page?

![image](https://user-images.githubusercontent.com/767504/50902968-b9c75900-141c-11e9-913f-9278ca4501d8.png)

**Comment by brasofilo** [comment]
Whoopsie, that was it... thanks for the help @derjanb !

**Comment by derjanb** [comment]
You're welcome.
