### ISSUE TITLE
How to help improve translation?

### ISSUE THREAD

**Issue by PeterDaveHello** [Tampermonkey/tampermonkey#638]
I'll like to help improve zh_TW translation, may I directly send to pull request here? Thanks!

**Comment by derjanb** [comment]
Of course, that'd be nice. Thanks.

**Comment by derjanb** [comment]
Ah, wait. Please file the pull request at this repo: https://github.com/Tampermonkey/tampermonkey-i18n
Thanks.

**Comment by PeterDaveHello** [comment]
Cool, thanks.

**Comment by PeterDaveHello** [comment]
PR sent here: https://github.com/Tampermonkey/tampermonkey-i18n/pull/108
