### ISSUE TITLE
GM_download's name

### ISSUE THREAD

**Issue by fghhfg** [Tampermonkey/tampermonkey#643]
```
GM_download(details)

details can have the following attributes:
url  -
name - the filename - for security reasons the file extension needs to be whitelisted at Tampermonkey's options page
...
onload callback to be executed if this download finished
...
```

  https://tampermonkey.net/documentation.php?ext=dhdg#GM_download

where is the options page? 
How to whitelist the file extension?

---

and I feel that onload's describe is wrong.
should be
callback to be executed if this download is triggered

that's why my download is not ordered.

**Comment by shikiyoku** [comment]
It's in `Downloads BETA` section on Settings tab

**Comment by derjanb** [comment]
Please set "Config Mode" to "Advanced" and search for it.
