### ISSUE TITLE
Crazy !!

### ISSUE THREAD

**Issue by StellarisStudio** [Tampermonkey/tampermonkey#645]
Some script have crazy behavior !! Like for example, script work but doesn't appear on the icon or in the list, and if I deactivate it it still work,  even after uninstall tampermonkey, some script are still working ??!!!! (example with that script : https://greasyfork.org/en/scripts/21820-mal2kissanime)

And To have couple of highlight theme is nice, but why change the background aswell ???? I want Monokai but on black background, not that ugly greenish shit !!!

**Comment by derjanb** [comment]
Do you have more than one script manager installed? For example Tampermonkey and Tampermonkey BETA? Or maybe the extension version of some scripts? 

After an extension is uninstalled and the tab is reloaded there is no way how scripts could be injected into the tab's page.

Regarding all script-specific questions please contact the script developer.
