### ISSUE TITLE
Tampermonkey pegging cpu and making browser unresponsive

### ISSUE THREAD

**Issue by ozzy92** [Tampermonkey/tampermonkey#647]
## Actual Behavior

Tempermonkey pegs the cpu in the browser  task list and task manager.
Think I figured it out... GM_listValues()/GM_deleteValue() doesn't seem to be persisting
I've turned off all other add-ins.

## Specifications

Using Chrome 72.0.3626.81
Tampermonkey 4.7.63
Windows 10 Pro

## Script

This snip is reporting 4000+ keys.... 
even after running multiple times, doesn't seem to persist and kill the browser, rinse repeat.
I have no idea how it has so many keys or where they are coming from; new computer and I haven't used this script before!

            var keys = GM_listValues();

            for (var i=keys.length - 1; i >= 0; i --) {
                GM_deleteValue(keys[i]);
            }
            alert('Cleared');

**Comment by ozzy92** [comment]
I think once I let it spin for several minutes it's finally cleared up.... always figure it out just after posting for help!

**Comment by tophf** [comment]
FWIW you can inspect and clear the script's storage in Tampermonkey dashboard editor manually:

![image](https://user-images.githubusercontent.com/1310400/52904332-83f76a80-323b-11e9-9edb-447d4a8347d2.png)
