### ISSUE TITLE
Incognito mode doesn't run the script

### ISSUE THREAD

**Issue by farzadmf** [Tampermonkey/tampermonkey#648]
## Expected Behavior
I need to be able to create a script once and use it everywhere

## Actual Behavior
A script created in "normal" mode isn't picked up by incognito mode.

I go to a Website, and then click "Create new script..." in TM's menu, and I fill out my script and save. If I referesh my tab, TM shows that 1 script is running.

I open a new incognito session and go to the exact same URL, but TM says "no script is running". I need to choose "Create new script ..." from TM's window (this time in incognito mode), and copy/paste what I had in my original script so that the script is picked up by TM.

Of course every time I close my incognito session and open a new one, I have to repeat the same steps!

## Specifications

- Chromium: 72.0.3626.96 (Official Build) (64-bit)
- TM: 4.8
- OS: Windows 10 x64

**Comment by derjanb** [comment]
This is working fine here. The only way to make TM behave like this it to reconfigure the used storage type. (Which is not officially supported, btw. ;))

Please check at TM's background page the output of this command:

```JavaScript
var used_storage = localStorage.getItem('#storage');
console.log("Used Storage:", used_storage);
```

In case it logs something else than ```null``` or ```chromeStorage``` then please migrate to ```chromeStorage```:

```JavaScript
var Storage = Registry.get('storage');
Storage.migrate(used_storage, 'chromeStorage');
localStorage.removeItem('#storage');
```

**Comment by farzadmf** [comment]
Thank you @derjanb for your reply, I tried that, and it's printing `null`, so I think it should be fine.

But anyway, maybe it had something to do with "matching" the URL; I changed the `@match` from the exact URL to use `*` for some parts, and it seems to be picking up the Website now.

I'm going to close this, and if you don't mind, re-open in case I think it's not working as expected.

**Comment by derjanb** [comment]
If you're using "Browser Sync" then you can only sync between different Chrome/Chromium browsers and you have to sign in (at the upper right of your browser windows) at every browser with your Google account. You can also sync to Google Drive, Dropbox or OwnCloud for example.

**Comment by farzadmf** [comment]
Thank you @derjanb for your help
