### ISSUE TITLE
Report a bug doesn't take you here

### ISSUE THREAD

**Issue by trlkly** [Tampermonkey/tampermonkey#649]
## Expected Behavior
Report a bug should send me to Github Issues

## Actual Behavior
Report a bug takes me to a notification that the forum is temporarily offline. 

## Specifications

- Chromium: 72
- TM: 4.8
- OS: Win7 SP1

## Additional info
Would likely only involve fixing the https://tampermonkey.net/bug redirect to point to the right place.

**Comment by derjanb** [comment]
Fixed.
