### ISSUE TITLE
tapas.io blocks Tampermonkey somehow

### ISSUE THREAD

**Issue by trlkly** [Tampermonkey/tampermonkey#650]
(Please fill out the issue template with your details)

## Expected Behavior
Got to tapas.io, and userscript will work. 

## Actual Behavior
A "Hello World" uncaught exception is thrown, followed by several syntax errors on perfectly fine scripts, and none of the scripts actually work. 

## Specifications

- Chromium: 72.0.3626.96
- TM: 4.8
- OS: Windows 7 SP1 all updates

**Comment by trlkly** [comment]
Tested on beta, and works fine. 

I'm curious: can you give me a little bit of info on what the issue was? Something to do with try/catch?

Or was the site actually trying to mess up Tampermonkey?

**Comment by derjanb** [comment]
> Or was the site actually trying to mess up Tampermonkey?

I don't think so.
