### ISSUE TITLE
the "headers" in the "GM_xmlhttpRequest" method don't work

### ISSUE THREAD

**Issue by barrer** [Tampermonkey/tampermonkey#651]
## Expected Behavior
Send a cookie to the server.

## Actual Behavior
The cookie becomes base64 encrypted and is placed behind the tm*** in the header.

## Specifications

- Google Chrome 72.0.3626.109
- Tampermonkey 4.7.54
- Windows 10 x64

## Script
https://github.com/barrer/tampermonkey-script/blob/master/translate/translate-dictionary.js

Install and run it

**Comment by derjanb** [comment]
Fixed at TM 4.8. :) https://tampermonkey.net/changelog.php?version=4.8&ext=dhdg
