### ISSUE TITLE
All rules "striken out" and disabled after Mac OS Update: need to restore prior state of TamperMonkey scripts

### ISSUE THREAD

**Issue by dmland** [Tampermonkey/tampermonkey#652]
(Please fill out the issue template with your details)

## Expected Behavior:

Scripts that I've been using for several years continue to work.

## Actual Behavior:

ALL of my scripts have been disabled and I now have no way of knowing which of my 150 scripts were enabled and which were disabled before they were all unconditionally disabled.

Disabled scripts have the following title attribute:

>Warning: The origin of this script can't be determined.
Either it was installed by a malicious third party to steal you private data or some basic browser settings, your operation system or hardware has changed!
Please open, review and save the script to enable it.

**Note:** recently was "forced" to update my operating system. How am I supposed to know which scripts were enabled prior to the upgrade so I can restore the state of my carefully-curated collection of scripts?

## Specifications

- Google Chrome 72.0.3626.109
- TM: v4.9.5914
- OS: Mac OS 10.14.3 (18D109)

## Script:

Not Applicable – All of my scripts are disabled.

**Comment by dmland** [comment]
Follow-up: I notice that some of the script titles are Gray (and striken through) and some are black (and stricken through). I assume that this is an indication that they were either disabled or enabled prior to the upgrade.

Still, without laboriously opening and re-saving all 150 scripts (which will take hours of wasted time), Is there any way to tell Tampermonkey to trust the scripts I have installed and restore their prior active/inactive states?

**Comment by dmland** [comment]
It's been 2 weeks, and I've had to give up on preserving the "last time updated". I got no response here (I understand: it's a volunteer effort), so I'm giving up on getting one.

**Comment by derjanb** [comment]
Sorry for the delay. You can restore the previous state by running this at the [extension's background page console](https://tampermonkey.net/faq.php#Q600):

```JavaScript
scbr.getUidList().forEach(function(uid) {
    var s = scbr.getByUid(uid);
    s.script.evilness = 0;
    scma.doModify(uid, s.script, false);
});
```

**Comment by dmland** [comment]
What a beautiful thing this is! Thank you so much for saving me a LOT of time.
