### ISSUE TITLE
storage automatically stringify value ???

### ISSUE THREAD

**Issue by zeus81** [Tampermonkey/tampermonkey#653]
I have a very weird behavior of the storage on firefox.
This is my script : https://greasyfork.org/fr/scripts/17913-lazy-embedded-video
It replaces embedded videos by clickable images and there is some settings that can be saved.
The problematic part is :
    window.addEventListener("message", async function(e) {
            ...
            settings = JSON.parse(await getValue("zeusLEV", '[false,true,[]]'));
            ... update values ...
            setValue("zeusLEV", JSON.stringify(settings));
            ...
    });
After the first call the value is saved as if it was stringified twice, on the second call settings becomes a string instead of an object and everything is broken.
I've tried using GM.get/setValue, GM_get/setValue, localStorage.get/setItem, they all behave like that with this particular script on firefox.
Chrome + tampermonkey = no bug
Firefox + greasemonkey = no bug
Firefox + jsfiddle = no bug
So I think the bug is from the firefox version of tampermonkey, however I couldn't reproduce it in a smaller subset of code, it's weird.
I can easily fix it with a loop like : while(typeof(settings) == "string") settings = JSON.parse(settings);
but it won't change that there is something going wrong.

**Comment by derjanb** [comment]
> I've tried using GM.get/setValue, GM_get/setValue, localStorage.get/setItem, they all behave like that with this particular script on firefox.

I can not reproduce this. However, if even `localStorage` behaves like this, then this clearly either is a Firefox or a script bug. :)
