### ISSUE TITLE
Changes made in Incognito don't stick, option for this is gone (Chrome)

### ISSUE THREAD

**Issue by stealsfromhobos** [Tampermonkey/tampermonkey#656]
## Expected Behavior
Making changes to a script (editing/deleting) within an incognito session would be retained so long as the advanced security option "Store data in incognito mode" is set to "Permanent"

## Actual Behavior
While in Incognito, editing/deleting a script, or changing options within a script revert to their previous state when I close the incognito window.  Deleted scripts come back as well.  They are only retained if done in a normal window.  The option to allow this is gone, even when config is set to advanced mode.

Normally I could just make these changes in a normal session but it affects some scripts I like to use in incognito.  For example the thread watcher feature in 4chanX doesn't function properly because of this.

## Specifications

- Chrome:  72.0.3626.119 (Official Build) (64-bit)
- TM: 4.8
- OS: Windows 10 Pro version 1809 build 17763.316

**Comment by flrngel** [comment]
I'm having same issue, does this comes from only latest version?

**Comment by stealsfromhobos** [comment]
For now the only solution is to switch to a different script manager.  Violentmonkey seems to not have this issue.

**Comment by SkyNinja** [comment]
I'm wondering if this might be a case of trying to increase security the Microsoft way, i.e. stripping away any features that could potentially be dangerous.
Maybe the feature will be re-implemented on a per-script basis or something.

**Comment by filbo** [comment]
This is an old issue, but I am now having the same issue.  Some quick googling did not show me a changelog or anything, indicating that the checkbox '[ ] Store data in incognito mode' was abolished.  But it seems to be gone.

I'm using TM 5.3.6222 in Opera 131.0.5868.0.  When I open TM dashboard in incognito, there is a banner line at the top reading 'All modifications are only kept until this incognito session is closed!'.  It is not entirely obvious that this refers to **both** TM settings changes **and** any changes attempted to be saved by TM scripts; but, by behavior, that is what it means.

Is there a technical barrier or is this meant to be a safety feature?

I do have script settings (i.e. saved data of a userscript) which I would like to persist across incognito sessions.
