### ISSUE TITLE
script doesn't run

### ISSUE THREAD

**Issue by emp2687** [Tampermonkey/tampermonkey#658]
Page visited: https://www.youtube.com/watch?v=2m04j8rRkHw
Script does not run on the original load.
However, it runs if the page is refreshed.
Also appears to work everywhere else, only time it has problems is on youtube pages.

## Expected Behavior
Script should run

## Actual Behavior
Script does not run on the original load.
However, it runs if the page is refreshed.

## Specifications
TM: 4.8
Chrome: 72.0.3626.119
Page visited: https://www.youtube.com/watch?v=2m04j8rRkHw

## Script
// ==UserScript==
// @name        HERE
// @version     1.0
// @namespace   Global
// @include     *
// @grant       GM_log
// ==/UserScript==

console.log("HERE");

**Comment by derjanb** [comment]
Please see #200 and #488
