### ISSUE TITLE
Tampermonkey throws error 401 in safari but works well in chrome and firefox

### ISSUE THREAD

**Issue by pankajnarola1995** [Tampermonkey/tampermonkey#660]
I have a problem with safari browser.

The code works very fine in crome and firefox box in safari it gives this error...

I do have the login in my safari browser for the APIs(in this case youtrack login).
when I did the log out, it threw the below error in chrome and firefox browser but The same doesn't happens into safari if I do login/logout any.

I don't understand why? I tried to google it but not found answer.. so could you please tell me where I'm wrong? or what I'm missing? I don't use any headers with api call so what should I check?
and the same API Url if I run directly into safari browser then it returns the value what I expect.. 🤔

## Expected Behavior
Response data

## Actual Behavior
Error 401

## Specifications

- Safari(Version 12.0.3 (13606.4.5.3.1))
- TM:( 4.8.5847)
- OS: (MacOS )

## Script

(Please give an example of the script if applicable.)

```js
// @grant        GM_xmlhttpRequest

GM_xmlhttpRequest({
            method: 'GET',
            url: url,
            responseType: 'json',
            onload: function (responseCurrentUser) {
            console.log(responseCurrentUser)
 })
```
the Error 
```

response: Object

error: "Unauthorized"

error_description: ""

Object Prototype

responseHeaders: "access-control-expose-headers: Location
↵cache-control: no-cache, no-store, no-transform, must-revalidate
↵content-encoding: UTF-8…"

responseText: 

responseType: "json"

responseXML: 

status: 401

statusText: ""
```

**Comment by derjanb** [comment]
Please re-open if this issue still happens and #786 is not the root cause.
