### ISSUE TITLE
Installing TM on a 2nd machine

### ISSUE THREAD

**Issue by Octopod2** [Tampermonkey/tampermonkey#664]
I have Chrome 68 in this computer.   I've installed Win 7 and Chrome 68 on my other machine.   I know Chrome profiles, unlike Firefox profiles, can't just be copied from one machine to the other.

I've installed Tampermonkey on the other machine. What would be the easiest way to copy 16 Tampermonkey scripts from this computer to the other? Must I download and configure each one again?

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
You can manually import and export your scripts or use an automatic script sync via DropBox, Google Drive or a WebDAV server (like [TamperDAV](https://github.com/Tampermonkey/tamperdav), OwnCloud or NextCloud.
