### ISSUE TITLE
已安装脚本自动关闭且无法打开

### ISSUE THREAD

**Issue by niege92** [Tampermonkey/tampermonkey#666]
(Please fill out the issue template with your details)

## Expected Behavior
已安装脚本在开机时自动打开

## Actual Behavior
已安装的所有脚本，在第二次打开电脑时，都处于关闭状态且无法打开

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
"Duplicate" of #672
