### ISSUE TITLE
`Script install` ERR_UNSAFE_REDIRECT 

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#667]
Behavior changed when click on `Install this script` button or `*.user.js` links.

## Expected Behavior
1. TM scipt install dialog opens in new tab

## Actual Behavior
1. TM scipt install dialog opens in new tab
1. GF tab has error `ERR_UNSAFE_REDIRECT` and message `This site can’t be reached`.
1. Browser starts to download `*.user.js`

## Specifications

- Chromium: 73.0.3683.75 (64-bit) 
- TM: 4.9.5921
- OS: Windows 10 v1607 x64

## Script
Anyone, e.g. https://greasyfork.org/en/scripts/2312 or https://github.com/ParticleCore/Particle/wiki/Download

**Comment by fireattack** [comment]
This is not limited to greasyfork, I found the same thing when installing from GitHub. 

I have a feeling it would be the case for all the sites?

Thankfully you can still install the scripts just fine, but it's quite annoying indeed.

**Comment by Cyberavater** [comment]
I'm having the same Issue here.

**Comment by wuhuihong** [comment]
i got the same question.

**Comment by mikhaelkh** [comment]
https://github.com/violentmonkey/violentmonkey/issues/537 - similar issue in Violentmonkey

**Comment by derjanb** [comment]
Fixed in Chrome 74 and will be fixed at the next Chrome 73 release [1] as well.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=941653

**Comment by Martii** [comment]
Thanks.

**Comment by Martii** [comment]
Interesting... claims it didn't install from OUJS but when browser restarted... it is installed. :roll_eyes:

**Comment by derjanb** [comment]
Fixed in 73.0.3683.103 
https://chromereleases.googleblog.com/2019/04/stable-channel-update-for-desktop.html

**Comment by Martii** [comment]
**Chromium** is sure taking it's sweet time getting to that version in the Ubuntu line.
