### ISSUE TITLE
[Firefox] Lost userscripts/settings, how to import storage.js.

### ISSUE THREAD

**Issue by ntswitch** [Tampermonkey/tampermonkey#668]
Tampermonkey lost my userscripts and its settings rolled back to default after running firefox. However, after a bit of googling I found out that firefox saves the userscripts on the storage.js of the browser extension (\Profiles\[profile name]\browser-extension-data\firefox@tampermonkey.net), though whenever I try to import it nothing seems to happen, is there any chance that I can still recover my userscripts and its settings? Thank you.

## Expected Behavior
Userscripts loaded

## Actual Behavior
Lost userscripts and settings, tampermonkey rolled back to default.

## Specifications

- Firefox 66.0
- TM: 4.8.5847
- OS: Windows 10

**Comment by derjanb** [comment]
How exactly are you trying to import the scripts?

**Comment by ntswitch** [comment]
I'm probably doing it wrong but via the dashboard utilities tab.

**Comment by ntswitch** [comment]
I tried but nothing happens.
