### ISSUE TITLE
Edge closes when checking for updated scripts

### ISSUE THREAD

**Issue by slear** [Tampermonkey/tampermonkey#669]
## Expected Behavior
I am trying to check if new userscripts versions are available using the "Check for userscript updates" menu. Expecting to resume work when no updates are present

## Actual Behavior
Edge shows the blue bar at the top informing that TM has started to check for updates. Then Edge closes, no error message at all.

## Specifications
Windows 10 1809
Edge 
TM 4.8.5847 - 2018-09-05

## Script
This is the list of the scripts installed: (all StackOverflow Close Vote Reviewers Chat related)

**Autoreview Comments** => 
https://github.com/Benjol/SE-AutoReviewComments/raw/master/dist/autoreviewcomments.user.js

**Roomba Forecaster** => 
https://github.com/makyen/StackExchange-userscripts/raw/master/Roomba-Forecaster/RoombaForecaster.user.js

**Stack Exchange CV Request Generator** => 
https://github.com/SO-Close-Vote-Reviewers/UserScripts/blob/master/SECloseVoteRequestGenerator.user.js

**Unclosed Request Review Script** => 
https://github.com/SO-Close-Vote-Reviewers/UserScripts/raw/master/UnclosedRequestReview.user.js

**Comment by RaptorCZ** [comment]
The same problem. Forcing update using menu crashes Edge. Regular update works fine.

**Comment by derjanb** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20146233/

**Comment by derjanb** [comment]
Will be fixed once Chromium-based MS Edge will be released net month.
