### ISSUE TITLE
 tampermonkey-已安装脚本-（拖动）排序，浏览器就开始假死卡住。

### ISSUE THREAD

**Issue by oicqbak** [Tampermonkey/tampermonkey#670]
tampermonkey-已安装脚本-（拖动）排序，浏览器就开始假死卡住。

 tampermonkey-Installed script - (drag) sort，The browser started to freeze.

## Specifications

- Chromium: Cent Browser
版本 3.9.2.45（正式版本） （32 位） (Chromium 72.0.3626.121)
- OS: (win10 64bit)

**Comment by derjanb** [comment]
Fixed.
