### ISSUE TITLE
jQuery works on GM (Firefox) but not TM (Firefox/Slimjet/CentBrowser)

### ISSUE THREAD

**Issue by rasoir0591** [Tampermonkey/tampermonkey#671]
(Please fill out the issue template with your details)

## Expected Behavior
Working selectors $('div:contains(text)') and $('div:first'). 

## Actual Behavior
I get msg in console: TypeError: matchExpr[type].exec is not a function

## Specifications

- Firefox: (i.e. 66.0.1)
- TM: (i.e. 4.8.5847)
- OS: (i.e. Win 8.1)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @require     http://code.jquery.com/jquery-3.3.1.js
/* globals jQuery, $ */
// @name         PDmod2
// @version      0.1
// @description  BW mod!
// @author       PD
// @match		https://bloodwars.interia.pl/*
// @match     https://*.bloodwars.interia.pl/*
// @match     https://*.bloodwars.net/*
// @match 	https://*.bloodwars.pl/*
// @match     https://beta.bloodwars.net/*
// @match     https://old.bloodwars.interia.pl/*
// @grant 		GM_log
// @grant  		unsafeWindow
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// @grant       GM_addStyle
// @require     file:///D:\Users\Radek\Desktop\Automat_bw\PD2.js
// ==/UserScript==
(function($) {
    'use strict';
	console.log($('span:contains(Klan)').text());
})(jQuery);
```

**Comment by rasoir0591** [comment]
Ofc in Firefox I don't use require for local file.

**Comment by PetrToman** [comment]
Try:
- ``// @require https://code.jquery.com/jquery-3.3.1.js`` (https, not http)
- adding ``$ = this.jQuery = jQuery.noConflict(true);`` below the header

**Comment by rasoir0591** [comment]
`// ==UserScript==
// @require     https://code.jquery.com/jquery-3.3.1.js
/* globals jQuery, $ */
// @name         PDmod2
// @version      0.1
// @description  BW mod!
// @author       PD
// @match		https://bloodwars.interia.pl/*
// @match     https://*.bloodwars.interia.pl/*
// @match     https://*.bloodwars.net/*
// @match 	https://*.bloodwars.pl/*
// @match     https://beta.bloodwars.net/*
// @match     https://old.bloodwars.interia.pl/*
// @grant 		GM_log
// @grant  		unsafeWindow
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// @grant       GM_addStyle
// ==/UserScript==
$ = this.jQuery = jQuery.noConflict(true);
(function($) {
    'use strict';
	console.log($('span:contains(Klan)').text());
})(jQuery);`
Like this? The same, 

> TypeError: matchExpr[type].exec is not a function

**Comment by derjanb** [comment]
Can not reproduce. I've tested this script at https://bloodwars.interia.pl/ and https://bloodwars.net/

```JavaScript
// ==UserScript==
// @require     http://code.jquery.com/jquery-3.3.1.js
/* globals jQuery, $ */
// @name        PDmod2
// @version     0.1
// @description BW mod!
// @author      PD
// @match       https://bloodwars.interia.pl/*
// @match       https://*.bloodwars.interia.pl/*
// @match       https://*.bloodwars.net/*
// @match 	    https://*.bloodwars.pl/*
// @match       https://beta.bloodwars.net/*
// @match       https://old.bloodwars.interia.pl/*
// @grant 		GM_log
// @grant  		unsafeWindow
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// @grant       GM_addStyle
// ==/UserScript==

(function($) {
    'use strict';
    console.log('----> jQuery', $().jquery);
    console.log('----> contains Klan', $('span:contains(Klan)').text());
    console.log('----> div first', $('div:first'));
    console.log('----> PASSWORD REMINDER', $('div:contains(PASSWORD REMINDER)'));
})(jQuery);
```

and it logs messages as expected:

![image](https://user-images.githubusercontent.com/767504/55068278-bfc6f080-5081-11e9-9183-0ade8a4ac46b.png)

![image](https://user-images.githubusercontent.com/767504/55068308-d3725700-5081-11e9-8027-f06bf65a11b2.png)

Please add more details on how to reproduce this.

**Comment by rasoir0591** [comment]
![tamp 2](https://user-images.githubusercontent.com/48962434/55097864-038b1b80-50bd-11e9-9d82-6819f067a405.jpg)
![tamp 1](https://user-images.githubusercontent.com/48962434/55097871-05ed7580-50bd-11e9-9c56-960b0013634b.jpg)
Ok mayby I need reinstal FF and Tampermonkey

**Comment by rasoir0591** [comment]
Tried to do this on clean instal Vivaldi with Tampermonkey. Have the same error. You need to be logged in to get this error. I tried to get help on stackoverflow but no one answers. It's strange but same script works good on FF with Greasemonkey:
![Uploading greas.jpg…]()

**Comment by rasoir0591** [comment]
Do you have any solution for me? I tried on laptop with centbrowser and this doesn't work too.

**Comment by rasoir0591** [comment]
@derjanb 
Hey any help? I tried everything. Always same error:

>  TypeError: V[a].exec is not a function
