### ISSUE TITLE
[MacOS] Tampermonkey (beta) disabled all userscripts, and unable to enable it.

### ISSUE THREAD

**Issue by gslin** [Tampermonkey/tampermonkey#672]
(Please fill out the issue template with your details)

## Expected Behavior

* Tampermonkey should not disable all userscripts.
* Tampermonkey should allow users to enable userscripts if they are disabled.

## Actual Behavior

After selected all userscripts and clicked "Enable", they were still disabled, like this:

https://i.imgur.com/PX00iZH.mp4

Inspecting `background.html` and `chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/options.html` didn't show any javascript error.

btw, the symptom is same with #666.  And this is not the first time I occured this issue.

## Specifications

- Chromium: 73.0.3683.86
- TM: 4.9.5921
- OS: MacOS 10.14.4 (18E226)

## Script

No scripts here...

**Comment by derjanb** [comment]
What changed when this happened? OS update or a browser update or somthing similar?

**Comment by derjanb** [comment]
As q quick work-around. You can re-enable the scripts by opening and saving them. Another way is to factory reset the scripts (which will clear user defined includes, excludes, ... and the script storage as well).

**Comment by derjanb** [comment]
For reference: #652

**Comment by gslin** [comment]
In my memory, sometimes this would happen after something upgraded (Google Chrome or Tampermonkey).

btw, this also happened in Linux (with Google Chrome) before.

**Comment by gslin** [comment]
Factory reset works, thanks.

What information should I get next time (if it happens again) to help you debug?
