### ISSUE TITLE
Chrome conflicting when installing userscripts

### ISSUE THREAD

**Issue by feildmaster** [Tampermonkey/tampermonkey#673]
So when you try to load a userscript in chrome, the default behavior (without tampermonkey) is to download the file. A recent update causes tampermonkey to conflict.

## Expected Behavior
Loading userscript should only load the tampermonkey script install screen.

## Actual Behavior
Tab opens as "this site can not be reached", tampermonkey shows an install screen, and chrome attempts to download the file.

Chrome also attempts to refresh every few seconds, creating download and tampermonkey tab spam.

![](https://i.imgur.com/mAfG74X.png)

## Specifications

- Chrome: Version 73.0.3683.86 
- TM: 4.8
- OS: Windows 10

## Script
(Here's my script, though it should technically do it for every script)
http://unpkg.com/underscript

**Comment by Martii** [comment]
Same in `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/73.0.3683.75 Chrome/73.0.3683.75 Safari/537.36` with both latest TM and TM Beta. e.g. a brand spanking fresh profile in the last few minutes. Went to go see why a .user.js that I use on OUJS wasn't updated and tried installation manually... no go... said wasn't allowed however TM window below it said "Reinstall"... so clicked it ... and got the issuers image.

**Comment by derjanb** [comment]
See #667
