### ISSUE TITLE
Spensor payment way wanted

### ISSUE THREAD

**Issue by lifeforfun** [Tampermonkey/tampermonkey#674]
I don't have Paypal or credit card. I do only have Alipay 、Wechat.

**Comment by derjanb** [comment]
I once had a working Alipay implementation, but their TOS forbids donations/funding. 😒

**Comment by lifeforfun** [comment]
Haha. There is a simplest way: Patste a money receiving QR code (收款码) on the spnsor page, pepole can scan the qrcode picture to invoke a payment .

**Comment by joeytwiddle** [comment]
You could also consider Patron, so that people can set up a regular donation.

I think regular small donations might earn you more than occasional large donations. [citation needed]

**Comment by derjanb** [comment]
> Haha. There is a simplest way: Patste a money receiving QR code (收款码)...

@lifeforfun How do I get such a QR code from outside of China?

**Comment by lifeforfun** [comment]
Register an Alipay account or Wechat account (They all have international version), then you can get a money receiving QR code in their APP.

**Comment by xiaopangju** [comment]
> > Haha. There is a simplest way: Patste a money receiving QR code (收款码)...
> 
> @lifeforfun How do I get such a QR code from outside of China?

Register a WeChat or Alipay account,they have English vision.Then you can get QR code form WeChat or Alipay.Maybe you need real name authentication

**Comment by derjanb** [comment]
😔

![image](https://user-images.githubusercontent.com/767504/89629018-6ab60400-d89d-11ea-9c26-7ee87aaa91ea.png)
