### ISSUE TITLE
Edge crashes once the userscript is installed

### ISSUE THREAD

**Issue by machsix** [Tampermonkey/tampermonkey#675]
## Expected Behavior
run normally

## Actual Behavior
Once the script is installed, the browser crashes. This script applies to all web page. It works normally for both Firefox and Chrome. I need some help to learn how to debug the script for Edge. :cry:

## Specifications

- Edge

## Script

https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new

**Comment by derjanb** [comment]
Can't reproduce, but since the script uses notifications it's most probably related to this issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20146233/
