### ISSUE TITLE
TAMPERMONKEY SETTINGS MISSING

### ISSUE THREAD

**Issue by torbator** [Tampermonkey/tampermonkey#676]
In Tampermonkey>>Settings>>Security, there is no "STORE DATA IN INCOGNITO MODE".

I've seen a screenshot (1st image) where it is visible but mine (2nd image) seems missing. 

![image](https://user-images.githubusercontent.com/45986675/55818741-e9742300-5b29-11e9-8bdc-78b5c3c3c286.png)

![image](https://user-images.githubusercontent.com/45986675/55818815-17596780-5b2a-11e9-87ee-1f55ce2e125a.png)

**Comment by derjanb** [comment]
Duplicate of #656
