### ISSUE TITLE
Tampermonkey installed in Edge on chromium warns for malware

### ISSUE THREAD

**Issue by hansmbakker** [Tampermonkey/tampermonkey#677]
## Expected Behavior
Installing Tampermonkey from Insider Store in Edge (Chromium) runs without issues

## Actual Behavior
Tampermonkey warns for malware and says it is repackaged.

## Specifications

- Edge: `Version 74.1.96.24 (Official build) dev (64-bit)` --> Edge on Chromium Insider build
- TM: 4.8
- OS: Windows 10

Tampermonkey installed from https://microsoftedge.microsoft.com/insider-addons/detail/iikmkjmpaadaobahmlepeloendndfphd

## Screenshot
![image](https://user-images.githubusercontent.com/3463496/55831870-74e2b980-5b14-11e9-9089-8db06e4a4df9.png)

**Comment by derjanb** [comment]
Thanks for reporting.

**Comment by kathampy** [comment]
Is the Edge Insider version recommended over the Chrome Web Store version?

**Comment by derjanb** [comment]
The "Edge Insider store" version is taken from the Chrome Web Store, while the "regular Edge store" version indeed has some Edge-specific changes.
