### ISSUE TITLE
Feature Request: Script customization by folder

### ISSUE THREAD

**Issue by Cyberavater** [Tampermonkey/tampermonkey#681]
It'd be nice if I could customize scripts to different folders according to their usage.

**Comment by Cyberavater** [comment]
The dashboard looks really messy when you have a lot of scripts and it's really hard to manage them making the dashboard useless.

**Comment by derjanb** [comment]
A workaround for the moment is to add tags like "#myfavoritescript" at each script's comment section and then to search the scripts via Ctrl+F and "#myfavoritescript".

**Comment by Cyberavater** [comment]
https://github.com/violentmonkey/violentmonkey/issues/287

**Comment by Cyberavater** [comment]
That would do, I guess. My target is grouping them. If I can group them by different 'Tags' (which I can name myself) Tags ill do just fine. It'd look nice to see the 'Tag(s)' on the *group* title rather than having it separately on each script of the same group.

**Comment by derjanb** [comment]
Duplicate of #267
