### ISSUE TITLE
Donate is broken

### ISSUE THREAD

**Issue by phoenix1887** [Tampermonkey/tampermonkey#682]
(Please fill out the issue template with your details)
prompted to donate, can't. made a selection and selected paypal, it opened up 5 windows to paypal. security challenge failed probably because of the 5 windows. best to just include your paypal email address to donate manually. or venmo username.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Should work again. Thanks for reporting. :)
