### ISSUE TITLE
[Chrome] couldn't load @require from forbidden URL for local js file

### ISSUE THREAD

**Issue by Sasstraliss** [Tampermonkey/tampermonkey#685]
## Expected Behavior
Import the local js file for use within the userscript

## Actual Behavior
'couldn't load @require from forbidden URL' error in console when running userscript

## Specifications

- Chrome 73.0.3683.103
- TM v4.8 normal version
- Windows 10

## Script
```js
// @require       onbeforescriptexecute.js
```

My security settings: https://imgur.com/NUF0yAW

**Comment by molgin** [comment]
In case it helps: I was just struggling with this, and it turned out I needed to use the [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) in the `@require`, rather than just the path.

**Comment by Martii** [comment]
@molgin 
Yah Chromium backend defaults to https: for just about everything now. Even some http: doesn't work. Best to use absolute paths including protocols.

**Comment by derjanb** [comment]
This works fine if the `@require` URL is relative to the script's install URL. 

Main script D:\foo.user.js or /tmp/foo.user.js
---
```JS
// ==UserScript==
// @name        UTF-8 sample
// @namespace   utf_8_sample
// @match       https://www.tampermonkey.net/empty.html
// @version     0.0.1
// @grant       none
// @run-at      document-end
// @require     foo2.user.js
// ==/UserScript==

document.body.appendChild(document.createTextNode("漢字"));
```

Required script D:\foo2.user.js or /tmp/foo2.user.js
---
```JS
// ==UserScript==
// @name        UTF-8 sample
// @namespace   utf_8_sample
// @match       https://www.tampermonkey.net/empty.html
// @version     0.0.1
// @grant       none
// @run-at      document-end
// ==/UserScript==

console.log('external laoded');
```

Now install the first script by drag and dropping it to Chrome.
