### ISSUE TITLE
General question about sync

### ISSUE THREAD

**Issue by farzadmf** [Tampermonkey/tampermonkey#686]
Hi,

I have a general question about syncing that I wanted to double check. Right now, I'm putting sensitive information (passwords) in my scripts, and I just wanted to make sure that my scripts are not synched anywhere. Is it enough to have the setting as below or I need to do something else?

![image](https://user-images.githubusercontent.com/5768792/56743750-33bdec80-6745-11e9-99e1-c6a5047c6fdf.png)

Thank you

**Comment by derjanb** [comment]
Yes, it's enough to keep the settings as shown.
