### ISSUE TITLE
Auto reload pages should reload also after updating a script

### ISSUE THREAD

**Issue by garralab** [Tampermonkey/tampermonkey#688]
Not a bug, the setting option "Auto reload pages" clearly states that it will reload the page only when enabling or disabling a script. Still while I work on a new script I keep clicking on "check for userscript updates" and then I have to refresh the page manually (also since I'm impatient I keep trying to "race" the update refreshing even before the notification that the changes has been found... so if the new version was not up yet it get also a bit confusing)...

My point is, I click on check for updates after every single build (because I work with an ide and some build scripts externally), while I may actually never click on activate/deactivate for a script. So I would find very usefull if after updating the script to a new version the page gets refreshed automatically. At least when I manually clicked on "check for userscript updates".

**Comment by derjanb** [comment]
I feel this would confuse users.
If you're using Chrome you can enable local file access and `@require` a local copy (file://) of your script to have it up to date on every page reload.
