### ISSUE TITLE
kaspersky reports "HEUR:Trojan.Script.Generic"

### ISSUE THREAD

**Issue by spnova1** [Tampermonkey/tampermonkey#689]
"HEUR:Trojan.Script.Generic" is detected from files listed below:
1.  %\Google\Chrome\User Data\Profile 2\Extensions\jgphnjokjhjlcnnajmfjlacjnjkhleah\5.9.33_0\js\background.js

2. %\Google\Chrome\User Data\Profile 2\Extensions\jgphnjokjhjlcnnajmfjlacjnjkhleah\5.9.33_0\js\background.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\1.18.16_0\background.html

3. \Google\Chrome\User Data\Profile 2\Extensions\jgphnjokjhjlcnnajmfjlacjnjkhleah\5.9.33_0\js\background.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm\1.18.16_0\background.html

And Kaspersky deleted all those files already. 
What's wrong with these files and can i trust all this files and recover them?

**Comment by derjanb** [comment]
jgphnjokjhjlcnnajmfjlacjnjkhleah is not a Tampermonkey extension ID, but a shopping tool from the Chrome Web Store.

**Comment by spnova1** [comment]
sorry, wrong quotes. Files from Tampermonkey are:
1. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\storage.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

2.  D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\storage.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

3. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\parser.js

4. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\parser.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

5. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\parser.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

6. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\jgphnjokjhjlcnnajmfjlacjnjkhleah\5.9.20_0\js\background.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

7. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\icon.js

8. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\icon.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

9. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\icon.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

10. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\vendor\forge-sha256\forge-sha256.js

11. **D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\vendor\forge-sha256\forge-sha256.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html**

12. D:\Program Files (x86)\Google\Local\Google\Chrome\User Data\Profile 2\Extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\vendor\forge-sha256\forge-sha256.js//d:\program files (x86)\google\local\google\chrome\user data\profile 2\extensions\dhdgffkkebhmkfjojejmpbldmpobfkfo\4.8_0\background.html

these files are from tampermonkey.
