### ISSUE TITLE
[Suggestion] Add caching favicons and local use

### ISSUE THREAD

**Issue by aompqn** [Tampermonkey/tampermonkey#692]
(Please fill out the issue template with your details)

## Expected Behavior
Suggestions: 
add caching favicons (from like google) 
and option - local use, from local folder /img/github.com and popular sets of favicons(google, like on one image icons_set.png

## Actual Behavior
each time its ask internet

## Specifications

- Chromium: supported
- TM: 4.8
- OS: windows

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
You can choose between different services and at least in native mode most favicons are delivered from disk cache here.

![image](https://user-images.githubusercontent.com/767504/56914947-a5839680-6ab5-11e9-9e3e-c952832ebfd3.png)

![image](https://user-images.githubusercontent.com/767504/56915062-e54a7e00-6ab5-11e9-8595-88e33b177082.png)
