### ISSUE TITLE
[Suggestion] Options use build-in icons instead font awesome

### ISSUE THREAD

**Issue by aompqn** [Tampermonkey/tampermonkey#693]
(Please fill out the issue template with your details)

## Expected Behavior
Options use build-in icons like 
<img id="img_user_script" class="icon16" src="data:image/png;base64
or with "set of icons"

## Actual Behavior
font awesome support only on newest versions of chrome

## Specifications

- Chromium: supported (example v55)
- TM:  4.8
- OS:  windows 

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
What's the Chrome version that has issues with Font Awesome?

**Comment by aompqn** [comment]
> What's the Chrome version that has issues with Font Awesome?
55

**Comment by derjanb** [comment]
You can use "Custom CSS" to modify the Font Awesome rules to show UTF-8 icons for example.
