### ISSUE TITLE
[Suggestion] Add button edit this script in pop-up(Action) menu

### ISSUE THREAD

**Issue by aompqn** [Tampermonkey/tampermonkey#694]
(Please fill out the issue template with your details)

## Expected Behavior
Add button edit this script in pop-up menu(Action Menu) that open it script in extension tab

## Actual Behavior
only report problem menu button

## Specifications

- Chromium: supported
- TM: 4.8
- OS: windows
## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
For the moment Control+click or middle-mouse-button-click at the script will do the job.

**Comment by aompqn** [comment]
Control+click  and right click working
