### ISSUE TITLE
[Suggestion] options add line menu separator in Action Menu for Enabled

### ISSUE THREAD

**Issue by aompqn** [Tampermonkey/tampermonkey#695]
(Please fill out the issue template with your details)

## Expected Behavior
help with separation, focusing when have big list

make font little bit contrast and fat

add line menu separator in Action Menu for Enabled like it separate main menu actions
1 for on/off  and 2-framing for random in list 

## Actual Behavior
it is shown as row and unfocus in big list

## Specifications

- Chromium: supported
- TM: 4.8
- OS: windows

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Just configure Tampermonkey to use the 3 column action menu layout and disabled and enabled scripts will be separated.

**Comment by Martii** [comment]
> use the 3 column action menu layout and disabled and enabled scripts will be separated

With a page refresh here... just tried this out. :)
