### ISSUE TITLE
[Suggestion] Option tab scripts load with search bar opened and untied browser native CTRL+F search

### ISSUE THREAD

**Issue by aompqn** [Tampermonkey/tampermonkey#696]
(Please fill out the issue template with your details)

## Expected Behavior
Option: tab "installed userscripts" load with search bar opened
and untied native browser CTRL+F search

## Actual Behavior
each 99.9% time need press 3 times to open search script

## Specifications

- Chromium: supported
- TM: 4.8
- OS: windows

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
You can simply add this to the "Custom CSS" field and the search bar will be always be visible.

```CSS
.multiselect .multiselectrow {
    display: table-row;
}
```

**Comment by aompqn** [comment]
thank you, but checkbox will be perfect
