### ISSUE TITLE
Google drive auth_failed

### ISSUE THREAD

**Issue by chi-ang** [Tampermonkey/tampermonkey#697]
(Please fill out the issue template with your details)

## Expected Behavior
Can export and display backups

## Actual Behavior
Shows `auth_failed` when click export to google drive
`show backups` doesn't work after jump to google verification page.

## Specifications

- Chromium: (74.0.3729.131)
- TM: (4.8)
- OS: ( Windows10 1809)

**Comment by derjanb** [comment]
"Duplicate" of #698

**Comment by hackeye** [comment]
I have this ，but beta is ok

**Comment by Kaiskov** [comment]
beta already fix 4days ago, thanks.
