### ISSUE TITLE
OneDrive/Dropbox/Google drive authentication fails

### ISSUE THREAD

**Issue by water903** [Tampermonkey/tampermonkey#698]
(Please fill out the issue template with your details)

## Expected Behavior
Can export and display backups

## Actual Behavior
Shows auth_failed when click export to dropbox/google drive
show backups doesn't work after jump to dropbox/google verification page.

## Specifications

- Chromium: (Chromium 72.0.3626.121 /Chrome 74.0.3729.131 )
- TM: (4.8)
- OS:  ( Windows7 )

**Comment by redion1992** [comment]
This also seems to be affecting the appropriate sync implementations.

**Comment by derjanb** [comment]
Should be fixed at Tampermonkey BETA 4.9.5937. I'll release a new stable soon.

**Comment by chi-ang** [comment]
tnks!

**Comment by chi-ang** [comment]
@water903  Why are you copying my description? #697

**Comment by water903** [comment]
@chi-ang 
I'm sorry that i copy your description.
because trying export to dropbox/google drive on two Chrome version then i feel tired,i copy it.

**Comment by chi-ang** [comment]
@water903 你把👴逗笑了

**Comment by Yoosk** [comment]
Maybe fixed at beta, but not firefox beta, that's still 5921 version.

**Comment by derjanb** [comment]
I'll update the Firefox version as sonn as Mozilla starts to sign extensions again.

https://www.tampermonkey.net/changelog.php?version=4.9.5941&ext=firb
https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/15
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 (armagadd-on-2.0)

**Comment by derjanb** [comment]
A new Chrome version was released, but it might take some time until the updated is delivered to everyone.
You can force update Tampermonkey by downloading

https://test.tampermonkey.net/versions/stable/156a5e9/stable_4_8_41.crx

and drag and drop the file to Chrome's extension page (chrome://extensions)

**Comment by derjanb** [comment]
Fixed at both FF vesions as well.

**Comment by txl263** [comment]
Same error at 
macos10.12.6
Safari 12.1.1
Tampermonkey v4.7.5826

**Comment by derjanb** [comment]
I've updated the self-hosted Tampermonkey Safari version. The official one might take a while.

**Comment by zanderzhng** [comment]
I'm now using version 5941 and the problem was fixed.
https://safari.tampermonkey.net/tampermonkey-5941.safariextz
