### ISSUE TITLE
[Firefox] Debugger does not work correctly when using @grant other than none

### ISSUE THREAD

**Issue by D0tNet4Fun** [Tampermonkey/tampermonkey#699]
## Expected Behavior
The source code that is loaded in the debugger should be identical to the one that is being executed, regardless the value of `@grant`.

## Actual Behavior
The source code that is loaded in the debugger is out-of-sync when `@grant` is something other than `none`.

## Specifications

- Firefox Quantum: 66.0.3
- TM: 4.9.5921; also happens in TM Beta 4.9.5921.
- OS: Windows 10 1809

## Script

The following script, when loaded in the Firefox debugger, behaves as I expect:

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    debugger;
    GM_log('hello world');
})();
```
The first statement to be executed is `debugger;`, then the next statement is `GM_log('hello world');`

After updating `@grant` to `GM_log`, the statements to be executed are displayed as being outside of the userscript, as shown in this screenshot:

![image](https://user-images.githubusercontent.com/17428504/57130300-b710bb00-6da1-11e9-9ff9-7b15707e6ca7.png)

If I try to set a breakpoint on line 18, the breakpoint is added to line 20 instead. I think this means there is no instruction at line 18 in the source that is being executed, meaning this source is not the same as the one being loaded in the debugger.

Notes:
- the script is executed as expected
- this does not happen in Chrome

**Comment by xiaoyao9184** [comment]
I had the same problem on chrome.

Chrome: 78.0.3904.108 x64
TM: 4.9; also happens in TM Beta 4.10.6102
OS: Windows 10 1909
