### ISSUE TITLE
[Firefox] Obfuscated code not allowed

### ISSUE THREAD

**Issue by racalav** [Tampermonkey/tampermonkey#701]
I just found out that effective June 10th, 2019, Firefox won't allow add-ons to contain obfuscated code. What does mean for Tampermonkey on Firefox? As far as I can tell, all the code is obfuscated and minified.

Links:
* https://blog.mozilla.org/addons/2019/05/02/add-on-policy-and-process-updates/
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Blocking_Process

**Comment by derjanb** [comment]
> We will continue to allow minified, concatenated, or otherwise machine-generated code as long as the source code is included.

Tampermonkey uses minification and the source code is sent along and reviewed with every release.
