### ISSUE TITLE
SaveAs stopped working today, all of sudden

### ISSUE THREAD

**Issue by ssfmin** [Tampermonkey/tampermonkey#703]
(Please fill out the issue template with your details)

## Expected Behavior
This code should save the file, I have this code in several scripts.
It was working fine until yesterday
Today I am getting warning message on line :: saveAs(blob, filename+".txt");
Warning: saveAs is not Defined

I didn't update Chrome/Tampermonkey
But this code stopped working in all scripts, & also in all chrome versions I have.
I did notice new update(6/5/2019) in TamperMonkey, I did update, problem still exists.

FileSaver.js/Jquery links are working fine.

Please help - Thanks

## Actual Behavior
Should Save file

## Specifications
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         HTML_File_Downloader_
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.ashleyfurniture.com/*
// @grant GM_setValue
// @grant GM_getValue
// @grant GM_setClipboard
// @grant unsafeWindow
// @grant window.close
// @grant window.focus
// @require      http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
// @require      http://MYDOMAIN.com/FileSaver.js

(function() {
    window.setTimeout(function(){
        var text = document.body.innerHTML;
            var filename = window.location.href.split('/'); filename = filename[(filename.length)-2];
            var blob = new Blob([text], {type: "text/plain;charset=utf-8"});
            saveAs(blob, filename+".txt");
    }, 3500);
})();
```

**Comment by derjanb** [comment]
Looks like the `@require` could not be loaded/updated? Can you please check the content of it at the scripts "Externals" tab. Thanks.
