### ISSUE TITLE
Filter icon is missing

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#706]
See the same in Chromium or FF, stable or beta:

![TM](https://user-images.githubusercontent.com/14100003/57415507-8201cf80-71ca-11e9-8bb5-ceee7c2858b9.png)

**Comment by derjanb** [comment]
Please excuse the delay. I was on parental leave. :) Fixed at TM BETA 4.9.5960.

**Comment by narcolepticinsomniac** [comment]
Bout damn time. =) Congrats btw!
