### ISSUE TITLE
[Firefox] sync page won't close automatically

### ISSUE THREAD

**Issue by michaelts1** [Tampermonkey/tampermonkey#708]
(Please fill out the issue template with your details)

when Script Sync is enabled (at least if using google drive), the tampermonkey opens a page with the following:
https://www.tampermonkey.net/oauth.php#state=...&access_token=...&token_type=...&expires_in=...&scope=https://www.googleapis.com/auth/drive.appdata

after the page loads, it should close automatically, so the page has the following script in source:
> <script>
>       (function() {
>         "use strict";
>         window.close();
>       })();
> </script>
This works on chrome, but on Firefox, the page won't close. instead, you will get the following message in the console: **"Scripts may not close windows that were not opened by script."**

### Specs:
- Firefox 66.0.5
- TM v4.9.5921
- Win 10 version 1903 (OS build 18362.86)

**Comment by derjanb** [comment]
See #708

**Comment by michaelts1** [comment]
Are you aware of that you are referencing me to this very issue?
If you mean by "See #708", that this is duplicate, then you are wrong. _This_ is issue #708

**Comment by derjanb** [comment]
Oh sorry.  🤦 #698 😊
