### ISSUE TITLE
why import the script failed

### ISSUE THREAD

**Issue by SuperVBird** [Tampermonkey/tampermonkey#709]
my system is win10 ,I switched the currently  user ,so my browser become initial ,I lost all my script that I download before time,I forget to backup the scripts,I don't know how to recover that,my browser version is 360 safe browser 10.1,I am not sure that I found the real storage path of scripts,I try to load the file ,
![Z~4RWE7 I)`UG(NXKR$P)JO](https://user-images.githubusercontent.com/40413302/57696473-6b082500-7683-11e9-8a7d-a3a066ddcb63.png)

![Y9S$UYPXWT5}AO`)D@WCVS5](https://user-images.githubusercontent.com/40413302/57696490-73606000-7683-11e9-8ba9-aa01a3aeebcb.png)

but as the picture show, I faild,that really make me dispirited.

**Comment by derjanb** [comment]
This is Chrome's database file which is not compatible to Tampermonkey's import utlity.

Please use https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0 or https://gist.github.com/calraith/5ea698d022dfe77d3927e75af7cdea75 to extract your scripts instead.
