### ISSUE TITLE
на каком сайте это делается Заполните одно предложение, чтобы иметь доступ к скрипту Сделать одно предложение (бесплатно ), это лучший способ назначения моего скрипта бесплатно

### ISSUE THREAD

**Issue by Pavel231** [Tampermonkey/tampermonkey#711]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by Pavel231** [comment]
как мне решить действие с этим Заполните одно предложение, чтобы иметь доступ к скрипту
Сделать одно предложение (бесплатно ), это лучший способ назначения моего скрипта бесплатно где надо зделать предложение срочно надо

**Comment by Pavel231** [comment]
ну

**Comment by Pavel231** [comment]
долго

**Comment by derjanb** [comment]
Not sure, what you are talking about. If you do have a problem with one of your scripts, then please contact the script author. Thanks.

**Comment by shurmosha** [comment]
![Снимок](https://user-images.githubusercontent.com/17802561/68510143-c9edd600-0283-11ea-91b4-688357e8aad2.PNG)
![Снимок1](https://user-images.githubusercontent.com/17802561/68510144-c9edd600-0283-11ea-8092-2c074ed80d97.PNG)
