### ISSUE TITLE
Encountering a bug can lead to memory leaks

### ISSUE THREAD

**Issue by heiyutian** [Tampermonkey/tampermonkey#713]
I have encountered a place where youtube is embedded on any page. If there are many scripts enabled on this page, it will take up a lot of resources and memory of my computer. I see that this extension icon will display a lot of numbers. It’s many times more than the number of extensions I have enabled. I don’t know why this is happening. I’m in the official version of Tampermonkey and Tampermonkey BETA. I tried turning off all other extensions, just use this one, as long as I Each time you enable a script that will take effect on the page, it will add a lot of numbers to the icon. The more the enabled scripts take effect, the more memory and CPU it consumes. The memory of my computer is only 8G, which is unacceptable. I hope I can find the reason and avoid this problem. This problem is only found in the place where there are many youtube videos embedded on the webpage. On other webpages that do not have youtube embedded, I have enabled a lot of scripts. This problem does not occur. .

I will give a test address here.
https://katecfilms.blogspot.com/2018/08/netflix-original-series.html

**Comment by derjanb** [comment]
Please disable all scripts and re-enable them step by step to find out which script causes the issue. If you found it, then you may limit the URLs where it is running at by adding `@exclude` statements or altering `@include`s.
