### ISSUE TITLE
Scripts synced from dropbox are invisible.

### ISSUE THREAD

**Issue by zanderzhng** [Tampermonkey/tampermonkey#717]
## Expected Behavior
I should be able to see my scripts synced from dropbox.

## Actual Behavior
In Safari, I see no scripts in my TM, but there are actually scripts running. They seems to be invisible.
I tried uninstalling TM, restart, reinstall, resync. Problem not fixed.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/867749/58452843-76f7ea80-814b-11e9-9d03-0082542808da.png">
I can see them in Chrome, however.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/867749/58452977-e2da5300-814b-11e9-887f-c0a0705faced.png">

## Specifications

- Safari: Version 12.1.1 (14607.2.6.1.1)
- TM: 4.7.5826
- OS: 10.14.5 (18F132)

## Script
All scripts synced from dropbox.

**Comment by derjanb** [comment]
This is related to #698. I need to release a new Safari version first.
