### ISSUE TITLE
Please add donation channels for Chinese people

### ISSUE THREAD

**Issue by DFLMJ** [Tampermonkey/tampermonkey#718]

**Comment by joeytwiddle** [comment]
In #674 the author tried using Alipay but it didn't work out.

@DFLMJ Do you have any recommendations? What channels have you seen other projects using?

**Comment by Robin2233** [comment]
@joeytwiddle WeChat Pay

**Comment by DFLMJ** [comment]
@joeytwiddle Alipay pay or WeChat pay

**Comment by derjanb** [comment]
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464
