### ISSUE TITLE
Browser crash when closing Incognito window

### ISSUE THREAD

**Issue by rossjrw** [Tampermonkey/tampermonkey#719]
## Expected Behavior

1. Open Incognito tab.
2. Close Incognito tab.
3. Everything is fine.

## Actual Behavior

1. Open Incognito tab.
2. Close Incognito tab.
3. Chrome (and ChromeOS) immediately crashes and reboots.

Opening more tabs, and closing tabs, in the Incognito window is fine. The browser crashes as soon as the last incognito tab is closed. On ChromeOS, this soft-reboots the system. I imagine it's equivalent to just crashing Chrome on any other OS.

## Specifications

- Chrome: 74.0.3729.159
- TM: 4.8.41
- OS: ChromeOS 11895.118.0 (Official Build) stable-channel lulu

## Script

Bug is present even with no scripts enabled.

**Comment by derjanb** [comment]
Looks like a known Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=897946

**Comment by rossjrw** [comment]
Quite possibly. On my end at least, it's only present when Tampermonkey is active (and enabled for Incognito). Turning Tampermonkey off stops the crash.

**Comment by samirgiri** [comment]
Experience the same behavior in Chrome OS Version 74.0.3729.159 (Official Build) (64-bit).   This was working fine with an older version (of Chrome OS or Tampermonkey).

**Comment by hgrubbs** [comment]
This is reproducible for me with no extensions enabled.

**Comment by derjanb** [comment]
Is this still an issue?
