### ISSUE TITLE
Locally loaded UTF-8 scripts decoded as Latin-1

### ISSUE THREAD

**Issue by 5891** [Tampermonkey/tampermonkey#720]
## Expected Behavior

Load a local script file encoded in UTF-8 and see no [mojibake](https://en.wikipedia.org/wiki/Mojibake).

## Actual Behavior

Load a local script file encoded in UTF-8 and note the mojibake. It looks like that it is force-decoded using an exotic encoding, namely Latin-1.

## Specifications

- Chromium: 74.0.3729.169
- TM: 4.8.41
- OS: Windows 10 Version 1803 Build 17134.765

## Script

Remember to load the following script by opening it in the browser as a local file encoded in UTF-8 with or without the leading BOM.

```js
// ==UserScript==
// @name        UTF-8 sample
// @namespace   utf_8_sample
// @match       https://www.example.org/
// @version     0.0.1
// @grant       none
// @run-at      document-end
// ==/UserScript==

document.body.appendChild(document.createTextNode("漢字"));
```

Execute the following expression to reproduce the mojibake using Python IDLE.

```pycon
>>> "漢字".encode("utf-8").decode("latin-1", errors="ignore")
'æ¼¢å\xad\x97'
```

**Comment by derjanb** [comment]
Please excuse the delay. I was on parental leave. :) Fixed at TM BETA 4.9.5960.
