### ISSUE TITLE
Is it possible to inject javascript into a webpage in order to broadcast messages when an event is triggered?

### ISSUE THREAD

**Issue by LarryEitel** [Tampermonkey/tampermonkey#724]
I am interested in connecting a webpage's updates with Integromat or Zapier via websocket.

I understand that it is possible using Tampermonkey that I can inject and launch javascript into a page. I am thinking that it is possible to inject code to listen to changes to the DOM and if an element has new data, to broadcast/push it to an end point, ie, Integromat for further handling.

If so, can you point to an example?

Thank You

**Comment by derjanb** [comment]
This should be possible depending on what a Integromate end point is. However, this is not a development support forum. Sorry.
