### ISSUE TITLE
window.opener null with GM_openInTab

### ISSUE THREAD

**Issue by jimdonohue** [Tampermonkey/tampermonkey#725]
The window.opener reference is not set when using Tampermonkey's GM_openInTab

## Expected Behavior
The new window should have window.opener set as a reference to the [script's] source window

## Actual Behavior
window.opener is null in the window loaded in the new tab

## Specifications

- Chrome 75
- TM: 4.8.41
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         script
// @match        https://github.com/*
// @grant        GM_openInTab
// ==/UserScript==

GM_openInTab('https://example.com', true);    // window.opener is null in new window
window.open('https://example.com', '_blank'); // window.opener references this window in new window
```

**Comment by derjanb** [comment]
Can't really fix this, because tabs a separate processes and it is therefore not possible to access the opening window. 

Not sure what you're doing, but maybe this can be used as a woraround:
```JS
GM_openInTab('a_page.html').name = 'foo'
```

A script running at `a_page.html` then can access ```unsafeWindow.name``` which will be `foo` (after a short time);
