### ISSUE TITLE
window.close might be ignored with GM_openInTab

### ISSUE THREAD

**Issue by jimdonohue** [Tampermonkey/tampermonkey#726]
Chrome won't let a script close() a window/tab unless it was opened by a script. It will also ignore close() when the user navigates to a new document in that opened window/tab.

Also, in Chrome, if open() is used to open a new window/tab and then a script causes a redirect to a new document within a short time frame, the navigation is (typically) replaced within the history and the back button is (typically) disabled. I believe there is a chrome:flag for this behavior. In this case, a script in the newly loaded document can still call close(). So, a script can window.open() a tab, a script can load a new document, and then a script can window.close() this tab.

However, with GM_openInTab, if any kind of navigation occurs in the opened tab, any future call to window.close will be ignored.... UNLESS, of course, the script trying to call window.close() is a TM userscript with a `@grant window.close` declaration.

As a workaround for my needs, I have a userscript that simply grants window.close and then calls window.close() for the necessary URL which gets loaded in the new tab.

## Expected Behavior
window.close() should close any tab opened by GM_openInTab

## Actual Behavior
window.close() is ignored if a navigation occurs in the tab opened by GM_openInTab

## Specifications

- Chrome 75
- TM: 4.8.41
- OS: Windows 10

**Comment by derjanb** [comment]
I understand your request, but unfortunately the tabs API has no option to somehow mark the tab as being opened programmatically. It might be possible to somehow track the tab and overwrite window.close on every navigation, but given the easy way to workaround it, this might not being worth the effort.
