### ISSUE TITLE
advanced Notification options

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#727]
## Expected Behavior
GM_notification to support (more) options detailed at https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#Browser_compatibility
example:
`new Notification("hi",{silent:true}) //opens a notification without sound
`

## Actual Behavior
`
GM_notification({text:"hallo",silent:true}) // still makes a sound
`

## Specifications

- Chromium: (74.0.3729.169)
- TM: (4.9.5941)
- OS: (Windows)

**Comment by jonnytest1** [comment]
not sure how youre doing this but this might help 
https://developer.chrome.com/apps/notifications#type-NotificationOptions

**Comment by derjanb** [comment]
Fixed at TM BETA 4.9.5960.
