### ISSUE TITLE
Can you provide Alipay payment or WeChat payment?

### ISSUE THREAD

**Issue by wolvezb** [Tampermonkey/tampermonkey#728]
Thank you very much, I really like this plugin.
I really want to donate
But I am in China
I can't use those payment methods
Can you provide Alipay payment or WeChat payment?
                                                                    - using machine translation

**Comment by derjanb** [comment]
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464
