### ISSUE TITLE
Chromium: Websockets connections timeout if behind Proxy with NTLM and TM enabled

### ISSUE THREAD

**Issue by distahl** [Tampermonkey/tampermonkey#730]
(Please fill out the issue template with your details)

## Expected Behavior
Chat Implementations like Discord, Whatsapp Web, Steam should work without issues.

## Actual Behavior
If Tampermonkey plugin is enabled (Browser Side) Websocket connections fail, demanded by e.g. Discord. But only if you are using a Proxy which is working with Windows Authentication (NTLM). (Maybe even in general if using Proxies with any kind of authentication, but this part is untested.)
If I disable Tampermonkey (Plugin Side) Websocket connections still don't work.  They only work again if I disable the hole Tampoermonkey plugin broser side.

This behaviour first started after I updated Chromium from v66 to v75. 
On v66 everything was working fine.

## Specifications

- Chromium: 75.0.3770.90
- TM: 4.8.41
- OS: Windows 10 (1803)

## Script
-

**Comment by derjanb** [comment]
Tampermonkey+Chromium+Websockets are working fine here. Can you please add a failing example? Thanks.

**Comment by distahl** [comment]
Hi. thanks for looking into this.
As mentioned in the "Actual Behaviour". To reproduce this. 
 - You need to make Chromium use a Proxy with NTLM Authentication. Maybe another Authentication-Method also creates this issue, but this is untestet. Only thing I can say for sure is, proxies without any authntication don't produce this issue.
- Then try to login to Discord or try to login to Whatsapp-Web (You maybe even dont see any QR-Code)

**Comment by derjanb** [comment]
I can confirm that the issue does not happen with a "regular" proxy using authentication. 
I applied a fix to Tampermonkey so can you please test whether the issue is still there at Tampermonkey BETA 4.10.6104.
Thanks.

**Comment by distahl** [comment]
Hi,
Thanks for trying to fix this.
I've downloaded the newest Beta-Release of Tampermonkey from the Chrome Web Store and checked. Unfortunately it's still the same. With Tampermonkey (Stable or BETA) enabled and NTLM Proxy. I'm not able to access e.g. Steam Chat.

**Comment by derjanb** [comment]
Is this still an issue. Not sure from where to get a NTLM proxy at the moment.

**Comment by distahl** [comment]
Thanks for your reply. I've check and with v80 of Chromium, this issue seems to be gone.
