### ISSUE TITLE
谷歌浏览器重启电脑删除插件

### ISSUE THREAD

**Issue by sanxue** [Tampermonkey/tampermonkey#732]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```
谷歌浏览器，版本 75.0.3770.27（正式版本）beta （64 位）
每次重启电脑后，在打开谷歌浏览器，每次都发现油猴插件被删除了，需要重新添加插件才能用。

**Comment by derjanb** [comment]
看起來你正在使用非官方版本。 請從此處下載Tampermonkey：https：//chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
---
Looks like you're using an unofficial version. Please download Tampermonkey from here: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
