### ISSUE TITLE
пропала почта сегодня  утром было нормально..а днем включил браузер цент и нет почты

### ISSUE THREAD

**Issue by shurmosha** [Tampermonkey/tampermonkey#733]
![Снимок6](https://user-images.githubusercontent.com/17802561/60437928-0f383200-9c18-11e9-9ed2-b30e5f59fe23.PNG)
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please disable all scripts, check again and re-open this issue if the problem still persists.
