### ISSUE TITLE
[Chrome] Cannot close tab anymore: Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab).

### ISSUE THREAD

**Issue by kingIZZZY** [Tampermonkey/tampermonkey#734]
## Overview
Chrome fails with console error `Unchecked runtime.lastError: Tabs cannot be edited right now (user may be dragging a tab).` if user interacts with tabs opened with `GM_openInTab(...)` while the tab is attempted to be `close()`d

## Expected Behavior
Even if there was a failure closing the tab
- calling `tab.close()` subsequently should still close the tab
- `tab.closed` should still evaluate to `false`

## Actual Behavior
- `tab.close()` does not work anymore. The tab is now "lost" and out of control of the userscript
- `tab.closed` evaluates to `true` even though the tab is not closed

## Specifications
Chrome 75.0.3770.100 (Official Build) (64-bit)
TM v4.8.41
Windows 10 x64

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant GM_openInTab
// ==/UserScript==

var tab1 = GM_openInTab('https://www.google.com');
// go interact with the tab at just the right (wrong) instant
// when it's attempting to close ex. be clicking/holding the tab handle
setTimeout(function(){
    tab1.close(); // while the tab is being clicked
},3000);
// assuming tab failed to close with the above chrome error
setTimeout(function(){
    console.log(tab1.closed); // true - when it should be false
    tab1.close(); // does nothing, when it should perform its normal function
},10000);
```

**Comment by derjanb** [comment]
Sorry for the delay. Fixed at the beta version a month again, but review took that long. 😢
