### ISSUE TITLE
download not working any more

### ISSUE THREAD

**Issue by qtairo** [Tampermonkey/tampermonkey#736]
(Please fill out the issue template with your details)

## Expected Behavior
press download then start

## Actual Behavior
Nothing happend

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by Martii** [comment]
Download of what? Script.... Tampermonkey... the collective knowledge of humanity? :confused: Didn't realize there was a release of Chromium on macOS too other than nightly.... brew?

**Comment by derjanb** [comment]
@qtairo Please contact the script author. He will contact me if there are any problems.
