### ISSUE TITLE
[MS Edge] Internal Error

### ISSUE THREAD

**Issue by SmartManoj** [Tampermonkey/tampermonkey#737]
Chromium Edge
![image](https://user-images.githubusercontent.com/7231077/60727510-ac1e0680-9f5b-11e9-810f-43e4a621b542.png)

**Comment by SmartManoj** [comment]
Some text are hiding if the extension is at rightmost

**Comment by derjanb** [comment]
Will be fixed at the "new Microsoft Edge" browser.
