### ISSUE TITLE
GM.xmlHttpRequest strange behaviour with Firefox

### ISSUE THREAD

**Issue by liquorburn** [Tampermonkey/tampermonkey#739]
## Expected Behavior
The `response` variable contains the html of page set into `url` variable

## Actual Behavior
The `response` variable contains the html of the currente page in which my userscript is running

## Specifications

- Mozilla Firefox: (v68.0)
- TamperMonkey: (v4.9.5941)
- OS: (Windows 10 Build 18362.207)

## Script
```js
/* ... */
GM.xmlHttpRequest({
      method: "GET",
      url: "https://mycoolsite.com/mypage.html",
      onload: function(response) {
          /* ... */
      }
});
/* ... */
```
Using `GM_xmlhttpRequest` does not solve the issue.

With Tampermonkey v4.8.41 in Google Chrome v75.0.3770.100 my code works like a charm. Any clue?

**Comment by kingIZZZY** [comment]
How are you examining the contents of `response` ?

If you are outputting / logging / writing the contents into the page, then I'd consider that reliable and indeed this would be a strange bug.

BUT if you're examining javascript debugger watch variables, or hovering over expressions in debugger, or exploring locals in debugger etc. I've had some experiences where the developer tools javascript debugger lies to you and shows you the wrong values for the wrong expressions of the wrong scopes.

Also; does the network log confirm the ajax response is what you need it to be? Maybe your webserver is serving the wrong response after all for some reason?

**Comment by liquorburn** [comment]
I'm writing the contents into the page. But nevermind, because I found the solution: I had to manually pass the cookies into `headers` variable like this:
```
GM.xmlHttpRequest({
      method: "GET",
      url: "https://mycoolsite.com/mypage.html",
      headers: {
        'Cookie' : 'mycookiename:mycookievalue;anothercookiename:anothercookievalue'
      },
      onload: function(response) {
          /* ... */
      }
});
```
Without cookies the server redirects me. So please consider this issue closed, thanks anyway.
