### ISSUE TITLE
Cannot install Tampermonkey

### ISSUE THREAD

**Issue by hinku** [Tampermonkey/tampermonkey#740]
install form web store :https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
## Actual Behavior
cannot install Tampermonkey

## Specifications

- Chromium: 版本 75.0.3770.100（正式版本） （64 位）
- OS: Windows 10 1809 17763.615

![cannot install Tampermonkey](https://user-images.githubusercontent.com/49828397/61305303-2b91bc80-a81d-11e9-8a45-f5fb6d2eb8a3.png)

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/744#issuecomment-515352477
