### ISSUE TITLE
Enable/disable scripts for specific sites from Tampermonkey icon in chrome toobar

### ISSUE THREAD

**Issue by zxyzgt** [Tampermonkey/tampermonkey#741]
Enable/disable scripts from the TM icon is global. Is there any way to apply the setting only to the specific sites? I know @match or @include, but it is redundant to open the dashboard and add domains in TM settings each time when you browsing some sites. It would be better if the enabled sites could be added to the **user includes** in settings automatically.
![1](https://user-images.githubusercontent.com/21346832/61683014-eae4e800-ace1-11e9-889c-5fb01f99ae03.png)

## Specifications
- Chrome: (Version 75.0.3770.100)
- TM: (4.8.41)
- OS: (i.e. windows 10)

**Comment by derjanb** [comment]
By doing so the action menu would need to display all installed script with an option to add a domain. I think this would look very confusing. So the current solution is to make the script run at every page and disable it for given domains at the action menu.

![image](https://user-images.githubusercontent.com/767504/68085145-cbf80500-fe3d-11e9-9b59-fbdb54e050d3.png)

**Comment by devn4u** [comment]
But there are a few scripts that I would like to run only on a specific website and exclude all others can this be done?

**Comment by derjanb** [comment]
@devn4u 

Yes, at the script's "Includes/Excludes" section at the settings tab:

![image](https://user-images.githubusercontent.com/767504/95296545-3f3d9e80-0879-11eb-9380-b5ad1d07df32.png)

**Comment by Firefox289** [comment]
I still don't understand

**Comment by Firefox289** [comment]
i cant like add excludes

**Comment by stdedos** [comment]
What seems to be the problem? 😕
![image](https://user-images.githubusercontent.com/133706/155216861-f25a1bf1-e13a-44dc-a435-3768bc6efa8d.png)

**Comment by younyokel** [comment]
Sorry for bringing this up but is there a way to turn off a Tampermonkey script on every websites, except for specific websites?

**Comment by derjanb** [comment]
> Sorry for bringing this up but is there a way to turn off a Tampermonkey script on every websites, except for specific websites?

Yes, simply disable "Original matches" and "Original includes" and add your own "User matches".

**Comment by zpoison** [comment]
Where is it located please? It doesn't seems to be there in the setting page that I have v4.19.0
No include/exclude section and no "matches" option neither
