### ISSUE TITLE
75.0.3770.142正式版本64 位谷歌浏览器不支持

### ISSUE THREAD

**Issue by sihairensheng** [Tampermonkey/tampermonkey#744]
75.0.3770.142正式版本64 位谷歌浏览器不兼容,直接报错说包格式不支持
![image](https://user-images.githubusercontent.com/12953151/61815901-cfaedf80-ae7d-11e9-9b0e-c8e10db5407a.png)

**Comment by derjanb** [comment]
You can force update Tampermonkey by downloading

https://test.tampermonkey.net/versions/stable/156a5e9/stable_4_8_41.crx

and drag and drop the file to Chrome's extension page (chrome://extensions)
