### ISSUE TITLE
Version mismatch in dashboard

### ISSUE THREAD

**Issue by anddam** [Tampermonkey/tampermonkey#748]
## Expected Behavior
After a sync via Google Drive that is bumping the version of an userscript already present, I expect the dashboard 'version' column to reflect the value contained in the script.

## Actual Behavior
The old version is displayed.

### System A
- Chrome 75.0.3770.144 
- TM: 4.8.41
- OS: Chrome OS 75.0.3770.144
### System B
- Chrome: 75.0.3770.142
- TM: 4.8.41
- OS: elementary OS 5.0 (Ubuntu 18 LTS)

## How to reproduce
1. Setup two browsers, A and B, to use Google Drive sync
1. Create an empty script on A, this script has `@version 0.1` and `@name New Userscript`
1. Click on `File > Save` in editor
1. On browser B click on the tampermonkey icon and choose `Check for userscript updates` from the popup menu
1. Refresh the dashboard, a script called `New Userscript` should appear, it has `0.1` in the versio column
1. On browser A edit the script and bump the version to `0.2`, then save
1. On browser B click `Check for userscript updates` menuitem again, the notification area will show "Narf! No update found, Sry!
1. Refresh the browser page, you may have to repeat these last two steps with a bit of delay, if the other sync had not finished already
1. After refresh the dashboard will show version `0.1` but clicking on the actual script will open the editor with `@version 0.2` in it

**Comment by derjanb** [comment]
Fixed at TM BETA 4.10.6106
