### ISSUE TITLE
[Firefox] Tampermonkey doesn't load my script sometimes.

### ISSUE THREAD

**Issue by GustavoRuedaEnriquez** [Tampermonkey/tampermonkey#750]
I have script that is injected to a web page using the Tampermonkey extension. 
The page should be loaded as usual, then the script is loaded in the site.

The script works perfectly fine and it loads correctly in Chrome, but sometimes while using Firefox, the script isn't loaded in the page and I need to refresh the page in order that the script could be loaded. Sometimes no reload is needed, sometimes you need to reload 1, 2 or 3 times.

I don't really know why this is happening, do you know if the extension has a issue with Firefox?
Please, I hope you could help me.

My web browser versions are:
- Firefox 68.0.1 (64-bit)
- Chrome 75.0.3770.142 (Official Build) (64 bits)

Sorry, I can't share the script, due to legal issues.

**Comment by FarisHijazi** [comment]
Hello,

There could be multiple reasons for this happening:
- issues with `@match` or `@include`
- issues with triggering the script, depending on when the script is injected (`@run-at `)

I've noticed this issue with Firefox at times, maybe the page didn't load entirely, the default for TamperMonkey is that it's injected on `document-idle`, try the following:

Add the following to the metadata block: `// @run-at   document-start`

Also, if you can't share the script, at least share the metadata block, this helps in resolving the issue

**Comment by GustavoRuedaEnriquez** [comment]
Sorry for the late response, I have tried adding the `@run-at document-start` but my script dies, I can share the meta data block, it is the following one:
`
// ==UserScript==
// @name        TIC Tool Community
// @namespace   [SERVER_URL_TOKEN]
// @author      TIC TEAM
// @description TIC Tool that helps to create cases in SFDC faster on the NXP community page
// @downloadURL [SERVER_URL_TOKEN]/[REPOSITORY_TOKEN]/userscripts/CommuniTICs.user.js
// @updateURL   [SERVER_URL_TOKEN]/[REPOSITORY_TOKEN]/userscripts/TicTool.meta.js
// @version     5.2.0
// @include		http://community.nxp.com/*
// @include		https://community.nxp.com/*
// @include		http://community-uat.nxp.com/*
// @include		https://community-uat.nxp.com/*
// @include		http://freescale.jiveon.com/*
// @include		https://freescale.jiveon.com/*
// @resource    min_app [SERVER_URL_TOKEN]/[REPOSITORY_TOKEN]/CommuniTICsApp/minFiles/app.min.js
// @grant       GM_getResourceText
// ==/UserScript==
`

**Comment by Martii** [comment]
@GustavoRuedaEnriquez 

Would you please edit [your post above](https://github.com/Tampermonkey/tampermonkey/issues/750#issuecomment-520901622) and use at least an unnamed [Code Fence](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks)? Very difficult to read since it's just in a code tag block.  Thanks.

**Comment by Ssieth** [comment]
I get exactly the same problem.  Sometimes tampermonkey in firefox runs my script and sometimes it doesn't.  When it doesn't run, it's still marked as active in the menu:

![2021-02-17 22_46_34-Window](https://user-images.githubusercontent.com/38430835/108277947-22dc3780-7172-11eb-81eb-334df667e0c8.png)

The header looks pretty normal(ish) and I've tried varying @run-at with no change in behaviour

```// ==UserScript==
// @name        Storium Improver
// @namespace   4faa34747d826bd32beeeaae92bffb79
// @description Storium Page Improvements
// @include     https://storium.com/*
// @resource	CSS_JUI https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css
// @resource	CSS_Icons https://fonts.googleapis.com/icon?family=Material+Icons
// @version     3.17.2
// @require     https://code.jquery.com/jquery-3.4.1.min.js
// @require     https://code.jquery.com/ui/1.12.1/jquery-ui.min.js
// @require		https://cabbit.org.uk/scripts/jquery.mark.min.js
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_addStyle
// @grant       GM_getResourceText
// @grant       GM_xmlhttpRequest
// @connect     cabbit.org.uk
// @oujs:author Ssieth
// @copyright   2019, Ssieth
// @license     GPL-3.0-or-later
// ==/UserScript==```

**Comment by yuezy3** [comment]
I get exactly the same problem.  You need to refresh page, or, you need to restart firefox.

**Comment by peterwx** [comment]
There's an API(only for Firefox) for registering userScripts that [Firemonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey) uses. Seems to be more robust, even when navigating to other pages from the one the script is initially loaded. Maybe you could give it a try with your scripts and see if it works there.

Does TM implement this API? If so how can it be applied by a regular TM user?

**Comment by derjanb** [comment]
Closing in favor of https://github.com/Tampermonkey/tampermonkey/issues/1016
