### ISSUE TITLE
Basic Script Fails on Twitter using Safari, possibly due to CSP

### ISSUE THREAD

**Issue by bengrosser** [Tampermonkey/tampermonkey#751]
(Please fill out the issue template with your details)

## Expected Behavior
I'm finding that TM scripts are no longer working on twitter.com in Safari. I tried a basic test script that only prints to the console to be sure (see below).

## Actual Behavior
But this will not run. Nothing prints to the console. The only message in the console that seems related is this: 

> Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

I tried TM 4.7. Note that I'm not having issues with other sites and other scripts on Safari, just Twitter.

Is there a workaround for this?

## Specifications

- Safari: 12.1 (14607.1.40.1.4)
- TM: 4.7
- OS: 10.14.4

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://twitter.com/home
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    console.log("hi");
})();
```

**Comment by Alien426** [comment]
Already described in #700.

**Comment by derjanb** [comment]
Please see https://github.com/Tampermonkey/tampermonkey/issues/296#issuecomment-222356524
