### ISSUE TITLE
???

### ISSUE THREAD

**Issue by EvaLynn420** [Tampermonkey/tampermonkey#753]
Exception: downloadManager.js加载失败
Script Ver: 0.1.7
TemperMonkey Ver: 4.8.41
UA: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by derjanb** [comment]
Tampermonkey doesn't include a file named "downloadManager.js". Please contact the script developers and they will come back to me if the problem is caused by Tampermonkey.
