### ISSUE TITLE
Unable to load local file in some browsers

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#754]
(Please fill out the issue template with your details)

## Expected Behavior
Reads the file content

## Actual Behavior
Not reads the file content. Console status:

Refused to connect to "c:\LOGFILE.TXT": URL is not permitted: URL can not be parsed

## Specifications

- Firefox 54.0.1 + Opera 62.0.3331.99
- OS: Windows 8.1 x64

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Test FileReader
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @match        https://*/*
// @connect      file://*
// @grant        GM_xmlhttpRequest
// ==/UserScript==

(function() {
  'use strict';

  var uri = new URL('C:\\LOGFILE.TXT');

  GM_xmlhttpRequest({
	method: 'GET',
	url: uri.href,
	responseType: 'arraybuffer',
	onload: function(response) {
	  console.log(response.responseText);
	}
  });
})();
```

Trying to use GM_xmlhttpRequest for loading local storage file content. Tested it in Chrome 75.0.3770.142; the callback was invoked with valid responseText content.
In Opera, the error above occurs just like with Firefox.
I wonder if I could do anything to make it process the URI encoded filepath.
If the local file storage access is part of security policy, what the heck is the point when I was able to read the desired file in Chrome? Here I'm looking for an makeshift which will enable me to read my file on *any* browser using TM. Thank you.

**Comment by derjanb** [comment]
Please contact Mozilla for Firefox local file access: https://bugzilla.mozilla.org/show_bug.cgi?id=1246236
:-)

Opera should work fine as well if the "Allow access to file URLs" option is enabled:
![image](https://user-images.githubusercontent.com/767504/63087892-83722f00-bf53-11e9-8300-d97f36e6a055.png)
