### ISSUE TITLE
[Service Workers] How early is document-start suppose to be?

### ISSUE THREAD

**Issue by bughit** [Tampermonkey/tampermonkey#756]
## Expected Behavior

The earliest theoretical point would seem to be just after the js environment for a page is created, before any parsing, dom creation or page  script execution. That's what I am looking for. Is that possible?

## Actual Behavior

a page head script runs before a document-start tampermonkey script

## Specifications

- Chromium: 76.0.3809.100
- TM: 4.8.41
- OS: win7

**Comment by derjanb** [comment]
With ["Instant" injection mode](https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595) your script should run before the page's scripts, but after the DOM being parsed.

**Comment by bughit** [comment]
@derjanb 

Thanks, will try, but inline scripts execute as the dom is being parsed and built, so how can anything run after dom and before page's scripts?

**Comment by bughit** [comment]
@derjanb 

That didn't work. I changed the inject mode to instant but my document-start script still ran after the first head script

**Comment by bughit** [comment]
@derjanb 

It looks to be service worker related.

The page in question is cached and load by a service worker. If I delete the service worker and reload, then the TM script runs first.

**Comment by derjanb** [comment]
Probably related: https://bugs.chromium.org/p/chromium/issues/detail?id=766433

I need to double-check this. Do you have an example how a page can be "cached and loaded by a service worker"?

**Comment by bughit** [comment]
[Microsoft Teams](https://teams.microsoft.com/_)

**Comment by bughit** [comment]
by the way, when exactly is the default (non-instant) `document-start`?

Is it after head scripts?

Is it deterministic ("as fast as possible" is pretty vague)?

If it is, then instant (with a possibly clearer name) should become another `@run-at` value, because "before any content code" is a useful injection point.

If no, then instant should be default for `document-start` because a non-deterministic injection point is pretty useless.

**Comment by tophf** [comment]
The thing is, in Chrome there's no 100% deterministic document-start at all because there are exceptions that cannot be solved by extension API like e.g. pages that load so quickly that it occurs before the webRequest listener even triggered.
