### ISSUE TITLE
Improve documentation of GM_getTab, GM_getTabs.

### ISSUE THREAD

**Issue by kbauer** [Tampermonkey/tampermonkey#757]
It would help greatly, if the argument were simply called "callback" rather than "cb" in the documentation. Being not a webdeveloper, but rather an occasional scripter only, it wasn't clear to me what "cb" means, until I came across [How does GM_getTab(cb) work? (stackexchange)](https://stackoverflow.com/questions/25793331/how-does-gm-gettabcb-work).

New users especially may come to TamperMonkey with relatively little javascript experience and may not be aware of the ubiquity of callbacks and abstractions like promises and async functions.

**Comment by derjanb** [comment]
Fixed. :)
