### ISSUE TITLE
Manually Triggering a Sync?

### ISSUE THREAD

**Issue by jdtechsol** [Tampermonkey/tampermonkey#759]
- Chromium: Chrome Browser, 76.0.3809.132 (Official Build) (64-bit)
- TM: 4.8.41
- OS: Win 10 Pro x64

Please forgive me as I am sure this has been asked about, but I am a bit annoyed at the moment so my search for this was quite brief. I also tried to find a discussion method on here but "issues" seems to be the only way to communicate.  

The ability to manually initiate a sync to cloud (via a menu item in either the editor or from the main menu) seems to be non-existent. While it is understood that this is an automatic process, the delay for syncing is annoyingly long. I get why it might be designed in such a way that it does not sync immediately, but after completing the processes of editing, saving, closing the editor, reloading the page which uses said-script, and the script runs with no issues... shouldn't it then sync the script? But that is all really beside the point. I feel that there should be an in-editor menu item that syncs the script. 

For now, does anyone know if a command exists which manually triggers the sync? (i.e. a command that can be typed into chrome's dev console which is attached to the editor's chrome tab)

Thanks

**Comment by derjanb** [comment]
You can simply use the "Check for userscripts updates" menu item. It will trigger a sync first.
