### ISSUE TITLE
No   "New Userscript" in menu. Where?

### ISSUE THREAD

**Issue by selevo** [Tampermonkey/tampermonkey#760]
![ScreenShot000669](https://user-images.githubusercontent.com/13694921/64076935-2d83e200-ccdc-11e9-8a3e-5047ced9fe36.jpg)

It's  a russian version, in english   too.
![ScreenShot000673](https://user-images.githubusercontent.com/13694921/64098682-8e60f800-cd78-11e9-88c5-7137442047ca.jpg)

- Chrom: (76.0.3809.132 x64 )
- TM: (v4.8.41 by Jan Biniok)
- OS: (win 7x64)

**Comment by Martii** [comment]
@selevo 

> No "New Userscript" in menu. Where?

Select Dashboard *(⚙)* then the plus *(＋)* symbol in the tab bar to create a "New userscript".

**Comment by selevo** [comment]
> @selevo
> 
> > No "New Userscript" in menu. Where?
> 
> Select Dashboard _(⚙)_ then the plus _(＋)_ symbol in the tab bar to create a "New userscript".

I need, as before, with a menu item, so that the page address is automatically added to the script.
If I create a new script from the toolbar, I will have to write with my hands.

**Comment by Martii** [comment]
> I need, as before, with a menu item

That's not what you asked... however...

> so that the page address is automatically added to the script.

This might be a nice feature to have in TM, if possible. 

I would ask for a feature request with this in mind rather than asking where is the new userscript. :smile_cat:

**Comment by derjanb** [comment]
You can set "General > Config Mode" to "Advanced" and then "Action Menu > Columns" to 2 (or 3) and the "Create a new script" menu item will always be visible adn insert the current URL into the new script template.

**Comment by Martii** [comment]
Think it's only in 3 columns here... I'm rarely out of column 1 but just tried 2 and it's not there.

**Comment by derjanb** [comment]
@Martii Yes, you're right.

**Comment by selevo** [comment]
Previously, this menu item was, after the update, the version disappeared.
I always used this without thinking about copying the paste URL to // @match        https://www.kukareku.mu/

Now more unnecessary work, more mouse clicks, more button presses, less time to live.

**Comment by selevo** [comment]
> You can set "General > Config Mode" to "Advanced" and then "Action Menu > Columns" to 3 and the "Create a new script" menu item will always be visible adn insert the current URL into the new script template.

The menu has become not very beautiful but it is a solution.
Thank.
