### ISSUE TITLE
[Chrome] Script editor disappears / is way to large / scrolls the complete page

### ISSUE THREAD

**Issue by selevo** [Tampermonkey/tampermonkey#762]
![2019-09-13~17_56_56]
understanding gif video >> https://user-images.githubusercontent.com/13694921/64868343-2fd92b00-d650-11e9-8f57-6462e54d8eff.gif

- Chrome (76.0.3809.132 x64)
- TM: (i.e. 4.8.41)
- OS: (win 7x64)

**Comment by rundamnyou** [comment]
Having the same issue.
Chrome 77.0.3865.75 (Official Build) (64-bit)
TM 4.8.41
Windows 10

Mostly happens when scrolling but sometimes clicking inside the editor sets it off. Pulling up the browser's console can bring it back most of the time but it's half the normal size.

**Comment by derjanb** [comment]
Already fixed at TM BETA, but not released yet, because the last release is in "Pending review" state since more than a week. 😢

However, you can workaround this issue by setting "Config Mode" to "Advanced" and past this at the "Custom CSS" option:

```css
.editor_100 {
     height: unset !important;
}
```
![image](https://user-images.githubusercontent.com/767504/64882033-85b3d000-d65c-11e9-98da-d93b95c6f9fc.png)

**Comment by wefalltomorrow** [comment]
> Already fixed at TM BETA, but not released yet, because the last release is in "Pending review" state since more than a week. 😢
> 
> However, you can workaround this issue by setting "Config Mode" to "Advanced" and insert this at the "Custom CSS" option:
> 
> ```css
> .editor_100 {
>      height: unset !important;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/767504/64882033-85b3d000-d65c-11e9-98da-d93b95c6f9fc.png)

Thanks for the fix!

**Comment by raszpl** [comment]
I was beginning to think Im going crazy. It was happening to me only on the first time I opened big scripts, but reloading the tab somehow fixed it. Custom layout css fixes it permanently, thanks.

**Comment by derjanb** [comment]
Sorry for the delay. Fixed at the beta version a month again, but review took that long. 😮
