### ISSUE TITLE
Autoupdating ?????? pls help me

### ISSUE THREAD

**Issue by ZeWhiteHatHacker** [Tampermonkey/tampermonkey#763]
(Please fill out the issue template with your details)

## Specifications

- Chromium: 76.0.3809.132
- TM: I dont know
- OS: Windows 10 Pro Latest update 64 bit 8GB ram powerfull pc

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Krunker.io Hacks for SEPTEMBER | Actually working
// @description  Tutorial out @ https://cutit.org/GoBayMax
// @version      1.2.3
// @author       BayMax
// @namespace    BayMax
// @updateURL    https://github.com/ZeWhiteHatHacker/new_krunker_hack_sept/raw/master/krunkerhack.user.js
// @downloadURL  https://github.com/ZeWhiteHatHacker/new_krunker_hack_sept/raw/master/krunkerhack.user.js
// @match        *://krunker.io/*
// @grant        none
// @run-at       document-start
```

**Comment by derjanb** [comment]
The default script update check interval is one day. You can configure this after setting "Config Mode" to "Advacned".

**Comment by ZeWhiteHatHacker** [comment]
Thank you bro if I change that will every user of my script need to tho?

**Comment by Martii** [comment]
@ZeWhiteHatHacker 

> ... and I have just made chanegs and 5 mins later nothing on tampermonkey.

GitHub also has a DoS prevention cache mechanism built in. i.e. they cache the latest changed version when it is served. If you make too many commits rapidly no .user.js engine manager will ever get the updates until that period has expired.

**Comment by mqliutie** [comment]
I uploaded my update script and changed the script in tampermokey. I pasted the update url in chrome why tampermonkey can not know my tampermonkey script should update?

**Comment by derjanb** [comment]
Updates work the other way around, they are pulled from the update URL.
