### ISSUE TITLE
ES5 Warning on Multi-line Strings

### ISSUE THREAD

**Issue by ameer1234567890** [Tampermonkey/tampermonkey#764]
Despite `es5 : true` option in jslint, it does not honor multi-line strings and emits a warning.

**Comment by derjanb** [comment]
Can you please tell me you Tampermonkey and browser version? Thanks.

**Comment by derjanb** [comment]
Nevermind, this is working fine here using no config or 
```JSON
{
    "parserOptions": {
        "ecmaVersion": 6
    }
}
```

See https://eslint.org/docs/user-guide/configuring for more details.

**Comment by ameer1234567890** [comment]
Gives out warning with no config. When I enter this config under `Custom Linter Config`, it gives no more warning.

**Comment by derjanb** [comment]
> Gives out warning with no config

Oh, what is your browser version?

**Comment by ameer1234567890** [comment]
Google Chrome latest.
