### ISSUE TITLE
[Safari] Tampermonkey not found in App Store/automatically removed with Safari update

### ISSUE THREAD

**Issue by murphysm2342** [Tampermonkey/tampermonkey#765]
#584  Expected Behavior
Trying to install Tampermonkey from the TM website on Safari browser and the URL provided now opens Apple's AppStore but TM  is not found.  Doing a search for TM ends in zero results.  I noticed in a recent changeling that the Apple Dev Certificate had been renewed.  Might this be connected with it not showing in the App Store?

To make things worse, I just installed a Safari update (Version 13.0 (14608.1.49)) on a different computer, which had been running TM successfully, and this update automatically removed the TM extension.  Screen shot of dialog showing that TM had been removed:
https://s3.amazonaws.com/commonuse/External%20Send%20Files/Monosnap%202019-09-19%2013-24-37.jpg 

## Specifications

13.4). Mac OS 10.13.6 and Mac OS 10.14.6

**Comment by Martii** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-506836395
