### ISSUE TITLE
Safari third Extensions

### ISSUE THREAD

**Issue by LoveJessyChen** [Tampermonkey/tampermonkey#770]
## About Safari third Extensions

Hello，tampermonkey developers,
You can creat a Applications to install the Safari Extensions For mac Safari 13 and above,（ even in 12.1.x）.
In the future , the users can't install tampermonkey with Show Extension Builder （扩展构建器）in 10.15 or above and url “safari-extensions.apple.com/details/?id=*”，apple will be disabled in macOS 10.14.5，15 or above.

## Specifications

- Safari 12.1.2
- TM: 14607.3.9
- OS: MacOS 10.14.6 (18G103)

**Comment by derjanb** [comment]
Duplicate of #558
