### ISSUE TITLE
[Chrome ] GM_setClipboard not working 

### ISSUE THREAD

**Issue by Vegeta780** [Tampermonkey/tampermonkey#771]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @include https://mywebsite.com/*
// @require      https://code.jquery.com/jquery-2.1.4.min.js
// @grant        GM_setClipboard
// ==/UserScript==
```
(function() {

var txt = document.body.innerHTML;
var x= txt.indexOf("www.blalas.com", 12);

    var res = txt.slice(x,x+28);
var aa = res;
GM_setClipboard(aa);
  alert("Copied " + aa);

})();

when i crl + v didnot  copy

**Comment by derjanb** [comment]
GM_setClipboard is working fine here. Please tell me your Tampermonkey, Chrome and OS version.

**Comment by Vegeta780** [comment]
one eternity later , i received  message hahaahaha Thats sucks ( i solved that script in half day)
  i creates many  scripts Long live  tampermonkey
