### ISSUE TITLE
[Firefox] Script is never run on pages with a caching service worker

### ISSUE THREAD

**Issue by gsz** [Tampermonkey/tampermonkey#773]
In an attempt to track down why a userscript wasn't working on a certain website (devdocs.io), I wrote a very simple test script and set it up to run on every page. It works everywhere except on devdocs.io. The problem didn't occur on Chromium.

Edit: ok, this is a content security policy thing.There are errors in the console:

Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

I assumed they are unrelated because they kept showing up even when I disabled Tampermonkey in the toolbar, but turns out you have to disable it completely in the add-on settings and then they go away.

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http*://*/*
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';
    console.log('Test script running.');
})();
```
## Expected Behavior

The message "Test script running." should be printed to the console immediately after loading or reloading a page.

## Actual Behavior

It does exactly what it's supposed to do on pages that aren't devdocs.io. On that page, things get weird. No message shows up in the console, but Tampermonkey still shows the script as active by displaying it in the context menu and displaying the red badge with a number.

In fact, the number displayed in the badge keeps increasing every time I reload the page (the same number can be obtained by hovering over the script name in the context menu until "This script was executed N time(s)" message pops up). This is different from trying it on other pages, where the number stays at one after successive reloads.

## Specifications

- Firefox: 69.0
- TM: 4.9.5941 (freshly re-installed)
- OS: Ubuntu 18.04.3

**Comment by derjanb** [comment]
Workaround for the moment: 

* go to `about:config` 
* search `dom.caches.enabled` and 
* set it to `false`. 

Note: you might also need to unregister the service worker at `about:debugging#/runtime/this-firefox`.

**Comment by alexolog** [comment]
Mozilla wants to remove that option as per https://bugzilla.mozilla.org/show_bug.cgi?id=1177968
@derjanb, could you please comment on that bug?  I don't have the expertise to explain what the problem is.  Thanks!

**Comment by alexolog** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1643405 for this issue.
Please comment on it.

**Comment by derjanb** [comment]
I've added a workaround to 4.11.6114 :-)
