### ISSUE TITLE
No scripts apply when restarting FF

### ISSUE THREAD

**Issue by Pugnatrix** [Tampermonkey/tampermonkey#774]
Hello,

I am using Tampermonkey on Firefox and the scripts I install work perfectly fine when I first install them but after I restart Firefox, they stop working. The scripts still say they have been executed on the sites but nothing happens. Is it because I am running userchrome.css?

Thank you.

**Comment by Pugnatrix** [comment]
It is NOT because of userchrome.css. I just tested it with userchrome.css disabled and the same problem persists.

**Comment by Pugnatrix** [comment]
It seems to have been purely a tampermonkey problem. I reproduced the situtation with greasemonkey and everything is running smoothly.

**Comment by derjanb** [comment]
Can you please tell me your Firefox, OS and Tampermonkey version?

**Comment by Pugnatrix** [comment]
Firefox 69.0.3
Windows 10 Pro Version 1809
I have uninstalled tampermonkey but I was using the latest one at the time of the original post.
