### ISSUE TITLE
TM Beta is outdated in CWS

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#775]
[4.9.6004](https://www.tampermonkey.net/changelog.php?ext=dhdg&show=gcal) was released 2019-09-16 and still not availible in Chrome Web Store.
1. What is the reason? Was the new version rejected?
2. Is TM available elsewhere for manual installation?

## Specifications

- Chromium: 77.0.3865.120
- TM: Beta
- OS: Windows 10

**Comment by derjanb** [comment]
Simeon Vincent from Google is already double-checking why it takes that long...

You can download the version from here: https://test.tampermonkey.net/versions/beta/ae48f293a/beta_4.9.5971.crx
and then drag and drop it to the extensions page chrome://extensions

**Comment by mikhaelkh** [comment]
@derjanb you gave a link for 5971 which is available in CWS.

**Comment by mikhaelkh** [comment]
@derjanb you gave a link to 5971 which is available in CWS.

**Comment by derjanb** [comment]
Yes, that is the latest version signed by CWS that I have. I can not upload new versions until the extension is reviewed. 😭

**Comment by derjanb** [comment]
Fixed for now. Unfortunately after updating TM BETA it now requires review again. 😮
