### ISSUE TITLE
Make File section import accept plain text userscripts

### ISSUE THREAD

**Issue by LWChris** [Tampermonkey/tampermonkey#777]
I wrote a script in Tampermonkey and it works. Then I exported it, and now, when I try to re-import it, it just says "Unable to parse this". Since I exported a **working** script literally just 10 seconds earlier from the very same machine (I am just testing whether colleagues could now install the script), I don't know what I am supposed to do to fix it.

I think this is general import problem, because I cannot even import the unchanged blank template that TM pre-generates.

## Expected Behavior
Give me some indication on whether it detected an unknown header line or thinks the script is missing a bracket or what else the problem is.

## Actual Behavior
Just says "Unable to parse this" and that's it.

## Specifications

- Vivaldi: 2.5.1525.48 (I _think_ that is Chromium 74.0.3729.172 according to UA)
- TM: 4.8.41
- OS: Windows 10 Pro 64-bit

## Script
I took a copy of my script and delete more and more until meanwhile I think the import process in general is busted. I can reproduce the error 10/10 with the blank template:

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        <any URL here>
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```

**Comment by derjanb** [comment]
Can't find a trustworthy location from where I can get your Vivaldi version, however import and export is working find here with Windows 10 and Vivaldi 2.2.1388.37 as well as 2.9.1705.34.

Are you sure you're using the correct file type for the corresponding import/export section (plain text file vs. zip file?)

**Comment by LWChris** [comment]
I have just updated to the latest Vivaldi version, that is "2.9.1705.34 (Stable channel) (32-Bit)", which should be equivalent to "Chrome 78.0.3904.72" according to the UA.

My UI language is actually German, maybe that's a thing?

I am installing this way:
* Tampermonkey icon
* Overview (cog icon)
* Utils tab (left of Help tab)
* File section (not Cloud, Zip, URL)
* I select a file at `C:\Users\Christoph\mytest.user.js`
* The file content (encoded in UTF-8 without Byte Order Mark):
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      1
// @description  try to take over the world!
// @author       You
// @match        https://www.google.de
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
})();
```

So no `@version 0.1` that could mess up with the decimal separator. The file path has no spaces in it. It doesn't have much code. I don't think there's much more to strip to remove more potential sources of error.

When I select the file, I see the UI popup "Please wait" with the two rings of four blue quarter circles rotating, and immediately a JavaScript alert message that says "Falsche Syntax :(" which according to the repository should be the error message for `Unable_to_parse_this_`.

There's one thing I noticed that I don't understand: the message says "Falsche **S**yntax :(" (uppercase s) when the resources say ["Falsche **s**yntax :("](https://github.com/Tampermonkey/tampermonkey/blob/master/i18n/de/messages.json#L354) (lowercase s). No idea how this comes about.

**Comment by dineshrathee12** [comment]
I faced this issue as well...

    Tampermonkey Unable to parse this! :(

**What Action I took to solve this :**
> I had one **large** Zip file , Divided it into **3 small chunks** and imported and it again 3 times one by one (chunk wise chunk) and it was successful.

***- Pathetic experience with tampermonkey  always in Import/Export***
