### ISSUE TITLE
[Safari] Toolbar icon rendered wrongly

### ISSUE THREAD

**Issue by dionisokan** [Tampermonkey/tampermonkey#779]
## Expected Behavior
Tampermonkey toolbar icon in Safari 13 should be rendered correctly just as it was in Safari 6-12.

## Actual Behavior
The icon is rendered in a mistaken way, much more slim than it should be:
<img width="53" alt="image" src="https://user-images.githubusercontent.com/19278941/66900836-1b61c700-f030-11e9-8753-c71286816c4a.png">

## Specifications
- Safari: Version 13.0.2 (15608.2.30.1.1)
- TM: 4.9.6037 (MAS Version)
- OS: macOS 10.15 (19A602)

## Notes
Tried uninstall and re-install Tampermonkey MAS version, yet nothing changes.

**Comment by derjanb** [comment]
Probably a HiDPI/Retina related problem? I need to get a macOS running at a retina display first...

**Comment by Chandler-Lu** [comment]
> Probably a HiDPI/Retina related problem? I need to get a macOS running at a retina display first...

In 2015early MacbookAir（No Retina, macOS 10.15, safari 13.0.2）, the icon also display in a mistaken way.
![截屏2019-10-1709 33 57](https://user-images.githubusercontent.com/18322610/66970870-83acb900-f0c1-11e9-81eb-672455564d75.png)

**Comment by cylott** [comment]
Me too

**Comment by zj299792458** [comment]
me too, twisted icon XD

**Comment by YuntianCheng** [comment]
Same here

**Comment by gabrielferrari714** [comment]
me too, macbook air 2015, Original display and second display.
the toolbar looks the same way. see this photo. ↓ 
![Captura de Tela 2019-10-17 às 13 15 26](https://user-images.githubusercontent.com/20546781/67027662-54597480-f0e0-11e9-848a-0d54c2787a9c.png)

**Comment by gabrielferrari714** [comment]
me too, macbook air 2015.
Same problem in Original display and second display (monitor ultrawide displayport).
the toolbar looks the same way. see this photo. ↓
![Captura de Tela 2019-10-17 às 13 15 26](https://user-images.githubusercontent.com/20546781/67027859-b2865780-f0e0-11e9-9bca-ecc532896c20.png)

**Comment by derjanb** [comment]
I was able to persuade my virtual machine to install macOS 10.15 to reproduce the issue. 🤓
Fixed at 4.9.6055 which was reviewed some minutes ago. 😅

**Comment by gabrielferrari714** [comment]
yeah! works perfectly right now. Thank you, Jan..
Live long and prosper. 🖖🏼
