### ISSUE TITLE
Popup bug

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#781]
Chromium 74.0.3729.169
TM beta 4.9.6045
Win 8.1

For a split second, when the popup opens, sometimes it's flashing 100% of the popup's available height, even though the content is much shorter. This occurs randomly, but frequently. Definitely due to the last update, because I was already editing scripts, then got the update message, restarted the browser and started noticing it directly after.

[Screen record](https://streamable.com/tkc4q)

**Comment by derjanb** [comment]
Fixed at 4.9.6055
