### ISSUE TITLE
No save notification

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#782]
Chromium 74.0.3729.169
TM beta 4.9.6045
Win 8.1

Title's pretty self explanatory. It's a little unsettling without the visual verification, particularly since TM doesn't require a confirmation before closing a tab with unsaved changes, which is also unfortunate.

**Comment by derjanb** [comment]
Fixed at 4.9.6055

**Comment by derjanb** [comment]
>  particularly since TM doesn't require a confirmation before closing a tab with unsaved changes, which is also unfortunate.

Fixed at 4.9.6055 as well. Thanks for the suggestion.
