### ISSUE TITLE
Minor suggestion: Use stroked version of icon as favicon

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Tampermonkey/tampermonkey#784]
I like beta testing TM, but the recent bugs really affect usability, and I've been editing a lot lately, so I switched to stable. The stroked icon is cool for dark browser themes, and should really be used as the favicon as well IMO.

![TM icon](https://user-images.githubusercontent.com/14100003/67114856-d6ae6b00-f1aa-11e9-8e5a-29c5967587fc.png)

**Comment by derjanb** [comment]
Fixed. :)
