### ISSUE TITLE
After new updates script DONT WORKING FROM SIDE VOD.PL

### ISSUE THREAD

**Issue by Zbyszek40** [Tampermonkey/tampermonkey#785]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Can not reproduce. Please add more details.

![image](https://user-images.githubusercontent.com/767504/68070767-ed3fef00-fd72-11e9-96f7-360ec8618630.png)
