### ISSUE TITLE
[Safari] Tampermonkey Extension won't update to new version

### ISSUE THREAD

**Issue by Juicy0Steak** [Tampermonkey/tampermonkey#787]
## Expected Behavior
The application should be on the newest standard after starting the process of updating via the Mac app store. After the update the blue button on the App's page should turn from "update" into "open".

## Actual Behavior
The download bar shows the progress, then indicates that it was downloaded (bar is full and Launch-icon in bar "jumps"), but in the App Store the "update" button is visible again. Clicking it again repeats this process.

## Specifications

- Safari: Version 13.0.2 (15608.2.30.1.1)
- TM: 4.9.6037
- OS: MacOS 10.15

## Script

No special script

**Comment by derjanb** [comment]
There is nothing I can do. It all depends on Apple's cloud. 

Some useful hints though:
https://apple.stackexchange.com/questions/345857/mac-app-store-downloads-just-dont-start-mojave

**Comment by tianshilei1992** [comment]
You could goto `$TMPDIR/../C/com.apple.appstore` and find the right one. One good way is to remove everything in `$TMPDIR/../C/com.apple.appstore` and then click Update button. The only folder in `$TMPDIR/../C/com.apple.appstore` like `2D15B9C4-.....` is the one contains `.pkg` file for Tampermonkey. Then you could install it manually.

**Comment by Juicy0Steak** [comment]
Reinstalling it seemed to fix it (for now)

**Comment by Ekonoms** [comment]
Updating Tampermonkey while Safari is closed fixed this for me.

**Comment by LoveJessyChen** [comment]
It is too expensive to install TamperMonkey from App Store.

**Comment by LoveJessyChen** [comment]
I will turn to chrome to use Tampermonkey.

**Comment by denverbee** [comment]
> Updating Tampermonkey while Safari is closed fixed this for me.

thank you Ekonoms, why didn't I think of that

**Comment by derjanb** [comment]
> Updating Tampermonkey while Safari is closed fixed this for me.

@Ekonoms Yes, this fixes the issue. Thanks for pointing this out.
