### ISSUE TITLE
[Safari] Script does not install within Tampermonkey, but downloads .js file instead

### ISSUE THREAD

**Issue by Juicy0Steak** [Tampermonkey/tampermonkey#788]
## Expected Behavior
After clicking "click here" [on this page](https://github.com/rafaelgssa/esgst/tree/master/browser) (See at Installation > Option 2), the Tampermonkey page should show up to install the script, like it does with any other script from GitHub.

## Actual Behavior
After clicking "click here" on the page above, Safari downloads the script's .js file instead, without redirecting to the Tampermonkey install page. I believe however, that the script worked in the old Tampermonkey Safari versions like it should do.

## Specifications

Safari: Version 13.0.2 (15608.2.30.1.1)
TM: 4.9.6055
OS: MacOS 10.15

## Script

// ==UserScript==
// @name Enhanced SteamGifts & SteamTrades (ESGST)
// @namespace ESGST
// @description Enhances SteamGifts and SteamTrades by adding some cool features to them.
// @icon https://github.com/rafaelgssa/esgst/raw/master/browser/src/assets/images/icon.png
// @version 8.5.8
// @author rafaelgssa
// @contributor Royalgamer06
// @updateURL https://github.com/rafaelgssa/esgst/releases/latest/download/userscript.meta.js
// @downloadURL https://github.com/rafaelgssa/esgst/releases/latest/download/userscript.user.js
// @match https://www.steamgifts.com/*
// @match https://www.steamtrades.com/*
// @match https://www.sgtools.info/*
// @connect steamtrades.com
// @connect steamgifts.com
// @connect sgtools.info
// @connect api.dropboxapi.com
// @connect api.imgur.com
// @connect api.steampowered.com
// @connect content.dropboxapi.com
// @connect files.1drv.com
// @connect googleapis.com
// @connect graph.microsoft.com
// @connect rafaelgssa.com
// @connect isthereanydeal.com
// @connect raw.githubusercontent.com
// @connect revadike.ga
// @connect script.google.com
// @connect script.googleusercontent.com
// @connect steam-tracker.com
// @connect steamcommunity.com
// @connect store.steampowered.com
// @connect userstyles.org
// @grant GM_addValueChangeListener
// @grant GM_deleteValue
// @grant GM_getValue
// @grant GM_info
// @grant GM_listValues
// @grant GM_setValue
// @grant GM_xmlhttpRequest
// @grant GM.addValueChangeListener
// @grant GM.deleteValue
// @grant GM.getValue
// @grant GM.info
// @grant GM.listValues
// @grant GM.setValue
// @grant GM.xmlHttpRequest
// @run-at document-start
// @noframes
// ==/UserScript==
```

**Comment by derjanb** [comment]
Hm, it not working with Tampermonkey and Chrome here either. I'll check what's going on.

**Comment by Procyon-b** [comment]
I have a weird behavior with this one.
I'm on an old laptop (2GB) win7, old chrome version, TM 4.8.41.

When I click "click here" chrome takes 3-4s to open a new tab "UserScript installation" (TM page). But the page is completely blank for about 15s when parts of the form appear. Then another 4-5s before the page display seems complete. And another 4s, when the tab is closed and chrome asks me if I want to keep the file ("...can harm your computer...").

The userscript file is quite big: 2.5Mb

This computer is not slow, but slow enough. Maybe this is the reason I experience this.
Or maybe it's the chrome version.

**Comment by derjanb** [comment]
The problem, at least in my case, is that the resource from

> After clicking "click here" on this page (See at Installation > Option 2)

loads extremely slow while all other things load fast as usual. This triggers Tampermonkey's 60 seconds timeout for source code retrieval.

**Comment by Procyon-b** [comment]
It looks like this to me too.
Except that it takes 33 seconds from the click on the link, to the tab closing and chrome asking me if I want to keep the file.
