### ISSUE TITLE
not working on twitter using Firefox for Android

### ISSUE THREAD

**Issue by zeus81** [Tampermonkey/tampermonkey#790]
I use Firefox Nightly (68.2a1) on Android 9 (Lineage OS 16.0) and I have Tampermonkey (4.9.5941) with some userscripts that won't trigger on twitter.
You can try a simple script like alert(0), it will print the message on any website but twitter (when logged in with the new design at least, I don't know with the old one).

**Comment by derjanb** [comment]
Everything is working fine here with 68.10.1. Do you still see this issue?

**Comment by zeus81** [comment]
No, the issue is gone.
