### ISSUE TITLE
[Safari] Dashboard favicon is low resolution

### ISSUE THREAD

**Issue by Daniele** [Tampermonkey/tampermonkey#791]
Since the new application-based MacOS version was released, the dashboard favicon's resolution has worsened. I think the favicon gets loaded from here: https://ui.tampermonkey.net/options.html

## Expected Behavior
Favicon is high-resolution and crisp, just like the toolbar icon  <img width="31" alt="Screen Shot 2019-10-22 at 22 37 01" src="https://user-images.githubusercontent.com/52667/67330322-786fe800-f51c-11e9-9801-d607576c6186.png">

## Actual Behavior
Favicon is low-resolution and pixelated, looks pretty bad in my tabs  <img width="25" alt="Screen Shot 2019-10-22 at 22 37 56" src="https://user-images.githubusercontent.com/52667/67330419-989fa700-f51c-11e9-9871-db560e2f6287.png">

## Specifications
- Browser: Safari 13.0.2
- OS: MacOS 10.14.6

**Comment by derjanb** [comment]
This should be better now, right? It's still a sticker effect icon, but with a higher resolution.

**Comment by Daniele** [comment]
Yes it's much better, thank you 🙂
