### ISSUE TITLE
This extension cannot change the response header (Content-Security-Policy)

### ISSUE THREAD

**Issue by repna99** [Tampermonkey/tampermonkey#795]
(Please fill out the issue template with your details)

## Expected Behavior
no yellow circle icons, both working

## Actual Behavior
Open(any): https://github.com/Tampermonkey/tampermonkey/issues

yellow circle icon with an exclamation mark, after the extension panel, Replaces the button "main chrome menu button" (...)

in "chrome://extensions/" tampermonkey side message:
"Attention!
This extension cannot change the response header (Content-Security-Policy) due to a conflict with another extension (WebAPI Manager)."

## Specifications

- Chromium
- TM: 4.8.41
- OS: windows 7

WebAPI Manager 0.9.27 (recently was in store)
Any blocking rule: "Hardware: Battery Status API"
https://www.crx4chrome.com/extensions/hojoljbhkebfjalcbnfmoiljfidcmcmj/

Tampermonkey: any working script:
https://greasyfork.org/ru/scripts/22667-direct-links

**Comment by derjanb** [comment]
See https://github.com/Tampermonkey/tampermonkey/issues/353#issuecomment-278456508 for more information.
