### ISSUE TITLE
[Firefox] Broken dashboard refresh

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#797]
1. Open TM Settings
2. Change config mode

## Expected Behavior
New config mode is shown.

## Actual Behavior
Old config mode is shown.
After page refresh via F5 new config mode is shown.

## Specifications

- Firefox 71.0b5 (64-bit)
- TM: 4.9.6055 beta
- OS: Windows 10 v1607

**Comment by derjanb** [comment]
Nice find! Thanks for reporting.
