### ISSUE TITLE
[Safari] Factory Reset Does Not Work

### ISSUE THREAD

**Issue by jamesg311** [Tampermonkey/tampermonkey#798]
## Expected Behavior
I click "Factory Reset" button and it completely blasts all of Tampermonkey's settings

## Actual Behavior
It does not work. It reloads the Admin UI page but all scripts and settings remain in tact.

## Specifications
macOS 10.14.6
Safari 13.0.3
Tampermonkey: 4.9.6055

## Script

[All]

**Comment by jamesg311** [comment]
So I can move forward with my testing, where are Tampermonkey's preferences located so I can wipe them?

**Comment by derjanb** [comment]
Fixed at 4.9.6079
