### ISSUE TITLE
Userscripts icons are not cached

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#799]
## Expected Behavior
`@icon` is cached like other externals

## Actual Behavior
`@icon` is fetched every time Dashboard is opened

## Specifications

- Firefox 71.0b6 (64-bit)
- TM: 4.9.6055 beta
- OS: Windows 10 v1607 x64

## Script
https://greasyfork.org/scripts/388733

**Comment by derjanb** [comment]
Interesting thought.
