### ISSUE TITLE
[Safari] Any way to access old userscripts after updating to safari 13?

### ISSUE THREAD

**Issue by Boelensman1** [Tampermonkey/tampermonkey#802]
After updating to safari 13 I can't seem to find where my old user scripts went.

I looked in:
~/Library/Preferences/com.apple.Safari.Extensions.plist (does not exist)
~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.Extensions.plist (does not list Tampermonkey)

I had some, quite extensive user scripts, it's quite important for me to recover these. Did apple just delete them or is there a space where they are still stored?

**Comment by derjanb** [comment]
There is no way for Tampermonkey to access them. But you can find them here:
`~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.Extensions.plist`

See https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-542346885
