### ISSUE TITLE
Sometimes won't save cookies

### ISSUE THREAD

**Issue by SneakerRat73** [Tampermonkey/tampermonkey#803]
**I'm not filling this out per the suggested layout because I literally have zero computer knowledge and I'm not going to act like I'm confident in what I'm talking about. I don't really feel qualified to report this potential bug, but, since I was prompted with a pop-up referring to bug reporting, I decided to give it a try.

As far as I know, this script (I pasted the link below) simply collects cookies from a specified list of websites. These cookies can be saved and then imported into software for later use. However, I've recently been experiencing an issue when I hit save and it does nothing. Recently, I literally spent and hour or two trying to save, waiting a little while in between attempts. I've also tried: refreshing the page and reattempting to save; disabling tampermonkey/script, refreshing the page, re-enabling tampermonkey/script and reattempting to save--and that never worked.

When this happens, the only way I'm able to save is if I spam-click the page until I get "Access Denied." Once, I get the white screen/Access Denied, it saves on the very first click, like it's supposed to. I would assume it's something that I'm doing wrong, except I've seen others user report the same issue off and on.

In the recent past, I've successfully used this a TON without a single hiccup. On the slight chance this issue has anything to do with Tampermonkey, I just thought I'd report it! Even with the issue, this combo is still amazing!!! Thank you!!!!

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
https://destroyerbots.github.io/cookie-destroyer/cookies.user.js

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Is this still an issue? If so can you please explain this a little bit more in detail, maybe add screenshots? Thanks.
