### ISSUE TITLE
[Firefox] Some pages do not display the management menu

### ISSUE THREAD

**Issue by g1thub-h** [Tampermonkey/tampermonkey#809]
As shown in the figure
![图片](https://user-images.githubusercontent.com/49114731/68855838-1751c380-071a-11ea-9170-494092aab0be.png)
Some pages do not display the management menu, and some pages can display

If so, please explain to me what information you need to provide

The script runs normally, but the management interface is not displayed

- Chromium: Firefox (70.0.1 (64 位))
- TM: 4.9.6091
- OS: Windows 10

**Comment by g1thub-h** [comment]
If so, please explain to me what information you need to provide

**Comment by g1thub-h** [comment]
The script runs normally, but the management interface is not displayed

**Comment by derjanb** [comment]
Can you please tell me a URL where this happens (it would be great if that site is accessible without login) and the scripts that are running at that page. (You can open the options page, open the Scripts tab, press Control+F and paste the URL from the tab where the issue happens to filter the script list).

**Comment by g1thub-h** [comment]
https://fanyi.baidu.com/
![图片](https://user-images.githubusercontent.com/49114731/68858459-0dcb5a00-0720-11ea-98d4-8f6ab996caef.png)
https://www.taobao.com/
![图片](https://user-images.githubusercontent.com/49114731/68858533-38b5ae00-0720-11ea-9457-c6ad1014a4a3.png)
https://github.com/
![图片](https://user-images.githubusercontent.com/49114731/68858565-4703ca00-0720-11ea-8a55-ab23a7d8af46.png)

Here are the scripts in effect
https://greasyfork.org/zh-CN/users/106222-qxin-i
https://greasyfork.org/zh-CN/users/150560
https://greasyfork.org/zh-CN/users/150560

When I do not enable these scripts, I also cannot open the management interface on some pages. The previous version did not have this problem

**Comment by g1thub-h** [comment]
When I change the number of columns to 2, the bugs that cannot display the operation menu are gone. When I switch to 1, the bugs come back
As shown in the figure
![图片](https://user-images.githubusercontent.com/49114731/68867558-03fe2280-0731-11ea-9ddb-3de384e118d1.png)
![图片](https://user-images.githubusercontent.com/49114731/68867752-4f183580-0731-11ea-98e3-41329320291b.png)
![图片](https://user-images.githubusercontent.com/49114731/68867771-56d7da00-0731-11ea-9fcc-cd0cd4dc8e5f.png)
![图片](https://user-images.githubusercontent.com/49114731/68867786-5ccdbb00-0731-11ea-8b95-b9d6aee50362.png)

**Comment by derjanb** [comment]
> When I change the number of columns to 2, the bugs that cannot display the operation menu are gone.

Nice find!

I found the root issue. It's a combination of ideographic writing systems (-> short labels + 1 column -> "no need" to resize beyond the default width) and a race condition between Firefox layouting the popup and the data transfer from the background.

**Comment by g1thub-h** [comment]
Will you fix this problem in the next version?

I don't like the style of two columns very much.Thx

**Comment by derjanb** [comment]
> Will you fix this problem in the next version?

Yes, of course. In the meantime you can add this to the "Custom CSS" setting as a workaround. The action menu should then also work in 1 column mode properly.

```CSS
#action {
    min-height: 80px;
}
```

**Comment by g1thub-h** [comment]
It works, thank you very much! Looking forward to your update

**Comment by g1thub-h** [comment]
Thank you very much for your update, but there are still some problems.
The operation menu page cannot be opened before. Now it can be opened, but there is a problem with its adaption, as shown in the figure
![图片](https://user-images.githubusercontent.com/49114731/68989341-1cc91e00-0880-11ea-9418-714f5b45f745.png)

It should automatically adjust the height of this menu, as shown in the figure below
![图片](https://user-images.githubusercontent.com/49114731/68989362-98c36600-0880-11ea-9494-c4e5df9a0ab7.png)

Please fix this bug again

**Comment by g1thub-h** [comment]
I really need your help，please don't forget this bug.

**Comment by derjanb** [comment]
Can you please check TM BETA 4.10.6100 (https://www.tampermonkey.net/index.php?browser=firefox). Thanks.
