### ISSUE TITLE
How to use the jsx codemirror interface?

### ISSUE THREAD

**Issue by neechange** [Tampermonkey/tampermonkey#810]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)
android kiwi
How to use the jsx codemirror interface?

**Comment by derjanb** [comment]
Script editing is better done at a desktop system and synced to Android devices later-on.
