### ISSUE TITLE
Script updates aren't simple with user excludes

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#813]
## Expected Behavior
Consider script update simple if possibly dangerous parts (`@match`, `@include`, `@exclude`, `@grant`, `@require`, etc.) wasn't changed and don't show notification when `Don't ask me for simple script updates` is on.

## Actual Behavior
I get update notification on every script update for which I added user excludes. Even when only `@version` was changed in header.

## Specifications

- Firefox 71.0b10 x64
- TM: v4.9.6088 Beta
- OS: Win 10 v1607 x64

**Comment by mikhaelkh** [comment]
I probably not listed all conditions for simple script updates. When exactly script update is considered simple?

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.10.6100 (https://www.tampermonkey.net/index.php?browser=firefox)
