### ISSUE TITLE
Persistent scrollbars in `Darker` Layout

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#814]
## Actual Behavior
Persistent scrollbars (both horizontal and vertical) in Dashboard with `Darker` Layout. Other layouts don't have this issue.

## Specifications

- Firefox 71.0b10 x64
- TM: v4.9.6088 Beta
- OS: Win 10 v1607 x64

**Comment by derjanb** [comment]
Should be fixe at TM BETA 4.10.6100 (https://www.tampermonkey.net/index.php?browser=firefox)
