### ISSUE TITLE
All userscripts gone!

### ISSUE THREAD

**Issue by thunderpants** [Tampermonkey/tampermonkey#818]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
I'm sorry to hear that. Most likely your browser profile or the browser's extension storage database got corrupted. But without further information it's not possible to help you.

**Comment by thunderpants** [comment]
Waterfox 2019.10
4.9.6095
Win10 1909 BUILD.18363.476 (allowed it to update to 1909 feature update  last night)

Woke up today ,opened my browser and all my scripts have vanished.
I had quite a few scripts but not all activated ,this is some of them:
   AdsBypasser
   Anti-Adblock_Killer_Reek
   Auto_Steam_Discovery_Queue
   BaiduPanDownloadHelper
   CS.RIN.RU_-_Google_Blacklist_Fix
   Daily_Mail
   FAST_SELL_STEAM
   PiratePowered.ga_download
   Steam_Discovery_Queue_Auto-Skip
   steam_quick_queue
   Steam_Store_-_Game_Owned_Checker
   SteamTrades_-_Have_List_Filter

**Comment by thunderpants** [comment]
I wish i had kept a recent userscipt backup though i did get most of them back by importing an old backup thanks to Tampermonkey's easy to use import feature.
