### ISSUE TITLE
[Safari] Logging Level option can't get changed

### ISSUE THREAD

**Issue by icpz** [Tampermonkey/tampermonkey#824]
I modified logging level option to debug/verbose, but the logging file still show warn and error logs only. Though there's an floating context shows 'option completed successfully'.

## Expected Behavior
Debug level logs show up in log.txt.

## Actual Behavior
I got this log.txt:
```plain
App started
#appex(background) [warn]: TODO: implement webRequest.onHeadersReceived!
#appex(background) [warn]: TODO: implement webRequest.onResponseStarted!
#appex(background) [warn]: TODO: implement webRequest.onErrorOccurred!
#appex(background) [warn]: TODO: implement webRequest.handlerBehaviorChanged!
#appex(background) [warn]: webNavigation.onCommitted.addListener is not implemented.
#appex(background) [warn]: TODO: implement runtime.onConnectExternal!
#appex(background) [warn]: commands.onCommand.addListener is not implemented.
#appex(background) [warn]: TODO: implement browserAction.setPopup!
#appex(background) [warn]: TODO: implement storage.onChanged!
#appex(background) [warn]: Storage: can't clean currently active storage
#appex(background) [warn]: TODO: implement webRequest.handlerBehaviorChanged!
#appex(background) [warn]: TODO: implement browserAction.setBadgeBackgroundColor!
#appex(content) [error]: Script error.
#appex(content) [error]: Script error.
#appex(background) [warn]: scriptman: invalid userscript [object Object] [object Object]
#appex(background) [warn]: import: Error @ script  [object Object]
#appex(content) [error]: Script error.
#appex(content) [error]: Script error.
#appex(content) [error]: Script error.
```

BTW, when I open the dashboard of TM, console shows two errors:
![console-errors](https://i.imgur.com/v85k6oq.png)

## Specifications

- Safari: 13.0.4
- TM: 4.10.6103
- OS: macOS 10.15.2

## Script

I only installed [userscript](https://greasyfork.org/scripts/24508-userscript-show-site-all-userjs) currently.

**Comment by derjanb** [comment]
Please try to restart Safari to apply the log level. Does that work?
Thanks for sending the error screenshot.

**Comment by icpz** [comment]
I've restart Safari several times, still same issue.

**Comment by icpz** [comment]
I did try removing directories under `~/Library/Containers` and factory reset, it still doesn't show debug logs...

**Comment by derjanb** [comment]
> I only installed userscript currently.

I installed the script successfully and it's working fine here. However, yours is somehow broken: 
> scriptman: invalid userscript [object Object] [object Object]

The two console errors, as well as some issues regarding the log level will be fixed at the next version.

**Comment by icpz** [comment]
Thanks!
