### ISSUE TITLE
Brave browser loses all changes to scripts developed incognito 

### ISSUE THREAD

**Issue by aarondc** [Tampermonkey/tampermonkey#832]
(Please fill out the issue template with your details)

## Expected Behavior
I expect that saving a script when editing it from an incognito Brave browser would mean when I open an incognito Brave browser some time later that my hours of coding would still be there

## Actual Behavior
It's gone. All of it. POS.

## Specifications
OS: Win 10 Home
Browser: Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)

## Script

(Please give an example of the script if applicable.)
Try anything. TamperMonkey exhibits really FUBAR behaviour when switching between normal and incognito Brave browser instances. WTAF?

**Comment by derjanb** [comment]
Have you seen this message?

![image](https://user-images.githubusercontent.com/767504/70432454-a0d98480-1a7f-11ea-9bb7-36e2072513ac.png)

Also have you tried this setting after setting "Config Mode" to "Advanced":

![image](https://user-images.githubusercontent.com/767504/70432594-ef871e80-1a7f-11ea-9aa1-7fd8060c6d0e.png)

Please re-open if one these is missing or not working.

**Comment by aarondc** [comment]
I am pretty sure I already had Store data in incognito mode set to permanent, and no, I did not notice a tiny message in the same tiny font as the other 300++ items on that page.

**Comment by derjanb** [comment]
You should be able to zoom Tampermonkey's UI like normal webpages via CTRL+Middle Mouse Scroll Wheel or CTRL++/CTRL+-
