### ISSUE TITLE
[Firefox <=57] Incompatible with script produced by Webpack + Babel + core-js2

### ISSUE THREAD

**Issue by machsix** [Tampermonkey/tampermonkey#834]
# Expected Behavior
Script runs normally like Chrome 48+Tampermonkey and produces the following content in the console
![untitled2](https://user-images.githubusercontent.com/28209092/70486496-15ccae80-1ac0-11ea-951b-ec5aa6fdd572.png)

## Actual Behavior
An error is generated for Firefox 52 ESR or Firefox 57 with Tampermonkey
![untitled](https://user-images.githubusercontent.com/28209092/70486510-22510700-1ac0-11ea-9544-206eab1f46cb.png)

The error is not reproducible in
- Firefox 52 ESR or Firefox 57 with Violentmonkey
- Firefox 68 ESR with Tampermonkey
- When bundle the script with `core-js@2` but not `core-js@3`

## Specifications

- Firefox 52 ESR (downloaded from https://portableapps.com/apps/internet/firefox-portable-legacy-52), Firefox 57
- TM: 4.9.6095
- OS: Windows 10

## Script

The script is generated with Webpack + @babel/plugin-transform-runtime + @babel/runtime-corejs3. If I use Webpack + @babel/plugin-transform-runtime + @babel/runtime-corejs2, everything works normally. I hosted the minimum example at 
- core-js@3: https://github.com/machsix/tampermonkey_bug
- core-js@2: https://github.com/machsix/tampermonkey_bug/tree/core-js%402

Entry point is `/src/index.js`

The produced userscript is at `/dist/test.user.js`

**Comment by derjanb** [comment]
Well that's a Firefox issue. Somehow the FF folks thought it would be a good idea to have global properties which are not part of the global object.

```Symbol``` is one of these in FF 52. That's why Tampermonkey misses this property.

You can workaround the issue by either adding 

```// @grant none```

to your script or by adding

```window.Symbol = Symbol;```

as first line after the header.
