### ISSUE TITLE
how to load css file by GM method?

### ISSUE THREAD

**Issue by Joyeah** [Tampermonkey/tampermonkey#835]
(Please fill out the issue template with your details)
How cant I load a css file from outside just like @require a js ?
如何从外部引入一个css文件？

- Chromium: (i.e. 64.0.3282.140)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @require http://cdn.abc.com/jquery-ui.min.css
// ==/UserScript==
```

**Comment by derjanb** [comment]
For example via `@resource` and `GM_getResourceText`.

https://www.tampermonkey.net/documentation.php#_resource
https://www.tampermonkey.net/documentation.php#GM_getResourceText

**Comment by jb222** [comment]
Don't use `@require`. Use `@resource` instead and `@grant GM_getResourceText`. You will need a reference to the external link, in the example: IMPORTED_CSS.

### **External file**
I tested this successfully in Chrome, Firefox and Safari.
```
// ==UserScript==
    ...
// @resource   IMPORTED_CSS http://cdn.abc.com/jquery-ui.min.css
// @grant      GM_getResourceText
// @grant      GM_addStyle
/// ==/UserScript==

(function() {
    'use strict';
    const my_css = GM_getResourceText("IMPORTED_CSS");
    GM_addStyle(my_css);
```
### **Local file**
Similar procedure, but unfortunately **this only works in Chrome**. 
Note the extra steps below the code, it took me hours to make it work.
```
// ==UserScript==
    ...
// @resource   IMPORTED_CSS file:///D:/xxx/xxx/styles.css
// @grant      GM_getResourceText
// @grant      GM_addStyle
/// ==/UserScript==

(function() {
    'use strict';
    const my_css = GM_getResourceText("IMPORTED_CSS");
    GM_addStyle(my_css);
```
You need to allow Tampermonkey access to local file URI's (watch the video tutorial in [#204](https://www.tampermonkey.net/faq.php#Q204)). 

1. Go to chrome://extensions/ and click on the TM details button:

![tm_1](https://user-images.githubusercontent.com/61352184/81808796-8751d280-9520-11ea-812e-feea5fc891dd.png)

2. Allow access to file URL's:

![tm_2](https://user-images.githubusercontent.com/61352184/81809501-cd5b6600-9521-11ea-87f1-3fa7579e2b14.png)

3. Now, back in your TM settings tab, a new line has appeared in the Security section:

![tm_3](https://user-images.githubusercontent.com/61352184/81809896-5b375100-9522-11ea-87c0-4a981473b184.png)
