### ISSUE TITLE
[Safari] WebDAV Support

### ISSUE THREAD

**Issue by Chandler-Lu** [Tampermonkey/tampermonkey#836]
## Expected Behavior
Use Webdav to sync on Safari

## Actual Behavior
Chrome version has webdav to TESLA sync. But there is not on safari.

## Specifications

- Safari 13.0.4
- Tampermonkey MAS

**Comment by derjanb** [comment]
Unfortunately this can't be fixed using Safari's App technology. However, there now is a [new extension that uses Web Extension technology](https://github.com/Tampermonkey/tampermonkey/issues/1258#issuecomment-2485870092).

You can upgrade your extension [by getting the Tampermonkey bundle](https://github.com/Tampermonkey/tampermonkey/issues/1258#issuecomment-2495388545).
