### ISSUE TITLE
import 500 tampermonkey scripts it only shows 99 installed afterwards

### ISSUE THREAD

**Issue by mattnakatani** [Tampermonkey/tampermonkey#837]
(Please fill out the issue template with your details)

## Expected Behavior
import with zip file and should have over 500 scripts afterwards

## Actual Behavior
only 99 scripts showing in "installed userscript"

## Specifications
Firefox 

- Firefox: 68.2.0esr (64-bit)
- TM: 4.9.6095
- OS: MacOS 10.14.6

**Comment by derjanb** [comment]
Hi, this is working fine here with a backup with more than 500 scripts. Would it be possible that you sent me the archive [via mail](https://www.tampermonkey.net/imprint.php)?
