### ISSUE TITLE
Utilize Monaco Editor for better user experience

### ISSUE THREAD

**Issue by vmachacek** [Tampermonkey/tampermonkey#841]
(Please fill out the issue template with your details)

## Expected Behavior
better usability of editor of scripts

## Actual Behavior
not so great usability of editor

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

Please throw away current editor and use Microsoft's Monaco
https://microsoft.github.io/monaco-editor/

**Comment by tophf** [comment]
Monaco editor package is 10MB after build+minimization (compare that to 2MB of js files included with Tampermonkey) so obviously it's not something that can be included with an extension where editing of source code is not the primary function, nor even the secondary, for 99% of users.

Use [TamperDAV](https://github.com/Tampermonkey/TamperDAV#user-content-tamperdav) instead.

**Comment by aolko** [comment]
But tamperDAV is useless

**Comment by derjanb** [comment]
I just created a new extension that allows to edit the userscripts of Tampermonkey at vscode.dev (which is basically a VSCode online editor).

I know this does not fix Tampermonkey's internal editor, but it might help.
To test it you have to install [TM BETA 4.19.6176+](https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf) and [Tampermonkey Editors 1.0.1](https://chrome.google.com/webstore/detail/tampermonkey-editors/lieodnapokbjkkdkhdljlllmgkmdokcm).

A click at "Tampermonkey Editors"' icon will take you to vscode.dev and a "folder" with all installed Tampermonkey scripts should be automatically opened.
