### ISSUE TITLE
matches not updated in database after WebDav sync

### ISSUE THREAD

**Issue by Nils-1st-retail** [Tampermonkey/tampermonkey#842]
## Expected Behavior
After updating a script with a new match url on Chrome, the change are synced too Firefox and Firefox will run on the new match url.

## Actual Behavior
The changes in the script is synced, but the match list isn't updated in the database on Firefox. 
The problem exists from Firefox -> Chrome too, and from Chrome -> Chrome on another computer too.
If I manually update the script on the receiving computer the match urls get fixed.

## Specifications

- Chromium: 79.0.3945.79, Firefox: 71.0
- TM: 4.8.41
- OS: MacOS 10.15

**Comment by derjanb** [comment]
Fixed at TM BETA 4.10.6106
