### ISSUE TITLE
URL detection not properly functional - script not launched

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#845]
(Please fill out the issue template with your details)

## Expected Behavior
Run the script on any page matching the @match clause..

## Actual Behavior
Script doesn't activate when I'm brought to page when it's expected to run by hyperlink from another page on same web. The script runs only after I do a manual page reload afterwards. The web may use some tricky lazy load or kind of redirects which I'm not able to disclose. If I inspect the target of link which opens the page, there's not any visible redirection or obfuscating, the href value leads directly to page.

## Specifications

- Firefox 54.0.1
- TM: 4.10.6105
- OS: Windows 8.1 / x64

## Script
[https://greasyfork.org/scripts/394041-novinky-cz-roz%C5%A1%C3%AD%C5%99en%C3%A9-%C5%99azen%C3%AD-diskus%C3%AD/code](https://greasyfork.org/scripts/394041-novinky-cz-roz%C5%A1%C3%AD%C5%99en%C3%A9-%C5%99azen%C3%AD-diskus%C3%AD/code)

**Comment by derjanb** [comment]
I assume the pages uses pushState or replaceState to modify the displayed URL. If so, please see https://github.com/Tampermonkey/tampermonkey/issues/488#issuecomment-357531737

Possible workaround for your userscript:

```JavaScript
history.pushState = history.replaceState = location.reload.bind(location);
```
