### ISSUE TITLE
Safari 13 Stuck on "Sync is Running"

### ISSUE THREAD

**Issue by maobowen** [Tampermonkey/tampermonkey#846]
## Expected Behavior
Tampermonkey should be able to sync from Google Drive in several seconds. Syncing works perfectly on Chrome 81.0.4000.3 dev and Firefox 72.0b9 on the same machine.

## Actual Behavior
After opening Safari, Tampermonkey stuck on "Sync is Running" and could not update or sync scripts from Google Drive automatically. Since I usually use Safari in private mode, each time I opened Safari, I would be redirected to Google's authentication (login) page. After logging in, the tab was not close automatically and Tampermonkey stuck. After I switched to normal mode, the issue still existed. I didn't see any *related* error message from the browser's console.

## Specifications

- Safari: 13.0.4
- TM: 4.10.6103
- OS: macOS 10.15.2

**Comment by Jonatino** [comment]
Still happening on macOS 11.0.5 Big Sur

**Comment by androidfans** [comment]
Reproed this bug. 
step : 
1. click "save sync", noting happens
2. launch browser another time, it promt a google login page. just close it
3. it always stuck on sync is running

**Comment by Kosezu** [comment]
This is happening for me on Safari 14.1.1 (16611.2.7.1.4) as well.

**Comment by jeffbyrnes** [comment]
Same for me on Safari 14.1.2 (16611.3.10.1.6), on macOS Big Sur 11.5.2 (20G95), on an iMac (24-inch, M1, 2021).

**Comment by MittWillson** [comment]
Also Safari 15.1 on macOS Monterey with Google Drive sync

**Comment by marlarius** [comment]
Also happening on Chrome 100.0.4896.127 on Linux Mint.

**Comment by mantazzo** [comment]
I encountered this issue with Firefox 105.0.3. After checking the console, it shows me "<link> req.status = 404" and then fails to continue. Maybe have some bypass if the plugin cannot be found and throw a note that "some plugins couldn't be retrieved"?

**Comment by derjanb** [comment]
Should be fixed 4.20.6184 which is currently rolled out. Thanks for reporting.
