### ISSUE TITLE
Silent scripts downgrades and wrong script synces across browsers

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#849]
(Please fill out the issue template with your details)

## Expected Behavior
N/A

## Actual Behavior

I record situations, when some of my scripts kept in repository is silently reverted to older state. What the situations have in common is the script is exported to cloud via TESLA and also is published to GreasyFork (but possibly not linked to as the import icon is not shown for it). The downgrades are detectable after having the script opened in editor persistently for longer period, make minor changes and want to save it, a confirmation tab opens with highligh of changes against stored version, I can clearly see the stored version has far more differences than the most recent changes. I can safely rule out that this script wasn't saved earlier.

There may be more scenarios, when opening a different browser or browser on different device, where the same script was already added by TESLA, or was imported from GreasyFork, and containing an older script state, may by an algorithm mistake send this version by TESLA and update on other browsers in background, while still having opened the latest snapshot in TM's editor where it's currently being worked on.
Some role on this may play Greasyfork's auto updates, but as I said the primary browser (where it's being developed) probably hasn't linked this script with it's GF repository.
Another thing which may cause the mess is that I change @version only after major changes to script, which admits more different script snapshots with same @version may at least for short periods concurently coexist on different devices bound via TESLA.

If I want to debug a script in secondary browser, I usually launch it and immediately  open TM control panel, open concerned script in editor and paste/save the fresh snapshot from browser where latest changes to it were made, as it may be not yet synced.

There's yet one more situation which proves TESLA behaves unreliably:
If I connect to TESLA for the first time a browser already having installed some scripts from GF, I encounter that some scripts in other already connected browsers are overwritten by different scripts, making them duplicate, without changing the script names in repo, but opening them in editor clearly shows that the content is not this script. Updating the silently misplaced script's name in local repository occurs only after I explicitly do Save it from editor.

May executing "Reset sync" on initially linked browser contribute to this mess, but anyway the TESLA system should in no situation allow to link mismatching scripts among different browsers, or update matching scripts in any browser to older state from another browser. If it matches scripts by their Order №, it's completely bad idea as same scripts may and mostly have varying Order № in different browsers, as the order of instalaltion is in every browser different.

## Specifications

- Firefox 54.0.1 (4.10.6105)
- Chrome 79.0.3945.88 (4.9)
- Opera 65.0.3467.78 (4.9.6091)
- OSes: Windows 8.1/x64, Windows 10/x64

## Script

general

**Comment by derjanb** [comment]
TM BETA 4.10.6106 should make script sync more reliable, but I haven't checked all of the use cases from above though.

**Comment by derjanb** [comment]
> If I connect to TESLA for the first time a browser already having installed some scripts from GF, I encounter that some scripts in other already connected browsers are overwritten by different scripts, making them duplicate, without changing the script names in repo, but opening them in editor clearly shows that the content is not this script.

Not sure how this could happen. Scripts are synced by a UUID which is generated on script installation.

> the TESLA system should in no situation allow to link mismatching scripts among different browsers, or update matching scripts in any browser to older state from another browser.

This can only happen when one of the systems is set up to a wrong time which then is changed by Tampermonkey is running.

> Another thing which may cause the mess is that I change @Version only after major changes to script, which admits more different script snapshots with same @Version may at least for short periods

To create more overview you could add sub minor numbers on simple edits.

> The downgrades are detectable after having the script opened in editor persistently for longer period, make minor changes and want to save it, a confirmation tab opens with highligh of changes against stored version, I can clearly see the stored version has far more differences than the most recent changes

The confirmation tab is there to detect exactly such kind of issues. 

Finally, there were a major sync improvement in  4.10.6106 so can you please test with a newer version?

**Comment by trumpeta** [comment]
This has not been fixed, the version kickbacks are still present.

The scenario which may be in effect is this:

I have Tesla configured and create new script in one browser, then upload it to GreasyFork (or other updatable repository)
I run another browser with TM, I have Tesla configured and the script adds via Tesla during work.
I run another browser with TM, I have Tesla configured and need to test the script quickly, open GreasyFork, install it from there, which makes update binding to online repository.

Later all browsers are closed, I update the script in primary browser, increase version and update source at online repository.
Later I update the script in primary browser again (say it beta version), but don't increase version number and don't update the repositury.
I open the third browser, which updates the script to next version from GreasyFork, which is currently not the most recent snapshot, and synces this snapshot to Tesla, as it's the most recently modified source with current version number. Later I open prmary browser, which via Tesla reverts to latest stable version.

The scenario may be yet different, but somehow so this does happen, on the cause dual-tracked and mutually uncoordinated synchronization schems. Perhaps this can be avoied by unticking the Check for updates checkbox in script's settings, but one always doesn't care, or forgets. I feel like Tampermonkey should handle this duality and not so easily allow to send older versions to Tesla.
