### ISSUE TITLE
"Limited runtime" warning is over the script name and the enable button

### ISSUE THREAD

**Issue by johnmx** [Tampermonkey/tampermonkey#852]
## Expected Behavior
When I click on the TM icon, the "Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!" message should be at the bottom of the popup window.

## Actual Behavior
This message is now at the top and over the loaded script name and other options, like the enable/disable button, etc.
That way I cannot disable it neither view the current loaded script name.
The attached picture shows this.

Please note: This issue is not about the meaning of the warning message. I don't want to make the message disappear. It is only about the position of the message on the window!

## Specifications

- Chromium: Version 79.0.3945.88 (Official Build) (64-bit)
- TM: Version 4.9
- OS: Win10 Enterprise

![Limited](https://user-images.githubusercontent.com/10428529/71783714-c0ae8a80-2fe2-11ea-906a-dd4fbd92a90f.jpg)

**Comment by derjanb** [comment]
Thanks for reporting this issue. Fixed at 4.10.6109
