### ISSUE TITLE
GM_xmlhttpRequest doesn't handle URLs without the protocol

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#855]
## Expected Behavior

URL without the protocol should be considered as a relative URL.

## Actual Behavior

The final URL doesn't include the target hostname but the hostname of the current page.

## Specifications

- Chromium: Cent Browser Version 4.0.9.112 (Official Build) (32-bit) (Chromium 74.0.3729.169)
- TM: 4.10.6106
- OS: Windows 7

## Script

```js
GM_xmlhttpRequest({
  method: "GET",
  url: "//www.youtube.com/",
  onload: function(response) {
    console.log(response)
  }
});
```

**Comment by derjanb** [comment]
Fixed at 4.10.6109
