### ISSUE TITLE
status == 0 when readyState < 4

### ISSUE THREAD

**Issue by qsniyg** [Tampermonkey/tampermonkey#857]
## Expected Behavior

`status` should be the actual status (works fine under Violentmonkey)

## Actual Behavior

`status` is 0 on `onprogress` events.

## Specifications

- Firefox: 72.0.1
- TM: 4.10.6105
- OS: Linux

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *
// @include      *
// @grant        GM.xmlHttpRequest
// ==/UserScript==

(function() {
    'use strict';

    var xhr;

    var loadfunc = function(resp) {
        if (resp.readyState < 2)
            return;

        console.log(resp);
        xhr.abort();
    };

    var obj = {
        url: "https://www.google.com/"
    };

    if (true) {
        obj.onprogress = loadfunc; // status == 0
    } else {
        obj.onload = loadfunc; // status == 200
    }

    xhr = GM.xmlHttpRequest(obj);
})();
```

This is problematic for my userscript (https://greasyfork.org/en/scripts/36662-image-max-url), as it believes status == 0 to mean that the website was blocked via either tracking protection or that the domain/ip couldn't be resolved.

**Comment by derjanb** [comment]
Fixed at 4.10.6109
