### ISSUE TITLE
Chrome update has broken tampermonkey: Version 79.0.3945.130 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by reb32136** [Tampermonkey/tampermonkey#859]
(Please fill out the issue template with your details)

## Expected Behavior
User script woks

## Actual Behavior
User script does not work - no evidence it is loaded.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
// ==UserScript==
// @name           Social Fixer for Facebook
// @namespace      http://userscripts.org/users/864169999
// @include        /^https?:\/\/facebook\.com\//
// @include        /^https?:\/\/[^\/]*\.facebook\.com\//
// @exclude        /^https?:\/\/[^\/]*(channel|static)[^\/]*facebook\.com\//
// @exclude        /^https?:\/\/[^\/]*facebook\.com\/.*(ai.php|morestories.php|generic.php|xti.php|plugins|connect|ajax|sound_iframe|l.php\?u)/
// @exclude        /^https?:\/\/[^\/]*\.facebook\.com\/help/
// @exclude        /^https?:\/\/[^\/]*\.facebook\.com\/support/
// @exclude        /^https?:\/\/[^\/]*\.facebook\.com\/saved/
// @connect        mbasic.facebook.com
// @connect        socialfixer.com
// @connect        matt-kruse.github.io
// @run-at         document-start
// @version        24.1.0
// @grant          GM_addStyle
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// ==/UserScript==
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
This is workgin fine here using Windows 10, Chrome 79.0.3945.130 and Tampermonkey stable and beta. Please add more details on how to reproduce the issue. Thanks.

**Comment by filbo** [comment]
If this is from SFx user Bob B, we resolved this issue and it was not a Tampermonkey bug.  However, there was a very small TM, um, inadequacy -- a thing which could have avoided the whole issue in the first place, were it better.  I have raised that as a separate TM issue (#860).
