### ISSUE TITLE
Update from file stored in network shared drive is working poorly

### ISSUE THREAD

**Issue by dbarwikowski** [Tampermonkey/tampermonkey#864]
(Please fill out the issue template with your details)

## Expected Behavior
Update of script stored in file in network shared drive should work.

## Actual Behavior
Update from 'Installed scripts' view is always saying that no never version was found.
When I go to tools and paste url to file then it says that there is an update.

## Specifications

- Chrome: 79.0.3945.88
- TM: 4.9
- OS: Windows

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         ***
// @namespace    http://tampermonkey.net/
// @version      2020.01.291
// @description  ***
// @author       ***
// @match        https://***
// @match        http://***
// @grant       GM_getValue
// @grant       GM_setValue
// @updateURL	file:///J:/Tampermonkey/Script%202.0/Automate.user.js
// ==/UserScript==
```

**Comment by derjanb** [comment]
Duplicate of #977
