### ISSUE TITLE
Detect whether userscript is running on page?

### ISSUE THREAD

**Issue by edreal** [Tampermonkey/tampermonkey#866]
I noticed that getEventListeners(document) has some handler from Tampermonkey but getEventListeners can be called only from dev tools so it doesn't work in real situation.
Does tampermonkey leave any fingerprints to window object or anything else?

**Comment by derjanb** [comment]
It tries not to do. :) 
However, for content script <> page communication an event with a random name is used. I guess this is what you were seeing?

Also scripts that change the DOM or global window functions/properties might be detectable.
