### ISSUE TITLE
Retrieve userscripts from chrome backups

### ISSUE THREAD

**Issue by InsOpDe** [Tampermonkey/tampermonkey#872]
I have lost my userscripts due to 
> Tampermonkey detected that the extension storage is unreliable!\n\nUnfortunately this means that all your settings and userscripts are inaccessible at the moment.\n\nDo you want to visit the FAQ entry that explains how to recover from that?
and couldnt retrieve them via FAQ or the [python](https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0) script you've provided.

I do have backups of my chrome directory (`/home/user/.config/chromium`) including this extension (version `4.8.41_0`).
Now I was not able to retrieve my userscripts via the python script either - i think this is due to the missing log-files in which the userscripts are stored.

Is there any way to restore the userscripts with my chromium backup?

**Comment by derjanb** [comment]
> i think this is due to the missing log-files in which the userscripts are stored.

This might be the root cause, if they are really missing. Just to be sure: the data folder in your case should be: `~/.config/chromium/Default/Local Extension Settings/dhdgffkkebhmkfjojejmpbldmpobfkfo`

If the log files are missing, the you might be able to recover data from the .ldb files, which btw. should contain most of the data:
https://antimatter15.com/2015/12/recovering-deleted-data-from-leveldb/

**Comment by lamchau** [comment]
x-posting from the FAQ [script](https://gist.github.com/derjanb/9f6c10168e63c3dc3cf0)
> Couldn't get the macOS `leveldb` python package to compile, but wrote a [node-based solution](https://gist.github.com/lamchau/718aa36a6e78c2a744ff017709efcf58) for anyone else who gets stuck.

**Comment by nitorita** [comment]
> > i think this is due to the missing log-files in which the userscripts are stored.
> 
> This might be the root cause, if they are really missing. Just to be sure: the data folder in your case should be: `~/.config/chromium/Default/Local Extension Settings/dhdgffkkebhmkfjojejmpbldmpobfkfo`
> 
> If the log files are missing, the you might be able to recover data from the .ldb files, which btw. should contain most of the data: https://antimatter15.com/2015/12/recovering-deleted-data-from-leveldb/

Thank you; this was helpful in finding my old Tampermonkey scripts after a PC reset without backing them up. Total godsend.

The exact folder is ambiguous as they are randomly generated per extension per installation instance, but I managed to find the correct one through trial and error.

**Comment by yilmazdurmaz** [comment]
I needed such process moments ago when I realized I didn't save any scripts I wrote before reinstalling my system. Fortunately, I had a system backup before reinstallation. 

At first, I tought about reading ldb file and try to rescue my scripts. But there seemed too many work to do.

Then, I decided to make a trial and hit the bulls eye:
 - close the browser
 - open the storage location and copy/paste the whole content from old backup. all the logs, ldb files and manifests, etc. 
   - remove all current files (maybe backup)
 - restart the browser

It was MSEdge and extendion ID is `iikmkjmpaadaobahmlepeloendndfphd`.

On windows, the location is `%LOCALAPPDATA%\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\`

**Comment by L0garithmic** [comment]
Thank you for this @yilmazdurmaz. I lost some one-off scripts on a rebuild after a BSOD and I just replaced my C:\ Drive files with the backups of the folders containing "iikmkjmpaadaobahmlepeloendndfphd" I had made (I always backup my entire C drive contents to another drive before rebuilt) and they were all there. Thank you.
