### ISSUE TITLE
TamperMonkey breaks download funtionality in FireFox

### ISSUE THREAD

**Issue by ErgoPr0xy** [Tampermonkey/tampermonkey#873]
(Please fill out the issue template with your details)

## Expected Behavior
Any download button/option in Firefox should work, tested on multiple sites, the browser just flashes and the download does not start. 

## Actual Behavior
Nothing works until TamperMonkey is disabled and FF is restarted

## Specifications

- Firefox: v73.0 
- TM: v4.10.6105
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)
N/A
```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Test Case:
* Windows 10
* https://www.mozilla.org/de/firefox/all/#product-desktop-release
* FF 73.0 (64-Bit)

This is working fine here. Can you please try a new temporary profile?

![image](https://user-images.githubusercontent.com/767504/74289947-b9d90d00-4d30-11ea-94fe-823706c3faa8.png)

**Comment by ErgoPr0xy** [comment]
Tried with a temp profile and TM and downloads worked fine. 
Re-enabled on browser/profile that originally had the issue and downloads are working now. 
This was any download not any particular website. I will log this again with more info if it happens again. 

Thanks
