### ISSUE TITLE
Firefox addon sync doesn't work

### ISSUE THREAD

**Issue by zax-ftw** [Tampermonkey/tampermonkey#875]
Tampermonkey doesn't get synced via Firefox sync. It doesn't appear in sync-....-mozilla.com account data (I check it using "About Sync" addon, there's no Tampermonkey entry at all).

It's the only addon I have installed that doesn't get imported from my home pc to work pc.

## Expected Behavior
Tampermonkey entry is detected on mozilla account data so it's automatically installed with new Firefox installations along with other synced addons.

## Actual Behavior
Tampermonkey entry doesn't appear on mozilla account data.

## Specifications
- Firefox 73.0
- Windows 10

**Comment by derjanb** [comment]
> Tampermonkey doesn't get synced via Firefox sync.

I don't think extensions can control whether Firefox tries to sync them or not. Tampermonkey however uses Firefox Sync to synchronize the userscripts if "Script Sync" Type "Browser Sync" is configured and enabled.

> It doesn't appear in sync-....-mozilla.com account data (I check it using "About Sync" addon, there's no Tampermonkey entry at all).

How do I check that? At "about:preferences#sync" it don't look like you can configure Add-on on a per Add-on base.

> It's the only addon I have installed that doesn't get imported from my home pc to work pc.

I just synced Tampermonkey from Ubuntu to Windows 10. So there doesn't seem to be general problem. However, only the stable version from AMO was synced, the not-listed beta version was not. Which one do you use?

**Comment by zax-ftw** [comment]
> I don't think extensions can control whether Firefox tries to sync them or not. 

Well, I don't know either, could be some flag or so? I never tinkered with browser extensions honestly.

> How do I check that? At "about:preferences#sync" it don't look like you can configure Add-on on a per Add-on base.

With About Sync addon installed you check it with about:sync, it shows all of your account data uploaded via sync. The entries we are talking about are under "addons" -> Records(table)

![sync](https://user-images.githubusercontent.com/15687163/74470273-84eac880-4e9e-11ea-9e0e-a25ac836a78d.png)

> I just synced Tampermonkey from Ubuntu to Windows 10. So there doesn't seem to be general problem. However, only the stable version from AMO was synced, the not-listed beta version was not. Which one do you use?

I'm using the official stable version from AMO as well. If it doesn't appear in my account data, it explains why it doesn't get synced. Reinstalling didn't help either, will try tomorrow at work PC.

**Comment by zax-ftw** [comment]
Just wanted to add that once I manually installed this addon on other PC the scripts synced fine. The only thing that doesn't sync here is the "existence" of Tampermonkey itself (confirmed with about:sync) thus on new Firefox installations this addon doesn't get automatically installed via sync.

The same thing is happening on all of my computers, so it's not unique to some specific installation.

**Comment by derjanb** [comment]
> The only thing that doesn't sync here is the "existence" of Tampermonkey itself (confirmed with about:sync) thus on new Firefox installations this addon doesn't get automatically installed via sync.

Ah. OK. Well, extensions should definitely be synced (https://wiki.mozilla.org/Services/Sync/Addon_Sync)

Please report this issue to Mozilla's bug tracker. There is nothing that I can do to fix the issue.

> With About Sync addon installed you check it with about:sync

👍
