### ISSUE TITLE
Add version number in tabs

### ISSUE THREAD

**Issue by jb222** [Tampermonkey/tampermonkey#878]
I often get lost with different versions open in the editor, even the file itself doesn't provide clarity. Can the version number be added in the tabs and the top level? See image.

![tm-versionnumber](https://user-images.githubusercontent.com/61352184/75093057-c35b4400-557e-11ea-926e-356e778127df.png)

**Comment by janboeijink** [comment]
Thanks for the fix! But I still miss it in the top level, see the left arrow in the image.
BTW the top level takes a lot of valuable screen space for no obvious reason.

**Comment by derjanb** [comment]
> BTW the top level takes a lot of valuable screen space for no obvious reason.

You can define custom CSS rules to hide the header, see #495 for more information.
