### ISSUE TITLE
[Google Drive Sync] The script reappears after deleted

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#879]
(Please fill out the issue template with your details)

## Expected Behavior

Delete a script.

## Actual Behavior

I have deleted a script yesterday but it reappears now. This has happened multiple times.

## Specifications

- Firefox Developer Edition 74.0b7
- TM: (i.e. 4.5.5648) 4.10.6105
- OS: (i.e. MacOS 10.13.4) Windows 10 64-bit

## Script

This script: https://greasyfork.org/en/scripts/386048-top-theme. Though I don't think it is a script issue.

I have enabled Google Drive script sync and I do see some authentication errors in the background:
![image](https://user-images.githubusercontent.com/1324510/75234310-543b5500-57f5-11ea-9b53-6a0112308e11.png)

**Comment by eight04** [comment]
Delete again and I saw this:
![image](https://user-images.githubusercontent.com/1324510/75292809-eaa46080-585f-11ea-933b-023bf1fa11f4.png)

**Comment by mica** [comment]
This is an issue for me as well in Chrome using browser sync. I've got a number of scripts that I've deleted multiple times, only to have them reappear again and again.

**Comment by derjanb** [comment]
@mica Browser sync is not related to this issue. So please create a new one. But if you do, please try to find the script at 
 "chrome://sync-internals/" at the "Sync Node Browser" tab and attach its value. Thanks.

![image](https://user-images.githubusercontent.com/767504/88193995-9484ef00-cc3e-11ea-8abd-d2dc9b00b9b6.png)

**Comment by devnull69** [comment]
And adding/changing scripts works flawlessly...

**Comment by derjanb** [comment]
I hope this is fixed at 5.1.6193 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

I reworked sync quite a bit. My guess is that the delete request didn't succeed due to an authentication error and then the script was synced back (and restored) from remote. 

Please re-open if you see this problem again. Thanks.

**Comment by Alistair1231** [comment]
I feel like Tampermonkey should have an option to completely reset the sync-storage, but I was able to manually fix it by deleting the data in Google Drive.

1. go to Tampermonkey Backups and `Save to Disk` all Backups you don't want to loose (this will not only wipe the sync-storage but also the backups).
1. disable `Userscript Sync` in Tampermonkey, don't forget to click `save`
1. Go here: https://drive.google.com/drive/settings
1. select: `Manage Apps`
1. Scroll down to Tampermonkey
1. click `options`
1. click `delete hidden app data`
1. confirm
1. Back to Tampermonkey: delete all scripts, then restore your preferred Backup and reenable Sync

I don't yet know if this will permanently fix it, but at least for now it seems to work. If I delete a script and force a re-sync it doesn't reappear.
