### ISSUE TITLE
Constantly having to sign into Google...

### ISSUE THREAD

**Issue by A-Sparowe** [Tampermonkey/tampermonkey#880]
(Please fill out the issue template with your details)

## Expected Behavior

Not having to sign in to Google every time I open my browser?

## Actual Behavior

For the past few days, Tampermonkey has been giving me constant errors and making me sign into google every time I open my browser. I know this is for the sync feature with my Google Drive but I've never had it have to ask me after the initial setup of the extension when I first downloaded it. For the time being, I've just turned off the sync with Google Drive until I can figure out why it's constantly asking me now.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Can you please name your browser and Tampermonkey version?

And have you tried the "Revoke Access Token" button at the "Utilties" Tab?

![image](https://user-images.githubusercontent.com/767504/76355277-4a950f80-6314-11ea-93ef-243e29023f33.png)

**Comment by xXReDxSparoweXx** [comment]
Oops. Currently using the current builds of Firefox and Tampermonkey. Yes I was able to revoke access but I wouldve liked to leave it. Problem only started happening recently.

**Comment by jamxe** [comment]
same problem, I am using Chromium Edge v88 on Win10Pro. The `Revoke Access Token` would not work when cliked.

**Comment by Wimmox** [comment]
Experiencing this behavior for months now. I'm having Google Drive sync enabled, but with same account I have logged in into Chrome/Google. Would be better if it didn't asked to login every time I start my browser. 

- Chrome Versie 89.0.4389.114 (Officiële build) (64-bits)
- TM v4.11
- OS: Windows 20H2 (19042.906)

**Comment by derjanb** [comment]
There was a fix that improved the functionality if the "Revoke Access Token" at 4.12, which was released some days ago.

**Comment by Wimmox** [comment]
Thnx, I shall upgrade and try again!

**Comment by WhiteChairFromIkea** [comment]
This one started happening again about two months ago (chrome and tempermonkey ara always up to date). Doing "access token" thing does not help at all, even it always says "success".

**Comment by psychoadept** [comment]
This is happening to me now with 4.19. Using Vivaldi on Windows 11.

**Comment by mdtareque** [comment]
Seeing same behaviour. SignIn Tabs opens every now and then asking to SignIn with google to continue to TamperMonkey. On clicking the desired account, the tabs stop for sometime (~10+ mins) , but again start opening.

Firefox:115.5.0esr 
TamperMonkey: v5.0.0

**Comment by derjanb** [comment]
@mdtareque Your issue is tracked here: #1925

Sorry for any inconvenience!

**Comment by jbrandibas** [comment]
I am starting to get this issue now as well.  My settings look different though.  I don't have the buttons where they are in the image above, so I can't revoke the access token.

Tampermonkey 5.0.1
Windows 11 (10.0.22631)
Chrome 122.0.6261.129

**Comment by derjanb** [comment]
@jbrandibas Please see https://github.com/Tampermonkey/tampermonkey/issues/1925#issuecomment-2002082213. The issue should be gone after the next authentication dialog.
