### ISSUE TITLE
[Waterfox Classic] Scripts do not run when the "responsive design mode" from the devtools is open.

### ISSUE THREAD

**Issue by jasonkhanlar** [Tampermonkey/tampermonkey#882]
Same issue as https://github.com/Tampermonkey/tampermonkey/issues/473

When loading in Responsive Design Mode (Ctrl+Shift+M), user scripts no longer run at all.

I'm using Waterfox Classic 2020.01

I tested this also on Waterfox Current 2020.01 (64-bit), and it works there.

So, it seems this is an issue affecting the Waterfox Classic branch, and potentially other web Firefox-based browsers too.

**Comment by derjanb** [comment]
Is Waterfox Classic based on FF 57? This would explain the issue. If so, then this is a browser limitation which can't be workarounded by an extension. :-(
