### ISSUE TITLE
Scripts seem to run where they should not run

### ISSUE THREAD

**Issue by BoomerScratch** [Tampermonkey/tampermonkey#884]
All scripts seem to run at the chrome web store, even when `@include` or `@match` are set on a different website. I was looking [here](https://chrome.google.com/webstore/detail/boxel-rebound/iginnfkhmmfhlkagcmpgofnjhanpmklb) when the bug occurred.
![image](https://user-images.githubusercontent.com/60622217/76162955-61840800-6142-11ea-8928-d66632b7eddc.png)
They don't actually run. Tampermonkey thinks they run, but they don't.

Browser: Chrome 80.0.3987.132, OS: Windows 10
I have Tampermonkey stable.

**Comment by BoomerScratch** [comment]
O wait, i noticed it wasn't a bug. Closing as no longer relevant.

**Comment by derjanb** [comment]
Tampermonkey runs at the embedded Youtube page: https://www.youtube.com/embed/WbqaurkI...

**Comment by BoomerScratch** [comment]
> Tampermonkey runs at the embedded Youtube page: https://www.youtube.com/embed/WbqaurkI...

i know, but this happens at the chrome web store without any youtube embeds. it's because chrome extensions do not have access to some things, including the chrome web store.
