### ISSUE TITLE
Export backup to webdav error

### ISSUE THREAD

**Issue by Vstory** [Tampermonkey/tampermonkey#885]
## Actual Behavior
The file name contains the special character ":", causing the backup to fail.
webdav service provider: [https://www.jianguoyun.com/](https://www.jianguoyun.com/)
Because the file name contains ":", it cannot be successful when using webdav backup.

## Specifications

- Chromium: 82.0.4077.0
- TM: 4.9
- OS: Windows 1909

**Comment by derjanb** [comment]
Fixed at TM BETA 4.10.6112. Thanks for reporting.

**Comment by Vstory** [comment]
Thank you!
