### ISSUE TITLE
Конфликт со скриптами сайтов

### ISSUE THREAD

**Issue by tox-x** [Tampermonkey/tampermonkey#887]
## Expected Behavior
Реализовать возможность отключения работы дополнения на указанных сайтах, так же как это сделано в "AdBlock", для исключения конфликтов со скриптами сайтов.
Если это реализовано, то описать настройки так, что бы было понятно назначение полей.

## Actual Behavior
Дополнение вступает в конфликт со скриптами на сайтах, исключая их полноценное использование. При отключении дополнения функционал сайтов восстанавливается.

## Specifications

- GoogleChrome: Версия 80.0.3987.132 (Официальная сборка), (64 бит)
- OS: Windows 7/ 64 Professional

## Script

(Please give an example of the script if applicable.)

Конфликты происходят с разными сайтами. Общие замеченные ошибки на сайтах: Теряется функционал выпадающего меню, просмотра прикрепленных офисных документов, отображение модальных окон и их содержимого.

**Comment by derjanb** [comment]
Can you please name some URLs that show conflicts? Does this happen with all scripts disabled as well?

**Comment by tox-x** [comment]
Для примера могу привести один сайт, другие не помню, но ситуация похожа.
https://oblsport43.ru - при наведении на пункт "Документы" не появляется  
выпадающее меню.
Если отключить ваше дополнение, то выпадающее меню появляется.

Jan Biniok <notifications@github.com> писал(а) в своём письме Sat, 28 Mar  
2020 22:27:38 +0300:

> Can you please name some URLs that show conflicts? Does this happen with  
> all scripts disabled as well?

**Comment by tox-x** [comment]
Заметил ещё кое что. Если сайт построен на Joomla, версия старше 3x, то  
наблюдаются конфликты.
В версии 3x конфликты только со скриптами некоторых компонентов, большей  
частью связанных с администрированием/редактированием...

Jan Biniok <notifications@github.com> писал(а) в своём письме Sat, 28 Mar  
2020 22:27:38 +0300:

> Can you please name some URLs that show conflicts? Does this happen with  
> all scripts disabled as well?
>

**Comment by tox-x** [comment]
Сегодня заметил, что при включенном расширении не работает увеличение изображений по клику. Например, можете попробовать с включенным расширением, в браузере GoogleChrome, кликнуть по какой нибудь фотографии здесь: https://prestige-gimnasia.ru/fotogalereya/den-gimnazii-2020.html

**Comment by 7nik** [comment]
@tox-x, у меня на первом сайте меню выпадает, на втором просмоторщик изображений работает без нареканий. Вы уверены, что проблемы вызваны именно расширением, а не одним из установленных юзерскриптов?

**Comment by derjanb** [comment]
@7nik Thanks.
