### ISSUE TITLE
can't login onedrive???

### ISSUE THREAD

**Issue by RussiaVk** [Tampermonkey/tampermonkey#888]
(Please fill out the issue template with your details)

## Actual Behavior
![image](https://user-images.githubusercontent.com/43515485/76931063-db767700-6922-11ea-8062-04d03a97949c.png)

## Specifications

- Chromium:  80.0.3987.132
- TM: (i.e. 4.10.6111)
- OS: (i.e. WIN10)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Hi, this is working fine here. The log message of the penultimate line indicates that this was a network/server issue. Do you still see this issue?

**Comment by RussiaVk** [comment]
> Hi, this is working fine here. The log message of the penultimate line indicates that this was a network/server issue. Do you still see this issue?

problem still existed.

![image](https://user-images.githubusercontent.com/43515485/77848942-b1626600-71fa-11ea-99bc-b65bf7427783.png)
![image](https://user-images.githubusercontent.com/43515485/77848945-b7f0dd80-71fa-11ea-8e32-f4af7b49d5af.png)

**Comment by RussiaVk** [comment]
I install 4.8.41 version of TM and try again but still get me error
![image](https://user-images.githubusercontent.com/43515485/78633228-a3d06e80-78d3-11ea-9425-dc6a9b6dbb73.png)

**Comment by derjanb** [comment]
> I install 4.8.41 version of TM and try again but still get me error

@RussiaVk Looks Tampermonkey's permission to use OneDrive is denied. Please check at https://account.live.com/consent/Manage

I've also improved TM's OneDrive error handling at the latest beta 4.11.6116
