### ISSUE TITLE
Chrome CORB block GM_XMLHttpRequest

### ISSUE THREAD

**Issue by elig0n** [Tampermonkey/tampermonkey#890]
Chrome is blocking my GM_XMLHttpRequest if I put them in a window.addEventListener function, or even sometimes arbitrarily with the message

 `Cross-Origin Read Blocking (CORB) blocked cross-origin response https://... with MIME type .... See https://www.chromestatus.com/feature/5629709824032768 for more details.`

**Comment by derjanb** [comment]
Can you please tell me your Chrome and Tampermonkey version? 
Please attach a screenshot where the message is visible, if possible. Thanks.
