### ISSUE TITLE
在最新版Edge Browser中无法运行

### ISSUE THREAD

**Issue by Johnliang12** [Tampermonkey/tampermonkey#891]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Can not reproduce. What is your Microsoft Edge, Tampermonkey and Windows version?

**Comment by Seventth** [comment]
@derjanb I can probably be able to specify as Tampermoney isn't working on my Edge browser as well. Just endlessly loads and when trying to manage it, you get an error prompt.

![March_25_2020-19-06-30](https://user-images.githubusercontent.com/25657372/77602915-1a896700-6ee5-11ea-8816-37d8fcd721b5.gif)

Here my specifications.
Microsoft Edge Version: 44.18362.449.0 (HTML 18.18363)
Tampermonkey Version: 4.9.5942
Windows Version: Windows 10 Home Version 10.0.18363 Build 18363

If you need anything, let me know!
