### ISSUE TITLE
Does distributing under a proprietary license violate GPL?

### ISSUE THREAD

**Issue by test8421** [Tampermonkey/tampermonkey#902]
Tampermonkey below version 2.9 as discribed is released under GPL. But newer versions are distributed under a proprietary license. Does it violate GPL for developing derivatives without disclosing source?

**Comment by derjanb** [comment]
No. :-)

**Comment by test8421** [comment]
> 
> 
> No. :-)

Could you explain why......? =_=

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Yeah, why? I expect that it violates the license.

**Comment by Thaodan** [comment]
He can change the license if he is the sole author.
