### ISSUE TITLE
Google Images is zoomed when scrolling mouse when the addon is enable

### ISSUE THREAD

**Issue by ooker777** [Tampermonkey/tampermonkey#903]
When the addon is enable (via the addon's menu, not in Firefox's addon manager), this happens, even though no script is enable on this site

## Expected Behavior
Google Images scrolls up and down when scrolling mouse

## Actual Behavior
It zooms instead

## Specifications

- 76.0b2 (32-bit)
- Windows 7

**Comment by raszpl** [comment]
did you install some zoom script by any chance?

**Comment by ooker777** [comment]
hmm yes. I install the [Zoom Page WE)](https://addons.mozilla.org/en-US/firefox/addon/zoom-page-we/ "Zoom Page WE – Get this Extension for 🦊 Firefox (en-US)") addon. So is this a conflict between the two? Whose fault is this?
