### ISSUE TITLE
: ) README

### ISSUE THREAD

**Issue by GFRPIG** [Tampermonkey/tampermonkey#907]
感谢你的付出，请为中国用户提供支付途径（比如微信、支付宝）
Thank you for your efforts, please provide Chinese users with payment channels (e.g. WeChat, Alipay)

**Comment by derjanb** [comment]
I'd really would like to and once I had a working implementation, but the payments processor says that donations/funding are not allowed. I also registeres an international Alipay account, but the payment functionality is disabled there.

Duplicate of #674
