### ISSUE TITLE
谷歌浏览器中插件出现问题，百度界面出现混乱。

### ISSUE THREAD

**Issue by SukiGakki** [Tampermonkey/tampermonkey#909]
(Please fill out the issue template with your details)
谷歌浏览器中插件出现问题，百度界面出现混乱。并且第一次搜索结果并没有呈现分块的那种效果，和普通的搜索结果界面一样。
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact the script developer. Thanks.
