### ISSUE TITLE
Tampermonkey issues

### ISSUE THREAD

**Issue by Tenshikoba** [Tampermonkey/tampermonkey#910]
(Please fill out the issue template with your details)

## Expected Behavior
For it to work at all

## Actual Behavior
It doesn't work with any script

## Specifications
How do I fix this, does this even work at all?
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
all scripts
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
I need more details than a simple "it doesn't work". Browser, TM and OS version would be a good starting point. Maybe even the page where a script should run at and what script.

**Comment by BenjD90** [comment]
I have the same issue since TM V 4.10, the match is not detected :/

on Chrome : Version 81.0.4044.113 (Official Build) (64-bit)

thanks for any help
