### ISSUE TITLE
[feature request] support authentication via browser.identity api

### ISSUE THREAD

**Issue by Alino** [Tampermonkey/tampermonkey#911]
hi Jan, first I want to thank you for developing this extension, I just made a small donation.

I wanted to discuss the following:

I need to write user scripts which are using api calls requiring an auth token.
This token can be obtained after identity server is setup with the redirect URI.
This redirect URI has to be static, (there is already browser API for this browser.identity.getRedirectURL())

Can we somehow expose browser.identity webextension API to user scripts, so that our scripts can achieve this?

browser.identity -> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity

I would like to help standardize this somehow, so that also greasmonkey and violentmonkey would add support for this.

**Comment by derjanb** [comment]
I don't get this at the moment.

Looking at Mozilla's example:

```JS
function authorize() {
  const redirectURL = browser.identity.getRedirectURL();
  const clientID = "664583959686-fhvksj46jkd9j5v96vsmvs406jgndmic.apps.googleusercontent.com";  
  const scopes = ["openid", "email", "profile"];
  let authURL = "https://accounts.google.com/o/oauth2/auth";
  authURL += `?client_id=${clientID}`;
  authURL += `&response_type=token`;
  authURL += `&redirect_uri=${encodeURIComponent(redirectURL)}`;
  authURL += `&scope=${encodeURIComponent(scopes.join(' '))}`;

  return browser.identity.launchWebAuthFlow({
    interactive: true,
    url: authURL
  });
}```

Why can't you just define your own redirect URI (for example use Github or any other page), make your script run at that URL to get the access token and open a new with ```authURL``` to start the process?

**Comment by Alino** [comment]
Regarding browser.identity.getReridectURL - It would be better if we could reuse the native browser API, instead of having to host a page somewhere by ourselves and deal with issues such as availability etc.

Regarding browser.identity.launchWebAuthFlow - this launches a new popup window to authenticate.
It's hard to reimplement in user script, because the http request should not be called from content script, but rather background page. Even if we could forge the request from user script somehow, it could potentially cause cross browser compatibility issues. (I had some issues related to auth with popups in firefox, but not in chrome when I was developing an extension, but using this browser.identity api works well across browsers)
