### ISSUE TITLE
Allow script to auto update, even with major changes

### ISSUE THREAD

**Issue by indeed-a-genius** [Tampermonkey/tampermonkey#914]
I don't like the "UserScript update" tabs appearing every time one of my scripts has an update, interrupting my browsing.

One solution would be for the user to mark scripts as trusted, so they always auto update without user action. There is the "Don't ask me for simple script updates", but that only applies to minor updates.
I imagine a warning would be needed, since it can be potentially dangerous. Although I assume most users don't analyze the code changes every time anyway.

Alternatively, instead of the "UserScript update" popup, a less annoying method would be a notification badge on the TM icon.

**Comment by derjanb** [comment]
There is an option called "Don't ask me for simple script updates". If this is enabled, then only updates which modify where a script is allowed to run at should show that prompt.

![image](https://user-images.githubusercontent.com/767504/80014484-a8e70d80-84d0-11ea-824c-d3996c8a2367.png)

**Comment by indeed-a-genius** [comment]
The script that usually triggers the prompt for me is HandyImage, and it's one where `@match` changes are quite frequent and necessary. [Example](https://github.com/Owyn/HandyImage/commit/f970f7822a9e9d5923ad861e269d58f52bf404dc#diff-73d03a047f9407d1e1bdaf480a25d368)
Trusting it would make my browsing distraction-free.
But thank you for the `@require` local file suggestion.

**Comment by gabri25ele** [comment]
also for me HandyImage requires update manually.
possibile to have update silently for every type of script?
At least we need a little notifiy, not else.

**Comment by AhmadIbrahiim** [comment]
@derjanb  Is contribution open? Can I make a checkbox for Auto-update? Which updates itself automatically once a new version detected?

**Comment by tchuke** [comment]
@derjanb, could you please document -- in your FAQs or a Settings tab [?] tooltip -- what exactly makes a script update "simple" or not?  Having this clearly defined would help developers and users like me!

Jan, what other types of userscript header changes besides an add/edit of an **@include** mark an update as non-simple?  

I did clone the repo to try to figure the criteria out myself, but ideally userscript consumers and developers should not need to search through source code to understand what a Settings checkbox exactly does.

Thanks for your help and work on this project!

**Comment by derjanb** [comment]
Will do. In the meanwhile see https://github.com/Tampermonkey/tampermonkey/issues/1098#issuecomment-746840836

**Comment by L0rent** [comment]
> There is an option called "Don't ask me for simple script updates". If this is enabled, then only updates which modify where a script is allowed to run at should show that prompt. If the modification is a major one, then this dialog is intended behavior. Have you thought about using `@require` to require a local copy which is loaded from disk every run? Also the "Update" button is preselected, so you can also press the enter key when the dialog opens.
> 
> > Although I assume most users don't analyze the code changes every time anyway.
> 
> Maybe, but at least they are reminded that the script is there.
> 
> ![image](https://user-images.githubusercontent.com/767504/80014484-a8e70d80-84d0-11ea-824c-d3996c8a2367.png)

Thank you, but, where does @require go?
I have "Bypass All Shortlinks Debloated"installed (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/). This script is updated very often a tab offering me an update interrupts my browsing several times a day.

**Comment by gabri25ele** [comment]
> Thank you, but, where does @require go? I have "Bypass All Shortlinks Debloated"installed (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/). This script is updated very often a tab offering me an update interrupts my browsing several times a day.

 **Codeberg is currently unavailable for technical reasons.**

_There was a certain project which was banned from GitHub due to "Excessive Bandwidth Usage" - guess where they moved to? We're currently blocking web access while we clean some things up. We expect to return in about 5 - 10 minutes. Sorry for the inconvenience._

**Comment by L0rent** [comment]
> > Thank you, but, where does @require go? I have "Bypass All Shortlinks Debloated"installed (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/). This script is updated very often a tab offering me an update interrupts my browsing several times a day.
> 
> **Codeberg is currently unavailable for technical reasons.**
> 
> _There was a certain project which was banned from GitHub due to "Excessive Bandwidth Usage" - guess where they moved to? We're currently blocking web access while we clean some things up. We expect to return in about 5 - 10 minutes. Sorry for the inconvenience._

what does this have to do with my question?

**Comment by gabri25ele** [comment]
> > > Thank you, but, where does @require go? I have "Bypass All Shortlinks Debloated"installed (https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/). This script is updated very often a tab offering me an update interrupts my browsing several times a day.
> > 
> > 
> > **Codeberg is currently unavailable for technical reasons.**
> > _There was a certain project which was banned from GitHub due to "Excessive Bandwidth Usage" - guess where they moved to? We're currently blocking web access while we clean some things up. We expect to return in about 5 - 10 minutes. Sorry for the inconvenience._
> 
> what does this have to do with my question?

a little bit.
offiline, so it doesn't update itself
and then (not have to do with your question), I can try it
