### ISSUE TITLE
I cannot download 

### ISSUE THREAD

**Issue by Alexander403** [Tampermonkey/tampermonkey#915]
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```
<img width="609" alt="屏幕快照 2020-04-20 上午9 45 21" src="https://user-images.githubusercontent.com/57257343/79707158-21da3f80-82ee-11ea-9412-071753ba3f18.png">
![Uploading 屏幕快照 2020-04-20 上午9.45.08.png…]()

**Comment by derjanb** [comment]
This is not a Tampermonkey dialog. Please contact the script developer.
