### ISSUE TITLE
setClipboard API sets the clipboard to "undefined"

### ISSUE THREAD

**Issue by renaws** [Tampermonkey/tampermonkey#918]
(Please fill out the issue template with your details)

## Expected Behavior
setClipboard API should set the clipboard to the specified value

## Actual Behavior
setClipboard API sets the clipboard to the string "undefined".
This is a regression from version 4.10.6105.
Removing Tampermonkey 4.10.6112 and reinstalling 4.10.6105 restores the setClipboard API

## Specifications

- Firefox: 75.0
- TM: 4.10.6112
- OS: Ubuntu 18.04 LTS

- Firefox: 75.0
- TM: 4.10.6112
- OS: Windows 10 1909 (18636.778)

## Script

```js
// ==UserScript==
// @name         Clipboard Test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Script to test GM.setClipboard in Tampermonkey 4.10.6112
// @author       renaws
// @match        https://*.tampermonkey.net/
// @grant        GM.setClipboard
// ==/UserScript==

(function() {
    'use strict';

    GM.setClipboard('test string');
})();
```

**Comment by derjanb** [comment]
Will be fixed soon.

Note: GM_setClipboard is working fine and can be used as a workaround.
