### ISSUE TITLE
window.close() doesn't work when current tab is the last tab remaining in window

### ISSUE THREAD

**Issue by mariusa** [Tampermonkey/tampermonkey#919]
(Please fill out the issue template with your details)

1. open new incognito window
2. go to https://www.google.com/
3. console log shows 'closing', but it doesn't close
4. open a new tab (a 2nd tab)
5. go to https://www.google.com/
6. window is closed

## Expected Behavior
3. close the window, even if it's only 1 tab

## Actual Behavior
window doesn't close, because it's the last tab. If not the last tab, it works.

## Specifications

- Chromium: 81
- TM: 4.9
- OS: Fedora

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.google.com/
// @grant        GM_openInTab
// @grant        window.close
// @grant       window.focus
// ==/UserScript==

(function() {
    'use strict';
console.log('closing')
    window.close();
})();
```

**Comment by derjanb** [comment]
This is intended behavior. Just think about your example script having an additional line:

```JS
// @match        *://*/*
```

**Comment by mariusa** [comment]
Thanks for your comment, Jan! I'm not sure I get it though. 

The ```@match``` is on a very specific pattern, ```https://www.google.com/``` is just an example.
If we want to close the last tab of a specific window (out of several windows), why not allow that?

**Comment by highspeeder** [comment]
I have the same problem.

The following error occurs in content.js.

content.js:19 refused to close last tab!

![1](https://user-images.githubusercontent.com/41020549/98775999-864b2080-2431-11eb-86fc-f72c0445c31a.PNG)

**Comment by derjanb** [comment]
@highspeeder This is desired behavior to prevent jokes like thiis:

```JS
// ==UserScript==
// @name         close 'em all
// @namespace    http://eviljokes.com/
// @version      0.1
// @description  close 'em all
// @author       Joker
// @match        *://*/*
// @grant        window.close
// ==/UserScript==

window.close();
```

**Comment by highspeeder** [comment]
`
// ==UserScript==
// @name         test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.google.com
// @grant        window.close
// ==/UserScript==


window.close();
`
I tried the same, but the result was the same.

**Comment by derjanb** [comment]
> What does this mean?

It matches all URLs and therefore runs runs in every tab.

**Comment by highspeeder** [comment]
I want to apply it to a specific window.

**Comment by highspeeder** [comment]
Also, this code gives the same error in the unsafewindow function.
'refused to close last tab!'

// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// @grant        window.close
// ==/UserScript==

var myfunc = unsafeWindow.myfunc = {};

myfunc.winClose = function(){
    window.close();

};

**Comment by ittayd** [comment]
@derjanb , Why is it OK to close the 2nd tab, but not the first? Why can the first be closed if the 2nd remain? I can have a script match on all tabs and run it on 20 open tabs. It'll close 19 and leave one random.

**Comment by derjanb** [comment]
@ittayd see https://github.com/Tampermonkey/tampermonkey/issues/919#issuecomment-725259726

**Comment by ittayd** [comment]
@derjanb the joke mentioned will close all tabs except one. so this makes the joke work 99% of the time. In my case I have tabs that open just to run a rest call and I want to close them once the response (page) returns

**Comment by derjanb** [comment]
> so this makes the joke work 99% of the time

That's the point. With one tab open you can open Tampermonkey and disable the script. This does not work if you open Chrome and it is instantly closed by a joke script again.

**Comment by ittayd** [comment]
So tampermonkey should prevent closing the last tab in the last window. But I imagine it may not be easy to achieve. An alternative is to have a 'safe' mode in which TM loads, but doesn't run any script.

**Comment by RustinHaaseCSS** [comment]
I've just spent a bunch of time trying to get a maximized webapp the ability to close its one and only window, I suggest two things that could keep the user safe enough from lockout:

- Only close upon button press
- Ask for confirmation before closing the last tab, just like how browsers ask if you want to lose your progress w/o tab saving.

I think this'd be safe enough to allow this as a feature.

The discovery of this action being prohibited was really disappointing and I'll need to find another solution.

**Comment by tmackarel-r7** [comment]
I use arc browser, and closing the last tab is not an issue since there are dozens of other pinned tabs available. It doesn't close the browser window or anything. This isn't a big deal or anything, but in the modern browser world maybe this needs a rethink?

**Comment by trumad** [comment]
I use arc browser, and closing the last tab is not an issue since there are dozens of other pinned tabs available. It doesn't close the browser window or anything. This isn't a big deal or anything, but in the modern browser world maybe this needs a rethink?
