### ISSUE TITLE
Add version number to TM menu

### ISSUE THREAD

**Issue by jb222** [Tampermonkey/tampermonkey#922]
Thanks for adding the version number in the tab name. This follow-up will help choosing the right userscript while developing.

![tm-versionnumber3](https://user-images.githubusercontent.com/61352184/80373070-ccc19f00-8894-11ea-8db1-f18a8e0a0730.png)

**Comment by derjanb** [comment]
I agreed on adding the version number to the options page's tabs, but it isn't it very unlikely to have many scripts with exactly the same name but different versions running at the page at the same time? Space is rare on the action menu, there for I tend to not add this feature.

**Comment by jb222** [comment]
The only one running is the one with the green slide button. But right now, in the menu it's not possible to know the version number. So I have to go to the dashboard...
