### ISSUE TITLE
Why not add a payment method for Chinese with no international payment to donate?

### ISSUE THREAD

**Issue by MicroBlock2017** [Tampermonkey/tampermonkey#924]
I want to donate, but I failed to find an easy payment method.
Could you add a payment method for Chinese like WeChat Pay or Alipay?

**Comment by derjanb** [comment]
I'd really would like to and once I had a working implementation, but the payments processor says that donations/funding are not allowed. I also registered an international Alipay account, but the payment functionality is disabled there. 

I'm open to suggestions.

Duplicate of #674
