### ISSUE TITLE
GM_openInTab return Window Object ?

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#925]
(Please fill out the issue template with your details)

## Expected Behavior
GM_openInTab returns window object

## Actual Behavior
only clsoe handler is returned

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. Win 10)

**Comment by derjanb** [comment]
It is not possible to return the window object, because there is no way to get it in this context. 

What property do you want to access? You can make your script run at the new tab's URL as well and access the window object this way.

**Comment by jonnytest1** [comment]
well tbh its probably worse than what u imagine im opening a window from one tab and then later want to close it (at best  from the opened window itself  ) but for now i was trying to send the current url per valuechangelistener and then clsoe it from the first tab -  mainly im trying to get around the whole u can only close the window from the script it was created from


(lets ignore for now that most likely the first tab already opened another url and now has no reference to the variable anymore)

**Comment by derjanb** [comment]
Please check out ```// @grant window.close```.

https://www.tampermonkey.net/documentation.php#_grant
