### ISSUE TITLE
Tampermonkey not running scripts in Firefox Dev Edition 77.0b3

### ISSUE THREAD

**Issue by madmuffinz** [Tampermonkey/tampermonkey#926]
All of my scripts are no longer running on Firefox Developer Edition 77.0b3 (I usually keep dev ediotion up to date)
I am not sure if it's the addon or the browser itself. I am not sure which setting to look into, since I never changed my settings. 
I normally use the stable version of Tampermonkey, and I tried installing Tampermonkey Beta, but I have the same results.

Any settings or flags I should look into?

**Comment by madmuffinz** [comment]
I've noticed that these script work that applies to direct URLs such as images:
https://greasyfork.org/en/scripts/2312
https://greasyfork.org/en/scripts/36662

**Comment by derjanb** [comment]
Both scripts are working (or at least running) fine here using 77.0 (64-bit).

Example: https://pbs.twimg.com/media/EY5bSsgU8AAR3mD?format=png&name=small
