### ISSUE TITLE
Problems with script export

### ISSUE THREAD

**Issue by lhj5426** [Tampermonkey/tampermonkey#927]
Problems previously reported

I'm giving you feedback now

The previous problem was that when 197 or 200 scripts were exported at one time, they would be infinite

Now, can I export in batches? Can I solve the problem of stuck mass script export? Or can I add a batch to select some scripts? It's convenient to export a large number of scripts in batches

It's too much trouble to select only one script
![image](https://user-images.githubusercontent.com/30548000/81491490-c3d3c300-92c1-11ea-94d8-49825668e478.png)

**Comment by derjanb** [comment]
Duplicate of #1020
