### ISSUE TITLE
TM 4.10 window.* access

### ISSUE THREAD

**Issue by goodwin64** [Tampermonkey/tampermonkey#932]
Hi there! I have a question about the global `window` object and how the TamperMonkey user script can access it.

My question is similar to the https://github.com/greasemonkey/greasemonkey/issues/2741 from GM repo. I have a script that tries to access the global `window` object in the following way:

```js
// top
window._sharedData = { x: 1 };

// Javascript context: Tampermonkey
console.log(window._sharedData) // undefined
console.log(window)             // prints window
```

but with no result. What I have to add to access to the `window` object? And is it even possible?

- Chromium: 81.0.4044.138 (Official Build) (64-bit)
- TM: 4.10
- OS: Win 10

## Script

(Please give an example of the script if applicable.)

Link to the script: https://greasyfork.org/en/scripts/38743-instagram-followers-liker
Line of code: 161

**Comment by derjanb** [comment]
If the script uses ```@grant none``` then ```window``` is the global Window object and ```unsafeWindow``` otherwise. If ```_sharedData``` is not present when the script runs, then it might be initialized by the page's scripts at a later time. You can use

```JS
window.setInterval(() => console.log(window._sharedData), 1000)
```

to log every second.

**Comment by goodwin64** [comment]
The aforementioned script uses interval and the `window._sharedData` is still not accessible:

![3](https://user-images.githubusercontent.com/10671879/81968632-50b1b000-9625-11ea-96fa-62aef1dc5207.png)

It's available in the "top" scope:

![1](https://user-images.githubusercontent.com/10671879/81968625-50191980-9625-11ea-94e4-fb54896ab5be.png)


But not in the TM scope:

![2](https://user-images.githubusercontent.com/10671879/81968629-50b1b000-9625-11ea-86a2-292458757dfa.png)

**Comment by goodwin64** [comment]
Also, I have nothing in the `unsafeWindow` variable:

![image](https://user-images.githubusercontent.com/10671879/81968934-cfa6e880-9625-11ea-8229-f02b6ae18941.png)

**Comment by derjanb** [comment]
My test script is working fine at https://www.instagram.com/

```JS
// ==UserScript==
// @name         _sharedData test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.instagram.com/
// @grant        none
// ==/UserScript==

console.log('SDT:', window._sharedData);
debugger;
```

![image](https://user-images.githubusercontent.com/767504/81972853-86ee3000-9623-11ea-8b2d-3bc906f2b0ed.png)
