### ISSUE TITLE
Script always on pause in debug mode

### ISSUE THREAD

**Issue by selevo** [Tampermonkey/tampermonkey#938]
(Please fill out the issue template with your details)

## Expected Behavior
normal work

## Actual Behavior
pause  debug sreen

## Specifications

win7 x64
opera brauser

![ScreenShot002017](https://user-images.githubusercontent.com/13694921/82136858-27f70980-9823-11ea-9b74-d476f5467466.jpg)

There is a pause of debugging constantly, in the browser opera.
With any scripts.
The scripts work fine, this only happens if I turn on the development tool.

There is no such anomalous behavior in Google Chrome.
Maybe someone knows how I can solve this problem?
It annoys me very much, it seems this is some kind of idiotic setting from the creators of the Opera browser, but I do not know where it is or what it is called.

## Script

(Please give an example of the script if applicable.)

```

**Comment by AhmetEmsal** [comment]
Remove all breakpoints. Image : [https://i.stack.imgur.com/NBAzK.png](https://i.stack.imgur.com/NBAzK.png)

**Comment by selevo** [comment]
> Remove all breakpoints. Image : https://i.stack.imgur.com/NBAzK.png

Thank!
I have no breakpoints but I understood your note.

**Comment by derjanb** [comment]
Please remove all ```debugger``` statements from your script and make sure the Tampermonkey option `Debug scripts` is disabled.
