### ISSUE TITLE
Tampermonkey for new Android Firefox (Preview)

### ISSUE THREAD

**Issue by Couchy** [Tampermonkey/tampermonkey#940]
Hi, I was wondering if Tampermonkey devs were aware of the Firefox reboot for Android and if anything was being done to ensure compatibility with this upcoming version. Theoretically, existing Firefox extensions should just work, but Mozilla is only allowing us to install select "recommended extensions" now, and they're moving very slowly on this - they allowed uBlock Origin in February and 6 other extensions last month. We might have to push for Tampermonkey to be included as a recommended extension, assuming it works (which it hopefully does).

https://blog.mozilla.org/addons/2020/04/14/april-extensions-for-firefox-preview/

**Comment by derjanb** [comment]
I'm aware of this and I hope they will open Firefox Preview for more extensions soon.

**Comment by derjanb** [comment]
@all Feel free to give Mozilla feedback on the lack of general extension support:

https://play.google.com/store/apps/details?id=org.mozilla.firefox&showAllReviews=true
https://support.mozilla.org/en-US/questions/1298184

**Comment by Couchy** [comment]
lol, believe me, I have. Now I'm stuck using Yandex (yuck) since it's now the only Android browser with real extension support.

**Comment by derjanb** [comment]
"We are also working on enabling support for persistent loading of all extensions listed on addons.mozilla.org (AMO) on Firefox for Android Nightly. This should make it easier for mobile developers to test for compatibility, and for interested users to access add-ons that are not yet available on release. You can follow our progress by subscribing to this issue. We expect to have this enabled later this month."

https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/

**Comment by Martii** [comment]
I actually learned how to install an older APK on my device because even the current "recommended extensions" don't work under the current Android Fx... which I find amusing. So totally disappointed. 

As far as Yandex goes, at least on my device, it seems to not support extensions anymore but haven't spent a whole lot of time examining why I got those results last month... plus I'm a desktop user most of the time.

**Comment by alpe12** [comment]
> I actually learned how to install an older APK on my device because even the current "recommended extensions" don't work under the current Android Fx... which I find amusing. So totally disappointed.
> 
> As far as Yandex goes, at least on my device, it seems to not support extensions anymore but haven't spent a whole lot of time examining why I got those results last month... plus I'm a desktop user most of the time.
> 
> I stand corrected on Yandex... Tampermonkey from the Chrome store says it's not compatible. VM installed though.

On Kiwi browser it works.

**Comment by derjanb** [comment]
FYI: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by Couchy** [comment]
> On Kiwi browser it works.

I was going to advise against using Kiwi since it hadn't been updated for a year, but it looks like it finally updated October 10th. Hopefully they can keep up with Chromium now.

**Comment by ajayyy** [comment]
The Kiwi browser update is still based off a really old version of chromium.

I suggest trying [ungoogled-chromium-android-extensions](https://uc.droidware.info/extension.html).

**Comment by Eccenux** [comment]
Great to see some progress 🙂. Works on FF Nightly. Hopefully the will move it to default collection at some near future... I hope I can finally update my FF 😉

![](https://user-images.githubusercontent.com/1045235/101613263-db1b9000-3a0b-11eb-929e-869be3513b41.png)

**Comment by MagpieFourtyTwo** [comment]
Yep, already tried and is still installed, nevertheless Kiwi is still first choice, cause FF Nightly crashes a lot.
Don't know what they have done to good old FF ... it was the very best browser and an unrestricted recommendation for decades, but since v68 things are getting worse and worse ... on smartphone *and* windows pc ...  :/

**Comment by Rosabis** [comment]
> Great to see some progress 🙂. Works on FF Nightly. Hopefully the will move it to default collection at some near future... I hope I can finally update my FF 😉
> 
> ![](https://user-images.githubusercontent.com/1045235/101613263-db1b9000-3a0b-11eb-929e-869be3513b41.png)

But when I access some sites such as reddit with some script,the browser will crash🤔

**Comment by Eccenux** [comment]
> But when I access some sites such as reddit with some script,the browser will crash:thinking:

Might be a problem with the script. Not TM. Didn't experience any problems myself. And on one site I have 26 scripts installed (Ingress Intel).

**Comment by MulverineX** [comment]
Any updates on this?

**Comment by MagpieFourtyTwo** [comment]
If not: Currently using FF Nightly with TM installed - works like a charm.
It's a bit tricky to install (via [Collections](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)), but once this is done, everything is perfectly fine.

**Comment by zxkmm** [comment]
Try[ Iceraven ](https://github.com/fork-maintainers/iceraven-browser), a fork of Firefox-Android with Tampermonkey support. Works fine and stable in my device.

**Comment by Eccenux** [comment]
Interesting, but seems like an early alpha now. Seems like FF Nightly is more stable for now.

**Comment by MagpieFourtyTwo** [comment]
Did not even know Iceraven until @zxkmm mentioned it, gave it a try - and it's working perfectly fine over here. Replaced FF and FF Nightly completely. Right now I'm using Iceraven only. With Tampermonkey (with e. g. "GC little helper II", "GCVote" and "Mystery Wizard") and some more AddOny. Had not a single crash or hang,

**Comment by derjanb** [comment]
Tampermonkey is officially available for FF Android

**Comment by eadmaster** [comment]
I've tried reinstalling, but the settings page appear empty for me on FF Beta.
