### ISSUE TITLE
Even after uninstalling AllMyTube script & tampermonkey, download popup still shows

### ISSUE THREAD

**Issue by AniketNBorhade** [Tampermonkey/tampermonkey#942]
(Please fill out the issue template with your details)

## Expected Behavior
It should not show the download popup

## Actual Behavior
Even after uninstalling AllMyTube script & tampermonkey, download popup still shows
Screenshot link: https://ani.d.pr/ZTvWSA

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please reload the tab. After uninstalling Tampermonkey no script can be injected anymore, but already loaded tabs might have scripts still running.
