### ISSUE TITLE
GM_info.isIncognito is not returning the correct value

### ISSUE THREAD

**Issue by frozenbits** [Tampermonkey/tampermonkey#943]
GM_info.isIncognito is not returning the correct value in Firefox 76.0.1. 
Tested in Chrome 81.0.4044.138 and it worked.

## Expected Behavior
GM_info.isIncognito is expected to return true when the window is an incognito window.

## Actual Behavior
GM_info.isIncognito returns false in Firefox 76.0.1 even when the window is an incognito window.

## Specifications

- Firefox: 76.0.1 (this is the one with the issue)
- Chromium: 81.0.4044.138 (no issue here, just for comparison)
- TM: 4.10.6112
- OS: Windows 10 Build 18363.836

## Script

```js
(function() {
    'use strict';
    console.log(GM_info)
    console.log(GM_info.isIncognito) 
    if(!GM_info.isIncognito){
        //code here
    }
})();
```

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.11.6113 (https://www.tampermonkey.net/index.php?browser=firefox)
