### ISSUE TITLE
grepoils

### ISSUE THREAD

**Issue by kmclark16** [Tampermonkey/tampermonkey#946]
(Please fill out the issue template with your details)

## Expected Behavior
quit working they say they dont support it any more and got told they never did but they did i know that for a fact 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by kmclark16** [comment]
any help with this would help me greatly

**Comment by derjanb** [comment]
Please contact the script developer.
