### ISSUE TITLE
mole-hole

### ISSUE THREAD

**Issue by kmclark16** [Tampermonkey/tampermonkey#947]
(Please fill out the issue template with your details)

## Expected Behavior
none it quit working

## Actual Behavior
none it stops doing anything its needs to do and in sted   makes the screen jump of a different view to different  

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by kmclark16** [comment]
/ ==UserScript==
// @name		Mole Hole - grmh.pl
// @version		1.18
// @author		Tropsy Kreets
// @namespace		GRMH
// @description		extension of the Grepolis game
// @updateURL    	https://grmh.pl/MHscript/MH_install.user.js
// @downloadURL		https://grmh.pl/MHscript/MH_install.user.js
// @include		https://*.grepolis.*/game*
// @include		https://*.grepolis.*/start?action=select_new_world
// @icon		https://grmh.pl/imgs/icon.ico
// @grant		none
// ==/UserScript==
(function(){
 var s=document.createElement('script');
 s.type='text/javascript';
 s.src='https://grmh.pl/MHscript/MH_script.js?_'+Math.round(new Date().getTime()/60000);
 var l=document.createElement('link');
 l.type='text/css';
 l.rel='stylesheet';
 l.href='https://grmh.pl/MHscript/MH_styles.css?_'+(new Date().getDay());
 document.body.appendChild(s);
 document.body.appendChild(l);
})();

**Comment by kmclark16** [comment]
i would like to learn how do make these kinds of scripts and know how to get them approved

**Comment by derjanb** [comment]
Please contact the script developer.
