### ISSUE TITLE
moll holl

### ISSUE THREAD

**Issue by kmclark16** [Tampermonkey/tampermonkey#950]
(Please fill out the issue template with your details)
quit working and no longer supported by grepoils 
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Please contact the script developer.

**Comment by kmclark16** [comment]
u should have dont before the changes  and u didnt the game sucks so im npi
playing it until iy gets fixed

**Comment by kmclark16** [comment]
tell me who it is

**Comment by kmclark16** [comment]
and how to get a hold of them

**Comment by kmclark16** [comment]
Hi Tampermonkey/tampermonkey

To create your new password, click on the link below.
Create New Password
http://links.site-members.com/ls/click?upn=qWuWkJQJpo5z7cySPDdSfRqrSCeTUE-2BTJmWngX52O00nAjJBPJZjJ3Rh73VAOJ-2FmbTVpESYC2plZ1joJtEziTPh3B2sweVcnsswv2zeSiIqcBISxmd4U9dUahDhlVTkzxRIyku1otXQAzUhApLAZ2ZVmiTDZcZKLkR8I0UWQLCtmji95PXV0rsNR2PWUOlHs0TDWQ22j9F0RKM1plja7h0gUz2aLVqQzuiVj4HsqNrw-3D_wln_U31jt5HgHBh7k3Grc5s4l59g1SKfaSMnQMom6EaDfgrka4zAaV7DAyHgNsByzUeokGUvLhGSiMEABZtITzqc9byRuwbQO9gnQHejBfb8JRhbr8aGu1CQX82XeBIdZIOx1CvtY2IrikIggB-2B-2FqwOc5xBx5RavxesWyn6gQBrziJXMaV0yAU56ki9pY3YhzoTrzE3ExBkVBIC0znnkMjdjVhBozsEHFh7XRo-2BPlzE9qlMuxXa2oBTBq7npLr4tQ7JCuhnFw-2FmPR5-2FUxZB2JSUvR-2BUlqJf-2Bl4-2FQmglRYssYSpk8HiN-2BZMIJ4epg8phNL9gtf2uAJqSPrL3YIr3Hf0MIZ1-2F5buJj3LjGRfygqTdazf7ahsfDcf618UCoP5CoJVmSy3L9EpzFgt6EqtYxs6E0tkN7-2FY8Hg1oMwZZWgAzVFLS9kZ06Jb9BKB9un27tBTH4IBpO6RGYCvz-2FNnS3NlS9tsWTvk90o3FIUe-2FyQhHkeBNuvrSLBFbuSyVs2YSD3MXTQGq5lST4xP2WMsZah-2FHIh3YpYLcKGqeTF9D23EY0ODN8sxEAyoWdMsJ201ShOr9d6UbzbkARO-2BhdoNnEk1R-2F-2Bt2bV8CJ-2F0qZX-2FbEpsSkLrkLc1p6B3xx1a5Gm9sb9db-2FIqfdkQykl4RFtyhf7dYxaVUV8DHn3SPikxw8ZympJgtHigZo14rb7JgdCth5QXql



Thanks!

Please do not reply to this email
