### ISSUE TITLE
Bug: Causes Constant Reload of Duo Login Page in Safari

### ISSUE THREAD

**Issue by Jason-Morcos** [Tampermonkey/tampermonkey#954]
## Expected Behavior
Georgia Tech uses a two-factor login system called "Duo". With the Tampermonkey extension fully disabled from safari settings, the embedded Duo two-factor login view loads and I am able to successfully authenticate. 

## Actual Behavior
With Tampermonkey extension enabled in safari settings (whether or not the extension itself is enabled in its own preferences) the page gets in a reboot loop and I am unable to complete two factor login.

## Specifications
Safari, macOS 10.15.5
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15

## Script
NA

**Comment by ohan8** [comment]
Hi I'm also having this issue. Were you able to fix it?

**Comment by Jason-Morcos** [comment]
> Hi I'm also having this issue. Were you able to fix it?

No, I had to disable it :/

**Comment by compulov** [comment]
I am seeing this same behavior with the Duo frame in Safari 14.0.2 on MacOS 11.1 on Apple Silicon. I don't run into this at all with Tampermonkey in either Firefox or Chrome. If there any more information/diagnostic data I can provide to the devs to try and diagnose this, let me know.

**Comment by darezik** [comment]
I am seeing this same behavior with the Duo frame in Safari 14.0.3 (16610.4.3.1.4) on MacOS 11.2.1 with an intel processor. It doesn't work while Tampermoney is installed but works as soon as it is disabled. Please let me know if there is any more information which would be of help.

**Comment by jdarsey6** [comment]
It also doesn't work with Evernote Safari extension.  Fixed when turned off, and then can turn on after signin.

**Comment by derjanb** [comment]
Should be fixed at 4.20.6184 which is currently rolled out.
