### ISSUE TITLE
Error in the console log

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#955]
Opening the following URL:
https://www.google.com/search?tbm=isch&q=cat&tbs=imgo:1

## Expected Behavior
No errors in the console log

## Actual Behavior
The following error in the console log:
```
Security Error: Content at https://www.google.com/search?tbm=isch&q=cat&tbs=imgo:1 may not load data from blob:moz-extension://cead213d-0b91-4b93-8155-6cc7de3bb687/b7694c43-94c6-41d6-8b0f-c059e064307a.
```

## Specifications

- Firefox developer edition 77.0b9 (64-bit) [Firefox Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0]
- TM beta v4.10.6112
- OS: Windows 10 1903

## Script

All scripts disabled

**Comment by derjanb** [comment]
I can not reproduce this one. I do see Content Security Policy errors, but no security error. Do you have `security.csp.enable` disable or something like this?

**Comment by alexolog** [comment]
Yes, I disabled CSP for now because otherwise many scripts do not run at all.

**Comment by derjanb** [comment]
Closing in favor of #963
