### ISSUE TITLE
GM_xmlhttpRequest.onprogress not called on modern browsers

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#958]
(Please fill out the issue template with your details)

## Expected Behavior
GM_xmlhttpRequest params.onprogress callback, if defined, should be repeatedly called during the transfer

## Actual Behavior
Called not sooner than headers received on modern browsers (progress.readyState == 3), which is when all POST data were already dispatched and progress.loaded == progress.total (specifically on this event  .load already contains header size and .total == -1)

## Specifications

- Chtome 83.0.4103.61, Opera latest, Firefox Quantum latest
- TM: 4.10
- OS: Windows 8.1/x64

## Script
```
GM_xmlhttpRequest(url: url, method: POST, data: formData, headers: { ... },
onprogress: function(progress) {
  console.debug(progress);
},
});
```

## Remarks

The weird thing on it is that on old legacy Firefox 54 (TM 4.10.6112), this callback is called regularly and smoothly during the transfer (bulky request), so it's not being about the callback is wrongly written.

**Comment by WaqasIbrahim** [comment]
@trumpeta Were you able to find a solution to this?

**Comment by derjanb** [comment]
Should be fixed at the current TM/browser versions.  At least my test showed onprogress being called repeatedly.

TM: 4.14.6141 
Browsers: FF 90.0 (64-bit) and Chromium 91.0.4472.114

```JS
// ==UserScript==
// @name         log onprogress
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://example.com/*
// @grant        GM_xmlhttpRequest
// @connect      httpbin.org
// ==/UserScript==

GM_xmlhttpRequest({
    method:   "POST",
    data: 'x'.repeat(1*1024*1024),
    url:      'https://httpbin.org/post?t='+ Date.now(),
    onloadstart: function(e) {
        console.log('onloadstart', e);
    },
    onloadend: function(r) {
        console.log('onloadstart', r);
    },
    onprogress: function(e) {
        console.log('onprogress', (e.loaded / e.total), e);
    },
    onload: function(r) {
        console.log('onloadstart', r);
    },
    onerror: function(r) {
        console.error('onerror', r);
    }
});
```
