### ISSUE TITLE
GM_cookie.list should return Cookies that match the Container tab of the execution context in Firefox.

### ISSUE THREAD

**Issue by ghcsd** [Tampermonkey/tampermonkey#959]
1. Install the following user script in Firefox.  
2. Open the `https://www.google.com` in the default container tab and other container tab respectively.
3. Sign in different google accounts on the two tabs.
----
Sorry for my bad English.

## Expected Behavior
The console of the two tabs output different cookies.

## Actual Behavior
The console of the two tabs outputs the same cookies.

## Specifications

- Firefox 76
- TM 4.10.6112
- OS:  Windows 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         GM_cookie
// @version      0.1
// @match        *
// @grant        GM_cookie
// ==/UserScript==

GM_cookie('list', { url: location.href }, (cookies) => {
	console.log(cookies.map(c => `${c.name}=${c.value}`).join('; '));
});
```

**Comment by derjanb** [comment]
Should be fixed at 4.11.6114
