### ISSUE TITLE
Gm_download won't download name with coma in Firefox

### ISSUE THREAD

**Issue by Yusifx1** [Tampermonkey/tampermonkey#960]
I don't know if I wrote something wrong or there is answer to that. The only answer that I found is to use ",". I am not good with scripts and don't understand why it won't work. Here is problem:

I have script that download files with names. Sometime name contain special character like "/*?" and others why I replace it  with full-width character: ／＊？.
But coma (,) is legal character. In "Kiwi" ( mobile chrome that support extension) it work, but in firefox it won't work. I don't want make coma full-width, because it look ugly and I can't find file. Tried with these methods:
"abc,def"
 "abc\\,def.jpg"
"abc\\u002cdef"

## Expected Behavior
It should save file with coma. Like "some,text,with,coma"

## Actual Behavior
It won't start downloading in firefox

## Specifications

- Latest firefox
- OS: Android 10

## Script
```
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://*
// @grant GM_download
// ==/UserScript==
var url="somelink";

GM_download(url , "aa,gf.jpg" );

GM_download({url: url ,name:"aa,gf.jpg" });

```

**Comment by derjanb** [comment]
This has only been requested once so far.
