### ISSUE TITLE
HandyImage errors

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#965]
HandyImage error message

## Expected Behavior
No log errors.

## Actual Behavior
Console log shows: "Handy Image: Your browser is very very old, please update it."

## Specifications

- Firefox 78.0b3 : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
- TM beta v4.10.6113
- OS: Windows 10 1903

## Script

https://greasyfork.org/scripts/109-handy-image/

Problem likely here:
```js
try
{
	eval(
	'loadCfg = async function ()'+
	'{'+
		'cfg_direct = await GM.getValue("directImage", false);'+
		'cfg_bgclr = await GM.getValue("bgColor", "grey");'+
		'cfg_fitWH = await GM.getValue("fitWH", true);'+
		'cfg_fitB = await GM.getValue("fitB", false);'+
		'cfg_fitS = await GM.getValue("fitS", true);'+
		'cfg_js = await GM.getValue("js", "");'+
	'}'
	);
}
catch(e) // PRE FireFox 53
{
	console.warn("Handy Image: Your browser is very very old, please update it.");
}
```

**Comment by derjanb** [comment]
Can't find that eval at the latest version of that script... 
Also, please always send a URL where the scripts is running at. Thanks.

**Comment by alexolog** [comment]
Fixed by script developer
