### ISSUE TITLE
Problem with autopager script

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#968]
[The Super_preloaderPlus_one_New script](https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new) automatically loads the next page on web site.

It exhibits a problem on certain forum threads that are not visible to unregistered guests where the loaded pages are not passed the user's credentials, but only when running under TM.  Greasemonkey works OK.

Example:
1. Install https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new
2. Go to https://www.trektraxs.com/index.php?topic=8951.0 (username: tampermonkey, password: Tampermonkey4)
3. Scroll to the end of the page

## Expected Behavior
Under GM, the next page is loaded beneath the first one.

## Actual Behavior
Under GM, the "login" page is loaded beneath the first one.

## Specifications
- Firefox 78.0b3 : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
- TM beta v4.10.6113
- OS: Windows 10 1903

## Script

https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new

I suspect the problem is in the handling of the GM.xmlHttpRequest call or the polyfill.

**Comment by derjanb** [comment]
The scripts contains this comment:

```
    } // `options.cookie`, dirty fix for TM and VM on Firefox
    // TODO: remove when TM and VM releases new version
```

Without 

```
        options.cookie = document.cookie;
````
the script is working fine here.

Please report this back to the script developer. Thanks.

**Comment by alexolog** [comment]
Thanks!

I believe a better place to fix it is:
```
    if (BROWSER.name === 'firefox') {
      if (SCRIPT_MANAGER.name === 'Violentmonkey' && compareVersions(SCRIPT_MANAGER.version, '2.12.3') <= 0 || SCRIPT_MANAGER.name === 'Tampermonkey') {
        // `options.cookie`, dirty fix for TM and VM on Firefox
        // TODO: remove when TM releases new version
        logger.warn("[Super-preloader]", `${SCRIPT_MANAGER.name}  v${SCRIPT_MANAGER.version} has a flaw on Firefox, which may affect this script`);
        logger.warn("[Super-preloader]", 'Check https://github.com/Tampermonkey/tampermonkey/issues/786 and https://github.com/violentmonkey/violentmonkey/issues/606 to learn more');
        gotConfig.cookie = true;
      }
    }
```
Can you suggest a TM version for the backward compatibility?

**Comment by alexolog** [comment]
Never mind:  4.10.6103
