### ISSUE TITLE
Missing Searchbar

### ISSUE THREAD

**Issue by MajorMilk90** [Tampermonkey/tampermonkey#969]
(Please fill out the issue template with your details)

## Expected Behavior
A search bar on the top right at all times

## Actual Behavior
If I search for something, the bar itself disappears if I leave the results. Then I have to reload again.

## Specifications

- Firefox: 77.0.1
- TM: 4.10.6112
- OS: Windows 10 Ver. 1903 (Build 18362.836)

![image](https://user-images.githubusercontent.com/25435738/83972197-7177c900-a8a4-11ea-996d-092361eafbf6.png)
![image](https://user-images.githubusercontent.com/25435738/83972230-8ce2d400-a8a4-11ea-9436-05f25dd6e6e4.png)
![image](https://user-images.githubusercontent.com/25435738/83972236-966c3c00-a8a4-11ea-83d5-e70bb66c9b48.png)

**Comment by derjanb** [comment]
What scripts do you have installed? Are there scripts running at Twitter? Does the issue appear if you disable all scripts/Tampermonkey?
