### ISSUE TITLE
Editor show wrong error: variable "already defined" in if/else

### ISSUE THREAD

**Issue by WiliTest** [Tampermonkey/tampermonkey#972]
if [this condition is true] set `var A` to `XXX` else set  `var A` to `YYY`. 

## Expected Behavior
the editor shouldn't show the error under `var A`  "already defined" 

## Actual Behavior
the editor think there is a mistake witth `var A` ("already defined"). (But the script works as expected but the editor should not show an error)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

            if (URLstripped.includes('wikipedia')){
                URLstripped='wiki/'
                var html = 'XXX'
                                                 } else {

               var html = 'YYY'
                                                 };

**Comment by derjanb** [comment]
Please see:

https://stackoverflow.com/questions/11532072/defining-javascript-variables-inside-if-statements

and if necessary disable this eslint rule:

https://eslint.org/docs/2.0.0/rules/no-redeclare
