### ISSUE TITLE
Add keyboard shortcut to toggle Tampermonkey menu

### ISSUE THREAD

**Issue by achernyakevich** [Tampermonkey/tampermonkey#973]
## Expected Behavior

Tampermonkey should provide support of keyboard shortcut to open Tampermonkey menu and navigate in the menu using keyboard.

## Actual Behavior

Tampermonkey provides possibility to add a menu item to call some functionality. Unfortunately at the moment it is accessible only by mouse click.

## Specifications

- any browser

## Script

It is not related to any script but related to  `GM_registerMenuCommand` command.

**Comment by derjanb** [comment]
![image](https://user-images.githubusercontent.com/767504/85905639-349c5380-b80c-11ea-9ebe-00e06a28d9fc.png)

Chrome automatically adds a "Activate the extension" shortcut. Will add this manually to the Firefox versions.

**Comment by alexanderchernyakevich** [comment]
@derjanb 
![image](https://user-images.githubusercontent.com/7402566/85981296-a59a6180-b9ec-11ea-980f-4c5af5b90e81.png)

Firefox as well provides some shortcuts configuration but it does not provide any for activation of Tampermonkey menu.

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.11.6115

**Comment by mklaber** [comment]
Where does did this screenshot come from? I'm struggling to find it in my settings — even with _Advanced_ enabled.

> ![image](https://user-images.githubusercontent.com/767504/85905639-349c5380-b80c-11ea-9ebe-00e06a28d9fc.png)
> 
> Chrome automatically adds a "Activate the extension" shortcut. Will add this manually to the Firefox versions.


It doesn't help matters that the `GM_registerMenuCommand ` docs only say:

> Please note that there are browser-wide shortcuts configurable to open Tampermonkey's popup-menu.

Configurable how? where?

**Comment by derjanb** [comment]
You can access this page at this URL: `chrome://extensions/shortcuts`
