### ISSUE TITLE
Very simple script(help/direction)

### ISSUE THREAD

**Issue by AtotehZ** [Tampermonkey/tampermonkey#975]
I know nothing about scripting. I usually use tampermonkey for finished scripts, so I can't fill out the template given, sorry.

I have a site that's behaving in an annoying way. creates a column on the left side dedicated to ads, even in full screen. I know how to find the value that creates the column and how to change it. I just don't know how to make a script do it.

It's a game I play with my young stepbrother, and on this site specifically it doesn't lag for him and he can use the bonuses they offer, unlike other sites hosting the game.

Here's the link:
http://shellshockersgame.com/play-shell-shockers

Here are some screenshots of the issue and the value that causes it:
![Shellshocker script1](https://user-images.githubusercontent.com/10325796/84154169-0de9c900-aa67-11ea-9a8e-803ef7147c3a.png)
![Shellshocker script2](https://user-images.githubusercontent.com/10325796/84154179-117d5000-aa67-11ea-91d4-efc3993d6e89.png)

I don't know what to do about it. What I was hoping was that a script could change that value every time I load the site.

I'm not sure I'm even asking in the right place and I'm definitely not asking the right way. I was just hoping someone would help out since I don't want to keep my stepbrother waiting.

If you want me to provide more info just tell me how. Or if you think the question should be asked elsewhere I'm open to suggestions too.

**Comment by O-AN-drew-O** [comment]
I wrote a script that should work

// ==UserScript==
// @name         shellshockersgame
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://shellshockersgame.com/*
// @require      https://code.jquery.com/jquery-3.1.1.min.js
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    $("#ad-160").remove()
    $("#iframe").css("width", "100%")
    setInterval(function(){
        console.log($("#div-gpt-ad-ShellShockers_TitleScreen").get(0))
        $("#div-gpt-ad-ShellShockers_TitleScreen").attr("style","display:none; visibility:hidden; position:absolute; top:-1000px;");
    },1)
})();

**Comment by AtotehZ** [comment]
Thanks a lot. Ill try it out when I get home.

**Comment by AtotehZ** [comment]
It worked perfectly. Thank you
