### ISSUE TITLE
"All modifications are only kept until this incognito session is closed!"

### ISSUE THREAD

**Issue by anonmon** [Tampermonkey/tampermonkey#978]
Tampermonkey was working fine until the latest updated version, now I get this every time I restart my browser, and the previously established way to turn this off in the security menu is completely missing. This isn't viable as my browser is set up to be in "incognito" mode as default and not running it like this screws with a ton of other stuff.

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.11.6115
