### ISSUE TITLE
Notification image doesn't change

### ISSUE THREAD

**Issue by CarlZA** [Tampermonkey/tampermonkey#982]
Hi All,

I'm trying to change the image on a GM_notification but can't get the image to change from the default Chrome one. Is this a known issue?

## Expected Behavior
The image on the notification should be what is set in the notification properties.

## Actual Behavior
The image is the default Chrome logo.

![image](https://user-images.githubusercontent.com/7535644/85164160-f31b0f80-b231-11ea-9d30-3183b98b107d.png)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
```js
// ==UserScript==
// @name        notify_image_not_working
// @match       https://github.com/Tampermonkey/tampermonkey*
// @grant       GM_notification
// ==/UserScript==

GM_notification ( {
    title: 'foo',
    text: '1',
    image: 'https://i.stack.imgur.com/geLPT.png'
} );
```

**Comment by derjanb** [comment]
Note: this is working fine on Windows

**Comment by jonnytest1** [comment]
seems to be fixed in the most recent update yes

**Comment by jonnytest1** [comment]
🤔 there seems to be a bug where the image resolution crashes after a while - restarting the browser helps however

**Comment by jonnytest1** [comment]
i did a bit of debugging and the condition that decides wther to use the default background image seems to be inverted

**Comment by derjanb** [comment]
> so it uses the default background image

Yes, and it does this when chrome.notifications.create failed e.g. with `Unable to successfully use the provided image.`

**Comment by jonnytest1** [comment]
yes and it saves the state for the next potentially completely different image

**Comment by derjanb** [comment]
Indeed. Will be fixed at the next release.

**Comment by derjanb** [comment]
Should be fixed at Tampmonkey BETA 4.13.6135 which is review now. In urgent cases please download the [crx](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6135.crx) and drag and drop it to Chrome's extensions page (chrome://extensions).

**Comment by jonnytest1** [comment]
you can also predownload the image to a base64url to prevent some loading errors :)
async function toDataURL(url) {
    return fetch(url)
        .then(r => r.blob())
        .then(async text => {
            return new Promise(res => {
                var reader = new FileReader();
                reader.onloadend = () => {
                    res(reader.result);
                };
                reader.readAsDataURL(text);
            });
        });
}

**Comment by pradipkhangaonkar** [comment]
you are making it very complicated, please make it simple that everyone can handle it easy. on single click.
