### ISSUE TITLE
safari 5?

### ISSUE THREAD

**Issue by mrkapqa** [Tampermonkey/tampermonkey#987]
Helli,

is there a BETA version for Safari 5?

Sorry for posting here,

remember finding somewhere something about it but could not remember where.

thank you

## Expected Behavior

play video with youtube-classic layout
## Actual Behavior

difficult to achieve

## Specifications

mac osx 10.6.8
safari 5.1.10

## Script

https://pastebin.com/ENYXrWwr

**Comment by derjanb** [comment]
Can you please check the version for Safari 6 from here: https://www.tampermonkey.net/index.php?browser=safari
It should (mostly) work with Safari 5.1 as well.
