### ISSUE TITLE
[Chrome] tampermonkey don't load script unless I disable and then enable the script

### ISSUE THREAD

**Issue by iron9light** [Tampermonkey/tampermonkey#988]
## Expected Behavior
Load script automatically for matched url

## Actual Behavior
Tampermonkey doesn't load script automatically.
After I disable and then enable the script manually, it works.
Tempermonkey for Firefox does not have this issue.

## Specifications

- Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
- TM: 4.10
- OS: Win10 pro 1909

## Script

https://gist.github.com/iron9light/155fb046393b504304b54a1e855715e6

**Comment by derjanb** [comment]
```JS
JSON.parse(ytplayer.config.args.player_response).captions
```

is missing. Not sure why, but this is not a Tampermonkey issue. Please contact the script developer.

https://stackoverflow.com/questions/42867732/getting-youtube-auto-transcript-from-api/42871347
