### ISSUE TITLE
Installed Scripts page doesn't load in Safari on macOS Big Sur

### ISSUE THREAD

**Issue by strafe** [Tampermonkey/tampermonkey#991]
## Expected Behavior
See a list of installed scripts.

## Actual Behavior
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15663890/86625444-fb5aa500-bfbc-11ea-99cf-acd47d9da9e9.png">

## Specifications

- Safari: 14.0
- TM: 4.10.6108
- OS: macOS 11.0 Big Sur

**Comment by Csineneo** [comment]
+1
Big Sur beta2

**Comment by jasonlakez** [comment]
Same issue here

- Safari: Version 14.0 (16610.1.15.51.6)
- System Version:	macOS 10.16 (20A4300b)
- TM: 4.10.6108

**Comment by derjanb** [comment]
Hmm, looks good here. (It took a while to install Big Sur, sorry.)

Does `tail -f Library/Containers/net.tampermonkey.SafariApp.Extension/Data/Documents/log.txt` or the JavaScript console show any errors?

![image](https://user-images.githubusercontent.com/767504/87335654-f2c81880-c540-11ea-953c-bab4282cd185.png)

**Comment by jasonlakez** [comment]
> Hmm, looks good here. (It took a while to install Big Sur, sorry.)
> 
> Does `tail -f Library/Containers/net.tampermonkey.SafariApp.Extension/Data/Documents/log.txt` or the JavaScript console show any errors?
> 
> ![image](https://user-images.githubusercontent.com/767504/87335654-f2c81880-c540-11ea-953c-bab4282cd185.png)

I would be accessible when the installed userscript is vacant, but if you install one, you would enter the loading loop

**Comment by derjanb** [comment]
@jasonlakez Can you tell me which one? I installed multiple script (i.e. [Webcomic Reader](https://github.com/anka-213/webcomic_reader)) and it worked.

**Comment by jasonlakez** [comment]
> @jasonlakez Can you tell me which one? I installed multiple scripts (i.e. [Webcomic Reader](https://github.com/anka-213/webcomic_reader)) and it worked.

I have [Facebook Purity](https://www.fbpurity.com/fbpurity.THRTY.user.js#bypass=true), [YouTubeAutoLiker](https://greasyfork.org/scripts/33865-youtube-auto-liker/code/YouTube%20Auto-Liker.user.js) and [AdsBypasser](https://adsbypasser.github.io/releases/adsbypasser.full.es7.user.js), tried one by one but didn't work out

**Comment by derjanb** [comment]
Thanks, meanwhile I found it... #778 is back... 🙄

**Comment by derjanb** [comment]
Sorry for the delay. Should be fixed at 4.11.6117.

Please make sure Safari is closed when the update is started.

**Comment by strafe** [comment]
Seems to be working now :+1:.
