### ISSUE TITLE
XMLHttpRequest CORS missing while it typed (GM_xmlhttpRequest not work)

### ISSUE THREAD

**Issue by Yusifx1** [Tampermonkey/tampermonkey#993]
Trying get some resources from another domain (domain.com and anotherdomain.com). it gives me 3 errors; 2 reason and 1 error message. All work great in greasemonkey, because it don't need `xhr.setRequestHeader("Access-Control-Allow-Origin", "https://some/url/");`  (I don't know how it possible without permission). When using same domain it accept it (without header it wont show allow origin). I can't use `GM_xmlhttpRequest` because it's not synchronous (tested and in documentation writen) and it won't run in function. Created another function that will call it but it say `Refused to connect to "some/link": URL is not a part of the @connect list` while I typed it. In new script `GM_xmlhttpRequest` runs without @connect list.

## Expected Behavior
Script get text from another domain

## Actual Behavior
giving [CORS Missing Allow Origin](https://developer.mozilla.org/ru/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)
then [CORS Did Not Succeed](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)
and final ERROR: Execution of script 'New Userscript' failed! A network error occurred.

PS. If I download extension for [CORS](https://addons.mozilla.org/ru/firefox/addon/cors-everywhere/) it works. But I can't say to download it to everyone (security reason).

## Specifications

- Firefox 78.0.1 64-bit
- TM:  4.11.6414
- OS: windows 10 LTSC

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.google.com/
// @grant        none
// ==/UserScript==
var url="https://some/url/to/another/domain.txt"
var xhr = new XMLHttpRequest();
xhr.open('GET', url,false)
xhr.setRequestHeader("Access-Control-Allow-Origin", "https://some/url/");
xhr.send()
alert(xhr.responseText)
```

**Comment by derjanb** [comment]
XMLHttpRequest has CORS capabilites at Greasemonkey because the script runs inside the extension's content script context. However, Chrome already removed that "feature" and IIRC Firefox will do so as well.
